### ISSUE TITLE
(SOLVED) "There was an error calling the Invidious API"

### ISSUE THREAD

**Issue by DocKDE** [FreeTubeApp/FreeTube#249] opened 2019-03-31 09:57 UTC
It seems in the 0.40 Beta there already were some problems with API call errors that have since been fixed. Still, I try to use Freetube 0.5.1 and whenever I search for videos I get the above error. I have two machines which both run Manjaro, one with KDE and one with Cinnamon. On the one with Cinnamon I have no problems, KDE, however, give me said problem. This occurs with the AppImage and the AUR package.
It seems to me, the problem is at my end but I'm at a loss how I might fix it. I'd be very grateful for any pointers here!

**Comment by linuxgirl22** [comment] 2019-04-01 03:24
I'm on Manjaro KDE (stable), using the appimage, and am not having any issues, so I think you're right that there's something happening at your end. All I see, with the latest 0.5.2 release, is a white box very briefly attempts to show, but it doesn't stop anything or slow down subscriptions from loading. 

Sorry, I'm not very tech, so can't suggest different KDE settings/hardware solutions, but if you get on the matrix/riot chat, the devs are great about responding with fixes.

**Comment by VaGNaroK** [comment] 2019-04-02 13:53
I'm having the right error when I import my youtube subscriptions via file. I'm using the flatpak version of the official flathub repository.

https://postimg.cc/YjqwCQTn

Any idea?

**Comment by linuxgirl22** [comment] 2019-04-02 21:01
The issue needs an internal fix. I can recommend going into the matrix/riot chat and asking there.

**Comment by PrestonN** [comment] 2019-04-02 21:32
Hey there.

@VaGNaroK I have left a response for your issue over at [#6](https://github.com/flathub/io.freetubeapp.FreeTube/issues/6#issuecomment-479037149).

@DocKDE In order to figure out the exact issue, I'll need a little bit of extra information.  You can open up the dev console by hitting `Alt` on your keyboard and clicking on `Open Developer Tools`.  In the opened window, you should see a button called `console` at the top.  Click on that and we should be able to view the exact error message given.  There should be an object near the error message that can be expanded on that includes the message returned by Invidious.

I think in the future the error messages needs to be a little bit more descriptive in order to help troubleshoot this issue.  I'll be sure to include that alongside whatever the next release is.

Hopefully the instructions don't seem too complicated to follow.  If you're having trouble finding the error message you're welcome to chat with me on the Matrix server as @linuxgirl22 mentioned.

**Comment by DocKDE** [comment] 2019-04-03 15:31
@PrestonN 
Thank you for replying. Indeed, the console gives me a "parsererror". I typed "how to do stuff" in the search field and freetube tried calling "https://invidio.us//api/v1/search/?q=how%20to%20do%20stuff&page=1&sort_by=relevance&date=&duration=&type=all". When pasted into my browser this just calls invidio.us and not the search terms I typed. I'm not sure if this is expected behaviour.
There is also an object just above the parsererror but pasting it in here will take ludicrous amounts of space and the formatting is weird. Could you maybe tell me exactly what would be of interest? Otherwise, I can try screenshotting the thing.

**Comment by PrestonN** [comment] 2019-04-03 15:41
The issue is found in the URL.  We have 2 forward slashes after the main URL.  If we remove one of them, the URL will return the information expected.

https://invidio.us/api/v1/search/?q=how%20to%20do%20stuff&page=1&sort_by=relevance&date=&duration=&type=all

I believe the reason you are having this problem is because your "custom Invidious instance" is set to https://invidio.us/.  Try removing the forward slash to the instance in your settings and your issue should be fixed.

**Comment by DocKDE** [comment] 2019-04-04 15:30
Huh, what do you know? Works like a charm. Thanks a bunch! Now I can finally roam Youtube without being tracked doing it :)

**Comment by PrestonN** [comment] 2019-04-04 17:00
Great!  Glad that worked for you.  I'll try to have a fix for this in the next release to prevent future users from experiencing the same thing.  Closing this issue as the problem has been fixed.

**Closed by PrestonN** 2019-04-04 17:00 UTC

**Comment by DanielValahul** [comment] 2019-05-22 16:11
Hello, the problem seems to have returned to me. My instance is https://invidio.us but I get the "There was an error calling the Invidious API".  Am i missing something with those slashes?
