### ISSUE TITLE
Remove shown videos Youtube wide (subscriptions/trending etc) based on title keywords.

### ISSUE THREAD

**Issue by bob808** [FreeTubeApp/FreeTube#1184] opened 2021-04-09 03:36 UTC
**Describe the solution you'd like to see implemented**
I'd like a setting where I could write certain keywords that if contained in video titles (maybe even video description) those videos wouldn't be shown in whatever list I'm looking (eg. subscriptions list).

**Describe alternatives you've considered**
Are there other ways to solve the problem? Please give a clear and concise description of any alternative solutions or features you might have considered.

**Screenshots**
Sometimes people have screenshots from mock-ups or other projects. Add them here.

**Additional context**
Add any other context about the feature request here.

**Comment by GilgusMaximus** [comment] 2021-04-09 15:11
Duplicate of #1070

**Closed by GilgusMaximus** 2021-04-09 15:11 UTC
Labels: enhancement
