### ISSUE TITLE
Video resolution is always automatic and doesn't stick to what it's told to stay on

### ISSUE THREAD

**Issue by Araly** [FreeTubeApp/FreeTube#1082] opened 2021-03-02 18:40 UTC
**Behavior of the program**
When watching a video, it will often and regularly fall back on a very bad video resolution. When I choose 1080p (or whatever the better is for a video), it stays on the low resolution for a while (I think because it keeps what it already loaded with the horribly bad resolution. After a while, it will finally play the video at the expected resolution, only to, later fall back again to the lowest resolutions. This causes some videos to be unviewable, because I can't read the text (in my case, sheet music). I tried going back and playing the video again, but the same issues will happen at some other point of the video, or sometimes even the same point.

Also, related issue is that when I click on a resolution in the little gear icon resolution list, sometimes the right resolution will light up, sometimes it won't. Sometimes it will light up several resolutions. 

![image](https://user-images.githubusercontent.com/24990801/109697312-f1a63300-7b85-11eb-9596-1fe88733b614.png)

I know I have the required internet speed to play those videos at the resolution I want (it works fine on normal youtube)
 
**Expected behavior**
I'd expect videos to change resolutions only when the "auto" resolution is selected, and to keep on the resolution selected, even if it means pausing sometimes. I'd also expect that when I click on a resolution option in the gear icon list, it lights up the right resolution, and doesn't light up any other of the options.

**To Reproduce**
There's not really any specific steps aside from "watch a video", and play with the resolution options.

**Environment Information (please complete the following information):**
 - OS: Manjaro
 - OS Version: rolling, kernel 5.10
 - FreeTube version: 0.11.3
 - Installation Method (If applicable): pacman
 - Primary API Used: Local API

**Comment by PrestonN** [comment] 2021-03-02 18:45
This is a duplicate of #791

**Closed by PrestonN** 2021-03-02 18:45 UTC
Labels: bug
