### ISSUE TITLE
Setting for quality of backup video format

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#1508] opened 2021-07-08 19:29 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Some videos seem only to be available in certain video formats (e.g. legacy) or qualities (e.g. 480 or 720p) and it seems that Freetube is not choosing the highest possible option.

**Describe the solution you'd like to see implemented**
There are two potential solutions:
1. Freetube should pick the option that is nearest to the chosen option (e.g. 720p, if 1080p is not available but is the chosen option).
2. Offer a second quality setting as backup.

**Describe alternatives you've considered**

-

**Screenshots**

-

**Additional context**

-

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-08 20:02
related to https://github.com/FreeTubeApp/FreeTube/issues/595

**Comment by GilgusMaximus** [comment] 2021-07-23 16:33
basically a duplicate of #595

**Closed by GilgusMaximus** 2021-07-23 16:33 UTC
Labels: enhancement
