### ISSUE TITLE
This video is unavailable in your country 

### ISSUE THREAD

**Issue by Joseph65** [FreeTubeApp/FreeTube#66] opened 2018-03-25 23:11 UTC
I know this is related to #34 but i don't know how to reopen issues
this issue is still present on version 0.2.0

**Comment by PrestonN** [comment] 2018-03-26 01:19
Hey there.  I believe the issue has to do with how FreeTube accesses youtube-dl.  It currently calls a Heroku server that does the request for the user.  Like I mentioned in #34, running youtube-dl locally on the user's system fixed this issue.  The problem with that is that youtube-dl did not work when I tested on Windows.  Because of this, I reverted this feature for 0.2.0.  I believe the reason is because of Windows typically not having Python installed.

I could change my releases where Linux uses youtube-dl locally and Windows does not, but that wouldn't solve the issue for Windows users.  I'd have to keep a separate branch for Windows builds as well.

I could change the region location of the server, but that won't guarantee that it will be fixed for everyone.

I could spin up multiple servers in multiple locations, but that would be extra costs that I'd rather not make.

This is something I need to think about for a little bit.  I want to get a nice solution for everyone and I'd rather not exclude features from users just because of their operating system.  I'll definitely start taking a closer look at this though.

**Comment by dimqua** [comment] 2018-03-26 02:16
> I believe the reason is because of Windows typically not having Python installed.

Is this a problem? You can ask users to install Python manually.

**Comment by PrestonN** [comment] 2018-03-26 02:34
I would consider this a problem yes.  I'd rather not add an extra barrier for Windows users to use the app.  I believe that it would reduce the amount of users willing to use FreeTube if that were the case.

Having said that, I did find [this](https://github.com/fent/node-ytdl-core).  I'm still in the early stages of testing it but it might solve all of the problems if this works.

**Comment by dimqua** [comment] 2018-03-26 02:44
Does youtube-dl required to python installed at all? It seems that [youtube-dl.exe](https://yt-dl.org/latest/youtube-dl.exe) works without it.

**Comment by PrestonN** [comment] 2018-03-26 02:47
From their website, it says that the Windows executable has Python bundled with it.  The NPM package that I used a while ago appears to not have it bundled.  The package that I just found seems to be a version that uses pure JavaScript, which would bypass the need to install Python.

**Comment by dimqua** [comment] 2018-03-26 02:50
Can't you use the Windows executable, in that case?

**Comment by PrestonN** [comment] 2018-04-05 03:41
I would have no way of interfacing with their executable to grab the information that FreeTube needs.  Even if I could, I believe that it wouldn't be a clean solution to do so.

For an update on this though, youtube-dl seems to be running locally on Windows using the package mentioned above which should fix this issue.  I will go ahead and close this issue for now.  If the issue persists when the next update comes around please make a new issue or open this one back up.  Thanks.

**Closed by PrestonN** 2018-04-05 03:41 UTC
Labels: bug

**Comment by snow-frog** [comment] 2019-01-13 07:00
I've had this issue running Freetube on Mint, and confirmed that i could indeed watch the video on the website
