### ISSUE TITLE
[Feature Request] Sort Videos by Published only

### ISSUE THREAD

**Issue by WandeingLagomorph793** [FreeTubeApp/FreeTube#685] opened 2020-10-17 18:07 UTC
**Important note**
Please check other open and closed issues for a similar feature request before proposing a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Is your feature request related to a usage problem (not a bug)? Please describe.**
With Invidious one of the ways that subscriptions are sorted is via Published, specifically lets say you subscribe to 5 channels and they recently uploaded, then it shows only the most recent video and not the rest below it. It's similar here but it'll also show the other channels videos as well, so those same 5 channels would show absolutely every video in their lineup.

**Describe the solution you'd like to see implemented**
I wouldn't mind seeing an option to sort subscriptions via their most recently published by channel, where it shows just the most recent. The current default shows that but shows the other videos from that same channel as well, which can make it cumbersome to sort if you have a ton of subscriptions or several profiles.

**Comment by GilgusMaximus** [comment] 2020-10-18 15:03
Closing because it is a duplicate of #546

**Closed by GilgusMaximus** 2020-10-18 15:03 UTC
Labels: enhancement
