### ISSUE TITLE
[Bug]: Wayland inhibit_idle

### ISSUE THREAD

**Issue by le-jun** [FreeTubeApp/FreeTube#3384] opened 2023-03-30 14:02 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Playing a video in FreeTube doesn't pause SwayIdle/SwayLock. The issue seems reproduced by at least [one other person](https://teddit.pussthecat.org/r/swaywm/comments/wd7ez5/how_to_make_swayidle_not_work_while_freetube_is/) who's been suggested some workaround.

### Expected Behavior

Apparently the issue could be resolved through your (dev) side by `inhibit_idle`, not competent enough to understand though. While a quick Googling gave me an answer, I thought it would make more sense for this bit of information to be linked to the repo.

### Issue Labels

usability issue

### FreeTube Version

v0.18.0

### Operating System Version

Debian 6.1.20-1 (2023-03-19) x86_64 GNU/Linux

### Installation Method

.AppImage

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-03-30 14:12
duplicate of #1369 and #3140
already fixed in #3286, you can use the nightly builds if you want this before the next release: https://docs.freetubeapp.io/development/nightly-builds

**Closed as not planned by absidue** 2023-03-30 14:12 UTC
Labels: bug, U: duplicate, B: usability

**Comment by absidue** [comment] 2023-03-30 14:19
The screen saver blocker should work properly after those changes, if it still doesn't work for you with those changes, I recommend checking the rest of your setup, the issue is likely outside of FreeTube, as it works correctly for other Linux users.
https://www.electronjs.org/docs/latest/api/power-save-blocker
