### ISSUE TITLE
Option to hide Recommended and Comments

### ISSUE THREAD

**Issue by gkeegan** [FreeTubeApp/FreeTube#152] opened 2018-08-14 02:53 UTC
An option to hide the "show comments" bar when viewing a video would be nice. Also removing the recommended from the page would be good, as very few people afaik think their recommendations are very good.

**Comment by PrestonN** [comment] 2018-08-20 14:09
Hiding recommendations is a duplicate of #42.  I will keep this open to track the hiding of comments however.  Both of these are planned for (hopefully) next release.

**Comment by PrestonN** [comment] 2019-08-08 19:45
With distraction free mode implemented, this request has been fulfilled and I will go ahead and close this issue.

**Closed by PrestonN** 2019-08-08 19:45 UTC
Labels: enhancement
