### ISSUE TITLE
Error: Status code: 410, after update to 0.15.1 on archlinux.

### ISSUE THREAD

**Issue by mrazster** [FreeTubeApp/FreeTube#1913] opened 2021-11-24 05:08 UTC
As the title says.
After update to 0.15.1 on archlinux with latest updates; I get the following messages:

```
Local API error: Error: Status code: 410
Falling back to Invidious API
```

I have tried to remove all installed files and configs and reinstall Freetube.
It also doesn't matter which Invidious server/instance I choose, this message persists.
But the videos load and play just fine.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-11-24 11:40
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1296

**Closed** 2021-11-24 11:40 UTC
Labels: bug, U: doesn't follow template

**Comment by peepopoggers** [comment] 2021-11-25 12:58
This is normally due to age-restricted videos being blocked. I am unsure why this happens even though they load in invidious. Its actually pretty weird. If you want to access an age-restricted video, open the video in invidious with the share icon.
