### ISSUE TITLE
[Feature Request]: Add option to select which region you are in

### ISSUE THREAD

**Issue by Sandyran** [FreeTubeApp/FreeTube#3528] opened 2023-05-12 16:37 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Certain videos on YouTube, select their language based on the region you are in. Some videos that are like this, are Mr Beast's videos. If you try to watch any of Mr Beast's videos in FreeTube, it will most likely give you the Arabic dub of the video. 
The problem, however, is that not all FreeTube users understand Arabic.

### Proposed Solution

Add option which lets you select which region you are in.

### Alternatives Considered

No alternative considered.

### Issue Labels

new feature

### Additional Information

I am aware that this might infringe on some of the privacy aspects of FreeTube. Issue #3423 may also have some similarities with this issue.

**Comment by absidue** [comment] 2023-05-12 18:27
duplicate of #2419

**Closed** 2023-05-12 18:27 UTC
Labels: U: duplicate, enhancement, E: new feature
