### ISSUE TITLE
[Feature Request]: Export subscriptions and history through command line

### ISSUE THREAD

**Issue by adinan-cenci** [FreeTubeApp/FreeTube#4295] opened 2023-11-07 20:36 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I have two computers I use, one during the week, the other in the week ends. I would like to have both synced.

### Proposed Solution
Currently Freetube allow us to export subscriptions and visualization history through its user interface.

I proposed exposing to the user a command to export said information through the terminal.

With this feature I could implement a shell script to help me sync both machines.

### Alternatives Considered

As an alternative, Freetube could perhaps expose a setting to configure in which directory those information are saved.
Then we could just point to a directory inside dropbox or similar service.

### Issue Labels

new feature

**Comment by absidue** [comment] 2023-11-07 22:18
The directory and the files are listed here: https://docs.freetubeapp.io/usage/data-location/

If you setup some kind of syncing system, make sure it only runs when FreeTube is fully closed and has finished doing it's database and cache cleanup after the last window is closed. Touching the files while FreeTube is running is not supported, if you still decide to touch them during runtime and lose data that is on you.

You will likely want to write a custom syncing solution that waits until FreeTube has fully shutdown or trigger your sync manually, instead of using off the shelf sync solutions that sync on every file modification, because as mentioned above messing with the files while FreeTube is running is not supported and may lead to data loss.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-09 16:54
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/192

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-09 16:54 UTC
Labels: enhancement, E: new feature

**Comment by gdh123** [comment] 2024-06-03 15:54
I created a script to backup automatically firefox and thunderbird profiles. I adapted it for freetube, therefore a bit messy.

what it does: check if a backup has been taken today, check if freetube is running
if both is no, it creates an archive of the freetube folder, save it locally, rsync it to a new location, delete the temp archive
the script auto delete the oldest entries and keep only the 4 most recent backups.
Also the script checks if a backup was successful in the last 30 days, else it will create a popup warning. The warning might be dependent on the OS/installed libraries, it shall work with Ubuntu/popos etc.

test the script:
create a file, ending with .sh
go to terminal ./scriptname.sh
see if the backup is working

if its working terminal:
crontab -e
add /30 * * * * /home/user/testsript.sh
script will be executed every 30 minutes


#!/bin/bash

# Konfiguration freetube
FREETUBE_PROFILE_DIR="/home/user/.config/FreeTube/"                       # Verzeichnis mit den Freetube-Profilen
NAS_DESTINATION="9-Backup/Freetube/autobackup/"                         # Zielverzeichnis auf dem NAS
#ENCRYPT_PASSWORD="1234"                         # Passwort für die Verschlüsselung
PROFILE_FOLDER="/home/user/.config/FreeTube/"


# Aktuelles Datum und Uhrzeit
DATE=$(date +"%Y_%m_%d_%H_%M")

# Heutiges Datum
TODAY=$(date +"%Y_%m_%d")

# Prüfe, ob heute bereits ein Backup gemacht wurde
if ls -d "$NAS_DESTINATION/freetube_backup_$TODAY"* > /dev/null 2>&1; then
    echo "Heute wurde bereits ein Backup durchgeführt. Das Skript wird beendet."
    exit 0
fi

# Zielverzeichnis auf dem NAS
REMOTE_DIR="$NAS_DESTINATION"

# Überprüfe, ob Freetube läuft
if ps aux | grep -v grep | grep freetube > /dev/null; then
    echo "Freetube läuft. Das Backup wird nicht durchgeführt."
else
    # Suche nach dem Profilordner mit "default-release" im Namen
    

    # Überprüfe, ob ein passender Profilordner gefunden wurde
    if [ -z "$PROFILE_FOLDER" ]; then
        echo "Es wurde kein Profilordner gefunden, der 'profiles.db' im Namen hat. Das Backup wird nicht durchgeführt."
    else
        # Archiviere und verschlüssele den Backup-Ordner -mx= kompression, 9 höchste,1 geringeste #-p $ENCRYPT_PASSWORD
        7z a -mhe=on -mx=2 -mmt=on -ssc- -t7z "$HOME/freetube_backup_$DATE.7z" "$PROFILE_FOLDER"

        # Kopiere die neuesten Backup-Dateien auf das NAS
                rsync -avh --progress "$HOME/freetube_backup_$DATE.7z" "$REMOTE_DIR"

        # Protokolliere die Aktion
       # echo "Freetube-Backups wurden am $DATE auf das NAS kopiert." >> "$HOME/freetube_backup.log"
	rm "$HOME/freetube_backup_$DATE.7z"

        # Zähle die Anzahl der Backups auf dem NAS
        BACKUPS_COUNT=$(find "$NAS_DESTINATION" -type f -name "freetube_backup_*" | wc -l)


        # Lösche ältere Backups auf dem NAS, wenn mehr als 4 vorhanden sind
        if [ "$BACKUPS_COUNT" -gt 4 ]; then
            OLDEST_BACKUPS=$(find "$NAS_DESTINATION" -type f -name "freetube_backup_*" -printf '%T@ %p\n' | sort -n | head -n -4 | awk '{print $2}')
            rm -r $OLDEST_BACKUPS
            echo "Ältere Backups wurden gelöscht, um sicherzustellen, dass mindestens 4 Backups vorhanden sind."
        fi

        # Überprüfe, ob das letzte Backup vor mehr als 30 Tagen durchgeführt wurde
        LAST_BACKUP=$(find "$NAS_DESTINATION" -type f -name "freetube_backup_*" -printf "%T+\t%p\n" | sort -r | head -n 1 | cut -f 1)
        LAST_BACKUP_DATE=$(date -d "$(echo $LAST_BACKUP | cut -d '+' -f 1)" +%s)
        CURRENT_DATE=$(date +%s)
        DAYS_DIFF=$(( ($CURRENT_DATE - $LAST_BACKUP_DATE) / (60*60*24) ))

        if [ "$DAYS_DIFF" -gt 30 ]; then
            zenity --warning --text="WARNUNG: Das letzte Freetube-Backup wurde vor mehr als 30 Tagen durchgeführt! Freetube muss geschlossen sein. Manuelles antriggern in Konsole ./.profile_backup_FT.sh"
        fi
        
    fi
fi
