### ISSUE TITLE
[Bug]: Some 1080p videos have a poor quality image for the first few seconds

### ISSUE THREAD

**Issue by rjdg14** [FreeTubeApp/FreeTube#5784] opened 2024-10-03 08:35 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1: Go to a random popular video with a resolution of 1080p or higher
2: The video may start at a blurry low resolution quality in 1080p mode before its picture becomes like how it should be a few seconds later
3: Some of these videos also have segments in 720p mode where the video briefly glitches to a green screen.

### Expected Behavior

The video should start with its regular 1080p quality.

### Issue Labels

API issue, inconsistent behavior, visual bug

### FreeTube Version

v0.21.3 Beta

### Operating System Version

macOS Sequoia 15.0

### Installation Method

.dmg

### Primary API used

Local API

### Additional Information

The problem seems to primarily affect monetised videos from what I can tell. It also seems to occur inconsistently - a video might have the problem initially and then when viewed at a later time doesn't.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-03 08:43
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5564

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-03 08:43 UTC
Labels: bug, B: visual, B: inconsistent behavior, B: API issue
