### ISSUE TITLE
Autoplay wording in German is too long for the available space

### ISSUE THREAD

**Issue by Zerotask** [FreeTubeApp/FreeTube#1366] opened 2021-05-28 20:38 UTC
**Behavior of the program**
For the German language the wording is too long for the available space.

**Expected behavior**
There is enough space

**To Reproduce**
Go to https://youtu.be/emIsJ-czz5I

**Screenshots**
![image](https://user-images.githubusercontent.com/20150243/120039372-14b97500-c005-11eb-8029-dd38bf6ecdf6.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: v0.13.0 Beta
 - Installation Method (If applicable): exe (x64)
 - Primary API Used: Default
 - Resolution: 1920x1080

**Comment by GilgusMaximus** [comment] 2021-05-31 10:54
This happens for basically most language:
Example of finnish:
![image](https://user-images.githubusercontent.com/34301369/120182939-574e9d80-c20f-11eb-9463-6b647bc4ac0c.png)

**Comment by ChunkyProgrammer** [comment] 2021-08-17 15:28
duplicate of #1300

**Closed by ChunkyProgrammer** 2021-08-17 15:28 UTC
Labels: bug
