### ISSUE TITLE
Allow to hide new version banner

### ISSUE THREAD

**Issue by PeterDaveHello** [FreeTubeApp/FreeTube#1691] opened 2021-09-12 08:38 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**

I know that v0.14.0 is out and I've tested it, but bug like https://github.com/FreeTubeApp/FreeTube/pull/1658 made me rollback to v0.13.2, then I have to see and close the new version banner by click the ❌ button every time I open this app, even though I already got it.

**Describe the solution you'd like to see implemented**

Have a button to "hide" the banner for current notice version

**Describe alternatives you've considered**

Maybe once the link or ❌ button was clicked, the banner could automatically been hidden.

**Screenshots**

![image](https://user-images.githubusercontent.com/3691490/132979768-8ef98529-7288-4ef8-ae67-fdca45d2d8c4.png)

**Comment by toby63** [comment] 2021-09-12 13:14
You can already hide that banner in the options.
But I guess you would like to be notified one time and then it should be disabled, until there is a newer version?

**Comment by PeterDaveHello** [comment] 2021-09-12 16:09
@toby63 you're right, I want to be notified and then I can decide to hide it. Thanks.

**Comment by ChunkyProgrammer** [comment] 2021-09-12 17:52
Duplicate of #1375

**Closed by ChunkyProgrammer** 2021-09-12 17:52 UTC
Labels: enhancement

**Comment by PeterDaveHello** [comment] 2021-09-13 05:50
Thanks @ChunkyProgrammer
