### ISSUE TITLE
[Bug]:  Freetube becomes a haitian quake simulator

### ISSUE THREAD

**Issue by JohnSmith25** [FreeTubeApp/FreeTube#3853] opened 2023-08-06 15:40 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

At random moments Freetube completely refuses to playback the video and instead becomes a haitian quake simulator. Temporary workarounds for this is to play a next video or restart Freetube. It has become really annoying since it happens frequently but at random times for me.

### Expected Behavior

That it the plays the video as it is. 

### Issue Labels

content not loading

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Xubuntu 22.04

### Installation Method

.AppImage

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-08-06 16:31
Can you reproduce this on the latest nightly build?

**Comment by aleksejrs** [comment] 2023-08-10 17:31
Do you mean some part of the UI is shaking?

**Comment by Winterhuman** [comment] 2023-08-10 20:56
This is likely a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1442. It's because the video element doesn't have a set height and becomes empty when there's no video to fill it, but, FreeTube tries filling it repeatedly which causes the height to rapidly change

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-08-10 21:00
Ah you're right @Winterhuman after reading this again it does sound allot like that issue

**Comment by JohnSmith25** [comment] 2023-08-11 01:35
> Ah you're right @Winterhuman after reading this again it does sound allot like that issue
> 
> @JohnSmith25 is this [#1442 (comment)](https://github.com/FreeTubeApp/FreeTube/issues/1442#issuecomment-946151192) the thing ur seeing?

Yes exactly this is what happens to me. But I don't know how to exactly reproduce this bug, it happens at random to me. Sometimes the video loads  fine on my end and sometimes it gets broken.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-08-11 05:54
Read more about the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds) here.

I'll will be closing this as u confirmed this is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1442

**Closed** 2023-08-11 05:54 UTC
Labels: bug, U: duplicate, B: content not loading
