### ISSUE TITLE
[Feature Request]: Need Confirm Age Warning or Ability to Bypass

### ISSUE THREAD

**Issue by Wajinn** [FreeTubeApp/FreeTube#6372] opened 2024-12-13 11:57 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

FreeTube unexpectedly fails when encountering videos that need age confirmation. 

### Proposed Solution

Player should have the ability to recognize such videos and give user proper warning why it can't be played. Additionally, player should allow some further actions, like ability to run personal script, skip, etc...

### Alternatives Considered

Other alternatives not observed as possible with present player.

### Issue Labels

new feature

### Additional Information

N/A

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-13 12:19
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/6243 and proper messaging has already been implemented. That will be part of the next release.

**Closed as completed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-13 12:19 UTC
Labels: U: duplicate, enhancement, E: new feature
