### ISSUE TITLE
Main window is blank in OS X El Capitan

### ISSUE THREAD

**Issue by harrydevs2021** [FreeTubeApp/FreeTube#1876] opened 2021-11-05 12:17 UTC
The main window is blank upon start, and clicking any of the buttons, eg., Subscriptions, Tending, doesn't populate the main window with any videos.

OS: OS X El Capitan 10.11.6
Installation: .dmg from GitHub
Version: 0.15.0

<img width="1198" alt="Screen Shot 2021-11-05 at 12 12 26" src="https://user-images.githubusercontent.com/88600467/140508497-ef439d11-7231-4305-9aee-1d84efd23cf3.png">

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-11-05 12:57
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1689

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-11-05 12:57 UTC
