### ISSUE TITLE
[Feature Request]: Actual Isolated profiles

### ISSUE THREAD

**Issue by IkelAtomig** [FreeTubeApp/FreeTube#5531] opened 2024-08-05 11:42 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently the profiles mechanism in FreeTube is confusing, it is more of a sort/filter option than actually acting as profiles that undermines privacy of the user a lot.

### Proposed Solution

Implement profiles isolated from each other like Chromium browsers, Separate subscriptions, feed and history. Ask which to load during opening automatically or ask every time during start.

This way, User could use VPN for separate profile and for the other without VPN. Actually isolating.

### Alternatives Considered

This could be done by running FreeTube via AppImage and Flatpak separately in case of Linux or use the PWA port of FreeTube project in docker container which could be loaded with firefox containers to isolate them for other OSes.

### Issue Labels

improvement to existing feature

### Additional Information

If this were to be implemented there should be an option which profile to be used if in case a YouTube video is opened using features such as "Open in FreeTube" via other things such as Browser extensions.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-08-05 12:14
Duplicate of #1996

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-08-05 12:14 UTC
Labels: enhancement, E: improvement existing feature
