### ISSUE TITLE
[Bug]: The video player glitches

### ISSUE THREAD

**Issue by NikNikovsky** [FreeTubeApp/FreeTube#5452] opened 2024-07-23 17:43 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I was just watching a video on a playlist, and this happened.
(Epilepsy warning)

https://github.com/user-attachments/assets/af5c7c28-1bf0-4835-902f-169fe71ae838

### Expected Behavior

The video was supposed to play.

### Issue Labels

content not loading, feature stopped working, visual bug

### FreeTube Version

0.21.1 beta

### Operating System Version

Windows 11 23H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.21

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Zephiii** [comment] 2024-07-23 19:46
Noticing the same issue on macOS 14.5.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-23 21:18
duplicate of #1442

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-23 21:18 UTC
Labels: bug, B: visual, B: content not loading, B: feature stopped working

**Comment by FluffyRudy** [comment] 2024-07-24 16:56
Well its still glitchy, i am regretting that i update it to latest version.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-24 21:58
see https://github.com/FreeTubeApp/FreeTube/issues/5456 and [workaround](https://github.com/FreeTubeApp/FreeTube/issues/5456#issuecomment-2248897869)
