### ISSUE TITLE
(Privacy Redirect) YouTube Links Opening FreeTube Subscriptions Page Rather Than Actual Video

### ISSUE THREAD

**Issue by Lanklow** [FreeTubeApp/FreeTube#1690] opened 2021-09-12 05:01 UTC
**Behavior of the program**
When I click on a YouTube video link while the Privacy Redirect extension is installed, it will open FreeTube. However instead of opening the video in question; it just opens the FreeTube Subscriptions page. I've tried disabling "Invidious automatically play video on load", uninstalling the AUR package and installing the Flatpak, making FreeTube and the extension use the same Invidious instance, and trying a few different instances.

**Expected behavior**
Since I have Privacy Redirect installed and "Use FreeTube over Invidious when possible" is enabled, I expect that when YouTube video links are clicked; it will open the video in FreeTube.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Install the Privacy Redirect extension (https://github.com/SimonBrazell/privacy-redirect)
2. Open the extension's options
3. Enable Advanced>Invidious>"Use FreeTube over Invidious when possible"
4. click on YouTube video link, confirm "open app" prompt.
5. FreeTube will open the "subscriptions" page instead of the video from the clicked link

**Link to video**
(none of these formats work)
https://www.youtube.com/watch?v=dQw4w9WgXcQ
https://youtu.be/dQw4w9WgXcQ
https://youtu.be/dQw4w9WgXcQ?t=18

**Screenshots**
Will upload screenshots and logs upon request.

**Environment Information:**
 - OS: Arch Linux
 - OS Version: Latest
 - FreeTube version: 0.14.0 Beta
 - Installation Method: FlatHub
 - Primary API Used: Invidious API

**Comment by ChunkyProgrammer** [comment] 2021-09-12 17:58
Duplicate of #1061

**Closed by ChunkyProgrammer** 2021-09-12 17:58 UTC
Labels: bug
