### ISSUE TITLE
[Bug]: Local API Error - TypeError: Cannot read properties of null (reading 'reason')

### ISSUE THREAD

**Issue by phenty** [FreeTubeApp/FreeTube#5582] opened 2024-08-18 19:13 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Using Local API for video playback:
1. Goto any video and click to watch it
2. Video screen comes up but there is no player.
3. Message below say "Local API Error (Click to copy): TypeError: Cannot read properties of null (reading 'reason')"

### Expected Behavior

The video should play

### Issue Labels

content not loading

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.3 Beta worked until today

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-08-18 19:16
Duplicate of #5534

**Closed** 2024-08-18 19:16 UTC
Labels: bug, B: content not loading
