### ISSUE TITLE
Video quality isnt displaying the best quality after default setting

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#734] opened 2020-10-27 12:12 UTC
**Behavior of the program**
So my default video quality is 1080p. 
When i watch a video where the highest quality 720p is. 
The label is showing me that im watching it in 480p. 
The same goes for a vid where the highest quality is 360p. 
The label is showing me im watching the vid in 240p. 
The moment i want to change the quality to the highest setting so from 480p to 720p or 240p to 360p, quality of the vid doesnt change. 
What does happen is if u go back into quality settings u will notice that it is displaying 2 quality's selected.
I think the quality of the vids are playing correct but just the labels acting up weird.

**Expected behavior**
Video quality should be displayed correct in the quality setting

**To Reproduce**
0. Your default video quality should be 1080p in the settings
1. Go to https://youtu.be/Uk8ME2EdU8w (720p vid) or https://youtu.be/ZrtDBhI3MvE (360p link)
2. Click on 'video quality button'
3. U will notice that the label says u watching the vid in 480p or 240p
4. Click to correct to quality to highest possible so 720p or 360p
5. Quality of the video doesnt change
6. Click on video quality button
7. Notice that it now is displaying 2 qualitys selected

**Screenshots**
![Screenshot (18)](https://user-images.githubusercontent.com/73130443/97299882-910c8f80-184d-11eb-96d3-b30ef9129b54.png)

**Desktop (please complete the following information):**
 - OS: [win 10]
 - OS Version: [1909]
 - FreeTube version: [0.9.1]

**Additional context**

**Comment by Synkky** [comment] 2020-10-27 17:24
Possibly related to #595

**Comment by GilgusMaximus** [comment] 2020-10-28 10:28
Yes. Duplicate of #595. Also it is the roadmap for v0.10, therefore closing it

**Closed by GilgusMaximus** 2020-10-28 10:28 UTC
Labels: bug
