### ISSUE TITLE
Request: 32-bit windows version

### ISSUE THREAD

**Issue by budg3** [FreeTubeApp/FreeTube#133] opened 2018-07-14 17:46 UTC
Would be nice to have since hooktube dropped all support for channels, search etc and this seems to be the best option available to track channels and search videos without actually using youtube.

**Comment by PrestonN** [comment] 2018-07-15 02:58
This is sort of a duplicate of #115.

My stance hasn't changed since then.  I already have a lot of different versions that I have to support and I don't have the equipment or time to support 32 bit versions.  Having said that, it should be possible to make a build on your system if you'd like to try it (instructions also at #115).

If you're not able to / don't feel comfortable with building, [Invidious](https://invidio.us/) seems to be worth a look as a good alternative.

**Closed by PrestonN** 2018-07-15 02:58 UTC
