### ISSUE TITLE
Blacklist specific videos and/or keywords

### ISSUE THREAD

**Issue by Rabcor** [FreeTubeApp/FreeTube#1825] opened 2021-10-16 21:20 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Sometimes autoplay puts on videos I'd much rather have avoided. Othe times I'm searching for something but all I'm getting are irrelevant results of a similar kind (for example searching for a specific song but I only get live recordings when I want a studio one).

It'd be real nice to have an option to custom tailor the search and autoplay experience a bit better, my idea is to do so by blocking undesired results.

**Describe the solution you'd like to see implemented**
I would like to have the ability to blacklist specific things I don't want to see such as:
 - Specific videos (e.g. a menu option for "I do not want to see this video")
 - Specific channels
 - Specific keywords (titles only)
 - Specific keywords (tags only)

Content matching blacklist conditions should not show up in searches, browsing or the 'up next' recommendations, or just about anywhere.

**Additional context**
What I actually want is to be able to get rid of Live/Concert videos when I'm listening to music with autoplay on, it's annoying as all hell lol. There I am, just listening to some music and chilling, and then all of a sudden my music is replaced by a screaming crowd, not fun.

Being able to blacklist things on-demand would allow me to tailor my own experience nicely for any other corner cases of things I want and do not want to see and I'm sure a lot of other users would appreciate the ability to do so.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-16 21:57
Duplicate of #1070

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-10-16 21:57 UTC
Labels: enhancement
