### ISSUE TITLE
Add YouTube Account(s)

### ISSUE THREAD

**Issue by Blackhawke** [FreeTubeApp/FreeTube#5335] opened 2024-06-24 20:02 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I don't know if anyone here is familiar with the AndroidTV YouTube alternative app "SmartTube", but somehow, that app has managed to eliminate all of YouTube's ads and other annoyances just like FreeTube, but _maintain_ the ability of its users to log into their YouTube accounts.

### Proposed Solution

That would be a great feature to add to FreeTube if possible. It would eliminate the annoyances of trying to export/import subscription lists, etc.

### Alternatives Considered

.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-24 20:57
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2959

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-06-24 20:57 UTC
Labels: enhancement, E: new feature
