### ISSUE TITLE
[Feature Request]: Hide only fully-watched videos

### ISSUE THREAD

**Issue by terminal-root** [FreeTubeApp/FreeTube#4863] opened 2024-04-04 15:28 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The `Hide Videos on Watch` setting under `Subscription Settings` hides played videos from the `Subscriptions` page no matter what portion of the video is watched. This is desirable sometimes but not so for videos you're just taking a break on.

### Proposed Solution

Hide or provide and option to hide only fully-watched videos.

### Alternatives Considered

 - option to hide X%-watched videos
 - option to hide X-minutes-left videos

### Issue Labels

improvement to existing feature

### Additional Information

FreeTube v.20.0 Beta

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-04 17:48
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/609

This is basically the root issue that needs to be addressed.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-04 17:48 UTC
Labels: enhancement, E: improvement existing feature
