### ISSUE TITLE
Ability to block/hide channels.

### ISSUE THREAD

**Issue by dudeamax99** [FreeTubeApp/FreeTube#970] opened 2021-01-21 21:52 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
There are a few I dislike channels that will show up in "Up Next".

**Describe the solution you'd like to see implemented**
Ability to block/hide specified channels.

**Describe alternatives you've considered**
No good alternatives I can think of. 

**Additional context**
Don't show the channel anywhere unless it is directly opened by url or similar.

**Comment by PrestonN** [comment] 2021-01-21 22:13
Duplicate of #95

**Closed by PrestonN** 2021-01-21 22:13 UTC
Labels: enhancement
