### ISSUE TITLE
Videos Wont Load: Error 410 

### ISSUE THREAD

**Issue by serarr** [FreeTubeApp/FreeTube#1565] opened 2021-08-05 19:02 UTC
What i expected to happen was for the Age restricted video to  simply load in as it should 

What i did:
Copy-pasted the URL  from  the age-restricted video from Youtube 
Pasted it into the Freetube URL 
attempted to run it
It tells me that the local API wont work because Error 410, then it tells me that the Inviduous APi wont work because: Undefined

 -Using a PC ,
 -Latest windows 10 Version
 -Latest Free-tube Version 
 -Installed Via Zip 
 - Primary API is the Local API 

In addition: ive only used free-tube working once (and it worked, it was an age restricted video), afterwards ( several days later after i downloaded it) it would just not work, i tested it out on several videos which were age restricted (all of which were SFW)  aka they were falsely marked) , none of them worked,

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-08-05 20:34
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1296

@PrestonN @GilgusMaximus

**Comment by serarr** [comment] 2021-08-06 08:54
> Duplicate of #1296
> 
> @PrestonN @GilgusMaximus

for me its error 410, not 404,

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-08-06 09:27
Doesnt matter its still related to it.

See https://github.com/FreeTubeApp/FreeTube/issues/1563

**Comment by GilgusMaximus** [comment] 2021-08-06 18:11
Yes, we have come to the same conclusion

**Closed by GilgusMaximus** 2021-08-06 18:11 UTC
Labels: bug
