### ISSUE TITLE
[Feature Request]: Fix broken Favourites UI/UX

### ISSUE THREAD

**Issue by openforfuture** [FreeTubeApp/FreeTube#4897] opened 2024-04-07 21:27 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

v20.0 introduced playlists, which is a great step forward, however it made a lot harder to reach your Favourites than before: the new version just broke the usability of this feature.

**reach your latest favourites in v20.0**
1. click on Playlists
2. click on Favourites
4. scroll all the way down (!!!)
5. click on Load More Videos (if you have more than 100 videos) 
6. scroll all the way down (you might have to repeat the two steps before several times!!!)
7. you've (🤯 finally 🤯) reached your latest favourite videos: 3 visible + 1 cropped (!!!)

![image](https://github.com/FreeTubeApp/FreeTube/assets/99279367/90a99340-ebcf-4b95-864d-f26a5538c28b)

**reach your latest favourites in v19.x**
1. click on Playlists
2. you've reached your latest favourite videos: 8 visible + 4 cropped

![image](https://github.com/FreeTubeApp/FreeTube/assets/99279367/bf5951f8-4b0c-420b-a36f-2d80e5ae52bd)

### Proposed Solution

1. Since Favourites are kind of a "special playlist" and they have their own "quick buttons" to be added/removed, they should also have a dedicated button in the sidebar to reach them quickly, like it was before OR any playlist should be able to be added to the sidebar (in this case, by default, favourites should be added)
2. Add an option to reverse the order (most recent instead of oldest) & remember the selected order (without changing the favourite "real order" of course), in the case of favourites the stored order should already be "oldest first"
3. Add an option to visualise thumbnails in tiles, filling the entire screen (remembering it)

In this way it should be possible to fix all the issues:

**reach your latest favourites in the fixed version**
1. click on Favourites directly in the sidebar
2. you've reached your latest favourite videos: 8 visible + 4 cropped

### Alternatives Considered

-

### Issue Labels

improvement to existing feature

### Additional Information

Better prioritise adding the order option asap.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-07 21:48
Duplicate of #4870
#4594
#4708

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-07 21:48 UTC
Labels: enhancement, E: improvement existing feature

**Comment by Tombstone2K** [comment] 2024-04-14 10:58
The new UI completely breaks things. Maybe give an option between the new and the old (better) style of a grid. and maybe a toggle to have oldest to newest or newest to oldest.
