### ISSUE TITLE
[Feature Request]:  Remember my set playback speed

### ISSUE THREAD

**Issue by Leezan-1** [FreeTubeApp/FreeTube#6009] opened 2024-10-29 09:59 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The problem I am having is that I have set default playback speed to be 1x, and I want it that way. But when I am learning or from playlist. It is tedious to change the playback speed (to 1.5x)  again and again. 

### Proposed Solution

The playback speed changed in player may change my default speed. so next time i  play video, it would be 1.5x till i change it to 1.

### Alternatives Considered

YouTube keyboard shortcuts to it would be also easier and a plus.

### Issue Labels

ease of use improvement

**Comment by absidue** [comment] 2024-10-29 11:04
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2295

**Closed by absidue** 2024-10-29 11:04 UTC
Labels: enhancement, E: ease of use improvement
