### ISSUE TITLE
[Feature Request]: "Next Short" button or section

### ISSUE THREAD

**Issue by Victor239** [FreeTubeApp/FreeTube#4792] opened 2024-03-22 22:21 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

It's cumbersome to watch multiple shorts in a row from a channel. 

### Proposed Solution

Whilst TikTok uses an infinite scroll for their videos, a less addictive alternative would be to have a button, or a dedicated slot in the "Up Next" section which allows you to click on the next Short for the channel who's video you're currently watching a Short of. 

### Alternatives Considered

N/A

### Issue Labels

ease of use improvement, new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-03-25 15:57
This is basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/629

The play all would work per individual tab.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-03-25 15:57 UTC
Labels: enhancement, E: ease of use improvement, E: new feature
