### ISSUE TITLE
[Feature Request]: Automatic full window

### ISSUE THREAD

**Issue by superfreeman1989** [FreeTubeApp/FreeTube#5115] opened 2024-05-15 14:49 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Add an option to automatically launch video in full window mode:
<img width="129" alt="SCR-20240515-jvqo" src="https://github.com/FreeTubeApp/FreeTube/assets/15226945/c089fbaa-673c-4d46-9a4f-93d107d1b0e4">

### Proposed Solution

Add an option similar to this:
<img width="300" alt="SCR-20240515-jvys" src="https://github.com/FreeTubeApp/FreeTube/assets/15226945/9f956276-406e-4d8a-89b6-d8057cef628a">

### Alternatives Considered

Nothing I can think of...

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-15 15:32
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2756

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-05-15 15:32 UTC
Labels: enhancement, E: new optional setting
