### ISSUE TITLE
[Feature Request]: "Show Only Ungrouped Subscriptions"

### ISSUE THREAD

**Issue by Foroneus** [FreeTubeApp/FreeTube#2223] opened 2022-04-26 18:20 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Sorting different kinds of channels into different profiles can be tedious if you have a lot of subscribed channels.

### Proposed Solution

Add a "show only ungrouped subscriptions" option when editing profiles to filter out channels that have a profile that isn't the "All Channels" Profile.

### Alternatives Considered

None.

### Issue Labels

improvement to existing feature

### Additional Information

Right here in the "Other Channels" section would be the best place for it:
![image](https://user-images.githubusercontent.com/19240319/165365704-f29455c0-9f00-4bfa-81f0-47f5c4bd2f15.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-06-02 12:45
I actually think that this is not necessity when #1934 is implemented

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-10-16 07:51
Possible implementation: Filter shown in screenshot is based on the profile. If we want to utilize that we need to add a standard profile that can be called 'Unsorted Subscriptions' and if u add a subscription from this profile to the profile u want the subscription in it need to be removed automatically from the 'Unsorted Subscriptions' profile

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-09-10 16:29
basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/914

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-09-10 16:29 UTC
Labels: enhancement, E: improvement existing feature
