### ISSUE TITLE
[Bug]: Local API Error and falls back to invidious but fails to play video

### ISSUE THREAD

**Issue by liammcsh2008** [FreeTubeApp/FreeTube#6337] opened 2024-12-09 22:31 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click on a random video
2. Get an error message that says local API Error
3. Invidious results in [BAD_HTTP_STATUS: 403] YouTube watch session expired. Please reopen this video

### Expected Behavior

Videos should play normally

### Issue Labels

content not loading

### FreeTube Version

v0.22.0

### Operating System Version

Windows 11 23H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.22.0

### Additional Information

The following videos I tried to watch are affected.
https://www.youtube-nocookie.com/embed/uUpcfhju3Rc
https://www.youtube-nocookie.com/embed/h-mkMiheqhI
https://www.youtube-nocookie.com/embed/pHpLEW0MW4E

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-12-09 22:46
Duplicate of #6328

It's literally the pinned issue...

**Closed by absidue** 2024-12-09 22:46 UTC
Labels: bug, B: content not loading
