### ISSUE TITLE
[Bug]: FreeTube window has no title bar (the usual top most part of the window where you can drag it for example)

### ISSUE THREAD

**Issue by joyofdata** [FreeTubeApp/FreeTube#5193] opened 2024-05-30 13:33 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Just what the title says. The problem started about two or three weeks ago. I did not update FreeTube right before the issue started. Also I tried reinstalling the package - to no avail.

### Expected Behavior

Show window title bar.

### Issue Labels

usability issue

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Linux Mint 21.3

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.20.0 Beta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-30 13:42
Use f11, duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3220

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-05-30 13:42 UTC
Labels: bug, B: usability
