### ISSUE TITLE
Search / Go to URL doesn't show if diacritics are not missing

### ISSUE THREAD

**Issue by ovari** [FreeTubeApp/FreeTube#688] opened 2020-10-18 10:10 UTC
**Behavior of the program**
Does not find videos if the diacritics are missing.

**Expected behavior**
`matyas kiraly` should find `mátyás kiraly` into the `Search / Go to URL` field.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. In the `Search / Go to URL` field, type `matyas kiraly`.
2. The `Search Results` do not show any results.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - OS Version: 20 Cinnamon
 - FreeTube version: 0.9.0 Beta

Thank you

**Comment by PrestonN** [comment] 2020-10-19 13:48
Duplicate of #662

**Closed by PrestonN** 2020-10-19 13:48 UTC
Labels: bug
