### ISSUE TITLE
Very low quality on every video

### ISSUE THREAD

**Issue by MattRGX** [FreeTubeApp/FreeTube#836] opened 2020-12-06 22:00 UTC
**Behavior of the program**
Very low quality on every video i play. My settings are 1080p auto but each video i played from my subscription list is in 360p even less i think. With lots of pixels. Even if i try to change the quality (via the player options) during the video, it changes maybe after few minutes, sometimes doesn't change at all and stay very blurry.
Sometimes i succeed to get my video to 1080 but after few second goes back to 360p or even less.

I precise, i don't have any internet connection problem :)

**Expected behavior**

Video start straight in 1080 or at leat being able to change it to 1080 after the video has started

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any video in subscriptions menu
2. Click on any video
3. See error

**Screenshots**
------

**Environment Information (please complete the following information):**
 - OS: W10
 - OS Version: W10 1809
 - FreeTube version: v0.9.2-nightly-334 Beta
 - Installation Method (If applicable): exe
 - Primary API Used: Local API

**Additional context**

**Comment by GilgusMaximus** [comment] 2020-12-07 11:08
Closing because this is a duplicate of #595

**Closed by GilgusMaximus** 2020-12-07 11:08 UTC
Labels: bug
