### ISSUE TITLE
Memory hungry causing it to crash

### ISSUE THREAD

**Issue by TomasGutierrez0** [FreeTubeApp/FreeTube#4] opened 2018-03-03 16:50 UTC
I tried to play a really long video. As seen in the image below. The amount of memory the program was using started to increase steadily as the video was played. It only stopped after the OS slowed down because it started running out of memory and closed the program. It took only a few minutes for before using all memory available.

I did notice that RAM increase when watching several 10 minutes videos but it would go down from time to time. Between 200MB to 400MB.

Is this a limit/problem to electron?

I'm using Ubuntu 17.10
Kernel 4.13.0-36

![Task manager](https://user-images.githubusercontent.com/30012262/36936880-bfbc52f8-1f02-11e8-9783-293778b6d694.png)

**Comment by PrestonN** [comment] 2018-03-03 17:04
This sounds like it might be something with Electron, but I'll definitely have to play around with it more before I know that for sure.

During my testing, watching a typical 10 minute video will use around 200MB - 300MB of RAM.  I haven't tested running a bunch of videos at once but that could be something to do with it.  I'll let you know if I find something.

**Comment by TomasGutierrez0** [comment] 2018-03-03 17:38
Playing a 17 min video, memory usage would constantly stay between 190MiB - 200MiB. 
As soon as I played a 10 hour long video memory would go beyong 1GiB before I closed FreeTube. 
It looks like it loads the video into memory but the 17 min video didn't increase memory usage as it would stay between 190MiB and 200 MiB.

**Comment by PrestonN** [comment] 2018-03-03 18:47
Looking into it a little more.  Electron itself handles the downloading and storing the video within memory. I'll have to see what I can do in order to somehow control this, but keep in mind that more videos playing will use up more RAM.

Thanks for letting me know of this issue and I'll update here if I find anything.

**Comment by TomasGutierrez0** [comment] 2018-03-08 13:36
Hey.
Tested 0.1.3 and sometimes it works and sometimes it doesn't. I don't know why.

Green line is when I opened FreeTube and started playing a 10 hour video, the next one, orange I tried to play a different 10 hour video the memory usage raises a bit but seems to get cleaned then the blue line, I tried a different 10 hour video and that's when it stopped working, the last pink line is after I close freetube

![memory](https://user-images.githubusercontent.com/30012262/37153647-582decc4-22d5-11e8-9574-f61c84d737e8.png)

**Comment by LexHimself** [comment] 2018-05-22 16:49
My system tends to have a high memory usage when just opening firefox, and closing down applications at random to keep firefox running. 

Can you provide me with a link to a video that makes the app crash? Just to confirm it is not an issue on your side.

**Comment by TomasGutierrez0** [comment] 2018-05-25 23:17
@LexHimself https://youtube.com/watch?v=U9IcBxFlE_s
after a while try loading another one like this https://youtube.com/watch?v=1PIhqTrL4GA

I downloaded 0.2.1 and it would start adding up. Ended up using 3GB+ of RAM but after that, the video stopped playing and RAM went down to 210MB and continued to play. RAM stayed between 210MB and 215MB.

**Comment by LexHimself** [comment] 2018-05-26 04:15
Tried both on the latest release. Nothing shows up on the first vid. 
the second however makes my CPU spike to 64% total, memory increasing rather fast. Reproduced on Arch Linux.

**Comment by K06RA** [comment] 2018-07-23 00:06
I couldn't reproduce this issue on my laptop as well.

**Comment by PrestonN** [comment] 2019-08-08 19:31
This hasn't been brought up again in a very long time, so I believe it's safe to close this now.  If anyone sees an issue like this again please create a new issue.

**Closed by PrestonN** 2019-08-08 19:31 UTC
Labels: bug
