### ISSUE TITLE
Youtube links auto redirect instead of open in browser

### ISSUE THREAD

**Issue by ckorder** [FreeTubeApp/FreeTube#1117] opened 2021-03-15 15:42 UTC
**Youtube links auto redirect instead of open in browser**

Youtube video, playlist, channel  links appear in the video descriptions and comments, clicking them result for me in opening a browser window loading the clicked link.

Links to channels  or to specific videos get redirected to the invidious instance on websites.
That feature would be awesome for Freetube. 

https://youtube.com/channel/UCYPrd7A27nLhQONcCIfFTaA
https://youtu.be/eX2qFMC8cFo
https://www.youtube.com/watch?v=eX2qFMC8cFo
https://youtube.com/playlist?list=PLBhKKjnUR0XAIAK-HDMvwQ7sx5UXe9zeK

Filter for short and normal youtube links.

Left click would be load this video / channel / playlist in the current Freetube window, middle mouse click would be open this content within a new Freetube window. 

**Thanks for considering.**

**Comment by GilgusMaximus** [comment] 2021-03-17 12:20
This is definitely something important to add, and could be done by a new contributor. You'll only have to check whether link point to YouTube and if so, replace them with a link that points to the resource in FreeTube

**Comment by GilgusMaximus** [comment] 2021-03-18 12:05
Going through all issues I realized this is a duplicate of #811 
Therefore I am closing this issue

**Closed by GilgusMaximus** 2021-03-18 12:05 UTC
Labels: enhancement, good first issue
