### ISSUE TITLE
[Feature Request]: Support chapter loop

### ISSUE THREAD

**Issue by stdedos** [FreeTubeApp/FreeTube#5142] opened 2024-05-21 11:07 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

For video playlists, a user may want to loop a specific chapter

### Proposed Solution

On the chapter list, create a "loop" button, that will activate the "Loop Mode" (https://www.mrfdev.com/how-to-use-enhancer-for-youtube#:~:text=display%3A%20none%20!important%3B%0A%7D-,Loop%20mode,-When%20you%20want), with the start/end times set from the chapter

In the proposed way, a "generic" loop mode can be easily supported (Similar to https://www.mrfdev.com/enhancer-for-youtube)

### Alternatives Considered

:upside_down_face: 

### Issue Labels

ease of use improvement, improvement to existing feature, new feature

### Additional Information

- https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+chapter+loop
- https://docs.freetubeapp.io/: "loop" returns nothing

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-21 11:20
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1029

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-05-21 11:20 UTC
Labels: enhancement, E: improvement existing feature, E: ease of use improvement, E: new feature
