### ISSUE TITLE
[Feature Request]: Return YouTube Dislike

### ISSUE THREAD

**Issue by NeedsArt** [FreeTubeApp/FreeTube#2627] opened 2022-09-27 04:29 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

https://github.com/Anarios/return-youtube-dislike

### Proposed Solution

Use the api for dislikes

### Alternatives Considered

New pipe fork and revanced have this
Aswell as tube archivist

### Issue Labels

display more information to user

**Comment by absidue** [comment] 2022-09-27 07:10
duplicate of #1927

**Closed by absidue** 2022-09-27 07:10 UTC
Labels: enhancement, E: display more information
