### ISSUE TITLE
Video Window

### ISSUE THREAD

**Issue by deplorable76** [FreeTubeApp/FreeTube#1447] opened 2021-06-24 21:03 UTC
Win 10. Local API. V 13.1 beta. x64.exe.
The video window loads with only the bottom quarter at the top of the page. I can see the controls which do not function and have incorrect date and it can't be pulled down with sidebar. Closing and reopening has no effect on the problem, I just downloaded the program again after going months with not being able to see the chat on livestreams. I guess I'll do it again and put up with vast bugs rather than submit to google. This could be such an awesome app.

**Behavior of the program**
Please write a clear and concise description of what the bug is.

**Expected behavior**
Please describe clear and concise what you expected to happen.

**To Reproduce**
Please add all steps to reproduce the behavior:

**Link to video**
If you refer to a problem which occurs within a specific video, or a range of videos, please link at least one here.

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.

**Environment Information (please complete the following information):**
 - OS: [e.g. Windows, Mac, Ubuntu, Fedora, Arch, etc.]
 - OS Version: [e.g. Windows 10, Ubuntu 20.04]
 - FreeTube version: [e.g. 0.9.0, Nightly build?]
 - Installation Method (If applicable): [e.g. Portable, .exe, .deb, .AppImage, FlatHub]
 - Primary API Used: [Local API, Invidious API]

**Additional context**

**Comment by PrestonN** [comment] 2021-06-24 21:08
Duplicate of #1438

**Closed by PrestonN** 2021-06-24 21:08 UTC
Labels: bug
