### ISSUE TITLE
[Feature Request]: Use Set and Map instead of arrays where applicable 

### ISSUE THREAD

**Issue by jasonhenriquez** [FreeTubeApp/FreeTube#5001] opened 2024-04-22 18:38 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

We currently use arrays in many places where sets and maps would be far more performant. This is notable particularly for oft-repeated operations and collections of reasonable size (>50-100+).

### Proposed Solution

Replace arrays with the better-suited data structures of Set and Map for larger collections where searching is commonly done. This is overwhelmingly present in `store/modules`, so that can be considered the scope for this story, although I'd recommend checking any other one-off instances just in case.

### Alternatives Considered

None

### Issue Labels

improvement to existing feature

### Additional Information

Functionally dependent on #4428, since Maps and Sets are only reactive in Vue 3.

**Comment by absidue** [comment] 2024-04-22 19:30
I really don't think we need an issue open for something like this, considering that literally the only reason we haven't done it yet is because it's literally not possible at the moment and because it's so vague that'll we'll never be able to actually close it, because there will always be something that can be more optimised.

**Comment by absidue** [comment] 2024-04-22 19:46
This doesn't need investigation or action items, we especially don't need an issue open that is  worded in way that makes it sound like we chose to use inefficient data types when that couldn't be further from the truth.

**Closed** 2024-04-22 19:47 UTC
Labels: enhancement, E: improvement existing feature, PR/Issue: dependent

**Comment by jasonhenriquez** [comment] 2024-04-22 19:50
> This doesn't need investigation or action items, we especially don't need an issue open that is worded in way that makes it sound like we chose to use inefficient data types when that couldn't be further from the truth.

I'm not sure if the wording of the issue relates to whether the issue needs any investigation, but I will close the issue if it is causing an unexpected argument. I didn't expect this to be controversial.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-22 19:53
I think this suits https://github.com/FreeTubeApp/FreeTube/projects/10 more than our issue board

**Comment by absidue** [comment] 2024-04-22 20:01
Part of my problem with this issue is that you are misdiagnosing the cause of the performance problems. Vue's store is many times slower in dev mode than in production builds, Vue 2's reactivity is slow, especially noticeable in FreeTube because of the unreasonably large amount of items that we try to display on screen at the same time. I don't blame you for not knowing that, all of your PRs are UI stuff. Our core problem isn't bad data structures, it's bad UI.

**Comment by jasonhenriquez** [comment] 2024-04-22 20:07
I didn't think it was the root cause of problems, but I do think it's a minor improvement that could be made for things like large quantities of videos / playlist videos where we're doing search, targeted insertion, and targeted removal operations on them. I apologize that I misstated the importance, if I said something relating to the salience or degree in the issue description. That's my bad.

**Comment by absidue** [comment] 2024-04-22 20:17
Maps and Sets won't help much with the playlists, unless we finally get rid of the ability to add the same video to a playlist multiple times. They also don't address the fact that the reason those are slow in FreeTube is because we make those structures reactive, so there is added overhead to every single property access both during reading and writing.
