### ISSUE TITLE
I keep getting this error when trying to play a video and it keeps loading

### ISSUE THREAD

**Issue by Abdulee** [FreeTubeApp/FreeTube#753] opened 2020-10-31 20:41 UTC
**Behavior of the program**
After I click on a video and it is loading it, I get this error: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined  
The video keeps on loading then and never plays

I expect to have the video opened.

Please add all steps to reproduce the behavior:
1. Go to subscriptions or search for a video.
2. Click the video and you get this error.

-Arch Linux x86_64 
-Arch Linux latest updates
Freetube version 0.9.1
Release beta

The problem gets fixed sometimes after closing and reopening and it only occurs with local API not the indivious api tho once again indivious has its own problems it doesnt load subscriptions very well.

**Comment by PrestonN** [comment] 2020-10-31 20:43
Please look for existing issues before creating new ones.

This is a duplicate of #733

**Closed by PrestonN** 2020-10-31 20:43 UTC
Labels: bug

**Comment by Abdulee** [comment] 2020-10-31 20:56
Hi, I have looked the issue and the only thing mentioned there is that you have fixed the issue in the latest build however I am running the latest build through the AUR, tho it might not be maintained by you it just uses the latest .deb package released by you. So, I am not sure why this is still happening. Please look into it I can't seem to get the local API to work with videos.

**Comment by PrestonN** [comment] 2020-10-31 21:04
We post nightly builds that currently has the actual fix (Instructions for downloading are in the README), however the official release hasn't been created yet.  Once I make the official release (Builds are uploading as I type this), then the maintainers of the AUR will do what they need to get it up to date on their end.  If you don't want to wait, you're welcome to use a nightly build in the mean time.

**Comment by Abdulee** [comment] 2020-10-31 21:06
ok, my bad I thought you have fixed in the actual release.

**Comment by Abdulee** [comment] 2020-10-31 21:10
Is it possible for you to send me the link to a nightly build? (I can't seem to find it)

**Comment by PrestonN** [comment] 2020-10-31 21:59
I just released v0.9.2.  You can download the new builds directly from the website now.

**Comment by Abdulee** [comment] 2020-11-01 12:31
Thank you very much. I just installed the latest release .deb package and it works fast and flawlessly. Freetube app really is a gem. :100:
