### ISSUE TITLE
[Feature Request]: Unwatched videos date filter on sub page

### ISSUE THREAD

**Issue by PhilJbt** [FreeTubeApp/FreeTube#6039] opened 2024-10-30 13:08 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I find difficult to identify relevant unwatched videos from irrelevant videos amidst frequent uploads from active channels, resulting in missed content.

### Proposed Solution

Add a rolling date filter (e.g. up to 1 day/1 week/1 month dropdown menu, or a more precise slider) to limit unwatched video display to recent uploads. This will streamline the view and improve visibility of not yet seen content that the user is not yet aware of.
The value of this filter must be saved.

### Alternatives Considered

No alternative comes to mind.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-30 22:31
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3799

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-30 22:31 UTC
Labels: enhancement, E: new feature
