### ISSUE TITLE
[Feature Request]: Implement some form of cast feature, 

### ISSUE THREAD

**Issue by darkralts** [FreeTubeApp/FreeTube#2801] opened 2022-11-02 13:22 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

on regular youtube you can only cast by going to youtube.com/tv and they block it by default you need to change your useragent or get an addon that does it for you like https://addons.mozilla.org/en-US/firefox/addon/youtube-for-tv/

and even then you are still using youtube, not a very elegant solution for casting from Phone to Linux. 

if this is doable i would totally love and use this feature all the time,

i can understand if its not though, considering youtubes proprietary nature.  i would really prefer any solution that is at least elegant and easy to use,

### Proposed Solution

in simple terms,  i have a few ideas, and if you have any of your own that you think is good feel free to share as well!

i think the simplest solution would be the freetube cast companion app or something, as opposed to using the proprietary youtube apps cast button.

basically you open youtube on your phone in any manner you want, browser, proprietary app, vanced, newpipe, etc. doesnt matter as long as you can copy the url. 
then with freetube open on your pc at the same time, find a video and copy the url, or even better press share and open with freetube companion casting app. then it will say do you want to cast (video name) to (Device name)[dropdown menu if you have more than one freetube running]? YES NO

i genuinely think this would be pretty good,

another idea i had was to use newpipe. you might need to work together with the newpipe dev or something, but if newpipe has a cast to external client on local network button or something, it could be able to cast to freetube, regular youtube, or really any other client but specifically freetube in this case. i think that would be really nice too

id say those are the only ideas i would reccomend out of the ones i had, i had one about using the proprietary app but i dont think its FOSS enough..

### Alternatives Considered

the only real alternative as of now is to just search up the title or url yourself after looking at it on your phone.

or send yourself the url in element or something and click on it

or use the proprietary youtube.com/tv with the proprietary app/using youtube vanced

### Issue Labels

ease of use improvement, new feature

### Additional Information

basically, in other words, when i see a cool video on my phone, and id rather watch it on the big screen, i just want to make the transition process from phone to PC as easy and effort free as possible in the shortest amount of time possible.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-11-02 13:34
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/437

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-11-02 13:34 UTC
Labels: enhancement, E: ease of use improvement, E: new feature

**Comment by darkralts** [comment] 2022-11-03 08:46
its not a duplicate of #437. #437 is a request for freetube to be able TO cast TO TV's

i want external devices to be able to cast TO freetube. do you understand?

please read carefully,

its the other way around.

**Comment by absidue** [comment] 2022-11-04 10:52
Hi @darkralts
Yes this isn't a duplicate of the other feature request, however we won't be reopening it, as this is way out of scope of FreeTube. It would require loads of time and effort to implement this feature request and almost nobody would use it, so it's definitely not worth the time and effort needed to implement it.

**Comment by darkralts** [comment] 2022-11-04 19:53
i know people who would use it

**Comment by darkralts** [comment] 2024-09-29 02:22
i also think so, sure if its not implemented with the proprietary cast
thing, thats probably better in my opinion.

maybe there is a simple way to implement this that does not require loads
of time and effort to implement, and is not way out of the scope of
freetube. perhaps we are just thinking about this the wrong way, the wrong
approach to a solution to a what is basically a qol feature.

hmm, maybe there could be a better way to do this with an external program?

for example, all it would take to cast a video, would be to copy the link,
and paste it into the freetube search bar.

one could copy a link off of newpipe for example, open some simple app that
just pastes content into that search bar, and presses enter.

i do agree that the shoulder of development for this should not lie on the
freetube contributors, perhaps if i find someone willing to work with me on
it, i may sketch something up.

**Comment by darkralts** [comment] 2024-09-29 02:25
that is actually so true though chris, i totally feel you there about the
whole HDMI thing with a computer just to get ad free youtube. sometimes i
even use my phone with an OTG HDMI

**Comment by absidue** [comment] 2024-09-29 08:51
@chris-aeviator Have you considered getting a really cheap wireless keyboard and mouse and plugging the USB dongle into the Raspberry Pi? That would let you use FreeTube like normal and also use the Raspberry Pi for other things too.

**Comment by absidue** [comment] 2024-09-29 08:57
Also keep in mind that the Raspberry Pi 5 is not the best device for this sort of thing, considering that it only supports hardware decoding for HEVC/h265, which won't help you with YouTube because they do h264, VP9 and AV1. But it should be okay as long as you stick to lower resolutions and avoid things like HDR videos.
