### ISSUE TITLE
[Bug]: cant receive large amount of subscriptions anymore

### ISSUE THREAD

**Issue by wiiguy** [FreeTubeApp/FreeTube#5748] opened 2024-09-25 13:07 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

go to subscriptions
push refresh 
message : This profile has a large number of subscriptions. forcing RSS to avoid rate limiting
and now i get :
Your subscribed channels currently does not have any videos.

### Expected Behavior

normally i would see my videos

### Issue Labels

API issue

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Linux Mint 22

### Installation Method

.AppImage

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.3 Beta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-25 14:38
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5749

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-25 14:38 UTC
Labels: bug, B: API issue
