### ISSUE TITLE
Feature request: Use tags to organise/filter subscriptions and saved videos

### ISSUE THREAD

**Issue by avamk** [FreeTubeApp/FreeTube#25] opened 2018-03-08 16:55 UTC
Hello,

First of all, a huge thank you for creating such an useful and important program. This will greatly help protect a YouTube viewer's privacy.

I was going to suggest a playlists feature. However, I realised that a more flexible approach is to allow tagging of saved videos and filtering those videos based on tags.

The user can also tag their subscriptions and search for/filter their subscriptions based on tag.

What do you think?

**Comment by PrestonN** [comment] 2018-03-08 17:39
Hey there. I'm glad that you enjoy FreeTube. :)

 This sounds like a duplicate of #8 but correct me if I'm wrong.  If it is a duplicate then please close this issue.

To add to this, it sounds more like users would like multiple local "accounts" to switch between, where each have their own set of subscriptions and videos.  This should fulfil the "label" that is requested. Let me know on what you think and if you think this is a better idea or not.

**Comment by avamk** [comment] 2018-03-08 22:40
I just looked at #8 but I don't think they are the same. Having multiple local "accounts" or profiles would be nice, but I'm talking about a general organisational functionality where you create a set of tags that you use to tag everything from subscriptions to saved videos, etc. plus a general search UI where you can filter for a certain set of tags.

**Comment by PrestonN** [comment] 2018-03-09 00:23
Alright.  I understand the request now.

To be honest, I'd probably consider this a low priority feature.  I'd rather focus on some more core functionality right now but that doesn't mean I won't take a look at this in the future.

**Comment by K06RA** [comment] 2018-07-21 22:58
This seems like a really similar issue to #8. Maybe we could create a special freetube tag in the app, say FT. Then FT:Playlist:<playlist name> would be attached to every video in the playlist. Even better we could store tags/playlists in a local json file enabling the user to edit his tags if he wants to. 

For instance (pseudo-code):
![playlist-ft](https://user-images.githubusercontent.com/41452613/43040672-6f6c8ba6-8d39-11e8-8bfe-9133aa35be0c.png).

And then to show all the tags you just need to loop over the tags array, etc.

**Comment by PrestonN** [comment] 2018-07-22 02:43
> Even better we could store tags/playlists in a local json file enabling the user to edit his tags if he wants to.

This is essentially how I plan on doing this.  I already store subscriptions on the user's computer so including a user created tag along with that subscription in the database file won't be much of an issue.  Saved videos would be identical as well.

**Comment by throwaway847462** [comment] 2019-06-15 15:45
Is this coming out?
I want to ditch YouTube but it's missing playlists, the only feature I use on YouTube

**Comment by PrestonN** [comment] 2019-08-08 19:34
Subscription profiles will be included in the next release.  The functionality is already done and the new release is currently in testing.  Expect to see this very soon!

**Closed by PrestonN** 2019-08-08 19:34 UTC
Labels: enhancement

**Comment by toby63** [comment] 2022-01-06 16:46
I would still like this feature.

While profiles can be used for this, I don't think they are really intuitive.

With tags you could simply bookmark a video and add a tag to it, like "Music, Gaming, Howto, Tech, Cars" etc.
You can then simply search for the tags (related to #1942) or list them in the playlist.
When you click on them, all videos in that tag category are displayed.
