### ISSUE TITLE
[Feature Request]: Display auto-captions as full lines

### ISSUE THREAD

**Issue by spaceghost24** [FreeTubeApp/FreeTube#6049] opened 2024-10-31 04:35 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

In the previous version of freetube, each line of automatically-generated captions was displayed all at once. With the update (which looks great otherwise, by the way!), each word of the auto-captions now pops up individually. This is closer to how they work on Youtube, but actually makes the auto-captions much harder to use.

Captions are most useful when you can glance down when each new line of captions comes up, catch an entire sentence or sentence fragment, and then look back up and watch the video while they say what you just saw. This enhances understanding of the speech and/or visual content, because the captions provide context ahead of time of what's being said. If each word only shows up as it's being said, you have to either check the captions during every single word (and miss out on a lot of the video) or read the captions after they're said (which is confusing as it removes the benefit of having context during the visual content).

### Proposed Solution

The ideal solution in my opinion would be for automatic captions to be displayed in groups of two full lines, being replaced by the next group of two lines after both lines have "expired".

### Alternatives Considered

Each line appearing in full and "bumping up" the previous line, as the captions worked before, would also be preferable to each word being added on individually.

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-06 23:52
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5961

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-06 23:52 UTC
Labels: enhancement, E: improvement existing feature
