### ISSUE TITLE
[Bug]: The app goes blank while searching something

### ISSUE THREAD

**Issue by roXtar007** [FreeTubeApp/FreeTube#6490] opened 2024-12-31 19:55 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Frequently the app goes completely blank while I am trying to search something. The issue is not happening every time but is happening frequently.
![image](https://github.com/user-attachments/assets/d459ad30-6bd1-4c76-911c-6385cd4d7bd5)

https://github.com/user-attachments/assets/f54061a0-defa-4765-ae6a-46749cfa85b9

### Expected Behavior

The search should work normally.

### Issue Labels

usability issue, visual bug

### FreeTube Version

v0.22.1 Beta

### Operating System Version

Windows 11 Home Single Language

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-12-31 20:04
Duplicate of #6065

**Closed by absidue** 2024-12-31 20:04 UTC
Labels: bug, B: visual, B: usability
