### ISSUE TITLE
Scroll bar positioning when switching between sections

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#167] opened 2018-09-29 19:47 UTC
If you scroll to the bottom of one of the sections (subs, popular, favorites, history), changing to any of the other sections results in the section being scrolled to the last item.

Replicate
Select on of the sections, e.g. most popular.  Scroll to the bottom.   Switch to subscriptions and it will be displayed as scrolled to the bottom of the list.    This only appears to happen when you scroll to the bottom.  If you do the same and only scroll half way the above is not observed.

Expected behavior
Select on of the sections, e.g. most popular.  Scroll to the bottom.   Switch to subscriptions and it should be at the most recent item (scrolled to the top)

**Comment by rickndmorty** [comment] 2019-06-09 14:30
Easy to reproduce:
1) Go to Trending and scroll way down.
2) Go to Subscriptions and you'll find that you're scrolled down there too.

Please fix.

**Comment by PrestonN** [comment] 2019-06-14 23:57
I believe this has been mentioned before and it's something that I want to look at soon.  Because of the way FreeTube is structured, I'll have to store where you were scrolled on each page and return you to that position when you come back.  I don't have an ETA on when it will be fixed but please know that it's planned.

**Comment by rickndmorty** [comment] 2019-06-15 18:07
That would be great, please do it whenever it is possible! 👍

**Closed** 2020-09-29 19:46 UTC
