### ISSUE TITLE
[Bug]: back button removes search results

### ISSUE THREAD

**Issue by hboetes** [FreeTubeApp/FreeTube#4016] opened 2023-09-10 08:15 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Go to any channel, search that channel for something, watch video from the results, hit the back button.

And you are back at the main channel page.

### Expected Behaviour

Here I would expect to be back at the results page.

### Issue Labels

usability issue

### FreeTube Version

freetube-0.19.0-1.x86_64

### Operating System Version

linux

### Installation Method

.rpm

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

dna

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-09-10 08:56
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2446

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-09-10 08:56 UTC
Labels: bug, B: usability
