### ISSUE TITLE
[Feature Request]: Option to add custom profile image.

### ISSUE THREAD

**Issue by SentientBeingOnAQuest** [FreeTubeApp/FreeTube#4094] opened 2023-10-03 06:00 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

It's hard to imagine that this hasn't been suggested already, but I haven't been able to find anyone suggesting it. 
If it has then moderators feel free to delete this post. 

I would like to see the option to add custom images to my subscription profiles. 
The first letter of the profile name and a random colour doesn't really tell you anything useful. 

### Proposed Solution

Add the option to customize subscription profile images.

### Alternatives Considered

In the event that allowing users to upload their own photos is too difficult then just give users a set of icons to select from that are included in the default program. 

### Issue Labels

ease of use improvement, improvement to existing feature, visual improvement

**Comment by absidue** [comment] 2023-10-03 07:31
Duplicate of #1979

**Comment by absidue** [comment] 2023-10-03 07:31
Also for your information you can customise the colour on the profile edit screen.

**Closed** 2023-10-03 07:31 UTC
Labels: U: duplicate, enhancement, E: improvement existing feature, E: visual improvement, E: ease of use improvement

**Comment by aphaits** [comment] 2025-06-06 15:07
Would love to have this feature.

Possible custom image from either:
- Select one of the channels subscribed in the profile to set as profile image
- Select/upload image for custom thumbnail
- Custom Letter input / Emoji input
- Maybe some preset images, can be in combination with the letter/emoji input

**Comment by absidue** [comment] 2025-06-06 15:08
@aphaits You can already use emojis as the icon by putting an emoji at the start of the profile name.

**Comment by aphaits** [comment] 2025-09-18 00:37
> [@aphaits](https://github.com/aphaits) You can already use emojis as the icon by putting an emoji at the start of the profile name.

Oh neat! very useful. Too bad still can't use custom local images though.
