### ISSUE TITLE
[Bug]: New player makes whole app hang when it can't fetch video data

### ISSUE THREAD

**Issue by EvilGremlin** [FreeTubeApp/FreeTube#6460] opened 2024-12-27 09:10 UTC
### Describe the bug

If video stream/segment is unreachable for whatever reason (connection loss, network changed, youtube itself do not respond clearly) whole app stop reacting to any inputs, no other choice but to close it and relaunch.

### Issue Labels

causes crash, inconsistent behavior, usability issue

### FreeTube Version

v0.22.1 Beta

### Operating System Version

Ubuntu 24.04

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

old player

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-12-27 09:46
Already fixed by #6180 on the development branch and this issue is a duplicate of the issue that pull request closed.

**Closed by absidue** 2024-12-27 09:46 UTC
Labels: bug, B: usability, B: crash, B: inconsistent behavior
