### ISSUE TITLE
[Feature Request]: Change FreeTube Settings font size

### ISSUE THREAD

**Issue by filcode** [FreeTubeApp/FreeTube#2489] opened 2022-08-16 15:51 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

FreeTube Settings fonts on macOS are to big. It's not possible to change font size of FreeTube Settings for macOS.

### Proposed Solution

Add the ability to change the font size.

### Alternatives Considered

Decreasing UI Scale on Theme Settings allows to decrease FreeTube Settings font size, but decrease all fonts size in the app.

### Issue Labels

display more information to user, ease of use improvement, new feature, new optional setting, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-09-11 10:26
i consider this a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/39

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-09-11 10:26 UTC
Labels: enhancement, E: new optional setting, E: visual improvement, E: display more information, E: ease of use improvement, E: new feature
