### ISSUE TITLE
[Feature Request]: Put icons of favorite subscribers profiles on the upper bar!

### ISSUE THREAD

**Issue by CelularBat** [FreeTubeApp/FreeTube#4345] opened 2023-11-18 03:59 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There is a lot of empty space on the upper bar. Let's put there a placeholder for storing fav profiles, for quick switching.

[Empty space marked](https://i.ibb.co/pKvzqn5/freetube-demo.png)

### Proposed Solution

Visualisation:

https://i.ibb.co/XtPvQjz/freetube-concept.png

### Alternatives Considered

There is no alternative.

### Issue Labels

display more information to user, ease of use improvement, improvement to existing feature, new feature, visual improvement

**Comment by absidue** [comment] 2023-11-19 10:08
FreeTube supports a wide range of window and screen sizes, as well as zoom levels, which means that while there is a lot of empty space in your provided full screen/maximised window screen shot, on smaller window sizes there is a lot less and on narrow/phone screen sizes there is no spare space.

**Comment by jasonhenriquez** [comment] 2023-11-19 14:42
This is similar to #2871, but with pinning instead of showing all profiles. Personally, if we did add something like this, it would make the most sense as a collapsible list of profile bubbles above channels on the side nav, with pinning as a separate feature that modifies the default sort order.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-19 15:19
What about pinning profiles in the Profile Select menu?

**Comment by jasonhenriquez** [comment] 2023-11-19 15:32
That works as well, albeit a bit less in the same spirit of the OP (still takes another click to access). Duplicate of #987 if it's just about profile pinning, duplicate of #2871 if it's just about a better quick list for profiles

**Closed by jasonhenriquez** 2023-11-19 15:32 UTC
Labels: enhancement, E: improvement existing feature, E: visual improvement, E: display more information, E: ease of use improvement, E: new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-19 23:36
Testing duplicate workflow because it didnt trigger when jason used the keywords

Duplicate of #987 #2871
