### ISSUE TITLE
[Feature Request]: ability to modify and/or disable keyboard shortcuts

### ISSUE THREAD

**Issue by nick75e** [FreeTubeApp/FreeTube#3997] opened 2023-09-04 18:21 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

1. Play a video
2. Press arrow key to seek forward
3. Accidentally press the 0 key
4. Video starts over

### Proposed Solution

Show a list of the current shortcuts with the possibility to customise them or set them to empty.

### Alternatives Considered

Disable some/all shortcuts.

### Issue Labels

ease of use improvement, improvement to existing feature, new optional setting

### Additional Information

This issue is related to #992.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-09-04 19:01
Duplicate of #992 and #251

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-09-04 19:01 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: ease of use improvement
