### ISSUE TITLE
[Bug]: The playing in the window ""Picture-in-Picture"" does not resume

### ISSUE THREAD

**Issue by kit20a** [FreeTubeApp/FreeTube#5091] opened 2024-05-09 06:01 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1.  Play Video Youtube
2.  Click "Picture-in-Picture"
3.  Playing...
4.  Connection is interrupted (loss 3-5 pings)
5.  Video Stoping and not resume if conection is resumed after the failure (as Youtube app)

### Expected Behavior

Video resume Playing, when  conection resumed after the failure

### Issue Labels

content not loading

### FreeTube Version

v0.20.0

### Operating System Version

Windows 10

### Installation Method

Portable

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.20.0

### Additional Information

This bag in all versions FReeTube

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-10 10:04
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4159

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-05-10 10:04 UTC
Labels: bug, B: content not loading
