### ISSUE TITLE
[Feature Request]: Ability to highlight and copy subtitle text

### ISSUE THREAD

**Issue by ngoomie** [FreeTubeApp/FreeTube#4141] opened 2023-10-12 22:25 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I would like to be able to copy text in subtitles when watching content in languages other than my native one, so I can look up words I don't know more easily (especially helpful for learning languages where the writing system doesn't map cleanly or at all to the writing system). As it stands now any sort of clicking on the subtitles pauses the video. 

### Proposed Solution

It should be possible either by default or by toggling an option in the settings to highlight subtitle text without it being treated as interaction with the video player itself.

### Alternatives Considered

Transcripts (#3487) would be perfectly fine too if I could copy from those.

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by absidue** [comment] 2023-10-15 15:26
Duplicate of #3195

**Closed** 2023-10-15 15:26 UTC
Labels: enhancement, E: improvement existing feature, E: ease of use improvement
