### ISSUE TITLE
"Freetube" cannot be opened because it is from an unidentified developer

### ISSUE THREAD

**Issue by D4v1dH03** [FreeTubeApp/FreeTube#1943] opened 2021-12-13 22:14 UTC
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**
Please write a clear and concise description of what the bug is.

Freetube refuses to open and pops up "Freetube" cannot be opened because it is from an unidentified devloper

**Expected behavior**
Please describe clear and concise what you expected to happen.

Freetube opens normally

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Use macOS Monterey
2. Open freetube

**Link to video**
If you refer to a problem which occurs within a specific video, or a range of videos, please link at least one here.

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.
<img width="315" alt="Screenshot 2021-12-13 at 14 13 42" src="https://user-images.githubusercontent.com/81270448/145897383-c01078bb-35e2-47cc-823a-eb06b62601f8.png">

**Environment Information (please complete the following information):**
 - OS: [e.g. Windows, Mac, Ubuntu, Fedora, Arch, etc.]
 - OS Version: [e.g. Windows 10, Ubuntu 20.04]
 - FreeTube version: [e.g. 0.9.0, Nightly build?]
 - Installation Method (If applicable): [e.g. Portable, .exe, .deb, .AppImage, FlatHub]
 - Primary API Used: [Local API, Invidious API]
macos monterey 12.0.1
Freetube 0.15.1
DMG

**Additional context**

**Comment by rootedetc** [comment] 2021-12-14 00:01
Solution for opening it: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

The problem is however that upon each update the end user has to use the solution noted on the link above.
-- This is especially annoying for people that use "nightly" build from the actions section.

**Comment by D4v1dH03** [comment] 2021-12-29 06:14
Notarisation is really an issue. They require developers to pay $99 a year for the Apple Developer Program. **** Apple.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-12-29 13:13
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1520#issuecomment-881112252

**Closed** 2021-12-29 13:13 UTC
Labels: bug
