### ISSUE TITLE
[Feature Request]: play pause button size is big.

### ISSUE THREAD

**Issue by sudo-404-hub** [FreeTubeApp/FreeTube#6438] opened 2024-12-23 06:19 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

bro when we watch any study lecture and pause the video this pause button comes and don't even disapper and i can't see the text . it should fix bro. 
![image](https://github.com/user-attachments/assets/d2b1d22c-9b1a-4ead-acc7-9ae6cb6f9027)

### Proposed Solution

soultion 1 :  remove the pause button .
soultion 2 : pause button auto disapper after 2 sec of pause. 
don't set 5-10 sec man . 

### Alternatives Considered

?????/

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-23 07:57
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5951

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-23 07:57 UTC
Labels: enhancement, E: ease of use improvement
