### ISSUE TITLE
[Feature Request]: Play All

### ISSUE THREAD

**Issue by onkq** [FreeTubeApp/FreeTube#2561] opened 2022-09-10 13:02 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [ ] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I want a button on the channel page as NewPipe does. As I use FreeTube to listen to music. The button should play all the videos the channel has uploaded in order, like a playlist.

Sometimes clicking the lastest uploaded video does not autoplay the next video uploaded and so on.

### Proposed Solution

A button called "Play All" on the channel page. NewPipe has one.

### Alternatives Considered

There are none. The alternative is to manually go back and click the next music video after 3 minute has past and so on.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-09-10 13:15
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/629

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-09-10 13:15 UTC
Labels: enhancement, E: new feature
