### ISSUE TITLE
[Bug]: Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by jianboy** [FreeTubeApp/FreeTube#6459] opened 2024-12-27 07:08 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

不能播放

### Expected Behavior

Sign in to confirm you’re not a bot

Error: This content isn't available, try again later.

Error: [UNPLAYABLE] Please sign in

### Issue Labels

API issue

### FreeTube Version

v0.21

### Operating System Version

win11

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-27 14:14
- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

What nightly build are you using?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-27 18:56
Please update to v0.22.1

Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/6385

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-27 18:56 UTC
Labels: bug, U: Waiting for Response from Author, B: API issue
