### ISSUE TITLE
Turn a profile into a "music" profile

### ISSUE THREAD

**Issue by IronMaltese** [FreeTubeApp/FreeTube#1974] opened 2022-01-03 03:54 UTC
**Important note**
Please check other open and closed issues for a similar feature request before proposing a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Is your feature request related to a usage problem (not a bug)? Please describe.**
Please describe clear and concise of what the problem is. Ex. I'm always frustrated when [...]
It would be better if when I'm listening to music there's a better interface and search functionality for it

**Describe the solution you'd like to see implemented**
Please give a clear and concise description of what you want to happen.
When creating a new profile, in the customization screen there should be an option to make the profile a "music profile" which would give the app a UI that looks like spotify and search on youtube music instead of regular youtube

**Describe alternatives you've considered**
Are there other ways to solve the problem? Please give a clear and concise description of any alternative solutions or features you might have considered.
N/A

**Screenshots**
Sometimes people have screenshots from mock-ups or other projects. Add them here.
N/A

**Additional context**
Add any other context about the feature request here.
Idk how hard this would be to implement, but I would greatly appreciate if this was added

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-03 17:01
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1861

**Closed** 2022-01-03 17:01 UTC
Labels: U: duplicate, enhancement
