### ISSUE TITLE
[Bug]: Video stops playing after minutes of playing

### ISSUE THREAD

**Issue by brskl88** [FreeTubeApp/FreeTube#4460] opened 2023-12-15 19:10 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1.Open the app and start a video for watching 
2.After a while the video stops, and i have to change the video resolution to make video keeps playing.Otherwise it does not start playing again.
3.(the internet speed is 1 Gbit/s and the problem is not seen on the browser.)

### Expected Behavior

Make the app playing videos without any stop from start to the end.

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Lubuntu 22.04.3 LTS

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-12-15 19:56
> 2.After a while the video stops, and i have to change the video resolution to make video keeps playing.Otherwise it does not start playing again

What do you mean by after a while?

**Comment by brskl88** [comment] 2023-12-15 20:02
> > 2.After a while the video stops, and i have to change the video resolution to make video keeps playing.Otherwise it does not start playing again
> 
> What do you mean by after a while?

After i started a video.it keeps playing for a while.But it stops after a while randomly.Sometimes a few minutes sometimes it plays 10-15 minutes.But consequently it stops playing and to make it continue the same video i have to change resolution of it.Otherwise it never continues to play.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-12-15 21:46
Please make a screenshot of your general settings and your player settings

**Comment by brskl88** [comment] 2023-12-15 22:48
> Please make a screenshot of your general settings and your player settings

![general](https://github.com/FreeTubeApp/FreeTube/assets/89378367/902c73e3-37b3-400e-9e21-2e0e2613bf06)

![player](https://github.com/FreeTubeApp/FreeTube/assets/89378367/420f470c-3ee3-4956-b095-b3eca4519315)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-12-15 23:35
Do you have a proxy setup in the proxy settings section? If yes please try disabling it and seeing if that fixes the issue.

If you are using a VPN, can you try without one to see if it still happens and if you aren't using a VPN can you try with one (please close FreeTube between turning on/off you VPN, just to make sure that all connections are closed).

Additionally to check if it's actually throttling and not something else, could you please open the devtools (CTRL+SHIFT+I) and switching to the network tab before opening the video page. When you open the video, see if any of the videoplayback?expire=... requests are taking a significantly long amount of time than others. e.g. 10+ seconds.

Note: Might be related to #3979

**Comment by brskl88** [comment] 2023-12-15 23:58
> Do you have a proxy setup in the proxy settings section? If yes please try disabling it and seeing if that fixes the issue.
> 
> If you are using a VPN, can you try without one to see if it still happens and if you aren't using a VPN can you try with one (please close FreeTube between turning on/off you VPN, just to make sure that all connections are closed).
> 
> Additionally to check if it's actually throttling and not something else, could you please open the devtools (CTRL+SHIFT+I) and switching to the network tab before opening the video page. When you open the video, see if any of the videoplayback?expire=... requests are taking a significantly long amount of time than others. e.g. 10+ seconds.
> 
> Note: Might be related to #3979

Thank you very much.I do not use any proxy or VPN.But i try your last suggestion to check network on devtools for a while and write here the result.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-12-16 00:10
Example screenshot can be found https://github.com/FreeTubeApp/FreeTube/issues/3979#issuecomment-1701487361

**Comment by brskl88** [comment] 2023-12-16 00:11
> Do you have a proxy setup in the proxy settings section? If yes please try disabling it and seeing if that fixes the issue.
> 
> If you are using a VPN, can you try without one to see if it still happens and if you aren't using a VPN can you try with one (please close FreeTube between turning on/off you VPN, just to make sure that all connections are closed).
> 
> Additionally to check if it's actually throttling and not something else, could you please open the devtools (CTRL+SHIFT+I) and switching to the network tab before opening the video page. When you open the video, see if any of the videoplayback?expire=... requests are taking a significantly long amount of time than others. e.g. 10+ seconds.
> 
> Note: Might be related to #3979

Okay i think i found something here.While i was trying to check network activity, there were two longer videoplayback?expire=.. requests which are red lines.Then the video pauses.I add a screenshot of that.Is that an indicator of youtube throttling?

![screen](https://github.com/FreeTubeApp/FreeTube/assets/89378367/bb4ffb87-751b-4a50-9a41-9ad10a9fff90)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-12-18 22:54
Ah yes it looks like you are getting throttled by YouTube

Unfortunately at the moment we don't have a fix or workaround for this. As this has already reported before i will be closing marking this a duplicate of #3979

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-12-18 22:54 UTC
Labels: bug, B: usability, B: inconsistent behavior
