### ISSUE TITLE
[Bug]: Back from shorts in subscribed channel goes back to videos and not shorts

### ISSUE THREAD

**Issue by kaistian** [FreeTubeApp/FreeTube#5314] opened 2024-06-23 19:24 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to a subscribed channel
2. Click the shorts tab
3. Play one of the short by clicking it
4. Then click back
5. You get back to videos tab

### Expected Behavior

5. You should get back to the shorts tab

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.21.0 Beta

### Operating System Version

Kubuntu 22.04

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-24 10:09
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2446

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-06-24 10:09 UTC
Labels: bug, B: usability, B: inconsistent behavior
