### ISSUE TITLE
Add an option to hide scheduled videos until they're released

### ISSUE THREAD

**Issue by kibalcic** [FreeTubeApp/FreeTube#1163] opened 2021-04-04 06:14 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Whene a channel plans a video or a series of videos I get to see them on top of the subscription page until they're released.

**Describe the solution you'd like to see implemented**
I'd like to have an option in the settings to hide videos that are just scheduled but not released yet. 

**Describe alternatives you've considered**
A different option may be let them follow the feed and then showing them again at the top when they're released. 

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/76997570/113500354-92896480-951d-11eb-8bd4-b700e27a7119.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-05 18:19
@GilgusMaximus isn't this a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/507?

**Comment by PrestonN** [comment] 2021-07-06 03:53
It is.

**Closed by PrestonN** 2021-07-06 03:53 UTC
Labels: enhancement, good first issue
