### ISSUE TITLE
Export/Import support for FreeTube System/ Userdefined [config] Settings

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1978] opened 2022-01-04 05:35 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
To implement an import/export function for the FreeTube system configuration settings, for easy usability between OS or in another manner. It will be also good migration after some issue and for later version updates without resetting to the system default.

**Describe the solution you'd like to see implemented**
At the time of this issue was writing I haven't experienced how the history and subscriptions export/import in data settings works.
I think this issue can be applied similar way or like I find in most projects by using ".json" JavaScript syntax for the configuration option.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-06-21 16:19
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1018

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-06-21 16:19 UTC
Labels: enhancement
