### ISSUE TITLE
[Feature Request]: Video download management page

### ISSUE THREAD

**Issue by chrrybmb64** [FreeTubeApp/FreeTube#3932] opened 2023-08-23 02:59 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There is no way the view the status of downloads in Freetube. You also cannot pause downloads or queue videos to be downloaded.

### Proposed Solution

A download management page which lets you view and manage your downloads. Ideally, this page would do all of the following:

- Show all of the video(s) which you are currently downloading
- Show the progress of your downloads in the form of a progress bar or percentage (or both)
- Show you information about your downloads such as file size, video format, resolution, framerate, and download path
- Show you videos which you've downloaded in the past (optionally)
- Let you pause, resume, and cancel downloads
- Let you queue videos to be downloaded one at a time

### Alternatives Considered

n/a

### Issue Labels

display more information to user, improvement to existing feature

### Additional Information

I made of mock-up of what this download page would look like.

![freetube](https://github.com/FreeTubeApp/FreeTube/assets/117260224/430da0e7-8243-46ab-9507-6ceb43e11a00)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-08-23 08:53
This is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1772

Please put your suggestions over there

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-08-23 08:53 UTC
Labels: enhancement, E: improvement existing feature, E: display more information
