### ISSUE TITLE
Age-restricted videos don't work

### ISSUE THREAD

**Issue by LurkerHub** [FreeTubeApp/FreeTube#1563] opened 2021-08-04 19:40 UTC
**Behavior of the program**
Age-restricted videos throw several errors and get stuck

**Expected behavior**
Age restricted videos should play

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Start program
2. Enter url of age-restricted video
3. Observe errors
4. Enjoy endlessly spinning colours 

**Link to video**
Example: https://youtu.be/I5-6wR9RBwg
Don't worry, this is a generic SFW cat clip that I found on the Web, uploaded to YT, and marked as "age restricted".

**Screenshots**
![image](https://user-images.githubusercontent.com/20542915/128243862-40dfc959-286a-479b-a846-91b5fc16273d.png)

**Environment Information (please complete the following information):**
 - OS: Windows 10
 - FreeTube version: v0.13.2 Beta
 - Installation Method: .exe
 - Primary API Used: whatever the default is

**Additional context**
Local API error: status code 410
Invidious API error: undefined

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-08-04 20:10
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1296

@PrestonN @GilgusMaximus

**Closed** 2021-08-04 20:56 UTC
Labels: bug
