### ISSUE TITLE
Can't open channels that don't have a banner image

### ISSUE THREAD

**Issue by adolfintel** [FreeTubeApp/FreeTube#301] opened 2019-07-13 05:29 UTC
I get this error when I try to open one (try extraashens for example):
```
channels.js:50 Uncaught TypeError: Cannot read property 'url' of undefined
    at Object.success (channels.js:50)
    at fire (/opt/FreeTube/resources/app.asar/node_modules/jquery/dist/jquery.js:3291)
    at Object.fireWith [as resolveWith] (/opt/FreeTube/resources/app.asar/node_modules/jquery/dist/jquery.js:3421)
    at done (/opt/FreeTube/resources/app.asar/node_modules/jquery/dist/jquery.js:9533)
    at XMLHttpRequest.<anonymous> (/opt/FreeTube/resources/app.asar/node_modules/jquery/dist/jquery.js:9785)
```

This is with FreeTube 0.6.1.

**Comment by 0b10** [comment] 2019-07-13 11:42
Duplicate of #295, fixed here: #300

**Closed** 2019-07-13 14:15 UTC
