### ISSUE TITLE
[Feature Request]: Full buffering of the video

### ISSUE THREAD

**Issue by krpt** [FreeTubeApp/FreeTube#4577] opened 2024-01-21 13:19 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

My internet connection is very bad, lots of interruptions, video stop playing as I loose connection and video has not enough buffering to complete.

### Proposed Solution

having the video to fully load would be a game changer

### Alternatives Considered

Firefox permits that with media.mediasource.enabled but the resolution drops.

### Issue Labels

new optional setting

**Comment by absidue** [comment] 2024-01-21 20:19
duplicate of #678

**Closed** 2024-01-21 20:20 UTC
Labels: U: duplicate, enhancement, E: new optional setting
