### ISSUE TITLE
[MacOS] Tabbed "browsing"

### ISSUE THREAD

**Issue by lothar-cell** [FreeTubeApp/FreeTube#1870] opened 2021-11-03 07:17 UTC
**Describe the solution you'd like to see implemented**
Native OS implementation of tabs, eg. like in Finder and any browser. First tab should be invisible, I mean it is the window itself.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-11-03 19:17
Follow the full template otherwise we will close ur issue. We cant understand what u mean if u dont follow the template and please add and screenshot or video of what u mean.

**Comment by PrestonN** [comment] 2021-11-03 20:36
Duplicate of #333

**Closed by PrestonN** 2021-11-03 20:36 UTC
Labels: enhancement, OS: macos, U: doesn't follow template
