### ISSUE TITLE
[Bug]: Subs getting bigger rewatching the same clip if their size is set to >100%

### ISSUE THREAD

**Issue by Nioner42** [FreeTubeApp/FreeTube#4712] opened 2024-02-24 22:35 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Whenever I rewatch the same clip of a video or enter/exit from fullscreen, if subs size is set to be more than 100%, they'll look bigger and bigger (resizing, for instance, 125% of their size subs that already have been resized).

This only happens if I don't reopen the video.

https://github.com/FreeTubeApp/FreeTube/assets/142514507/eb160d07-b456-4ba7-90f5-25dbebedb57e

### Expected Behavior

Stay resized and not to resize again and again.

### Issue Labels

inconsistent behavior, text/string issue, visual bug

### FreeTube Version

v0.19.2

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-02-24 23:15
Duplicate of #3920

**Closed by absidue** 2024-02-24 23:15 UTC
Labels: bug, B: visual, B: text/string, B: inconsistent behavior
