### ISSUE TITLE
[Linux] TypeError: Cannot read property 'channelMetadataRenderer' of undefined

### ISSUE THREAD

**Issue by presianbg** [FreeTubeApp/FreeTube#1231] opened 2021-04-27 10:07 UTC
Hi,

For past few days the local API stopped working for some reason:
![image](https://user-images.githubusercontent.com/2163486/116224114-eec85880-a758-11eb-9878-233552f93360.png)

**Environment Information (please complete the following information):**
 - OS: Linux
 - OS Version: Solus 4.2
 - FreeTube version: FreeTube-0.12.0-nightly-741.AppImage
 - Installation Method: AppImage
 - Primary API Used: Local API

I've tried with clean profile ( deleting the `~/.config/FreeTube` folder ) to no avail. 

Any suggestions how to troubleshoot this ?
Tried with VPN via USA, because I'm EU based and saw some comments that the new youtube notice window might break things, but it does not make any difference. 

Kind regards,
Presian

**Comment by Svallinn** [comment] 2021-04-27 14:09
It would help if you actually let us know **how** this message came about, what action were you performing and such.

Anyway, I don't think I'm getting this error anywhere myself.
Can you paste the stacktrace in here?
Open the webtools with `Ctrl+Shift+I` and browse to the `Console` tab.
It should look something like this (might be in red instead; it might also be collapsed and need to be expanded)

![image](https://user-images.githubusercontent.com/41585298/116255228-947fc580-a761-11eb-8dc9-64b65d6ac5d9.png)

You can ignore all the `DevTools failed to load SourceMap...`

**Comment by presianbg** [comment] 2021-04-27 14:19
Thanks for getting back to me so fast!

Nothing, I just open the app and the above messages appear. Same errors, when trying to load the `Trending` section.
I missed this is an electron app and forgot to check the console:

```
Error: Status code 404
    at ClientRequest.<anonymous> (/tmp/.mount_FreeTuIYLyJS/resources/app.asar/node_modules/rss-parser/lib/parser.js:88)
    at Object.onceWrapper (events.js:422)
    at ClientRequest.emit (events.js:315)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126)
    at TLSSocket.socketOnData (_http_client.js:509)
    at TLSSocket.emit (events.js:315)
    at addChunk (internal/streams/readable.js:309)
    at readableAddChunk (internal/streams/readable.js:284)
    at TLSSocket.Readable.push (internal/streams/readable.js:223)
```

```
TypeError: Cannot read property 'channelMetadataRenderer' of undefined
    at YoutubeGrabberHelper.parseChannelVideoResponse (/tmp/.mount_FreeTuIYLyJS/resources/app.asar/node_modules/yt-channel-info/app/helper.js:60)
    at Function.getChannelVideosNewest (/tmp/.mount_FreeTuIYLyJS/resources/app.asar/node_modules/yt-channel-info/app/fetchers/channel.js:10)
    at async Function.getChannelVideos (/tmp/.mount_FreeTuIYLyJS/resources/app.asar/node_modules/yt-channel-info/app/youtube-grabber.js:207)
```

```
TypeError: Cannot read property 'simpleText' of undefined
    at /tmp/.mount_FreeTuIYLyJS/resources/app.asar/node_modules/yt-trending-scraper/src/Youtube-Scraper.js:112
    at Array.forEach (<anonymous>)
    at Function.parse_normal_video_section (/tmp/.mount_FreeTuIYLyJS/resources/app.asar/node_modules/yt-trending-scraper/src/Youtube-Scraper.js:84)
    at Function.build_api_output (/tmp/.mount_FreeTuIYLyJS/resources/app.asar/node_modules/yt-trending-scraper/src/Youtube-Scraper.js:32)
    at /tmp/.mount_FreeTuIYLyJS/resources/app.asar/node_modules/yt-trending-scraper/src/Youtube-Scraper.js:20
    at Array.forEach (<anonymous>)
    at Function.parse_new_html (/tmp/.mount_FreeTuIYLyJS/resources/app.asar/node_modules/yt-trending-scraper/src/Youtube-Scraper.js:19)
    at Function.scrape_trending_page (/tmp/.mount_FreeTuIYLyJS/resources/app.asar/node_modules/yt-trending-scraper/src/Youtube-Scraper.js:8)
```

I thought something is wrong with my installation, but tried on different machine (again Solus) and the result is the same.

**Comment by GilgusMaximus** [comment] 2021-04-27 16:21
When opening your subscription page it might be due to one channel getting banned or closed. Then the api tries to access it, but it is not there anymore.

For the trending page I am not 100% sure what could be a cause. If you could share from which country you are, it would help to narrow down the list of trending regions to test. You can also send it to me privately via Matrix if you do not want to disclose it here on Github @gilgusmaximus:matrix.org

**Comment by presianbg** [comment] 2021-04-28 05:43
@GilgusMaximus , in some of my testes I deleted the `~/.config/FreeTube` folder, but the issue persisted. 
I'm from Bulgaria, but I tried with USA VPN and the result was the same.

**Comment by GilgusMaximus** [comment] 2021-04-28 17:01
So regarding the trending page I already found the problem's source. The module itself is not working correctly anymore. 
However for your subscriptions it is likely still the problem I described above. There is not much I can do here atm. If the channel is closed/banned then the app will fail. If it is an error in the app, I'd need some info on which channel it actually is.

**Comment by linuxgirl22** [comment] 2021-04-28 18:01
switched to linux channel

renderer.js:2 Uncaught TypeError: Cannot read property 'videoWidth' of null
    at o.checkAspectRatio (renderer.js:2)
    at renderer.js:2
renderer.js:2 
Array(24)
renderer.js:2 https://invidious.kavin.rocks
renderer.js:2 Error: Status code 404
    at ClientRequest.<anonymous> (/tmp/.mount_FreeTuNl…er/lib/parser.js:88)
    at Object.onceWrapper (events.js:422)
    at ClientRequest.emit (events.js:315)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:509)
    at TLSSocket.emit (events.js:315)
    at addChunk (internal/streams/readable.js:309)
    at readableAddChunk (internal/streams/readable.js:284)
renderer.js:2 TypeError: Cannot read property 'channelMetadataRenderer' of undefined
    at YoutubeGrabberHelper.parseChannelVideoResponse (/tmp/.mount_FreeTuNl…fo/app/helper.js:60)
    at Function.getChannelVideosNewest (/tmp/.mount_FreeTuNl…chers/channel.js:10)
    at async Function.getChannelVideos (/tmp/.mount_FreeTuNl…tube-grabber.js:207)
/tmp/.mount_FreeTuNl…uter.common.js:2067 Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/subscriptions".
    at createRouterError (/tmp/.mount_FreeTuNlblfG/resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:2067:15)
    at createNavigationDuplicatedError (/tmp/.mount_FreeTuNlblfG/resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:2037:15)
    at HashHistory.confirmTransition (/tmp/.mount_FreeTuNlblfG/resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:2330:18)
    at HashHistory.transitionTo (/tmp/.mount_FreeTuNlblfG/resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:2262:8)
    at HashHistory.push (/tmp/.mount_FreeTuNlblfG/resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:2706:10)
    at /tmp/.mount_FreeTuNlblfG/resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:3022:22
    at new Promise (<anonymous>)
    at VueRouter.push (/tmp/.mount_FreeTuNlblfG/resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:3021:12)
    at o.navigate (file:///tmp/.mount_FreeTuNlblfG/resources/app.asar/dist/renderer.js:2:492430)
    at click (file:///tmp/.mount_FreeTuNlblfG/resources/app.asar/dist/renderer.js:2:492777)
renderer.js:2 
Array(24)
renderer.js:2 https://invidious.048596.xyz
renderer.js:2 Error: Status code 404
    at ClientRequest.<anonymous> (/tmp/.mount_FreeTuNl…er/lib/parser.js:88)
    at Object.onceWrapper (events.js:422)
    at ClientRequest.emit (events.js:315)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:509)
    at TLSSocket.emit (events.js:315)
    at addChunk (internal/streams/readable.js:309)
    at readableAddChunk (internal/streams/readable.js:284)
renderer.js:2 TypeError: Cannot read property 'channelMetadataRenderer' of undefined
    at YoutubeGrabberHelper.parseChannelVideoResponse (/tmp/.mount_FreeTuNl…fo/app/helper.js:60)
    at Function.getChannelVideosNewest (/tmp/.mount_FreeTuNl…chers/channel.js:10)
    at async Function.getChannelVideos (/tmp/.mount_FreeTuNl…tube-grabber.js:207)
renderer.js:2 No sources available
renderer.js:2 Getting video info please wait...
renderer.js:2 Error: Status code: 429
    at ClientRequest.<anonymous> (/tmp/.mount_FreeTuNl…t/dist/index.js:204)
    at Object.onceWrapper (events.js:422)
    at ClientRequest.emit (events.js:315)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:509)
    at TLSSocket.emit (events.js:315)
    at addChunk (internal/streams/readable.js:309)
    at readableAddChunk (internal/streams/readable.js:284)
invidious.048596.xyz…deos/M7RVPFisSO4?:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
renderer.js:2 
Object
renderer.js:2 error
renderer.js:2 https://invidious.048596.xyz/api/v1/videos/M7RVPFisSO4?
renderer.js:2 Forbidden
renderer.js:2 found an error
renderer.js:2 
Object
renderer.js:2 
Object
renderer.js:2 -1
/tmp/.mount_FreeTuNl…/video.cjs.js:27343 Uncaught TypeError: Cannot read property 'length' of undefined
    at addPropertiesToMaster (/tmp/.mount_FreeTuNl…/video.cjs.js:27343)
    at parseMasterXml (/tmp/.mount_FreeTuNl…/video.cjs.js:29571)
    at DashPlaylistLoader.haveMaster_ (/tmp/.mount_FreeTuNl…/video.cjs.js:30148)
    at DashPlaylistLoader.onClientServerClockSync_ (/tmp/.mount_FreeTuNl…/video.cjs.js:30203)
    at DashPlaylistLoader.syncClientServerClock_ (/tmp/.mount_FreeTuNl…/video.cjs.js:30098)
    at /tmp/.mount_FreeTuNl…/video.cjs.js:30078
    at callbackWrapper (/tmp/.mount_FreeTuNl…/video.cjs.js:28882)
    at Object.callback (/tmp/.mount_FreeTuNl…/video.cjs.js:28904)
    at cbOnce (/tmp/.mount_FreeTuNl…ojs/xhr/index.js:95)
    at XMLHttpRequest.loadFunc (/tmp/.mount_FreeTuNl…js/xhr/index.js:162)
invidious.048596.xyz…PFisSO4?height=90:1 Failed to load resource: the server responded with a status of 404 (Not Found)
renderer.js:2 Uncaught TypeError: Cannot read property 'qualityLevels' of null
    at renderer.js:2
renderer.js:2 Uncaught TypeError: Cannot read property 'videoWidth' of null
    at o.checkAspectRatio (renderer.js:2)
    at renderer.js:2
renderer.js:2 Error: Request timed out after 60000ms
    at /tmp/.mount_FreeTuNl…r/lib/parser.js:101
        
america's funniest home videos channel
    
    No sources available
renderer.js:2 Getting video info please wait...
renderer.js:2 Error: Status code: 429
    at ClientRequest.<anonymous> (/tmp/.mount_FreeTuNl…t/dist/index.js:204)
    at Object.onceWrapper (events.js:422)
    at ClientRequest.emit (events.js:315)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:509)
    at TLSSocket.emit (events.js:315)
    at addChunk (internal/streams/readable.js:309)
    at readableAddChunk (internal/streams/readable.js:284)
/tmp/.mount_FreeTuNl…ist/jquery.js:10109 GET https://invidious.048596.xyz/api/v1/videos/NXHyNQGNBIc? 403 (Forbidden)
renderer.js:2 
{readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
renderer.js:2 error
renderer.js:2 https://invidious.048596.xyz/api/v1/videos/NXHyNQGNBIc?
renderer.js:2 Forbidden
renderer.js:2 found an error
renderer.js:2 
{readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
renderer.js:2 
{readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
renderer.js:2 -1

painting the light channel

No sources available
renderer.js:2 Getting video info please wait...
renderer.js:2 Error: Status code: 429
    at ClientRequest.<anonymous> (/tmp/.mount_FreeTuNl…t/dist/index.js:204)
    at Object.onceWrapper (events.js:422)
    at ClientRequest.emit (events.js:315)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:509)
    at TLSSocket.emit (events.js:315)
    at addChunk (internal/streams/readable.js:309)
    at readableAddChunk (internal/streams/readable.js:284)
/tmp/.mount_FreeTuNl…ist/jquery.js:10109 GET https://invidious.048596.xyz/api/v1/videos/S_cYlgl28Wo? 403 (Forbidden)
renderer.js:2 
{readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
renderer.js:2 error
renderer.js:2 https://invidious.048596.xyz/api/v1/videos/S_cYlgl28Wo?
renderer.js:2 Forbidden
renderer.js:2 found an error
renderer.js:2 
{readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
renderer.js:2 
{readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
renderer.js:2 -1
﻿
trending ... 
/tmp/.mount_FreeTuNl…ist/jquery.js:10109 GET https://invidious.048596.xyz/api/v1/trending/?region=US net::ERR_CONNECTION_RESET

UK, using UK IP

switching to Swiss IP ... 

turns out STL vid was premiere-bookmarked
america's funniest works, and comments too
painting the light works, and comments too
trending works

**Comment by presianbg** [comment] 2021-04-28 19:14
@linuxgirl22  sorry but I fail to see the connection with my problem :(

**Comment by linuxgirl22** [comment] 2021-04-28 19:58
I'm getting the same error. Was trying to be helpful, adding more info, particularly what was requested of you, but you didn't provide.

**Comment by GilgusMaximus** [comment] 2021-04-29 09:56
@linuxgirl22 are you using Invidious? Or is the fallback enabled, cause I am seeing some Invidious logs in there, which appear to fail as well. Also I checked the channel you provided and they work with local api and with various Invidious APIs

**Comment by linuxgirl22** [comment] 2021-04-29 12:17
@GilgusMaximus Yes, just the default ... local API and trying a different invidious alternatives from the drop down list. As I said, with a Swiss IP, videos and comments are working fine, albeit with a lot of error messages on startup, as OP is showing + the 'lots subs/forcing RSS line' above. Changing IP to non-UK made all the difference. The above code I included shows what happened with a UK IP, and then concludes with Swiss IP results at the end, after the code. If you're not using a UK IP, that could explain why not experiencing issues.

**Comment by GilgusMaximus** [comment] 2021-05-02 19:54
But OP also mentioned that it happens with US VPN. So it is not really UK only related. Also using a VPN in the UK does not result in problems for me. I can load the comments just like normal, even for US locations. So there must be something else in there...

**Comment by linuxgirl22** [comment] 2021-05-02 21:47
Only posted to answer questions being asked. If I switch to a USA IP, works great, same as Swiss IP. No luck with UK IP. Is it VPN servers/providers? Don't know; I'm not the tech support. Using Expressvpn.

**Comment by GilgusMaximus** [comment] 2021-05-03 11:55
I'm using MullvadVPN. But there really should not be a difference. An UK Ip should always load the same YouTube page

**Comment by linuxgirl22** [comment] 2021-05-03 13:52
Don't know; it's confusing, as all the reports conflict, e.g. I need to run a Swiss IP to run Freetube successfully, whereas another person is able to run it fine via a UK IP ... so I wasn't sure if where the VPN company may be running from, or how it structures things, may play some part.

**Comment by presianbg** [comment] 2021-05-04 05:04
Looks like it was a temporary thing... at least for the trending and most popular tabs.
For the subscription page it turned out that one of the channels I was subscribed to was closed/deleted.
Unsubscribing from this channel fixed the errors in `Subscription` tab.
Can we have something in the logs regarding which channel id/name is gone, because in current situation I had to check every channel one at a time.

Looks like you may close this issue if you see no bugs in the api. 

Cheers,
PY

**Comment by Victor239** [comment] 2021-05-07 09:35
I get the same error when trying to "View Comments" on videos, and it fails to load. It's consistent and occurs across multiple Invidious instances. 

```
/app/freetube/resour…adapters/xhr.js:177 GET https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DmYG3jiujVnY&gl=GB&m=0&pc=yt&uxe=23983172&hl=en-GB&src=1 403
renderer.js:2 TypeError: Cannot read property 'continuationContents' of undefined
    at Function.getComments (/app/freetube/resour…utube-Scraper.js:42)
renderer.js:2 found an error
renderer.js:2 TypeError: Cannot read property 'resource' of undefined
    at renderer.js:2
    at new Promise (<anonymous>)
    at Store.invidiousAPICall (renderer.js:2)
    at Array.wrappedActionHandler (/app/freetube/resour…/vuex.common.js:853)
    at Store.dispatch (/app/freetube/resour…/vuex.common.js:518)
    at Store.boundDispatch [as dispatch] (/app/freetube/resour…/vuex.common.js:408)
    at o.mappedAction (/app/freetube/resour…vuex.common.js:1066)
    at o.getCommentDataInvidious (renderer.js:2)
    at renderer.js:2

```
Local API with Invidious fallback, not proxying
v0.12.0
Kubuntu 21.04
Installation Method: Flatpak

**Comment by manuee** [comment] 2021-05-12 20:30
Using **v0.12.0-nightly-806 Beta** here.

I believe I momentarily _saw_ the same error, I _could_ reproduce it by just browsing to any channel... 
The console _showed_ this:
```
TypeError: Cannot read property 'channelMetadataRenderer' of undefined
    at Function.parseChannelPlaylistResponse (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/fetchers/playlist.js:25)
    at Function.getChannelPlaylistLast (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/fetchers/playlist.js:11)
    at async Function.getChannelPlaylistInfo (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/youtube-grabber.js:265)
renderer.js:2 TypeError: Cannot read property 'channelMetadataRenderer' of undefined
    at YoutubeGrabberHelper.parseChannelVideoResponse (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/helper.js:60)
    at Function.getChannelVideosNewest (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/fetchers/channel.js:10)
    at async Function.getChannelVideos (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/youtube-grabber.js:203)
renderer.js:2 TypeError: Cannot read property 'channelMetadataRenderer' of undefined
    at Function.getChannelInfo (/opt/FreeTube/resources/app.asar/node_modules/yt-channel-info/app/youtube-grabber.js:24)
```

However after restarting the application, the problem vanished somehow, and I can now browse any channel. Very strange.

**Comment by stemy2** [comment] 2021-05-14 10:06
For me, the error appears when i'm trying to show the comments. I say "trying" because it doesn't work.

**Comment by GilgusMaximus** [comment] 2021-05-16 14:38
> However after restarting the application, the problem vanished somehow, and I can now browse any channel. Very strange.

The problem for me atm is that I really do not have a channel where I can test this. I mean we can add a check to the module if this happens. But then what? It does not load the channel? So either way it will not load the channel. Then for the moment I still believe there is a major uncertainty to this problem. So keeping an eye out for it

**Comment by Trung0246** [comment] 2021-06-26 22:07
Hi, I found a channel in my subscription list that could cause this bug after putting debugger in the web console: https://www.youtube.com/channel/UC_FqH-6GpFosu_P0ApjqW5A

Seems like they deleted the channel which may or may not the same as getting banned?
And seems like https://www.youtube.com/feeds/videos.xml?channel_id=UC_FqH-6GpFosu_P0ApjqW5A returns 404 which is likely the cause.

Obviously for a normal channel like https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw the link still exist.
![image](https://user-images.githubusercontent.com/11626920/123526943-2a679c00-d690-11eb-92f6-aba752d595c9.png)

**Comment by kgorol** [comment] 2021-07-28 04:27
```
Some messages have been moved to the Issues panel.
View issues
renderer.js:2 TypeError: Cannot read property 'continuationContents' of undefined
    at Function.getComments (/opt/FreeTube/resour…utube-Scraper.js:36)
renderer.js:2 found an error
renderer.js:2 TypeError: Cannot read property 'resource' of undefined
    at renderer.js:2
    at new Promise (<anonymous>)
    at Store.invidiousAPICall (renderer.js:2)
    at Array.wrappedActionHandler (/opt/FreeTube/resour…/vuex.common.js:853)
    at Store.dispatch (/opt/FreeTube/resour…/vuex.common.js:518)
    at Store.boundDispatch [as dispatch] (/opt/FreeTube/resour…/vuex.common.js:408)
    at r.mappedAction (/opt/FreeTube/resour…vuex.common.js:1066)
    at r.getCommentDataInvidious (renderer.js:2)
    at renderer.js:2
```

Still getting this error when trying to load the comments. I've gone through my subscriptions and every seems to be online. There was a single channel that was banned for a couple of days, but now it's back online.

v0.13.2 Beta

**Comment by GilgusMaximus** [comment] 2021-07-28 14:23
Well the problem with the provided channel is that it has been banned.

Loading comments is fixed in the newest nightly builds and also does not relate to the issue here.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-05-16 14:42
anyone still experiencing this issue in the latest nightly?

**Closed** 2022-06-03 14:04 UTC
Labels: bug, U: Waiting for Response from Author
