### ISSUE TITLE
[Feature Request]: Have the settings of playback rate to apply only to non-live videos

### ISSUE THREAD

**Issue by Janaue** [FreeTubeApp/FreeTube#5656] opened 2024-09-06 13:20 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I set my default playback rate to 1.5x, which works fine for non-live videos, but for live videos of course it doesn't make sens and the stream constantly cuts off once I caught up with the stream

### Proposed Solution

. So it's best to make the playback rate 1x for live videos.

### Alternatives Considered

NA

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-06 13:38
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3674

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-06 13:38 UTC
Labels: enhancement, E: improvement existing feature
