### ISSUE TITLE
[Feature Request]: Disable Windows' "Media Volume Control" Popup

### ISSUE THREAD

**Issue by TBat** [FreeTubeApp/FreeTube#4256] opened 2023-10-31 00:49 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When using hardware volume controls, FreeTube calls Windows' ["Media Volume Control" popup](https://github.com/FreeTubeApp/FreeTube/assets/29135447/66284302-acd5-42e2-af94-1df7cdbc2f7d)
This popup is very distracting and unnecessary, plus it covers up a good portion of other applications for several seconds.

### Proposed Solution

Add an option to fully disable hardware media keys behavior in FreeTube. For instance, Chrome has this option in flags: `chrome://flags/#hardware-media-key-handling`. Disabling it stops the popup from appearing, leaving only the much smaller volume slider element.

### Alternatives Considered

Ideally there would also be an option to just stop FreeTube from calling the "Media Volume Control" popup, so people could get rid of it without sacrificing hardware media controls. I don't know how easy it is to decouple these behaviors, but personally I'm fine with disabling hardware keys' interaction with FreeTube entirely.

### Issue Labels

ease of use improvement

### Additional Information

![screenshot](https://github.com/FreeTubeApp/FreeTube/assets/29135447/66284302-acd5-42e2-af94-1df7cdbc2f7d)

**Comment by absidue** [comment] 2023-10-31 06:07
duplicate of #1465

**Closed** 2023-10-31 06:08 UTC
Labels: enhancement, E: ease of use improvement
