### ISSUE TITLE
[Feature Request]: Hide videos All Channels based on a particular Category

### ISSUE THREAD

**Issue by ScriptForAll** [FreeTubeApp/FreeTube#2061] opened 2022-02-08 20:59 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I would like to look at my "All Channels" subscriptions and have the option to hide videos based on something like a blacklist. This is particular useful when you are interested in watching all the new content except for a few ones (e.g. New Music Releases).

### Proposed Solution

My proposal is to have the ability to use certain categories as a blacklist.

From a UX/UI perspective, this could be achieved by introducing a submenu or a button to activate a "blacklisting mode" and then selecting the unwanted categories to show up.

### Alternatives Considered

Another option would be to implement the symmetric of what is proposed above: instead of using blacklists it would use whitelists, i.e. the ability to select several categories at once.
 
However, I reckon this wouldn't be as good of an option since it doesn't account for the subscriptions that don't have a category (i.e. those that are only in "All Channels") which would require a round-a-bout way to do the same as proposed.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-02-08 21:04
I'd consider this a duplicate of #1070

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-02-08 21:04 UTC
Labels: enhancement, E: new feature
