### ISSUE TITLE
Feature request: back button and ability to search for channels  

### ISSUE THREAD

**Issue by ricardotd** [FreeTubeApp/FreeTube#68] opened 2018-03-29 03:08 UTC
I installed free tube on mac, and these are the missing features that would make me switch to this instead of the actual youtube website.
I cannot search for channels, 
and there is no back button if you are on a channel.

**Comment by aproposnix** [comment] 2018-03-29 16:09
Duplicate of #3 
Duplicate of #15

**Comment by PrestonN** [comment] 2018-04-05 03:37
What @aproposnix said.  These are planned in the future.

**Closed by PrestonN** 2018-04-05 03:37 UTC
