### ISSUE TITLE
[Feature Request]: Ability to increase volume above 100%

### ISSUE THREAD

**Issue by tris03** [FreeTubeApp/FreeTube#4300] opened 2023-11-08 05:23 UTC
### Guidelines

- [x] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Some videos are significantly quieter than others as different content creators balance their audio differently.

### Proposed Solution

Implement an option to increase the volume of a video above 100% - maybe to 200% or 300% maximum.

### Alternatives Considered

Alternatively, a feature could be implemented to normalize or equalize volume to a user's desired amount.

### Issue Labels

ease of use improvement, new feature, new optional setting

### Additional Information

There are plugins/extensions for most browsers which implement this. They could be looked to for inspiration.

**Comment by absidue** [comment] 2023-11-08 07:24
duplicate of #1551

**Closed** 2023-11-08 07:25 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement, E: new feature
