### ISSUE TITLE
[Feature Request] Apply some sort of ordering to subscription profiles

### ISSUE THREAD

**Issue by brettmitchelldev** [FreeTubeApp/FreeTube#1892] opened 2021-11-13 12:17 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I manage my music subscriptions in individual profiles by genre. I use prefixes to simulate folder-like behavior ('Music - ' in this example). This leads to a lot of entries in my profiles dropdown, and it can be difficult to find what I am looking for, since profiles are displayed in the order they were created, rather than in a sorted or manually set order.

**Describe the solution you'd like to see implemented**
I've personally thought of two options, though there may be better solutions out there.

1) Allow drag-and-drop re-ordering of profiles, either in the profiles dropdown or in the profiles settings page. DnD would probably fit better with the feature set of the settings page, but would fit better with the layout of the dropdown IMO, but I'm no UX expert. :shrug:

2) Automatically sort by lexical order. This would be the simpler of the two, and would probably be the one I'd personally prefer.

**Describe alternatives you've considered**
I've tried hacking `~/.config/FreeTube/profiles.db` to no avail, it just gets overwritten with the original order when I fire FreeTube back up. There's probably a cache file somewhere that I need to delete, but I don't know where that is.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by arrowgent** [comment] 2021-11-15 06:26
subscription folders could be very cool idea

ALL would be default
then you'd need a menu to manage them
similar to how browsers organize bookmarks

also consider importing subscription lists from youtube is unorganized == ALL

**Comment by brettmitchelldev** [comment] 2021-11-16 10:59
@arrowgent There is an open issue tracking that idea: https://github.com/FreeTubeApp/FreeTube/issues/800

From the discussion there, I don't think the devs are implementing folders, but you could go ahead and leave a description of your specific use case. More use cases from the user community is never a bad thing IMO; e.g. even if folders never make it in, maybe there is a simpler/different solution to the main points of the feature.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-05-25 14:05
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/987

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-05-25 14:05 UTC
Labels: enhancement
