### ISSUE TITLE
[Bug]: Constant stop/buffering on external player

### ISSUE THREAD

**Issue by PolGZ** [FreeTubeApp/FreeTube#2531] opened 2022-09-03 00:14 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Reproducing video with external player (mpv) is way slower than from the app itself.

I can play videos from normal freetube without any issues (I have a very good internet connection). I frequently check for the instance that seems to work nicer. But when I use the external player option (wich I have set to mpv, but also have tried vlc), it doesn't go without constant stop/buffering (completely unusable).

I'm running latest flatpak version on Debian stable.

I would love to use mpv because it is way lighter for my CPU. I can close the freetube instance and have my laptop fan total silent (whereas with freetube player itself it makes a low but constant fan noise, that is specially uncomfortable at nights.

### Expected Behavior

To load and buffer the same with internal/external player.

### Issue Labels

usability issue

### FreeTube Version

v. 0.17.1

### Operating System Version

Debian 11 Stable

### Installation Method

Flathub

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-09-03 00:23
please add a title your bug report

**Comment by absidue** [comment] 2022-09-03 12:30
FreeTube passes the video URL in the case of VLC `https://www.youtube.com/watch?v=dQw4w9WgXcQ` and for MPV with the ytdl protocol `ytdl://dQw4w9WgXcQ`.
https://github.com/FreeTubeApp/FreeTube/blob/f8eff0e422f04e2e765a8f07b622c1629cdea9be/src/renderer/store/modules/utils.js#L1078-L1082

So playback issues in the external player are problems on their end.

After a few quick searches it looks like MPV uses `youtube-dl` or `yt-dlp` under the hood to handle the `ytdl://` protocol, therefore you might be able to solve the problem by updating MPV and `youtube-dl` or `yt-dlp`, whichever one you use.

**Comment by absidue** [comment] 2022-09-03 13:02
Closing this issue, as the problem is with the external player and not with FreeTube.

**Closed by absidue** 2022-09-03 13:02 UTC
Labels: bug, third-party, B: usability
