### ISSUE TITLE
[Feature Request]: Group videos in Subscriptions by day or week and make the groups collapsable

### ISSUE THREAD

**Issue by Gorrrg** [FreeTubeApp/FreeTube#3799] opened 2023-07-22 17:24 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [x] This issue contains only one feature request.

### Problem Description

I am following hundreds of channels, and I usually use FreeTube in the evening. So every time I look at new videos it's a hassle to find the position where the videos from yesterday end and the videos of today start. Also if I want to go back and look for a video from a specific day of the week, it's almost impossible to get to it by scrolling.

### Proposed Solution

Add the option to have groups in Subscription and Playlist view. The UI element could be borrowed from the Settings page: the subgroups collapsable by clicking the subgroup heading.

You should be able to set the grouping scheme to month, week, day, or 12, 6 hours. Or "session", meaning grouping the videos by the last times the applications was started, in which case FreeTube would need to keep track of its start datetimes.

### Alternatives Considered

Add a calendar as a filter. When you filter by date, a calendar element popus up and you can set a day and time or a range.

Actually I'd love to have both.

### Issue Labels

ease of use improvement, new feature, new optional setting, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-10 06:52
Closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/4803

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-10 06:52 UTC
Labels: enhancement, E: new optional setting, E: visual improvement, E: ease of use improvement, E: new feature

**Comment by AlexanderRavenheart** [comment] 2024-05-04 21:33
> Closing in favor of #4803

Why? #4803 has nothing to do with the grouping of videos as per a specific time span like day, week or month.

I think this issue should be reopened, it is a very nice feature to have.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-05 09:20
> I am following hundreds of channels, and I usually use FreeTube in the evening. So every time I look at new videos it's a hassle to find the position where the videos from yesterday end and the videos of today start. Also if I want to go back and look for a video from a specific day of the week, it's almost impossible to get to it by scrolling.

The solution to the issue isnt to group videos. #4803 addresses the root cause so you always know where you left off. Then the user can really decide when to fetch new subscriptions to see new ones. The user will be in full control of their own subscription page.

**Comment by AlexanderRavenheart** [comment] 2024-05-06 19:57
#4803 does not address:
- "to find the position where the videos from yesterday end and the videos of today start" -> a refresh (manual or automatic) will still populate the subscription list with new entries and there will be no separation between old and new videos
- "if I want to go back and look for a video from a specific day of the week, it's almost impossible to get to it by scrolling" -> because there is no distinction of videos per day/week/month, it is just a continuous list of entries

#4803 addresses:
- using the previously fetched list of videos (at the time of the last refresh) for multiple sessions of the app -> this permits users to browse the previously fetched list of videos and only refresh when they want to see newer videos even if they restart the application multiple times (as long as they have automatic fetching set to disabled)

So, in essence, this issue and #4803 are for different use cases.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-06 20:51
> "to find the position where the videos from yesterday end and the videos of today start" -> a refresh (manual or automatic) will still populate the subscription list with new entries and there will be no separation between old and new videos

This can be easily addressed with implementing https://github.com/FreeTubeApp/FreeTube/issues/4536

> if I want to go back and look for a video from a specific day of the week, it's almost impossible to get to it by scrolling" -> because there is no distinction of videos per day/week/month, it is just a continuous list of entries

That sounds like you got too many subscriptions in one profile. I suggest creating multiple profiles

**Comment by AlexanderRavenheart** [comment] 2024-05-07 13:52
> > "to find the position where the videos from yesterday end and the videos of today start" -> a refresh (manual or automatic) will still populate the subscription list with new entries and there will be no separation between old and new videos
> 
> This can be easily addressed with implementing #4536

I agree with this.

> > if I want to go back and look for a video from a specific day of the week, it's almost impossible to get to it by scrolling" -> because there is no distinction of videos per day/week/month, it is just a continuous list of entries
> 
> The distinction is the published date. It sounds like you got too many subscriptions in one profile. I suggest creating multiple profiles

You are suggesting to limit usage of a feature instead of accepting a better UI design.

Compare this (current UI, one continuous list of videos):
![Freetube - No video grouping](https://github.com/FreeTubeApp/FreeTube/assets/7274337/e29cb3c4-9008-466b-b095-d3ac90dc85e7)

With this (rough mockup, multiple lists, one per grouping (e.g. days), with a simple header for each group of videos):
![Freetube - With video grouping](https://github.com/FreeTubeApp/FreeTube/assets/7274337/102c436c-33ad-409a-a9d6-5871a8c74b21)

The difference is like night and day in terms of usability.

And this grouping could be an opt-in feature, for those who want more flexibility and control over how video entries are displayed.
