### ISSUE TITLE
[Feature Request]: Subscription Feed filters to remove self-promotion non-content videos (premieres, shorts, etc.)

### ISSUE THREAD

**Issue by Joeviocoe** [FreeTubeApp/FreeTube#2634] opened 2022-09-28 18:08 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Some YouTube channels have a large number of uploaded "shorts" that do not contain actual content, but rather are mere previews of content soon to be coming.  This is in addition to the "premiere" future video placeholders.

This can and does clutter the subscription feed as more and more channels abuse this to dominate the attention of viewers with non-content videos.

### Proposed Solution

Inside the "channel list" menu, and for each channel, create a drop down sub-menu with filter options similar to the "Duration" in the "search filters" menu.
There should be two duration options with number selectors, a greater than and a less than.  This will allow users to filter out the "shorts" from different channels independently and is customizable depending on the particular duration "shorts" tend to be.
There should be one checkbox for "premiere" videos that aren't not available yet, and one checkbox for "live stream" videos too.

### Alternatives Considered

If individual settings per each channel is too much, a global setting should suffice.

### Issue Labels

ease of use improvement, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-09-28 18:19
basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2008 https://github.com/FreeTubeApp/FreeTube/issues/1070

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-09-28 18:19 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement

**Comment by Joeviocoe** [comment] 2022-09-28 22:10
> basically a duplicate of #2008 #1070

Not really a close duplicate.  This certainly falls into a similar Category of subscription filter.  Both #2008 and #1070 request to filter by matching the video "title" (#shorts or arbitrary string).
My feature request is a more detailed filtering mechanic based on type or duration, similar to the Search Filter.

Since feature requests in this broad category seems to be submitted very often, only to be closed as a duplicate, can this be prioritized higher?
