### ISSUE TITLE
[Bug]: Long playlists broken with Invidious API

### ISSUE THREAD

**Issue by m3thm4th** [FreeTubeApp/FreeTube#5789] opened 2024-10-04 00:11 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When using the Invidious API long playlists (hundreds of videos) are not shown completely, only about half are shown. When reloading the playlist using Local API the issue disappears.

### Expected Behavior

.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.21.3

### Operating System Version

Debian 12

### Installation Method

Flathub

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-04 04:31
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2333

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-04 04:31 UTC
Labels: bug, B: inconsistent behavior
