### ISSUE TITLE
FreeTube doesn't load in Windows7

### ISSUE THREAD

**Issue by gh-supersudo** [FreeTubeApp/FreeTube#1779] opened 2021-10-01 18:45 UTC
**Behavior of the program**
App doesn't load

**Expected behavior**
App should work normally

**Screenshots**
![freetube-w7](https://user-images.githubusercontent.com/61962519/135670892-003e03bd-7c10-44db-8771-86b6f8c2ea82.png)

**Environment Information (please complete the following information):**
 - OS: Windows 7 - 64bit
 - FreeTube version: 0.14.0
 - Installation Method (If applicable):  .exe
 - Primary API Used: [Local API, Invidious API]

**Additional context**
It's newly installed on W7. I have FreeTube in i3wm linux and I didn't got any errors like this.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-01 18:48
Hi @gh-supersudo this is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1768

If u want u can leave a comment over there.

I'll be closing this issue in order to prevent cluttering the backlog.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-10-01 18:48 UTC
Labels: bug, duplicate
