### ISSUE TITLE
[Bug]: Seek bar only goes up to 1 hour in live videos

### ISSUE THREAD

**Issue by kugiigi** [FreeTubeApp/FreeTube#6037] opened 2024-10-30 12:03 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to a live video that's has been live for more than an hour
2. Try to use the seek bar to go back to more than 1 hour

### Expected Behavior

The seek bar can be used to go back in a live video up to its start.

### Issue Labels

usability issue

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Ubuntu 22.04

### Installation Method

.AppImage

### Primary API used

Local API

### Additional Information

The seek bar in live videos has only been added in this version which is nice however, it has this limitation.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-10-30 12:26
Duplicate of #661

This is working as expected, we never said that you could go back more than an hour (if you check the iOS HLS pull request linked in the changelog you'll notice that it explicitly says 1 hour) and the feature request to go back further is still open. Be happy that you can even go back an hour.

**Closed** 2024-10-30 12:26 UTC
Labels: bug, B: usability
