### ISSUE TITLE
[Feature Request]: Download Progress Bar/Indicator

### ISSUE THREAD

**Issue by Techngro** [FreeTubeApp/FreeTube#5299] opened 2024-06-20 22:38 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When you download through the app, after you click download and select a file, there is a popup about the video starting, but no other indicator that it is actually downloading. And since you have no idea how long it will take, you can't really figure out if it's still downloading or there was an error.

### Proposed Solution

Please add a progress indicator (something as simple as changing the download icon to a download meter) so that it is clear that the video is actually downloading.

### Alternatives Considered

I don't think an alternative is necessary.

### Issue Labels

display more information to user

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-20 22:51
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2110

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-06-20 22:51 UTC
Labels: enhancement, E: display more information
