### ISSUE TITLE
[Bug]: Local API, videos started jumping up and down

### ISSUE THREAD

**Issue by EngieSSB** [FreeTubeApp/FreeTube#5458] opened 2024-07-24 17:07 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When clicking on a video, it will load up, and then it will starting bouncing the screen up and down. This only happens when it is on the Local API. It works fine when I switch to Invidious API.

### Expected Behavior

The screen should not be bouncing, making a video unplayable unless it is switched to Invidious API

### Issue Labels

API issue, feature stopped working, inconsistent behavior

### FreeTube Version

v0.21.1 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

https://github.com/user-attachments/assets/cb22a815-e42d-4332-ac78-58c04a05b268

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by HairyMilkshakes** [comment] 2024-07-24 17:23
thought it was my crack but it was just freetube

**Comment by OothecaPickle** [comment] 2024-07-24 17:26
#5456

**Comment by crisjolliff** [comment] 2024-07-24 18:11
Duplicate bug, but yes, +1 to reporting this bug.

**Comment by CelularBat** [comment] 2024-07-24 18:30
The same has happened today on my forked version, which is based on FreeTube v0.20.0

I suspect in may has something to do with Youtube breaking youtubei.js ,giving unprecedented results when trying to fetch video, and FreeTube GUI reacting to those result. 

The "bouncing" comes from changing size of video window inside video player.

**Comment by 4yman-0** [comment] 2024-07-24 18:31
#5459 #5457 #5456

make sure you searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues.

**Comment by gsalvatella** [comment] 2024-07-24 18:44
@CelularBat do you think they're doing this on purpose?

**Comment by jordanmontt** [comment] 2024-07-24 18:52
Same here, I have this error:


```
DASH request error at URL: https://rr1---sn-25glenlz.googlevideo.com/videoplayback?expire=1721868657&ei=EU2hZqCoOuXnvdIPl-eRiAY&ip=146.70.194.75&id=o-AHAu5BvNEKE5n26jkFvAqylM9oHCEYPGJ5vp2G1Jew1m&itag=136&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313%2C394%2C395%2C396%2C397%2C398%2C399%2C400%2C401&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=5B&mm=31%2C29&mn=sn-25glenlz%2Csn-25ge7nzr&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=1530000&bui=AXc671IWyNAYBKZSMBVPvTfIk796ZTeDmSKW7zs_vNz8CMkshN3SzcOhR792V-ykZOXh9T1j9TUOG8TZ&spc=NO7bATMOeYD2Zv_yeF317XFUWh9WnpU0b3YVS8PHgzK_0ma-4girqC8VSvs-&vprv=1&svpuc=1&mime=video%2Fmp4&ns=uhnAQV4D5lFdRq7X0CALcBQQ&rqh=1&gir=yes&clen=690693879&dur=7035.320&lmt=1717394562419251&mt=1721846724&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=4532434&n=HmTXsCZ5sKHRB7XOP7&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAPXyZi9hBS1TR-tCPRDjq6Hrg4oo2l7KUGnqqPHkaIMdAiBUjVLuSTPKPy0iL4Cl_zAhLGiOpoPvAVr8BkEJwimG8A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAOE1TRQIGcJW3-vQOG5-1ozk56nx6DfUYimdTkX4jnHZAiEA9vWKvsxeWDzUo88GoTca3GbmFXmmI4d5GRwLXJ7ASf4%3D&cver=2.20240111.09.00&cpn=b0ZT4ea3mxAbdSI-
```

**Comment by birb7** [comment] 2024-07-24 18:59
i had the exact problem as #5459 so i thought to switch to a different instance, but then it transformed into this... MINUS switching APIs. every single API is doing this

**Comment by MaxGripe** [comment] 2024-07-24 19:22
+1

**Comment by mierdev** [comment] 2024-07-24 20:00
+1

**Comment by SkyTheGreatOne** [comment] 2024-07-24 20:08
I can confirm that this is also in the latest Nightly Build. (v0.21.1-nightly-4581 Beta) For now I am using Invidious API.

**Comment by reterkha** [comment] 2024-07-24 20:36
Have the same issue.    Using FreeTube-bin 0.21.1-1 from the AUR.

**Comment by KPCOFGS** [comment] 2024-07-24 20:47
Same issue with the latest release on Linux Mint

**Comment by Thundertheidiot** [comment] 2024-07-24 20:51
Same issue here, using FreeTube v0.21.1 Beta from nixpkgs unstable.

**Comment by root574** [comment] 2024-07-24 20:54
Same issues. Freetube v0.21.1 Beta

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-24 21:06
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5456

[Temporary workaround](https://github.com/FreeTubeApp/FreeTube/issues/5456#issuecomment-2248897869)

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-24 21:06 UTC
Labels: bug, B: feature stopped working, B: inconsistent behavior, B: API issue

**Comment by h1pp13p373** [comment] 2024-07-29 01:32
Same here, changing api also fixed.  I'm on Ubuntu 24.04, freetube 0.21.1 beta
