### ISSUE TITLE
[Feature Request]: Make the video area always the active one

### ISSUE THREAD

**Issue by nigelpyjamas** [FreeTubeApp/FreeTube#2195] opened 2022-04-12 05:12 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Right now, when clicking on a video and making it full screen with the full screen button, arrow keys and fast-forward/rewind functions do not work. I need to click twice on the screen (once to make it "active", which pauses it, and another time to de-pause it) so that key functions are attributed to the video, and not another area of the program.

Furthermore, when I click on the full screen button to leave full screen, the same problem happens. I need to click twice (slowly so not to make it full screen) to have function keys work on the video.

Oh, and the same problem applies to the full window button as well.

### Proposed Solution

Make the video area always the active one when clicking on full screen or full window buttons.

### Alternatives Considered

None

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-04-13 22:59
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/766

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-04-13 22:59 UTC
Labels: enhancement, E: improvement existing feature
