### ISSUE TITLE
[Feature Request]: Hide Shorts

### ISSUE THREAD

**Issue by crisp5** [FreeTubeApp/FreeTube#2655] opened 2022-10-01 15:11 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

My Subscriptions page is flooded with Youtube Shorts. It has become a trend with certain creators to post long form content (podcasts, stream VODs) followed by highlights in the form of shorts. I usually watch/listen to the longer videos anyways, so the Shorts are just a nuisance.

### Proposed Solution

I propose adding a "Hide Shorts" toggle to the Subscription Settings section. If enabled, Shorts would not be shown in the Subscriptions page.

### Alternatives Considered

I originally thought of adding this to the Distraction Free Settings, but I wanted to make it clear the setting is only targeting the Subscriptions page. I think they should still show up elsewhere (e.g., channel pages, search results, Recommended videos), but other users should voice their opinions before the developers start implementing the feature.

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-10-01 15:26
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2008

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-10-01 15:26 UTC
Labels: enhancement, U: doesn't follow template, E: new optional setting
