### ISSUE TITLE
[Bug]: Failing to consistently load comments on videos

### ISSUE THREAD

**Issue by Xindaris** [FreeTubeApp/FreeTube#5894] opened 2024-10-18 16:58 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Lately I've found that, when opening a video, Freetube will frequently report there are "no comments available". But the video _does_ have comments; if you use the back and forward buttons a few times to reopen the video it will eventually load them. This is not with any one particular video, but all of them.

### Expected Behavior

It should load comments the first time it opens the video. Or at least have a way to independently retry loading the comments without having to close and reopen the entire video.

### Issue Labels

content not loading

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-18 17:19
Duplicate of #5880

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-18 17:19 UTC
Labels: bug, B: content not loading
