### ISSUE TITLE
Trying to view comments redirects to page to search results instead

### ISSUE THREAD

**Issue by Victor239** [FreeTubeApp/FreeTube#973] opened 2021-01-22 17:43 UTC
**Behavior of the program**
On any video when I try to view the comments it'll instead redirect the page to a search results page instead.

**Expected behavior**
Should show comments and not redirect. 

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to 'https://youtu.be/heBgvcXgkNw' for example
2. Click on 'Click to View Comments'
3. It'll redirect the page to a search results page instead for ARPGs (it's the same results for every video I try to view comments on)

**Environment Information (please complete the following information):**
 - OS Version: Kubuntu 20.04 LTS
 - FreeTube version: v0.11.1 Beta
 - Installation Method (If applicable): Flatpak
 - Primary API Used: Local API

**Comment by PrestonN** [comment] 2021-01-22 17:46
Duplicate of #943

**Closed by PrestonN** 2021-01-22 17:46 UTC
Labels: bug
