### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by James-Fire** [FreeTubeApp/FreeTube#5295] opened 2024-06-20 13:35 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When switching videos (Like in a playlist), freetube exits fullscreen. It happens both when setting fullscreen using F or the UI button.

1. Add 2 videos to a playlist
2. Play the first video/Enter fullscreen
4. Let the video finish and move to the next one in the playlist.

### Expected Behavior

I would expect fullscreen to be maintained through the entire playlist.

### Issue Labels

visual bug

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Windows 10 Home 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-20 14:40
Duplicate of #2295

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-06-20 14:40 UTC
Labels: bug, B: visual
