### ISSUE TITLE
[Feature Request]: Time format setting

### ISSUE THREAD

**Issue by chrrybmb64** [FreeTubeApp/FreeTube#4843] opened 2024-04-03 00:53 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I want freetube to use 24 hour time but my locale uses 12 hour time. I want to change the time format while keeping my locale the same.

### Proposed Solution

Add a dedicated time format setting where users can choose whether they want 24hr time or 12hr time regardless of their locale.

### Alternatives Considered

n/a

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-03 10:30
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4156

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-03 10:30 UTC
Labels: enhancement, E: new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-03 20:30
We cant make this issue happen if that one isnt solved. It would be way easier to switch between formats if that is implemented. This is an extension to that issue so i recommend you to post a comment over there with this extra requirement
