### ISSUE TITLE
[Feature Request]: Please consider using the piped network

### ISSUE THREAD

**Issue by Raj2032** [FreeTubeApp/FreeTube#2615] opened 2022-09-25 08:52 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Currently freetube exposes our IP address to Google/YouTube.

### Proposed Solution

I wish freetube would use the [piped network](https://github.com/TeamPiped/Piped) like [libretube](https://github.com/libre-tube/LibreTube) does as our IP is still being exposed to Google.

Yes there is TOR network however that is slow.

### Alternatives Considered

-

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-09-25 09:10
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1527

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-09-25 09:10 UTC
Labels: enhancement, E: new feature

**Comment by absidue** [comment] 2022-09-26 07:20
@Raj2032 You can switch to the Invidious API and set FreeTube to proxy the videos through the Invidious instance that you are using. Proxying the videos will probably be noticably slower than streaming them directly from Google. You have to decide if speed is more important to you than Google seeing your IP address.

**Comment by Raj2032** [comment] 2022-09-26 12:11
@absidue Didn't realise that, well thanks mate :)
