### ISSUE TITLE
[Windows 7, 8 & 8.1] 0.15.1 crashes upon video playback (very beginning, reproducable)

### ISSUE THREAD

**Issue by Leza89** [FreeTubeApp/FreeTube#1886] opened 2021-11-12 00:15 UTC
**Behavior of the program**

- Freetube crashes as soon as any video is played 
- it goes to the player environment, starts the playback 
- image freezes at 0:00 or 0:01 of the video and program is reported as not responding
- sound is playing for 2-10 seconds while Freetube is reported as unresponsive, then stops

**Expected behavior**
Video playback without Freetube crashing and being unresponsive.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to 'any video (for example https://youtu.be/mefTPTD-p6k)
2. wait for video to load and begin playing
3. See error

**Screenshots/DevConLogs**
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/FreeTube/resources/app.asar/dist/index.js.map: Unexpected end of JSON input

![Bild_2021-11-12_011403](https://user-images.githubusercontent.com/40437661/141387038-93adc564-48cd-49da-a0c3-0c6c6878f4f8.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 7 SP 1 all patches
 - FreeTube version: 0.15.1 beta
 - Installation Method (If applicable): Win-x64 installer .exe
 - Primary API Used: Local API, also tried with Invidious API

**Comment by PrestonN** [comment] 2021-11-12 02:09
Hey there, before we test this further, could you please run this test and return back with the results?

Please try [this](https://github.com/FreeTubeApp/FreeTube/actions/runs/1441922213) build and attempt to watch a video. Let me know if it crashed.

Then please try [this](https://github.com/FreeTubeApp/FreeTube/actions/runs/1444754116) build and do the same thing.

My guess is that it might have something to do with the new Electron release and Windows 7. If the first build works and the second one does not then that very well seems to be the case. If both of these builds return the same result then we'll have to dig further.

**Comment by PrestonN** [comment] 2021-11-12 02:14
Just did a search and found [this](https://github.com/electron/electron/issues/31762) issue posted a couple of days ago. Looks like it's an Electron issue. We'll have to wait for this to be fixed by the devs upstream.

**Comment by Leza89** [comment] 2021-11-12 03:03
> Hey there, before we test this further, could you please run this test and return back with the results?
> 
> Please try [this](https://github.com/FreeTubeApp/FreeTube/actions/runs/1441922213) build and attempt to watch a video. Let me know if it crashed.
> 
> Then please try [this](https://github.com/FreeTubeApp/FreeTube/actions/runs/1444754116) build and do the same thing.
> 
> My guess is that it might have something to do with the new Electron release and Windows 7. If the first build works and the second one does not then that very well seems to be the case. If both of these builds return the same result then we'll have to dig further.

It seems to be like you suspected:

Freetube installed from 

- `freetube-0.15.0-nightly-1322-setup-x64.exe` works fine
- `freetube-0.15.0-nightly-1324-setup-x64.exe` crashes with the same error as stated in OP

**Comment by PrestonN** [comment] 2021-11-12 03:27
Unfortunately yes. I'm not keen on downgrading Electron again as the latest release has fixed a variety of issues even if it introduced this one. The Electron devs are aware of the issue though so hopefully a fix will be out soon.

For now, my only suggestions are to either downgrade FreeTube (Either to v0.15.0 or to the nightly build I linked) or to change your OS (Regardless if that's to Windows 10, Linux, etc). We try to stay as close to the latest release of Electron as possible so we'll push out a fix as soon as we can. Keeping an eye on that issue I linked will give you a better idea of when it'll be fixed. Sorry I don't have better news for you.

**Comment by Leza89** [comment] 2021-11-12 11:31
I understand; Thank you for the explanation and FreeTube in general.

**Comment by mistersector** [comment] 2021-11-13 04:45
Win7 also here.
Confirmed freetube-0.15.1-win-x64-portable crashes
Confirmed freetube-0.15.0-nightly-1322-setup-x64 works fine
Confirmed freetube-0.15.0-nightly-1324-setup-x64 crashes
Will continue to use freetube-0.15.0-RC-1239-win

**Comment by KNAPPI23** [comment] 2021-11-15 09:59
Win7 crashes on Playback with Build #1334

**Comment by gpilot24** [comment] 2021-11-21 20:28
Hello:

Add my system to the list.

Version 15.0 did not crash. Some of the issues addressed by the v 15.1 update were present on v15.0, buffering issues mostly.

I can open the app (15.1) on my PC. All menus and search appear to work. As soon as I click on a video link, the video image (still image) will open and the audio plays for about 3 seconds. Then I get a windows crash message as pasted below. The video never begins.

Please don't ask me to (down)grade to Win 10. When I can't continue to use Win7,its Linux for me. I wont get into it here for this problem report. All updates to Jan 2020 are on the Win7 x64 SP1 system. Please contact me if you need more information. The system is running a core i7 6700 with 8 Gb ram. Locally stored videos play fine on vlc.

Problem signature:
Problem Event Name: APPCRASH
Application Name: FreeTube.exe
Application Version: 0.15.1.0
Application Timestamp: 6189679d
Fault Module Name: FreeTube.exe
Fault Module Version: 0.15.1.0
Fault Module Timestamp: 6189679d
Exception Code: c0000005
Exception Offset: 00000000004e0903
OS Version: 6.1.7601.2.1.0.256.48
Locale ID: 1033
Additional Information 1: 6bf1
Additional Information 2: 6bf10fa8aa45fd539e87ea3d291a83a9
Additional Information 3: 0fd1
Additional Information 4: 0fd1cbae0a4ab9b20165920fef308b6f

The system is running a core i7 6700 with 8 Gb ram.

**Comment by CypherpunkSamurai** [comment] 2021-12-05 17:55
I'm having the same problems on `v0.15.1 Beta` downloaded from the website.

**Comment by Tiltowait2** [comment] 2021-12-13 20:12
Windows 8.1 crashes as well.

**Comment by Cat333Pokemon** [comment] 2021-12-15 17:35
Windows 8.1 as well, same crashes. I can also confirm the 1322 nightly build works fine.

**Comment by SrIzan10** [comment] 2021-12-22 18:57
Windows 7 guy here, first link works, i'm trying out the second one, this will  be edited when done...

**Comment by VideoVoyeur** [comment] 2022-01-12 01:10
I am in a similar but nor identical situation.  I cannot run the latest version of FreeTube and the build that works for @Leza89 did not work for me.  Instead, [freetube-0.15.0-nightly-1322-win-x64-portable](https://github.com/FreeTubeApp/FreeTube/suites/4307272290/artifacts/112498985) seems to be working for me.

**Comment by rhinoduck** [comment] 2022-01-12 13:57
Electron [v15.3.5](https://github.com/electron/electron/releases/tag/v15.3.5) which should be fixing this has been released. PR  https://github.com/FreeTubeApp/FreeTube/pull/2006 exists for the update so this will hopefully be history soon.

**Comment by Tiltowait2** [comment] 2022-01-26 00:19
Please let us know the moment any build that fixes this problem is released.  There are other problems with 0.15.1 that I've held off reporting in the hope that the next version obsoletes them.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-02-01 21:13
This will be addressed soon in our upcoming release.

**Closed** 2022-02-06 20:07 UTC
Labels: bug, electron being electron, OS: windows
