### ISSUE TITLE
back button?

### ISSUE THREAD

**Issue by superfreeman1989** [FreeTubeApp/FreeTube#308] opened 2019-07-22 14:13 UTC
It would be useful to add a back button for situations such as going back to a channel you browsed to, preferably retaining scroll position of previous pages as well!

**Comment by PrestonN** [comment] 2019-07-22 15:31
This is a duplicate of #15 

It's on the roadmap. There is currently no ETA though.

**Closed by PrestonN** 2019-07-22 15:31 UTC
