### ISSUE TITLE
 [Bug]: FreeTube Playback Stops just after the 6 Hour Mark on long videos...

### ISSUE THREAD

**Issue by FYBSI** [FreeTubeApp/FreeTube#4349] opened 2023-11-18 13:32 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Not much to say here.  I use long sleep type videos that are 8, 10 or 12 hours long and freetube always stops playback a couple minutes after 6 hours, then just displays the buffering loop and never gets going again.  Must let the video playback from beginning and reach the 6 hour mark on its own to reproduce. Thanks!

### Expected Behavior

I expect the videos to play through to their end.

### Issue Labels

usability issue

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 11 Professional (x64) Version 22H2 (build 22621.2715)

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-18 13:38
Duplicate of #4160

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-18 13:38 UTC
Labels: bug, B: usability
