### ISSUE TITLE
[Bug]: Made play/pause logo more transparent

### ISSUE THREAD

**Issue by onlineapps-cloud** [FreeTubeApp/FreeTube#6080] opened 2024-11-03 09:22 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Hi, when i need to pause some video and read from screen some information i cannot to do, because play / pause logo is too much and not very transparent, it's possible to made it little smaller and more transparent?
![image](https://github.com/user-attachments/assets/c9a89b9f-2d24-4d20-bd1d-3a08758704d3)

### Expected Behavior

made logo more smaller and more transparent

### Issue Labels

usability issue

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Linux (Debian 11)

### Installation Method

.AppImage

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-11-03 09:35
Duplicate of #5951

**Closed** 2024-11-03 09:36 UTC
Labels: bug, U: duplicate, B: usability
