### ISSUE TITLE
Hope to increase account synchronization

### ISSUE THREAD

**Issue by yesyestoday2020** [FreeTubeApp/FreeTube#1526] opened 2021-07-17 13:33 UTC
Hope to increase account synchronization

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-17 15:52
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/144#issuecomment-408072780

**Closed** 2021-07-17 18:21 UTC
Labels: enhancement
