### ISSUE TITLE
App doesn't load vides from both local api and fallback api 

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [FreeTubeApp/FreeTube#1448] opened 2021-06-25 08:30 UTC
environment:
-windows 10
freetube v0.13.1

expected behavior - load videos from local api or invidious api as a fallback
current behavior :
- local api : Error: Status code: 404
- invidious api : {"error":"Could not extract video info. Instance is likely blocked."} (any instance , no difference)

This behavior has started to appear 2-3 days ago and became consistent (100% attempts blocked) today.

**Comment by robguthm** [comment] 2021-06-25 09:00
This is happening 100% of the time with or without fallback enabled.

**Comment by StoppingBuck** [comment] 2021-06-25 10:26
This is a duplicate of #1438

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-06-27 02:09
Hotfix update is available to download:

https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.13.2-beta

https://freetubeapp.io/#download

This should resolve this issue.

**Closed** 2021-06-27 04:24 UTC
Labels: bug

**Comment by AlekseiKhatkevich** [comment] 2021-06-27 07:03
ok, thanks for maintenance!
