### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SiF12022** [FreeTubeApp/FreeTube#2070] opened 2022-02-09 22:12 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Use to play age restricted content, but after installing this new Release v0.16.0 Beta it leaves the screen blank and nothing can be seen.
Even after uninstalling v0.16.0 and re-installing an older version, i can no longer watch my fav self-defence vids that sometimes have violence in them, hence the age restriction. So I'm now having to use "nsfw" to watch vids that worked fine on FreeTube before i installed Release v0.16.0 Beta

### Expected Behavior

It used to play all vids but not since Release v0.16.0 Beta install

### Issue Labels

API issue

### FreeTube Version

Release v0.16.0 Beta

### Operating System Version

windows 10 64bit

### Installation Method (If applicable)

.exe

### Last Known Working FreeTube Version (If Any)

0.15.1

### Primary API used

Local API

### Additional Information

Error: Status code: 410

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by bachig26** [comment] 2022-02-09 23:18
Duplicate of #2055

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-02-10 00:11
Actually a duplicate of #1296

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-02-10 00:12 UTC
Labels: bug, B: API issue
