### ISSUE TITLE
[Bug]: seems to be no longer working for 18+ Youtube Videos

### ISSUE THREAD

**Issue by overcomeMonster** [FreeTubeApp/FreeTube#2155] opened 2022-03-28 21:58 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Search for a youtube video that is marked as 18+
2. Click on it
3. These error messages will be shown: "Error: Status code: 410", "{"error":"This video may be inappropriate for some users."}"
The video cannot be played. Maybe Youtube has changed something?

### Expected Behavior

If it was somehow possible to make it work again, to play any Youtube video on FreeTube, it would be fantastic.

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Windows 10 Home, Version: 21H2

### Installation Method (If applicable)

.exe

### Last Known Working FreeTube Version (If Any)

Not known

### Primary API used

Local API

### Additional Information

![image](https://user-images.githubusercontent.com/102557315/160493938-1645c611-8ab2-4568-ba74-e971785d911d.png)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-03-28 22:36
Duplicate of #1296

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-03-28 22:36 UTC
Labels: bug, B: content not loading, B: API issue
