### ISSUE TITLE
Feature Request:  Please remove the PLAY Button in the center when a video is paused.

### ISSUE THREAD

**Issue by cocoonkid** [FreeTubeApp/FreeTube#1761] opened 2021-09-29 10:25 UTC
Please, let's get rid of it.  It's bugging me since month every time I stop a vid to make a screenshot or try to read things in details.

Thank you so much!

![CleanShot 2021-09-29 at 12 23 59@2x](https://user-images.githubusercontent.com/43231640/135251275-b0d1a913-c9ac-48cc-a11a-299623f12ece.jpg)

**Comment by ChunkyProgrammer** [comment] 2021-09-29 10:31
Related: #347

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-29 11:21
No its a duplicate of that issue. This has already been implemented. Go to player settings and disable 'Display Play Button In Video Player'.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-09-29 11:21 UTC
Labels: enhancement, doesn't follow template

**Comment by cocoonkid** [comment] 2021-09-30 11:45
Oh wow, my apology.  This is great. Thanks!

**Comment by faxotherapy** [comment] 2025-02-02 18:09
Context: macOS, FreeTube version: 0.23.1.

I de-activated “Display Play Button In Video Player“ and still the player buttons are still present when video is paused, preventing me from viewing the bottom of the video (e.g., for replicating commands in Terminal). Currently, I have to make a screen capture without pausing the video so I can have the time to see what's at the botton of the video.
