### ISSUE TITLE
[Bug]: Picture in Picture does not switch to the next video automatically as expected using auto play, and the video plays in regular mode instead.

### ISSUE THREAD

**Issue by Grossley** [FreeTubeApp/FreeTube#2473] opened 2022-08-12 14:40 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Enable picture-in-picture on a video.
2. Enable auto play.
3. The next video plays in regular mode and the picture in picture box remains but is black and the play button in that box is unresponsive. 

Additionally, trying to refocus onto the Freetube application via clicking the icon on the taskbar only pulls up the black picture-in-picture window instead of the main window. 

### Expected Behavior

The next video would play in the already existing picture-in-picture window instead of the main program window. 

### Issue Labels

content not loading, feature stopped working, inconsistent behavior, usability issue

### FreeTube Version

Release v0.17.1 Beta, d959a45

### Operating System Version

Windows 11 Home

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

![image](https://user-images.githubusercontent.com/42724744/184378673-5292d569-085b-4781-9465-3ef51148734a.png)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-09-09 00:15
There isnt a black box anymore but is the pip window is still static. So marking this as a

duplicate of https://github.com/FreeTubeApp/FreeTube/issues/953

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-09-09 00:15 UTC
Labels: bug, B: content not loading, B: usability, B: feature stopped working, B: inconsistent behavior
