### ISSUE TITLE
[Feature Request]: Display a mini player in windows top when scrolling through comments

### ISSUE THREAD

**Issue by GLLM** [FreeTubeApp/FreeTube#3179] opened 2023-02-09 19:56 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I play a video, then I want to see the description as well as browse the comments section.

![image](https://user-images.githubusercontent.com/3989573/217921965-225c0a94-b6f2-46c5-a517-d76cae7f0b81.png)

When scrolling through comments or description, I cannot see the video being played since the display port for the video itself is hidden at the top.

_Video not visible anymore_
![image](https://user-images.githubusercontent.com/3989573/217922158-ff00f2ec-93c1-4ef6-953c-42443987813a.png)

I'd like to be able to see comments while still watching the video

### Proposed Solution

Maybe have a small video preview (a bit like PiP) integrated in the main window (e.g. instead of the green rectangle below), which would enable watching the video while scrolling thru comments and/or description

![image](https://user-images.githubusercontent.com/3989573/217922703-51ba001f-226e-499e-99e6-5f171c75abc6.png)

### Alternatives Considered

I don't see how I can workaround this, unless using the PiP everytime ... which is not user friendly (unless it is automated, and exited from when scrolling back up)

### Issue Labels

ease of use improvement, visual improvement

### Additional Information

Thanks a lot !!
GLLM

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-02-11 15:13
i consider this a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1028

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-02-11 15:13 UTC
Labels: enhancement, E: visual improvement, E: ease of use improvement

**Comment by GLLM** [comment] 2023-02-12 08:59
Oh my ! You are right. Sorry for that ...

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-02-12 11:59
@GLLM no worries :)
