### ISSUE TITLE
Increase caption height

### ISSUE THREAD

**Issue by NomadVibes88** [FreeTubeApp/FreeTube#6408] opened 2024-12-18 09:50 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

(Not an issue.) On YouTube, the subtitles/captions have a bit of "height" to them. I want it on Freetube.

### Proposed Solution

Increase subtitle/caption height.

### Alternatives Considered

None.

### Issue Labels

ease of use improvement, improvement to existing feature, visual improvement

### Additional Information

FreeTube:
![2024-12-18 15_42_06-AI is ruining the internet - FreeTube](https://github.com/user-attachments/assets/59bef04c-8978-456a-92f8-32d18225adf3)

YouTube:
![2024-12-18 15_45_22-The Online Gambling Epidemic - YouTube and 1 more page - Profile 1 - Microsoft​ ](https://github.com/user-attachments/assets/bd0fc0fa-fae4-4d32-b6f2-3d50828ed1ba)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-18 12:45
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5961

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-18 12:45 UTC
Labels: enhancement, E: improvement existing feature, E: visual improvement, E: ease of use improvement
