### ISSUE TITLE
middle click new window open got broken?

### ISSUE THREAD

**Issue by je-vv** [FreeTubeApp/FreeTube#1020] opened 2021-02-07 00:42 UTC
Using freetube v. 0.11.2 from AUR (Artix/Arch GNU/Linux).

Sometimes middle click on URL withing freetube works by opening the URL in a new freetube window.  Ideally it should be rather a tab, but that's an already existent feature request.  Unfortunately, most of the time it doesn't work.

What's worse, when getting the middle click to open a new freetube window, it happes that the original freetube window moves to the "trending" view, instead of staying where it was, which is really wrong.

Also, I can't remember, if working before, but middle click should also work with right click and selecting opening in another window/tab.  But right click is not working...

I'm filing this as a bug, and not a feature request, because at least middle click was working fine, always opening a new window (not ideal, but it was working), and also the original freetube window where the mid click was performed, used to remain where it was...  So this is a regression in behavior...

Thanks !

**Comment by fabianski7** [comment] 2021-02-20 12:59
Same bug in the master. 
This is quite annoying, especially since it is the only way I can open more than one video at the same time in freetube

**Comment by GilgusMaximus** [comment] 2021-02-20 19:32
Hi,
so first of all could you please provide your operating systems and build versions? @je-vv @fabianski7 
I just tested it on channel names and it works on Windows 10.

Additionally these new windows are in fact not a feature we introduced or support actively, but rather is a feature of Chromium.

**Comment by fabianski7** [comment] 2021-02-20 20:49
> Hi,
> so first of all could you please provide your operating systems and build versions? @je-vv @fabianski7
> I just tested it on channel names and it works on Windows 10.
> 
> Additionally these new windows are in fact not a feature we introduced or support actively, but rather is a feature of Chromium.

I'm using the aur freetube-git package. built in the last commit

**Comment by je-vv** [comment] 2021-02-20 22:56
> Hi,
> so first of all could you please provide your operating systems and build versions? @je-vv @fabianski7
> I just tested it on channel names and it works on Windows 10.
> 
> Additionally these new windows are in fact not a feature we introduced or support actively, but rather is a feature of Chromium.

The data of OS was already provided on the 1st line of my original post @GilgusMaximus, but I'm copying it again here:

> Using freetube v. 0.11.2 from AUR (Artix/Arch GNU/Linux).

There came an upgrade to v. 0.11.3, but still the same thing.

**Comment by GilgusMaximus** [comment] 2021-02-21 11:55
@je-vv Thanks for sharing again. That is why we provide templates to use, so it is easier to identify the necessary information.

I suspect that there is a weird bug in the code again, which somehow leads the app to switch pages. We had that with the comment already. That is probably not as easy to fix as just rewriting the module, because as I mentioned, this is a feature of Chromium, not our own code. 

So yeah, at we'd need some more investigation into this. Maybe an update of a package version changed some behavior on Arch Linux.

**Comment by PrestonN** [comment] 2021-03-01 01:11
This should be fixed with #1073. The problem is that certain builds were sending CLI parameters to the app and FreeTube tried to handle them as if they were a YouTube URL. By default, if it doesn't find a URL, it would search that item instead. The PR removes the ability to search via the CLI which should fix this.

**Closed by PrestonN** 2021-03-01 01:11 UTC
Labels: bug
