### ISSUE TITLE
Open new freetube button does not show in small window mode

### ISSUE THREAD

**Issue by peepo5** [FreeTubeApp/FreeTube#1413] opened 2021-06-14 10:44 UTC
**Behavior of the program**
In small window mode, open new freetube window button dissapears. This might be intended for some reason, but i dont see a need for it disappearing as there is plenty space at the top of the window. 

**Expected behavior**
Change window size smaller until the side bar goes to the bottom. The copy window button up top left will disappear. It should be next to arrows.

**Screenshots**
Normal:
![image](https://user-images.githubusercontent.com/72892531/121880220-aa434d00-cd05-11eb-98a4-a87863e053d1.png)
Small (without open freetube window icon):
![image](https://user-images.githubusercontent.com/72892531/121880325-c7781b80-cd05-11eb-95c0-05f9af629c91.png)
This should have the open new window icon^

**Environment Information:**
 - FreeTube version: [e.g. 0.9.0]

**Comment by GilgusMaximus** [comment] 2021-06-15 19:56
Well yes. This is as intended by the original PR. the reasoning behind this was that such a small window will likely only occur on small devices where multiple windows are not very handy. But I must admit that it is happening very early. So changing it later is definitely a good idea

**Comment by peepopoggers** [comment] 2021-06-16 11:43
I understand why this is a thing, but presuming the window size is small only because the screen size is small does not make sense. If you have multiple windows open at once, and you resize it smaller, you need to maximize before you can open a new window. I think it should stay there all the way.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-14 19:56
Closing, converted to a feature request in #4155 because this isnt a bug

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-10-14 19:56 UTC
Labels: bug
