### ISSUE TITLE
Enhancement: Playlists in result page (search)

### ISSUE THREAD

**Issue by Gumichan01** [FreeTubeApp/FreeTube#24] opened 2018-03-08 15:29 UTC
It would be very appreciated if playlists can be added in the result page when I search for a specific content.

In the version I tested (Release 0.1.3 Beta), I can just get videos in my result page, even if I tried to get a specific playlist.

Just try with those keywords: ```touhou ost```. Youtube returns videos and playlist as requested. FreeTube just returned videos.

**Comment by PrestonN** [comment] 2018-03-08 15:40
Hello.  This is already planned.  I just haven't had time to implement this yet.  I will try to get working on it at some point in the near future.

I am going to close this issue though because this is a duplicate of #11.  Thank you! :)

**Closed by PrestonN** 2018-03-08 15:40 UTC
