### ISSUE TITLE
[Feature Request]: Seekbar takes up way too much space, covers information in video

### ISSUE THREAD

**Issue by Optekah** [FreeTubeApp/FreeTube#5967] opened 2024-10-27 17:32 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

![Screenshot (58)](https://github.com/user-attachments/assets/d0e29bd8-a75a-4ab2-8887-3c375c75ee6b)

### Proposed Solution

Move it down

### Alternatives Considered

.

### Issue Labels

ease of use improvement

**Comment by riverpiers** [comment] 2024-10-27 22:34
@Optekah I think I know why the scroll bar is double-height. There's an additional icon in the bottom-right corner that is outside the visible area of the full screen. It only becomes visible after pressing the 'd' shortcut (like the stats for nerds on YouTube) or after clicking in that corner on the player with the left mouse button. It then appears and changes its appearance depending on its direct click.
![10-27-2024](https://github.com/user-attachments/assets/2583b3ad-416e-428c-8bb1-1517c66532ea)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-27 22:49
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5955

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-27 22:49 UTC
Labels: enhancement, E: ease of use improvement
