### ISSUE TITLE
Request/Idea For a Added Function: Hide/Block videos or channel to hide recommended & scheduled videos from view

### ISSUE THREAD

**Issue by via80HD** [FreeTubeApp/FreeTube#1836] opened 2021-10-18 22:10 UTC
Just an idea I had that would be helpful, its not a big deal but Ive been meaning to put it here for a while now so figured I would while I was thinking about it. So, one thing that is super annoying to me is when creators will schedule a live stream or something for like a week or so in the future, that video will sit at the top of the video list everyday until that stream is actually started and the video has the big red LIVE box on it even though its not live it just makes it look that so I will end up clicking it and realizing that its not a real stream. So if there could be a way to work a block/hide this video function to get it out of the way that would be awesome. The hide/block button would also work for my other annoyance (Im not complaining, the app is great youtube just sucks)  is the recommended video list, I see the same few videos over and over and over and Im just sick of seeing the little kid from ET doing the ugly crying face from his audition for the movie, just bugs me haha, so yeah the block/hide feature would be sick. I know the mobile app sky tube has that function, Im not sure if knowing that will be any help to you all but just in case. Once again, this is no big deal it doesn't ever have to be done, Ill use the app regaurdless but if you happen to just want to do it, I'd appreciate it. 

Imagine seeing this face on every video you watch...not cool lol
![image](https://user-images.githubusercontent.com/84550322/137813271-6529b6c5-b8e0-4af6-b479-8b7edcd3bdf1.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-19 00:21
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1070

There is a PR open to hide Live streams
https://github.com/FreeTubeApp/FreeTube/pull/1456

**Closed as completed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-10-19 00:21 UTC
Labels: U: doesn't follow template
