### ISSUE TITLE
[Feature Request]: Option to maintain video setting during current session

### ISSUE THREAD

**Issue by skrshe** [FreeTubeApp/FreeTube#2263] opened 2022-05-24 10:41 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

video player settings (such as resolution, captions and view mode) are reset after opening a new video from playlist/recommended

### Proposed Solution

Add an option to keep video player setting changes when opening a new video in current session (possible including open in new window)

### Alternatives Considered

none

### Issue Labels

ease of use improvement, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-05-24 10:55
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1696 https://github.com/FreeTubeApp/FreeTube/issues/1695 https://github.com/FreeTubeApp/FreeTube/issues/1326 https://github.com/FreeTubeApp/FreeTube/issues/1236 https://github.com/FreeTubeApp/FreeTube/issues/1192 https://github.com/FreeTubeApp/FreeTube/issues/927 

And there is already a lengthy discussion going on over here https://github.com/FreeTubeApp/FreeTube/pull/1281

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-05-24 10:55 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement

**Comment by skrshe** [comment] 2022-05-24 11:26
sorry, thought I checked properly
