### ISSUE TITLE
[Bug]: "Sort By" doesn't sort videos at all

### ISSUE THREAD

**Issue by galure** [FreeTubeApp/FreeTube#2941] opened 2022-12-10 16:01 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Check a channel
2. Try to sort channel's videos by "most popular" or "oldest"
3. Nothing changes, videos are still sorted by Newest

### Expected Behavior

Should sort the videos

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Fedora 36

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.17.0

### Additional Information

![image](https://user-images.githubusercontent.com/108539468/206863925-011fd7b4-16a1-4b41-aceb-0ecaf90b25a1.png)
![image](https://user-images.githubusercontent.com/108539468/206863938-52b90840-35b7-463e-b453-eaa0fe706922.png)
![image](https://user-images.githubusercontent.com/108539468/206863948-89b896ac-daf9-4d2e-a637-b27ec3f2c17c.png)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by galure** [comment] 2022-12-10 16:13
Ok, invidious has the same problem... I  wasn't able to find a bug report on that matter (neither in open nor closed issues), but I'm pretty sure there is one already, right?

**Comment by absidue** [comment] 2022-12-10 18:14
duplicate of #2887

**Closed by absidue** 2022-12-10 18:14 UTC
Labels: bug, B: inconsistent behavior
