### ISSUE TITLE
[Feature Request]: Fast forward and backward

### ISSUE THREAD

**Issue by Lucasy0113** [FreeTubeApp/FreeTube#4630] opened 2024-02-04 15:48 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Fast forward and backward video 5 seconds or more seconds with the middle mouse wheel.

### Proposed Solution

I would like to be able to fast forward and rewind video by 5 or more seconds with the middle wheel of the mouse.

### Alternatives Considered

I would like to be able to fast forward and rewind video by 5 or more seconds with the middle wheel of the mouse.I would like to be able to fast forward and rewind video by 5 or more seconds with the middle wheel of the mouse.

### Issue Labels

new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-02-04 18:10
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1855

**Comment by Lucasy0113** [comment] 2024-02-05 17:43
> Duplicate of #1855

I'm sorry, but it's not the same. I am referring to the ability to move forward or backward in the same video, and not to change the playback speed of the video.

**Comment by absidue** [comment] 2024-03-10 09:42
Unless I am misunderstanding your feature request, it sounds like you are describing the existing `Skip by Scrolling Over Video Player` setting in the `Player Settings` section.

**Closed** 2024-03-25 00:00 UTC
Labels: enhancement, U: Waiting for Response from Author, E: new optional setting, E: new feature
