### ISSUE TITLE
[Bug]: API Error cannot read "text"

### ISSUE THREAD

**Issue by Alatarius** [FreeTubeApp/FreeTube#4826] opened 2024-03-29 04:53 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open Freetube on PC
2. Receive thios error: Local API Error: TypeError: Cannot read properties of undefined (reading 'text')
3. Invidious Error: undefined
4.  Not understanding what this error is

### Expected Behavior

Expected behavior is to open freetube without any error messages

### Issue Labels

API issue

### FreeTube Version

Have no idea since it's not listed anywhere in the settings

### Operating System Version

Windows 11 Pro

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

don't know I just downloaded this a week ago

### Additional Information

n/a

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-03-29 06:27
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4811

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-03-29 06:27 UTC
Labels: bug, B: API issue
