### ISSUE TITLE
[Feature Request]: Tabs

### ISSUE THREAD

**Issue by klutt** [FreeTubeApp/FreeTube#4138] opened 2023-10-12 07:49 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There is a reason why web browsers has tabs and do not rely on separate windows. I think the same applies here. 

### Proposed Solution

Add tabs to Freetube. 

### Alternatives Considered

The only alternative I can see is multiple windows, but that already exists. 

### Issue Labels

display more information to user, ease of use improvement, visual improvement

**Comment by absidue** [comment] 2023-10-12 08:16
Duplicate of #333

**Closed** 2023-10-12 08:16 UTC
Labels: enhancement, E: visual improvement, E: display more information, E: ease of use improvement
