### ISSUE TITLE
[Bug]: Changing from fullscreen-mode after every video

### ISSUE THREAD

**Issue by o0Julia0o** [FreeTubeApp/FreeTube#4369] opened 2023-11-22 00:11 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Start a video in fullscreen
2. the next video comes up after 5 seconds
3. the video is not played in fullscreen

### Expected Behavior

the video should play in fullscreen as the video before

### Issue Labels

usability issue

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 10

### Installation Method

Portable

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-22 00:42
Duplicate of #2295

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-22 00:42 UTC
Labels: bug, B: usability
