### ISSUE TITLE
[Bug]: Shows message "This channel does not currently have any shorts" for all channels

### ISSUE THREAD

**Issue by BeatlesNo1** [FreeTubeApp/FreeTube#5772] opened 2024-09-30 14:07 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Go to any channel, click on shorts and you will see that message.

### Expected Behavior

I expect to see the list of shorts under that tab.

### Issue Labels

feature stopped working

### FreeTube Version

0.21.3 Beta

### Operating System Version

Arch based, Garuda Linux with KDE on wayland

### Installation Method

.AppImage

### Primary API used

Local API

### Additional Information

**FreeTube:**
![FreeTube](https://github.com/user-attachments/assets/f523d81f-819c-4eca-be21-97827e80490b)
**YouTube**
![YouTube](https://github.com/user-attachments/assets/e290db69-ce1c-46e8-8b1f-524c9144428e)
64bf30-db51-44ee-9bfb-f80c43e16aa6)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-09-30 14:11
Duplicate of #5685

**Closed** 2024-09-30 14:11 UTC
Labels: bug, B: feature stopped working
