### ISSUE TITLE
Self-hosted browser / PWA version

### ISSUE THREAD

**Issue by Whayme** [FreeTubeApp/FreeTube#657] opened 2020-10-13 08:39 UTC
[As mentioned previously](https://github.com/FreeTubeApp/FreeTube/issues/456#issuecomment-599720595), the rewrite should allow for self-hosting at some point in the future.  It would be great to see a PWA implemented for mobile usage.

This would be particularly helpful for iOS users who don't get the luxury of just using NewPipe instead.

**Comment by PrestonN** [comment] 2020-10-13 13:51
Duplicate of #633

**Closed by PrestonN** 2020-10-13 13:51 UTC
Labels: enhancement
