### ISSUE TITLE
[Feature Request]: Individual Volume Settings

### ISSUE THREAD

**Issue by TheNyneR** [FreeTubeApp/FreeTube#2192] opened 2022-04-11 20:17 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

One global setting for volume level is not necessarily enough since some channels have very low volume while others are very loud.
It would be nice to be able to override the default volume on a per channel or per profile basis.

### Proposed Solution

A volume setting could be added to `profiles.db` to set the volume per profile.
Additionally a channel specific database file could be added to specify the default level on a per channel basis.

### Alternatives Considered

Default volume setting used, however more fine grained control would be preferred.

### Issue Labels

ease of use improvement, improvement to existing feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-04-11 20:23
duplicate of #1996

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-04-11 20:23 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: ease of use improvement
