### ISSUE TITLE
[Feature Request]: Exempt music videos from saving watched progress

### ISSUE THREAD

**Issue by NonRidiculousAdjective** [FreeTubeApp/FreeTube#5683] opened 2024-09-10 16:47 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Music in playlists tends to start mid-videos.

### Proposed Solution

Either from metadata if YouTube has tags or something like that for it or from length (under 5min - since those videos are most of the time watched in one sitting anyway) exempting video so that its watch progress isn't recorded.

### Alternatives Considered

Turning off progress saving altogether

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-11 09:46
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2237

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-11 09:46 UTC
Labels: enhancement, E: ease of use improvement

**Comment by NonRidiculousAdjective** [comment] 2024-09-11 12:24
> duplicate of #2237

Sort of but the solution is different, if one can't detect if a video is a music video, then what about just not saving progress of videos shorter than 5 minutes?

**Comment by NonRidiculousAdjective** [comment] 2024-09-11 21:17
> That is encapsulated in #447 #609

Oh, ok, though at least the first one seems to be dead for the last 4 years...
