### ISSUE TITLE
[Feature Request]: Support for WebM

### ISSUE THREAD

**Issue by avishj** [FreeTubeApp/FreeTube#4495] opened 2023-12-29 22:57 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Due to lack of WebM support, 1080p+ is rare to find, and generally 1080p being played ends up lower quality than WebM would be. I understand the limitations of the http-streaming module of VideoJS. I wanted to enquire if v2.x of that module as was suggested on an older thread has added support for WebM or is there any other video player that can work with WebM files? I haven't tested it, but would using an external player allow for WebM to be streamed?

### Proposed Solution

If there is an availability of alternate video player / module and development time is required, I would be happy to contribute.

### Alternatives Considered

None, I don't have any except opening the video with Firefox + uBlock Origin + Enhancer for YouTube.

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-12-30 01:15
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2013

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-12-30 01:15 UTC
Labels: enhancement, E: visual improvement
