### ISSUE TITLE
Improve SponsorBlock integration

### ISSUE THREAD

**Issue by m3thm4th** [FreeTubeApp/FreeTube#5017] opened 2024-04-25 19:02 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Would it be possible to select segments and submit them to the SponsorBlock database and to see statistics of time saved like in the browser extension?

### Proposed Solution

.

### Alternatives Considered

.

### Issue Labels

improvement to existing feature

**Comment by jasonhenriquez** [comment] 2024-04-25 19:23
> Would it be possible to select segments and submit them to the SponsorBlock database...

See our answer [here](https://github.com/FreeTubeApp/FreeTube/issues/2170#issuecomment-1093549872).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-25 20:12
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2170

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-25 20:12 UTC
Labels: enhancement, E: support external software
