### ISSUE TITLE
[Bug]: Translation of video titles

### ISSUE THREAD

**Issue by lolafur** [FreeTubeApp/FreeTube#4128] opened 2023-10-10 17:00 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When switching to some channels, the language of video titles changes. On one channel the video titles are translated into Russian, on another channel the video titles are automatically translated into English.
For example, type Denis Yelisevich channel in the search. And go to the "Videos" section. The titles to the videos are **changed to** **English**.
I search for Kuplinov Play and click on the "Videos" section. The video titles are **automatically translated into Russian**.
The language of the FreeTube interface itself is Russian.
![Снимок экрана 2023-10-10 195740](https://github.com/FreeTubeApp/FreeTube/assets/43754210/54778bad-91b6-4341-afe8-dd0075f875bd)
![Снимок экрана 2023-10-10 195825](https://github.com/FreeTubeApp/FreeTube/assets/43754210/fa251afc-d84a-4bb4-b240-4da06e0bee87)

### Expected Behavior

Translation of all video titles into Russian. 

### Issue Labels

text/string issue

### FreeTube Version

v0.19.1

### Operating System Version

Windows 10 version 19045

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-10 17:14
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2049

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-10-10 17:14 UTC
Labels: bug, B: text/string
