### ISSUE TITLE
Comments Will Not Load

### ISSUE THREAD

**Issue by LordSicarious** [FreeTubeApp/FreeTube#1536] opened 2021-07-22 12:08 UTC
Attempting to Load Comments on FreeTube v0.13.2 Beta on any video produces the following errors:

- (Local API) TypeError: Cannot read property 'continuationContents' of undefined
- (Invidious API) undefined 

Issue persists through reboots, but seems entirely contained to comments.
I did find a single video once where comments were able to load, but I was unable to reproduce that behaviour.

Operating System:
Linux Mint 20.2 Cinnamon (Kernel: 5.4.0-77-generic)

![FreeTube Comment API Failure](https://user-images.githubusercontent.com/87661780/126636142-8f07b897-81d4-45ac-9f3d-f39286507b0c.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-22 13:39
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1490

@PrestonN

**Closed** 2021-07-22 14:26 UTC
Labels: bug
