### ISSUE TITLE
[Feature Request]: History sync via eg. Nextcloud

### ISSUE THREAD

**Issue by scarleo** [FreeTubeApp/FreeTube#3969] opened 2023-08-29 05:51 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Would be nice to be able to replicate watch history between devices

### Proposed Solution

Have automatic watch history exports happen at some time interval which exports the file to a path in the file system, so I can write it to for example a synced Nextcloud folder. And have the option to import a history file automatically from a given path in the file system on client startup.

### Alternatives Considered

Maybe add the ability to upload directly to different cloud storage providers?

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-09-06 15:18
Basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/370

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-09-06 15:18 UTC
Labels: enhancement, E: new feature
