### ISSUE TITLE
Feature Request: Show dislike counter

### ISSUE THREAD

**Issue by Git-Forked** [FreeTubeApp/FreeTube#1951] opened 2021-12-19 20:44 UTC
Despite Google having removed this from YouTube pages, it can still be found using the API. 
Proof of that can be seen by testing this Firefox plugin which restores the dislike counter: 
https://addons.mozilla.org/en-US/firefox/addon/return-youtube-dislikes/

**Comment by Git-Forked** [comment] 2021-12-19 20:47
PS:  Here is the source code page, if you want to read through it and see how they accomplished it: 
https://github.com/Anarios/return-youtube-dislike

**Comment by absidue** [comment] 2021-12-20 22:13
Duplicate of #1927

**Comment by absidue** [comment] 2021-12-20 22:16
Before implementing support for their API it I think it needs to be discused with them to get their approval as it will cause a significant uptick in trafic to their API and database.

**Closed** 2021-12-21 14:20 UTC
Labels: enhancement

**Comment by Git-Forked** [comment] 2021-12-23 07:00
> Before implementing support for their API it I think it needs to be discused with them to get their approval as it will cause a significant uptick in trafic to their API and database.

**It's YouTube's API, not the extensions.  I'm sure Google can handle any traffic you throw at it.**

**Comment by absidue** [comment] 2021-12-23 08:05
@Git-Forked You must be using a different YouTube data API than the rest of the world, considering YouTube hasn't been returning dislikes in the API since the 14th of December. So yes it runs off someones server and database, that are funded through donations. More people using the API will result in higher costs for them. 

You can make your message bold and add thumbs down emojis to my messages, that doesn't mean you are correct though.

**Comment by constraintAutomaton** [comment] 2022-01-26 21:25
for the sake of reference it's written on there website https://returnyoutubedislike.com/faq

Q: Where dos the extension get it's data
A :  A combination of archived data from before the offical YouTube dislike API shut down, and extrapolated extension user behavior. [...] The extension collects the video ID of the video you are watching, fetches the dislike (and other fields like views, likes etc) using our API. The extension then displays the dislike count and ratio on the page. If you like or dislike a video, that is recorded and sent to the database so an accurate dislike count can be extrapolated.
