### ISSUE TITLE
[Feature Request]: Ability to Watch With Dual subtitles for Language Learners

### ISSUE THREAD

**Issue by WatchOfTime** [FreeTubeApp/FreeTube#5083] opened 2024-05-07 16:17 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Sometimes people will watch a video with 2 separate subtitles, one in their native language and another one in their target language. It's supposed to help with language learning. I used to use an extension for this. But since I've been using freetube, I don't use it anymore, 

### Proposed Solution

Have a player setting to enable the dual subtitle feature, then you should have the ability to enable 2 different subtitle options at once. One should be on top of the other.

### Alternatives Considered

I've also considered using SM Player's SMTube feature, since it has dual subs.

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-07 16:30
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4133

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-05-07 16:30 UTC
Labels: enhancement, E: new optional setting

**Comment by WatchOfTime** [comment] 2024-05-07 16:32
My bad, I didn't see when I searched subtitles for some reason.
