### ISSUE TITLE
filtering API proposal

### ISSUE THREAD

**Issue by rebelga** [FreeTubeApp/FreeTube#1272] opened 2021-05-12 13:07 UTC
A flexible means of filtering videos (minimally) by channel and title would give users (or at least advanced users) control to better focus their experience.  Any means at all to do this would be hugely helpful (e.g. REST, calling external functions, regex lists) although a programmatic interface would be most powerful (e.g. a boolean function passed channel, title, views, age, etc.).

This would allow users to remove channels they never want to see and topics they are not interested in, providing results that are far more tailored to what they would actually watch.

A refinement to this would be a button to then show unfiltered results (perhaps with the would-be filtered videos marked "FILTERED" similar to the current "WATCHED" label.

**Comment by GilgusMaximus** [comment] 2021-05-13 17:34
Could you please add the following part to #95 as the rest is a duplicate of it and this is indeed a good idea to add to that
> A refinement to this would be a button to then show unfiltered results (perhaps with the would-be filtered videos marked "FILTERED" similar to the current "WATCHED" label.

**Closed by GilgusMaximus** 2021-05-13 17:34 UTC
Labels: enhancement
