### ISSUE TITLE
[Bug]: why theres duplicates in quality of video?

### ISSUE THREAD

**Issue by ArshErgon** [FreeTubeApp/FreeTube#2520] opened 2022-08-31 15:14 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

I mean, I open the video and tried to down the quality of the video, but i see there
```
1080p
1080p
720p
720p
....
144p
144p
```
I'm on Ubuntu Budgie 2022

### Expected Behavior

```
1080p
1080p
720p
720p
....
144p
144p
```
to
```
1080p
720p
....
144p
```

### Issue Labels

visual bug

### FreeTube Version

v0.17.1 Beta

### Operating System Version

Ubuntu Budgie 2022

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment] 2022-08-31 15:28
duplicate of #1344

**Closed by ChunkyProgrammer** 2022-08-31 15:28 UTC
Labels: bug, B: visual

**Comment by ArshErgon** [comment] 2022-08-31 15:30
@ChunkyProgrammer oh sorry, I dont know that.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-31 15:32
it is not solved thats why the issue is still open

**Comment by maplepy** [comment] 2022-09-15 23:02
@ArshErgon check my issue
