### ISSUE TITLE
[Feature Request]: Ability to import your own styles

### ISSUE THREAD

**Issue by MStankiewiczOfficial** [FreeTubeApp/FreeTube#6413] opened 2024-12-19 16:26 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently, we have several styles already uploaded to FreeTube and they cannot be modified in any way.

### Proposed Solution

I propose to give the ability to import your own style file (e.g. as a CSS), so that the community could share their own styles and easily add them.

### Alternatives Considered

Alternatively, it can be given the option to simply paste the own style in CSS format into the text box.

### Issue Labels

new feature, new optional setting, visual improvement

**Comment by ChunkyProgrammer** [comment] 2024-12-19 16:44
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/38

**Closed as not planned by ChunkyProgrammer** 2024-12-19 16:44 UTC
Labels: U: duplicate, enhancement, E: new optional setting, E: visual improvement, E: new feature
