### ISSUE TITLE
[Bug]: Won't play videos

### ISSUE THREAD

**Issue by NDMarriott** [FreeTubeApp/FreeTube#5514] opened 2024-08-02 13:14 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When attempting to play a video loading fails on both local api and fallback
![Capture](https://github.com/user-attachments/assets/39f9705f-9c84-41f8-82b2-9b61c16d164c)

### Expected Behavior

Video starts playing

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

v0.21.2 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.2 Beta

### Additional Information

Worked until 1st August 2024

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-08-02 13:47
Duplicate of #5502

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-08-02 13:47 UTC
Labels: bug, B: content not loading, B: feature stopped working
