### ISSUE TITLE
[Bug]: Cannot search by channel name within playlist

### ISSUE THREAD

**Issue by vF360** [FreeTubeApp/FreeTube#4889] opened 2024-04-06 18:30 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

In the old version of freetube, I could easily load all the saved videos from a specific channel, but this is no longer the case in 0.20.0 as only the titles of the videos are indexed.

### Expected Behavior

I expected only saved videos from a given channel to appear when I entered that channel's name in the search box.

### Issue Labels

feature stopped working, inconsistent behavior

### FreeTube Version

v0.20

### Operating System Version

Windows 10 LTSC 1809

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-06 19:17
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4857

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-06 19:17 UTC
Labels: bug, B: feature stopped working, B: inconsistent behavior
