### ISSUE TITLE
RSS fetching fails with 0.11.3

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#1038] opened 2021-02-16 17:48 UTC
**Behavior of the program**

With `Fetch Feeds from RSS`  enabled feed updates fails with `Error: Status code 404

**Expected behavior**

With `Fetch Feeds from RSS`  enabled feed updates work.

**To Reproduce**

1. Open FreeTube
2. Click on Settings
3. Enable `Fetch Feeds from RSS`
4. Go to subscription section
5. refresh the feed.  
6. Update attempts to start but  `Error: Status code 404` is displayed a number of times on screen  and the progress bar bottom of screen never completes

**Environment Information (please complete the following information):**
 - OS: Debian
 - OS Version: 10
 - FreeTube version:0.11.3
 - Installation Method (If applicable): deb
 - Primary API Used: Local API

**Comment by Svallinn** [comment] 2021-03-05 18:51
@grrrrr 
I can't reproduce with the latest version at the very least.
There are problems when pulling from Invidious (different for every instance), but that's on their end, not from here.
Check to see if the bug still persists

**Comment by GilgusMaximus** [comment] 2021-04-10 20:17
As there has been no follow up encounters I am going to close this. Feel free to reopen if it still happens with the newest version

**Closed by GilgusMaximus** 2021-04-10 20:17 UTC
Labels: bug
