### ISSUE TITLE
[Feature Request]: Remeber volume across sessions

### ISSUE THREAD

**Issue by Moritzer** [FreeTubeApp/FreeTube#4627] opened 2024-02-01 12:10 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When closing freetube it doesnt remember the volume for the next startup.

### Proposed Solution

Add an option to enable or disable remembering the volume across sessions.

### Alternatives Considered

Alternative solution would be using the volume manager but I think its easier to just remember it as not every operating system can manage the volume of individual programms as well as others.

### Issue Labels

new optional setting

**Comment by jasonhenriquez** [comment] 2024-02-01 14:31
Closing this as a duplicate of #2295

**Closed by jasonhenriquez** 2024-02-01 14:31 UTC
Labels: enhancement, E: new optional setting

**Comment by absidue** [comment] 2024-02-04 08:48
@Moritzer In case you didn't already know about it, you can configure the default volume in FreeTube's player settings.
