### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Dex94** [FreeTubeApp/FreeTube#3716] opened 2023-06-29 14:56 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

video frame seems to refresh in loop continuosly without permitting to play the video. If play button is pressed, the frame refresh itself and it returns to the original status (stopped)

### Expected Behavior

play the video

### Issue Labels

content not loading, visual bug

### FreeTube Version

nightly-3064

### Operating System Version

Ubuntu

### Installation Method

.AppImage

### Primary API used

Invidious API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-06-29 15:33
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3457

That one will be reopened when we have definitive  proof of buffering issues

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-06-29 15:33 UTC
Labels: bug
