### ISSUE TITLE
[Bug]: Video player `TypeError: Cannot read properties of undefined (reading 'id')`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3843] opened 2023-08-03 13:54 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to https://youtu.be/UJeSWbR6W04
2. See that video doesnt play and u get an error
```
TypeError: Cannot read properties of undefined (reading 'id')
    at renderer.js:2:1727435
    at Array.forEach (<anonymous>)
    at a.getVideoInformationLocal (renderer.js:2:1727390)
```

### Expected Behavior

No error and video plays normally

### Issue Labels

content not loading, inconsistent behavior

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/ccefdb34a100a45e23fc832d473baff12a3b9ba7

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by rjdg14** [comment] 2023-08-05 17:27
Have you been having the issue when searching that I've been having where Freetube is receiving the error "Local API Error: TypeError: filtlerWrapper is not iterable", meaning that it falls back to Invidious which gives far less accurate results? FreeTube at my end has not been able to make many proper search requests to YouTube for months and the problem is yet to be fixed. The Android equivalent NewPipe, which is being actively updated (FreeTube has not had a notable update in a few months) still works perfectly.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-08-05 22:42
@rjdg14 switch to the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by rjdg14** [comment] 2023-08-06 13:53
> @rjdg14 switch to the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

This seems to have fixed the issues. The main stable release has not been updated in about 9 months and in that time there have probably been API changes leading to compatibility issues, though these issues have been fixed on the newer Nightly builds.

**Closed as completed** 2023-08-20 03:32 UTC
Labels: bug, B: content not loading, B: inconsistent behavior
