### ISSUE TITLE
Can't load comments

### ISSUE THREAD

**Issue by Tiltowait2** [FreeTubeApp/FreeTube#1523] opened 2021-07-16 05:36 UTC
**Behavior of the program**
Comments do not display.  When clicking "Click to View Comments", the program says:

Local API Error (click to copy): TypeError: Cannot read property 'continuationComments' of undefined

Falling back to Invidious API

Invidious API Error (click to copy): undefined

**Expected behavior**
Comments should display

**To Reproduce**
Click "Click to View Comments"

**Link to video**
All videos

**Screenshots**
n/a

**Environment Information (please complete the following information):**
 - OS: Windows 
 - OS Version: 8.1
 - FreeTube version: v0.13.2 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Additional context**

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-16 11:01
@PrestonN Duplicate of #1490

**Closed** 2021-07-16 13:41 UTC
Labels: bug
