### ISSUE TITLE
[Feature Request]: Refresh subscription in background

### ISSUE THREAD

**Issue by mgth** [FreeTubeApp/FreeTube#2063] opened 2022-02-08 22:07 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Subscription videos page is cleared on button refresh pressed

### Proposed Solution

It would be nice to be able to still see videos while refreshing list, 

### Alternatives Considered

even better if we could watch a video while refreshing.

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-02-08 22:16
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2026

**Closed** 2022-02-08 22:16 UTC
Labels: enhancement, E: ease of use improvement
