### ISSUE TITLE
Pragmatic-Keyboard navigation enhancement 

### ISSUE THREAD

**Issue by kajdo** [FreeTubeApp/FreeTube#1966] opened 2021-12-26 18:01 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Please describe clear and concise of what the problem is. Ex. I'm always frustrated when [...]

Yes, this isn't a bug. I checked the raised issues before creating that one and it seems that there already exist a lot of issues related to keyboard-shortcuts/-navigation. I'm using Freetube on a mpc in my living room and love it, but I usually don't navigate with a mouse/touchpad (most of the time I spend in kodi).

**Describe the solution you'd like to see implemented**
Please give a clear and concise description of what you want to happen.

I would like to see a possibility to use the keyboard for the most used actions (search, scroll, start playing a specific video in-app-player or mpv, load more, change category ...).

Considering, that FreeTube is based on electron, it might be an option to integrate Vimium extension within the application. It's open source and might solve lots of requests in the issue tracker.

Sure, it wouldn't be a perfect UX solution - but for people who don't bother it would be "invisible" and for people like me it would be a gamechanger in UX :) 

**Describe alternatives you've considered**
Are there other ways to solve the problem? Please give a clear and concise description of any alternative solutions or features you might have considered.

Alternatively there is always the option to jump into the rabbit hole and implement keyboard shortcuts for "everything" and make it configurable via the settings. 

This would of course be the perfect setup - but I still think in terms of effort to implement vs. benefit for the user gets, an integration of vimium would win by far

**Additional context**
Add any other context about the feature request here.

here is the github page of vimium to check: https://github.com/philc/vimium
it's licensed under MIT License, there shouldn't be a blocker from that perspective

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-10-09 16:32
Hi @kajdo, i just want to clarify if i interpreted your request correctly

> I would like to see a possibility to use the keyboard for the most used actions (search, scroll, start playing a specific video in-app-player or mpv, load more, change category ...).

So u want something to solve this.

> Considering, that FreeTube is based on electron, it might be an option to integrate Vimium extension within the application. It's open source and might solve lots of requests in the issue tracker.

And u would like to have vimium to be the solution for this

**Comment by kajdo** [comment] 2022-10-21 13:32
@efb4f5ff-1298-471a-8973-3d47447115dc vimium is just a suggestion, but yes - I think it would be great to have a possibility to use freetube with keyboard only

as stated in my original msg I think vimium would maybe a possibility to save some time to come up with sane shortcuts and because of the open source nature of vimium it might be a possibility

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-10-26 09:11
> @efb4f5ff-1298-471a-8973-3d47447115dc vimium is just a suggestion, but yes - I think it would be great to have a possibility to use freetube with keyboard only

For this part im closing this one in favor of https://github.com/FreeTubeApp/FreeTube/issues/2691

> as stated in my original msg I think vimium would maybe a possibility to save some time to come up with sane shortcuts and because of the open source nature of vimium it might be a possibility

This part is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1864

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-10-26 09:11 UTC
Labels: enhancement

**Comment by kajdo** [comment] 2022-11-02 16:45
agree ... duplicate of #1864 - must have missed it when i created this issue

don't relly agree with #2691 - since it will not enable to use keyboard only -- one would have to press (guess) 17-18 times tab to finally end up having the action in focus one wants to trigger ... this will work, but not in a pragmatic usable way

but yes - as mentioned, it is definitely a duplicate of 1864 ... sorry for that

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-11-02 17:10
Not sure i understand why u disagree with #2691. 

They also dont like tabbing 10+ times to get the action they want in focus.

So for these actions where an user needs to tab allot they are proposing to fix it with keyboard shortcuts. So the user dont have to tab all the way through the application.
