### ISSUE TITLE
[Feature Request]: Make Back button actually go back to where I was instead of default start.

### ISSUE THREAD

**Issue by Gevaarlijk** [FreeTubeApp/FreeTube#3506] opened 2023-05-07 20:14 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When I open a channel, scroll down to the oldest vid that I have not yet seen, watch it and then hit the back button I am then returned to the start of the channel with the newest vids and I have to scroll all the way down again to view the next vid in chronological order.

### Proposed Solution

Please make it so that I am back where I actually left of when I hit back instead of somewhere else.

### Alternatives Considered

None.

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-05-07 20:29
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2446

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-05-07 20:29 UTC
Labels: enhancement, E: ease of use improvement
