### ISSUE TITLE
[Feature Request]: Allow a user to choose the sorting order of playlists items

### ISSUE THREAD

**Issue by CrazzzzyChipmunk** [FreeTubeApp/FreeTube#4858] opened 2024-04-04 11:58 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

**It is impossible to choose a video order in the playback list.**

In the previous version of Freetube, had the order "date added (newest)" as the default one on its only playlist. Now the new version has an inverted order (i.e., "date added (oldest)") and does not give ways to choose the order.

For example. When the user prefers to see new added videos in the upper part of the list (sorting: “date added (newest)”), Freetube becomes unsuitable for large playback lists as it takes a lot of time for the user to scroll down and expand all the elements of the playlist (every time). It's too annoying!

By the way, YouTube has this function.

### Proposed Solution

Allow a user to choose the sorting order. At least, as this is implementened in Youtube.
![3](https://github.com/FreeTubeApp/FreeTube/assets/117451463/953c1995-6bd7-41ff-83ca-0b860866782c)

### Alternatives Considered

At least, as this is implementened in Youtube

### Issue Labels

ease of use improvement, improvement to existing feature, new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-04 12:00
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4856

Check comments

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-04 12:00 UTC
Labels: enhancement, E: improvement existing feature, E: ease of use improvement, E: new feature
