### ISSUE TITLE
TypeError: Cannot read property '4' of null

### ISSUE THREAD

**Issue by Arnab771** [FreeTubeApp/FreeTube#809] opened 2020-11-26 08:32 UTC
**Behavior of the program**
Every time I open a video in a playlist an error shows up saying it's falling back to invidious API. The video still plays though.

**To Reproduce**
Click any video in a playlist.

**Screenshots**
[![Screenshot](https://i.postimg.cc/HLCC9HKy/Screenshot-from-2020-11-26-13-53-52.png)](https://postimg.cc/bZLMzXqy)

**Environment Information (please complete the following information):**
 - OS: Pop OS 
 - OS Version: Pop Os 20.04
 - FreeTube version: 0.9.2
 - Installation Method (If applicable): Flathub
 - Primary API Used: Local API

**Additional context**
I think it's also worth mentioning that I have my default playback quality set to 360p but it never seems to work. Also a different error is shown when you use an url to open a video. Something like URL must be a string sometimes.

**Comment by GilgusMaximus** [comment] 2020-11-26 11:57
Playlists seem to have a general problem at the moment, but we are waiting for fixes of upstream modules.
The 360p not working can be read at #595 .
I can't reproduce the error with the URL. At least with the videos I use. So please provide some links to make it easier to check

Additionally I'd like to add, that each bug and problem should go into a new issue. Otherwise no one can keep track of them and check whether they are already open somewhere and when we close issues.

**Comment by Arnab771** [comment] 2020-11-26 15:14
> Additionally I'd like to add, that each bug and problem should go into a new issue. Otherwise no one can keep track of them and check whether they are already open somewhere and when we close issues.

Thanks. I was going to put the playback setting bug but it was already open as you mentioned but I thought it might be related to that. I'm not getting the other error while opening a video by URL not now so I can't really say what it was exactly.

>I can't reproduce the error with the URL. At least with the videos I use. So please provide some links to make it easier to check

Here is the URL to that playlist: 
1. https://youtube.com/playlist?list=PLkZJWF6pr5ezSQum5ekss1tpkue-YuPty
2. https://youtube.com/playlist?list=undefined

**Comment by PrestonN** [comment] 2020-11-28 16:42
This is an issue with the upstream module we're using for playlists.  Please see [this](https://github.com/TimeForANinja/node-ytpl/issues/84) issue for updates.  Since this is an issue with the module and not with FreeTube, I'll be closing this here.

**Closed by PrestonN** 2020-11-28 16:42 UTC
Labels: bug
