### ISSUE TITLE
Possibility to take screenshots (without playbutton icon in video)

### ISSUE THREAD

**Issue by o-xy** [FreeTubeApp/FreeTube#1878] opened 2021-11-06 21:50 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I'd like to take screenshots of a paused video

**Describe the solution you'd like to see implemented**
Usually I take screenshots with the print screen key and the windows internal function, which is fine. But the videoplayer in Freetube shows that playbutton-icon in the middle of the video (see screenshot) when the video is paused. Could that icon (optionally) be removed?

**Describe alternatives you've considered**
Alternatively or additionally it would be a nice feature if it would be possible to take screenshots with a keyboard shortcut directly. E.g. one can configure a directory and when pressing the shortcut key a screenshot with videoname, id and current timestamp as filename is saved

**Screenshots**
![image](https://user-images.githubusercontent.com/93843777/140624777-de5348c1-679d-4ec4-9f12-9bfb79221777.png)

**Additional context**
none

**Comment by ChunkyProgrammer** [comment] 2021-11-06 23:11
You can hide the play button through settings. Settings > Player Settings > Display Play Button In Video Player
![image](https://user-images.githubusercontent.com/78101139/140626428-bbf0dbae-8614-4a72-8fc6-b7728e6ee20e.png)

**Comment by o-xy** [comment] 2021-11-07 00:34
ah, thanks! totally missed that option. Makes FreeTube even better than I already though it was :)

Though, having an interal screenshot option I described as alternative still would be a really nice feature, thus I'd keep the issue open for now

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-11-07 00:54
In my opinion the alternative isn't going to be implemented because all the OS's have a some sort of screenshot program natively build into them. So i don't see a clear benefit into implementing this. Im closing this because it is a

Duplicate of #347

**Closed** 2021-11-07 00:55 UTC
Labels: U: duplicate, enhancement

**Comment by peepopoggers** [comment] 2021-11-07 12:25
I think it could be switched so default is off and it would be "hide play button"
