### ISSUE TITLE
White window and alt control menu bar appears stays forever when middle-clicking on a video

### ISSUE THREAD

**Issue by 7echLife** [FreeTubeApp/FreeTube#1655] opened 2021-09-05 21:52 UTC
**Behavior of the program**
When I middle click a window to open/watch a video in a new window, the window did not load properly. Instead, it shows a white window with the Alt menu bar when pressed (even though it was never pressed) and stays like that forever.

**Expected behavior**
I expected the video and contents to properly load when middle clicking to watch in a new window.

**To Reproduce**
1. Go to any video
2. Middleclick on any video
4. The problem appears, the video never loads in a new window but instead shows a white window with the Alt menu bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/54084841/132142265-a5573dfd-609a-46ca-b491-689765b21ba0.png)

**Environment Information (please complete the following information):**
 - OS: Windows 
 - OS Version: 7
 - FreeTube version: 0.14.0 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: [Local API]

**Comment by jasonhenriquez** [comment] 2021-09-05 22:13
This is a duplicate of #1636. This is likely a bug with the new Electron version, and we are looking into it right now.

**Closed by jasonhenriquez** 2021-09-05 22:13 UTC
Labels: bug
