### ISSUE TITLE
[Bug]: Some videos have a Legacy Formats not supported for this video and Unexpected tokens (1:71) error.

### ISSUE THREAD

**Issue by jmah17** [FreeTubeApp/FreeTube#6332] opened 2024-12-09 19:57 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When trying to watch certain videos, they won't play due to a legacy format not supported error. 
![Screenshot 2024-12-09 115447](https://github.com/user-attachments/assets/1493d01c-17e9-4360-be18-b3000b5d6e97)

### Expected Behavior

Video should play without issues. 

### Issue Labels

content not loading

### FreeTube Version

v0.22.0

### Operating System Version

Windows 11 (23H2) 

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.3

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-09 19:59
duplicate of #6328

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-09 19:59 UTC
Labels: bug, B: content not loading
