### ISSUE TITLE
[Feature Request]: Disable Blinking for Next Video in Playlist

### ISSUE THREAD

**Issue by Tahinli** [FreeTubeApp/FreeTube#5696] opened 2024-09-13 17:45 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hi, 

At the end of the video there is a blinking button says something like "Next video will be played automatically in x seconds" in playlists. Because it's blinking and recreates itself again and again,  it's hard to disable auto play.

### Proposed Solution

Disable blinking for the button.

### Alternatives Considered

I you still want to draw attention to the button. You can change colour opacity or something. In this way it will be still clickable.

### Issue Labels

ease of use improvement

**Comment by absidue** [comment] 2024-09-14 13:32
Duplicate of #2340

**Closed by absidue** 2024-09-14 13:32 UTC
Labels: enhancement, E: ease of use improvement

**Comment by Tahinli** [comment] 2024-09-14 19:15
> Duplicate of #2340

Sorry for duplication, it was very old issue but don't you want to fix ?
