### ISSUE TITLE
Typing "i" into the search bar opens stats for nerds

### ISSUE THREAD

**Issue by Winterhuman** [FreeTubeApp/FreeTube#2072] opened 2022-02-10 15:14 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Go to a video.
2. Click the search bar so it's selected/active.
3. Type "i".
4. See the "stats for nerds" widget open on the video.

### Expected Behavior

Pressing "i" should only trigger stats for nerds when the video is focused, typing in the search bar shouldn't trigger stats for nerds.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Arch Linux

### Installation Method (If applicable)

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-02-10 19:02
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2062

**Closed as completed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-02-10 19:02 UTC
Labels: bug, U: duplicate, B: inconsistent behavior
