### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by RameshShashank46** [FreeTubeApp/FreeTube#1789] opened 2021-10-04 10:57 UTC
After Connecting VPN the FreeTube shows trending according to the region of the VPN we selected, but we can't change the "Region for trending", when we press that, it is not showing the drop down menu to select any country nor we can type there. Can you please fix this in the next update maybe.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-04 11:20
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1644

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-10-04 11:20 UTC
Labels: duplicate, doesn't follow template
