### ISSUE TITLE
freetube fails to find or play video that are not indexed 

### ISSUE THREAD

**Issue by sysdbugfactory** [FreeTubeApp/FreeTube#995] opened 2021-01-30 01:30 UTC
**Behavior of the program**

Freetube does not find video that are not indexed, such as those from interactive game for example this game starts has this introduction video: https://www.youtube.com/watch?v=SVGf6uJ3v1I and is supposed to lead to https://www.youtube.com/watch?v=Hz-oCeQuYJA but there is no way to get freetube to find or play it.
**Expected behavior**
I expect freetube to find and play the video

**To Reproduce**

steps to repeat:
1. use the search box with Hz-oCeQuYJA
or alternatively use the search box with https://www.youtube.com/watch?v=Hz-oCeQuYJA
2. the video that exists and is public on youtube is not found by freetube

alternative steps:
1. watch https://www.youtube.com/watch?v=SVGf6uJ3v1I till the end where a link is supposed to appear
2. no link appears / clicking the link in the description opens a web browser

**Environment Information (please complete the following information):**
 - OS: Manjaro linux
 - OS Version: rolling release
 - FreeTube version: v0.11.2 Beta
 - Installation Method (If applicable): AUR
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment] 2021-02-20 19:44
Closing because this is not a bug.
Links in the description will lead you outwards of FreeTube at the moment.

The video link you provided for the unlisted video works when you paste it into the search bar and search for it. It should open automatically.

![image](https://user-images.githubusercontent.com/34301369/108606769-6e822180-73bc-11eb-9c9c-b18e31d98a2f.png)

**Closed by GilgusMaximus** 2021-02-20 19:44 UTC
Labels: bug
