### ISSUE TITLE
Clicking on "View Comments" takes me away from video

### ISSUE THREAD

**Issue by RagglenLove** [FreeTubeApp/FreeTube#949] opened 2021-01-17 21:45 UTC
I'm running the [Flathub version of FreeTube v0.11.1 Beta](https://flathub.org/apps/details/io.freetubeapp.FreeTube) on Xubuntu 20.04.

**Steps to reproduce:**

Choose a video to play.

![Screenshot_2021-01-18_05-29-51](https://user-images.githubusercontent.com/45503845/104856839-9f9bac00-594f-11eb-8749-4d9755279410.png)

Scroll down and click on "Click to View Comments".

![Screenshot_2021-01-18_05-31-00](https://user-images.githubusercontent.com/45503845/104856879-d1ad0e00-594f-11eb-88ac-d64f63f65419.png)
![Screenshot_2021-01-18_05-31-16](https://user-images.githubusercontent.com/45503845/104856890-e38eb100-594f-11eb-97d9-c45ccf4532b3.png)

However, clicking on "Click to View Comments" takes me here instead.

![Screenshot_2021-01-18_05-31-28](https://user-images.githubusercontent.com/45503845/104856901-f5705400-594f-11eb-9662-39538a4a9839.png)

**Comment by PrestonN** [comment] 2021-01-17 22:06
Duplicate of #943

**Closed by PrestonN** 2021-01-17 22:06 UTC
Labels: bug
