### ISSUE TITLE
Sometimes the video timeline just doesnt want to dissapear

### ISSUE THREAD

**Issue by Richardsilsa** [FreeTubeApp/FreeTube#722] opened 2020-10-25 21:24 UTC
**Behavior of the program**
Sometimes the video timeline will not dissapear, even in fullscreen

**To Reproduce**
It is kinda random ,sometimes happens and other not ,but when it happen it doest hide at all in any video anymore ,also only happens in fullscreen videos ,and disable the "f" buttom to toggle fullscreen 

**Desktop:**
 - OS: Pop!_OS running under xserver
 - FreeTube version: 9.1 beta via flatpak

**Comment by GilgusMaximus** [comment] 2020-10-25 21:27
Closing because duplicate of #695

**Closed by GilgusMaximus** 2020-10-25 21:27 UTC
Labels: bug
