### ISSUE TITLE
[Bug]: Comments not available

### ISSUE THREAD

**Issue by James-Fire** [FreeTubeApp/FreeTube#5889] opened 2024-10-17 18:42 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Various videos show "No comments available for this video", but if you go to that video in a browser, there are comments. Reloading using CRTL-R does not fix this. I noticed this yesterday.

Some videos that don't show comments in Freetube:
https://youtu.be/qQbWCYLCjz0
https://youtu.be/dW0sEl61GQk
https://youtu.be/83ZietQ1W_s

### Expected Behavior

Comments that are on the video are available.

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Win10 22H2 19045.5011

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.3 Beta

### Additional Information

Images of video comment sections in freetube vs firefox:

![image](https://github.com/user-attachments/assets/8dd9a943-937c-4b41-ba76-6bc45fd0827f)
![image](https://github.com/user-attachments/assets/12b85c79-ffa8-4291-afac-186b2221883b)

![image](https://github.com/user-attachments/assets/3dcb2a94-76b2-4914-821c-baed7e38d84a)
![image](https://github.com/user-attachments/assets/027e206a-dcf0-4930-b87c-b72afdf887e7)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-17 19:17
Duplicate of #5880

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-17 19:17 UTC
Labels: bug, B: content not loading, B: feature stopped working
