### ISSUE TITLE
[Bug]: Video plays with Spanish voice over even though I do not live in Spain or speak the language

### ISSUE THREAD

**Issue by 4164696f73** [FreeTubeApp/FreeTube#3742] opened 2023-07-09 08:14 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

[Video](https://youtu.be/mWEE2RJj3YI) has Spanish voice over. I live in the middle of Europe, have locale set to English, using Local API with fallback to Invidious, but that specific video has a random guy translating me everything to Spanish. Watching the video on [Invidious](https://yt.artemislena.eu/watch?v=mWEE2RJj3YI) works fine, so it has to be something with Freetube.
Edit: Seems to be tied to Local API, because another Invidious instance as default API works flawlessly, and it has to be watched through Invidious..

### Expected Behavior

Play the video in original language unless I decide I want it in Spanish (so never because I do not speak that language).

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux 5.15.114-2-Manjaro

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

I've been using Freetube for about a month I believe, and watched perhaps around 1000 (1k) videos in total and this is the first video this happens to me and I have no idea how to disable that. I also have captions off, if that matters (changing it does nothing aside of displaying English text). This is the same video on Freetube and Invidious as well.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-07-09 08:49
duplicate of #2419

Upgrade to the nightlies or wait until the next release.

**Closed by absidue** 2023-07-09 08:49 UTC
Labels: bug
