### ISSUE TITLE
Uncontrolled, undesired quality downgrade on my internet

### ISSUE THREAD

**Issue by doritoshave3sides** [FreeTubeApp/FreeTube#1137] opened 2021-03-23 22:28 UTC
Freetube 0.12 beta version (latest as of writing)

Because I live in the countryside I have a small issue where the internet connection dips from 9000 kbps (9-ish Mbps) to  1000 for just a second or two. This does not impact website videos but i have this strange behavior where freetube is dropping instantly from 1080 to 240 or the crippling 100's p

Behavior of the program:
No matter the video properties about once a day or so I have this behavior. My internet is capable of watching 1440p or better on youtube without disturbances. The problem is that it is hard to document when the (probably wind induced) hitch manifest in my home network. 

Description of what the bug is: 
Freetube seems to over-anticipate a bad connection or seems to have an aggressive switch to lower resolutions. 

Expected behavior:
Freetube should not change during playback and resume the quality selected (I use 1080p as is of my monitor), if there is a small 1 to maybe 2 second hitch despite having a '1080' buffer of more than 80 or so seconds (or whatever is the default for maximum 1080p buffer). 

To Reproduce:
1. Go to any video
2. Play in 1080 or 720 for example
3. Have a small network interference in bandwidth for a short period of time (I don't know if it is possible to do so artificially, maybe using a program like NetLimiter. I haven't tried to replicate it as i am not as advanced)
4. The resolution drops to a stunning pixelated slideshow for 10 seconds or around that long and it sometimes is 'lazy' to increase the resolution.
5. You might be tempted to smash 1080p in the cogwheel in the GUI of the video but that doesn't work immediately too.
6. Whenever freetube feels like 'you are allowed to watch at the higher resolution' it will then increase to 720 or 1080. 

Screenshots:
In here you can see what happens during a 'hitch'. I was watching in 1080 since 0:00 if the video fine.

![Screenshot (1)](https://user-images.githubusercontent.com/47162597/112227230-3d994480-8c27-11eb-9ab1-8e1768bf15d3.png)

Here is what happens what I meant in point # 5 and # 6 when I pressed on the 1080p button. (NOTE: I did not even press 720p button, you can trust me ;-)  ) It highlighted the wrong resolution because it 'thinks' the video is going to DIE because of a internet loss? It took 12.7 seconds to go back to normal resolution this time (used a regular stopwatch)

![Screenshot (10)](https://user-images.githubusercontent.com/47162597/112226335-f3639380-8c25-11eb-9b43-2762e3b1809c.png)

Environment Information:
 - OS: Windows 10 (issue persisted regardless of update of windows; or graphics or net controller drivers)
 - FreeTube version: 0.12 (downloaded from the freetube website)
 - Installation Method (If applicable): .exe (I think this does not matter though)
 - Primary API Used: https://invidious.snopyta.org (but replicable in other instances)

Solution:
in the settings have an option to allow the user to tell freetube to "prefer buffering" instead of dropping the resolution. This easy fix will allow the app to 'do its thing' and despite a hitch, continue from its ALREADY BUFFERED RESOLUTION. (sorry for capitals but I want to highlight this point/fix)

**Comment by GilgusMaximus** [comment] 2021-03-24 11:42
Closing this as this is a duplicate of #595 and #678

**Closed by GilgusMaximus** 2021-03-24 11:42 UTC
Labels: bug

**Comment by doritoshave3sides** [comment] 2021-03-24 12:52
I don't think they are the same bug 

> 
> 
> Closing this as this is a duplicate of #595 and #678

The first bug you mentioned deals with a different problem as the quality is stuck at that user's 720p or whatever it is
The second bug reference has nothing in common. It is not a bug and this enchantment will not fix the problem if you think about it.

**Comment by PrestonN** [comment] 2021-03-24 15:54
Hello @doritoshave3sides, could you please try the latest nightly build and see if that fixes your issue? I agree with Gilgus and believe that this is a duplicate issue of #595.

**Comment by doritoshave3sides** [comment] 2021-03-29 00:27
Im sorry, i dont mean any harm. I taught my topic gotten closed. sorry about that. Iwill delete the other one

**Comment by doritoshave3sides** [comment] 2021-03-29 00:28
> 
> 
> Hello @doritoshave3sides, could you please try the latest nightly build and see if that fixes your issue? I agree with Gilgus and believe that this is a duplicate issue of #595.

thank you Preston. It worked

**Comment by doritoshave3sides** [comment] 2021-03-29 00:30
> 
> 
> Im sorry, i dont mean any harm. I taught my topic gotten closed. sorry about that. Iwill delete the other one

sorry, i cant delete #1143

**Comment by PrestonN** [comment] 2021-03-29 00:30
All good! Nothing to apologize about. As you've noticed, closed issues can still have discussion even when they're closed. Glad that fixed the issue for you. :)
