### ISSUE TITLE
[Bug]: Missing audio device after restart of Pulseaudio or Pipewire-Pulse

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#2540] opened 2022-09-05 13:56 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Restart Pulseaudio service.
2.  Use FreeTube that is already open.
3. Experience problems:
No audio device is visible in the pulseaudio tray and sound can't be played.
There also seems to be stuttering and hanging of the application.

4. Even after a restart of FreeTube there are problems like content not loading, longer loading etc.
5. Reboot of the Computer fixes the issue.

### Expected Behavior

FreeTube should be able to recover from a Pulseaudio restart.

### Issue Labels

content not loading

### FreeTube Version

b6740acc37230c056e6a21a992ef9b634c1d587c

### Operating System Version

Manjaro Linux

### Installation Method

AUR

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

none

### Additional Information

See also https://github.com/electron/electron/issues/35577.

I also use KDE plasma on Wayland with an Nvidia GPU, if that is somehow of interest.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2022-09-05 18:31
This definitely sounds like an Electron issue. FYI the reason they ask for a minimal reproducable example is so that it's clear that the issue is with Electron and it also allows them to test fixes (you can't expect them to build and run FreeTube to replicate and test fixes).

**Comment by absidue** [comment] 2022-09-10 10:24
@toby63 I see you haven't provided an example for the eletron team yet, they will close the issue in 5 days time if you don't and then it probably won't get fixed.

**Comment by toby63** [comment] 2022-09-10 19:20
> @toby63 I see you haven't provided an example for the eletron team yet, they will close the issue in 5 days time if you don't and then it probably won't get fixed.

That might be the case, but I don't have time for that right now and I also don't see where I should start.
I only see a link to some kind of IDE and I would have to look up a lot of stuff it seems.
It is also very unusual to request such things in a bug report.
If they think closing is the right thing to do, they have to do it, though I think that is the wrong approach.

**Comment by absidue** [comment] 2022-09-11 19:40
Requesting a way to replicate the issue is not unusual in a bug report. There are tons of different applications that use Electron, you can't expect them to work out how to use and build all of those different apps.
Them asking for an example app, that has just enough code to replicate the bug and test fixes, solves that issue. It also allows them to easily see if it is actually a bug in electron or if it's a bug in that specific app.
They close issues without an example app after 10 days so they don't end up with a massive pile of issue that nobody can work on.

So yes, if you don't provide an example app within 10 days of creating the bug report they will close your issue, as it's basically useless to them (lots of devs will close bug reports if you don't give them a way to replicate the bug).

**Comment by toby63** [comment] 2022-09-11 20:08
It is very unusual, I am a user that is also reporting bugs, contributing documentation etc. for many years and I have never come across a situation like this.
Usual is providing logs, testing specific things, trying different commits and patches, but not "oh here is an IDE, search for everything you need yourself".

How about you give me more info about what exactly you use in your software?
And where to find an example app for what you use?

**Comment by absidue** [comment] 2022-09-11 20:29
I'm guessing you haven't reported bugs to libraries or frameworks before then, as asking for a minimal code example to reproduce the bug is standard in those situations.

That IDE is there to make it easier for you to build an example app. I use Windows and don't have access to your system, that makes it very hard for me to try and build some example app for you without going back and forth with you a million times asking "Did it break yet?".

As you mention you are using AUR, make sure you are using Electron 20 or try using one of the official FreeTube builds and see if the issue is fixed then.

Also as the issue persists after closing and reopening FreeTube, the bug is more likely to be in something that is still running after FreeTube is closed, like pipewire.

**Closed** 2022-10-04 00:02 UTC
Labels: bug, electron being electron, U: Waiting for Response from Author, B: content not loading, B: Unofficial Download
