### ISSUE TITLE
Video player goes higher than expected when clicking on any of its buttons

### ISSUE THREAD

**Issue by ClemGlacee** [FreeTubeApp/FreeTube#1814] opened 2021-10-12 04:47 UTC
**Behavior of the program**
When watching a video, changing the speed twice in fullscreen will make the video player go higher than what it's supposed to be. Both in the normal playing mode and with fullscreen

**Screenshots**
![fullscreen bug](https://user-images.githubusercontent.com/28269333/136892776-7436c11b-c6f0-4ac8-9c0b-4155cd9dfa22.png)
![normal bug](https://user-images.githubusercontent.com/28269333/136892780-c4856dc5-994a-4a8f-be33-3430184390a9.png)
_Note the black bar at the bottom and the title clipping at the top of the screen in fullscreen_ 

**Expected behavior**
The video is playing and the speed changes without changing the video player height

**To Reproduce**
Please add all steps to reproduce the behavior:

1. Play a video
2. Go fullscreen
3. Changing the speed in the video player (selecting the speed, not clicking on the speed at the bottom)
4. Change the speed again
5. Have everything moved up a bit

**Environment Information (please complete the following information):**
 - OS: EndeavourOS Linux x86_64 
 - OS Version: 5.14.9-arch2-1 
 - FreeTube version: v0.14.0 Beta
 - Installation Method (If applicable): .AppImage and AUR
 - Primary API Used: Local

**Additional context**
Reload the window will reset the bug

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-12 08:24
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1716

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-10-12 08:25 UTC
Labels: bug
