### ISSUE TITLE
Use Max Resolution instead of 1080p-option

### ISSUE THREAD

**Issue by o0Julia0o** [FreeTubeApp/FreeTube#4375] opened 2023-11-23 12:28 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There is the 1080p-option only. You have manually always change the resolution to a higher on if available in the video.

### Proposed Solution

Make an option like: always use the hightest resolution.

### Alternatives Considered

Or an option for 2k, 4k, 8k, next to the 1k-option.

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-23 12:39
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2013

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-23 12:39 UTC
Labels: enhancement, E: improvement existing feature
