### ISSUE TITLE
[Feature Request]: Ability to arrange playlists reverse-chronologically, or restore the grid view

### ISSUE THREAD

**Issue by sewerpig** [FreeTubeApp/FreeTube#4862] opened 2024-04-04 13:36 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

As far as I can tell, playlists are now organized in the order entries were added to it, which means long playlists take quite some time to reach the bottom of. This is a hassle, and it somewhat impairs using a playlist as a "watch later" tool if you want to save the list of videos rather than have to remove videos or make a new playlist regularly.

### Proposed Solution

A button to arrange playlists reverse in reverse chronological order (e.g. videos you've saved most recently at the top, instead of in the order you saved them)

### Alternatives Considered

An even better alternative method would be a button or setting restoring the previous saved videos arrangement within individual playlists. The grid was a very efficient and information dense means of displaying saved videos, allowing you to quickly scan through large lists, and in contrast the new playlists seem rather zoomed-in and only able to see a few listed videos at a time.

### Issue Labels

ease of use improvement, improvement to existing feature, new optional setting, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-04 13:48
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4856

Check comments

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-04 13:48 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: visual improvement, E: ease of use improvement
