### ISSUE TITLE
needs fixing.

### ISSUE THREAD

**Issue by DOOMMARINE117** [FreeTubeApp/FreeTube#4229] opened 2023-10-25 04:46 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

im trying to import data from youtube files. but, when clicking on import subscriptions. it wont do anything.

### Expected Behavior

it suppose to go like this: install from flathub or somethign, then when installed, create profile, go to settings, change theme, then go to data settings and click on import and its should suppose to load. 

### Issue Labels

accessibility issue, visual bug

### FreeTube Version

v0.19.1 beta

### Operating System Version

6.1.59-1-lts #1 SMP PREEMPT_DYNAMIC Fri, 20 Oct 2023 05:42:57 +0000 x86_64 GNU/Linux

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.1 beta

### Additional Information

none.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-25 06:34
Duplicate of #3943

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-10-25 06:34 UTC
Labels: bug, B: visual, B: accessibility
