### ISSUE TITLE
[Bug]: Redirect link opens in Freetube but replaces already open Video

### ISSUE THREAD

**Issue by Lcchy** [FreeTubeApp/FreeTube#3840] opened 2023-08-01 17:37 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open a video on Freetube
2. Open your browser and open any redirect link: freetube://https://youtu.be/7SofmXIYvGM
3. Observe that the video opens in the already opened Freetube window, replacing the previous video.

### Expected Behavior

Entering the link should open a new Freetube window.

### Issue Labels

usability issue

### FreeTube Version

v18.0

### Operating System Version

Fedora 38

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-08-01 18:46
duplicate of #1501

**Closed by absidue** 2023-08-01 18:46 UTC
Labels: bug

**Comment by Lcchy** [comment] 2023-08-02 18:39
Ah thanks I missed this!
