### ISSUE TITLE
How to import subscriptions?

### ISSUE THREAD

**Issue by ZormeinYT** [FreeTubeApp/FreeTube#1542] opened 2021-07-24 12:15 UTC
So i exported my file from Youtube, but FrreTube accepts only .json files but i have a .csv file. Is this possible to import?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-24 13:20
Did u read this?


https://docs.freetubeapp.io/usage/importing-subscriptions/

**Comment by ZormeinYT** [comment] 2021-07-24 15:55
Yes i exported and its a .csv file

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-24 16:13
Hmm do u have newpipe?

If u do maybe its faster to do an import of the newpipe file.

**Comment by ZormeinYT** [comment] 2021-07-24 16:17
i do okay i will try that

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-24 17:26
Lemme know if it worked out. If u were able to successfully import it please close this issue.

**Comment by ZormeinYT** [comment] 2021-07-24 21:28
On newpipe it laso requires a .json. Maybe i have too many subscritions

**Comment by ChunkyProgrammer** [comment] 2021-07-25 00:53
I think YouTube updated the way subscriptions are exported and now exports a csv instead of a json

**Comment by laundmo** [comment] 2021-07-26 20:39
getting a CSV too, made sure to select json everywhere i could.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-26 22:31
PR for this has to be merged, after that u guys can  import ur subscriptions.

https://github.com/FreeTubeApp/FreeTube/pull/1543

**Comment by JeeVee11** [comment] 2021-08-14 20:38
Until the issue is fixed, for anyone still running into this:
https://www.reddit.com/r/NewPipe/comments/oprw6d/google_takeouts_exporting_in_csv_format/h694cxs?utm_source=share&utm_medium=web2x&context=3

With this guide you can download your youtube subscribtion .csv file and convert it into a Newpipe .json one, and then import that.
Also an automated tool from the same thread: http://jsbin.com/pegiloviza/2

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-08-25 07:52
I have some good news for u guys. In this commit we made it possible for u to import ur subscriptions. All u need to do is download the nightly build.

https://github.com/FreeTubeApp/FreeTube/commit/044e5bf907ddd60e0d02cdd6b007e0a90ec41b3b

**Closed** 2021-08-25 07:56 UTC
Labels: question
