### ISSUE TITLE
Inclusion of "Remember Search History" Function

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1959] opened 2021-12-20 22:50 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
**In YouTube (official)**, there is a **function to view the previous entered/ typed search results within the search option as a drop-down list (can be seen under screenshots below)**, this function is needed for the FreeTube, so the same content doesn't need to type every time when closing and opening the FreeTube or after the new searches.

**Describe the solution you'd like to see implemented**
**"Remember Search History" option/ function is necessary, similar to "Remember History"** or the Watch History under the settings.
I believe this function is easy to implement as the project team can replicate it based on the "Watch History".

From what I have experienced: As FreeTube has the real-time/ online suggestions function during the search, this above mention enhancement is a local device improvement. so. this will be possible.

**Screenshots**
![FreeTube_6dkg5GpgFG](https://user-images.githubusercontent.com/96393348/146842072-dd631cd7-fba1-4e18-afaa-dd6cdc57ccda.png)
![FreeTube_rISHs8p9vU](https://user-images.githubusercontent.com/96393348/146842077-a4ed2079-d69f-41b3-8429-506495572250.png)

From Youtube
![vivaldi_oHfkFc4OKw](https://user-images.githubusercontent.com/96393348/146842283-ed11287a-20c7-4bb9-8cee-c0b259ca8034.png)

**Comment by absidue** [comment] 2021-12-20 23:06
Duplicate of #1492

**Comment by bachig26** [comment] 2021-12-21 03:15
> Duplicate of #1492

Yes, this issue #1492 that you have mentioned feels the same, but I couldn't understand it and this issue from my use case.

I hope this function will be implemented in a later release.

**Closed** 2021-12-21 18:06 UTC
Labels: enhancement
