### ISSUE TITLE
[Bug]: Settings tab is extremely slow

### ISSUE THREAD

**Issue by galure** [FreeTubeApp/FreeTube#3903] opened 2023-08-21 08:43 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to the Settings Tab
2. Click on any Settings (General settings, Theme Settings, etc)
3. It takes about 5 to 20 seconds to open or close the relevant tab

### Expected Behavior

It should open instantly I suppose

### Issue Labels

usability issue, visual bug

### FreeTube Version

v0.19.0 Beta

### Operating System Version

Fedora 38, Kde spin. Kernel: 6.4.11-200.fc38.x86_64, using Wayland

### Installation Method

Flathub

### Primary API used

Invidious API

### Additional Information

this last update is great

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-08-21 09:16
Hi @galure could u try to install `.rpm` so we can check if this is an issue with flatpak

**Comment by galure** [comment] 2023-08-21 09:25
I installed the .rpm version and it is as slow as the flatpak version

**Comment by galure** [comment] 2023-08-21 09:43
On my laptop running Fedora 38 Gnome version and Wayland there is no problem. Also Flatpak version.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-08-21 09:49
Working on Gnome but slow on KDE

I cant imagine KDE being the issue here

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-08-21 19:19
I cant seem to reproduce this on my fedora machine

**Comment by Julienist** [comment] 2023-10-18 22:19
Installed the .rpm version of FreeTube (v0.19.1 beta).
Have the same issue, still not resolved.

Interesting behaviour:
1. When clicking on a category in the settings menu, it is not opening directly.
2. It is about a 10 to 20 second long wait, to see what's in the selected category, BUT.
3. but, when doing a scroll down or up, this waiting time isn't there any more, the section/category will directly open.
4. When doing scrolling “too fast”—(about 20 lines down or up), I could open more sections in the settings menu. WHICH is annoying as hell.

Thoughts: Is there some kind of mouse event happening? If yes, then is also maybe related to issue #2436 …. Seeing that there is also not many activity, is this issue also not getting solved.

Else, where in those control+shift+i settings can I see what's happening as “mouse events”?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-18 23:09
@Julienist #2436 is unrelated to this

**Comment by Julienist** [comment] 2023-10-18 23:11
deleted the line
> @Julienist #2436 is unrelated to this

**Comment by absidue** [comment] 2023-10-21 14:45
I wonder if KDE delays rendering of things until you scroll or something, because this problem doesn't exist on Windows (tested myself) or Linux with Gnome (as mentioned by @efb4f5ff-1298-471a-8973-3d47447115dc).

**Comment by Julienist** [comment] 2023-10-21 15:23
Doing a quick search for KDE rendering delay(s), with or without scrolling as search indexers (doesn't really add much). But you will basically run into the following discussion: KDE is slower then gnome, because [reason].
To be objective, where to find the rendering (delay) inside FT itself? because FT itself is based on chromium (that's what the dev. console gives me).

**Comment by JoshuaMacklin** [comment] 2023-10-21 17:28
This is due to xwayland and electron being an oddly buggy combo. Its not a KDE thing as I've had the same issue in Gnome and I've seen this in other apps that fall into the same category. Using the correct electron flags while using native wayland fixes this appeared lag and makes things as snappy as it should be. I have a [PR](https://github.com/flathub/io.freetubeapp.FreeTube/pull/93) in the flathub side that you can test. Fixed the issue for me! Hoping it can be merged in to clear some of these related open issues.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-21 18:10
@galure are u available to test that PR?

**Comment by galure** [comment] 2023-10-21 18:28
I followed this instruction: 
`flatpak install --user https://dl.flathub.org/build-repo/57891/io.freetubeapp.FreeTube.flatpakref`
and it seems to work.  No more stutter, no slowness.

**Comment by galure** [comment] 2023-10-21 18:31
I would like to come back to before I installed the PR, just to be sure it fixed the issue (I should have tested the issue was still there, I'm an idiot), is there a command to do that?
`flatpack remove etc...` doesn't work

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-21 18:37
What about `flatpak uninstall`?

**Comment by galure** [comment] 2023-10-21 19:09
same as `flatpack remove`:

`error: Invalid id https:: Name can't contain :
`

**Comment by Julienist** [comment] 2023-10-21 22:36
When is the merge of the correct electron flags with the main branch possible? Because if snappy behaviour is possible then I guess the next thing to do, would be to merge it with the main FT-branch as flatpak -> thus also making it possible to do this with the .rpm versions.

**Comment by absidue** [comment] 2023-10-21 22:40
Okay so big question, if those flags are added by default, will it break FreeTube for anyone using X instead of Wayland?

Last time someone mentioned wayland flags they also said something about it removing X support or something.

**Comment by Julienist** [comment] 2023-10-21 22:49
Okay, so I do not have the following knowledge:
— Wayland or Xorg compositors (I did not read an explanation of how these 2 work).
— Wayland protocol.
— x11
What I do know:
Large amount of apps which work on x11 or Xorg work on Wayland, thanks to Xwayland.
(a fallback).

Next thing:
I do not want to have support for x11 to be gone, for the people who still use it/those who refuse to go to Wayland/ or just can't.

Confusing but safe path:
A safe path would be to make like a branch-off for Wayland only (testing), but then you would make 2 main chains of FT (which is more confusing). ..... → indirect this “wayland-only testing branch” could be tested on x11 for checking compatibility.

**Comment by absidue** [comment] 2023-10-21 22:53
Hopefully there is a way to do it without having to release lots of different versions just for linux, especially as most of the freetube devs don't actively use linux, so having to keep vms around to test loads of different versions would be horrible.

**Comment by Julienist** [comment] 2023-10-21 22:59
If most of the FreeTube devs do not actively use Linux, how is x11 support in question? I think in that case, there could be a risk made by taking the correct electron flags in the main branch. Then the question next could be, does xwayland work with the electron flags to fallback on x11. in that way, x11 and wayland support at the same time, is done.
Basically, making the electron flags to be supported by xwayland.

**Comment by JoshuaMacklin** [comment] 2023-10-23 01:40
> I would like to come back to before I installed the PR, just to be sure it fixed the issue (I should have tested the issue was still there, I'm an idiot), is there a command to do that? `flatpack remove etc...` doesn't work

You can just remove it through the Software Center Gui, find the app, click the flathub drop down and remove the version that has the user tag

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-08 04:25
Can be closed bc https://github.com/flathub/io.freetubeapp.FreeTube/pull/93 is merged

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-08 04:25 UTC
Labels: bug, B: visual, B: usability
