### ISSUE TITLE
[Feature Request]: Stop videos defaulting to 60 fps

### ISSUE THREAD

**Issue by dvoraking** [FreeTubeApp/FreeTube#2506] opened 2022-08-24 10:05 UTC
### Guidelines

- [x] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

In "player settings" I can choose the resolution to default videos to, but not the framerate. Videos default to 60fps if available, taking up bandwidth and making them buffer slower.

### Proposed Solution

Let us toggle between default framerates.

### Alternatives Considered

Let us toggle between default framerates.

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-09-08 23:48
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/504

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-09-08 23:48 UTC
Labels: enhancement, E: new optional setting
