### ISSUE TITLE
[Bug]: v.0.22.0 and beyond will not work on Ubunte MATE 24.04

### ISSUE THREAD

**Issue by swilly97** [FreeTubeApp/FreeTube#6416] opened 2024-12-20 00:09 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I updated to the newest version of Freetube, and it wouldn't even open the program when I tried. I uninstalled and reinstalled, and tried both v.0.22.0 and 0.22.1, and neither worked. Reverting to 0.21.3 is currently working. I'm using the amd64 .deb files for installation.

### Expected Behavior

the program should be opening.

### Issue Labels

causes crash, usability issue

### FreeTube Version

v.0.22.1

### Operating System Version

Ubuntu MATE 24.04

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v.0.21.3

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by swilly97** [comment] 2024-12-20 00:52
Yeah, running that command worked, it's starting now.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-20 01:00
Duplicate of #5952

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-20 01:00 UTC
Labels: bug, B: usability, B: crash
