### ISSUE TITLE
"Fully working playlists"

### ISSUE THREAD

**Issue by deejf** [FreeTubeApp/FreeTube#1841] opened 2021-10-19 18:15 UTC
I've been using FreeTube for a couple of years, and one of the only things that has been promised but never delivered is the capacity for multiple playlists. (There was a dark month or two where you could not save videos *at all*, but that was taken care of relatively quickly.)

When I go to my Playlists now, I get the same hover-help text as always:

> This page is not reflective of fully working playlists. It only lists videos that you have saved or favorited. When the work has finished, all videos currently here will be migrated to a 'Favorites' playlist.

I save videos to watch for later, I save videos to refer to much later, as an archive. I save videos that are music, and others that are lengthy lectures. Having them all in the same list is frustrating, especially with the "Load More" button jumping me back to the top every time I click it. (It does, at least, load more.)

Why can I still not create multiple playlists? Why must all videos be mashed together into one undifferentiated list so that older ones get lost in the ever-growing morass? Are "fully working playlists" ever going to happen?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-19 18:38
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/591

This is already described in multiple other issues. E.g. in the pinned issue #539 
Therefore closing due to being a duplicate.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-10-19 18:38 UTC
Labels: U: duplicate, enhancement, U: doesn't follow template

**Comment by deejf** [comment] 2021-10-19 23:56
> Duplicate of #591
> 
> This is already described in multiple other issues. E.g. in the pinned issue #539 Therefore closing due to being a duplicate.

Issue 591 is about copying YT playlists to a FreeTube playlist, which is, at best, only implicitly the same thing I was asking for. I looked through pinned issue 539 and saw nothing about multiple playlist support before I posted this. I am not looking for "dynamic" (I assume that means "changes with changing conditions") or "temporary" playlists, I am wondering when the promised functionality of *multiple* playlists will be available, and closing this issue and saying "this is a duplicate of things that are not the same" does not answer my question.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-20 09:25
Multiple playlists will be implemented when the main dev isnt busy anymore with life. There is no set date for when its going to be implemented.

I've marked this as duplicate because there are multiple issues and comments that describe the same. We dont need more open issue about this.

The next time u want to ask a question use the proper template.
