### ISSUE TITLE
[Bug]: FreeTube 0.16.0 not opening in Manjaro

### ISSUE THREAD

**Issue by RockatanskyV8** [FreeTubeApp/FreeTube#2206] opened 2022-04-16 17:33 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

I've installed Freetube through yay, my aur package, It worked fine for a long time but seems like after update to the 5.17.1-3 linux kernel it simply won't open at all when I click the icon. I've tried to launch it through my terminal and all that I get is:

`(electron:12757): Gtk-WARNING **: 14:00:55.853: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version`

An then nothing.

### Expected Behavior

FreeTube opening up.

### Issue Labels

accessibility issue, content not loading, inconsistent behavior, usability issue

### FreeTube Version

v0.16.0

### Operating System Version

Manjaro Linux 5.17.1-3-MANJARO

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-04-16 18:04
Duplicate of #2163

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-04-16 18:04 UTC
Labels: bug, B: content not loading, B: accessibility, B: usability, B: inconsistent behavior
