### ISSUE TITLE
[Feature Request]: playlist live update 

### ISSUE THREAD

**Issue by nrc00** [FreeTubeApp/FreeTube#5118] opened 2024-05-16 17:30 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

i copied a link of a yt playlist that was getting daily update in yt . but as i started to use freetube  , i noticed playlist =s dont auto update and i have to update every time manually , when i copy palyslist link and try to update it in the previous place the videos overlap on themselves . so basically i have to make  a new palylist every time the playlist gets a updates in  yt 

### Proposed Solution

make it so playlist gets auto update whenever the same playlist is updated in yt 

### Alternatives Considered

at least make it so that when i update playlists manually it doesnt overlap on itself 

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-16 17:42
Duplicate of #312

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-05-16 17:42 UTC
Labels: enhancement, E: new feature
