### ISSUE TITLE
[Bug]: "Your subscribed channels does not have any videos"

### ISSUE THREAD

**Issue by GrumbleAus** [FreeTubeApp/FreeTube#4429] opened 2023-12-08 00:50 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I have 200 channels, use RSS feed method. Just did a subscription refresh and got the above message. Was working an hour ago. Thanks for the great software.

### Expected Behavior

Shows new videos for all channels

### Issue Labels

content not loading

### FreeTube Version

v0.19.1 beta

### Operating System Version

Windows 10 Enterprise 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by bybeenull** [comment] 2023-12-08 02:11
I also confirm that I have the same problem

**Comment by torriem** [comment] 2023-12-08 02:36
I switched to a proxy I run on a VPS, and was able to refresh my feeds.  I'm sure eventually youtube will complain again.  My ISP IP address is shared with many customers, so maybe that tripped YouTube's block.  It has happened before.

**Comment by karolyi** [comment] 2023-12-08 06:57
seemingly, all the RSS feeds are gone, as in 404.

**Comment by taewyth** [comment] 2023-12-08 07:25
The issue likely stems from Youtube's side of things, I'm encountering it both on freetube and newpipe

**Comment by Janaue** [comment] 2023-12-08 07:28
The RSS feed seems involved. It's over isn't it ?
if RSS feed is forced, then even profiles with 2 channels are not updated and nothing is found....

**Comment by karolyi** [comment] 2023-12-08 11:25
I got it back as well. on newpipe, I got a notification that a couple channels couldn't be loaded, which they did after another refresh. I think YT is trying to limit the RSS feed requests.

**Comment by absidue** [comment] 2023-12-08 18:55
Closing as the RSS feeds have been back for a while now.

**Closed by absidue** 2023-12-08 18:55 UTC
Labels: bug, B: content not loading

**Comment by jeikashu** [comment] 2024-01-29 14:14
I think it's back. None of the invidious APIs work, only the local one. Getting code 200 from the instances but no videos

**Comment by karolyi** [comment] 2024-01-29 14:16
+1 could confirm, but for me it's fixed now. probably another developer-caused hiccup.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-01-29 14:57
The bug is on YouTube's side, we can't do anything about YouTube breaking their own systems.

Hopefully it is resolved soon.

For everyone that needs to use FT right now, try this workaround. 

> For a quick fix create a profile with < 100 subscriptions

**Comment by jeikashu** [comment] 2024-01-29 15:02
Aaaand it's back now. Sorry for the trouble. If anything, the local API works when needed

**Comment by karolyi** [comment] 2024-01-29 15:06
I think they're trying to find ways against freetube and the likes.

The RSS feed responses are sometimes 404, sometimes 500. They're definitely playing around with the backends.

**Comment by ACR-Jeff** [comment] 2024-01-29 20:25
> I think they're trying to find ways against freetube and the likes.
> 
> The RSS feed responses are sometimes 404, sometimes 500. They're definitely playing around with the backends.

Exactly, This is why anything related to YT shouldn't be relied upon. Yet what else is there.

**Comment by karolyi** [comment] 2024-01-29 20:27
Offtopic here, but I have quite a lot of subscriptions on LBRY. It's slowly becoming my go-to platform.

**Comment by ACR-Jeff** [comment] 2024-01-29 20:57
I might have found a fix, I am on Void Linux, I renamed /.config/Freetube > /.config/Freetube.bak restarted freetube, Feed works again as normal

**Comment by absidue** [comment] 2024-01-29 21:01
Well yes because FreeTube defaults to not using RSS and as you have now removed your subscriptions, you are well below the 125 channel per profile limit at which FreeTube forces RSS to avoid ratelimiting.

Your "workaround" doesn't change the fact that YouTube's RSS feeds are still down.

**Comment by ACR-Jeff** [comment] 2024-01-29 21:03
> Well yes because FreeTube defaults to not using RSS and as you have now removed your subscriptions, you are well below the 125 channel per profile limit at which FreeTube forces RSS to avoid ratelimiting.
> 
> Your "workaround" doesn't change the fact that YouTube's RSS feeds are still down.

For some odd reason it didn't remove my subscriptions, Normally it would, Unsure why it didn't and that's what I was leaning towards to clean slate and add only a few subs.
I proceeded to renamed my previous config file back, Restarted Freetube and it works again as intended even with 143 subs. YT may have fixed their broken RSS feed?

**Comment by polemion** [comment] 2024-03-26 07:03
Got it today with 34 channels.

Is there any verbosity flag, log or something to attempt to debug?

I did not find anything helpful after stracing it, only a multitude of the following:
`
recvmsg(47, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
`

But I am not certain if they are related to this, which seems benign:
`
(freetube:361334): dbind-WARNING **: 09:00:45.140: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_0.0: Permission denied
`

**Comment by absidue** [comment] 2024-03-26 11:28
@polemion Are you using the local API or the Invidious API?

> Is there any verbosity flag, log or something to attempt to debug?

Even if there were (which there isn't, FreeTube doesn't log to the terminal, instead you would want to open the devtools, like in a web browser), it won't help you in this case (when YouTube is saying the channel doesn't exist or Invidious is returning an internal server error, there is nothing FreeTube can log).
