### ISSUE TITLE
[Feature Request]: Favourite a YT playlist

### ISSUE THREAD

**Issue by lonix1** [FreeTubeApp/FreeTube#2847] opened 2022-11-08 23:53 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently there exists functionality to 1) search for playlists and 2) play playlists.

But there's no way to bookmark / favourite / star a playlist, so there's no way to keep track of it.

### Proposed Solution

Please add the possibility to bookmark / favourite / star a playlist.

### Alternatives Considered

Keeping the list of playlists in a separate file, outside of FreeTube, yuck... :)

### Issue Labels

ease of use improvement, improvement to existing feature

### Additional Information

I know there are lots of issues for playlists, but they deal with improving FreeTube's internal playlists feature. This issue is for bookmarking / favouriting / starring YT's playlists.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-11-09 06:08
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/312

**Closed as completed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-11-09 06:08 UTC
Labels: U: duplicate, enhancement, E: improvement existing feature, E: ease of use improvement
