### ISSUE TITLE
[Bug]: SponsorBlock outro doesn't skip; other segments do

### ISSUE THREAD

**Issue by shockwavebd** [FreeTubeApp/FreeTube#4341] opened 2023-11-16 20:33 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

The SponsorBlock feature in FreeTube is not skipping the outro segment of sponsored content, even though it works fine for other segments. I’ve attached a video to this issue for better illustration. The outro segment is marked in green, while all other segments are marked in red. Sometimes, if a segment starts from the beginning, it will not be skipped after the segments are fetched.
Also, I have a question unrelated to this issue. Why does FreeTube require more processing power to play videos compared to other media players like MPC-HC/BE or Pot Player when playing the same YouTube videos? Does FreeTube support auto-translation of closed captions? If not, are there any plans to implement this feature? Should I create another issue for this? Thank you.

### Expected Behavior

Should skip the outro as other segments.

### Issue Labels

feature stopped working, inconsistent behavior, usability issue

### FreeTube Version

v0.19.1

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

https://github.com/FreeTubeApp/FreeTube/assets/135010054/44c3a732-aa8a-4512-a623-61f8818c4ce3

YT example video link: https://youtu.be/iyGhI_JVOZI

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-16 20:43
Pretty sure its a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3534

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-16 20:43 UTC
Labels: bug, B: usability, B: feature stopped working, B: inconsistent behavior
