### ISSUE TITLE
[Bug]: After recent update, playback now crashes and won't play "adult" age videos

### ISSUE THREAD

**Issue by OutsideTub3r** [FreeTubeApp/FreeTube#6053] opened 2024-10-31 17:00 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

After the latest update, when you play a video and still use other programs like Firefox, unlike before where you'd be fine, now the playback crashes. You have to only use Freetube, if not leave only that program only, if you were to play a video. It just stops acts like its loading all over again, even missing your mark during the playback, and seems to suggest my internet connection is gone, affecting the rest of my programs, when no internet connection was ever lost. 

Another issue is that now I cannot watch a video that might be adult in age anymore. I must "sign in", which defeats the purpose of using Freetube over Youtube. 

I don't recall any other issues beyond those two, and would like these to be resolved, please. 

### Expected Behavior

I don't know what to put here, as its my first post. Perhaps just a repeat of the above.

After the latest update, when you play a video and still use other programs like Firefox, unlike before where you'd be fine, now the playback crashes. You have to only use Freetube, if not leave only that program only, if you were to play a video. It just stops acts like its loading all over again, even missing your mark during the playback, and seems to suggest my internet connection is gone, affecting the rest of my programs, when no internet connection was ever lost. 

Another issue is that now I cannot watch a video that might be adult in age anymore. I must "sign in", which defeats the purpose of using Freetube over Youtube. 

### Issue Labels

causes crash, content not loading, feature stopped working

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-10-31 17:15
> Another issue is that now I cannot watch a video that might be adult in age anymore. I must "sign in", which defeats the purpose of using Freetube over Youtube.

YouTube patched the only age-restriction bypass, so it's not possible to watch or download them anymore without an age-verified YouTube account.

**Comment by OutsideTub3r** [comment] 2024-10-31 17:26
> > Another issue is that now I cannot watch a video that might be adult in age anymore. I must "sign in", which defeats the purpose of using Freetube over Youtube.
> 
> YouTube patched the only age-restriction bypass, so it's not possible to watch or download them anymore without an age-verified YouTube account.

Really?! Damn. It kinda defeats the purpose of Freetube in that regard.

**Comment by absidue** [comment] 2024-10-31 17:29
If that's the only thing you used FreeTube for then yes, every 3rd party client and downloader is not useful to you anymore.

**Comment by OutsideTub3r** [comment] 2024-10-31 17:32
> If watching age-restricted videos is the only thing you used FreeTube for then yes, every 3rd party client and downloader is not useful to you anymore.

No I don't, but in general, I got Freetube bc YT screwed me. While I did get YT back, I don't use it unless I have to. Mainly its FT, unless I want to comment or something. But in regards to the adult stuff, just having that access with no issues being gone is sad. This means I have to dl the video, but commenting or liking is off the table :/ 

What about the playback issue?

**Comment by absidue** [comment] 2024-10-31 17:40
Can you please open the dev tools (CTRL+SHIFT+I) and check the Console tab for any red messages (you can ignore yellow ones, those are just warnings) after the problem occurs hopefully that will have some kind of indication of what is going on. Additionally does the player go white when it happens? if yes this could be a duplicate of another open issue.

**Comment by OutsideTub3r** [comment] 2024-11-04 07:49
Its still crashing. Anyone able to figure this out?

> Can you please open the dev tools (CTRL+SHIFT+I) and check the Console tab for any red messages (you can ignore yellow ones, those are just warnings) after the problem occurs hopefully that will have some kind of indication of what is going on. Additionally does the player go white when it happens? if yes this could be a duplicate of another open issue.

This is what I saw when it happened again
Failed to load resource: www.youtube.com/feeds/videos.xml?playlist_id=UULFkeQ70c-qKw_-CZPx2BLOrQ:1
the server responded with a status of 404 ()

**Closed** 2024-11-05 19:09 UTC
Labels: bug, B: content not loading, B: crash, B: feature stopped working
