### ISSUE TITLE
Video is not buffering during network interruption.

### ISSUE THREAD

**Issue by vetriselvan1187** [FreeTubeApp/FreeTube#1877] opened 2021-11-06 12:57 UTC
**Behavior of the program**
Video is not buffering during network interruption. While watching video, network connection drops which causes the video to load indefinitely. network connection drops causes the Freetube to play video till the buffered content. When network connection comes back, it is not resuming from that offset rather it shows loading progress indefinitely.
.

**Expected behavior**
When the network connection comes back, It should start the buffering and playing from that offset.

**To Reproduce**
Go to any video.
Watch video and meanwhile close the network connection.
Watch the video till the buffered content, then reconnect the network to load remaining content.
Observe the video is not buffering rather it is loading indefinitely.

**Workaround**
I clicked back, reloaded the video and moved my cursor to that offset to watch it again.

**Environment Information:**
FreeTube version: v0.15.0 Beta
Installation Method: Command Line

**Comment by su-klubert** [comment] 2023-05-19 22:59
I donated more than 200$ but i dp not keep supporting since this buffering issue was never fully addressed.

I still get slow af buffering rendering freetube worthless, when i set quality to auto it looks like gargabe and keeps looking like that. while i can seemingly buffer videos using mpv etc. this video players buffering is huge trash. after 2 years im sorry but i cant say it differently. 

i have a ping of 50-100 with my vpn and videos in freetube buffer like shit.
i cant watch a single video in 720p / 1080p without buffering video stopping every 5-10 seconds. 

i will keep supporting invidious, piped, libretube, newpipe etc since i dont see progress with that. really sad.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-05-20 04:15
@su-klubert try using in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by su-klubert** [comment] 2023-05-20 09:01
tried freetube-0.18.0-nightly-2944_amd64.AppImage

720p buffers better but still this buffering ahead of time is missing sometimes, causing rarely loading issues.

we cant select the frame (regular, 50 / 60) mode which helps to make this issue worst 

1080p without buffering is not possible unless i pause the video for a minute but than i run into buffering issues again a minute later. 

maybe the google video servers speed but i doubt it when i compare yt-dlp speed, my internet connection is quite fast just has a small ping increase

what is good:

i finally can switch the video quality without having to strg+r reload the page due to switching quality breaks the video.

**Comment by su-klubert** [comment] 2023-05-20 09:11
it seems to buffer always 1 minute ahead but lets say i have some load on the network than i may run into buffering issues, would it be possible to try to buffer 3-5 minutes in order to average out bandwidth shortages?

**Comment by Smurflicious** [comment] 2023-07-03 17:50
I have been getting this constantly for the last week and have had it for periods before. The issue is my ISP being crap but if I open the video on youtube website it plays fine.

Basically every video I open currently will start playing, the buffer bar will not grow, playback reaches the end of the buffer and the spinning icon appears, then I'm stuck waiting for like 30 seconds until it plays for like a second a spins again.

The buffer management/rules needs overhauled, it appears to assume the buffer will keep filling even when it has lost connection or the connection is spotty.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-07-03 18:03
@Smurflicious see https://github.com/FreeTubeApp/FreeTube/issues/3457#issuecomment-1616395495

**Comment by Smurflicious** [comment] 2023-08-01 09:18
This bug was fixed for me by updating to the most recent nightly build. The issue was YT changing things, possibly to stop freetube working right.

**Comment by ptomato** [comment] 2023-09-20 17:48
@Smurflicious can you mention which version number you updated to?

I have seen something similar where if the network is interrupted (e.g. computer suspend) the buffering never resumes. This was in v0.19.0 Beta and I'm not sure whether that's a release that includes the bugfix that you saw.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-14 21:08
Closing, converted to a feature request in #4159 because this isnt a bug

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-10-14 21:08 UTC
Labels: bug
