### ISSUE TITLE
[Feature Request]: Search for keywords in comments

### ISSUE THREAD

**Issue by Growebis** [FreeTubeApp/FreeTube#3124] opened 2023-01-28 14:07 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

On youtube, while this feature isn't available, you can simply press f3 or alt+f3 to search for keywords if you just scroll in the comments far enough, this could be useful if you want to see if someone commented about something that no one commented about. But in FreeTube, you cant really do that at all.

### Proposed Solution

Adding some sort of search button that goes through all the comments and returns back the results with some comments that match the keyword, if not then inform the user that no comments could be found with the keyword.

### Alternatives Considered

none

### Issue Labels

new feature

### Additional Information

Here is what i think it would look like;
![Screenshot 2023-01-27 231918](https://user-images.githubusercontent.com/113867283/215270603-5f9983d2-e244-44fa-af99-b991d34afbdd.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-01-28 14:34
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1401

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-01-28 14:34 UTC
Labels: enhancement, E: new feature
