### ISSUE TITLE
add the possibility to see "personalized" content

### ISSUE THREAD

**Issue by DogeIlMeme** [FreeTubeApp/FreeTube#229] opened 2019-03-07 17:39 UTC
Add the possibility to see "personalized" content for example, set the contents country by country

For example for those who see videos from Italy add the ability to set the content only for Italy

**Comment by PrestonN** [comment] 2019-03-19 17:55
Realistically this can only be done for the `Trending` section as searches are not based on country origin.

Nevertheless, this is a duplicate of #14 and has been implemented.  Expect to see this in the next release.

**Closed by PrestonN** 2019-03-19 17:55 UTC
