### ISSUE TITLE
[Bug]: Player does not open

### ISSUE THREAD

**Issue by AA-Coder-Beg** [FreeTubeApp/FreeTube#6032] opened 2024-10-30 03:34 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click on the App icon

### Expected Behavior

The app opens up

### Issue Labels

content not loading

### FreeTube Version

0.22

### Operating System Version

Ubuntu 24.04.1

### Installation Method

.deb

### Primary API used

Local API

### Additional Information

Right-clicking doesn't work. I uninstalled and re-installed the app. Unpinning from dash makes no difference

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-10-30 07:42
Duplicate of #5952

**Closed** 2024-10-30 07:43 UTC
Labels: bug, U: duplicate, B: content not loading
