### ISSUE TITLE
[Feature Request]: Having a watchtime graphics

### ISSUE THREAD

**Issue by e471wo** [FreeTubeApp/FreeTube#6429] opened 2024-12-22 09:52 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Could be great to have a watchtime tracker/history. (like that people could know if there are dugs addicts or not :-D.)

### Proposed Solution

in the history tab (or setting or a new window), having a graph that represent number of minuts per day, month, etc... and if possible having by info, the list of video watched.

### Alternatives Considered

I tried to export the history, but the files seems not complete. for exemple if I watch 2 times the same video, it's not inside. second, the timewatched seems not accurate.

### Issue Labels

display more information to user, ease of use improvement, new feature

**Comment by absidue** [comment] 2024-12-22 10:15
Duplicate of #6181

FreeTube only remembers the most recent watch of each video, to avoid wasting loads of storage. The time watched field is the datestamp of when you watched the video most recently.

**Closed** 2024-12-22 10:15 UTC
Labels: U: duplicate, enhancement, E: display more information, E: ease of use improvement, E: new feature

**Comment by e471wo** [comment] 2024-12-22 10:31
@absidue stupid question, but is it possible that freetube send the information to ... for example activitytracker ? or a tracker come and check (via an api or something else) what is watched ? 

thanks

**Comment by absidue** [comment] 2024-12-22 10:37
There is already an open feature request for something like there here: #1880 the main requirement would be that that service has to be completely FOSS (we make an exception for YouTube, as this is a YouTube app, but for other services that people want to add support for, we have a strict FOSS policy).
