### ISSUE TITLE
[Feature Request]: Increase Pause/Play Button Size In The Player

### ISSUE THREAD

**Issue by akano12** [FreeTubeApp/FreeTube#6011] opened 2024-10-29 11:40 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When pausing a video, the pause/play button becomes visible on top over the video.
The pause/play button on the player isn't big enough, it should be increased to cover the entire video

![2024-10-29_13-36](https://github.com/user-attachments/assets/0dda8b6a-a0df-4649-83c0-044548f01415)

### Proposed Solution

Increase it's size to cover all the screen, because when i pause the video to read or check something in the video, it just covers a small portion of the screen.

Increase its size to cover the entire screen, it'll be better UX

### Alternatives Considered

decrease its size, idk if that makes sensse

### Issue Labels

improvement to existing feature

### Additional Information

Seriously, kindly decrease the size of the button, makes no sense to have such a size with respect to the video, or remove it

**Comment by ChunkyProgrammer** [comment] 2024-10-29 12:25
Duplicate of #5951

**Closed by ChunkyProgrammer** 2024-10-29 12:25 UTC
Labels: enhancement, E: improvement existing feature
