### ISSUE TITLE
[Feature Request]: Resolutions Higher than 1080p?

### ISSUE THREAD

**Issue by ccateni** [FreeTubeApp/FreeTube#2551] opened 2022-09-08 03:48 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

As much as I love the app, I'm not happy being limited to 1080p on a setup that allows for resolutions higher than 1080p. I would love to figure out a way to have the app have the ability to play videos with higher resolutions like 1440p or 4k.

### Proposed Solution

Figure out a way to support WebM or WebM alternative to add to the player to allow for resolutions like 1440p or 4k.

### Alternatives Considered

Make a different format similar to Legacy that might work alongside DASH to allow for users interested to playback videos past 1080p at higher resolutions.

### Issue Labels

display more information to user, ease of use improvement, improvement to existing feature, visual improvement

**Comment by absidue** [comment] 2022-09-08 05:58
Duplicate of #2013

**Closed by absidue** 2022-09-08 05:58 UTC
Labels: U: duplicate, enhancement, E: improvement existing feature, E: visual improvement, E: display more information, E: ease of use improvement
