### ISSUE TITLE
In a playlist fullscreen is kept from video to video

### ISSUE THREAD

**Issue by elitecoder27** [FreeTubeApp/FreeTube#4315] opened 2023-11-11 03:12 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

in a playlist everytime a video ends the player reverts to non-fullscreen. this is very inconvenient

### Proposed Solution

keep the player on fullscreen if toggled even in playlists.

### Alternatives Considered

there are no alternatives to this problem

### Issue Labels

ease of use improvement, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-11 06:40
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2295

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-11 06:40 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement
