### ISSUE TITLE
The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

### ISSUE THREAD

**Issue by MichiFr** [FreeTubeApp/FreeTube#1208] opened 2021-04-17 13:30 UTC
Hi!

A similar of not same issue was posted back in 2020 same report with no solution in my case.

**Behavior of the program**
When starting any YT video, using the play button in the middle of a video preview, I almost immediately get the error "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

**Expected behavior**
I expect the vide o to start ;-)

**To Reproduce**
1. Start FreeTube, go to e.g. trending
2. Select any of those video
3. Click the play button in the middle of the preview screenshot
4. Immediately get a crossed button/icon and the error "The media playback was aborted due to a corruption problem or because the media used features your browser did not support"

**Screenshots**
Added some screenshots below.

**Environment Information (please complete the following information):**
 - **OS**: Windows 10 latest version and all updates installed, German locale
 - **OS Version:** 10, latest version
 - **FreeTube version**: 0.12.0. beta
 - **Installation Method** portable on a network share (Synology NAS, mapped drive letter)
 - **Primary API Used:** tried Local API and Invidious API as well

**Additional context**
I've checked my Linux firewall for any obscure logs that may have prevented the video from playing. Of course YT itself works in my browser Firefox latest.

Maybe I've missed the obvious, are there any additional steps necessary after the initial installation necessary .e.g. install a specific browser oder browser add-in?

_Edit: I've unpacked the portable version of FreeTube to a local folder on my Windows PC and re-tried to play any video - guess what? This works perfectly well! 
To investigate further, I've deleted the previous portable installation from my **network share** and copied the content of the local (portable) installation I've done just before, to the share again and restarted FreeTube.
Now, guess what? The video playback does not work again and the same error as stated above occurred again. So, now I'm clueless.
I noticed that even running a portable installation some of FreeTube's files are copied to APPDATA folder on local drive. So this seems not to be a true portable installation, right? Maybe I did sthg. wrong? But other than unpacking the zip file for the portable installation I cannot do anything ales. The files and folders in APPDATA were created automatically._

Thanks for your support!
Michael

![2021-04-17_152405](https://user-images.githubusercontent.com/28045390/115114788-5cbe9400-9f91-11eb-9b47-6ed5179a4eb7.jpg)
![2021-04-17_152420](https://user-images.githubusercontent.com/28045390/115114793-60521b00-9f91-11eb-9b1c-c23a31392ff6.jpg)
![2021-04-17_152902](https://user-images.githubusercontent.com/28045390/115114867-c343b200-9f91-11eb-9616-c07793ce83cc.jpg)
![2021-04-17_152926](https://user-images.githubusercontent.com/28045390/115114870-c63ea280-9f91-11eb-963c-735ed953efd7.jpg)

**Comment by MichiFr** [comment] 2021-04-18 08:24
Hm maybe I should use a "true" protable installation like mentioned here [https://github.com/FreeTubeApp/FreeTube/issues/746](url) or use the provided config param? Let's see I will give it a try later on today...

**Comment by GilgusMaximus** [comment] 2021-04-18 16:41
Closing as this is a duplicate of #885

**Closed by GilgusMaximus** 2021-04-18 16:41 UTC
Labels: bug
