### ISSUE TITLE
[Feature Request]: Playback Speed UI Change - Display playback speed when not 1x

### ISSUE THREAD

**Issue by thebetauser** [FreeTubeApp/FreeTube#6166] opened 2024-11-14 21:33 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The current version (0.22.0-beta) replaced the numerical representation of the playback speed with an icon. As a user who likes vary playback from 1x to 3x, it's hard to visually see how many times I have to press the keyboard shortcut for playback speed button to get it back to 1x. 

Having an overlay ontop of the new icon with the current playback speed (ie: 0.5x, 1.5x, 2x, 3x, etc) would be helpful to quickly navigate playback speed.

### Proposed Solution

Tiny overlay on top or in the corner of the new playback speed icon showing the current playback speed.

### Alternatives Considered

A more convenient solution would be to add a new keyboard shortcut key to automatically reset playback to 1x speed such as using a modifier like (ctrl-p or shift-p) or mapping it to a new key

### Issue Labels

display more information to user, new keyboard shortcut, visual improvement

**Comment by absidue** [comment] 2024-11-14 21:47
Duplicate of #4658

**Closed** 2024-11-14 21:47 UTC
Labels: enhancement, E: visual improvement, E: display more information, E: keyboard shortcut
