### ISSUE TITLE
[Feature Request]: Skip silence between tracks in playlist

### ISSUE THREAD

**Issue by lonix1** [FreeTubeApp/FreeTube#4887] opened 2024-04-06 05:59 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Now that we have the playlists feature (BTW: thanks!), I often find that there is excessive silence between tracks.

### Proposed Solution

It would be nice to have a "skip silence" toggle button in the playlist panel (loop, shuffle, reverse, SKIP, previous, next, pause).

The player seems to buffer some time ahead, so in theory it would be able to detect that
- it is near the end (e.g. < 20s)
- the buffered portion that is still unplayed, is empty/silent

### Alternatives Considered

/

### Issue Labels

ease of use improvement, improvement to existing feature

### Additional Information

Thanks

**Comment by absidue** [comment] 2024-04-06 06:38
This sounds like a duplicate of #1766

**Comment by absidue** [comment] 2024-04-06 07:32
Ah so you aren't asking for anything in the video itself, but to some how eradicate the loading of the new video?

That's going to be quite difficult to do, as it would require loading stuff in the background and the current watch page is designed to only handle one video at a time.

Not saying it's impossible and does sound like a cool feature, it's just going to require a bunch of non-trivial changes.

**Comment by absidue** [comment] 2024-04-06 21:11
Ah that does sound pretty much identical to the other feature request, you just want it to only trigger at the end of videos, instead of throughout the entire video.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-11 19:42
Closing in favor of #1766. Because that one will  allow us to detect and skip everything in the video. So that means we can also make it only skip at the end of the video.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-11 19:42 UTC
Labels: U: duplicate, enhancement, E: improvement existing feature, E: ease of use improvement
