### ISSUE TITLE
video playback

### ISSUE THREAD

**Issue by senolfndk** [FreeTubeApp/FreeTube#3714] opened 2023-06-28 17:39 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

videos hangs 😒

### Expected Behavior

videos hangs 😒

### Issue Labels

API issue

### FreeTube Version

v0.18.0-nightly-1 Beta

### Operating System Version

Windows 11 Pro 22H2 22631.1906

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18.0-nightly-1 Beta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-06-28 21:54
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3457

That one will be reopened when we have definitive  proof of buffering issues

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-06-28 21:54 UTC
Labels: bug

**Comment by senolfndk** [comment] 2023-06-29 06:09
https://github.com/FreeTubeApp/FreeTube/assets/52818836/39a50840-2f38-47c4-ac9d-7160bab4a3b6

v0.18.0-FTN-2 Beta
