### ISSUE TITLE
PiP and back is broken.

### ISSUE THREAD

**Issue by kubo6472** [FreeTubeApp/FreeTube#804] opened 2020-11-22 22:40 UTC
**Behavior of the program**
After going to PiP and back, the video page is gone, but playback continues.

**Expected behavior**
Either open the video page, or stop the playback.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open a video
2. Set to PiP
3. Go to some other page
4. Resume playback
5. Pop it back up

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: 10 20H2
 - FreeTube version: 0.9.2 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Personal Invidious Instance: https://github.com/greentornado/invidious-api-docker

**Comment by GilgusMaximus** [comment] 2020-11-24 17:54
Closing because duplicate of #624

**Closed by GilgusMaximus** 2020-11-24 17:54 UTC
Labels: bug
