### ISSUE TITLE
[Bug]: picture-in-picture not working correctly

### ISSUE THREAD

**Issue by mohitrajsinh7173** [FreeTubeApp/FreeTube#5205] opened 2024-06-01 05:55 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When I am playing a video and i click on picture-in-picture (pip) button the video goes to pip mode, now if i go to other page (e.g. subscription page, trending page etc.) or search something, the pip window is still there and playing the video fine, but now if I click on "back to tab" on pip window it is supposed to take me back to the page where the video is playing originally, but when i click on "back to tab" I remain on the same page where I am currently in, the video disappears but the audio is still playing. 

### Expected Behavior

When I click on "Back to tab" in pip windows it should take me to the original page where video is playing.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.20.0 beta

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-06-01 06:17
Duplicate of #624

**Closed** 2024-06-01 06:18 UTC
Labels: bug, B: inconsistent behavior
