### ISSUE TITLE
[Bug]: I am in full screen (app) all the time and cannot click the red cross to exit it, can't see my taskbar/dock

### ISSUE THREAD

**Issue by BarbzYHOOL** [FreeTubeApp/FreeTube#3406] opened 2023-04-07 21:26 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I don't know why, it started to happen randomly without any update.
I'm inside freetube and can't see my taskbar (or docker if I had one)

*Can't send you a screenshot it's on another computer*

### Expected Behavior

Always display the taskbar and menu bar

### Issue Labels

usability issue

### FreeTube Version

v0.18

### Operating System Version

Linux Mint 20

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-04-08 22:40
could u try pressing f11

**Comment by absidue** [comment] 2023-04-08 22:54
looks like this might be a the same things as #3220

**Comment by BarbzYHOOL** [comment] 2023-04-11 02:06
F11 doesn't work

But in the Issue they talk about Super+M which I'm gonna try

But it seems like it's a bug nonetheless (and I had no idea which keywords to type to find it on github)

**Comment by BarbzYHOOL** [comment] 2023-04-13 19:36
> could u try pressing f11

I tried again and it worked -__-

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-04-13 20:02
Duplicate of #3220

**Closed** 2023-04-13 20:02 UTC
Labels: bug, B: usability
