### ISSUE TITLE
[Feature Request]: Custom keybindings/keyboard shortcuts

### ISSUE THREAD

**Issue by Mark3xtrm** [FreeTubeApp/FreeTube#5944] opened 2024-10-26 11:29 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [x] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I´d like to have the ability to customize every existent keyboard shortcut with a key (or a combination of keys) of mine.
Now I can´t edit anything, and in the settings doesn't seem to be anything related.

Please, add this option, it would be very useful. Especially for people that have other system wide keybindings, or simply for those who want to change the default ones.

### Proposed Solution

Add a *Keyboard shortcuts* (or something like that) section to the *Settings menu in order to be able to customize them.

Bonus: add the ability to create custom shortcuts/actions (EG: the ones in extensions like *Tweaks for YouTube*) that could let us create shortcuts from scratch, or from a set of atomic commands.

### Alternatives Considered

If create shortcuts from scratch isn't doable, please at least give us the opportunity to customize the existing ones like said before

### Issue Labels

improvement to existing feature, new feature, new keyboard shortcut

**Comment by absidue** [comment] 2024-10-26 12:00
Duplicate of #251

**Closed by absidue** 2024-10-26 12:00 UTC
Labels: enhancement, E: improvement existing feature, E: new feature, E: keyboard shortcut
