### ISSUE TITLE
[Feature Request]: Download status

### ISSUE THREAD

**Issue by siteleas** [FreeTubeApp/FreeTube#2357] opened 2022-06-23 20:35 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

When you click the download link for a video and specify the file format and quality settings you want, then give FreeTube the save location the download presumably starts, but I see no indicator to track download progress of files. There does not appear to be a download queue, or at least I don't know where to look for it.

### Proposed Solution

I haven't seen in the FreeTube documentation information on seeing the download queue or individual download status. I recommend that the documentation be updated on where to find this information, and also that there would be a status indicator and a drop down list showing queued downloads and download status per queued items, along with a section for completed downloads.

### Alternatives Considered

If the default browser is being used for downloads, an indicator should be presented in FreeTube once a download has started that can be clicked to describe how to view the download status in the default browser.

### Issue Labels

display more information to user

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-06-23 22:08
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2110

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-06-23 22:08 UTC
Labels: enhancement, E: display more information
