### ISSUE TITLE
[Bug]: Import subscriptions not working

### ISSUE THREAD

**Issue by bluescorpion-ai** [FreeTubeApp/FreeTube#4183] opened 2023-10-18 17:16 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Import the csv from youtube. Program message says may take a while. I'm waiting over 5 hours without success. Close and reopen app and still nothing.

### Expected Behavior

.

### Issue Labels

content not loading

### FreeTube Version

v0.19.1 Beta

### Operating System Version

macos ventura

### Installation Method

.dmg

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-18 19:17
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3943

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-18 19:17
Try steps listed https://github.com/FreeTubeApp/FreeTube/issues/3943#issuecomment-1766332249

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-10-18 19:17 UTC
Labels: bug, U: duplicate, B: content not loading
