### ISSUE TITLE
[Bug]: Some videos that are supposed to be in English aren't in English

### ISSUE THREAD

**Issue by RagglenLove** [FreeTubeApp/FreeTube#3874] opened 2023-08-14 04:18 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Play 'https://youtu.be/sD-hb8FmEGc' via FreeTube.

Attached to this bug report is a video of the bug.

https://github.com/FreeTubeApp/FreeTube/assets/45503845/9035c5e4-19a5-4b38-8bb4-cdad5924b1bb

### Expected Behavior

The video should be in English since local preference is "English (US)".

![Screenshot_2023-08-14_12-14-33](https://github.com/FreeTubeApp/FreeTube/assets/45503845/477f9c82-462c-494d-88b9-adcb2cc8a853)

### Issue Labels

usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Xubuntu 22.04 LTS

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-08-14 05:46
This is already solved in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2419

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-08-14 05:46 UTC
Labels: bug, B: usability
