### ISSUE TITLE
Time when the video was uploaded doesn’t show on shorts , but does in regular videos  

### ISSUE THREAD

**Issue by sallyFoster** [FreeTubeApp/FreeTube#5161] opened 2024-05-23 22:09 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

<img width="1597" alt="image" src="https://github.com/FreeTubeApp/FreeTube/assets/104597302/5c559b22-dcb4-41a6-9717-86182e0df6b3">

One cannot see when the shorts were uploaded

<img width="1594" alt="image" src="https://github.com/FreeTubeApp/FreeTube/assets/104597302/c43e98cd-a2a0-46a7-a7b3-bbc13dd3c4a1">

but one can see when the regular videos were uploaded 

### Expected Behavior

It shows when the shorts were uploaded the same way it shows for regular videos 

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.20 Beta

### Operating System Version

MacOS Soma 14.4.1

### Installation Method

.dmg

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-05-23 22:26
While I can understand that it might be unexpected, this is not a bug. FreeTube can only show information that YouTube provides and they don't have the published dates or video durations on the shorts channel tab (you can check on the official YouTube website in your web browser if you don't believe me).

Closing as there is nothing we can do about it.

**Closed** 2024-05-23 22:26 UTC
Labels: bug, B: inconsistent behavior
