### ISSUE TITLE
Back/ Previous Button Issue | Back Function & Home Function conflict

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1961] opened 2021-12-20 23:16 UTC
**Behavior of the program**
The **"Back" or "Previous" Button doesn't fall back to the previous page as needed or expected, instead goes back to the Subscriptions Page during the Search**.
This behavior ruins the practical search and user experience and leads to consuming more time in the process of browsing the needed content.

**Expected behavior**
In the expected state, the **back function** needs to go back to the **previous page**.
The **Back button/ function works the same as the Home button, which should not happen**.

**To Reproduce**
N/A
       - I don't know how to show the conflict but it can be understood while comparing the same function between official YouTube and FreeTube.

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: 0.15.1 beta
 - Installation Method (If applicable): .exe

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-12-21 16:56
Do not leave things out of the template.

I would like to see steps to reproduce.

**Comment by bachig26** [comment] 2021-12-22 03:32
> Do not leave things out of the template. It is possible that ur issue will get closednif u do that.
> 
> I would like to see steps to reproduce.

I removed the topics in the template that I don't know what to fill, I'll try to avoid in future issues.

"**To Reproduce**
N/A
       - I don't know how to show the conflict but it can be understood while comparing the same function between official YouTube and FreeTube."

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-12-22 06:40
Could u maybe upload a video?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-09 18:26
@bachig26 please respond to the request

**Comment by bachig26** [comment] 2022-01-09 19:04
> @bachig26 please respond to the request

I forgot about this issue.
at present, I cannot reproduce this issue as happened before. I don't know why.
can you try if this appears for you?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-09 19:08
i dont understand how to reproduce it

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-09 21:24
I have to close this because author cant reproduce.

feel free to comment if u can reproduce and share the steps to reproduce

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-01-09 21:24 UTC
Labels: bug
