### ISSUE TITLE
[Bug]: Appimage, deb, and flatpak will not play videos on Ubuntu 24.10

### ISSUE THREAD

**Issue by linuxosd** [FreeTubeApp/FreeTube#6014] opened 2024-10-29 15:00 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open Freetube appimage, deb, or flatpak on Ubuntu 24.10 Gnome
2. Click to play a video

### Expected Behavior

Videos should play but clicking on the play button does nothing and the entire app screen crashes and nothing can be clicked on other than closing the application. The previous version worked just fine.

### Issue Labels

causes crash, content not loading

### FreeTube Version

0.22.0

### Operating System Version

Ubuntu 24.10 Gnome

### Installation Method

.deb

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

0.21.3

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-30 22:30
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5975

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-30 22:30 UTC
Labels: bug, B: content not loading, B: crash

**Comment by linuxosd** [comment] 2024-10-30 23:06
This is not a duplicate of the other issue. I never get a white screen and that is what others are getting on the other issue. Please reinstate this issue since it is entirely different.
