### ISSUE TITLE
This video is unavailable in your country

### ISSUE THREAD

**Issue by Joseph65** [FreeTubeApp/FreeTube#34] opened 2018-03-11 02:50 UTC
i keep getting this popup "this video is unavailable in your country"
when i watch a korean link but when i open the link in chrome or firefox it plays fine.

**Comment by Larivact** [comment] 2018-03-11 05:37
The problem is that FreeTube resolves videos using a youtube-dl-api-server, which is located in the USA, so any videos restricted in the USA won't work. The only way to circumvent this is to run youtube-dl in a country where the video is allowed (or to use a proxy). Both of which currently isn't an option.

**Comment by PrestonN** [comment] 2018-03-12 01:13
Hey.  This should be fixed with the next update.  I have youtube-dl running locally on the application like @Larivact suggested.  I will close this issue for now but if it comes up again please re-open or make a new issue.

Thanks!

**Closed by PrestonN** 2018-03-12 01:13 UTC
