### ISSUE TITLE
[Bug]: Hotkeys only work on latin keyboard layouts

### ISSUE THREAD

**Issue by EvilGremlin** [FreeTubeApp/FreeTube#3615] opened 2023-05-31 18:31 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [x] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Just updated to v0.18.0-nightly-2990 and noticed that it's not hotkey but hotletter now

### Expected Behavior

hotkeys must never depend on layout

### Issue Labels

usability issue

### FreeTube Version

v0.18.0-nightly-2990

### Operating System Version

Mint 22.1

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18.0-nightly-2949

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-05-31 21:57
Can you please give us a bit more detail in what exactly is broken (e.g. which keys/combinations and what pages) and how we can replicate the issue? That will make it possible for us to investigate and figure out the problem.

**Comment by EvilGremlin** [comment] 2023-05-31 23:51
FJKL etc in player. Dont respond when in cyrillic layout.

**Comment by absidue** [comment] 2023-06-01 06:35
Please check that the keyboard focus isn't on one of the player buttons, as video.js swallows keyboard events when e.g. the fullscreen button is focused.

**Comment by EvilGremlin** [comment] 2023-06-01 10:29
Nope, focus is not on buttons (though even if it is hotkeys must work properly anyway)

**Comment by absidue** [comment] 2023-06-01 10:32
As the player hotkeys are working completely fine for me on Windows 10, I'm tagging this issue as Linux only.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-06-01 15:56
@EvilGremlin could u maybe create a screenrecording? I cant reproduce this in Ubuntu.

What i would like u to include in the screen-recording before u use the shortcuts: 

- Click on any thumbnail that brings u to the video page
- After that dont click anywhere and try to use the shortcuts
- Then Click somewhere in FT and use the shortcuts

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-06-01 16:01
@EvilGremlin is it in all latin keyboard layouts? I tested with a random latin layout on Ubuntu and all shortcuts u mentioned are still working for me.

**Comment by EvilGremlin** [comment] 2023-06-01 16:07
Yep, any latin where letters are same work, any cyrillic don't.

**Comment by absidue** [comment] 2023-06-01 16:27
The physical locations of keys doesn't matter, FreeTube only cares about the actual value of the keyboard event. We check for both upper and lowercase letters, so that we aren't affected by shift or caps lock. So all latin keyboards should work completely fine.

I'm guessing we need to add special handling for Cyrillic characters, mapping them to their latin equivalents and pairing others together when there isn't a direct equivalent.

**Comment by absidue** [comment] 2023-06-01 16:32
Additionally nothing player hotkey related changed between your listed working and broken versions. So either it's been broken since before the 0.18.0 stable release and you just didn't notice it before or you've changed something outside of FreeTube in your linux environment that broke it.

**Comment by EvilGremlin** [comment] 2023-06-01 16:34
yeah, likely it's regression in some dependency

**Comment by absidue** [comment] 2023-06-01 16:39
Not a dependency inside FreeTube, we do the hotkey handling ourselves using the standardised JavaScript `KeyboardEvent.key` API. So the only thing that might affect it is Electron, which we haven't upgraded since the 6th of February (https://github.com/FreeTubeApp/FreeTube/pull/3154).

**Comment by EvilGremlin** [comment] 2023-06-01 16:41
hmmm, will recheck previous builds later

**Comment by EvilGremlin** [comment] 2023-06-30 19:40
bump, still an isuue in latest build

**Comment by absidue** [comment] 2023-07-01 14:15
Just going to leave this here for when someone wants to work on adding support for non-latin layouts.

FreeTube doesn't support non-latin layouts, this is not a regression, we just haven't added support for them yet. Why doesn't it just work?
The keyboard shortcuts and hotkeys don't rely on the physical position of the keys, instead they rely on the values they return. That means to rewind by 10 seconds, FreeTube needs to receive a key event that has the value of `J` it doesn't matter where that key is on the physical keyboard, but that means for keyboard layouts that don't have a `J` key, like cyrillic ones, you can't currently trigger that hotkey.

The solution will have to be some hacky mess that tries to detect whether the active keyboard layout is a latin one (not sure how we are going to detect that, considering that there are no APIs to do that) in which case it needs no special handling and otherwise it will likely have to act as if the user has an English QWERTY layout. Ideally we want to keep the behaviour of not caring about the physical locations of keys when we can, otherwise we'll have to get rid of the docs page with the hotkeys because they will be completely different for every layout.

**Comment by EvilGremlin** [comment] 2023-07-01 20:41
How every other app does that then? Starting with youtube werb player itself. Seriously, FreeTube is only one that i've seen in 20 years which stops reacting to hotkeys in different layout. And translating hotkeys is just abyssmally horrible manners, no one does that, i only seen this in badly made games. Hotkeys legend must always stay english.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-07-01 20:54
> The solution will have to be some hacky mess that tries to detect whether the active keyboard layout is a latin one (not sure how we are going to detect that, considering that there are no APIs to do that) in which case it needs no special handling and otherwise it will likely have to act as if the user has an English QWERTY layout. Ideally we want to keep the behaviour of not caring about the physical locations of keys when we can, otherwise we'll have to get rid of the docs page with the hotkeys because they will be completely different for every layout.

Could https://github.com/FreeTubeApp/FreeTube/issues/251 help out with this?

**Comment by EvilGremlin** [comment] 2023-07-01 20:58
Not directly and not in a right way i think. Even when you input custom hotkeys, apps always use english layout despite current active one is not.

**Comment by EvilGremlin** [comment] 2023-07-30 06:54
bump

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-14 18:49
Closing, converted to a feature request in https://github.com/FreeTubeApp/FreeTube/issues/4150 because like already said this isnt a bug

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-10-14 18:49 UTC
Labels: bug, OS: linux, B: usability
