### ISSUE TITLE
Default select of subtitles 

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [FreeTubeApp/FreeTube#682] opened 2020-10-17 13:00 UTC
Add a settings to select the subtitles by default (as in video quality settings) or like the one in invidious to select first subtitle and if it's not there, select second one or third one so yeah it would be nice

**Comment by GilgusMaximus** [comment] 2020-10-18 15:02
Hi.
This is a good idea for sure, unfortunately we have some issues with subtitles not loading on dash format sometimes.
So adding default subtitles would interfere with this issue, to which we have not found a viable solution yet. Unfortunately.

**Comment by EsmailELBoBDev2** [comment] 2020-10-19 12:22
what about make it and add your notes (that it might not always work) *at least for now*

**Comment by GilgusMaximus** [comment] 2020-10-20 10:22
We are open for pull requests if someone wants to implement that.
However without having a fix for the other issue, we'll get issues mentioning that it doesn't work. 

Additionally we are currently working on a pretty packed set of features for 0.10, as seen [here](https://github.com/FreeTubeApp/FreeTube/projects/4), in our free time. So we first have to focus on the things we already planned to implement and then look forward what else to implement. And from November on, the development will slow down again, because I won't have much free time anymore.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-03-08 07:58
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/62

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-03-08 07:58 UTC
Labels: enhancement
