### ISSUE TITLE
[Bug]: Error: a javascript error occored in the main process

### ISSUE THREAD

**Issue by wben73** [FreeTubeApp/FreeTube#5027] opened 2024-04-26 15:19 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

thank you for this great app. today on my other laptop i keep getting this error please fix soon.
it says : uncaught ecception. typeerror: object has been destroyed.
at app. <anonymous>
then it has a directory in my c drive: appdata\local\programs\FreeTube\resources\app.asr\dist\mai....:243466
at app.emit (node:events:514:28)

### Expected Behavior

popup with the info pasted above. keeps popping up cannot open Free Tube.

### Issue Labels

causes crash

### FreeTube Version

v0.22.0

### Operating System Version

windows 10

### Installation Method

.zip

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.1

### Additional Information

 sorry everything posted above. just wanted to add. please keep up the good work, its a great app with great features. i use screenshots and occasionally the browser downloader. hoping the app will get higher resolution downloads eventually. 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-27 10:28
Hi @wben73 this issue is actually a duplicate of 
https://github.com/FreeTubeApp/FreeTube/issues/4762 therefore im closing this one.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-27 10:28 UTC
Labels: bug, B: crash
