### ISSUE TITLE
[Feature Request]: Pitch and Speed Control

### ISSUE THREAD

**Issue by ccateni** [FreeTubeApp/FreeTube#2550] opened 2022-09-08 03:36 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

On other apps like Newpipe, I'm able to not only change the speed to whatever I want, but also change the pitch separately allowing for some great effects to videos I'm watching. I would love to see something similar implemented to the app.

### Proposed Solution

One way is to use the Newpipe example, That app allows for the speed and pitch to be separated into two different tools and allow for great customization. It also includes tools to unhook the pitch and speed alongside changing the pitch from semitones to percent.

### Alternatives Considered

Apps like Transpose for Chrome (https://transpose.video/) also allow for changing the speed and pitch of the video without combining the two using similar methods.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-09-08 09:32
Duplicate of #1850

**Closed** 2022-09-08 09:32 UTC
Labels: enhancement, E: new feature
