### ISSUE TITLE
[Bug] Long videos cause unexpected problems in FreeTube.

### ISSUE THREAD

**Issue by ModdedGamers** [FreeTubeApp/FreeTube#1065] opened 2021-02-26 16:10 UTC
**Behavior of the program**
When viewing very long videos(a 19.5 hour video in this case), once the video loads, you can't control anything in FreeTube. Also, no audio is played.

**Expected behavior**
I expected to be able to hear and watch the video.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to https://youtu.be/_rnUCkKjJZQ
2. Wait for the video to load
3. Try doing any action in FreeTube, both related to the video(pause/play, full screen, etc.) and not(going to subscriptions page, settings page, etc.) Scrolling works but is extremely delayed.
4. See that nothing happens and that you can't hear anything.

**Screenshots**
N/A
**Environment Information (please complete the following information):**
 - OS: macOS
 - OS Version: 10.14.2
 - FreeTube version: 0.11.3
 - Installation Method (If applicable): .DMG
 - Primary API Used: Local API

**Additional context**
This only happens on this video. Other long videos play audio, but are stuck in the lowest quality, and the same input glitches occur.

**Comment by GilgusMaximus** [comment] 2021-02-26 17:39
Hi, so your bug report has multiple things to sort out here.

First of all, very long videos seem to be a problem. As the application works fine for normal stream length of ~2-5 hours. But somewhere up at your 15/17 hour mark it starts to become a problem. We already had someone who watched a 200 hour video and obviously encountered problems #845 .

The problem with the 'lag' in the application is most likely related to the video player trying to stream and buffer data, of which a lot is available, and it loads for a few seconds. However I am unable to reproduce the complete freeze of the application once the video starts playing. I can go to fullscreen just fine, scroll up/down, load comments etc... This could be related to hardware, internet bandwidth available at the moment, etc.

The low quality for many videos is related to #1055, please check that one out.
This is also the reason for the missing audio here. The dash file looks like this, so we only have one audio stream available, but it is in webm format (see #1055): 

![image](https://user-images.githubusercontent.com/34301369/109334637-459cd900-7861-11eb-9368-7cc0cd4b330e.png)


So the application freeze seems to be a bit dependent on the setup of the host system, while the missing audio is a problem of the streaming plugin not supporting webm formats and YouTube not always providing these in the format we support atm. 

However, a solution for the moment is to switch to legacy player and then watch the stream. For this video now you will not have any quality options. Why that is, no idea. But you can watch with audio. 
![image](https://user-images.githubusercontent.com/34301369/109334978-b47a3200-7861-11eb-9ca9-4d87b73d991d.png)


I would now suggest the following:
Once my exams are done, I wanted to revisit the dash file generator (for the formats) anyways, so I will check whether there is anything I can improve to get more formats available.

In the mean time, I would open up a new discussion issue, where I'd use the video you provided as a benchmark to see what other users report about the freeze of the application.

Therefore I will close this issue

**Closed by GilgusMaximus** 2021-02-26 17:39 UTC
Labels: bug
