### ISSUE TITLE
[Feature Request]: Ability to save playlists  to a cloud service, personal server or something to access them on a different device

### ISSUE THREAD

**Issue by Huecuva** [FreeTubeApp/FreeTube#6478] opened 2024-12-29 22:54 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I'm sorry if this has already been requested. I have done some searching and couldn't find anything that matched and I'm not really even sure how to word my search for such a thing so if it has already been requested, I apologize.

I have an HTPC in my living room and another one in my bedroom. Currently, they have separate playlists and are managed completely separately. It makes it hard to want to watch YouTube from my bedroom because my playlists are all in my living room and in order to carry on in my bedroom I would have to manually search for the videos and recreate the playlist on my bedroom HTPC or manually export the playlist from my living room HTPC and then import it to my bedroom HTPC, and then once I'm back in my living room I would again have to either manually export from my bedroom and import to the living room or manually delete whatever videos I watched in my bedroom from the living room playlist and add whatever videos I added...it's very hard to keep track of.

### Proposed Solution

What I'm requesting is a way to access playlists created in FreeTube on one machine from another machine. I would like for some way to be able to watch the same playlist in my bedroom as I do in my living room.  I'm aware that there is currently (I think) a way to manually export your playlists and then sneakernet them via USB stick or something to another machine and import them and I realize this could technically be done over my LAN using my server as well but, as mentioned above, it's very hard to keep track of.

### Alternatives Considered

Personally, I have a personal file server to which FreeTube could save the playlist from my living room HTPC and then I could import it to my bedroom HTPC. It would be nice to simply configure FreeTube to just automatically save the playlist to a server and then when I boot up FreeTube in my bedroom it could be configured to automatically import the playlist and any changes made to it from my server. Added or removed videos, watch status, etc.

I realize not everyone has a personal server in order to do this, so other ways to accomplish this might be:

A way for FreeTube to detect, either by manually or automatically scanning, other instances of FreeTube on a network and share playlists between them. 

A way to configure FreeTube with IP addresses for all devices on the LAN with FreeTube installed so it could, manually or automatically, transmit the playlist to each device. 

Maybe even a function to, in real time, as long as both machines are online, sync the playlist so that any changes that are made are immediately enacted on both machines.

It would also need to determine which playlist was the updated one and which was the outdated one whether it was syncing between peers or with a server. 

In any case other than the server, I would need to have both machines booted up at once initially and then I could shut one down once they're synced. It would not be ideal, but I could live with that. Maybe both methods could be implemented and configured based on the needs of the user.

This would be keeping in line with YouTube functionality of logging in and having playlists available on any machine I'm logged into. These are just suggestions. If you decide this is a feature worth adding and come up with some other feasible, possibly better,  way of implementing it...well, whatever works.

### Issue Labels

ease of use improvement, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-29 23:30
Duplicate of #370 + see maybe useful comments


Another piece of useful info: https://github.com/FreeTubeApp/FreeTube/issues/6454#issuecomment-2562532010

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-29 23:30 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement

**Comment by Huecuva** [comment] 2024-12-30 00:33
Okay. That first link refers to syncing subscriptions, not playlists. I'm not sure if it would be the same thing. The second just talks about syncing but doesn't specify whether it's for subs or playlists. Apologies if they actually encompass both, but I'm just looking for a way to share playlists between FreeTube on different machines. I will dig into that second link a little further and see if the symlinking thing works for my purposes. I also don't use NewPipe or Invidious.

It appears that this Syncthing could be a stopgap solution for this problem.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-30 00:43
it doesnt matter what file the other issue are talking about they are all stored in the same location, see https://docs.freetubeapp.io/usage/data-location/
