### ISSUE TITLE
[Feature Request]: Allow downloader or combine video+audio

### ISSUE THREAD

**Issue by Aphexus** [FreeTubeApp/FreeTube#6179] opened 2024-11-16 22:01 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Using the download button separates video and audio. This requires, then, one to manually combine them.

### Proposed Solution

Allow one to add an external downloaded. This can be done by specifying a file to run with the url as an argument passed.

E.g., I might want to use youtube-dl, freedownloader, or a custom batch that does what I would want.

I could do this manually by getting the link and using the command line but it would be nice to automate it. E.g., in the downloads list the top entry could be "Custom" if the custom runner is set in settings.

### Alternatives Considered

tes

### Issue Labels

ease of use improvement, improvement to existing feature, new optional setting

**Comment by absidue** [comment] 2024-11-17 09:56
Duplicate of #4178

**Closed** 2024-11-17 09:57 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: ease of use improvement
