### ISSUE TITLE
Subscription tab: Don't list already existing videos after subscribing to a channel

### ISSUE THREAD

**Issue by Karol-G** [FreeTubeApp/FreeTube#1955] opened 2021-12-20 20:02 UTC
Hi,

I just started using FreeTube and subscribed to a bunch of channels. I like to have a tidy "subscription inbox" meaning that only new videos that I haven't watched yet should be listed. So once I watch a video it should not appear in the subscription inbox anymore and if I don't want to watch a video than I can mark it as watched, making the video disapear. Both  features work as intended. 
However, the subscription tab also lists every video of a channel before I even subscribed to the channel, meaning that it is always full of videos. This way I have no overview which videos I still want to watch for later and which ones are just videos from before the subscription.

It would be nice to have an option in the subscription settings to only list new videos of a channel after the subscription :)

Best Karol

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-05 11:19
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/546

**Closed** 2022-01-05 11:19 UTC
Labels: U: duplicate, enhancement, U: doesn't follow template
