### ISSUE TITLE
[Feature Request]: Import subscriptions directly into current profile

### ISSUE THREAD

**Issue by rptb1** [FreeTubeApp/FreeTube#4389] opened 2023-11-26 11:28 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I have thousands of subscriptions split across several accounts.  I would like to import them into separate profiles in FreeTube.  But FreeTube's import only adds them to the "All Channels" category.  There does not seem to be a way to import them into a profile.  It is not practical for me to organise them after import, either individually, or to pick them from the list of channels in the "Manage Subscriptions" system.

### Proposed Solution

When I have a profile selected and use subscription import, add the imported subscriptions to the current profile.

You could add a separate "Import to current profile" button if necessary.

### Alternatives Considered

Create a profile for each import.

### Issue Labels

improvement to existing feature

**Comment by absidue** [comment] 2023-11-26 11:34
Duplicate of #1996

(covered by the additional information section in that issue)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-26 11:35
Basically duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1996

**Closed** 2023-11-26 11:34 UTC
Labels: enhancement, E: improvement existing feature
