### ISSUE TITLE
Develop a localhost WebUI for the client

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#1228] opened 2021-04-23 18:41 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
To use FreeTube, you need to open a client window and maximize it. A way to use it like a browser tab would help a lot with multi-tasking.

**Describe the solution you'd like to see implemented**
Implement a WebUI that launches via the settings and/or a terminal by navigating to localhost:8080 for example.

**Describe alternatives you've considered**
None

**Screenshots**
None

**Additional context**
None

**Comment by PrestonN** [comment] 2021-04-23 18:45
Duplicate of #633

**Closed by PrestonN** 2021-04-23 18:45 UTC
Labels: U: duplicate
