### ISSUE TITLE
[Bug]: FreeTube Fails to Display

### ISSUE THREAD

**Issue by thangnguyenxtz** [FreeTubeApp/FreeTube#5056] opened 2024-05-03 00:58 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to taskbar/FreeTube
3. The main window doesn't open despite the application running in the background and consuming CPU and RAM. No errors are visible to explain the issue, and no window is displayed. I can see the preview of the app running (using Alt + Tab), but I can't interact with it.

### Expected Behavior

The application should open and display its main window upon launch.

### Issue Labels

usability issue

### FreeTube Version

v0.20.0

### Operating System Version

Windows 11 version 23H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

- I have tried restarting both the application and the system, and reinstalling the application, but the issue persists.
- Attached is a screenshot showing the application's process in the task manager.

![image](https://github.com/FreeTubeApp/FreeTube/assets/160583202/6a2e579e-9d7a-4470-bece-2087b15826e3)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-05-03 06:55
Duplicate of #4981

**Closed** 2024-05-03 06:56 UTC
Labels: bug, U: duplicate, B: usability
