### ISSUE TITLE
[Feature Request]: Automatic import / export of subscription / playlists / history

### ISSUE THREAD

**Issue by rasmusthog** [FreeTubeApp/FreeTube#3385] opened 2023-03-31 17:09 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I use FreeTube on Linux and the fork FreeTube Cordova for Android. I enjoy being able to import my subscriptions (including all channels), history and playlists directly into the Android app, but as both export and import is done manually, it can be tedious to keep this updated. I would like a way to synchronise between the two.

EDIT: This also requires this functionality to be incorporate into the Android version, so if this happens, I would request the addition of this into their fork. Regardless, it would serve as a way to sync between different computers.

### Proposed Solution

An easy solution that comes to mind is to enable automatic export and import of subscription, history and playlist data that happens on launch or at defined intervals. By then exporting to a shared location between the Linux computer and Android phone (such as a cloud storage), this should allow easy synchronisation. 

There could be some issues with conflicts here if both apps are used simultaneously, but within the scope of this solution this would be up to the user to handle (using an external synchronisation tool)

### Alternatives Considered

If it is not desireable to add this option to the GUI, then if there could be some kind of CLI command to handle the same thing, then the user could set up a cron job to handle this.

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-04-02 09:01
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/370

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-04-02 09:01 UTC
Labels: enhancement, E: ease of use improvement
