### ISSUE TITLE
Video control bar doesn't disappear fully after being selected with Tab key

### ISSUE THREAD

**Issue by snugglybug** [FreeTubeApp/FreeTube#1233] opened 2021-04-28 01:49 UTC
**Behavior of the Program**
After selecting one of the options on the video control bar (progress bar, seek bar, whatever you wish to call it), the control bar messes with the placement of the video. A black bar appears underneath, and the control bar is still visible after sliding down. Even in fullscreen, the tops of many of the buttons (volume, captions, picture-in-picture) are still visible at the bottom edges of the screen). 

**Expected Behavior**
Here's what the video control bar looks like normally:
![electron_gIaztyufNm](https://user-images.githubusercontent.com/83252721/116333648-57e4b600-a7c3-11eb-9a0a-e522666866f1.png)

**Images of bug**
Black bar underneath the video after selecting the Pause button using Tab. Normally the video reaches down to the white underneath:
![electron_pF7sffoWbs](https://user-images.githubusercontent.com/83252721/116333303-beb59f80-a7c2-11eb-8afe-9ce25d5ab1ea.png)

Even when the Pause button isn't selected, the black bar persists and the control bar only dips down this far:
![VHsVvJKuMT](https://user-images.githubusercontent.com/83252721/116333558-2ec42580-a7c3-11eb-8606-5e6195fdbcc1.png)

It's much less noticeable in fullscreen, but the edges of some buttons are still visible in the bottom corners: 
![electron_atZWOizmLn](https://user-images.githubusercontent.com/83252721/116333540-27048100-a7c3-11eb-814d-13d9e2e60380.png)

**To reproduce**:
1. Start watching a video
2. Click on the video player to ensure it's selected
3. Press Tab

**Environment Information**
OS: Windows
OS Version: Windows 10
FreeTube version: v0.12.0
Installation Method (If applicable): .exe
Primary API Used: Local API

**Comment by Svallinn** [comment] 2021-04-28 16:49
Duplicate of #695

**Closed** 2021-04-28 16:50 UTC
Labels: bug, duplicate
