### ISSUE TITLE
Scrolling flicker

### ISSUE THREAD

**Issue by fractalf** [FreeTubeApp/FreeTube#1621] opened 2021-08-28 20:05 UTC
Hi!

First off, thanks a lot for a great project :)

I just installed v.0.13.2 for on my Linux Mint 20.1 (based on Ubuntu 20.04), tried both the .deb and the .AppImage, same problem.

As you can see in the screen-video here sometimes (quite often) the whole page just seems to flicker like mad. I haven't seen a logical pattern to when it hits, and reset all settings and restarting the app will sometimes help if I try a few times.

![flicker-bug](https://user-images.githubusercontent.com/5707457/131229730-aee5b665-9fc0-46e1-8fe4-21bb89f8c6aa.gif)

Cheers

**Comment by ChunkyProgrammer** [comment] 2021-08-28 21:42
Duplicate of #1442

**Closed by ChunkyProgrammer** 2021-08-28 21:42 UTC
Labels: bug
