### ISSUE TITLE
[Bug]: Subtitles are Locked to the Size of the Player When They Were First Displayed

### ISSUE THREAD

**Issue by rehashedsalt** [FreeTubeApp/FreeTube#5478] opened 2024-07-27 05:18 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Launch FreeTube
2. Navigate to a video that has subtitles ([here's the one I observed the behavior on](https://youtu.be/XRCprhlz4D8))
3. Enable subtitles, play the video, and wait for one to be displayed
4. Pause the video and either resize the window or toggle theater mode on/off to resize the player
5. Observe that subtitles are not repositioned to account for the new size of the player
6. Allow the video to play and display more subtitles
7. Observe that those subtitles are positioned appropriately for this size of player
8. Pause the video and reposition the player again to some third configuration
9. Seek backward through the video and notice that past subtitles are sized/positioned for the configuration of the player at the time they were first displayed

### Expected Behavior

All subtitles should be repositioned/resized to accommodate the size of the player whenever they are displayed and when the window is resized.

### Issue Labels

text/string issue, visual bug

### FreeTube Version

0.21.2 Beta (as reported by Flatpak)

### Operating System Version

Fedora 40 (Sway Atomic, but it's the same packagebase)

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

Here are a couple pictures of the observed behavior:

![image](https://github.com/user-attachments/assets/672447b5-b33e-4836-80f4-c7e0782efabd)

![image](https://github.com/user-attachments/assets/1b6a41a6-eb65-43c0-a076-c633529d78e5)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds). (Repro'd on cd5d293, head of development at time of writing)

**Comment by rehashedsalt** [comment] 2024-07-27 05:19
Footnote: this may constitute an a11y issue -- I wasn't sure enough about that to tag it as such.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-27 07:14
Duplicate of #3920

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-27 07:14 UTC
Labels: bug, B: visual, B: text/string
