### ISSUE TITLE
No content shown a.t.m.

### ISSUE THREAD

**Issue by Woodhousemelena** [FreeTubeApp/FreeTube#485] opened 2020-05-27 07:02 UTC
Since may 24, I can not playback any content. I get this error:
Invidious API Error: Could not extract video info. Instance is likely blocked. Trying other method to retrieve video.  

Futhermore freetube will tell me all my subscribes channels do not exist !? Is it a general problem or a local one on my side?

**Comment by Brin-o** [comment] 2020-05-27 08:38
I'm also getting this error D:

**Comment by p2635** [comment] 2020-05-27 11:25
My search does not return results, much less play videos

**Comment by kru520** [comment] 2020-05-27 12:50
+1
Same issues on Windows 8.1 and Debian 10.4 (using the 0.7.2 beta release)

**Comment by torriem** [comment] 2020-05-27 13:53
Well we've had a good run. The problem is YouTube is blocking Invidious instances now (it's a captcha issue).  I don't see any way around that, unfortunately.  Several of the people I watch are posting to LBRY now. Maybe I'll have to start watching there and abandon YouTube for the most part.

**Comment by PrestonN** [comment] 2020-05-27 15:07
Hey everyone, I wanted to give everyone an update on what's going on.  As you've probably figured out, there have been some problems with Invidious being able to get data from YouTube.  You can learn more about the issue overe [here](https://github.com/omarroth/invidious/issues/1183) on the Invidious repo.  I do believe that this can be fixed and that we will be back up whenever it can be worked on.

In the meantime, switching to a different instance and having "Grab Videos Locally" enabled in your settings will be the best bet on being able to play videos through FreeTube.  This still may not work properly (Due to poor logic handling in FreeTube) but it can after a couple of tries.

I'm also working on something that should help out with this issue.  It's still pretty early but I'm hoping to have it out later this week.  I'll update here and in various places when it's ready, so be on the lookout for it.

**Comment by Johnnyreyman** [comment] 2020-06-04 06:58
Why not switch the backend to NewPipe?

**Comment by Brin-o** [comment] 2020-06-15 06:30
I'm reposting here because there are issues again:
`Error parsing config: Unexpected token ; in JSON at position 83138`

**Comment by PrestonN** [comment] 2020-06-15 21:18
Hey everyone.  I'm guessing that more people have experienced this issue at this point.

YouTube has removed their old layout today.  This was the layout that they had before they used Polymer.  Removing this ended up breaking some functionality with Invidious.  You can track progress of the issue over in the Invidious repo [here](https://github.com/omarroth/invidious/issues/1241).

As for a fix in FreeTube, enabling `Grab Videos Locally` should in theory fix it.  It's been a while since this module has been updated so it might be worth making an update so that this can be functional again. It might have been affected by this as well so I'll get this updated as soon as I can.

I won't be able to work on this right away, but in the meantime, you can try out the FreeTube rewrite by grabbing the latest artifact over in the [GithHub Actions](https://github.com/FreeTubeApp/FreeTube-Vue/actions) page.  At this time, the rewrite is fully functional and usable despite the current issues with Invidious.

**Comment by esotericDisciple** [comment] 2020-06-15 23:11
How do you grab the appimage files?

**Comment by PrestonN** [comment] 2020-06-16 00:38
Unfortunately you'll have to be signed into GitHub to download the files. There isn't anything I can do about that. The real solution would be to upload them to the GitHub releases page which would make them available without signing in. If I do that I'd like to make it happen automatically through the CI tool instead of doing it manually.

**Comment by grrrrr** [comment] 2020-06-16 13:04
@PrestonN sorry if this is not the right place for the question but...

Now that invidious have fixed things their end  (https://github.com/omarroth/invidious/commit/d30a972a909e66d963ee953349fe045a1d9a41ee ),  if proxying through invidious, why is FreeTube impacted by the change on YouTube?

**Comment by PrestonN** [comment] 2020-06-16 14:56
Whenever `Grab Videos Locally` is enabled, FreeTube will attempt to get video information on it's own alongside Invidious.  The package that is included with FreeTube hasn't been update to upstream in a while so there's a chance that that could fail a little more often with the recent changes.  It would be worth updating that package to match upstream so that we can minimize any issues.

Besides that functionality.  FreeTube uses Invidious for everything else.  Everything, except for subscriptions (can be tracked [here](https://github.com/omarroth/invidious/issues/1251) should be working again.  Once the subscriptions are working again then I think we can close this issue.

**Closed** 2020-10-01 10:02 UTC
