### ISSUE TITLE
APIS not working but for different reasons

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#817] opened 2020-11-28 19:29 UTC
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**

iv api:
Videos are playbale, but the following infos are missing:
-Video descriptions
-Number of subscribes
-Up/downvote
-Channels are empty, but not the subscriptions tab

Local api:
Videos are not playable (only a small pic with grey buttons and 0:00 as time indicator) and following infos are missing:
-Number of subscribers
-Likes/dislikes
-Subscribe status on the video pages
-Video title on the window bar
-Channel profile pic

```
TypeError: Cannot read property 'captions' of undefined
```

iv API:
Videos are playable, but infos are also missing:
-Video description
-Channel profile pics
-Like/dislikes
-Number of subscribers
-Videos in individual channels
-Video title on the window bar

**Expected behavior**
A working app

**To Reproduce**
Please add all steps to reproduce the behavior:
Use the app as usual.

**Environment Information (please complete the following information):**
 - OS: Debian
 - OS Version: 10.6
 - FreeTube version: nightly build Build #319
 - Installation Method (If applicable): deb
 - Primary API Used: both

**Comment by PrestonN** [comment] 2020-11-29 01:39
Any Invidious API issue needs to be logged over in their respective repository as missing data from the API is not a FreeTube issue.

The local API extractor was just updated in build 321.  If the issues with the local API are not fixed in that build, please send me a video example so I can confirm the issue and we can create an issue with the upstream maintainer.  Currently I cannot reproduce the issue you're seeing with data missing from a video.

Since neither one of these problems are related to issues on the FreeTube side (or involve modules that we manage), I will close this issue.

**Closed by PrestonN** 2020-11-29 01:39 UTC
Labels: bug
