### ISSUE TITLE
[Feature Request]: Autoplay subscription list

### ISSUE THREAD

**Issue by bussdriver** [FreeTubeApp/FreeTube#4373] opened 2023-11-22 23:51 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

It would be incredibly useful to automatically play all the subscription videos in order. 

### Proposed Solution

Simply add a checkbox in the settings for Autoplay subscriptions in the subscriptions area then just continue to the next item in the subscriptions automatically.

### Alternatives Considered

1) Add subscription videos to a playlist to achieve the same end result; however, there does not seem to be any way to add videos from the subscription page to a playlist.

2) hit back button to see subscriptions and click next video; however, it does not scroll down to the last position so one has to hunt for the video just played to know what is next.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-23 11:25
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/413

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-23 11:25 UTC
Labels: enhancement, E: new feature
