### ISSUE TITLE
[Feature Request]: Remember Filter Search settings

### ISSUE THREAD

**Issue by Brier1104** [FreeTubeApp/FreeTube#2499] opened 2022-08-20 16:14 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Filter Search settings are not saved between sessions.

### Proposed Solution

An option to remember Filter Search settings between sessions. This would be very useful.  For example, most of the time I want to see my search results sorted by Upload Date.

### Alternatives Considered

A an option to save a default Filter Search.

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-31 14:24
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/646

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-08-31 14:24 UTC
Labels: enhancement, E: new optional setting
