### ISSUE TITLE
[Bug]: is:issue is:open when clicking on links i get several errors including SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON. but dont know how to adjust server settings

### ISSUE THREAD

**Issue by EldonTheStrange** [FreeTubeApp/FreeTube#6362] opened 2024-12-12 14:43 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

cant watch a lot of things

### Expected Behavior

when clicking on thumbnails to view i get several errors including SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON. but dont seem to have access to server settings

### Issue Labels

API issue

### FreeTube Version

v0.22.0

### Operating System Version

linux mint cinnimon 21.3

### Installation Method

.apk (Alpine Linux Package)

### Primary API used

Invidious API

### Additional Information

i never had this issue until today, and a lot of content still works, but it seems music in perticular is failing to load

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-12 16:56
Duplicate of #6328

**Comment by absidue** [comment] 2024-12-12 16:57
Duplicate of #6328

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-12 16:57 UTC
Labels: bug, B: API issue
