### ISSUE TITLE
[Feature Request]: Custom video speed of a video applied to all videos the channel

### ISSUE THREAD

**Issue by BarbzYHOOL** [FreeTubeApp/FreeTube#4849] opened 2024-04-04 00:28 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When we watch a video of a channel and we speed it up, it's most likely because the youtuber is too slow to speak or boring. So we speed it up. And of course, it applies to almost 100% of his videos. Therefore it's pretty annoying to have to set the speed on EACH of his video (if the dude makes tons of small videos for example). By listening to these slow talking dudes, we waste precious minutes of life.

### Proposed Solution

When we set the custom speed for a video, it should remember it for every video of the channel. We can change it back to x1 if needed.

### Alternatives Considered

Make it optional eventually

### Issue Labels

ease of use improvement, improvement to existing feature, new optional setting

### Additional Information

Please, save us time.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-04 05:35
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2295

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-04 05:35 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: ease of use improvement

**Comment by BarbzYHOOL** [comment] 2024-04-05 01:28
@efb4f5ff-1298-471a-8973-3d47447115dc no this is totally UNRELATED
I'm talking about a "per channel" default speed, not a global default speed

That does not make sense to have x1,5 speed on a video, then you switch to a music channel and the music is set to x1,5

Please, reopen
@PrestonN

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-05 02:48
We're not going to implement such a feature.

**Comment by BarbzYHOOL** [comment] 2024-04-07 01:49
You arbitrarily close suggestions based on your own misunderstanding (it's like you don't even use freetube yourself). I was certain you would not reopen, like you did multiple times.  One low IQ dude with a retarded name is deciding for all Freetube users, nice
You guys added playlists after 5 years of us stacking videos in favorite and now all the videos in favorite are listed in the oldest order, so all the newest videos are not accessible (unless you want to scroll forever to the bottom). Did you even test the PR before merging? I put the blame on you most likely since you're the one making all the idiotic calls

hence why I called @PrestonN for help in my last msg
