### ISSUE TITLE
[Feature Request]: Automatic Updates

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [FreeTubeApp/FreeTube#5555] opened 2024-08-11 10:25 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I need to manually update FreeTube.

### Proposed Solution

All it needs is a checkbox to "Automatically update".
If someone trusts a project enough they can check it, for paranoid people they can leave it unchecked.
(Unchecked by default)

Because I just want to watch Youtube videos, not to constantly update. It's running on Electron right? So why is there no auto update?

### Alternatives Considered

I don't think there is an alternative to this, either do or don't. I think it wouldn't harm anyone.

### Issue Labels

ease of use improvement

**Comment by absidue** [comment] 2024-08-11 10:32
Duplicate of #841

**Closed** 2024-08-11 10:32 UTC
Labels: enhancement, E: ease of use improvement
