### ISSUE TITLE
[Bug]: Trouble Playing Videos With Sponsorships

### ISSUE THREAD

**Issue by CTRLexe** [FreeTubeApp/FreeTube#6476] opened 2024-12-29 19:58 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to subscriptions
2. Click on Video
3. Play video
4. Get IP blocked message
5. Video won't play
6. Video either works after some time or only works in SMPlayer

### Expected Behavior

Video plays with sponsorship block enabled

### Issue Labels

content not loading, feature stopped working, inconsistent behavior, usability issue

### FreeTube Version

v0.22.1

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.22.0

### Additional Information

It only seems to be videos with sponsorships. I know this because it either works eventually OR I end up playing it in SMPlayer.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-29 20:04
Please provide links to videos

**Comment by absidue** [comment] 2024-12-29 20:05
Duplicate of #6385

**Closed** 2024-12-29 20:05 UTC
Labels: bug, U: Waiting for Response from Author, B: content not loading, B: usability, B: feature stopped working, B: inconsistent behavior
