### ISSUE TITLE
[Feature Request]: Auto-translate Captions

### ISSUE THREAD

**Issue by hix1000** [FreeTubeApp/FreeTube#5577] opened 2024-08-16 23:38 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

(Accessibility issue) No way to translate from Subtitles/Captions to preferred language

### Proposed Solution

Auto-translate button in CC/subtitles menu

### Alternatives Considered

Translate subtitles dropdown and switch in Player settings

### Issue Labels

display more information to user, improvement to existing feature, new optional setting

### Additional Information

Also helps with accessibility.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-06 10:55
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4632

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-06 10:55 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: display more information
