### ISSUE TITLE
[Bug]: When using Invidious API only up to 200 videos are loaded in channel's playlist. 

### ISSUE THREAD

**Issue by ahaone** [FreeTubeApp/FreeTube#4877] opened 2024-04-05 06:50 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When using Invidious API only up to 200 videos are loaded in channel's playlist. When Local API is used the "Load More Videos" option button pops out.
1. Use Invidious API - Regardless of the instance used.
2. Search and choose channel playlist with higher number videos than 200.
3. Open the playlist and scroll down to the bottom of it. You can reach the bottom with no option to load more videos.

![invidious api ](https://github.com/FreeTubeApp/FreeTube/assets/95525436/8e196a52-f3e1-43c5-806b-aaf0f206e093)

### Expected Behavior

4. Opening the same playlist when using the Local API will allow you to load the full count of videos using the "Load More Videos" option button at the bottom of the list.

![local api](https://github.com/FreeTubeApp/FreeTube/assets/95525436/2696f987-6827-4b9b-a55c-603f4739a49e)

### Issue Labels

content not loading

### FreeTube Version

v0.19.1-nightly-4093 Beta & v0.20.0 Beta

### Operating System Version

Windows 10 22H2

### Installation Method

Portable

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

unknown

### Additional Information

win-x64-portable.exe

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-05 06:59
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2333

**Comment by absidue** [comment] 2024-04-05 06:59
duplicate of #2333

Unfortunately we can't add support for fetching more pages of Invidious videos, until it stops being broken on the Invidious side, they return videos from the previous page when you request later pages, so you have no idea when you've actually reached the end of the playlist, as they'll keep responding with videos, for page numbers that don't exist.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-05 06:59 UTC
Labels: bug, B: content not loading

**Comment by ahaone** [comment] 2024-04-05 10:23
I remember last year Invidious had that problem (loading same videos), but browsing all pages of the same playlist using Firefox and the same Invidious instance as in Freetube, works now. That is why I reported the bug. Because I notice that the feature didn't work in the application.
Cheers!
