### ISSUE TITLE
[Bug]: Local API Errors and invidious only plays legacy formats

### ISSUE THREAD

**Issue by toby63** [FreeTubeApp/FreeTube#5237] opened 2024-06-07 19:33 UTC
### Guidelines

- [] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When I click on a video, the following error is shown: `TypeError: GI.shim.Headers is not a constructor`
Invidious is used instead, but only plays legacy formats (720p).

### Expected Behavior

- Local API should work
- Dash formats should be used

### Issue Labels

content not loading

### FreeTube Version

ac544ec9014d90bc2d570145565d25ed1257e7cf

### Operating System Version

Archlinux

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

-

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-07 20:06
Explain why you list a commit in the FT Version field.

**Comment by absidue** [comment] 2024-06-07 23:28
I can't reproduce it in the official 0.20.0 build, the official latest nightly build or when i use the unmodified FreeTube source code for that commit. Please only report issues here that are actually a problem with FreeTube, there is a reason that the checkbox on whether you can reproduce it on an official FreeTube build is mandatory.

To quote the README:
> Any issues specific with these builds should be sent to their respective maintainer. Make sure u always try an official download before reporting your issue to us!

Closing as this looks a lot like an issue specific to the unofficial AUR build.

**Closed by absidue** 2024-06-07 23:28 UTC
Labels: bug, U: Waiting for Response from Author, B: content not loading, B: Unofficial Download

**Comment by absidue** [comment] 2024-06-08 08:03
@toby63 Downgrading the AUR electron30 package from 30.1.0 to 30.0.9 should fix your problem.

**Comment by toby63** [comment] 2024-06-08 12:12
> @toby63 Downgrading the AUR electron30 package from 30.1.0 to 30.0.9 should fix your problem.

Thx, I will try that.

Regarding other points:
I can understand that you want to limit the possible scenarios, but the reason that I reported this was that:
1. The AUR package simply builds your software, even with your yarn config (IIRC), so there is not much that can go wrong downstream, so an upstream bug is always very likely.
2. I think it is still worth a bug report to know that either a more recent commit or newer versions of dependencies (like here) are causing problems.

I will try to debug more (including other official versions) next time though.

**Comment by absidue** [comment] 2024-06-09 07:50
> Is this a FreeTube problem or an Electron problem

It's an Electron problem, but the reason you are experiencing it with the AUR build but not with the official ones is because the unofficial AUR version always use the latest version of Electron as soon as it gets released, without doing any testing to make sure it actually works, before doing the upgrade.

> The AUR package simply builds your software, even with your yarn config (IIRC), so there is not much that can go wrong downstream, so an upstream bug is always very likely in this case at least. Other packages might have more options, compilations methods etc.

No it doesn't, it modifies the files and also uses different versions of Electron than the official FreeTube release and nightlies, additionally it currently passes custom flags to yarn which can cause it to behave differently and produce a potentially different build.

> I think it is still worth a bug report to know that either a more recent commit or newer versions of dependencies (like here) are causing problems.

In the future please do not open a bug report here unless you can actually reproduce the issue with an official build. We would have discovered the Electron issue while testing the Electron upgrade, which would have saved me wasting my time investigating this when it turns put it's just once again because of the unofficial AUR version upgrading Electron without even testing it first.

Personally I would love to see the unofficial AUR versions taken down, because it's a support nightmare for the FreeTube maintainers and we have to frequently waste our time investigating and then explaining to users, that it's the unofficial AUR build's fault that it is broken, not ours.
