### ISSUE TITLE
[Feature Request]: Please add NewTab option + Custom Keyboard Shortcuts

### ISSUE THREAD

**Issue by kakayzai** [FreeTubeApp/FreeTube#5269] opened 2024-06-16 00:26 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hi, Firstly, I am using this app, FreeTube, and it is working smoothly. Thumbs up for that.
Please add a new tab option, like a browser new tab. Opening a new window breaks the flow of usability.
Please add the option to set custom keyboard shortcut keys.

I previously used a browser extension called Tweaks for YouTube, using which I use my numeric keypad keys to control YouTube videos, play, pause, forward, fullscreen, etc.

I want to also report that the import playlist option is not working. I downloaded the Google YouTube Takeout zip file and imported the subscription file successfully, but the playlist folder contains lots of separate files, and the free YouTube import option does not detect these files.

### Proposed Solution

Hi, Firstly, I am using this app, FreeTube, and it is working smoothly. Thumbs up for that.
Please add a new tab option, like a browser new tab. Opening a new window breaks the flow of usability.
Please add the option to set custom keyboard shortcut keys.

I previously used a browser extension called Tweaks for YouTube, using which I use my numeric keypad keys to control YouTube videos, play, pause, forward, fullscreen, etc.

I want to also report that the import playlist option is not working. I downloaded the Google YouTube Takeout zip file and imported the subscription file successfully, but the playlist folder contains lots of separate files, and the free YouTube import option does not detect these files.

### Alternatives Considered

Hi, Firstly, I am using this app, FreeTube, and it is working smoothly. Thumbs up for that.
Please add a new tab option, like a browser new tab. Opening a new window breaks the flow of usability.
Please add the option to set custom keyboard shortcut keys.

I previously used a browser extension called Tweaks for YouTube, using which I use my numeric keypad keys to control YouTube videos, play, pause, forward, fullscreen, etc.

I want to also report that the import playlist option is not working. I downloaded the Google YouTube Takeout zip file and imported the subscription file successfully, but the playlist folder contains lots of separate files, and the free YouTube import option does not detect these files.

### Issue Labels

ease of use improvement, new feature, new keyboard shortcut

### Additional Information

![Screenshot_2024-06-16_05-25-19](https://github.com/FreeTubeApp/FreeTube/assets/134511733/e1aae286-f16f-4636-a9c2-101ab2f2c0b7)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-16 09:09
Duplicate of #251 #333

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-06-16 09:10 UTC
Labels: enhancement, E: ease of use improvement, E: new feature, E: keyboard shortcut
