### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by UserNameJohnDoe** [FreeTubeApp/FreeTube#1936] opened 2021-12-07 19:12 UTC
Hello! I have a low end laptop. I don't know if it's a bug or not, but my processor is loaded as much as on the official website (60-80%).
I tried to watch 1080p60 fps video on the another app and there the processor load is only 10-30%, the average is around 15-20%.
I have tried toggling "Force Local Backend for Legacy Formats" on and off, changing the "Default video formats" and" Preferred API Backend". But nothing helped. Is it okay that I have such a high cpu usage in FreeTube but not in the other app?
Maybe I can disable vp9? I did not find this option.

**Environment Information (please complete the following information):**
**OS:** Windows
**OS Version:** Windows 10
**FreeTube version:** v0.15.1 Beta
**Installation Method (If applicable):** .exe

**Comment by absidue** [comment] 2021-12-07 20:34
The other app you mention, is that streaming video from YouTube or playing back a local file? If the other app is streaming from YouTube can you please share what said app is?

If you are getting the same bad performance on the official website there is probably not much that can be done on FreeTube's side.

A short term solution is to set FreeTube to use the legacy formats, as those are MP4s, this does however limit you to 720p.

**Comment by UserNameJohnDoe** [comment] 2021-12-07 21:25
It is myTube! I have just noticed that myTube is using more hdd than FreeTube. So, maybe it downloads a part of the video and then plays it. I don't know. But it can play 1080p60fps with 10-15% cpu usage.

**Comment by UserNameJohnDoe** [comment] 2021-12-10 14:13
> The other app you mention, is that streaming video from YouTube or playing back a local file? If the other app is streaming from YouTube can you please share the name of it?
> 
> If you are getting the same bad performance on the official website there is probably not much that can be done on FreeTube's side.
> 
> A short term solution is to set FreeTube to use the legacy formats, as those are MP4s, this does however limit you to 720p.
So I can't reduce the cpu usage except to enable legacy formats?

**Comment by absidue** [comment] 2021-12-10 18:45
Not on your end, FreeTube could probably be changed to add an option to use the none VP9 streams, although it's not my call.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-09 12:36
basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/504

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-01-09 12:36 UTC
Labels: question
