### ISSUE TITLE
[Feature Request]: Forward and Backward function via trackpad swipe like in browsers

### ISSUE THREAD

**Issue by nowakommunikation** [FreeTubeApp/FreeTube#2518] opened 2022-08-30 19:41 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I'd like to go back and forth in the history by a trackpad swipe rather than clicking the arrows in the top left corner.

### Proposed Solution

First off: great program!

I was wondering if it is possible to make the Forward and Backward function "swipe-able" like in browsers, so you don't have to push the mouse up to the arrows in the top left and click them but rather (on a trackpad i. e. on laptops) swipe left or right.

I'm actually not sure if this is possible on all systems or if this is a MacOS feature, but it works (in browsers) with a double-finger-swipe on all browsers I have tested so far on different MacOS versions. 

Or maybe this is already possible and I'm missing some setting?

### Alternatives Considered

Well, the alternative is further clicking on arrows...

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by absidue** [comment] 2022-08-31 14:52
duplicate of #1976

**Closed by absidue** 2022-08-31 14:52 UTC
Labels: enhancement, E: improvement existing feature, E: ease of use improvement
