### ISSUE TITLE
[Bug]: Some Videos Default to Wrong Audio Track (v0.22.0 Beta)

### ISSUE THREAD

**Issue by sewerpig** [FreeTubeApp/FreeTube#6271] opened 2024-12-04 00:58 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Some videos consistently load in the first available audio track. This is almost always the wrong audio track for videos with multiple tracks, and it seems to ignore the track marked as "original". As an example, the following video, for which I've also included a screenshot of the audio tracks panel opened, defaults to German: 

https://youtu.be/gE6PjvcyUMU

I believe this is recent behavior, as it didn't seem to occur in the past even on videos with multiple audio tracks, but I can't speak with full certainty.

I've checked the documentation to little avail, as I presumed I somehow set a setting wrong. 

I've also checked the Issues page, and found this mentioned at least 3 times, but generally marked as solved in 2022 or 2023. Yet this is clearly occurring to me, and I've tested it on two separate devices, one of which I ensured was a fresh install with no pre-existing configs, imported playlists, etc. 

### Expected Behavior

Presumably, Freetube should default to the original audio track. Barring that, it should at least choose based on the Locale Preference.

### Issue Labels

usability issue

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Windows 10

### Installation Method

.apk (Alpine Linux Package)

### Primary API used

Local API

### Additional Information

A screenshot documenting the incorrect behavior
![image](https://github.com/user-attachments/assets/f01e21cb-8a37-4bda-bc5b-56de1dd90053)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-04 04:46
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/6162

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-04 04:46 UTC
Labels: bug, B: usability
