### ISSUE TITLE
[Feature Request]: Automaticaly refresh youtube window when i get this error

### ISSUE THREAD

**Issue by onlineapps-cloud** [FreeTubeApp/FreeTube#6079] opened 2024-11-03 09:17 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hi, when i pause video for long time, and after i want to play it again, i get this error:
![bad status](https://github.com/user-attachments/assets/6efbe33e-320c-4bb2-afcc-0af827cf8301)

### Proposed Solution

can you auto refresh app window to reload video automatically? best regards.

### Alternatives Considered

don't know another solutions.

### Issue Labels

new feature

**Comment by absidue** [comment] 2024-11-03 09:34
Duplicate of #4160

**Closed as completed** 2024-11-03 09:34 UTC
Labels: U: duplicate, enhancement, E: new feature
