### ISSUE TITLE
[Feature Request]: Should be able to open settings while video continues to play in the background

### ISSUE THREAD

**Issue by PAI5REECHO** [FreeTubeApp/FreeTube#2137] opened 2022-03-19 20:54 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When opening the settings the currently playing video is paused

### Proposed Solution

Continue to play video in the background while settings are being changed

### Alternatives Considered

[comment]: <> (asd)

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-03-19 22:41
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1077

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-03-19 22:41 UTC
Labels: enhancement, E: new feature
