### ISSUE TITLE
[Bug]: Videos play the wrong audio track

### ISSUE THREAD

**Issue by Rhettica** [FreeTubeApp/FreeTube#3249] opened 2023-03-03 10:22 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Play a video
2. If the video has alternative audio tracks in other languages, they will play instead of the default audio track the video is set to
3. This means that when i go to watch some videos, the audio starts playing in Spanish instead of English and there is no way to change it that I can see

### Expected Behavior

The videos I watch have English audio tracks by default (which I verified by going to the original video on YouTube) and I expect to hear the video in English or have an option to change the audio track used

### Issue Labels

usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Mac OS Ventura 13.2.1

### Installation Method

.dmg

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-03-03 13:29
duplicate of #2419

**Closed by absidue** 2023-03-03 13:29 UTC
Labels: bug, B: usability
