### ISSUE TITLE
[Feature Request]: Option to disable and/or change keyboard shortcuts.

### ISSUE THREAD

**Issue by aalbrightpdx** [FreeTubeApp/FreeTube#5439] opened 2024-07-21 13:37 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I never use keyboard shortcuts in either youtube or freetube.  I more often have the experience where I don't know that freetube is the highlighted window (multi-monitor) and I'll start typing which makes freetube do all sorts of things that I don't want it to do.  There needs to be an option to disable or change the keyboard bindings/shortcuts.  This is also a must have because disabled uses need to be able to customize the bindings, nothing else makes logical sense.

### Proposed Solution

Option to disable or change keyboard shortcuts.  

### Alternatives Considered

I don't know of an alternative other than looking for a replacement for freetube.

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-21 22:55
Duplicate of #251 #992

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-21 22:55 UTC
Labels: enhancement, E: improvement existing feature
