### ISSUE TITLE
[Bug]: The order of videos in the Favorites playlist has changed

### ISSUE THREAD

**Issue by pkrasicki** [FreeTubeApp/FreeTube#4945] opened 2024-04-13 19:52 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open the Favorites playlist.

Videos are ordered by added date, from oldest to newest. The most recently added videos are difficult to access.

### Expected Behavior

Videos should be ordered by added date, from newest to oldest - just like in previous releases. The most recently added videos should be easy to access.

### Issue Labels

usability issue

### FreeTube Version

v0.20.0

### Operating System Version

Any

### Installation Method

other

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.0

### Additional Information

#4870 would be one way to fix this.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-04-13 20:04
Duplicate of #4870

**Closed** 2024-04-13 20:04 UTC
Labels: bug, B: usability
