### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by loa111** [FreeTubeApp/FreeTube#5240] opened 2024-06-09 07:59 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

YouTube has a great feature: while long pressing the left mouse button on the active video space you will get a temporary playback rate of 2x, till you release the button, then it gets straight back to playback rate of 1x.

### Proposed Solution

I propose that you include the same mouse behavior into the freetube

### Alternatives Considered

None

### Issue Labels

ease of use improvement

**Comment by absidue** [comment] 2024-06-09 08:13
Duplicate of #5064

**Closed** 2024-06-09 08:13 UTC
Labels: enhancement, E: ease of use improvement

**Comment by loa111** [comment] 2024-06-09 08:23
Sorry, but for people asking for an ease of access like myself, with spine injury using both hands and keyboard is hard, mouse usage is preferable, because I asked for the same mouse feature like on the youtube, using keyboard is not an option! Please could you reopen my request.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-09 09:19
Its a closed as a duplicate because the functionality that you describe is the same as the other issue only difference is the mouse button

**Comment by loa111** [comment] 2024-06-09 09:37
Could I remap functionality to the left mouse button inside the config file or in the source code, because keyboard is not an option? Is there a chance that in the current version we got the function on the left mouse button?

**Comment by jasiralavi** [comment] 2025-02-26 05:56
> Could I remap functionality to the left mouse button inside the config file or in the source code, because keyboard is not an option? Is there a chance that in the current version we got the function on the left mouse button?

True, this is not exactly a 'duplicate' of the 'hold spacebar...' issue
We could have this and wait for the other one to be decided - either spacebar or mapped to another key (maybe F for faster?)
