### ISSUE TITLE
[Featurerequest] Play on Chromecast

### ISSUE THREAD

**Issue by kajdo** [FreeTubeApp/FreeTube#1002] opened 2021-01-31 18:09 UTC
Hi,

love the tool ... but really missing the feature to play videos on a chromecast device.

I think there might be a chance of a "low hanging fruit" in terms of enriching the tool with little effort.

thx for your great work

**Comment by GilgusMaximus** [comment] 2021-02-20 19:37
Closing because this is a duplicate of #437 and can also be found in #539

**Closed by GilgusMaximus** 2021-02-20 19:37 UTC
