### ISSUE TITLE
Multiple separate playlists ... linked to multiple profiles ?

### ISSUE THREAD

**Issue by goldanorak** [FreeTubeApp/FreeTube#4301] opened 2023-11-08 09:59 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

As Freetube is now, I can arrange the channels feeds by theme, but not my bookmarks (which Freetube calls "saved videos"). I seemed to me not very intuitive, considering the profiles logic.

### Proposed Solution

It would be very useful if there were multiple "playlists" (in the Freetube sense of the word), linked to the multiple profiles created.

### Alternatives Considered

N/A

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-08 11:56
Multiple playlists are coming https://github.com/FreeTubeApp/FreeTube/pull/4234

But not for multiple profiles that is something that needs to addressed separately 

Duplicate of #1996

**Closed** 2023-11-08 11:56 UTC
Labels: enhancement, E: new feature
