### ISSUE TITLE
[Feature Request]: Make it easier to browse comment timestamps

### ISSUE THREAD

**Issue by Nobylo** [FreeTubeApp/FreeTube#6207] opened 2024-11-21 15:37 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

You're browsing the comment section for timestamped comments. Every time you click one it sends you all the way up to the video player (even with picture in picture enabled.) Now you gotta scroll all the way back down for the next one.

### Proposed Solution

Let the user pop out the entire comment section, viewing it next to the video. (This would have similar functionality to using the PIP miniplayer but would be a lot more functional - you need to scroll all the way back up to see important stuff like your current timestamp if using the miniplayer)

### Alternatives Considered

- Let users disable the automatic scroll-up altogether. That's what the home key on your keyboard is for
- Let users "pin" comments to the top of the comment section. This can stay there even after you leave a la [this idea](https://github.com/FreeTubeApp/FreeTube/issues/783)
- Stop the automatic scroll-up if the PIP miniplayer is in use
- Display timestamped comments on the timeline ([idea marked as unplanned](https://github.com/FreeTubeApp/FreeTube/issues/5388))
- Have a tiny menu next to the video player that displays timestamped comments, styled like youtube's "transcript" menu
- Add functionality to pop out individual comments. This would work well if there's one comment with all the timestamps

### Issue Labels

ease of use improvement

### Additional Information

Some of these are easy, some of these are hard, please do one of them. I've seen that a lot of people want this functionality in one way or another, it would be a big leap in smoothing out the UX. I think this counts as containing more than one feature request but it did ask me to provide alternatives, sorry. If you ask me to I'll split the ones that didn't already exist into new feature requests

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-06 22:15
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3471

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-06 22:15 UTC
Labels: enhancement, E: ease of use improvement, E: new feature
