### ISSUE TITLE
Video speed UI

### ISSUE THREAD

**Issue by maplepy** [FreeTubeApp/FreeTube#1371] opened 2021-05-30 10:16 UTC
**Behavior of the program**
The speed of the video can't be choosen, when opening the ui for the speed, clicking goes right through the ui and simply pause/resume the video

**Expected behavior**
Video speed is changed

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Choose a video
2. Change the speed or at least try to

**Environment Information (please complete the following information):**
 - OS: Manjaro 
 - OS Version: 5.10.36-2-MANJARO 
 - FreeTube version: v0.13.1 Beta
 - Installation Method (If applicable): AUR
 - Primary API Used: Local

**Additional context**
Bug is inconsistent, speed ui sometimes work, sometimes not and I'll have to manually reload the page to make it work again

**Comment by ClemGlacee** [comment] 2021-05-30 10:17
Appeared since this version

**Comment by ClemGlacee** [comment] 2021-11-09 21:57
Yeah sometimes it still happens, but I haven't figured how it appears yet

**Comment by ClemGlacee** [comment] 2021-11-09 21:58
I'm now on Endeavour OS
DE: Plasma 5.23.2
Kernel: 5.14.16-arch1-1

**Comment by ClemGlacee** [comment] 2021-11-09 21:59
Clicking on the speed to increment it works fine
Choosing the specific speed doesn't always work, it goes through the ui and just pause the video

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-11-10 06:16
Very weird case indeed. i tried to reproduce it multiple times but im still unable to do that

**Comment by ClemGlacee** [comment] 2021-11-10 08:23
I’ll try to see if I can pinpoint this issue and get back to you :)

**Comment by maplepy** [comment] 2022-05-16 16:33
I'm not sure if I still do, I just use the `O` and `P` keybinds now since it was more reliable than the UI so I can't really tell since my "workflow" is done with keyboard mainly now

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-05-16 16:38
Ah okay. If u think this does not apply anymore or u dont know because u have changed your workflow, feel free to close the issue.

**Comment by maplepy** [comment] 2022-05-16 16:57
I can try to see if it's still present in the new build and will give an update

**Closed** 2022-07-13 00:00 UTC
Labels: bug, U: Waiting for Response from Author
