### ISSUE TITLE
[Bug]: freetube stopped working entirely

### ISSUE THREAD

**Issue by justsomehumanbeing** [FreeTubeApp/FreeTube#2172] opened 2022-04-08 10:02 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

When trying to open freetube via the bash shell I get the following output:
```
[86245:0408/114656.707762:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/unique_ptr.h:659: typename std::add_lvalue_reference<element_type>::type std::unique_ptr<blink::CSSSelector []>::operator[](std::size_t) const [_Tp = blink::CSSSelector [], _Dp = std::default_delete<blink::CSSSelector []>]: Assertion 'get() != pointer()' failed.
```
Besides that nothing happens.

This behavior started a few days ago after a system update.

### Expected Behavior

I expect freetube to open normally as it did before.

### Issue Labels

causes crash

### FreeTube Version

v0.16.0

### Operating System Version

OS: EndeavourOS Linux x86_64  Kernel: 5.17.1-arch1-1 

### Additional Information

Looking in htop I find:

```
100828 nutzer      20   0 21.3G  215M  125M S  0.0  2.8  0:01.15 │  │  └─ /usr/lib/electron/electron --enable-crashpad /usr/lib/freetube/app.asar
 100832 nutzer      20   0 21.3G  215M  125M S  0.0  2.8  0:00.00 │  │     ├─ /usr/lib/electron/electron --enable-crashpad /usr/lib/freetube/app.asar
 100834 nutzer      20   0 16.8G 93264 81360 S  0.0  1.2  0:00.06 │  │     ├─ /usr/lib/electron/electron --type=zygote --no-zygote-sandbox --enable-crashpad --enable-crashpad
 100881 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.13 │  │     │  └─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/hom
 100883 nutzer      39  19 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100884 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100885 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100886 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100887 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100888 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100889 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100890 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100892 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100893 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100894 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100895 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100897 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100898 nutzer      39  19 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100899 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100900 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100901 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100902 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100903 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     ├─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
 100904 nutzer      20   0 17.1G  106M 86136 S  0.0  1.4  0:00.00 │  │     │     └─ /usr/lib/electron/electron --type=gpu-process --enable-crashpad --enable-crash-reporter=847d4fa8-f59a-4d50-96e2-674f5d2f1518,no_channel --user-data-dir=/
```

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Connor-GH** [comment] 2022-04-09 06:23
https://aur.archlinux.org/packages/freetube

**Comment by PrestonN** [comment] 2022-04-09 17:40
Duplicate of [#2163]

**Closed by PrestonN** 2022-04-09 17:40 UTC
Labels: bug, third-party, electron being electron, B: crash
