### ISSUE TITLE
Subscribed Channels - New Container / Panel needed

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1962] opened 2021-12-20 23:24 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
At present, the subscribed channels are laid directly one by one after the "About".
This needs to be **refined into a single container or panel tab similar to "History", "Playlists" and Subscriptions, other panels**.

**Describe the solution you'd like to see implemented**
In practice, the **channels need to be under one panel to explore easily**. As it will be a headache once there are 100's of channels subscribed.

**Screenshots**
![FreeTube_T0gkwuICqJ](https://user-images.githubusercontent.com/96393348/146845420-ea32c55b-2820-42cc-803c-820ab4dc9b41.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-12-21 17:02
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1506

**Closed** 2021-12-21 17:02 UTC
Labels: U: duplicate, enhancement
