### ISSUE TITLE
[Feature Request]: Implement tabs to FreeTube

### ISSUE THREAD

**Issue by Sandyran** [FreeTubeApp/FreeTube#3106] opened 2023-01-22 17:18 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When I use YouTube, I tend watch multiple videos at once. I do this, by having multiple tabs open in my browser, like on the picture below.

![bilde](https://user-images.githubusercontent.com/31732894/213929955-6d6133f8-06c5-45cc-9333-8f20b1ff155e.png)

Currently, the only way to watch multiple videos at once with FreeTube, is to have multiple windows open. This can be done by clicking on a link with the mouse wheel. Still, it is harder to keep track of multiple windows, than multiple tabs. Implementing such a feature in FreeTube, would make it easier for someone to watch multiple videos in FreeTube at once.

![FreeTube, multiple windows](https://user-images.githubusercontent.com/31732894/213928142-4c5a40bd-6891-46a6-9b41-5f14f2d1bd3f.PNG)

### Proposed Solution

Add the ability to have multiple tabs open in FreeTube, like on the picture below.

![FreeTube, multiple tabs](https://user-images.githubusercontent.com/31732894/213927984-926c0712-efb0-4220-b04c-35baee0d502a.PNG)

This feature could be added by adding a "open link in new tab" feature, like on the picture below. Clicking on this, would open the video in a new tab.

![right click menu](https://user-images.githubusercontent.com/31732894/213928692-439159c9-ea53-4607-8d58-10fe07e70834.png)

### Alternatives Considered

Continue using FreeTube, by having two or more windows open at the same time.

### Issue Labels

new feature

**Comment by absidue** [comment] 2023-01-22 17:46
duplicate of #333

**Closed by absidue** 2023-01-22 17:46 UTC
Labels: enhancement, E: new feature
