### ISSUE TITLE
[Feature Request]: Keep Volume and "media formats" when selecting a new video or opening a new window

### ISSUE THREAD

**Issue by skacon** [FreeTubeApp/FreeTube#6013] opened 2024-10-29 15:00 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

when I select a new item from "Up Next" list, the selection from "Change Media Formats" resets from "Use audio formats" to default (playing video and audio). I have to select audio-only again. It also happens, if a "go back" to a stream.

When I start an item in a new window via third-mouse-button-click, both the media format and volume resets to default. Volume is 100%, media format plays video and audio.

### Proposed Solution

In both situations a) new window and b) new item played  the current settings of volume and media format playback should remain the same, 

a) if the current window has volume set to 45%, the new window should use a volume level of 45%.

b) if the current item is played with audio-only, the next item should be played audio-only as well, regardless if in the same or a new window.

### Alternatives Considered

Actually I cannot consider an alternative. Maybe: that these features can be enable via two optional settings.

### Issue Labels

ease of use improvement, new optional setting

**Comment by kommunarr** [comment] 2024-10-29 17:15
Duplicate of #2295 (note it may temporarily be showing as unavailable due to an issue with GH that are trying to get resolved)

**Closed** 2024-10-29 17:16 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement
