### ISSUE TITLE
[Feature Request]: Show all the profiles a channel belongs to at once

### ISSUE THREAD

**Issue by vucefalas** [FreeTubeApp/FreeTube#2213] opened 2022-04-21 18:07 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I have many subscriptions, so I avoid using All Channels because it gets crowded.

However, if I have a subscribed channel that has not been added to any "custom" profile, I will miss it.

To solve this, it would be useful to have a way to easily check which subscribed channels have *not* been added to any "custom" profile.

### Proposed Solution

In the Edit Profile page, add a small colored dot below each channel, for each custom profile where the channel has been added to (and showing the name of the profile on hover).

The colored dots could also be added in the main page of a channel.

### Alternatives Considered

None.

### Issue Labels

display more information to user

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-06-02 12:47
I think that #1934 solves this

**Comment by jasonhenriquez** [comment] 2023-11-20 14:43
Possible fix for this use case: as @efb4f5ff-1298-471a-8973-3d47447115dc said, the Channels tab on the side nav for the All Channels profile allows for seeing this one channel at a time.

We can keep this issue open if an "Uncategorized" Channel Filter option on the Profile Edit page is what's wanted.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-20 21:53
@jasonhenriquez isnt this a dupe of https://github.com/FreeTubeApp/FreeTube/issues/914

**Comment by jasonhenriquez** [comment] 2023-11-23 23:18
Duplicate of #914

**Closed by jasonhenriquez** 2023-11-23 23:18 UTC
Labels: enhancement, E: display more information
