### ISSUE TITLE
Open with PotPlayer error

### ISSUE THREAD

**Issue by barongi** [FreeTubeApp/FreeTube#5281] opened 2024-06-17 12:49 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I choose a video and choose "Open in PotPlayer" but get a window that says something about potplayermini64.

### Expected Behavior

I expect PotPlayer to open and play the video.

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

0.20.0 Beta

### Operating System Version

Windows 11 Home 23H2

### Installation Method

.exe

### Primary API used

Invidious API

### Additional Information

I have been using PotPlayer for years and it's common knowledge that the 64-bit version does not work as well as the 32-bit version. Therefore I never ever install the 64-bit version. I think FreeTube assumes everyone installs the 64-bit version, which is incorrect. Therefore FreeTube should be looking for potplayermini.exe instead of potplayermini64.exe, or both.

![Screenshot-1](https://github.com/FreeTubeApp/FreeTube/assets/60045663/2cf1bd2b-a1a6-408b-9d3d-e18659e10a00)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by barongi** [comment] 2024-06-17 12:56
Adding C:\Program Files (x86)\DAUM\PotPlayer\PotPlayerMini.exe to PATH fixes this problem.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-17 18:27
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5215

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-06-17 18:27 UTC
Labels: bug, B: content not loading, B: feature stopped working

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2025-08-06 13:46
inquires regarding external players migrated to https://github.com/FreeTubeApp/FreeTube/discussions/7789
