### ISSUE TITLE
[Feature Request]: Allow the user to create custom playlists for pinning videos

### ISSUE THREAD

**Issue by collector-ynh** [FreeTubeApp/FreeTube#3178] opened 2023-02-09 18:56 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Freetube offers to classify videos in a playlist to find them quickly afterwards. But there is only one playlist for all videos, which is problematic if you want to sort your videos into appropriate playlists!

It is not possible for the moment to automatically play several videos in a row in the playlist, although this is a very important function on linux 

### Proposed Solution

Allow the user to create their own video playlist, with the ability to automatically play all videos in a playlist, without manually switching between videos.

### Alternatives Considered

For the moment I only use the only playlist on Freetube, and I manually switch them from one video to another!

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-02-09 19:29
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/547

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-02-09 19:29 UTC
Labels: enhancement, E: new feature
