### ISSUE TITLE
[Bug]: FreeTube crashes upon entering fullscreen (Wayland)

### ISSUE THREAD

**Issue by Mnky313** [FreeTubeApp/FreeTube#5334] opened 2024-06-24 18:00 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open a video
2. Enter Fullscreen
3. FreeTube crashes

### Expected Behavior

Video plays in fullscreen

### Issue Labels

causes crash

### FreeTube Version

v0.21.0

### Operating System Version

Arch Linux (Hyprland)

### Installation Method

Flathub

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

v0.20.0

### Additional Information

Doesn't crash in Xwayland, only when running in native wayland (--ozone-platform-hint=wayland)

Tried the freetube-bin package from the AUR, same result.

v0.20.0 works as expected.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by kommunarr** [comment] 2024-06-24 18:11
Duplicate of #5304

**Closed by kommunarr** 2024-06-24 18:11 UTC
Labels: bug, B: crash
