### ISSUE TITLE
[Feature Request]: Toggle hide/unhide Watched Video

### ISSUE THREAD

**Issue by lamborghinipth** [FreeTubeApp/FreeTube#5320] opened 2024-06-24 04:28 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Beside the feature request Only Show Latest x Videos for Each Channel - https://github.com/FreeTubeApp/FreeTube/issues/5265#issue-2352167189, I think my feature request is also neccessary.

I have many subscribed channels. Of course I always want to watch new videos. But sometimes, I would like to watch WATCHED videos again, especially knowledge videos.

Remove Watched function in configuration/ settings is not convenient in my opinion. A toggle button to hide/ unhide is better.

### Proposed Solution

A button on topbar is solution

![300](https://i.imgur.com/AcChC9M.jpeg)

When we click on the button, it will hide all Watched Videos on the screen/ page of Homepage/ Channel page/ Playlist page ... whatever.

When we click again, it will display (unhide) all videos as it is now.

### Alternatives Considered

None

### Issue Labels

improvement to existing feature, new feature, new optional setting

### Additional Information

We can merge to Remove Watched Videos or not. 
In my opinion, they should be separated.

Remove: when we do not need anymore
Hide: just dont want to see temporarily at the moment

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-24 09:56
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4999

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-06-24 09:56 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: new feature
