### ISSUE TITLE
Ability to sort subscritions into folders

### ISSUE THREAD

**Issue by JonnyCodewalker** [FreeTubeApp/FreeTube#86] opened 2018-05-04 13:13 UTC
It would be nice to have the ability to sort channels you subscribed to into folders. And to then have the capability to only show the new videos from that folder.

**Comment by aproposnix** [comment] 2018-05-08 09:38
I think this is related to both #1 and #17

**Comment by JonnyCodewalker** [comment] 2018-05-08 09:40
It is somewhat related, but not the same. What i want is to be able to bundle multiple subscriptions into one folder. So that for example i can have one folder for TechVideos, containing all the different youtubers that make videos in that category, and one for Lets Plays etc.

**Comment by aproposnix** [comment] 2018-05-10 03:56
Aha. So you want to create groups for your subscriptions (like an RSS reader). Sorry I misunderstood.

**Comment by PrestonN** [comment] 2018-05-10 22:34
This looks more like a duplicate of #8 but you described it a little better than over there so I don't think I'll close this.

This is something I'd be interested in doing in the future.  This will probably be an "after stable" feature though as there are other things that I'd like to prioritize first.  I will add this to the [project page](https://github.com/FreeTubeApp/FreeTube/projects/1) so that you can keep track of it though.

**Comment by PrestonN** [comment] 2019-08-08 19:39
This has been implemented and will be included in the next release.  I am currently within a testing phase of the app and will release when I feel comfortable to.  Expect it in the next week or so.

**Closed by PrestonN** 2019-08-08 19:39 UTC
