### ISSUE TITLE
[Feature Request]: Custom Font Option in FreeTube  Dear FreeTube Team

### ISSUE THREAD

**Issue by Erick12890** [FreeTubeApp/FreeTube#5766] opened 2024-09-29 22:01 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I hope this message finds you well. I would like to suggest a feature that could improve the user experience in FreeTube. It would be fantastic to have the option to change the default font to a custom one, allowing users to select and apply their preferred fonts within the program.

The current font feels quite large and lacks visual appeal for my personal taste, so the ability to customize the font would greatly enhance the program’s appearance and offer a more personalized experience.

Thank you for considering this request, and I appreciate all the great work your team has done so far

### Proposed Solution

I hope this message finds you well. I would like to suggest a feature that could improve the user experience in FreeTube. It would be fantastic to have the option to change the default font to a custom one, allowing users to select and apply their preferred fonts within the program.

The current font feels quite large and lacks visual appeal for my personal taste, so the ability to customize the font would greatly enhance the program’s appearance and offer a more personalized experience.

Thank you for considering this request, and I appreciate all the great work your team has done so far

### Alternatives Considered

I hope this message finds you well. I would like to suggest a feature that could improve the user experience in FreeTube. It would be fantastic to have the option to change the default font to a custom one, allowing users to select and apply their preferred fonts within the program.

The current font feels quite large and lacks visual appeal for my personal taste, so the ability to customize the font would greatly enhance the program’s appearance and offer a more personalized experience.

Thank you for considering this request, and I appreciate all the great work your team has done so far

### Issue Labels

ease of use improvement

### Additional Information

I hope this message finds you well. I would like to suggest a feature that could improve the user experience in FreeTube. It would be fantastic to have the option to change the default font to a custom one, allowing users to select and apply their preferred fonts within the program.

The current font feels quite large and lacks visual appeal for my personal taste, so the ability to customize the font would greatly enhance the program’s appearance and offer a more personalized experience.

Thank you for considering this request, and I appreciate all the great work your team has done so far

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-29 22:06
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/39

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-29 22:06 UTC
Labels: enhancement, E: ease of use improvement

**Comment by Erick12890** [comment] 2024-09-29 22:20
I hope you are well. I noticed that my recent feature suggestion regarding custom font integration was rejected, and I wanted to follow up on this. I believe that allowing users to personalize the font in FreeTube, particularly by uploading custom .ttf files, could significantly enhance the program's visual appeal and customization options for a wider user base.

While I understand that not all suggestions may fit within your development roadmap, I encourage a more democratic approach when considering community feedback. Features that allow users to tailor their experience often lead to more engagement and satisfaction, ultimately enriching the program for everyone.

If it is not possible to include this feature at the moment, could you please clarify how we can properly suggest and request new features in a way that aligns with FreeTube’s development process? I would appreciate any guidance you can provide to ensure that future suggestions are considered more thoroughly.

Thank you for your time and for the work your team does to make FreeTube great.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-29 22:26
> I noticed that my recent feature suggestion regarding custom font integration was rejected

Your assumption is incorrect.

> I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.

You have checked this box which means there arent any open/closed issues that are similar to your request. I searched myself and did find that there was already a request for it so therefore i closed this one a duplicate. The duplicate i linked to is an **open** issue.
