### ISSUE TITLE
[Feature Request]: Subscribe to individual playlists/podcasts

### ISSUE THREAD

**Issue by MintMain21** [FreeTubeApp/FreeTube#4546] opened 2024-01-15 00:33 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Some channels I only want to follow for specific topics that are typically organized into playlists. Other channels have dedicated podcasts that are recognized as such by the app when browsing their channel page. 

Individual playlists have dedicated RSS feeds that update with changes to the playlist. As a result, I can keep up to date with specific playlists by subscribing via RSS, but not necessarily by subscribing via FreeTube, as it only supports subscribing to entire channels at once. 

### Proposed Solution

Either via RSS or internal mechanisms, support the option to subscribe to playlists and channels as if they were channels and channel RSS feeds. For example, allow me the option to subscribe to the "Game Grumps Legend Of Zelda" playlist rather than the Game Grumps channel itself.

### Alternatives Considered

As I mentioned before, I can create the functionality I desire in any RSS reader and open those links in Freetube. Furthermore I can use dedicated podcast apps to keep up with podcasts. I just see no reason why these features can't be built into FreeTube itself.

### Issue Labels

improvement to existing feature

### Additional Information

Alternative Category Choice: Ease Of Use Improvement.

**Comment by jasonhenriquez** [comment] 2024-01-15 04:18
Duplicate of #312

**Closed by jasonhenriquez** 2024-01-15 04:18 UTC
Labels: enhancement, E: improvement existing feature
