### ISSUE TITLE
[Feature Request]: Add option to move comment section to side when not in full screen

### ISSUE THREAD

**Issue by gummyhulk** [FreeTubeApp/FreeTube#6098] opened 2024-11-04 20:11 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Add an option to move the comment section to the side of the video so you can watch it and scroll through comments simultaneously. I know a YouTube customisation extension has this alternative.

### Proposed Solution

See above. Add the option in settings so users can turn it on / off.

### Alternatives Considered

No alternatives as far as I'm concerned.

### Issue Labels

new optional setting, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-11-04 21:04
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3471

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-11-04 21:05 UTC
Labels: enhancement, E: new optional setting, E: visual improvement
