### ISSUE TITLE
Please tag most recent release with 'latest' tag

### ISSUE THREAD

**Issue by crishaddad** [FreeTubeApp/FreeTube#1665] opened 2021-09-07 11:01 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**

As per title, please tag the latest release; this would enable advanced users to use local scripts to automatically keep our versions of FreeTube up-to-date.

**Describe the solution you'd like to see implemented**

Tag most recent release with 'latest' tag.

**Comment by absidue** [comment] 2021-09-09 09:31
@crishaddad If you are trying to download the latest artifacts I recommend using the GitHub API, even if the latest release is tagged with `latest` you are still going to have an issue downloading the artifacts because they have version numbers in the names, you don't have that issue when using the API. The API returns JSON which can be parsed in different ways depending on what language your script is written in. For shell scripts you can use `jq`, which is in the default repos for most Linux distros, on macOS you can install `jq` from brew, on Windows, PowerShell will automatically parse JSON when using the `Invoke-RestMethod` command and all other languages have builtin JSON parsing capabilities or libraries that make it easy to do.

Here is an example of how you can get the url to the latest amd64 deb in bash with jq:

```bash
curl -s https://api.github.com/repos/FreeTubeApp/FreeTube/releases | jq -r '.[0].assets[] | select(.name | endswith("amd64.deb")) | .browser_download_url'
```

**Comment by crishaddad** [comment] 2021-09-09 11:09
Hi absidue; thanks for the helpful reply. 

Yes I was already planning to use the Guthub API with curl/jq to get the correct download URI. But getting the result at position zero is not direct parity with having a 'latest' tag.

While you may provide a decent workaround, IMHO there is still value in adding a "latest" tag, since this allows for developers to point the 'latest' tag at an arbitrary release number. It can be pointed at whatever is considered to be the canonical current, best-working version. This canonical version might not necessarily be the release at position zero. For example it may be desirable to quickly roll back the 'latest' tag to an earlier release, in the event of a show-stopping problem with the most recent release. Using your workaround does not allow this, since it just pulls the release at position 0.

Your way also means pulling the entire 'releases' json tree, and filtering it locally - instead of just getting the json data for 'latest'. A relatively minor issue - but suboptimal, nonetheless! :)

**Comment by absidue** [comment] 2021-09-09 11:38
Hi @crishaddad I hadn't thought about the usecase of rolling back to a previous version, although if there were a release with major issues, I would assume that it would be deleted and once the issue is fixed a new release with a new version number and tag would be created.

My reasoning for not using the latest endpoint is that if a repository has releases that aren't marked as pre-releases, latest will always refer to the latest non-prerelease, even if there are newer pre-releases. For FreeTube the endpoint returns an error as there are no non pre-release releases.

**Comment by crishaddad** [comment] 2021-09-09 12:15
FWIW @absidue I have implemented [a variation of] your snippet. It simply hadn't occurred to me to get 'release 0', since I'm generally used to working with more precision. But, all I'm actually doing here is installing Freetube on a few personal machines, so: yes this is "good enough" TBF.

However, I, personally, would still like to see a 'latest' tag, ideally. I will leave the request open for devs to decide if they want to implement or close, etc.

**Closed** 2022-12-09 13:52 UTC
Labels: enhancement

**Comment by dinotheextinct** [comment] 2024-07-27 08:57
Same issue affecting: https://mijorus.it/posts/gearlever/update-url-info/
https://github.com/mijorus/gearlever/issues/113

**Comment by absidue** [comment] 2024-07-27 09:03
@dinotheextinct As mentioned above you need to use the GitHub API and select the first item in the releases array. That's the same way that FreeTube itself checks for updates.

**Comment by dinotheextinct** [comment] 2024-07-27 13:40
gear lever is an app to update appimages. it needs an url to check for updates, but because all releases are labeled as pre release it doesn't catch upon it, I linked the issue at gear level in my previous post.

**Comment by absidue** [comment] 2024-07-27 14:06
That's because they are all pre-releases, hence the `beta` in the version text. You'll have to ask the developer of that program to use the GitHub API instead.
