### ISSUE TITLE
[Feature Request]: Hide shorts

### ISSUE THREAD

**Issue by d35r0n** [FreeTubeApp/FreeTube#2571] opened 2022-09-12 13:51 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

If possible, please add an option to hide shorts videos in the Distraction Free Settings.

Short form media is making people zombies and I do not want to be one. I hate it when I open a video thinking it might be an interesting watch only to find out that it is a shorts video.

If removing the shorts videos isn't possible, can you add an indication for a video being a shorts video so I can avoid it?

### Proposed Solution

YouTube generally defines a shorts video having these features:

- Shorter than 60 Seconds
- Vertically Videos
- Might or might not contain #shorts

I think looking for these points in videos might help stop the shorts videos.

There is one possible issue though. Checking for those three checks requires video information which might not work if someone is using RSS to get the videos.

### Alternatives Considered

I cannot think of an alternative other than pretty much dropping this issue and going back to opening videos and checking manually if it is a shorts or not.

### Issue Labels

ease of use improvement, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-09-12 15:03
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2008

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-09-12 15:03 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement

**Comment by Flashwalker** [comment] 2023-03-13 18:24
Shorts must be skipped!
