### ISSUE TITLE
[Feature Request]: Add option in a subscribed channel to play all videos in a playlist

### ISSUE THREAD

**Issue by gituser823** [FreeTubeApp/FreeTube#5574] opened 2024-08-15 17:43 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

1. Click on one of the subscribed channels in the left menu.
2. There is no option to just play all videos from the channel, I can only click single videos, which will then play.

### Proposed Solution

Add an option in the chanell overview to just play all available videos (in a playlist).

Also would be great if you added an option to add one chosen video + all following videos to a playlist and just play it.
Like start playing all videos, starting with the chosen video.

### Alternatives Considered

-

### Issue Labels

ease of use improvement

**Comment by absidue** [comment] 2024-08-15 17:50
Duplicate of #629

**Closed by absidue** 2024-08-15 17:50 UTC
Labels: enhancement, E: ease of use improvement
