### ISSUE TITLE
[Bug]: App crash and non-responsive when internet cut

### ISSUE THREAD

**Issue by onegladiator4u** [FreeTubeApp/FreeTube#6076] opened 2024-11-02 16:11 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Start watching a video 
2. Disconnect internet (couldn't recreate issue by disabling network adapter )
3. after the loaded video finishes in the timeline, app will be non-responsive after some time when internet reconnects.

### Expected Behavior

Should stop and buffer and show message that your device is offline

### Issue Labels

causes crash

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Windows 10 pro 22H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

Turning off router and modem and turn on both after some time. when internet reconnects it'll be non responsive.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-11-02 19:10
Duplicate of #6028

**Closed** 2024-11-02 19:10 UTC
Labels: bug, B: crash
