### ISSUE TITLE
[Bug]: Subtitles changing size inconsistently

### ISSUE THREAD

**Issue by legwelfexiste** [FreeTubeApp/FreeTube#5300] opened 2024-06-20 23:59 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Enable subtitles on a video
2. Hover the mouse over the video and then move the mouse away
Doing this results in the subtitles becoming slightly bigger than their assigned size.

### Expected Behavior

Subtitles should not change size when doing this.

### Issue Labels

accessibility issue, inconsistent behavior, usability issue, visual bug

### FreeTube Version

v0.21.0

### Operating System Version

Windows 10 Home version 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-24 12:50
considering this as a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3920

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-06-24 12:50 UTC
Labels: bug, B: visual, B: accessibility, B: usability, B: inconsistent behavior
