### ISSUE TITLE
[Feature Request]: Options to translate subtitles and auto generated subtitles

### ISSUE THREAD

**Issue by Q32** [FreeTubeApp/FreeTube#5060] opened 2024-05-03 22:08 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Add the option to translate subtitles and auto generated subtitles from any language to any other languages.
My language is spanish and default subtitle translation for any language videos is limited to "translated from english".

### Proposed Solution

Add the option to translate subtitles and auto generated subtitles from any language to any other languages.
My language is spanish and default subtitle translation for any language videos is limited to "translated from english".
Improving the subtitle settings configuration.

### Alternatives Considered

N/A

### Issue Labels

improvement to existing feature

**Comment by SteveJackson490** [comment] 2024-05-05 07:35
Duplicate of #4632 see https://github.com/FreeTubeApp/FreeTube/issues/4632#issuecomment-1926377750 for the solution

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-05 09:04
Good catch @DontBlameMe99 

Duplicate of #4632

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-05-05 09:04 UTC
Labels: enhancement, E: improvement existing feature
