### ISSUE TITLE
Search comments and description

### ISSUE THREAD

**Issue by m3thm4th** [FreeTubeApp/FreeTube#5020] opened 2024-04-25 19:09 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Add a search box for text in comments and description

### Proposed Solution

.

### Alternatives Considered

.

### Issue Labels

ease of use improvement

**Comment by jasonhenriquez** [comment] 2024-04-25 19:27
Please follow the issue template or we will close your issues by default going forward. Please also search if the issue has already been proposed before making one. Duplicate of #1401.

**Closed as completed by jasonhenriquez** 2024-04-25 19:27 UTC
Labels: U: duplicate, enhancement, E: ease of use improvement
