### ISSUE TITLE
 Weird search results as start page - analytics?

### ISSUE THREAD

**Issue by mlario** [FreeTubeApp/FreeTube#955] opened 2021-01-18 20:46 UTC
**Behavior of the program**

When freetube is started it loads some weird search results as a start up page. Those videos have no connection to the subscription list and were not searched before. They are on the topics of VPN providers and types of proxy connections

Since I connect freetube through proxy, very sound question is whether freetube is utilizing some built-in analytics to fetch these suggested search results? 

Or is it a problem on the electron side/chromium side used as a basis of freetube that contains some analytics?

I tried removing freetube, removing all directories (e.g. in ~/.config/Freetube etc) and installing freetube again. Same behaviour observed after reinstall.

Also I do not store search history

**Expected behavior**

When freetube is launched it should load subscriptions as a start up page

As a privacy friendly application, it is expected to be free from analytics. 

**Environment Information (please complete the following information):**
 - OS: Linux
 - OS Version: fedora 31
 - FreeTube version: v0.11.0 Beta
 - Installation Method (If applicable): built from source
 - Primary API Used: both on Local API and Invidious API

**Comment by GilgusMaximus** [comment] 2021-01-26 16:03
That is weird. FreeTube does not fetch any analytics. Usually people report that their subscriptions are just empty and then reload the page and it works fine. Could you add a screenshot of such videos so I get a better understanding of what exactly is loaded

**Comment by SubtleNudge** [comment] 2021-01-29 23:42
I came here to report the same issue. I just updated FreeTube to v0.11.2 Beta (AUR package) and when I start the program, it displays some unrelated search results.

This is how it looks right after starting it:

![freetube](https://user-images.githubusercontent.com/74121303/106337764-f4adbb00-6289-11eb-8fb4-2077ef9ee93b.png)

As you can see, the content of these videos are all related to FreeTube itself, as if someone searched for the term "FreeTube". In fact, I tested it by searching for the term "FreeTube" myself and it displays the exact same results.

Closing and opening the program will load the same search result page every time, no matter what I searched for myself.

Also, I don't think I ever searched for the term "FreeTube" within FreeTube myself before this issue appeared, so I don't think it's something out of my search history.

**Comment by SicroAtGit** [comment] 2021-01-31 22:14
I had the same problem that when I started the program, the search page was always displayed instead of the video list of my subscribed channels.

I think this problem occurred only since the update from the previous version to the version v0.11.2 Beta.

@mlario

You stated that you built and installed FreeTube from source. Have you also tried the `.rpm` packages from the FreeTube website?

@SubtleNudge

This is the AUR package I used:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freetube

Now I switched to this AUR package and the problem has disappeared:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freetube-bin
On the FreeTube website this AUR package is listed, so I think this is the official AUR package.

---

- OS: Linux
- OS Version: Manjaro (an Arch-based distribution)
- FreeTube version: v0.11.2 Beta
- Installation Method (If applicable): AUR package, built from source
- Primary API Used: Local API

**Comment by mlario** [comment] 2021-02-13 22:01
> That is weird. FreeTube does not fetch any analytics. Usually people report that their subscriptions are just empty and then reload the page and it works fine. Could you add a screenshot of such videos so I get a better understanding of what exactly is loaded?

OK, sorry for late response. Here is screenshot. It appears only when I launch freetube with proxy server option in command:
/opt/FreeTube/freetube --proxy-server="socks5://proxy_server:proxy_port"

![Screenshot](https://user-images.githubusercontent.com/73748784/107862743-b518ce80-6e46-11eb-8a49-1f4beb884354.png)

**Comment by PrestonN** [comment] 2021-03-01 01:11
This should be fixed with #1073. The problem is that certain builds were sending CLI parameters to the app and FreeTube tried to handle them as if they were a YouTube URL. By default, if it doesn't find a URL, it would search that item instead. The PR removes the ability to search via the CLI which should fix this.

**Closed by PrestonN** 2021-03-01 01:11 UTC
Labels: bug
