### ISSUE TITLE
[Feature Request]: Download progress - a way of viewing all downloads with progres bars (similar to the way it can be checked in browsers such as Firefox or Chromium)

### ISSUE THREAD

**Issue by filolog2** [FreeTubeApp/FreeTube#6155] opened 2024-11-12 22:02 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When downloading an audio or video file (on Ubuntu version), there is a small pop-up message saying that download started. However, the download usually takes a good few minutes, and when downloading multiple audio files it takes even longer and it seems not possible to see progress of each download. I need to wait until files appear on my Desktop to be sure that they were downloaded and I can close the application. 

### Proposed Solution

It would be useful to have a 'Downloads' option with progress bars per each download process, similar to the way it is in browsers such as Firefox or Chromium. 
![Screenshot](https://github.com/user-attachments/assets/db78fb25-dde5-462e-9219-a6ea05edaccd)

### Alternatives Considered

no alternative

### Issue Labels

new feature

**Comment by absidue** [comment] 2024-11-13 05:30
Duplicate of #1772

**Closed** 2024-11-13 05:30 UTC
Labels: enhancement, E: new feature
