### ISSUE TITLE
Channel Blocker / Hider / Filter

### ISSUE THREAD

**Issue by NamesNetworkNic** [FreeTubeApp/FreeTube#1577] opened 2021-08-11 09:26 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
A button or option to hide videos from (a) Youtube channel(s) that upload content you dislike or are uncomfortable seeing.

**Describe the solution you'd like to see implemented**
If the button is pressed or option is selected, a specified channel will be added to a blocklist.

All videos from channels on that list will be removed from trending and suggested videos _(or is it 'up next'?)_.

Additionally:

1. It may also be a good idea to have a 'show/hide hidden videos' option at the end of the suggested videos list, when some results are hidden.

2. Not to go too far, but it also may be worth considering having an option for different blocklists depending on your profile (ie 'hide these political news stations while I'm on 'Shows', but keep them while I'm on 'News'').

**Describe alternatives you've considered**
As a possibly quicker solution, you could remove the thumbnail of any videos from a channel on the blocklist and replace their titles with 'Video Hidden' or similar.

xo
Lovejoy

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-08-11 09:32
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1070

@PrestonN @GilgusMaximus

**Closed** 2021-08-17 15:38 UTC
Labels: enhancement
