### ISSUE TITLE
Annoying error messages

### ISSUE THREAD

**Issue by jesperjackson** [FreeTubeApp/FreeTube#1972] opened 2022-01-02 11:53 UTC
**Behavior of the program**
Multiple annoying error messages in the middle of the screen.

**Expected behavior**
I think error messages should be hidden away some where, like in the terminal or a file.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Start FreeTube
or
1. Click on a video

**Screenshots**
I'll try to add some screenshots (and logs if needed) next time I see these errors

**Environment Information (please complete the following information):**
 - OS: Manjaro
 - OS Version: 2022-01-02
 - FreeTube version: v0.15.1 Beta
 - Installation Method (If applicable): AUR
 - Primary API Used: Invidious API

**Additional context**
I get error messages often when I start FreeTube or click on a video. They are usually the same message displayed 5-10 times and taking up a large portion of the screen. The video will often play fine, so the errors are only annoying

**Comment by constraintAutomaton** [comment] 2022-01-03 01:31
I think it should be an option to show it into the toast

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-03 21:10
Please move the discussion over to https://github.com/FreeTubeApp/FreeTube/issues/1049

Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1049

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-01-03 21:10 UTC
Labels: bug
