### ISSUE TITLE
[Bug]: NotSupportedError: Failed to load because no supported source was found.

### ISSUE THREAD

**Issue by techrivertree** [FreeTubeApp/FreeTube#4079] opened 2023-09-28 13:38 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open freetube
2. Select any video
3. See error

### Expected Behavior

If you click on a video it should play. That does not work "NotSupportedError: Failed to load because no supported source was found." I tried 5 different videos. None worked. I restarted my PC, still wont work.

### Issue Labels

usability issue

### FreeTube Version

v0.19.0 Beta

### Operating System Version

Ubuntu 22.04

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.0 Beta

### Additional Information

Freetube was working. I also posted the bug in the matrix chat.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-09-28 16:05
Please provide the urls of all the videos u get this error on

**Comment by techrivertree** [comment] 2023-09-28 17:24
Every video.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-09-28 17:30
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3892

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-09-28 17:30 UTC
Labels: bug, B: usability

**Comment by Gevaarlijk** [comment] 2023-11-15 23:46
I have this exact same error since an hour. "NotSupportedError: Failed to load because no supported source was found." Happens on all the vids and on every build I've tried.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-16 07:49
@Gevaarlijk 

Could u do the following: 

1. open the dev tools with ctrl + shift + i
2. Navigate to a video
3. Make a screenshot of the red errors that appeared in the dev console

**Comment by Gevaarlijk** [comment] 2023-11-16 09:21
So I switched to "Proxy Videos Through Invidious" last night because I found that solution in some other thread with the same error and it worked again. Tomorrow it didn't work anymore and switched back to unflag that setting and now it works again. I don't know what that setting does though or why.

**Comment by LinxLynxin** [comment] 2024-07-24 21:33
Error: This video is not available and API error. Nothing is working and the video is glitching

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-24 21:55
> Error: This video is not available and API error. Nothing is working and the video is glitching

@LinxLynxin see https://github.com/FreeTubeApp/FreeTube/issues/5456
