### ISSUE TITLE
[Feature Request]: select default video quality with or witthout the 60fps variant [frames per seconds]

### ISSUE THREAD

**Issue by zh54tg234f** [FreeTubeApp/FreeTube#2875] opened 2022-11-19 13:09 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

since buffering is very bad for people with unstable / limited bandwidth connection it would be nice to set a default buffering quality that is or is not the 60fps version.

i mean fixing buffering in the first place would be appreciated but since it does not seem to happen soon 
a more reliable way of selecting a default quality.

### Proposed Solution

make an option for 60fps and non 60fps 
currently you can only select quality and it will use the 60fps version as default when ever it is available.
(good intention but with crappy buffering resulting in bad user experience) 

### Alternatives Considered

no idea what else to say about this beside tackling the buffering issues.

### Issue Labels

display more information to user, ease of use improvement, improvement to existing feature, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-11-19 16:38
We consider this a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/504

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-11-19 16:38 UTC
Labels: enhancement, E: improvement existing feature, E: visual improvement, E: display more information, E: ease of use improvement
