### ISSUE TITLE
[Feature Request]: Opening Links in New Window

### ISSUE THREAD

**Issue by RagglenLove** [FreeTubeApp/FreeTube#2042] opened 2022-02-03 12:13 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

In regular YouTube, you can right click multiple videos and load them, which allows for multitasking, e.g. watching two or more simultaneous videos at once.

In FreeTube, you cannot do this.

### Proposed Solution

Add a "Open Link in New Window" to the context menu when right clicking on links.

### Alternatives Considered

N/A

### Issue Labels

ease of use improvement, improvement to existing feature

### Additional Information

![Screenshot_2022-02-03_19-33-33](https://user-images.githubusercontent.com/45503845/152340030-1eff3e83-9b80-41dd-893b-aab534b015c2.jpg)

Here's the mockup of the feature I'm requesting.

**Comment by johnno66** [comment] 2022-02-03 13:22
In my case (kubuntu) the middle mouse button opens links in new window on Freetube.  No specific configuration in either Freetube or mouse preferences has been done.

**Comment by ChunkyProgrammer** [comment] 2022-02-03 14:23
Duplicate of #2000

**Closed** 2022-02-03 14:23 UTC
Labels: U: duplicate, enhancement, E: improvement existing feature, E: ease of use improvement
