### ISSUE TITLE
Removal of the black error messages or this needs some coding effort

### ISSUE THREAD

**Issue by Hx2-code** [FreeTubeApp/FreeTube#1030] opened 2021-02-13 04:36 UTC
Can the black toast messages viewed when errors are encountered be disabled?

**Comment by saideepesh000** [comment] 2021-02-14 13:11
Hey @Hx2-code , Could you show us the screenshot, btw error messages are meant to be shown to users otherwise u never go to know what's happened.

**Comment by GizDrak** [comment] 2021-02-14 15:08
@saideepesh000 I bet he is getting the lame once I have been getting for a little over a week now that say. "TypeError: Cannot read property 'title' of undefined"

Here is a screenshot
[https://snipboard.io/9XhzpK.jpg](url)

**Comment by PrestonN** [comment] 2021-02-14 15:55
This is a duplicate of #1021. You can enable RSS to remove the error messages for now until a fix is released.

**Closed by PrestonN** 2021-02-14 15:55 UTC
Labels: Discussion

**Comment by Hx2-code** [comment] 2021-02-14 17:51
Thank you. You answered my issue before I observed the notifications.
