### ISSUE TITLE
Encoding error in search field and results

### ISSUE THREAD

**Issue by milotype** [FreeTubeApp/FreeTube#679] opened 2020-10-16 16:40 UTC
**Behavior of the program**
There seem to be 2 encoding problem in the search field ...

1. German diacritics/umlauts don't automatically show correctly. Instead `.notdef` character is shown. (Just for comparisson, Croatian diacritics are OK)
2. Using German diacritics/umlauts with German keyboard show correctly, but give no result.

**Expected behavior**

**Problem 1**
German diacritics/umlauts should show correctly without the `.notdef` sign. There shouldn't be a warning message after search is completed.
**Problem 2**
Using German diacritics/umlauts with German keyboard should give results without a warning message.

**To Reproduce Problem 1**
1. Go to search field
2. Type with German keyboard "franz"
`Enable Search Suggestion` is ON
`Fallback to Non-Preferred Backend on Failure` is ON
` Preferred API Backend` is ON
3. See .notdef character in suggestions, as well as the warnings ` Local API Error (Click to copy)` and ` Falling back to Invidious API`

![search1](https://user-images.githubusercontent.com/43657314/96282257-c528ba80-0fda-11eb-987a-d1c6f2fdd213.png)
![search2](https://user-images.githubusercontent.com/43657314/96282267-ca860500-0fda-11eb-9ceb-6db3d47143c1.png)

**To Reproduce Problem 2**
1. Go to search field
2. Type with German keyboard "französische"
`Enable Search Suggestion` is ON
`Fallback to Non-Preferred Backend on Failure` is ON
` Preferred API Backend` is ON
3. There is no search result. There are warnings ` Local API Error (Click to copy)` and ` Falling back to Invidious API`

![search3](https://user-images.githubusercontent.com/43657314/96283218-2a30e000-0fdc-11eb-8761-dc738422b5e0.png)
![search4](https://user-images.githubusercontent.com/43657314/96283224-2dc46700-0fdc-11eb-8f97-c2cddf38ac52.png)

**Desktop:**
 - OS: [MacOS]
 - OS Version: [10.11.6]
 - FreeTube version: [0.9 nightly]

**Comment by EchedeyLR** [comment] 2020-10-17 21:06
I am also experiencing the same issue

**Comment by EchedeyLR** [comment] 2020-10-17 21:17
I cannot edit the comment so I write a new one.

My case is applied to any search, even something basic like "amv" (only ascii set of characters).

**Comment by GilgusMaximus** [comment] 2020-10-19 10:06
Hi, so the error that is displayed to you and the results being empty as a result of this error is not related to using Umlaute in German or any other encoding. It is a general error, that happens due to a problem at a module we are using, that got broken by YouTube. That's why @EchedeyLR also has this error with ASCII. So we are currently waiting to a fix.

Nonetheless, special characters from languages do not give any results, which is a bug in itself.

**Comment by EchedeyLR** [comment] 2020-10-19 10:21
> You can fix this bug by searching again usually (not always).

Thank you for addressing which was the real issue. Yes, if you try several times can work but as you pointed it doesn't work always. 

I will be glad waiting for a fix.

**Comment by PrestonN** [comment] 2020-10-19 13:48
This is a duplicate of #662

**Comment by PrestonN** [comment] 2021-02-19 15:24
Re-opening to eventually handle the encoding issue. Need to replace the current module we're using and request the URL directly.

**Closed** 2021-04-21 23:47 UTC
Labels: bug
