### ISSUE TITLE
add server mode

### ISSUE THREAD

**Issue by ExpandingMan** [FreeTubeApp/FreeTube#1731] opened 2021-09-21 18:21 UTC
Would it be difficult to set `FreeTube` up to run in "server mode", i.e. serve from a port so that I can open it in my browser?

FreeTube has a number of nice features that are still missing from invidious, but when using it I miss out on some very powerful browser extensions that I use.

**Comment by PrestonN** [comment] 2021-10-12 21:10
Duplicate of #633

**Closed as completed by PrestonN** 2021-10-12 21:10 UTC
Labels: U: duplicate, enhancement, U: doesn't follow template
