### ISSUE TITLE
[Feature Request]: Refresh video after the watch session expires

### ISSUE THREAD

**Issue by pakoito** [FreeTubeApp/FreeTube#5960] opened 2024-10-27 12:12 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

If you leave Freetube open with a video for a while, you see `[BAD_HTTP_STATUS: 403] YouTube watch session expired. Please reopen this video.` which makes sense. I would like to have an easy way to refresh the screen to go back to the video.

### Proposed Solution

A refresh button is available somewhere in the UI.

### Alternatives Considered

At the moment you can go to another section of the app and come back and the video will refresh correctly.

### Issue Labels

ease of use improvement

**Comment by absidue** [comment] 2024-10-27 13:01
Duplicate of #4160

**Closed** 2024-10-27 13:01 UTC
Labels: enhancement, E: ease of use improvement
