### ISSUE TITLE
[Feature Request]: Option to hide YouTube Shorts

### ISSUE THREAD

**Issue by chaptergy** [FreeTubeApp/FreeTube#2008] opened 2022-01-14 21:25 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

This is less of a problem and more of an annoyance. When looking at the subscriptions / trending there are lots of #shorts videos which are not the content I am looking for on YouTube, and am not interested in.

### Proposed Solution

An option to automatically hide all #shorts within the app, so they don't show up in subscriptions / trending / popular.

### Alternatives Considered

Just not clicking on those videos I guess

### Issue Labels

new feature

**Comment by arrowgent** [comment] 2022-01-18 19:18
if there is a way to identify #shorts but i dont think youtube makes any distinction of this on any api
a youtube viewer just sees it as a regular youtube video.  same would occur on an invidious instance also

if the size of a video is an indicator, a 1:2 resolution such as 720x1440 would suggest a phone or short video

**Comment by elesto** [comment] 2022-01-22 19:10
Maybe you could add an option where you the user could select to hide videos less than X seconds long. The user could decide what they consider a short

**Comment by chaptergy** [comment] 2022-01-23 09:12
Officially shorts have to be under 60 seconds long currently. However for subscriptions fetched via RSS I don't think duration information for the videos is available...

**Comment by PrestonN** [comment] 2022-02-06 20:17
I'd consider this a duplicate of #1070

**Closed by PrestonN** 2022-02-06 20:17 UTC
Labels: enhancement, E: new feature

**Comment by BarbzYHOOL** [comment] 2023-01-12 23:08
two different issues

**Comment by Flashwalker** [comment] 2023-03-13 18:13
We want to skip shorts!

**Comment by ika-twb** [comment] 2023-06-13 17:37
i've never written any javascript code before, just wanted to share this quick hack that filters out video in Subscription list which are shorter than 60secs, before Developers implement the ``video title'' filter feature.

here's the patch:
```
From 7c21cc680dff8a1a6f2066e91afe4d5b91deaced Mon Sep 17 00:00:00 2001
From: ika <ika@thewizardbay.cc>
Date: Wed, 14 Jun 2023 01:21:21 +0800
Subject: [PATCH] quick hack for filtering out shorts

---
 src/renderer/views/Subscriptions/Subscriptions.js | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/src/renderer/views/Subscriptions/Subscriptions.js b/src/renderer/views/Subscriptions/Subscriptions.js
index c952fa66..fdc6d945 100644
--- a/src/renderer/views/Subscriptions/Subscriptions.js
+++ b/src/renderer/views/Subscriptions/Subscriptions.js
@@ -113,6 +113,11 @@ export default defineComponent({
         const subscriptionList = JSON.parse(JSON.stringify(this.profileSubscriptions))
         if (this.hideWatchedSubs) {
           this.videoList = await Promise.all(subscriptionList.videoList.filter((video) => {
+            const minutes = Math.floor(video.lengthSeconds / 60)
+            if (minutes === 0) {
+              return false
+            }
+
             const historyIndex = this.historyCache.findIndex((x) => {
               return x.videoId === video.videoId
             })
-- 
2.39.2
```

set up your environment according to the wiki, apply the change, run lint, run build-release and install the package.

suggestions welcome.

**Comment by Flashwalker** [comment] 2025-05-09 06:16
Shorts are still present in the search results. Please add a filter for search results
