### ISSUE TITLE
Enhancement: Region for Trending (Profile Level instead of General Settings)

### ISSUE THREAD

**Issue by p2635** [FreeTubeApp/FreeTube#484] opened 2020-05-25 11:19 UTC
Hi I'm a new user of FreeTube and I'm quite enjoying it, thanks for the hard work.

As I understand, the region for trending is done as general settings instead of the profile level. Would it be possible for that to be implemented as a future enhancement?

Related: #14

**Comment by PrestonN** [comment] 2020-10-01 22:11
Region will soon be based on your IP (because of a new API) so this might not be possible any more.  So I will be closing this for now.

**Comment by GilgusMaximus** [comment] 2020-10-14 19:13
YouTube still allows to set the region. I also added the option to choose to the trending module. Just the country code has to come from FreeTube as well as a setting to change it

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-06-28 14:29
> 
> 
> YouTube still allows to set the region. I also added the option to choose to the trending module. Just the country code has to come from FreeTube as well as a setting to change it

I wanted to set another region for trending but i cant select anything is this a known bug?

https://user-images.githubusercontent.com/73130443/123653986-2b7a0400-d81d-11eb-80fc-8d276defdbb4.mp4

**Comment by peepopoggers** [comment] 2021-09-27 12:02
@efb4f5ff-1298-471a-8973-3d47447115dc try changing locale and reversing and try again

**Comment by jasonhenriquez** [comment] 2021-09-27 15:03
> Region will soon be based on your IP (because of a new API) so this might not be possible any more.

Was this behavior ever implemented?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-27 15:11
Nope, just checked with my VPN.

**Comment by PrestonN** [comment] 2021-09-27 15:54
@jasonhenriquez 

I believe my wording with that was that at the time only the Invidious API was available.

I believed that the local API would automatically grab trending based on your region since grabbing that information would be based on the user IP instead of the server IP.

If it isn't behaving this way, we'll need to look into what's going on, as this should be implemented via the settings page already.

**Comment by jasonhenriquez** [comment] 2021-09-27 16:00
@PrestonN Ah okay, yes, the main issue is the base case of using the app without ever manually setting a locale preference leaves the Region for Trending dropdown unusable.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-09-30 19:30
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1996

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-09-30 19:30 UTC
Labels: enhancement, Rewrite: featurerequest
