### ISSUE TITLE
Player crash and playback progress lost on route change (i.e. toggling VPN)

### ISSUE THREAD

**Issue by EvilGremlin** [FreeTubeApp/FreeTube#1530] opened 2021-07-19 19:19 UTC
Well, that. Due to networks overload i have to often toggle VPN (by changing my LAN IP to be exact, actual route change and VPN is handled by my router) to get vidos playing at non-dialup speed. Youtube's regular web player and NewPipe handle route change just fine, but FreeTube just crash player. So i have to press Ctrl+R and then search for where it stopped playing... Extremely annoying, can something be done about it?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-19 20:24
Do u get an error message? If so what doe it say?

**Comment by EvilGremlin** [comment] 2021-07-19 20:37
`video append of 952354b failed for segment #2 in playlist 4-placeholder-uri-4`
Now that i delerately tried to change back and forth a lot, on a video that loads fast on both routes, it actually switched alright. I suppose error appears mainly if you switch route while it's waiting for response. Cannot replicate while there is decent buffer.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-19 20:39
This issue is a duplicate of issue https://github.com/FreeTubeApp/FreeTube/issues/761

I suggest closing this issue and commenting on that issue for visibility.

**Comment by EvilGremlin** [comment] 2021-07-19 20:49
Oh, thanks, will do.

**Closed** 2021-07-19 20:55 UTC
Labels: bug
