### ISSUE TITLE
[Feature Request]: Allow scrolling down from full-window

### ISSUE THREAD

**Issue by pseudomonas** [FreeTubeApp/FreeTube#4364] opened 2023-11-20 13:02 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently, if I'm watching a video on full-window, if I want to see the information text or related videos, I have to turn off full-window before scrolling down. This is the case even if playback has finished.

### Proposed Solution

Allow scrolling down in full-window to see the material that lives below the video.

### Alternatives Considered

Turn off full-window automatically when playback stops (and perhaps turn it on automatically when playback starts)

### Issue Labels

ease of use improvement

**Comment by jasonhenriquez** [comment] 2023-11-20 13:21
Duplicate of #887

**Closed by jasonhenriquez** 2023-11-20 13:21 UTC
Labels: enhancement, E: ease of use improvement
