### ISSUE TITLE
[Bug]: Shorts not showing in some channels

### ISSUE THREAD

**Issue by sqrxz** [FreeTubeApp/FreeTube#5741] opened 2024-09-23 20:45 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

In the https://youtube.com/@chluaid/shorts channel's shorts tab, I see none when there are several 

### Expected Behavior

I expect to see all the shorts in the channel

### Issue Labels

content not loading

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Win10 19045

### Installation Method

.zip

### Primary API used

Local API

### Additional Information

I know that the creator disabled alerting his suscriibers of the shorts, maybe that is whee Freetube is trying to get the list of shorts

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-23 20:51
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5685

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-23 20:51 UTC
Labels: bug, B: content not loading
