### ISSUE TITLE
Some thoughts on the linux FreeTube app

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#320] opened 2019-08-11 17:40 UTC
I've been testing the app for the weekend on my Debian linux and have some thoughts on it.

Basically it works well, but the `chrome-sandbox` needs to be setuid. You could fix this via the `postinst` script in the same way you created a link `/opt/FreeTube/freetube -> /usr/local/bin/freetube` so the manual intervention wouldn't be needed.

1. The logo in the top right could be clickable and point to the homepage.
2. The scrollbars can be really short, for instance when you have lots of channels, or when you look through the `Latest Subscriptions` tab. It would be nice to set some minimal sizes to the scrollbars for easier use.
2.1. I noticed that the menu/channel list scrollbar goes under the top panel, and when the scrollbar is really short, you can't target it, and you have to scroll a little bit down, which isn't really convenient when you want fast access to some of the channels from the middle of the list.
3. When you have lots of channels, the `Latest Subscriptions` tab can contain only the most recent positions from all the channels, and they can rotate really quickly. Could you add "fetch more" to this tab?
3.1. I have some channels that I rarely view (only by manual visiting the channel from time to time). It would be nice to see some option to remove/hide certain channels (and their vids) from the `Latest Subscriptions` tab, so it could only show the vids from channels you really want.
4. There's a way to go back using the back arrow that will appear after playing some searched video. This is the only place the back arrow shows up. What about other places like `subscribed channel -> vid` or `favorite -> vid`?
4.1. If the 4. can be done, an option can be added to ask user whether he wants the current scroll position to be preserved, so he wouldn't have to scroll all the way down to see another vids near the one he just played.
5. Subscriptions from YT can be imported, but there's no info on how to do it. I mean not that many users know that you have to go under `https://www.youtube.com/subscription_manager` and hit the export button.
6. Why is there only "max 20" comments? Is this limited somehow by some factor? What about adding "fetch more" to the comments section?
7. Currently the hamburger icon shows/hides the whole left panel. Wouldn't be more intuitive for a user to see here some drop down menu? I'm asking because when I scroll the channel list a bit down and click this hamburger icon, I expect some kind of menu to pop up, but instead the whole panel disappears. What about moving `Settings` and `About` icons to the top panel? There's plenty of space on the left of the search bar.
7.1. The channels list could also be hidden/restored by dragging the right edge.
7.2. The current solution (menu + channel list) isn't really designed to deal with many channels. I think it would be better to have two separate entities so they wouldn't conflict with each other. When you have 1000 channels, and you want to watch the 666th channel, you have to scroll a lot down. When you enter the channel, you are unable to call the menu -- you have to scroll all the way up, to get the `Settings` button, and then again scroll down to the 666th channel.
7.3. It would be nice to see some channel filter in the the subscription list. Again, when you have lots of channels, going through all of them to find the one you want to watch isn't really user friendly now. If you remember the channel name, you can look it up in the main search bar. But if you only know part of the name, it would be a way easier to filter the channels while typing some letters.
7.4. There's an `X` button on the channel list, which can remove a channel from the ones you subscribe. I think most of the people (including me) can press the button by mistake rather than intentionally to remove a channel from the list. Note that you can simply click on the channel, and a page with appropriate button will be presented to you. Could you remove that button and in its place add something more useful? You could for instance add a counter with a number of new videos since your last visit, or/and some info on when this particular channel posted its latest video.
8. Whenever you start FreeTube, it automatically refresh all the channels. This process can take a while, and during it you simply can't access any channel. Could you make an option to configure whether to refresh channels or not when the app starts? Think about starting the app a few times in the 10-minute period to just get some YT links and pass them to someone -- do you really need this automatic refreshments over and over each time you start the app?
9. Some people don't really want to go to the YT page to watch a vid, and they simply want to have full screen embedded video, which can be accessed via the `https://www.youtube-nocookie.com/embed/[vid_ID]` URL. This link also renders faster compared to a regular YT page. Could you add support for this kind of URL under the `Share` button?
10. Is there a chance to implement tabs like the ones in web browsers? For instance, you have a list of channels, and you want to watch five videos. I would normally use the middle mouse button, and the vids would open in separate tabs. I can switch to individual tab and play its video.
11. I noticed that only two keybindings are working so far: `space` (for pausing a vid) and `ESC` (for leaving the full screen mode). Could you add more keybindings so linux users can benefit from them?
11.1. `ctrl+f` (find) -- after pressing it, the search bar would appear and you can start typing whatever you want to search.
11.2. `backspace` (go back) -- when you search a vid in the main search bar and click it, you get the left arrow, and after clicking it, you go back. It would be nice to do that using also the backspace key.
11.3. `ESC` (home) -- after pressing it when you're not in the full screen mode, it should take you to your home tab, for instance the `Latest Subscriptions` or whatever you configured in the settings.
11.4. You can enter/exit the full screen mode by clicking 2x the left mouse button on the vid. While you doing this, the vid will be paused for a short period of time. Shouldn't it detect the event of entering/exiting the full screen mode via mouse clicks without pausing the vid?
11.5. Support for for the back and forward mouse buttons also would be nice to have.
12. There seems to be a problem when importing lots of channels (200-300) when some of them are deleted by YT policy (they aren't automatically unsubscribed and they're present on the YT page and wait for manual intervention).
13. When you switch to the black theme, the white one will appear while starting the app for short period of time.
14. When you have a slow internet connection, you can lower the vid quality in order to watch the video. Some video players (mpv) allow the cache to be configured. In this way, you can set how many data can be downloaded and held in the cache. But in the case of FreeTube when you pause a vid, it won't catch more stream -- it will download only a few MiB and will wait for user to play the vid. Is there a chance to implement such options like (1)how many seconds or MiB can be cached (possibly even a full vid), and (2)the download speed?
15. Sometimes when I play a vid, I get this message: `Write after end`. What does it mean?
16. Also it would be nice to have some minimode, in which it hides all borders/frames/panels and leaves only the player with the vid. This is useful when you want to pin the app window on the top of everything else and watch the vid while doing something else like browsing the net. Of course some keybinding will be needed to go into this mode and exit from it. 

I think that's it for now. :]

**Comment by PrestonN** [comment] 2019-08-13 15:53
Hey there!  I really appreciate you taking the time to write all of this.  I will answer each and every question / comment.  Long post incoming.

> Basically it works well, but the chrome-sandbox needs to be setuid. You could fix this via the postinst script in the same way you created a link /opt/FreeTube/freetube -> /usr/local/bin/freetube so the manual intervention wouldn't be needed.

I would like to get this fixed.  Right now the builds are made automatically by electron-builder so all the config is made through that.  If you know how to make this change through electron-builder then it would be much appreciated.

> The logo in the top right could be clickable and point to the homepage.

It felt kind of redundant to me to have it point to something already in the navigation bar, but it could be done.  Maybe it could point to the user's default landing page that is set in settings?

> The scrollbars can be really short, for instance when you have lots of channels, or when you look through the Latest Subscriptions tab. It would be nice to set some minimal sizes to the scrollbars for easier use.

Hmm. I'll have to look into this one a bit more.  I can see this being annoying.

> 2.1. I noticed that the menu/channel list scrollbar goes under the top panel, and when the scrollbar is really short, you can't target it, and you have to scroll a little bit down, which isn't really convenient when you want fast access to some of the channels from the middle of the list.

Good catch.  I'll fix this before the next release.

> When you have lots of channels, the Latest Subscriptions tab can contain only the most recent positions from all the channels, and they can rotate really quickly. Could you add "fetch more" to this tab?

Yes this could be done.  Should be a simple thing to include for a release after this upcoming one.

> 3.1. I have some channels that I rarely view (only by manual visiting the channel from time to time). It would be nice to see some option to remove/hide certain channels (and their vids) from the Latest Subscriptions tab, so it could only show the vids from channels you really want.

Local profiles will be coming this week which will allow you to categorize your subscriptions into different profiles and only show videos in the profile.  Check out the [Behind the Scenes](https://freetube.writeas.com/behind-the-scenes-local-profiles-preview) article to learn more.

> There's a way to go back using the back arrow that will appear after playing some searched video. This is the only place the back arrow shows up. What about other places like subscribed channel -> vid or favorite -> vid?

This will be addressed in it's own big release.  Proper navigation will take some time to get done right and I'm hoping to work on it soon.

> 4.1. If the 4. can be done, an option can be added to ask user whether he wants the current scroll position to be preserved, so he wouldn't have to scroll all the way down to see another vids near the one he just played.

Good idea.  I'll try to include this when I work on the navigation functionality.

> Subscriptions from YT can be imported, but there's no info on how to do it. I mean not that many users know that you have to go under https://www.youtube.com/subscription_manager and hit the export button.

There are instructions in the [F.A.Q.](https://github.com/FreeTubeApp/FreeTube/wiki/F.A.Q.) that explains how to do it.  I think linking to this within the app would be a good idea.

> Why is there only "max 20" comments? Is this limited somehow by some factor? What about adding "fetch more" to the comments section?

Simply because it's a part of the app I haven't had the time to flesh out just yet.  I try to align my priorities with what gets requested by the community and expanding on comments hasn't been a highly requested feature for now.  It's planned and coming.  I don't know when it will be ready but it should be soon.

> Currently the hamburger icon shows/hides the whole left panel. Wouldn't be more intuitive for a user to see here some drop down menu? I'm asking because when I scroll the channel list a bit down and click this hamburger icon, I expect some kind of menu to pop up, but instead the whole panel disappears. What about moving Settings and About icons to the top panel? There's plenty of space on the left of the search bar.

I'm going to go backwards for this comment.  Settings and About likely won't be moved because the top panel was rearranged a bit for local profiles.  You mentioned that there is some extra space up there and you're right.  I'm planning on saving that space for when the proper navigation functionality is ready as forward / back arrows will permanently be up there and will likely use a lot of that space.  I've thought about a refresh button going up there as well but I'm not 100% decided on that yet.

What sort of drop down menu would you recommend?  I can't say I've seen a setup similar to your suggestion in other apps, YouTube included.  Hiding the menu seems like the best option for now.

> The channels list could also be hidden/restored by dragging the right edge.

I'll have to look into this.  I don't see it having too much benefit though.

> 7.2. The current solution (menu + channel list) isn't really designed to deal with many channels. I think it would be better to have two separate entities so they wouldn't conflict with each other. When you have 1000 channels, and you want to watch the 666th channel, you have to scroll a lot down. When you enter the channel, you are unable to call the menu -- you have to scroll all the way up, to get the Settings button, and then again scroll down to the 666th channel.

I don't hear about too many people that subscribe to over 1000 channels, but it's still a valid concern.  I don't really know of any way that YouTube solves this problem either so I'll have to see what I can do.  Maybe if the navigation bar can be expanded by dragging it could show channels in a type of grid view?

> 7.3. It would be nice to see some channel filter in the the subscription list. Again, when you have lots of channels, going through all of them to find the one you want to watch isn't really user friendly now. If you remember the channel name, you can look it up in the main search bar. But if you only know part of the name, it would be a way easier to filter the channels while typing some letters.

As was mentioned above, channel profiles will be included in the next release.  Search suggestions will be coming as well so that should be helpful with finding more channels.  I could probably implement a local search through subscriptions though if there's enough demand for it.

> 7.4. There's an X button on the channel list, which can remove a channel from the ones you subscribe. I think most of the people (including me) can press the button by mistake rather than intentionally to remove a channel from the list. Note that you can simply click on the channel, and a page with appropriate button will be presented to you. Could you remove that button and in its place add something more useful? You could for instance add a counter with a number of new videos since your last visit, or/and some info on when this particular channel posted its latest video.

I can add a confirm dialog box to make sure you actually want to remove the subscription.  Adding different functionality there will require some time to work on it and I don't keep any information on last visits at the moment.  I think something could be added in the future though.  Maybe when push notifications get implemented?

> Whenever you start FreeTube, it automatically refresh all the channels. This process can take a while, and during it you simply can't access any channel. Could you make an option to configure whether to refresh channels or not when the app starts? Think about starting the app a few times in the 10-minute period to just get some YT links and pass them to someone -- do you really need this automatic refreshments over and over each time you start the app?

Some have mentioned storing the last list of subscriptions when the app quits and using that list when it re-opens which should prevent this.  This is something that I think would be good to do.  It won't be the next release but it could be a good idea for a release after that.  For now, if you change your default landing page you can startup in the Featured section for example and you won't have to wait for your subscriptions to load.

> Some people don't really want to go to the YT page to watch a vid, and they simply want to have full screen embedded video, which can be accessed via the https://www.youtube-nocookie.com/embed/[vid_ID] URL. This link also renders faster compared to a regular YT page. Could you add support for this kind of URL under the Share button?

This could easily be done.  I already generate a `nocookie` URL to use the embedded player within the app so adding it to the share menu should be easy enough.

> Is there a chance to implement tabs like the ones in web browsers? For instance, you have a list of channels, and you want to watch five videos. I would normally use the middle mouse button, and the vids would open in separate tabs. I can switch to individual tab and play its video.

This is another big update that's planned for a future release.  A lot of custom logic will need to be made in order for it to work so it will be in it's own release.  It will likely be one of the last things I do before a stable release.  For now, multiple windows can be opened through File->New Window or you can open videos through the mini-player.

> I noticed that only two keybindings are working so far: space (for pausing a vid) and ESC (for leaving the full screen mode). Could you add more keybindings so linux users can benefit from them?

We have a list of keyboard shortcuts that you can find over in the [Wiki](https://github.com/FreeTubeApp/FreeTube/wiki/Keyboard-Shortcuts).

> 11.4. You can enter/exit the full screen mode by clicking 2x the left mouse button on the vid. While you doing this, the vid will be paused for a short period of time. Shouldn't it detect the event of entering/exiting the full screen mode via mouse clicks without pausing the vid?

A normal double click will show a pause for a moment, but should still play normally once the player is full screen.  I can look into maybe preventing this but I'd consider it a minor issue.

> There seems to be a problem when importing lots of channels (200-300) when some of them are deleted by YT policy (they aren't automatically unsubscribed and they're present on the YT page and wait for manual intervention).

I'll have to see what I can do about this.  I would like to do it where the user is clearly notified of a channel being removed if it's done automatically and I want to make sure it isn't done accidentally on a false positive.  I would rather have users do it manually than automatically if legit channels end up removed by accident.  I will play around with making this work.

> When you switch to the black theme, the white one will appear while starting the app for short period of time.

I'd consider this a very minor issue.  I'll try to see if I can make the switch faster to prevent the quick flash, but as I said, it's a minor issue and not high priority.

> When you have a slow internet connection, you can lower the vid quality in order to watch the video. Some video players (mpv) allow the cache to be configured. In this way, you can set how many data can be downloaded and held in the cache. But in the case of FreeTube when you pause a vid, it won't catch more stream -- it will download only a few MiB and will wait for user to play the vid. Is there a chance to implement such options like (1)how many seconds or MiB can be cached (possibly even a full vid), and (2)the download speed?

This should be configurable since we're using Dash.js, however I'm still learning with it and haven't fully browsed through their documentation.  I'll look into this and try to make it an option for a future release.

> Sometimes when I play a vid, I get this message: Write after end. What does it mean?

Please see #303, fix coming later this week :)

> Also it would be nice to have some minimode, in which it hides all borders/frames/panels and leaves only the player with the vid. This is useful when you want to pin the app window on the top of everything else and watch the vid while doing something else like browsing the net. Of course some keybinding will be needed to go into this mode and exit from it.

This was sorta mentioned above, but FreeTube has a mini-player that will do exactly this.  You can see it when you are watching a video or you can have it open up in the video list but looking in the 3 dot menu near a video.

Phew, that's everything.  While I enjoy these long write ups, for future reference, please make a separate issue for each thing mentioned here as it's easier to track each individual issue.  There's a chance I might forget about some of the things mentioned here and we wouldn't want that.

Take care!

**Comment by Millichrome** [comment] 2019-08-13 16:19
Thanks for the detailed responses dev! A lot of the issues mentioned by OP would be helpful for non-linux users too. 

Looking forward to the local profiles feature.

Thanks for your work on FreeTube!

**Comment by morfikov** [comment] 2019-08-13 19:40
> What sort of drop down menu would you recommend? I can't say I've seen a setup similar to your suggestion in other apps, YouTube included. Hiding the menu seems like the best option for now.

Basically the one you usually see on mobile phones. Something similar to what happens when you click the hamburger icon in the Firefox. Here's an example from another YT app I was using till the switch to FreeTube: https://i.imgur.com/Z7dE8iG.jpg -- you just click the hamburger icon, and a menu pops up, it's simple. :)

> > The channels list could also be hidden/restored by dragging the right edge.
> 
> I'll have to look into this. I don't see it having too much benefit though.

It would make sense only if channels stayed in the left panel and the menu-related buttons were moved to some other space, i.e. under the hamburger menu.

> I don't hear about too many people that subscribe to over 1000 channels...

I'm pretty close to that, but even having 100 channels, can be a little bit irritating.

>Maybe if the navigation bar can be expanded by dragging it could show channels in a type of grid view?

What about making a whole tab for subscribed channels and leaving only menu related icons on the left panel, or even removing the whole left panel and hide the menu under the hamburger icon?

> This was sorta mentioned above, but FreeTube has a mini-player that will do exactly this...

I see, it wasn't working when I was testing it (only some blank new window appeared), but it looks like it's working now.

> Phew, that's everything. While I enjoy these long write ups, for future reference, please make a separate issue for each thing mentioned here as it's easier to track each individual issue. 

It simply can be ctrl+c and ctrl+v to a separate thread. I thought it it would be too much spam with each issue as a separate one, but I can cut this and place in a separate threads.

**Comment by PrestonN** [comment] 2019-08-14 15:26
> Basically the one you usually see on mobile phones. Something similar to what happens when you click the hamburger icon in the Firefox. Here's an example from another YT app I was using till the switch to FreeTube: https://i.imgur.com/Z7dE8iG.jpg -- you just click the hamburger icon, and a menu pops up, it's simple. :)

I see.  I think the problem is that I would be filling up a menu like that for the sake of it.  The only real way I see this working out is if I move the settings menu to a drop down like that and I don't see any real benefits to doing that.

> What about making a whole tab for subscribed channels and leaving only menu related icons on the left panel, or even removing the whole left panel and hide the menu under the hamburger icon?

Local profiles will sorta handle this as you'll have a much better view of all of your subscriptions, however it currently can't be used to actually view the channel in question.  It's something that could be added with a future update.

> It simply can be ctrl+c and ctrl+v to a separate thread. I thought it would be too much spam with each issue as a separate one, but I can cut this and place in separate threads.

Some of the smaller or related ones can be put together into one issue, but having a large list in one issue like this makes it harder to remember what needs to get done.  I check the issues fairly often to quickly look through and see what I can get done and certain issues can get lost in a lot of text if I'm not looking carefully.  It isn't a huge issue but I would prefer it when possible.

**Comment by morfikov** [comment] 2019-08-14 15:36
I've just split the issues. I think I covered all the important ones.

**Comment by PrestonN** [comment] 2019-08-14 18:32
Great!  Thank you for doing that.  I will go ahead and close this issue so that we can stay organized.

**Closed by PrestonN** 2019-08-14 18:32 UTC
