### ISSUE TITLE
Feature to save playlist

### ISSUE THREAD

**Issue by PeterDaveHello** [FreeTubeApp/FreeTube#1697] opened 2021-09-13 16:27 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**

There are many awesome playlists that I can't finish watching in a day because it's too long, would like to see if I can "save" them, so that I don't need to remember the channel and find them every time I want to continue watching it.

**Describe the solution you'd like to see implemented**

Is it possible to save a play list just like we can save a video?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-13 16:31
Hi @PeterDaveHello this is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/312

If u want u can leave a comment over there.

I'll be closing this issue in order to prevent cluttering the backlog

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-09-13 16:31 UTC
Labels: enhancement

**Comment by PeterDaveHello** [comment] 2021-09-13 16:44
Sure thing @efb4f5ff-1298-471a-8973-3d47447115dc , sorry that I didn't notice it and opened a duplicated issue.
