### ISSUE TITLE
[Bug]: No sound on external player

### ISSUE THREAD

**Issue by maplepy** [FreeTubeApp/FreeTube#3276] opened 2023-03-09 20:40 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click on any youtube video external player
2. Have mpv or any player open up and play the video with sound
3. it has no sound so you can't anymore

### Expected Behavior

mpv has a sound track

### Issue Labels

feature stopped working

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux 6.2.2-arch1-1

### Installation Method

AUR

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

The previous one I guess? 

### Additional Information

![image](https://user-images.githubusercontent.com/28269333/224150797-924b4da8-1a56-4632-97df-10efbbed8daa.png)

See you don't have an audio track

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-03-09 20:55
FreeTube doesn't pass any quality information along to mpv, it only tells it to open the video, so the format selection is all done on the mpv side. I recommend updating things like youtube-dl and yt-dlp and checking your mpv config.

**Comment by maplepy** [comment] 2023-03-09 20:59
Well that'd be weird because it only happened once I updated freetube? And some videos seem to work and some don't

**Comment by absidue** [comment] 2023-03-09 21:01
mpv uses youtube-dl or yt-dlp to get the formats for the video, check that whichever one of those you are using is up to date, YouTube introduced some new throttling stuff recently, so if you are using outdated versions of those, that is likely the cause.

**Comment by maplepy** [comment] 2023-03-09 21:01
This does not work: https://youtu.be/bHIUpniauqQ
This does: https://youtu.be/jN7mSXMruEo

**Comment by absidue** [comment] 2023-03-09 21:16
This is definitely not an issue in FreeTube

The only information that FreeTube passes to mpv is:
- the custom args you've specified in the FreeTube settings
- the video id e.g. `ytdl://jN7mSXMruEo`
- the playback rate e.g. `--speed=1.5`
- the timestamp it should start playing the video at e.g. `--start=10`

if you are watching a playlist it also passes along this information:
- instead of the video id it passes the playlist id to mpv e.g. `ytdl://PL8mG-RkN2uTylSTKCfzdX8YX4pkEnHanG`
- the index of the video at which is should start the playlist e.g. `--playlist-start=2`
- whether the playlist should be shuffled `--shuffle`
- whether the playlist should be looped `--loop-playlist`

**Comment by maplepy** [comment] 2023-03-09 21:34
Do you know how I could try debugging the situation? Should I try to pass video urls to mpv to see if it's an mpv issue?

**Comment by absidue** [comment] 2023-03-09 21:40
it's 100% not an issue with FreeTube. I can link you to the relevant bits of code, if you don't trust me or give you the link to the feature request to pass the quality and format to mpv, which means that FreeTube doesn't do that at the moment.

Yes you can try opening videos directly in mpv, also upgrade yt-dlp or youtube-dl, as that is what mpv uses to get the video information from YouTube.

**Comment by absidue** [comment] 2023-03-09 22:02
Closing this as it's definitely not an issue in FreeTube and not something we can fix on our side.

**Closed by absidue** 2023-03-09 22:02 UTC
Labels: bug, third-party, B: feature stopped working, B: Unofficial Download

**Comment by maplepy** [comment] 2023-03-09 22:53
No no I definitely trust you, just did some digging and it seems like yt-dlp updated with freetube and i just missed it so that's totally on me, sorry about that!
