### ISSUE TITLE
"Fetch More Results" on search doesn't exclude already shown results

### ISSUE THREAD

**Issue by eMorph** [FreeTubeApp/FreeTube#771] opened 2020-11-05 15:43 UTC
**Behavior of the program**
Upon clicking "Fetch More Results" in the search UI, it often brings up the same results as shown already, with maybe one other video.

**Expected behavior**
When fetching more results, if the behavior works via performing another search, that search should exclude all results already shown. If it works any other way, search results should not show more than once.

**To Reproduce**
1. Go to Search
2. Search for anything with a large amount of results
3. Scroll down to end of results
4. Click on "Fetch More Results"
5: Most videos already shown at the top should be fetched again

**Screenshots**
![Screenshot at 2020-11-05 10-38-34](https://user-images.githubusercontent.com/50468391/98262217-5b555e00-1f53-11eb-9537-bd7aaf7cf591.png)
![Screenshot at 2020-11-05 10-39-29](https://user-images.githubusercontent.com/50468391/98262380-8c359300-1f53-11eb-8d51-a84006d8f2ad.png)

**Environment Information (please complete the following information):**
 - OS: Fedora
 - OS Version: fc32
 - FreeTube version: 0.9.2 Beta
 - Installtion Method (If applicable): FlatHub

**Additional context**
This has happened both on local and Invidious, but I'm using local in these screenshots.

**Comment by PrestonN** [comment] 2020-11-05 16:21
I'm going to consider this as a duplicate of #662 because part of the problem is that search isn't providing the needed information to get the next page of results.

**Closed by PrestonN** 2020-11-05 16:21 UTC
Labels: bug
