### ISSUE TITLE
[Bug]: Don't hide videos which aren't completely watched

### ISSUE THREAD

**Issue by christian179717** [FreeTubeApp/FreeTube#2910] opened 2022-12-04 11:06 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Activate "Hide Videos on Watch".
![grafik](https://user-images.githubusercontent.com/89655752/205486949-1926a7ff-4bd1-49d4-84ea-b5b7ef54d0e0.png)

2. Begin watching a video.
3. Interrupt watching.
4. If you reload the subscription page the video will not be shown.

### Expected Behavior

The video should be shown till it's completely watched.

### Issue Labels

usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux Mint 21

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Gorrrg** [comment] 2022-12-08 19:11
Interrupted videos should show a progress bar in their thumbnail instead.

**Comment by petaded** [comment] 2022-12-17 19:29
In case you are trying to find the videos, you can go into "History" and click the three dots -> "Remove from history" to make it reappear.

In regards to the bug, this brings up two thoughts for implementing this:
1. The setting is currently "hide videos on watch" and not "hide watched videos" - e.g. "on watch" currently meaning having clicked on the video. (Just a semantic thing that would have to be changed, not a blocking issue)
2. What would you actually count as "watched" ?

To expand on 2: A lot of videos have an outro or a sponsor spot at the end (last 10 seconds maybe) but I personally would leave the video rather than waiting until it actually finishes. I would still count this as "watched".

The amount of watch time that someone counts as "watched" probably is different for each person and also video. I believe generally youtube counts 30 seconds and beyond as a view.

My possible solution would be some sort of configurable setting, so you could say what proportion of a video has to be seen before its hidden. e.g. 90%. You would also have to change the wording on the setting name to make it clear that this is what it does.

**Comment by christian179717** [comment] 2022-12-18 15:32
1. If I remove the video from history the time at which I dropped out isn't saved any more so this is no solution for me.
2. But if you  don't want to watch the video completely you could drop out and mark the video then as watched. I think that would be a better solution instead make it very complicate to continue watching e.g. you have no time anymore and want to watch the rest tomorrow you'll have to make the whole way through the history.
Additionally I don't really like it, if the subscription page is completely overloaded which videos I've already watched completely (so I'm not interested in them anymore) instead of showing me videos I haven't completely watched or even didn't begin watching.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-12-19 19:49
I'm sorry guys but i have to mark this as a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/964 and https://github.com/FreeTubeApp/FreeTube/issues/609. Please continue the conversation over there.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-12-19 19:49 UTC
Labels: bug, B: usability
