### ISSUE TITLE
[Feature Request]: Disable navigation by keyboard numbers

### ISSUE THREAD

**Issue by FelipeJz** [FreeTubeApp/FreeTube#5070] opened 2024-05-05 22:07 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I constantly tap the number row by accident making the video jump around

### Proposed Solution

Create a setting to disable number row navigation

### Alternatives Considered

Is the only solution really

### Issue Labels

new optional setting

**Comment by DontBlameMe99** [comment] 2024-05-06 04:03
Duplicate of 992
This one tried to implement this change, but was closed due to inactivity: 4296

**Comment by jasonhenriquez** [comment] 2024-05-06 04:07
Thanks @DontBlameMe99! Closing as this is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/992 and https://github.com/FreeTubeApp/FreeTube/issues/251.

**Closed by jasonhenriquez** 2024-05-06 04:07 UTC
Labels: enhancement, E: new optional setting
