### ISSUE TITLE
[Bug]: Endless video loading, all buttons become unresponsive

### ISSUE THREAD

**Issue by MemoryDreams** [FreeTubeApp/FreeTube#6351] opened 2024-12-11 09:15 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open Freetube app
2. Click any video
3. Loading starts and nothing can be clicked anymore. 

### Expected Behavior

When clicking on video it's supposed to start playing.

### Issue Labels

content not loading, feature stopped working, usability issue

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Linux Mint, latest build

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v.022.0 Beta

### Additional Information

I'Laptop I'm using is ThinkPad x230 with Core i5 processor. 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by MemoryDreams** [comment] 2024-12-11 09:18
The same version of the app from Flathub works just fine.

**Comment by absidue** [comment] 2024-12-11 09:45
Duplicate of #6328

**Closed by absidue** 2024-12-11 09:45 UTC
Labels: bug, B: content not loading, B: usability, B: feature stopped working
