### ISSUE TITLE
[Feature Request]: searching

### ISSUE THREAD

**Issue by Golddouble** [FreeTubeApp/FreeTube#3065] opened 2023-01-14 14:04 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

We can search for videos in the whole youtube universe. But there is no search function to search through the videos, that are on the current page.

### Proposed Solution

In Firefox you can press Ctrl+F and then you can search for a word on this page. This is the feature I would like to have also in FreeTube.

What do you think? Thank you for your feedback.

### Alternatives Considered

?

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-01-14 15:00
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1401

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-01-14 15:00 UTC
Labels: enhancement, E: new feature
