### ISSUE TITLE
Installation Errors Buster

### ISSUE THREAD

**Issue by asddsaz** [FreeTubeApp/FreeTube#211] opened 2019-01-18 17:52 UTC
**Issue**: Will not install on [Debian Buster](https://www.wikipedia.org/wiki/Debian_version_history#Debian_10_(Buster)) because of dependency errors.

Log: 
```
root@LINUX:/home/usr# dpkg -i Applications/FreeTube_0.4.1_amd64.deb
Selecting previously unselected package freetube.
(Reading database ... 236177 files and directories currently installed.)
Preparing to unpack .../FreeTube_0.4.1_amd64.deb ...
Unpacking freetube (0.4.1-1) ...
dpkg: dependency problems prevent configuration of freetube:
 freetube depends on libgconf2-4; however:
  Package libgconf2-4 is not installed.

dpkg: error processing package freetube (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.61) ...
Errors were encountered while processing:
 freetube
root@LINUX:/home/usr# apt-get install libgconf2-4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libgconf2-4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gconf-gsettings-backend

E: Package 'libgconf2-4' has no installation candidate
root@LINUX:/home/usr# apt-get install gconf-gsettings-backend
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gconf-gsettings-backend is already the newest version (3.2.6-5).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 freetube : Depends: libgconf2-4 but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
root@LINUX:/home/usr# 

```

I have tried running `apt --fix-broken install` but  after running I get the same errors.

**Comment by haydenhughes** [comment] 2019-02-28 20:12
Strange. `libgconf2-4` is [available in buster](https://packages.debian.org/buster/libgconf-2-4) so maybe your repo cache needs updating. Try running 

```
apt update
apt install libgconf2-4
```

**Comment by mat8913** [comment] 2019-03-16 04:32
@haydenhughes The link you provided is to `libgconf-2-4` which is a different package from `libgconf2-4`. The required package is not available in buster: https://packages.debian.org/jessie/libgconf2-4

Anyway, this issue is a duplicate of #166

**Comment by PrestonN** [comment] 2019-06-06 15:02
Closing as this has been fixed and will be included in the next release.  The issue was because of a slightly out of date version of Electron.

**Closed by PrestonN** 2019-06-06 15:02 UTC
