### ISSUE TITLE
Rapid flashing when video doesn't load properly

### ISSUE THREAD

**Issue by LynHyper** [FreeTubeApp/FreeTube#1546] opened 2021-07-25 21:41 UTC
Sometimes a video will fail to load but will keep trying over and over, the result is that the video shrinks to the height of the control bar and then grows to it's regular height each time a re-attempt is made, the flashing could actually be of some concern to epileptics since it can flash quite rapidly in some cases.

**Expected behavior**
Failed videos should still take up the space they otherwise would, like setting the width and height of an image in an HTML file for when it's still loading, to prevent the video frame and the rest of the UI from freaking out.

**To Reproduce**
Find a broken video (Can't point you to one unfortunately, sometimes it happens at random for videos that are completely fine after a page reload)
Watch the video frame collapse to the height of the control/video navigation bar and then expand to the default video frame height for each retry rapidly.

**Environment Information**
 - OS: Arch Linux
 - FreeTube version: 0.13.2 Beta
 - Installation Method: FlatHub
 - Primary API Used: Local API (Issue happens with Invidious too)

**Comment by GilgusMaximus** [comment] 2021-07-26 18:58
duplicate of #1442

**Closed by GilgusMaximus** 2021-07-26 18:58 UTC
Labels: bug
