### ISSUE TITLE
Please implement a way to filter and block channels

### ISSUE THREAD

**Issue by Computerlabrat** [FreeTubeApp/FreeTube#772] opened 2020-11-06 07:43 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I'd like to have option to block these channels and videos selectively on my end through the client.

**Describe the solution you'd like to see implemented**
Could you please look into implementing a blocking feature so we can personally block videos and channels that we'd rather not see on the trending page and search results?  I believe youtube does offer this by clicking the three dots below the video and then selecting the options from there.

**Comment by GilgusMaximus** [comment] 2020-11-06 09:48
Hi, so we already had a few suggestions for such a feature in the Matrix channel.
First of all we are politically neutral, so we will not implement anything that actively hinders certain kinds of channels by default. This is not what this project is about and additionally we do not want to get in any potential legal troubles. So I would kindly ask you to remove anything political from your post and just make it general and say 'ability to blocking certain channels' as in your title already. 

If such a list is implemented, it will be as a database file so anyone will be able to share their filter list.

I am gonna reroute you to #95 as it is a bit related.

However I am gonna say right now, that this will likely lead to multiple problems.
First of all searches can become (almost) empty due to too much blocking of content. Even if the search operators of YouTube are used. If you want to fix that, you might run into rate limiting very quickly, which is also bad. And additionally the performance and experience of the application can suffer from this.

So I would say this is very low priority for the moment, however we are probably open for PR's, but will look at any code regarding this very detailed and critical.

**Comment by Computerlabrat** [comment] 2020-11-06 17:23
Okay, I tried to cut out what I noticed. I think youtube offers it through the site itself by clicking on the three dots and selecting the option you want to do manually, which was part of the reason I suggested the idea. I'm not sure if that bit of info is useful for you or not. I get what you're saying about over blocking, so I don't think having a community shared filter system is ideal compared to seeing the ability to DIYing it similar to how youtube allows the option instead.

**Comment by GilgusMaximus** [comment] 2020-11-07 10:26
Thanks a lot. I appreciate it.
Yes the idea to allow users the blocking of certain channels is something that can be useful. Especially with the missing recommendation system of YouTube that you usually get with an account

**Comment by PrestonN** [comment] 2021-01-15 04:25
This is a duplicate of #95

**Closed by PrestonN** 2021-01-15 04:25 UTC
Labels: enhancement

**Comment by kazekanata** [comment] 2021-06-02 15:19
This is very highly requested by me. I want FreeTube to have simillar way to block video, channel and some keywords like BlockTube extension on Edge Chromium/Firefox. FreeTube will be perfect if it has this feature.

**Comment by cybergazer** [comment] 2024-11-16 01:39
Please reopen, you can block channels but not video, the issue isn't fully resolved
