### ISSUE TITLE
[Feature Request]: Add slash key `\` shortcut to search bar

### ISSUE THREAD

**Issue by anddam** [FreeTubeApp/FreeTube#6352] opened 2024-12-11 12:09 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

YouTube has a `\` slash key shortcut to focus the search bar.

### Proposed Solution

Please add a slash key `\` as additional shortcut (along with `ctrl-l` and `alt-d`) to search, this used to be a Google Web Search default (seems it is not anymore) and is actually a default shortcut on YouTube and other web search engine like DuckDuckGo.

### Alternatives Considered

Not sure what should go here, I might… not use the slash key as shortcut, I guess.

### Issue Labels

ease of use improvement

**Comment by devloberto** [comment] 2024-12-28 19:24
Hey there ✌🏼 I was searching for a shortcut to enter the search bar too.
I tried the common ones `ctrl + k` and `/` (`shift + 7` as well as the numpad `/`).

Since there is already a shortcut implemented to focus the search bar, it should be easy to add more: https://github.com/FreeTubeApp/FreeTube/blob/550ce7739bbee8662042cae148cd8e84ebb5542d/src/renderer/App.js#L354

_Just to phrase an user story:_
As a busy user I don't want to need to leave my keyboard and search for my mouse to select the search box because I don't want to waste my time.

_So I suggest following acceptance criterion:_
Focus the search bar when one of the following shortcuts is typed:
- `ctrl`+`k`
- `shift`+`7` (slash)
- `/` (numpad slash)

---

_I will open a PR_ 🙂

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-28 19:27
We have alt + d and ctrl + l to navigate to the searchbar, see https://docs.freetubeapp.io/usage/keyboard-shortcuts/. I dont see why we need more

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-28 19:48
@devloberto if u create a PR then only create it for the requested shortcut.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-28 19:55
this is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2138

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-28 19:55 UTC
Labels: enhancement, E: ease of use improvement

**Comment by devloberto** [comment] 2024-12-28 20:03
thx for pointing out the duplicate

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-28 20:10
> As far as why some of them were different, there were concerns with the shortcuts that YouTube uses for those with Non US / Standard layouts. Keys like `/` and `>` are mapped differently and more difficult to press on these type of layouts. The alternative that we used for the search bar, `Alt + D` was picked because this was the shortcut that Firefox uses for focusing their search bar and was more accessible across layouts.

Retrieved from https://github.com/FreeTubeApp/FreeTube/issues/2138#issuecomment-1074004577

**Comment by devloberto** [comment] 2024-12-28 20:34
Oh I see! I wondered why `Alt + D` was defined but that makes totally sense 👍🏼 thank you

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-28 20:42
Yeah i totally forgot about the reasons for it too. It was a long time ago haha

**Comment by anddam** [comment] 2024-12-30 11:27
>I dont see why we need more

The reason for asking was consistency with YT interface that I think is more on point for FreeTube users compared to FF.
