### ISSUE TITLE
[Bug]: Siwtching to fullscreen via double click resets playback speed

### ISSUE THREAD

**Issue by pakoito** [FreeTubeApp/FreeTube#6304] opened 2024-12-07 22:17 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When watching a video
And setting Playback Speed to any value above 1x
And going Fullscreen via double click
Then playback speed resets to 1x

### Expected Behavior

Playback speed should be kept across the fullscreen change

### Issue Labels

feature stopped working

### FreeTube Version

5f9807c

### Operating System Version

Windows 10

### Installation Method

Portable

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.22.0-beta

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-12-08 00:15
Duplicate of #6281

**Closed** 2024-12-08 00:15 UTC
Labels: bug, B: feature stopped working
