### ISSUE TITLE
[Bug]: Shorts tab just shows "Channels with errors" and turning on "hide channel shorts doesn't hide shorts tab

### ISSUE THREAD

**Issue by zBUS-549** [FreeTubeApp/FreeTube#4618] opened 2024-01-29 18:45 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Channel shorts now just say "Channels with errors" instead of loading shorts, and turning on "hide channel shorts" no longer hides the shorts tab. I have tried working around this with the "hide channel shorts" toggle both on and off, with no change in results.

Sometimes, the "channels with errors" issue occurs on the main tab as well. These are usually subscriptions of mine that haven't had new videos uploaded in quite some time, so I just unsubscribe.

### Expected Behavior

1. If "hide channel shorts" is off, shorts should load normally
2. If "hide channel shorts" is on, "SHORTS" tab should not appear on the main page
3. There should be no "channels with errors" on main page

### Issue Labels

API issue, content not loading, feature stopped working, usability issue, visual bug

### FreeTube Version

v0.19.1

### Operating System Version

Windows 10 Pro 22H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

I also haven't done anything about the local API errors I've been getting as they haven't affected my usability of Freetube until now. Should I just reinstall?

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-01-29 19:48
duplicate of #4614

**Closed** 2024-01-29 19:48 UTC
Labels: bug, B: visual, B: content not loading, B: usability, B: feature stopped working, B: API issue
