### ISSUE TITLE
Pause/play overlay on video is way to large.

### ISSUE THREAD

**Issue by Aphexus** [FreeTubeApp/FreeTube#6178] opened 2024-11-16 20:57 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The pause/play overlay is way to large and obscures the video. It was taking up almost 50% of the video. I rescaled the ui and it helped but still. E.g., if there is some text I want to read and pause the video it will block it.

### Proposed Solution

I don't need to see such a thing on the video(even at all(the play button itself should show a pause icon instead if it is paused)).

Likely an optional setting to either change the scale of such things, making them much more transparent or make them smaller and push them to a corner or just get rid of them completely(optionally if one wants).

### Alternatives Considered

Of course

### Issue Labels

ease of use improvement, new optional setting, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-11-16 21:05
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5951

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-11-16 21:05 UTC
Labels: enhancement, E: new optional setting, E: visual improvement, E: ease of use improvement
