### ISSUE TITLE
[Bug]: Navigating the searchbar with keyboard not working

### ISSUE THREAD

**Issue by RagglenLove** [FreeTubeApp/FreeTube#3020] opened 2023-01-01 22:11 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Type a search query on the search bar, e.g. Linux.
2. With your keyboard, attempt to go to "Linux Mint" or "Linux on Android" and it fails to do so.

Attached to this bug report is a video of the bug itself.

https://user-images.githubusercontent.com/45503845/210186003-bf4ecfe2-d92f-4981-a1c4-4313bbc53484.mp4

### Expected Behavior

1. Type a search query on the search bar, e.g. Linux.
2. With your keyboard, you should be able to navigate through the search results and select "Linux Mint" or "Linux on Android".

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Xubuntu 20.04

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-01-02 11:35
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2708

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-01-02 11:35 UTC
Labels: bug, B: inconsistent behavior
