### ISSUE TITLE
[Feature Request]: Video "categories" for discovering new content

### ISSUE THREAD

**Issue by khoin343** [FreeTubeApp/FreeTube#5385] opened 2024-07-10 12:51 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

FreeTube, like other apps, does not include an algorithm that recommends videos to users. This is good in many ways, however it hampers the ability to discover new content, which is one of the reasons people use YouTube in the first place.

### Proposed Solution

A category system that sorts videos into different topics. When users want to watch something new, they can browse topics, click on one they are interested in, and find videos that relate to that topic.

### Alternatives Considered

An algorithm similar to YouTube's algorithm that can be turned on and off. However, there are many problems with this solution, such as privacy concerns, hard to implement, etc.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-10 13:04
This just seems an expansion on https://github.com/FreeTubeApp/FreeTube/issues/677 so im closing it as a duplicate off https://github.com/FreeTubeApp/FreeTube/issues/677

**Closed** 2024-07-10 13:04 UTC
Labels: enhancement, E: new feature
