### ISSUE TITLE
Select Quality Option | Double Resolution Bug

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1952] opened 2021-12-19 23:34 UTC
**Behavior of the program**
When selecting or changing the Resolution Size in the "Select Quality" option, the same resolution appears twice.
This bug appears in every video in the new version 0.15.1 Beta.

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: 0.15.1 beta
 - Installation Method: .exe

**Screenshot**
![FreeTube_Select Quality](https://user-images.githubusercontent.com/96393348/146694674-1c923fb3-e3d4-4fd8-a04c-399ab33bee7d.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-12-20 06:29
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1344

**Closed** 2021-12-20 06:30 UTC
Labels: bug, U: duplicate
