### ISSUE TITLE
Videos always play on 1080p, even after selecting 720p

### ISSUE THREAD

**Issue by SirGorak** [FreeTubeApp/FreeTube#1056] opened 2021-02-24 01:13 UTC
**Behavior of the program**
Video always plays on the highest resolution, 1080p

**Expected behavior**
It should play on 720p, like I selected in the settings

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to settings
2. Click on 720p
3. Play a video
4. It's on 1080p

**Environment Information (please complete the following information):**
 - OS: Ubuntu
 - OS Version: KDE Neon 5.21
 - FreeTube version: 0.11.3 beta
 - Installation Method (If applicable): Flathub
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment] 2021-02-24 19:06
As mentioned on other issues, this is related to what VideoJS and the video streaming plugin do under the hood. It is, in terms of reason to occur, a duplicate of #595

**Closed by GilgusMaximus** 2021-02-24 19:06 UTC
Labels: bug
