### ISSUE TITLE
Some videos fail to load with The "url" argument must be of type string.

### ISSUE THREAD

**Issue by thansk** [FreeTubeApp/FreeTube#745] opened 2020-10-30 08:37 UTC
**Behavior of the program**
A lot of videos when clicked on produce this error:
`TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined`

**Expected behavior**
Video should load without an error.

**To Reproduce**
1. Search for `nexpo` or `vsauce`
2. Click on a video

Also works when clicking a video from subscriptions or any other place

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 20.04 
 - FreeTube version: 0.9.1
 - FreeTube build: Release

**Comment by GilgusMaximus** [comment] 2020-10-30 10:26
Closing. Duplicate of #733

**Closed by GilgusMaximus** 2020-10-30 10:26 UTC
Labels: bug
