### ISSUE TITLE
[Bug]: Blank screen after removing search query

### ISSUE THREAD

**Issue by DankstoneMC** [FreeTubeApp/FreeTube#6295] opened 2024-12-07 09:26 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open app on Windows PC
2. Type a something into the search bar
3. Delete the things typed
4. Type something again
5. App now goes blank (not consistent but if done enough times it will go blank)

https://github.com/user-attachments/assets/b4ae1f3f-02ad-4e3c-842c-219ff80a0d2d

### Expected Behavior

The app shouldn't go blank

### Issue Labels

causes crash, content not loading

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Windows 11 Pro 23H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-07 09:30
Im unable to reproduce this one. Could you do the following:

1. Open FreeTube
2. Open dev tools, ctrl + shift +i
3. Reproduce the bug
4. Check if there are red errors popping up in the console

**Comment by DankstoneMC** [comment] 2024-12-07 09:41
It says that the DevTools just disconnects and nothing shows up
![image](https://github.com/user-attachments/assets/6a75f287-a726-4de4-913b-51dbd5ed1e50)

**Comment by absidue** [comment] 2024-12-07 09:44
Duplicate of #6065

Please check both open and closed issues next time.

**Closed** 2024-12-07 09:45 UTC
Labels: bug, U: duplicate, B: content not loading, B: crash

**Comment by KnowledgeMC** [comment] 2024-12-10 00:38
I just wanted to chime in and say that I am also experiencing this exact issue, but on Mac OS Sequoia 15.1.1, instead of Windows like OP.

Latest Release of FreeTube v. 0.22.0

For anyone experiencing the same, try reloading via CMD + R. It seems to reload the page.
