### ISSUE TITLE
[Feature Request]: prevent autoplaying previously played videos

### ISSUE THREAD

**Issue by dev-stupid-codes** [FreeTubeApp/FreeTube#2843] opened 2022-11-08 18:58 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

FreeTube keeps replaying the same song every other autoplay.

1. start listening to "Gorillaz - Clint Eastwood"
2. song ends
3. another related song plays
4. it's very likely you'll be back to "Gorillaz - Clint Eastwood"

### Proposed Solution

I'm assuming this is not a problem at your end, since NewPipe also faces the same issue.

What I think we could do is:

1. video starts playing
2. freetube stores video ID in a list
3. video ends
3. fetch next related videos
4. filter out next videos based on IDs in list
5. plays next video

This feature would require to be enabled in privacy settings (disabled by default).

### Alternatives Considered

Always play the second next related video.

### Issue Labels

ease of use improvement, new feature, new optional setting

**Comment by dev-stupid-codes** [comment] 2022-11-08 19:11
I'm not sure if that's how autoplay works, but I guess you can get the gist.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-11-09 06:06
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/397

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-11-09 06:06 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement, E: new feature
