### ISSUE TITLE
Keep getting "The "url" argument must be of type string. Received type undefined" error whenever I try to watch a video on LocalAPI

### ISSUE THREAD

**Issue by JustYourAverageGithubUser** [FreeTubeApp/FreeTube#749] opened 2020-10-30 22:02 UTC
**Important note**
Please check other open and closed issues for a similar bug before reporting a new one. 

**Behavior of the program**
Please write a clear and concise description of what the bug is.

Whenever I click on a video about 85% of the time I get the error: "TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined" and the video refuses to load. This is with subscriptions, most popular and search result videos

**Expected behavior**
Please describe clear and concise what you expected to happen.

Video to load properly without an error message.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Set API Preference to "LocalAPI"
2. Go to any video
3. See error large portion of the time.

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - OS Version: Rolling Release (Can't find specific OS version number)
 - FreeTube version: v0.9.1.2 Beta
 - FreeTube build: Release I believe, though I'm unsure as I installed through AUR.

**Additional context**
If you switch to Invidious API the problem is resolved but than subscription refreshing breaks because LocalAPI handles that far better.

**Comment by PrestonN** [comment] 2020-10-30 22:22
Duplicate of #733

**Closed** 2020-10-30 22:22 UTC
Labels: bug
