### ISSUE TITLE
[Feature Request]: Adjust video buffer size

### ISSUE THREAD

**Issue by Augusto7743** [FreeTubeApp/FreeTube#4766] opened 2024-03-14 23:19 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

For users using metered is problem the large buffer cache used for some videos.
Have times the user only want see commentaries and few moments of video.

### Proposed Solution

An option in settings for select the default buffer size for videos in seconds or in video player an button to change the buffer timer.

### Alternatives Considered

I see another user topic saying about it, but not say about buffer time having several values in settings or in player button.

https://github.com/FreeTubeApp/FreeTube/issues/678

### Issue Labels

new feature

### Additional Information

Thanks for reading my topic.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-03-15 00:29
Doesnt matter if that issue isnt talking about it the devs know what is needed to implement this. Feel free to add extra info to that issue. 

Duplicate of #678

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-03-15 00:29 UTC
Labels: enhancement, E: new feature
