### ISSUE TITLE
[Bug]: Sponsorblock: Multiple segments are not skipped

### ISSUE THREAD

**Issue by stdedos** [FreeTubeApp/FreeTube#5164] opened 2024-05-24 07:20 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

For e.g. https://www.youtube.com/watch?v=8ToZrR1m5ss, Non-Music is skipped, but End-Credits not

All segments are set to auto-skip

### Expected Behavior

Both segments are skipped

### Issue Labels

inconsistent behavior, race condition, usability issue

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Ubuntu 20.04.6

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

- https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+sponsorblock+multiple+segments

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-24 07:42
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3534

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-05-24 07:42 UTC
Labels: bug, B: usability, B: inconsistent behavior, B: race condition

**Comment by stdedos** [comment] 2024-05-24 07:55
Could you maybe amend the bot to close _these tickets_ as not-planned?
