### ISSUE TITLE
[Feature Request]: Filtering out Shorts

### ISSUE THREAD

**Issue by rsankar94** [FreeTubeApp/FreeTube#3594] opened 2023-05-28 03:10 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Looks like many YouTube content creators are leaning towards shorts. That's great, but it's annoying to see my feed with a bunch of shorts.

Can there be a filter for not loading shorts in the video feed?

### Proposed Solution

Filter to eliminate videos <1 minute in length from showing in the feed

### Alternatives Considered

But, with the ability to see shorts separately when clicking on the specific channel?

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-05-28 07:32
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2008

**Closed** 2023-05-28 07:32 UTC
Labels: enhancement, E: new optional setting
