### ISSUE TITLE
[Feature Request]: add progress bar in live stream.

### ISSUE THREAD

**Issue by Jayavi11** [FreeTubeApp/FreeTube#4932] opened 2024-04-12 14:04 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

hi could you add progress bar in Live. while watching livestreams I'm unable to move backwards in stream.

### Proposed Solution

Add progress bar in live streams.

### Alternatives Considered

Add any way to view past minutes  in progress bar

### Issue Labels

new feature

### Additional Information

hi could you add progress bar in Live. while watching livestreams I'm unable to move backwards in stream.

**Comment by absidue** [comment] 2024-04-12 14:14
duplicate of #661

**Closed** 2024-04-12 14:14 UTC
Labels: enhancement, E: new feature
