### ISSUE TITLE
[Bug]: Cannot download videos. "Access to rr1---sn-a5m7lnld.googlevideo.com was denied" Error 404

### ISSUE THREAD

**Issue by javierxio** [FreeTubeApp/FreeTube#6347] opened 2024-12-11 03:00 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to any video. e.g. https://youtu.be/Cpstwe24eLk
2. Click "Download Video"
3. Choose format. e.g. 360p 24fps video/mp4
4. Browser window opens up with 403 error

This was recently working fine until about a day or two ago.

Complete error from website:

Access to rr1---sn-a5m7lnld.googlevideo.com was denied
You don't have the user rights to view this page.
HTTP ERROR 403

url:

https://rr1---sn-a5m7lnld.googlevideo.com/videoplayback?expire=1733907150&ei=bv5YZ6eNHvbXsfIPzPq_yQU&ip=&id=o-ADhVB6rs4P4CcyME1OnLnrT4iL5bcpW4Q_mFT2UyiA7T&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1733885550%2C&mh=rV&mm=31%2C26&mn=sn-a5m7lnld%2Csn-o097znsr&ms=au%2Conr&mv=m&mvi=1&pl=21&rms=au%2Cau&initcwndbps=3196250&bui=AQn3pFRU3L0kwFD6T6JCr4uCZhgkz7J6JATIr_iFxLD44SBHNxMLGl3rUfYCfsGVvni0uALCEHdW0CIY&spc=qtApAcDKoGU5p-7kjn4chV2KlHAkxcIn97eRZZSEmIrkEDdRYDHl89aSsxu7rF9rAQ&vprv=1&svpuc=1&mime=video%2Fmp4&ns=f-Zt0lKEIcQ4YVYR2l5x3w8Q&rqh=1&gir=yes&clen=43699067&ratebypass=yes&dur=707.303&lmt=1733868188815500&mt=1733885109&fvip=5&fexp=51326932%2C51335594%2C51347747%2C51355912&c=WEB&sefc=1&txp=5538434&n=NcoW5fnckZEsobP70&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIgRDS6dRpo_DOSdmZiKzByF0xw-UJwFePh5lQuHRmOmfACIQDW19GY9L7osnME5maqUp7UGyvciO9lRbmCywbRScZWag%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRgIhAI403EGCVBek11tQWKveWQV5cz_nDkJUlWLjo_0ophr3AiEAu4UR916RXqYU06zUKCkRzaYygasfGyLIr8Kgfp9JNkY%3D&cver=2.20240111.09.00

### Expected Behavior

Should be able to download video. For reference, Newpipe android app is still able to download videos.

### Issue Labels

feature stopped working

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Win 11

### Installation Method

.zip

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.22.0 Beta

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by javierxio** [comment] 2024-12-11 03:00
![image](https://github.com/user-attachments/assets/e15932ea-3fa6-47d5-90e3-b20e99f5053e)

**Comment by absidue** [comment] 2024-12-11 05:19
Duplicate of #6328

**Closed** 2024-12-11 05:19 UTC
Labels: bug, B: feature stopped working
