### ISSUE TITLE
[Top Priority] Implement multiple tabs, bookmarks and history components

### ISSUE THREAD

**Issue by Aikatsui** [FreeTubeApp/FreeTube#930] opened 2021-01-15 10:17 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
This is a request for @PrestonN to work for implement below parts now, kindly postpone the rest unless has any barrier
- Multiple tabs and open in new tab
- Bookmark tabs, bookmark all and bookmark page or window similar chrome
- History window (including ability to open in tab from history and clear history)

Just address above mentioned major (must have) requirements, since this project released compiled version few years ago(2018), i still have to give-up and use web browser often  

**Additional context**
https://github.com/FreeTubeApp/FreeTube/issues/539

**Comment by PrestonN** [comment] 2021-01-15 15:22
Duplicate of #333

**Closed by PrestonN** 2021-01-15 15:22 UTC
Labels: enhancement

**Comment by Aikatsui** [comment] 2021-01-15 17:24
I know that #333 and those issues mentioned on #539 its okey to close, i wanted to inform
In this cause, that's different request for you :)
