### ISSUE TITLE
Browser instance

### ISSUE THREAD

**Issue by UltraBlackLinux** [FreeTubeApp/FreeTube#1882] opened 2021-11-09 19:16 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I love the Idea of freetube, and would like to use it, but I am pretty much always using my browser anyways, so a separate program is pretty redundant for my use case.

**Describe the solution you'd like to see implemented**
I would prefer a browser instance over the desktop app. Yes, I know invidious, but it's [google login is broken](https://github.com/iv-org/invidious/issues/754) and I would like to move my subscriptions over (and maybe sync them)

**Describe alternatives you've considered**
The partially broken invidious is my only alternative that I can think of.

I am sorry, if this issue is a duplicate. The github search is way too inaccurate at this point, and I would have to look through so many issues.

**Comment by peepopoggers** [comment] 2021-11-09 19:18
Interesting idea. I am pretty sure this is very possible unless the browser makes the codespace face problems

**Comment by PrestonN** [comment] 2021-11-10 02:11
Duplicate of #633

Also, we will never implement syncing through a Google account, as that defeats the scope of the application. We may introduce syncing through other methods though, which already have respective issues.

**Closed by PrestonN** 2021-11-10 02:11 UTC
Labels: enhancement
