### ISSUE TITLE
[Feature Request]: Remove or minimize the HUGE pause button while in viewing mode.

### ISSUE THREAD

**Issue by PxBCPG** [FreeTubeApp/FreeTube#6182] opened 2024-11-17 16:56 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

With the new design of FreeTube, there is a huuuuge pause button displayed in the middle of the screen each time you move your cursor or that you pause your video. 

### Proposed Solution

Remove the pause button when moving the cursor (as with the old version of FreeTube) and only display it when the video is in pause. 
Maybe add a setting for removing this button entirely (sometime you just want to take screenshot and you can't because there is this huge button in front of what you were targeting ^^)

### Alternatives Considered

-

### Issue Labels

visual improvement

### Additional Information

<img width="990" alt="Screen Shot 2024-11-17 at 17 56 36" src="https://github.com/user-attachments/assets/b232b0d2-8429-4518-a65b-b17890502d52">

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-11-17 17:12
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5951

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-11-17 17:12 UTC
Labels: enhancement, E: visual improvement
