### ISSUE TITLE
[MacOS] Persistent Full Screen window state after closing and re-launching the app

### ISSUE THREAD

**Issue by lothar-cell** [FreeTubeApp/FreeTube#1535] opened 2021-07-22 09:16 UTC
I mean the app window itself, and not the video full screen. This would come very handy and shouldn't be hard to implement.
Some apps use this feature already, like Spotify for example. Once its window is set to Full Screen, it stays that way until it is changed. (this was a feature request:)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-22 13:36
@GilgusMaximus isnt this a duplicate of 

https://github.com/FreeTubeApp/FreeTube/issues/1446#issuecomment-867839878

?

**Comment by SebTota** [comment] 2021-07-22 13:53
This issue seems to be asking for the application itself to open in full screen, rather than just the video itself.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-22 13:58
Ah yes my bad i didnt read

**Comment by GilgusMaximus** [comment] 2021-07-23 16:58
Can anyone with a Mac confirm this issue?

**Comment by SebTota** [comment] 2021-07-23 17:25
Yes, I can confirm that this is an issue on Mac. 
Mac OS Big Sur 11.4

**Comment by lothar-cell** [comment] 2021-12-16 11:27
To be fair, I don't think this is a bug, but an optional feature of the MacOS framework. Because some native Apple apps keep staying in full screen when re-launched, like Mail.app for example, yet some others don't, like Reminders.app.
The same is true for 3rd party apps: Spotify, [SounCleod](https://github.com/salomvary/soundcleod) keeps it, [MixCloud Play](https://github.com/uffou/MixCloud-Play), FreeTube, [YT Music](https://github.com/steve228uk/YouTube-Music) client doesn't.

Maybe it would be easy to compare the relevant code with the one in SoundCleod, since it is open source too.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-18 22:51
@PikachuEXE what is you take on this?

**Comment by PikachuEXE** [comment] 2022-08-19 09:50
I rarely use full screen mode (not even multiple desktops) on MacOS
But anyway opened #2495

**Closed** 2022-09-20 12:49 UTC
Labels: bug, OS: macos, U: doesn't follow template
