### ISSUE TITLE
[Feature Request]: Is the big damn play/pause button in the middle of the video necessary?

### ISSUE THREAD

**Issue by robgazy** [FreeTubeApp/FreeTube#6116] opened 2024-11-07 23:43 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When I pause a video, there's a big damn play/pause button in the middle of the video

### Proposed Solution

Get rid of the big damn play/pause button in the middle of the video

### Alternatives Considered

Anything that does not block the video

### Issue Labels

visual improvement

### Additional Information

I'm watching NetworkChuck and want to see what his massive GPU is, but when I puase the video to see, all I can see is a big damn play/pause button in the middle of the video
![H24vLVz5v2](https://github.com/user-attachments/assets/304fd7a3-1def-4f42-a372-8e3d3f95e99b)

**Comment by Solanum95** [comment] 2024-11-08 01:04
Go to settings > Player > Display Play Button In Video Player and disable it :)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-11-08 01:22
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5951

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-11-08 01:22 UTC
Labels: enhancement, E: visual improvement
