### ISSUE TITLE
[Bug]: Doesn't save the state of the previous page

### ISSUE THREAD

**Issue by Johndjk** [FreeTubeApp/FreeTube#4465] opened 2023-12-17 18:31 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When I decide to follow a channel, I scroll down to the first video (depending on the channel, this can take a while), but when I return to the page to watch the next one, it went back to the top again and I have to go back to the beginning every time and this is very exhausting

### Expected Behavior

After watching the first video of the channel and returning to the page, it will be the one that was previously open (the one at the beginning of the channel)

### Issue Labels

usability issue

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Pop!_OS 22.04 LTS

### Installation Method

Flathub

### Primary API used

Local API

### Additional Information

https://github.com/FreeTubeApp/FreeTube/assets/154085819/ae55f4eb-c817-4955-8d1f-97b7ceca255f

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-12-17 20:11
Duplicate of #2446

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-12-17 20:11 UTC
Labels: bug, B: usability
