### ISSUE TITLE
[Bug]: Video has longer duration and audio is not in sync with video.

### ISSUE THREAD

**Issue by SkyTheGreatOne** [FreeTubeApp/FreeTube#2410] opened 2022-07-21 22:21 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

This video is 5 minutes longer in duration than it is when loading it on the Youtube website. On FreeTube, the video in the first few minutes shows the creator setting up the presentation but is playing audio as if the presentation is already started. On Youtube the video is already at the presentation.

Copy and paste link into browser and FreeTube and compare.
https://youtu.be/busHtSyx2-w

### Expected Behavior

The video was expected to load correctly with 9 minutes and 48 seconds, without showing the creator setting up their screen recorder.

### Issue Labels

usability issue

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Linux Mint 20.3 Cinnamon

### Installation Method

.AppImage

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by GilgusMaximus** [comment] 2022-07-23 12:13
Could you try out the new nightly builds? I cannot reproduce it there :)

**Comment by SkyTheGreatOne** [comment] 2022-07-24 01:40
I just tried it on the latest nightly build, (v0.17.0-nightly-1838 Beta) as an AppImage file. The issue is still present.

![image](https://user-images.githubusercontent.com/87588105/180628614-beb86e7d-48fd-4c1d-bdc9-fcb24eb355d3.png)

**Comment by absidue** [comment] 2022-07-29 11:22
@SkyTheGreatOne It looks like that specific video is corrupted/broken on the YouTube website as well. So this is definitely not a FreeTube specific issue so we probably won't be able to fix it on our end.

As you can see on the screenshot the progress bar shows that it's almost at the end of the video, however according to the duration and current playback position numbers there are another 5 minutes remaining. When it reaches the end of the progress bar it just loads endlessly.
![broken-video](https://user-images.githubusercontent.com/48293849/181747982-dd8f8856-5eaa-4419-9297-eaf98d46ac03.jpg)

endlessly loading:
![broken-video-end](https://user-images.githubusercontent.com/48293849/181748576-215e1fc0-6fda-47f8-91ea-28f2fa7337c2.jpg)

I recommend getting in touch with the creator of the video and seeing if they can fix it.

**Comment by absidue** [comment] 2022-07-29 11:23
Closing this as it looks like the problem is on YouTube's end, happy to reopen it in the future if it gets fixed on YouTube but is still broken in FreeTube.

**Closed by absidue** 2022-07-29 11:23 UTC
Labels: bug, wontfix, third-party, B: usability
