### ISSUE TITLE
[Feature] Add auto dark/light mode based on system theme settings

### ISSUE THREAD

**Issue by axeII** [FreeTubeApp/FreeTube#1408] opened 2021-06-13 14:48 UTC
**Describe the solution you'd like to see implemented**
FreeTube already has dark and light mode I would wish there was another option called system theme. This option would set light or dark mode based on system settings.

**Describe alternatives you've considered**
Using javascript or css it should be simple to detect system [theme](https://stackoverflow.com/questions/56393880/how-do-i-detect-dark-mode-using-javascript). 

Please add this feature to freetube 🙏🏻 it's very annoying to switch themes all the time.
Cheers.

**Comment by GilgusMaximus** [comment] 2021-06-13 14:57
duplicate of #691

**Closed by GilgusMaximus** 2021-06-13 14:57 UTC
Labels: enhancement
