### ISSUE TITLE
"Up Next" Autoplay sometimes loops

### ISSUE THREAD

**Issue by Tiltowait2** [FreeTubeApp/FreeTube#1443] opened 2021-06-24 02:18 UTC
Sometimes I like to go to sleep listening to podcasts.  I'll check "Autoplay" to let it run all night.  The first video will come to an end and play the video it decides fits best next.  Unfortunately, sometimes the software will decide that the best match to *that* video is the one I just watched.  Then it will loop, playing the same two videos.

Suggested behavior: once a video has been played in "Autoplay" mode, it may not be played again.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-06-24 12:55
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/397

**Comment by GilgusMaximus** [comment] 2021-06-24 17:48
That is correct

**Closed by GilgusMaximus** 2021-06-24 17:48 UTC
