### ISSUE TITLE
Adding "Not Interested" option to Subscriptions page

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1967] opened 2021-12-29 05:55 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Implementation of a "Not Interested" option similar to the YouTube Homepage (recommendation page), for removing the selected video from the subscriptions page and possibility of filtering the similar genre or topic in future refresh if applicable.

**Describe the solution you'd like to see implemented**
N/A

**Screenshots**
![vivaldi_T28M33FrvX](https://user-images.githubusercontent.com/96393348/147631379-eb748749-56bc-4acd-9e1f-0cc42d334772.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-12-29 12:37
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1577

**Closed** 2021-12-29 12:37 UTC
Labels: U: duplicate, enhancement

**Comment by bachig26** [comment] 2021-12-29 13:11
> Duplicate of #1577

this issue that you have mentioned as a duplicate for, is completely looks different from the way it is presented.

my idea of this issue is filtering based on the personal dislikes of a video to be filtered based on a similar theme or genre, but issue #1577 is completely opposite as it interprets to remove or hide the complete channel from the subscriptions page.
if that was the issue, then I just can unsubscribe to the channel itself and not have this feature.

additionally with the issue that I have engaged here is to filter the contents from every channel in the future that I may or may not be subscribing to.

If you read and compare my interest here and issue #1577, you will understand better. I myself wondering your point of view for labeling my issue #1967 as a duplicate.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-12-29 14:10
Apologies copied the wrong issue 

Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1362
