### ISSUE TITLE
YouTube playlist to FreeTube playlist with auto update/sync function

### ISSUE THREAD

**Issue by admin-ll55** [FreeTubeApp/FreeTube#1198] opened 2021-04-15 04:42 UTC
Simply importing a YouTube playlist to FreeTube with an auto-update/sync function.
Reason behind this idea: I still want to manage playlists with my YT account while looping them with FT so I don't have to paste the playlist link every time.

**Comment by GilgusMaximus** [comment] 2021-04-15 17:36
This is basically subscribing to playlists. For private playlists there won't be any way to do this.
Therefore I am closing this as duplicate of #312

**Closed by GilgusMaximus** 2021-04-15 17:36 UTC
Labels: enhancement
