### ISSUE TITLE
[Feature Request]: Reload Button

### ISSUE THREAD

**Issue by b2ag** [FreeTubeApp/FreeTube#6201] opened 2024-11-21 04:43 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request. (and a minor bug report)

### Problem Description

I sometimes find myself in the need of a reload function. Currently I click `back` and `forward` or click the channel and `back`. By the way quickly clicking `back` and `forward` almost always results in a race condition where the "back video" is loaded in place of the "forward video" (and playback position of "forward video" is applied to "back video").

### Proposed Solution

Add a `reload` button next to `back` and `forward` buttons. And maybe fix the race condition if there is time to spare.

### Alternatives Considered

Sticking to the old "back and forward" dance.

### Issue Labels

ease of use improvement

### Additional Information

Affects all versions I used so far, which are some since some years.
AppImage, Pipewire and (but race condition seems not limited to following to me) NixOS unstable, Wayland and NVIDA

If generating to much sus traffic by abusing the reload button is a potential issue, I'd be fine with a cooldown  function being attached to it.

**Comment by absidue** [comment] 2024-11-21 05:17
Duplicate of #1005

**Closed** 2024-11-21 05:18 UTC
Labels: U: duplicate, enhancement, B: race condition, E: ease of use improvement
