### ISSUE TITLE
No video's duration on Subscriptions page

### ISSUE THREAD

**Issue by marcqw** [FreeTubeApp/FreeTube#1740] opened 2021-09-23 08:58 UTC
**Behavior of the program**
Don't have video's duration display on the subscriptions page.

**Expected behavior**
Video's duration caps as it is on other page.

**To Reproduce**
Go to subscription page.

**Screenshots**
Without duration on subscription page
<a href="https://imgbb.com/"><img src="https://i.ibb.co/VYhvV3K/Screenshot-from-2021-09-23-10-52-59.png" alt="Screenshot-from-2021-09-23-10-52-59" border="0"></a>
With duration on others freetube page
<a href="https://imgbb.com/"><img src="https://i.ibb.co/vZ3L0FM/Screenshot-from-2021-09-23-10-53-37.png" alt="Screenshot-from-2021-09-23-10-53-37" border="0"></a>

**Environment Information (please complete the following information):**
 - OS: Manjaro
 - OS Version: 21.1.3 with Gnome 40.4.0 / Wayland
 - FreeTube version: v0.14.0 Bêta
 - Installation Method (If applicable): AUR : https://aur.archlinux.org/packages/freetube
 - Primary API Used: Local API

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-23 12:02
Hi @marcqw this is not a bug. Durations are already shown on the thumbnail of a video. If you're not seeing the duration in your videos, then that likely means that you're using RSS for grabbing subscriptions. While RSS is faster and prevents rate limiting, it doesn't provide all of the typical information such as video duration. There's nothing that can be done about this.

You can to the subscription settings in the settings menu to disable 'Fetch feeds from RSS'

This issue is also a duplicate of #638 and #587. 

I'll be closing this to prevent cluttering the backlog.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-09-23 12:02 UTC
Labels: bug, duplicate

**Comment by marcqw** [comment] 2021-09-23 14:09
It's good for me. Many thanks for this information.
