### ISSUE TITLE
[Feature Request]: Fix Favorites - add Grid layout & Sorting & search for playlists, ability to favorite playlists

### ISSUE THREAD

**Issue by JIGASHI** [FreeTubeApp/FreeTube#5097] opened 2024-05-11 11:10 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

This is useless the way it is right now. The lack of grid layout, search & sorting functionality for playlists, as well as no section where you can store/favorite playlists.

### Proposed Solution

Add the grid layout, make use of all the screen space within the app window, and add sorting options (like the drop down from the "Your playlists" defaulting to the latest added videos. And an ability to search all & within each playlist for videos.

And another thing would be to add the ability to favorite playlists, in a separate place. So favorite playlists, but not unpacked, they are displayed as playlists kind of like folders.

### Alternatives Considered

...

### Issue Labels

ease of use improvement, improvement to existing feature, new feature, new optional setting, visual improvement

### Additional Information

....

**Comment by absidue** [comment] 2024-05-11 11:51
Closing as this is a duplicate of existing open issues and secondly because you didn't follow the rules in the template and requested multiple things in one issue and deleted that part of the template to try and cover up your tracks.

> This issue contains only one feature request.

**Closed by absidue** 2024-05-11 11:51 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: visual improvement, E: ease of use improvement, E: new feature

**Comment by JIGASHI** [comment] 2024-05-11 13:02
You wrongfully assumed and attributed intent.

**Comment by absidue** [comment] 2024-05-11 13:12
Do you have a different explanation as to why you deleted a mandatory part of the template and then decided to request multiple things in the same issue anyway?

**Comment by JIGASHI** [comment] 2024-06-03 22:21
Yes, but nothing which makes you deserving of it.
