### ISSUE TITLE
Search failure causes filters to be ignored

### ISSUE THREAD

**Issue by Winterhuman** [FreeTubeApp/FreeTube#2179] opened 2022-04-09 18:39 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Search "libp2p" or "ipfs" with the search filter set to "Upload Date"
2. Observe `Error: Client network socket disconnected before secure TLS connection was established`, either by searching twice or letting it fail by itself, and that the results aren't ordered by upload date as they should be.

### Expected Behavior

Search filters should always correctly filter videos.

### Issue Labels

feature stopped working

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Arch Linux

### Installation Method (If applicable)

Flathub

### Last Known Working FreeTube Version (If Any)

Unknown

### Primary API used

Local API

### Additional Information

I have a screenshot, but GitHub says "Something went really wrong..." and won't let me upload it.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-04-09 19:49
cant reproduce on the latest nightly build

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-04-09 20:06
could u provide other examples?

**Comment by Winterhuman** [comment] 2022-04-09 20:28
Managed to do a filtered search without encountering https://github.com/FreeTubeApp/FreeTube/issues/1939 (I have no idea why FreeTube decides not to do this only sometimes), and the ordering for "libp2p" is correct now; interrupting the search by hitting enter while the search is loading is the cause.

**Comment by Winterhuman** [comment] 2022-04-09 20:29
This would technically be solved if https://github.com/FreeTubeApp/FreeTube/issues/1939 was fixed, but, ideally hitting enter twice shouldn't interrupt the search and should continue uninterrupted.

**Comment by Winterhuman** [comment] 2022-08-01 14:11
Looks like the search changes have fixed this issue; I can't replicate this issue anymore in v0.17, yay!

Closing issue

**Comment by Winterhuman** [comment] 2022-08-01 14:11
Wait no sorry, I was thinking of https://github.com/FreeTubeApp/FreeTube/issues/1939

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-16 00:26
@Winterhuman is this still an issue ur facing?

**Comment by Winterhuman** [comment] 2022-08-16 13:15
I can't reproduce it technically, but that's only because I can't figure out how to trigger a search failure; the search is too reliable now (not exactly a bad issue though). Without the failures, I can't verify if they cause search filters to be ignored still

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-16 14:08
Because it isn't reproduceable I'm going to close it. Feel free to comment when u can reproduce it.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-08-16 14:08 UTC
Labels: bug, B: feature stopped working
