### ISSUE TITLE
Cannot import JSON subscriptions, indicator stuck

### ISSUE THREAD

**Issue by andrejdam** [FreeTubeApp/FreeTube#1168] opened 2021-04-06 10:03 UTC
Hi there,

Before doing a system reinstall I exported my subscriptions to a .json file. Now when I try to import them the coloured line at the bottom that indicates import progress is stuck somewhere about 70%. Leaving it be for some time doesn't resolve the situation.

Is there a way to fix some problematic entry inside, or convert the .json to a .db, so that I can import my subscriptions? It's a really large list so I'd avoid doing it manually.

Regards,
A

**Comment by GilgusMaximus** [comment] 2021-04-06 18:38
So, what has happened here is that you exported it either as Youtube or NewPipe json.
![image](https://user-images.githubusercontent.com/34301369/113761494-d0ea7380-9717-11eb-811b-ebd65a7b95d5.png)

Now you'll have to import it in there and then export it again so you can import it. That is also the reason why .db files are mentioned as FreeTube. Please let me know whether that worked.

But I have to admit it is a bit inconsistent that you cannot simply reimport these files. Would be a good future feature.

**Comment by andrejdam** [comment] 2021-04-06 20:26
Hi, thanks for you reply. By 'import it in there' do you mean import it inside FreeTube, but as the specified type? I'll try this later. 

If you think about importing it to YouTube and reexporting it, I think it would be both impossible (I believe YouTube removed the option to export subscriptions) and I'd try to avoid it if possible.

**Comment by andrejdam** [comment] 2021-04-06 20:34
OK, so here's the error message:

> Falling back to Invidious API
> TypeError: Cannot read property 'title' of undefined

**Comment by Svallinn** [comment] 2021-04-07 03:02
There's either a channel that has been made unavailable/shutdown in your subscriptions or you might have a topic channel in your list and I believe FreeTube can't deal with that atm (I'm not 100% about this scenario, all I know is that accessing a topic channel with the module as it is now fails, I'm not sure if that's what's being used by the importing tool)

**Comment by Svallinn** [comment] 2021-04-27 14:12
Is this still happening in the latest nightly?

**Comment by avion540** [comment] 2021-05-04 21:22
With the latest nightly (788), it is no longer getting stuck on `TypeError: Cannot read property 'tabRenderer' of undefined`, but it is now getting stuck on `TypeError: Cannot read property 'title' of undefined` or `Error: Request failed with status code 429` when Preferred API Backend is set to Local API. The errors don't happen when set to Invidious API, but the subscriptions never finish importing for me. I am attempting to import an opml (for FreeTube) from an Invidious instance.

**Comment by Svallinn** [comment] 2021-05-04 23:06
Pretty sure you are simply rate-limited (429) and/or using certain broken Invidious instances when it falls back from the Local API (due to the rate-limiting).
Well... it's been a week. I'll close this for now. You're welcome to comment here again if it turns out I'm wrong or something.

**Closed by Svallinn** 2021-05-04 23:06 UTC
Labels: bug

**Comment by 6-AND-9** [comment] 2021-05-20 20:28
Sorry for not responding earlier. I think the issue is fixed now, even though I still get error messages while importing.
