### ISSUE TITLE
[Feature Request]: A shortcut/keystroke for SponsorBlock that will skip section

### ISSUE THREAD

**Issue by cra3yk** [FreeTubeApp/FreeTube#6017] opened 2024-10-29 17:38 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hi.

The SponsorBlock extension, when installed in browser, allow to configure sections to be:
- autoskip
- manually skip (by keyboard keystroke/shortcut)
- show in Seek Bar
- do not show/do nothing.

I'm usually have configured "Self-Promotion" and "Interaction" to manually skip, because (it depends on channel) some have a nice one (like Vila la Dirt Leagune), some don't.
In FreeTube there is no "manually skip" option nor dedicated keystroke/shortcut.

Please mention to add this functionality.
Thanks!

![categories-sponsorblock-list](https://github.com/user-attachments/assets/56b15add-65c6-4a6a-b450-a7b788e3ed12)

### Proposed Solution

Add ability and keyboard shortcut/keystroke to manually skip section.

### Alternatives Considered

nothing.

### Issue Labels

improvement to existing feature, new keyboard shortcut

**Comment by absidue** [comment] 2024-10-29 17:50
Duplicate of #1380

**Closed by absidue** 2024-10-29 17:50 UTC
Labels: enhancement, E: improvement existing feature, E: keyboard shortcut
