### ISSUE TITLE
Adjusting volume with scroll wheel is not working.

### ISSUE THREAD

**Issue by wildcard-f8** [FreeTubeApp/FreeTube#573] opened 2020-10-04 04:11 UTC
**Behavior of the program**
When I hover over the volume and try to adjust it with the scroll wheel it just scrolls the page. I've read in a closed issue that this feature was supposed have been implemented.

**Expected behavior**
Hovering over the volume and using the scroll wheel should increase/decrease volume.

**To Reproduce**
1. Open video
2. Hover over volume bar
3. Scroll up or down

**Desktop (please complete the following information):**
 - OS: Manjaro
 - OS Version: 20.1.1 Mikah
 - FreeTube version: v0.8.0 Beta

**Comment by GilgusMaximus** [comment] 2020-10-04 09:36
Yes. You probably saw that in #309.
However these old issues were all related to the old FreeTube. So this must be implemented again.

**Comment by TDDR** [comment] 2020-10-04 13:51
Hello, I just found this app by browsing the trending topics in Github. First off, love the idea of the app in general. I have been trying to get away from google's trackers for some time now so this is a great alternative!

Second, I would like to be assigned this issue. I am new to contributing and feel like this would be a good issue for me to tackle that's not something mundane like writing documentation.

**Comment by PrestonN** [comment] 2020-10-04 18:41
Hello!  Feel free to work on this if this is something you'd like to take a look at.  Let me know if you have any questions about the project.  Thank you so much for wanting to contribute!

**Comment by TDDR** [comment] 2020-10-16 00:25
Hello, just a little update. I have spent some time playing with the code and done some reading of the `video.js` documentation and  I think I figured out a way to implement this feature. I have just been really busy with school, but I do still plan on fixing this!

**Comment by TDDR** [comment] 2020-10-20 15:18
Hello again, I have made some progress and was wondering if I could get some help with the last little bug. Here is my [working branch](https://github.com/TDDR/FreeTube/tree/issue-573) for you to take a look at.

The volume scroll works as expected except for the fact that I actually have to click on the video player in order for it to start to take effect.  I think the problem is that I put the following code in initializePlayer, but I'm not really sure where else to put it.

```js
        this.volumeSelector = this.player.el().querySelector('vjs-volume-menu-button') ||
                             this.player.el().querySelector('vjs-volume-panel')
        if (this.volumeSelector != null) {
          this.volumeSelector.onmouseover = function() {this.volumeHover = true}
          this.volumeSelector.onmouseout = function() {this.volumeHover = false}
        }
```

Any help is appreciated!

**Closed** 2020-10-28 10:48 UTC
Labels: enhancement, good first issue
