### ISSUE TITLE
freetube white screen bug

### ISSUE THREAD

**Issue by daraspul** [FreeTubeApp/FreeTube#1765] opened 2021-09-30 08:38 UTC
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**
as soon as I open the app I can click on all of the buttons  but the screen in the middle where videos/settings would be is blank.
I've reinstalled it multiple times, tried the zip file and nothing works.

**Expected behavior**
not blank screen

**To Reproduce**
Please add all steps to reproduce the behavior:
1.Open Freetube
2.Blank screen

**Link to video**
If you refer to a problem which occurs within a specific video, or a range of videos, please link at least one here.

**Screenshots**
![image](https://user-images.githubusercontent.com/91661216/135417288-18a82c7d-91e1-4c81-ac80-54b2b5767dde.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: 0.14.0
 - Installation Method: .exe and .zip
 - Primary API Used: Invidious API

**Additional context**

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-30 08:45
Hi @daraspul could u make a screenshot of the error log. Ctrl + shift + I

**Comment by daraspul** [comment] 2021-09-30 08:56
> Hi @daraspul could u make a screenshot of the error log. Ctrl + shift + I

![image](https://user-images.githubusercontent.com/91661216/135421077-95d67050-791f-4e45-a04d-7b8e189503ac.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-30 08:59
Just to be sure can u screen the whole log. Its no big deal if it ends up in multiple screen.

**Comment by daraspul** [comment] 2021-09-30 09:00
![image](https://user-images.githubusercontent.com/91661216/135421799-549f49c6-2a77-4521-afa8-e588d20c9676.png)
That?

**Comment by daraspul** [comment] 2021-09-30 09:02
My bad found what you were probably looking for
![image](https://user-images.githubusercontent.com/91661216/135422148-32407405-c4bf-42df-92c7-34f8396046b6.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-30 09:10
Yes that's the one! Ah i see this issue is actually a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1689. There is already a PR for this that should solve this. I'll close this to prevent cluttering the backlog. U can make a comment over in that issue if u want. Thankyou for ur time and creating the screenshots. I needed those to be sure that it was the same issue as the other one. There is a similar looking issue https://github.com/FreeTubeApp/FreeTube/issues/1754 but the error is way different. So needed to rule that out.

**Comment by daraspul** [comment] 2021-09-30 09:11
Ah okay thanks alot

**Closed** 2021-09-30 09:11 UTC
Labels: bug, duplicate
