### ISSUE TITLE
Legacy Format Local API error (click to copy) : typeerror: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by MattRGX** [FreeTubeApp/FreeTube#818] opened 2020-11-30 10:37 UTC
**Behavior of the program**
Can't watch any video at all. If i click on any video of my subsription page, i have this error : 
"Local API error (click to copy) : typeerror: Cannot read property '0' of undefined"

**Expected behavior**
Video playing normally

**To Reproduce**
Please add all steps to reproduce the behavior:
1. install last nightly (v0.9.2-nightly-322 Beta)
2. Click on any video of the subscriptions page
3. See error

**Screenshots**

[image](https://ibb.co/dtrRhFK)

**Environment Information (please complete the following information):**
 - OS: W10 
 - OS Version: W10 19041.508
 - FreeTube version: v0.9.2-nightly-322 Beta
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Additional context**
-----

**Comment by GilgusMaximus** [comment] 2020-11-30 14:12
Hi, so this is weird. I just tried the live stream you provided and it works fine for me.

Could try to search the video and then play it?

**Comment by MattRGX** [comment] 2020-11-30 14:42
thanks for your answer. exactly the same behaviour from the search results with the same error message.
here are my settings :

[Settings 1](https://ibb.co/ss3tqr1)
[Settings 2](https://ibb.co/yVGSZtG)

**Comment by MattRGX** [comment] 2020-12-01 08:41
Hello,
Thanks for your answer.
So i moved to DASH format but i still have the error. the only thing that change is that now i have the player in the good size and not in very small in the corner.

[Picture](https://ibb.co/kStpFZn)

When i click on the play button, nothing happened and it just stays like that (the error message disappear after few seconds)

**Comment by GilgusMaximus** [comment] 2020-12-02 16:32
Thanks for testing. Currently the issue is due to our main module which grabs all the information not getting some information. This leads to the failures. 
I'll test something today or tomorrow and will come back to you :)

**Comment by GilgusMaximus** [comment] 2020-12-02 18:36
This is now fixed in the newest nightly build, which should be available in a few minutes

**Closed by GilgusMaximus** 2020-12-02 18:36 UTC
Labels: bug, help wanted
