### ISSUE TITLE
[Bug]: Videos with aspect ratio different that 16:9 are zoomed when Theatre Mode is enabled

### ISSUE THREAD

**Issue by juanmbt** [FreeTubeApp/FreeTube#4755] opened 2024-03-11 05:11 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open a video that has an aspect ratio that does not matches your display aspect ratio.
2. Toogle Theatre Mode, either by pressing the button in the player or pressing the shortcut key "T".
3. The video switches to Theatre mode, but it is zoomed.
4. The playback area is cut out at the bottom. It's bigger than the screen size and you need to scroll down to see the bottom of the video and the playback/progress bar.

### Expected Behavior

When using the option to toggle theatre mode, the video should appear complete on the screen, including the playback/progress bar at the bottom.

### Issue Labels

usability issue, visual bug

### FreeTube Version

v0.19.2 Beta

### Operating System Version

Windows 10 version 22H2 (Build 19045.4046)

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

tt![Freetube_theatre_bug](https://github.com/FreeTubeApp/FreeTube/assets/21691159/48967c30-da7f-47e4-aedf-286fc02b0257)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by juanmbt** [comment] 2024-03-11 05:26
Here is a link for the video with issues: https://www.youtube.com/watch?v=jKxHAhPAVAs
This video has a weird resolution: 1406x1080.

I tested with a different video with resolution: 1216x1080 and it works correctly.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-03-11 07:36
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/959

**Closed** 2024-03-11 07:36 UTC
Labels: bug, B: visual, B: usability
