### ISSUE TITLE
[Feature Request]: Display playlist as a grid instead of a really tall linear list

### ISSUE THREAD

**Issue by Xindaris** [FreeTubeApp/FreeTube#4874] opened 2024-04-04 23:42 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

In previous versions of freetube, prior to implementation of "actual playlists", the favorites showed up in a nice big grid. Now opening a playlist brings up a page where a useless thumbnail takes up like half of the space, and the contents of the list are a vertical, linear list which is much less convenient to navigate.

### Proposed Solution

I would appreciate at least an _option_ to have playlists display the same way favorites used to.

### Alternatives Considered

I guess I could just put up with it being much more annoying to navigate?

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-05 02:45
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4708

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-05 02:45 UTC
Labels: enhancement, E: improvement existing feature, E: ease of use improvement
