### ISSUE TITLE
[Bug]: Proxy not working   TypeError: No "host"

### ISSUE THREAD

**Issue by scinrmj686** [FreeTubeApp/FreeTube#3092] opened 2023-01-18 18:52 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Enable proxy
2. Add proxy
3. Test the proxy (works)
4. Use local API
5. Load a video and get error      Local API error (click to copy): TypeError: No "host"
6. Test proxy with indivious instance (works)
7. Proxy was a link (ex: proxy.com/socks5:1080) tried using the ipv4 still did not work (test were succesful)

### Expected Behavior

I'm trying to use a proxy with the Local API to get better performances because youtube is throttling my connection only on freetube for some reason. I tried using Youtube on a normal browser (chromium) and i get 60k kbps but on FreeTube I only get 8k kbps. 

Proxy is 100% working but I get this error : 
![image](https://user-images.githubusercontent.com/123011660/213268356-f959239a-b609-4c18-b366-59a9c216193a.png)

### Issue Labels

data loss, feature stopped working, inconsistent behavior, usability issue

### FreeTube Version

0.18.0

### Operating System Version

Windows 10 21H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by mctvcse839** [comment] 2023-02-05 23:32
Update: The issue is still here but I tried to use the proxy feature that comes with electron "--proxy-server=" . It works to a certain extent. There are some request that are not going in the proxy, primarly only saw youtube.com that were not going in the proxy which made some specific videos not load + made the timer stuck like this : 
![image](https://user-images.githubusercontent.com/124193980/216852155-a95add9a-35fe-4316-9cb2-56f8b2853673.png)

Not 100% sure but the videos doing this glitch are videos with this message on them:
"This video contains content from UMG, who has blocked it from display on this website or application"
makes them not go through the proxy.

**Comment by absidue** [comment] 2023-02-06 13:39
Do you have an example of one of the videos with that message?

**Comment by mctvcse839** [comment] 2023-02-06 17:40
> Do you have an example of one of the videos with that message?

https://youtu.be/ztvcUU2B0MM

**Comment by absidue** [comment] 2023-02-07 07:18
Could you please try a nightly build and see if that is resolved there?

**Comment by mctvcse839** [comment] 2023-02-07 17:13
> Could you please try a nightly build and see if that is resolved there?

Tried latest nightly build and the proxy setting finally worked without the "No host" error. The issue is that the proxy is 20x slower at 500kbs. To test it I used the same proxy on the nightly and the official build 0.18 and on the offical I got 22000kbs.

I also tried the electron proxy feature with the nightly build but I got the same slow speed of 500kbs. I also could watch the video I sent above.

**Comment by absidue** [comment] 2023-02-08 09:32
How are you testing the proxy speed? Is this purely an artificial test or are you actually noticing a performance difference?

In the nightly builds we migrated away from the nodejs modules that needed proxy agents on the node level, now everything proxy related is only set in electron, so passing the command line flags is identical to configuring it in the FreeTube settings now.

**Comment by mctvcse839** [comment] 2023-02-08 17:04
> How are you testing the proxy speed? Is this purely an artificial test or are you actually noticing a real world performance difference?
> 
> In the nightly builds we migrated away from the nodejs modules that needed proxy agents on the node level, now everything proxy related is only set in electron, so passing the command line flags is identical to configuring it in the FreeTube settings now.

I'm using the "show video stats"
![image](https://user-images.githubusercontent.com/124193980/217600086-b29e0a27-a712-4c2a-a41a-05ecda17dc78.png)

Comparing bandwidth. Yes I also see real world performance difference, videos takes 10-20 seconds to load the first frames in the nightly build. Basically so slow that it's unwatchable.

**Comment by absidue** [comment] 2023-04-07 21:00
@mctvcse839 do you have a proxy we could use to investigate the slow loading issue?

**Comment by absidue** [comment] 2023-09-13 16:15
Closing this, as the original issue is solved (we don't have the code that the error occurs inside in 0.19.0 anymore), as for the slow proxy issue that has its own dedicated issue: #3405

**Closed by absidue** 2023-09-13 16:15 UTC
Labels: bug, B: usability, B: feature stopped working, B: inconsistent behavior, B: data loss
