### ISSUE TITLE
[Bug]: Failed to run Flatpak app

### ISSUE THREAD

**Issue by mooreye** [FreeTubeApp/FreeTube#5480] opened 2024-07-27 09:53 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I use Sway WM on Fedora. Sometimes, when trying to run Freetube, it exits with this:

```
[2:0727/114942.248383:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
[2:0727/114942.453317:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0727/114942.453360:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```

It seems the only way to fix is to restart the whole Sway session, then it works fine. Unfortunately I don't know how to reproduce because it happens only sometimes.

### Expected Behavior

app runs

### Issue Labels

usability issue

### FreeTube Version

0.21.2 Beta

### Operating System Version

Fedora 40

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-27 10:47
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5422

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-27 10:47 UTC
Labels: bug, OS: linux, B: usability
