### ISSUE TITLE
Age protected videos

### ISSUE THREAD

**Issue by harryray33** [FreeTubeApp/FreeTube#1714] opened 2021-09-17 13:29 UTC
I've just installed v14.0b on Windows 7...Freetube doesn't seem to be playing age verification videos, it's kicking up a local API error, status code 10.
Thanks

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-18 09:24
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1296

**Closed** 2021-09-18 09:24 UTC
Labels: bug, doesn't follow template
