### ISSUE TITLE
[Bug]: freetube:// links no longer work (v0.20.0)

### ISSUE THREAD

**Issue by rail5** [FreeTubeApp/FreeTube#4915] opened 2024-04-09 04:03 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

freetube:/watch?v=(video-id) link schemas used to open the requested video in older versions of FreeTube, and now just open the program to the subscriptions page, ignoring the video link

I'm running FreeTube v0.20.0 on Debian Bookworm

### Expected Behavior

I would expect the freetube:/watch?v=(video-id) link to open the video in FreeTube.

### Issue Labels

feature stopped working

### FreeTube Version

v0.20.0

### Operating System Version

Debian 12

### Installation Method

.deb

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

v0.19.0

### Additional Information

I believe(?) that these link schemas work by passing the data after "freetube:" to argv, and so I also tried running `$ freetube /watch?v=(video-id)` from the terminal -- the same behavior (simply opening the program, not loading the video) was observed.

I tried also to search for a manual to fix this and found that the Debian package does not include a manpage, nor does the freetube binary have any `-h`/`--help` menu. This is not the point of this bug report, but incidentally I would request that a manpage be added to the Debian package. Manpages can be created rather easily from Markdown pages using pandoc, if nothing else

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-04-09 04:41
It works correctly it you pass valid URLs such as `https://youtube.com/watch?v=` or `freetube://https://youtube.com/watch?v=`, the fact that your previous invalid URLs worked was unintentional, valid URLs have alway worked correctly though.

Closing as it is expected behaviour that FreeTube shouldn't be able to handle invalid URLs.

**Closed** 2024-04-09 04:41 UTC
Labels: bug, B: feature stopped working

**Comment by absidue** [comment] 2024-04-09 04:55
FreeTube doesn't have a command line interface, the only reason you can even pass a URL to the binary through the args, is that that is how URL scheme handling on Windows and Linux works (in macOS there is a special app event for it).

It was never documented because the URL scheme handling was added so that browser extensions could redirect YouTube URLs to FreeTube. It wasn't a behavioural change, correct URLs worked in older versions and still do in the current one, all that changed is the incorrect URLs no longer work, because they should never have worked in the first place.

Even if it were documented somewhere, which it currently isn't, it would be documented on the docs page https://docs.freetubeapp.io, not burried in some manpage (pretty sure that most cross-platform GUI apps that don't have a CLI, don't ship a manpage).

**Comment by rail5** [comment] 2024-04-09 05:02
I realize that outside of the "Linux world" manpages aren't too terribly common, but within that world they tend to be the first place many of us look to find this kind of info -- otherwise we just end up guessing, often incorrectly like I did. Maybe it's silly, but it's just how we are
Thanks for the info by the way, even if it doesn't end up getting added to the docs I was at least able to patch the tiny browser addon I maintain to open YT links in FreeTube

**Comment by absidue** [comment] 2024-04-09 05:07
Is there a reason you decided to write your own browser extension instead of just using one of the many already out there?

**Comment by rail5** [comment] 2024-04-09 05:11
There is, I wanted to have one which added an option to open in FreeTube to the context menu rather than opening in FreeTube by default. The only other addon I'm familiar with is Privacy Redirect, which doesn't have this option -- if you know of one which does though I'd be happy to drop mine

**Comment by absidue** [comment] 2024-04-09 05:23
I'm very surprised that a Linux users first place to look for documentation on a cross-platform GUI app would be some command line tool and not inside the app itself. The docs website is currently linked on the about page inside the app, in the README in this repo, on the website and even in the very issue template that you just filled in.

However if some Linux users are still unable to find it, then maybe it's worth adding a manpage that just links to the docs website, no point maintaining two different sets of documentation, especially for a program that doesn't have a CLI.

**Comment by absidue** [comment] 2024-04-09 05:27
> There is, I wanted to have one which added an option to open in FreeTube to the context menu rather than opening in FreeTube by default. The only other addon I'm familiar with is Privacy Redirect, which doesn't have this option -- if you know of one which does though I'd be happy to drop mine

I think the maintained fork of Privacy Redirect, libredirect, adds itself to the context menu, so you could use that, not sure if you can disable the open by default behaviour.

**Comment by rail5** [comment] 2024-04-09 05:37
> > There is, I wanted to have one which added an option to open in FreeTube to the context menu rather than opening in FreeTube by default. The only other addon I'm familiar with is Privacy Redirect, which doesn't have this option -- if you know of one which does though I'd be happy to drop mine
> 
> I think the maintained fork of Privacy Redirect, libredirect, adds itself to the context menu, so you could use that, not sure if you can disable the open by default behaviour.

Thanks! I'll check it out

The only reason manpages are so popular is to have one "centralized" location for manuals, one "standard" way of finding them for any app -- it's obviously not a "necessity" strictly speaking, but for a lot of people who've been using *nix systems for decades, it's just instinct. I should say that I did fall back on a Google search which led me to the docs page afterward, and I don't think it's absolutely unreasonable to rely on users going to that page. (The valid URL scheme though, as you mentioned, isn't currently documented)
