### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by avincent98144** [FreeTubeApp/FreeTube#4048] opened 2023-09-17 18:19 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

to be able to clear the entire list in one fell swoop as 'watched' there are hundreds in my list so too time consuming to mark watched individually.

### Proposed Solution

a SELECT ALL button to be WATCHED. Currently there are hundreds of 1+-10+ year vids that I do not want to watch.

### Alternatives Considered

N/A

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-09-17 20:45
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2517

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-09-17 20:45 UTC
Labels: enhancement, E: improvement existing feature
