### ISSUE TITLE
[Bug]: Freetube forces full-screen (subscriptions page)

### ISSUE THREAD

**Issue by goldanorak** [FreeTubeApp/FreeTube#4645] opened 2024-02-05 12:59 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Freetube launches in a window that takes up the entire screen, but does not display a title bar (so no close window button). Also the linux mint taskbar disappear at the bottom. I'm not talking about full-screen video playback, but rather the Freetube "home" window, where you can browse the latest videos, subscriptions, etc. So the only way to close Freetube is to use the shortcut Ctrl+Q or Ctrl+W. I've already solved this bug once by uninstalling then reinstalling Freetube ... but after a few bug-free sessions, it came back.

### Expected Behavior

Freetube should normally appear with its title bar, and not make the Linux Mint Cinnamon taskbar disappear.

### Issue Labels

inconsistent behavior

### FreeTube Version

0.19.1

### Operating System Version

Linux Mint 21 Vanessa with Cinnamon 5.4.12

### Installation Method

.apk (Alpine Linux Package)

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-02-05 13:02
Try f11

**Comment by xypage** [comment] 2024-02-06 19:12
Using f11 is a workaround not a fix, I've had the same issue on Windows where it'll default to full screen, and I don't think that should be default behavior, or at the very least there should be a setting to change it to default to windowed.

**Comment by absidue** [comment] 2024-02-06 19:37
FreeTube defaults to windowed, it only reopens in fullscreen if you had it fullscreened when you closed the program.

**Comment by xypage** [comment] 2024-02-06 19:56
In that case I'll make a separate issue later, because I never full screen the window besides to play videos, and that's with "f" not f11, and when I close that to menu and thus whenever I click links I'm in windowed mode. I've observed opening a link in a new window from a window I'd already manually taken off of full screen that then opened the new window in full screen anyways.

**Comment by absidue** [comment] 2024-02-06 20:04
No need for that, there are already other open issues (although hopefully you would have realised that when filling in the issue template as it asks you check that there are no identical open issues).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-02-06 20:16
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3220

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-02-06 20:16 UTC
Labels: bug, U: Waiting for Response from Author, B: inconsistent behavior
