### ISSUE TITLE
[Bug] [Flatpak]: "System Default" base theme does not switch to or from dark mode

### ISSUE THREAD

**Issue by ek-is-anika** [FreeTubeApp/FreeTube#4063] opened 2023-09-22 18:22 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When switching to light or dark theme on system, freetube does not follow that setting, and has to be manually switched.

### Expected Behavior

FreeTube's theme should automatically switch to light or dark theme, based on the system prefrences

### Issue Labels

visual bug

### FreeTube Version

v0.19.0 Beta

### Operating System Version

Fedora Workstation 38

### Installation Method

Flathub

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

v0.19.0 Beta

### Additional Information

This feature worked previously on Debian GNU/Linux 12.

I also tried re-installing all the necessary xdg portals, and granting FreeTube additional permissions through Flatseal.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-09-23 07:47
This is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2831

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-09-23 07:47 UTC
Labels: bug, B: visual
