### ISSUE TITLE
0.14.0 fails to perform all but main screen

### ISSUE THREAD

**Issue by mistersector** [FreeTubeApp/FreeTube#1768] opened 2021-10-01 02:24 UTC
**Behavior of the program**
All buttons fail to load respective data or popup windows, save for "A" in upper right corner.

**Expected behavior**
Normal operations. Subscriptions show subscriptions, settings shows settings, about shows about, etc

**To Reproduce**
There is no error code / page. It has worked flawlessly since I installed it, but failed today. 

**Link to video**
No videos.

**Screenshots**
No screenshots. I do not know how to access console logs.

**Environment Information (please complete the following information):**
 - OS: Windows x64
 - OS Version: 7
 - FreeTube version: 0.14.0
 - Installation Method: portable
 - Primary API Used: Local, although the setup screen no longer popsup

**Additional context**
I have reset the OS. 
I have renamed the /%APPDATA%/*.db files to "*.db.old" to generate new ones. 
I have renamed most of the /%APPDATA%/* folders to "*.old" to generate new folders with new data.
I have renamed the /%APPDATA%/ folder entirely and allowed Freetube to create a new one.
I have deleted the folder containing the APP, re-extracted it to the same folder name, and launched Freetube from it.
All of these failed.
Two other internet apps failed in various ways starting today, but this does not explain why Freetube would not load the about or settings screen.

**Comment by AnonymousHex** [comment] 2021-10-01 04:27
I am getting the same issue with the same environment and setup.  You can access the console by pressing Ctrl+Shift+I

**Comment by mistersector** [comment] 2021-10-01 06:51
I found it is related due to the DST Root CA X3 certificate that expired on 9/30/2021. If you unsync with internet time and set the date back manually, not only Freetube works, but all broken websites that relied on that cert loads again. 

https://www.sevenforums.com/general-discussion/426367-dst-root-ca-x3-expired-sept-30th-2021-a.html

Now, the trick is to figure out how to install this particular root cert into my OS, which apparently, Freetube relies upon.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-01 07:07
@ChunkyProgrammer this is probably worth looking into and maybe add to ur PR

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-01 09:45
i'll mark this as duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1689. I wont close this because it looks like this could be the key to solving this issue.

**Comment by AnonymousHex** [comment] 2021-10-01 10:12
I was able to solve my issue by manually installing the ISRG Root X1 certificate manually.

1. Download the self signed .der certificate from https://letsencrypt.org/certificates/  
My browser already had it added so I exported a .crt from my browser certificate settings.  
2. Double click the certificate and install it under "Trusted Root Certification Authorities -> Certificates"
3. Restart your system.

I deleted the now expired DST Root CA X3 certificate from certmgr.msc before restarting as described in the guide but upon restarting and launching FreeTube I found that it had reappeared.  I don't know if it's necessary to remove it.

My certificate expires 6/4/2035, though time will tell how long it continues to work.

**Comment by PrestonN** [comment] 2021-10-01 19:01
Just to confirm, this issue is because of the master certificate that has expired by Let's Encrypt. You can learn more about it [here](https://techcrunch.com/2021/09/21/lets-encrypt-root-expiry/). This issue has affected many applications and is not specific to FreeTube.

This is something that needs to be fixed upstream. Electron has already made a patch which we will apply. If your operating system is old enough, then it may require an update as well.

**Comment by mistersector** [comment] 2021-10-02 06:54
> manually installing the ISRG Root X1 certificate manually. 

 I tried to change the R3 and root authority for R3, but apparently I don't understand how this works.

Installed ISRG Root X1 from https://letsencrypt.org/certs/isrgrootx1.der
Restarted. Verified per certmgr, but Freetube/websites/apps still failed.

Installed Let’s Encrypt R3 signed by ISRG Root X1 from https://letsencrypt.org/certs/lets-encrypt-r3.der
Restarted. Verified per certmgr, but Freetube/websites/apps still failed.

Deleted expired DST Root CA X3 certificate from certmgr
Restarted. Verified per certmgr, but Freetube/websites/apps still failed.

The websites still think the authenticator is R3 > DST Root CA X3.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-02 08:43
Hi guys, please try out the new RC. The RC must fix this problem. https://github.com/FreeTubeApp/FreeTube/discussions/1773#discussioncomment-1416306

**Comment by mistersector** [comment] 2021-10-02 11:46
[SOLVED!](https://www.stephenwagner.com/2021/09/30/sophos-dst-root-ca-x3-expiration-problems-fix/)

The irony is the steps listed are the [same steps I tried earlier.](https://github.com/FreeTubeApp/FreeTube/issues/1768#issuecomment-932696137) Obviously, I missed something, but no more.

**Closed** 2021-10-03 02:47 UTC
Labels: bug
