### ISSUE TITLE
[Feature Request]: Ability to skip to any point in a livestream

### ISSUE THREAD

**Issue by HearthstoneBugs** [FreeTubeApp/FreeTube#4145] opened 2023-10-13 12:06 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

On YouTube it's possible to move to any point in a live stream just by clicking on the time bar at the bottom, however FreeTube won't allow this. Are there any plans to implement such a feature? Or is this tied into the fact that it's not possible to use left/right arrows to skip more than 30 seconds either way?

I'm a new user to FreeTube and am loving it so far, wish I'd found it a long time ago. Thanks to all of those involved for their hard work.

### Proposed Solution

Implement it the same as YouTube.

### Alternatives Considered

Can't think of anything.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-05 14:56
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/661

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-05 14:56 UTC
Labels: enhancement, E: new feature
