### ISSUE TITLE
[Bug]: filter by most popular doesn't work, it shows newest instead

### ISSUE THREAD

**Issue by BarbzYHOOL** [FreeTubeApp/FreeTube#3747] opened 2023-07-09 21:57 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Go on a channel, and filter by most popular

it just keeps it ordered by newest, I suppose no filter work at all

### Expected Behavior

Filter properly

### Issue Labels

feature stopped working, usability issue

### FreeTube Version

v0.18

### Operating System Version

Linux Mint 20

### Installation Method

.deb

### Primary API used

Local API

### Additional Information

it has always bugged for me

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-07-09 21:59
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3741

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-07-09 21:59 UTC
Labels: bug
