### ISSUE TITLE
[Feature Request]: Recreate SponsorBlock "manual skip" feature

### ISSUE THREAD

**Issue by klazoklazo** [FreeTubeApp/FreeTube#5920] opened 2024-10-22 20:00 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Having partial SponsorBlock integration is fantastic, although a feature of SponsorBlock I use pretty commonly is the "manual skip" option for various segment types. FreeTube does not recreate this behavior, the closest it gets is merely showing the segment within the seek bar, which does not allow me to manually skip the whole segment with a single keybind.

### Proposed Solution

Recreate the feature, allow a user to set a custom keyboard to manually skip a segment, and show a pop-up stating that the skip is available.

### Alternatives Considered

I don't recall FreeTube being able to redefine keybinds for anything else, so the keybind being hardcoded to SponsorBlock's default of the enter key is also acceptable.

### Issue Labels

ease of use improvement, improvement to existing feature

### Additional Information

Examples taken from SponsorBlock in action with regular YouTube here:

![image](https://github.com/user-attachments/assets/1944ed08-881f-4274-b56d-bbf8d6592def)

![image](https://github.com/user-attachments/assets/d5f434ee-fd23-4e9d-b858-e8ae033ff27a)

**Comment by DontBlameMe99** [comment] 2024-10-23 11:16
Duplicate of  #1380

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-23 11:42
Thanks @DontBlameMe99 !

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-23 11:42 UTC
Labels: enhancement, E: improvement existing feature, E: ease of use improvement
