### ISSUE TITLE
[Bug]: Search Returns No Values On Newly Updated Install

### ISSUE THREAD

**Issue by xcarnage** [FreeTubeApp/FreeTube#4312] opened 2023-11-09 20:29 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

While using the search bar attempt a random search query. Results return empty. Clicking fetch more results still returns empty.

### Expected Behavior

I expected that search results would return information
![Screenshot (45)](https://github.com/FreeTubeApp/FreeTube/assets/23347336/7ac606e5-c7d0-4b37-b1e6-169c1b05f254)

### Issue Labels

content not loading

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows Version 22h2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-11-09 21:52
Can you please switch to the console tab in the devtools and see what the red messages are, according to the status bar on the top right, there are 13 errors.

**Comment by armakunizen** [comment] 2023-11-15 08:44
I have the same problem on 0.19.1 beta. In the devtools (as you described) I get the following, hope this helps:

`renderer.js:2 VIDEOJS: WARN: using Vhs.BANDWIDTH_VARIANCE is UNSAFE be sure you know what you are doing
(anonymous) @ renderer.js:2
renderer.js:2 TypeError: Cannot read properties of undefined (reading 'name')
    at o$ (renderer.js:2:1384290)
    at renderer.js:2:1385432
    at renderer.js:2:1385439
    at Array.map (<anonymous>)
    at l$ (renderer.js:2:1384669)
    at renderer.js:2:1579971
    at async a.performSearchLocal (renderer.js:2:1579720)
performSearchLocal @ renderer.js:2
yt.artemislena.eu/api/v1/search/?q=glauben+sie+ja+nicht+wen+sie+da+vor+sich+haben&page=1&sort_by=relevance&date=&duration=&type=all:1          Failed to load resource: the server responded with a status of 400 ()
renderer.js:2 Invidious API error https://yt.artemislena.eu/api/v1/search/?q=glauben+sie+ja+nicht+wen+sie+da+vor+sich+haben&page=1&sort_by=relevance&date=&duration=&type=all Error: Missing hash key: "navigationEndpoint"
    at renderer.js:2:1374459
(anonymous) @ renderer.js:2
renderer.js:2 Error: Missing hash key: "navigationEndpoint"
    at renderer.js:2:1374459
(anonymous) @ renderer.js:2
`

**Comment by absidue** [comment] 2023-11-22 18:23
Okay so it turns out that these are two separate issues, the one in the original post is caused by YouTube arranging their sections differently when it shows the "did you mean" text, so you'll see no results or just a few videos. That YouTube edge case will have to be supported in YouTube.js, so that's not something that can be changed on the FreeTube side.

The second issue, the one in the comment, is a FreeTube and Invidious bug. Auto-generated album playlists don't belong to any channels, so on the search results page they don't have a channel listed, just a bit of text that says "Playlist", so when FreeTube and Invidious try to parse the playlist author/channel, they error because they can't find it. I've opened a pull request to fix this in FreeTube for the local API.

**Comment by absidue** [comment] 2023-12-24 08:04
@Ammako Could you please try the nightly builds, that bug should already be fixed by this pull request https://github.com/FreeTubeApp/FreeTube/pull/4371. This one is caused by some music album playlists not being linked to a channel (either the artist doesn't have a YouTube channel or YouTube wasn't able to link it to the channel when the album was added to YouTube Music).

This issue is still open because of the other bug, the one listed in the original issue, not in the comments. That one is caused by YouTube's "showing results for x, search for y instead" (the typo correction response), because the structure of the response a bit different in that case.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-08 04:19
Hi @xcarnage is this still happening for you in v0.20.0?

**Closed** 2024-04-23 00:00 UTC
Labels: bug, U: Waiting for Response from Author, B: content not loading
