### ISSUE TITLE
[Bug]: Subscriptions visually hidden at start

### ISSUE THREAD

**Issue by ZinRicky** [FreeTubeApp/FreeTube#2058] opened 2022-02-07 22:17 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Launch the program
2. The subscriptions list hides them completely

![Immagine 2022-02-07 230637](https://user-images.githubusercontent.com/26520924/152880997-ed4e526d-fd63-4804-920a-61ce69228e97.png)

3. Clicking on the hamburger icon on the top left solves the issue until the app is closed

![Immagine 2022-02-07 230649](https://user-images.githubusercontent.com/26520924/152881193-61a8cedb-2e89-4c03-9370-f560def9dae3.png)

It should also be noted that in the first image the i18n is not working properly, whereas the second phase is fine.

### Expected Behavior

The subscriptions should be fully visible without any additional clicks, like in the image below.

![Immagine 2022-02-07 231600](https://user-images.githubusercontent.com/26520924/152881408-9a3ffb6c-6efa-4a8d-a01f-76d1406ba75a.png)

### Issue Labels

visual bug

### FreeTube Version

v0.16.0

### Operating System Version

Windows 10 version 21H1

### Installation Method (If applicable)

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-02-08 21:09
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1883

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-02-08 21:09 UTC
Labels: bug, B: visual
