### ISSUE TITLE
[Feature Request]: Add visual indicator that video is in "Using audio formats" mode

### ISSUE THREAD

**Issue by taivlam** [FreeTubeApp/FreeTube#5363] opened 2024-07-03 12:19 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently there is no indicator whether or not FreeTube is in audio-only mode after a user chooses "Use Audio Formats" from the "Change Media Formats" button.  Sometimes I use the audio-only mode to listen to music from music videos or watch videos of podcasts where nothing important happens in the video stream.

This is what the video looks like when playing the video normally (default behavior):
![pic1](https://github.com/FreeTubeApp/FreeTube/assets/47955724/f88c9aa4-73c4-4b56-8ff5-e0b9e31ccdb6)

Audio-only mode basically looks the same, except the video frame uses the video thumbnail:
![pic2](https://github.com/FreeTubeApp/FreeTube/assets/47955724/177ff507-d58b-4fd9-8f1b-25074ac0188a)

### Proposed Solution

Adding some sort of visual symbol to indicate if the video is on audio-only mode would make it easier for users to visually inspect and ensure that audio-only mode is on when they want activate it.

Maybe there could a headphones icon that lets the user activate the audio-only mode when desired (see below for how this works on Invidious).  Basically, in the default video mode, there will be a headphones icon that will activate the audio-only mode; and in the audio-only mode, there will be a camcorder icon that will activate the default video mode.

### Alternatives Considered

Doing nothing and keeping the app the same is the other alternative.

### Issue Labels

display more information to user, ease of use improvement, visual improvement

### Additional Information

Using the `invidious.private.coffee` Invidious instance, this is what the default video looks like:
![pic3](https://github.com/FreeTubeApp/FreeTube/assets/47955724/6b7b9826-c72e-42df-b80b-5471bbaa62cd)

There is an icon for a pair of headphones, if an Invidious user wants to activate the audio-only mode, when the video is in default video mode.

When the headphones icon is clicked, this is how the player looks on Invidious:
![pic4](https://github.com/FreeTubeApp/FreeTube/assets/47955724/7eb80077-f67e-4b22-b488-6db98a6cce91)

There is an icon for a camcorder, if an Invidious user wants to activate the default video mode, when the video is in audio-only mode.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-03 19:54
Duplicate of #1092

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-03 19:54 UTC
Labels: enhancement, E: visual improvement, E: display more information, E: ease of use improvement
