### ISSUE TITLE
[Feature Request]: Keyboard shortcuts for "Fetch more results"

### ISSUE THREAD

**Issue by n3rd4i** [FreeTubeApp/FreeTube#2830] opened 2022-11-05 10:19 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Would be nice to have keyboard shortcut to fetch more results without using a mouse

### Proposed Solution

implementation of default keyboard shortcut for this purpose

### Alternatives Considered

currently the only way to do this is to use mouse

### Issue Labels

new keyboard shortcut

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-11-05 13:52
this is basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2691

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-11-05 13:52 UTC
Labels: enhancement, E: keyboard shortcut

**Comment by n3rd4i** [comment] 2022-11-10 18:09
hi if I understood correctly #2691 would implement tab / shift+tab across "GUI buttons" but aparently this does not work for "Fetch more results"? Making this request still valid. (I've tested this w/ v0.18.0 Beta)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-11-10 19:25
That will work when https://github.com/FreeTubeApp/FreeTube/pull/1525 has been fully implemented

**Comment by n3rd4i** [comment] 2022-12-31 13:37
Hi, I would like to request reopen this ticket since from "v0.18.0 Beta" this is not fixed. There are cases where a red "Load more" button appears, this is pressable with keyboard, however, "Fetch more results" is not handled the same way, invisible to "jump to next item/object" as it works w/ "Load More".

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-12-31 16:36
This is already fixed in the latest nightly build
