### ISSUE TITLE
[Bug]: Video cannot be played and flickering present 

### ISSUE THREAD

**Issue by quietwalker-libre** [FreeTubeApp/FreeTube#4661] opened 2024-02-09 13:52 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Today I opened Freetube and I noticed that the videos cannot be played anymore. 
The error I ofter see is: `NotSupportedError: Failed to load because no supported source was found.`

I checked the closed issues and I noticed that in the past was suggested to disable the invidious video proxying, but in my case (default I guess) it's disabled.
I also tried with multiple invidious instances but the result is always the same.  
To exclude a problem with invidious itself, I've tried to play a video from the instance I'm using right now and it plays correctly, without any problem. 

This is the error shown by the devconsole: 
![freetube_console_error](https://github.com/FreeTubeApp/FreeTube/assets/19744161/eda32d15-3612-41e7-97db-46be8538a10d)

### Expected Behavior

The video should load correctly

### Issue Labels

content not loading

### FreeTube Version

v0.19.1

### Operating System Version

Ubuntu 22.04

### Installation Method

.AppImage

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.1

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-02-09 16:20
Hi @quietwalker-libre is this the flickering you talking about?

https://github.com/FreeTubeApp/FreeTube/issues/1442#issuecomment-946151192

**Comment by quietwalker-libre** [comment] 2024-02-09 16:57
@efb4f5ff-1298-471a-8973-3d47447115dc yes, it's exactly that one

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-02-09 16:57
ah okay, closing as this is a duplicate of #1442

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-02-09 16:57 UTC
Labels: bug, B: content not loading

**Comment by absidue** [comment] 2024-02-10 10:20
@quietwalker-libre In the text you mentioned using Invidious but in the primary API section you put the local API, could you please clarify which one you are using? Additionally does it happen for all videos or only some of them, if it's only some of them, could you please provide a few examples?

**Comment by quietwalker-libre** [comment] 2024-02-10 14:07
@absidue I'm using local API and the flickering happen always with every video.
Then I've enabled invidious proxy in FreeTube settings and it started working. 

For this reason I tried directly using youtube site and I wasn't able to play any video, so it looks like there is something wrong elsewere - not in freetube (probably a temporary ban of my IP, even if I don't understand why since I don't use youtube often)

**Comment by absidue** [comment] 2024-02-10 14:30
If you are using a shared IP like a VPN that might be why, otherwise it could be because of lots of YouTube downloads (e.g. if you archive videos or something).
