### ISSUE TITLE
[Bug]: Error: This helps protect our community. Learn more

### ISSUE THREAD

**Issue by Zephiii** [FreeTubeApp/FreeTube#5503] opened 2024-07-31 17:21 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open any video
2. FreeTube will throw a `Failed to extract n-token decipher algorithm` error, fallback to the Invidious API, then throw a `This helps protect our community. Learn more` error.
<img width="720" alt="Screenshot 2024-07-31 at 17 20 55" src="https://github.com/user-attachments/assets/47deed64-e592-4830-a2ee-5e1bfb40d3c4">

### Expected Behavior

The video would open as expected.

### Issue Labels

API issue, content not loading, feature stopped working, usability issue

### FreeTube Version

v0.21.2

### Operating System Version

macOS Sonoma 14.5 (23F79)

### Installation Method

.dmg

### Primary API used

Local API

### Additional Information

Was working fine just an hour ago.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ColonelSanford** [comment] 2024-07-31 17:41
![Untitled](https://github.com/user-attachments/assets/141b13a6-48f7-4fe2-b27e-64320d7b9865)

**Comment by rehashedsalt** [comment] 2024-07-31 17:42
See also: https://github.com/iv-org/invidious/issues/4734

**Comment by Unt1t13d** [comment] 2024-07-31 18:16
I have the same issue on Windows too, with the two errors, but reopening it seems to fix the "Error: This helps protect our community. Learn more" issue for me

**Comment by peterweissbier** [comment] 2024-07-31 18:57
so its an error with invidious instances? are all all of the instances affected? i get this error and the video still plays btw

**Comment by 4yman-0** [comment] 2024-07-31 19:38
There is already an issue for [`Failed to extract n-token decipher algorithm`](https://github.com/FreeTubeApp/FreeTube/issues/5502). Close this issue because it is a duplicate. The Invidious error is also a duplicate of [invidious #4734](https://github.com/iv-org/invidious/issues/4734).
>The Invidious team is aware of this issue. It appears that it affects all the software using YouTube.
Please refrain from commenting if you have nothing new to bring up. Thank you.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-31 21:23
duplicate of #5489 and #5502

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-31 21:23 UTC
Labels: bug, third-party, B: content not loading, B: usability, B: feature stopped working, B: API issue
