### ISSUE TITLE
[Bug]: In-Video Subscribe Buttons are Now Missing

### ISSUE THREAD

**Issue by ThisNekoGuy** [FreeTubeApp/FreeTube#4118] opened 2023-10-09 06:45 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click on a video
2. Inspect the page for the missing channel buttons (channel icon, associated subscribe button, copy copy video / share link button, etc)

### Expected Behavior

The common channel/video associated buttons every video should have should be present.

### Issue Labels

feature stopped working

### FreeTube Version

v0.19.0 Beta

### Operating System Version

Gentoo Linux (Rolling)

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

Unknown

### Additional Information

(I don't know where the logs are placed; I tried to find them but couldn't)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-10-09 06:53
This was fixed in 0.19.1, please upgrade to the latest FreeTube version.

**Comment by absidue** [comment] 2023-10-09 06:54
Duplicate of #4104

**Closed by absidue** 2023-10-09 06:54 UTC
Labels: bug, B: feature stopped working

**Comment by absidue** [comment] 2023-10-09 07:01
Please download the update from GitHub releases for the moment, as FlatHub seems to be failing to build packages, not just FreeTube is affected.

You'll have to move your user data around as flatpak is special and doesn't use the normal location, see https://docs.freetubeapp.io/usage/data-location/
