### ISSUE TITLE
Videos changing to 144p and cannot change back

### ISSUE THREAD

**Issue by t13rd** [FreeTubeApp/FreeTube#1045] opened 2021-02-21 02:47 UTC
**Behavior of the program**
Videos playing at 720p or 1080p revert to 144p after 1-5 minutes of play time. Changing resolution by clicking gear icon and then a higher resolution does not affect this. Sometimes video will return to original resolution after a few minutes, sometimes it will play at 144p for the duration of the video. Navigating away from video and then coming back sometimes "resets" it to 720p or 1080p for another 1-5 minutes and sometimes does nothing.

**Expected behavior**
Default resolution in Settings is set to 720p. Videos should continue to play at the quality they were set to. Selecting a different playback quality should affect the playback quality of the video.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Play any video at 720p or 1080p.
2. Wait 1-5 minutes, depending on video (longer videos seem to take longer for issue to occur).

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 Home
 - FreeTube version: 0.11.3 Beta
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment] 2021-02-24 19:05
As mentioned on other issues, this is related to what VideoJS and the video streaming plugin do under the hood. It is, in terms of reason to occur, a duplicate of #595

**Closed by GilgusMaximus** 2021-02-24 19:05 UTC
Labels: bug
