### ISSUE TITLE
[Feature Request]: Organize subscriptions with "folders"/"catalog"

### ISSUE THREAD

**Issue by cain-dev** [FreeTubeApp/FreeTube#4654] opened 2024-02-08 11:27 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I have too many subscriptions... It's hard to find exactly 1 type of content.

### Proposed Solution

The solution would be to have some kind of catalog of "subjects list" and then channels inside the list.
Like:
Technology 
- Linus Tech Tips
- Luke Smith

Music
- Top 80s songs
- Best of Rock

### Alternatives Considered

Anything to have this kind of organization will be ok

### Issue Labels

display more information to user, ease of use improvement, improvement to existing feature, new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-02-08 11:34
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/800

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-02-08 11:34 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: display more information, E: ease of use improvement, E: new feature

**Comment by cain-dev** [comment] 2024-02-09 13:51
No i am not, i am talking about having too many subs and can't find the exact channel after importing over 1000 links

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-02-09 16:22
We wont do the organizing for the user the user has to do that kind of stuff

**Comment by cain-dev** [comment] 2024-02-10 19:33
Wait, what? Where you got that from? Where is that i want YOU GUYS to do the organizing? 
It's simple: My account have more than 1000 subs and i can't find a specific channel, and creating multiple accounts and putting every channel in a new account on FreeTube would be a pain, even if i import to all accounts and then unsub. But if at the left i could see folders instead of channels, and i could drag and drop channels to folders when i go to "subscription list" it would solve things.

Very simple, what it IS about: 
- Subscription list with drag and drop to folders
- Left side bar shows folders instead of channels
- Click on side bar shows channels inside folder on main page

What it isn't about:
No AI organizing
No "you guys doing it for me"
No world domination

Plain and simple drag and drop to folders so i don't have to create 30 accounts with different themes and then keep changing accounts to see different themes.

Here, i will draw this for you:
![folders](https://github.com/FreeTubeApp/FreeTube/assets/66369488/f38110bf-5e57-4994-89bd-cd9c7f1c7121)

**Comment by jasonhenriquez** [comment] 2024-02-10 20:09
That feature request is already encapsulated in #800.
