### ISSUE TITLE
[Bug]: Failed to load because no supported source was found

### ISSUE THREAD

**Issue by Freddie344** [FreeTubeApp/FreeTube#5467] opened 2024-07-25 15:22 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Can`t play any video after windows update KB5041355 and KB5040525

### Expected Behavior

watch video

### Issue Labels

content not loading

### FreeTube Version

v0.21.1 Beta

### Operating System Version

windows 10 home 22h2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.1 Beta

### Additional Information

![Screenshot (1760)](https://github.com/user-attachments/assets/391c4256-4351-49d1-b609-a0df908bc300)
![Screenshot (1761)](https://github.com/user-attachments/assets/6024536e-af1f-4fd9-9641-c478907f25dd)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-25 15:29
Duplicate of #5456

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-25 15:29 UTC
Labels: bug, B: content not loading
