### ISSUE TITLE
[Feature Request]: Exclude Shorts from Subscriptions

### ISSUE THREAD

**Issue by ActualBest** [FreeTubeApp/FreeTube#2450] opened 2022-08-04 18:57 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Shorts are unecessary and annoying. I never watch them, but they clog up my feed.

### Proposed Solution

An option to remove Shorts from the Subscriptions feed [anything with a #shorts tag)

### Alternatives Considered

I could unsubscribe from channels that often post Shorts, but this would rid me of their better, longer videos.

### Issue Labels

new feature, new optional setting, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-04 19:01
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2008

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-08-04 19:01 UTC
Labels: enhancement, E: new optional setting, E: visual improvement, E: new feature

**Comment by ActualBest** [comment] 2022-08-04 19:04
whoops, only searched open issues 🤦
