### ISSUE TITLE
[Feature Request]: Add Piped api support

### ISSUE THREAD

**Issue by git-Hmmm** [FreeTubeApp/FreeTube#2593] opened 2022-09-18 17:15 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

## About
- Piped: An open-source alternative frontend for YouTube which is efficient by design.
- Source: https://github.com/TeamPiped/Piped
- Demo Instance: https://piped.kavin.rocks/

### Proposed Solution

Both Local and Individuous apis are slow compared to original youtube client and website, but piped feels faster so please add support for it.
Devs can take a look at [LibreTube](https://github.com/libre-tube/LibreTube) (YT Client that uses Piped api) for implementation purposes.

new option named Piped API in this dropdown:
![image](https://user-images.githubusercontent.com/102938585/190919824-96761d6d-6e34-4dd2-b58a-411f5eb05473.png)

### Alternatives Considered

Nothing

### Issue Labels

new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-09-18 18:22
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1527

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-09-18 18:22 UTC
Labels: enhancement, E: new optional setting, E: new feature
