### ISSUE TITLE
[Bug]: Seek on pressing left and right arrow keys sometimes down respond

### ISSUE THREAD

**Issue by laraib07** [FreeTubeApp/FreeTube#2136] opened 2022-03-18 10:27 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Some times on seeking through arrow keys don 't respond.
2. I have to zoom in/ zoom out or reload video to fix it.

### Expected Behavior

Pressing right/left arrow key must seek 10 second forward/backward.

### Issue Labels

keyboard control not working

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Pop OS 21.10

### Installation Method (If applicable)

Flathub

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-03-18 10:46
Duplicate of #766

**Closed** 2022-03-18 10:46 UTC
Labels: bug, B: keyboard control
