### ISSUE TITLE
[Feature Request]: Add tabs option.

### ISSUE THREAD

**Issue by ElToroRey** [FreeTubeApp/FreeTube#4706] opened 2024-02-23 00:20 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Only having the option of opening multiple windows can result in the desktop getting cluttered very easily. It also makes it quite difficult to navigate back and forth between windows.

### Proposed Solution

It would be very convenient to have tabs to quickly and easily navigate videos/windows without cluttering the desktop.

### Alternatives Considered

An alternative solution would be to make it an option so people can choose how to navigate freetube.

### Issue Labels

ease of use improvement, new feature, visual improvement

**Comment by ChunkyProgrammer** [comment] 2024-02-23 01:17
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/333

**Closed by ChunkyProgrammer** 2024-02-23 01:17 UTC
Labels: enhancement, E: visual improvement, E: ease of use improvement, E: new feature
