### ISSUE TITLE
[Feature Request]: Subscriptions page video 'stacking', to alleviate the problem of certain channels flooding the page

### ISSUE THREAD

**Issue by PMTabs** [FreeTubeApp/FreeTube#5368] opened 2024-07-06 12:59 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There are channels which release a huge dump of videos in one day (for example, the GDQ speedrunning channel). This can overwhelm one's subscription page, where all we see is videos from one channel with occasional videos from other channels peppered in amongst the noise. It makes it hard to keep track and I often miss videos from other channels entirely.

### Proposed Solution

Stacking/clustering of videos into a single, expandable video thumbnail frame, with the number of videos stored in it displayed on the image (the image would probably be the channel's icon).

For example, it could be done in such a way that all videos released within a 24-hour window by a particular channel will be clumped together, and any which fall outside of that 24-hour window will be 'loose' (or indeed still contained in their own 24-hour containers from previous days).

I've made a [terrible] mock-up of what I'm talking about:

![Video Stacking](https://github.com/FreeTubeApp/FreeTube/assets/36648952/3a5fc1ce-7c5b-4f5e-97d1-2b74ec99b06f)

So you'd then click on the "16 Videos" button, and... well, what happens after that is something I'm not sure about. A menu? A pop-up? A simple unpacking of the contents of the stack? If so, do they unpack together in a neat row, or do they slot themselves back into their original places? Do they re-stack after you leave the program and come back? 🤷‍

### Alternatives Considered

Unsubscribing from channels which flood our subscription page. This isn't ideal.

Even using the Profiles feature doesn't help much if the channel doing the flooding is part of an already-busy profile.

### Issue Labels

ease of use improvement, new feature, new optional setting

### Additional Information

My proposed solution probably isn't very good, I'm sure someone could come up with a better one 👍

If this is considered for a future release, I think it should be optional, of course. It should probably be customisable, too. For example, how many videos/hours should be clumped together? Should the program exclude certain channels from stacking regardless of how many videos they pump out in quick succession? And so on.

Thank you for your time!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-06 17:51
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3799

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-06 17:51 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement, E: new feature
