### ISSUE TITLE
[Feature Request]: Abiltity To Add A whole Playlist To Bookmarks Tab (or Playlists Tab).

### ISSUE THREAD

**Issue by sec-19** [FreeTubeApp/FreeTube#3727] opened 2023-07-06 06:27 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Dear Team, Please add a function to add a whole playlist say for example A channel has created a separate Playlist On a particular Topic , So With all the current versions , and  obviously previous versions, we can only add ONE video to playlists Tab by clicking The "star" Icon. Now say for example We want to add a playlist with 100 videos to "Playlists TAB', we have to click that "star" 100s of times. My request is either to add a 

bookmark Tab , so that when we "Click on A playlist , there should be an option to bookmark that playlist, so that it will be more convienent to browse straight to that playlsit.
Thanks I Hope This Requst Would be accepted.

![Screenshot from 2023-07-06 10-44-18](https://github.com/FreeTubeApp/FreeTube/assets/135316946/858337cc-a8ea-4a52-8601-40d511ee1cca)

### Proposed Solution

My Suggestion Is to add a separate Bookmarks Tab to freetube.

### Alternatives Considered

No.

### Issue Labels

new feature

### Additional Information

![Screenshot 222](https://github.com/FreeTubeApp/FreeTube/assets/135316946/378d31a5-b978-455a-93e1-45df83309fab)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-07-06 07:53
Hi @sec-19 this hopefully will be added in v0.20.0

Also this is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/591

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-07-06 07:53 UTC
Labels: enhancement

**Comment by loskool** [comment] 2026-03-01 12:09
As far as I can tell this issue should be re-opened
