### ISSUE TITLE
Why do some videos won't play ?

### ISSUE THREAD

**Issue by smartspacemonkey** [FreeTubeApp/FreeTube#169] opened 2018-10-04 15:09 UTC
Hi,

I have imported my subscriptions from an xml file, but some videos showing in the feed won't play in the software. Do you know why ?

thank you

**Comment by PrestonN** [comment] 2018-10-15 12:58
There are several reasons that a video wouldn't play.  Right now in 0.3.2 some videos won't auto play if a 720p video is not available but a 480p video is.  Try switching the quality and see if the issue is fixed. The next release should do a better job with switching the quality automatically in this situation.

If the video still isn't playing, please send me the URL and I can take a look at it.

**Comment by PrestonN** [comment] 2019-02-26 20:33
Closing as there are no updates and will likely be fixed in the next release.

**Closed by PrestonN** 2019-02-26 20:33 UTC
