### ISSUE TITLE
Web or iOS Version

### ISSUE THREAD

**Issue by Chameleon-789** [FreeTubeApp/FreeTube#1914] opened 2021-11-24 14:56 UTC
It would be great to have a Web Version or an iOS App. I am not aware of any easy way to watch YouTube videos without YouTube.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-11-24 16:28
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/697, https://github.com/FreeTubeApp/FreeTube/issues/633

https://docs.freetubeapp.io/faq/#do-you-plan-on-porting-freetube-to-other-platforms-android-ios-etc

**Closed** 2021-11-24 16:28 UTC
Labels: U: duplicate, enhancement

**Comment by ChunkyProgrammer** [comment] 2021-11-25 11:13
> It would be great to have a Web Version or an iOS App. I am not aware of any easy way to watch YouTube videos without YouTube.

There are a few web options you can try (not developed by FreeTube)

## Piped: 
https://piped.kavin.rocks/
*Source code:*
https://github.com/TeamPiped/Piped

## Invidious:
https://docs.invidious.io/Invidious-Instances.md
*Source code:*
https://github.com/iv-org/invidious

## CloudTube:
https://tube.cadence.moe/
*Source code:*
https://sr.ht/~cadence/tube/
