### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by senolfndk** [FreeTubeApp/FreeTube#4679] opened 2024-02-15 14:32 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

show comments in sidebar

### Proposed Solution

show comments in sidebar

### Alternatives Considered

show comments in sidebar

### Issue Labels

new optional setting

### Additional Information

show comments in sidebar
![Ekran görüntüsü 2024-02-15 172737](https://github.com/FreeTubeApp/FreeTube/assets/52818836/788c4cf7-70c4-402f-90a6-e4567a55f317)
![Ekran görüntüsü 2024-02-15 172836](https://github.com/FreeTubeApp/FreeTube/assets/52818836/fa910b30-c68e-438f-a750-1e1786bcf79d)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-02-15 15:02
This is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3471 

Please reopen the original one!

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-02-15 15:02 UTC
Labels: enhancement, E: new optional setting
