### ISSUE TITLE
[Feature Request]: "Back to Tab" (for PiP) should get you back to the video

### ISSUE THREAD

**Issue by stdedos** [FreeTubeApp/FreeTube#5186] opened 2024-05-28 07:13 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

1. Start a Video
2. Go to PiP
3. e.g. Search somethin
4. Click "Back to Tab" on PiP

### Proposed Solution

Video is refocused, playback continues (maybe as an option?)

### Alternatives Considered

:upside_down_face: 

### Issue Labels

ease of use improvement, new optional setting

### Additional Information

https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+back+to+tab+should+show+video

**Comment by absidue** [comment] 2024-05-28 07:45
Duplicate of #624

**Closed** 2024-05-28 07:46 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement

**Comment by stdedos** [comment] 2024-05-28 07:47
_Can you pls close as duplicate as well?_ :sweat_smile:

**Comment by absidue** [comment] 2024-05-28 07:50
There is no close as duplicate option, only close as completed or close as won't fix. Also it really doesn't make a difference, as you get the notification for our duplicate comment and GitHub also shows you that it was marked as a duplicate.

**Comment by stdedos** [comment] 2024-05-28 07:53
Github has made two catch-all closes:

![image](https://github.com/FreeTubeApp/FreeTube/assets/133706/d4bc3238-3538-4aa3-a9dc-37febc8b2861)

I have interpreted them as "positively closed" (i.e., if _this ticket_ is "closed", it's done and I should be able to see _the thing_ it asks), or "negatively closed" (i.e., that thing doesn't/won't exist, someone else as asked the thing, etc)

**Comment by absidue** [comment] 2024-05-28 07:59
Please spend more time looking through the existing issues, both open and closed before you open any more in the future, as you've opened lots recently and almost all of them are duplicates.

**Comment by stdedos** [comment] 2024-05-28 08:08
> Please spend more time looking through the existing issues, both open and closed before you open any more in the future, as you've opened lots recently and almost all of them are duplicates.

As you can see, I have tried to do my part before opening the tickets `https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+back+to+tab+should+show+video+sort%3Aupdated-desc`

I sincerely apologize for the extra work I have/am causing you, but my search terms are limited from "what I can come up with" to explain what I am noticing.
