### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Eken-beep** [FreeTubeApp/FreeTube#2730] opened 2022-10-16 14:35 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

My feed is filled with youtube shorts i dont want to watch

### Proposed Solution

An option to completely remove all shorts from your feeds.

### Alternatives Considered

none

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-10-16 14:36
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2008

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-10-16 14:36 UTC
Labels: enhancement, E: new optional setting
