### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by therealrobster** [FreeTubeApp/FreeTube#676] opened 2020-10-16 00:56 UTC
**Behavior of the program**
The error SyntaxError: Unexpected token < in JSON at position 0 occurs when I try and search.

**Expected behavior**
It should return search results

**To Reproduce**
click in search bar, search with ENTER as the submit driver.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04 LTS
 - FreeTube version: v0.9.0 Beta

**Additional context**
I hope that helps.  It's highly regular on this machine at least.

**Comment by PrestonN** [comment] 2020-10-16 01:28
Duplicate of #662

**Closed by PrestonN** 2020-10-16 01:28 UTC
Labels: bug

**Comment by therealrobster** [comment] 2020-10-16 01:33
My bad, sorry I did not see the other.
