### ISSUE TITLE
[Feature Request]: Add a Like button to videos so we can easily show support for content providers 

### ISSUE THREAD

**Issue by PythonesqueSpam** [FreeTubeApp/FreeTube#6087] opened 2024-11-03 18:02 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I don't want to watch ads or give my personal data to Google, yet I still want to support content providers by clicking the Like button if their content warrants it. Liking a video is the minimum I can do to support content providers and influence "the YouTube algorithm"without sacrificing my time in watching ads or privacy through giving Google access to such things as my video history or subscriptions.  Currently I have to open a video in my browser to access the Like Button in YouTube. I rarely, if ever, use the Dislike Button, but I suppose that function would also be useful.

### Proposed Solution

Add a Like Button (toggle) on the FreeTube video watch window on the same line as the "Add to playlist", "Add to favourites", "Download Video" buttons, that passes my choice through to the linked video on YouTube (or even Invidious if it allows such Like/Dislike functions).  Use the same toggle functionality that mirrors what appears in YouTube. Do the same for the Dislike Button if it's function is mandatory, integrated or a counterpart to the Like Button.
Possibly add the same functionality to the drop down menu that appears when the three dots are clicked below the video preview in the "Subscriptions" video list.

### Alternatives Considered

I currently have to open the video link in my browser via the drop down menu in the "Subscriptions" list or "Video Watch" windows in FreeTube, wait for the browser window to load and then click the "Like Button" on the line below the video title. I need both an "Ad blocker" and "Enhance for YouTube" browser extensions to stop the ads and video autoplay nuisance features of YouTube playback. A "Like Button" within FreeTube, would avoid this mess of additional mouse clicks and nuisance YouTube functionality.

### Issue Labels

new feature

**Comment by absidue** [comment] 2024-11-03 18:15
Duplicate of #2959

You'll have to keep opening the video with the official YouTube website or one of their official apps if you want to use a YouTube account. Adding support for Google login would defeat the privacy goals of FreeTube and would put your account at risk because you would be using it outside of the official apps.

**Closed by absidue** 2024-11-03 18:15 UTC
Labels: enhancement, E: new feature

**Comment by PythonesqueSpam** [comment] 2024-11-04 16:04
Of course.  I just tested that. I didn't realise I needed to be logged into Google to use the Like button. Thanks for the quick response.
