### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Addictc** [FreeTubeApp/FreeTube#2029] opened 2022-01-26 10:03 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Go to subscriptions
Open a video or channel in new window with middle mouse button
from the new window try opening another channel or video in new window with middle mouse button 

### Expected Behavior

Open new window in same way as the first time

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.15.1 Beta

### Operating System Version

5.13.0-27-generic #29~20.04.1-Ubuntu SMP

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-28 00:07
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1957

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-01-28 00:07 UTC
Labels: bug, B: inconsistent behavior
