### ISSUE TITLE
Stay in full screen mode while playing playlist movies 

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#896] opened 2020-12-22 12:24 UTC
When a user play some vids using playlists, the movies are played one after the other, which is a normal thing. When the video player is in the full screen mode, playing another movie (automatically) results in exiting to windowed mode. To make it full screen mode again, the user has to maximize the player's window. It would be nice to stay in the full  screen mode and write on the screen (after the end of the movie) that another vid is going to be played soon.

**Comment by arrowgent** [comment] 2020-12-23 16:12
i thought this was a feature once before long ago, but i may be mistaken
either way: i agree this would be a great feature

**Comment by GilgusMaximus** [comment] 2020-12-30 10:59
Closing because it is a duplicate of #640

**Closed by GilgusMaximus** 2020-12-30 10:59 UTC
Labels: enhancement
