### ISSUE TITLE
Cant see time indicator

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1470] opened 2021-06-28 15:08 UTC
**Behavior of the program**
If u hover all the way to the right to see whats going on at the end of the video the preview thumbnail stays on it place and u can see what happens, but the time indicator gets out of sight.

**Expected behavior**
The time indicator must do the same as the left side.

**To Reproduce**
See video.

**Link to video**

https://user-images.githubusercontent.com/73130443/123659303-0e93ff80-d822-11eb-8557-58da4a91a62f.mp4

**Screenshots**
None.

**Environment Information (please complete the following information):**
- OS: [Win 10]
- OS Version: [20h2]
- FreeTube version: [v0.13.2-nightly-953 Beta]
- Installation Method (If applicable): [Portable]
- Primary API Used: [Local API]

**Additional context**
None.

**Comment by peepopoggers** [comment] 2021-06-29 13:54
some z-index tricks would solve

**Comment by PikachuEXE** [comment] 2021-06-30 06:49
It seems the position is controlled from
- https://github.com/videojs/video.js/blob/v7.13.3/src/js/control-bar/progress-control/mouse-time-display.js#L56-L62
- https://github.com/videojs/video.js/blob/v7.13.3/src/js/control-bar/progress-control/time-tooltip.js#L54-L107

Overriding the z-index won't help

**Comment by peepopoggers** [comment] 2021-06-30 21:30
css makes me go insane sometimes, even simple centering breaks with a touch

**Comment by peepopoggers** [comment] 2021-06-30 21:32
![image](https://user-images.githubusercontent.com/72892531/124034332-f6bfa580-d9f2-11eb-8a6e-2247ff5bc946.png)

confirmed

**Comment by Svallinn** [comment] 2021-07-03 19:38
This doesn't seem to be an issue with CSS, but rather with JS.
Placing the cursor on the leftmost side does not reproduce this behavior, because the tool-tip appropriately compensates for it.
![image](https://user-images.githubusercontent.com/41585298/124365196-ee0ae180-dc35-11eb-8e6d-d36aea9a25e4.png)

I'd recommend opening an issue in the video.js project. Once they fix it on their end, we'll have the fix over on the app.
https://github.com/videojs/video.js

I'm going to close this, just because I don't wanna have to backtrack and close this issue 3 months from now for something so minor.

**Closed by Svallinn** 2021-07-03 19:38 UTC
Labels: bug, third-party

**Comment by PikachuEXE** [comment] 2021-07-03 22:39
Ya will try to fix it locally and open PR there

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-03 23:59
@PikachuEXE 

https://github.com/videojs/video.js/issues/7248

**Comment by PikachuEXE** [comment] 2021-07-05 07:33
@efb4f5ff-1298-471a-8973-3d47447115dc 
Posted a comment with a potential fix
https://github.com/videojs/video.js/issues/7248#issuecomment-873876011

I will submit a PR later this week unless further discussion developed on that issue
