### ISSUE TITLE
[Feature Request]: Auto-Update

### ISSUE THREAD

**Issue by careet** [FreeTubeApp/FreeTube#6404] opened 2024-12-18 00:55 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hello, I humbly request an auto-update feature be built into the app. This is a wonderful project and I'm immensely grateful for everyone's efforts, but the frequency of required updates makes using the app a bit tedious. I think an auto-update feature would improve everyone's experience with Freetube.

### Proposed Solution

An auto-updater, perhaps with an option to force a check via the hamburger menu, seems like a good solution.

### Alternatives Considered

N/A

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-18 01:02
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/841

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-18 01:02 UTC
Labels: enhancement, E: ease of use improvement
