### ISSUE TITLE
[Feature Request]: more intuitive playback speed controls

### ISSUE THREAD

**Issue by BatmanDrinkingLean** [FreeTubeApp/FreeTube#5398] opened 2024-07-12 06:27 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

playback speed automatically adjusts pitch alongside it. I would like to  control these separately and with greater precision than is currently allowed (.05 increments if using scroll feature)

### Proposed Solution

allow for changing playback speed by .01 at a time. and have separate controls for pitch and tempo with the ability to control these separately or together. 

### Alternatives Considered

newpipe does this perfectly and it would be great to see their same system for playback speed adjustment used as an example for freetube.  the youtube website can also do this using global speed.
![playbackspeedadjust](https://github.com/user-attachments/assets/c710b6ea-9df1-485d-b041-6f9119cd2210)

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-12 08:14
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1850

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-12 08:14 UTC
Labels: enhancement, E: new optional setting
