### ISSUE TITLE
[Feature Request]: Search Settings

### ISSUE THREAD

**Issue by stdedos** [FreeTubeApp/FreeTube#5155] opened 2024-05-22 10:44 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I want to figure out if a specific search exists

### Proposed Solution

"Somehow" it is possible to search all settings (and their possible values for e.g. drop-down ones).

And/or, at least the "Browser Search (Ctrl+F)" would be available (if possible)

### Alternatives Considered

:upside_down_face: 

### Issue Labels

ease of use improvement, new feature

### Additional Information

- https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+search+settings

... but there are 15 pages worth of stuff, and I don't think my keywords are very unique :sweat_smile: 

Apologies for the influx of "Duplicates" I am creating :heart:

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-22 10:50
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4726

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-05-22 10:50 UTC
Labels: enhancement, E: ease of use improvement, E: new feature
