### ISSUE TITLE
Video info overflowing off of element when window is small

### ISSUE THREAD

**Issue by peepopoggers** [FreeTubeApp/FreeTube#1639] opened 2021-09-04 21:41 UTC
**Behavior of the program**
Video info falling off the side of element

**Expected behavior**
For the buttons and info to compact under other elements

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any video
2. Make window small enough sideways to reproduce bug

**Screenshots**
![image](https://user-images.githubusercontent.com/72892531/132108719-bf096123-8e56-4c33-b4c0-c33d6b179add.png)

**Environment Information (please complete the following information):**
 - FreeTube version: Nightly

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-04 21:58
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/856

See enclosed screenshot at nr 8

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-09-04 21:58 UTC
Labels: bug

**Comment by peepopoggers** [comment] 2021-09-04 23:01
@efb4f5ff-1298-471a-8973-3d47447115dc Its not really the same thing, but i guess technically its the same issue, so good spot.
