### ISSUE TITLE
Implement the "go back" action in more places

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#324] opened 2019-08-14 15:20 UTC
There's a way to go back using the back arrow that will appear after playing some searched video. This is the only place the back arrow shows up. What about other places like `subscribed channel -> vid` or `favorite -> vid`?

An option can be added to ask user whether he wants the current scroll position to be preserved, so he wouldn't have to scroll all the way down to see another vids near the one he just played.

**Comment by PrestonN** [comment] 2019-08-14 18:34
This is a duplicate of #15.

**Closed by PrestonN** 2019-08-14 18:34 UTC
