### ISSUE TITLE
Sponserblock disable automatic skipping

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1441] opened 2021-06-23 18:37 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
At the moment u always get forced to skip the sponsor. It would be nice that it doesn't force u to skip but still shows u the color of the sponsorblock segment. So the user has more control over what sponser he/she like to see or not.

**Describe the solution you'd like to see implemented**
Maybe this could done with a toggle in the settings?

**Describe alternatives you've considered**
This comment was made by another user but i cant ping him/her :( 

The way I've seen it done in most other implementations is that for each category, each type of section (like sponsor or self promotion) you have several settings. You can disable it completely, you can show the bar, you can show the bar and skip, and in some implementations you can show the bar and a button to skip manually. Probably the first 3 are what the vast majority of people use.

So you could say "I want to show the sponsor section and the self promotion section, skip only the sponsor section, and I don't care about all the other sections".

For now though, having an automatic skip of all sponsor sections is I think what the majority of people want and need from a sponsorblock implementation. I've been using the fork as my daily FreeTube experience and it's been great. I'll change it to the development branch of this repo to see if I get any issues and continue testing it.

**Screenshots**
None.

**Additional context**
None.

**Comment by ChunkyProgrammer** [comment] 2021-06-23 19:50
Duplicate of #1380

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-06-23 19:52
Ah ur right i will comment my input over there.

**Closed** 2021-06-23 19:57 UTC
Labels: enhancement
