### ISSUE TITLE
[Bug]: Local API Error (Click to copy): Error: Failed to extract n-token decipher algorithm

### ISSUE THREAD

**Issue by kadster65** [FreeTubeApp/FreeTube#5505] opened 2024-07-31 23:20 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I get this error when attempting to view any videos in Freetube. It has happened in the current release, as well as the previous one.

Local API Error (Click to copy): Error: Failed to extract n-token decipher algorithm

### Expected Behavior

I expect the video to play as normal.

### Issue Labels

API issue

### FreeTube Version

v0.21.2 Beta

### Operating System Version

Linux Mint 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

N/A

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-08-01 04:56
Duplicate of #5502

**Closed** 2024-08-01 04:56 UTC
Labels: bug, B: API issue
