### ISSUE TITLE
Why does youtube Api keeps loading through Tor network ?

### ISSUE THREAD

**Issue by zaouch** [FreeTubeApp/FreeTube#171] opened 2018-10-08 03:08 UTC
It just keep loading without anything happening.

**Comment by haydenhughes** [comment] 2018-10-31 05:32
Are you using appimage? If so then it'll be the same problem as #161. Otherwise make sure that you have tor installed and running.

**Comment by haydenhughes** [comment] 2018-11-02 22:31
@PrestonN I just tried the RPM and I was getting the same issue as @zaouch. `nyx` doesn't report any network traffic so it seems like version 4 broke the tor connection. Cloning the development branch from github and running freetube using `npm start` results in the same problem.

**Comment by haydenhughes** [comment] 2018-11-02 23:20
All right I have found the issue. The problem is being caused by [socks](https://github.com/JoshGlazebrook/socks/) library used by the tor library. On line 205 of `node_modules/socks/build/client/socksclient.js` you need to remove the `.unref()` as it's causing `Uncaught (in promise) TypeError: setTimeout(...).unref is not a function`.

**Comment by PrestonN** [comment] 2019-02-27 15:21
This should be fixed in the next release.  The Tor functionality has been revamped quite a bit and should be much easier to work with and use.

**Closed by PrestonN** 2019-02-27 15:21 UTC
