### ISSUE TITLE
Add option for monochromatic logo throughout app

### ISSUE THREAD

**Issue by peepopoggers** [FreeTubeApp/FreeTube#1314] opened 2021-05-22 22:20 UTC
The logo at the top is red/blue and can sometimes be an eye sore due to the color differences. Its a small issue, but a pretty easy fix. An idea would be an option in settings to change it to monochromatic.

Before:
![image](https://user-images.githubusercontent.com/72892531/119242191-d418b200-bb53-11eb-99e0-3d8309ba8652.png)
After (Like this but in a brighter white):
![image](https://user-images.githubusercontent.com/72892531/119242220-088c6e00-bb54-11eb-8456-8792cbe6a6f0.png)

Also another idea:
Logo color sync (Example):
![image](https://user-images.githubusercontent.com/72892531/119242245-2f4aa480-bb54-11eb-8624-76bf118de3aa.png)

Logo would be split into two parts and would be colored using css to match the two chosen color options.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-11 12:38
duplicate of #1152 pls put ur idea's there

**Closed** 2021-07-11 15:39 UTC
Labels: enhancement
