### ISSUE TITLE
Add the ability to put videos in a temporary watchlist/playlist

### ISSUE THREAD

**Issue by muffinmaster1024** [FreeTubeApp/FreeTube#1970] opened 2021-12-29 07:03 UTC
Just like the "watch next" feature on youtube or newpipe.
It would be very helpful for binging etc.
It could be added in the three dot dropdown or next to save video button on the thumbnail in overview

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-12-29 13:06
Duplicate of
https://github.com/FreeTubeApp/FreeTube/issues/547

**Closed** 2021-12-29 13:06 UTC
Labels: U: duplicate, U: doesn't follow template
