### ISSUE TITLE
[Bug]: Every channel doesn't show shorts.

### ISSUE THREAD

**Issue by BeatlesNo1** [FreeTubeApp/FreeTube#5730] opened 2024-09-22 22:20 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Go to the channel, click on shorts and there are none shown.

### Expected Behavior

I expect to see the shorts.

### Issue Labels

content not loading

### FreeTube Version

0.21.3 Beta

### Operating System Version

Arch based, Garuda Linux with KDE on wayland

### Installation Method

.AppImage

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.21.2

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Bennguyen2** [comment] 2024-09-22 23:07
It is already being discussed [here](https://github.com/FreeTubeApp/FreeTube/issues/5685).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-23 00:00
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5685

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-23 00:00 UTC
Labels: bug, B: content not loading
