### ISSUE TITLE
[Feature Request]: User specified colours

### ISSUE THREAD

**Issue by Penguin-Guru** [FreeTubeApp/FreeTube#6123] opened 2024-11-09 05:57 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I seem to recall FreeTube once supporting arbitrary colours (e.g. R.G.B. hex codes). That no longer seems to be offered in the U.I. I think it would be good to have. Speaking for myself, the granular colour options currently offered do not match my system's colour palette, which I do use for other applications.

### Proposed Solution

Offer a colour picker and, or at least, an input field for R.G.B. hex codes. This could be per colour setting or as a side menu to add/remove custom colours to the current drop-down lists.

### Alternatives Considered

Maybe there's a way of doing this outside the U.I. I still think it would be good to have in the U.I.

### Issue Labels

improvement to existing feature, visual improvement

### Additional Information

Personally, I would rather not even have the default list of colour options. The lists are a bit long, I won't use any of those colours, and some of the names are a bit misleading. This isn't an issue, just my perspective on the relevant U.X.

**Comment by absidue** [comment] 2024-11-09 06:40
Duplicate of #3145

**Closed** 2024-11-09 06:40 UTC
Labels: enhancement, E: improvement existing feature, E: visual improvement

**Comment by Penguin-Guru** [comment] 2024-11-09 07:52
Wow, sorry. I did search for both "colour" and "color" but "color" found no results. I must have mixed up the search prefix somehow. 🤦
