### ISSUE TITLE
0.15.1 - crash upon video playback

### ISSUE THREAD

**Issue by Kazcade** [FreeTubeApp/FreeTube#1910] opened 2021-11-23 16:47 UTC
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**
The application crashes upon video playback. Audio continues to play. No additional error information is displayed. Windows event-log only displays default information (appliaction error, event ID : 1000 etc.).

**Expected behavior**
Application should not crash when commencing video playback.

**To Reproduce**
Start FreeTube. Select any video. Play back video.

**Screenshots**
I can provide Screenshots of the crash window and event log entry if necessary.

**Environment Information (please complete the following information):**
 - OS: Windows 7 64-bit
 - FreeTube version: 0.15.1
 - Installation Method (If applicable): portable
 - Primary API Used: Local API

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-11-23 17:28
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1886

**Closed** 2021-11-23 17:29 UTC
Labels: bug, U: duplicate
