### ISSUE TITLE
[Feature Request]: Option to block Shorts and Upcoming videos

### ISSUE THREAD

**Issue by MaxGripe** [FreeTubeApp/FreeTube#2755] opened 2022-10-21 20:07 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

It would be really great to have an option to hide "Shorts" and "Upcoming" YouTube videos from the Subscriptions panel.

In FireFox I can do that using some plugins, for example:
- BlockTube plugin has "Block Youtube Shorts videos" option
- uBlock Origin plugin has advanced filter that allows to remove Upcoming videos with the following code:

```
www.youtube.com##ytd-browse ytd-grid-video-renderer:has(ytd-thumbnail-overlay-time-status-renderer[overlay-style="UPCOMING"])

www.youtube.com##ytd-browse ytd-rich-item-renderer:has(ytd-thumbnail-overlay-time-status-renderer[overlay-style="UPCOMING"])

www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer ytd-thumbnail-overlay-time-status-renderer[overlay-style="UPCOMING"]:upward(ytd-item-section-renderer)
```

### Proposed Solution

Additional options in the "Settings" > "Subscription settings" section:

- Hide Youtube Shorts videos
- Hide Youtube Upcoming videos

### Alternatives Considered

1) the above options available in the Search Filters
2) new feature - advanced filters that allow custom filtering / scripts

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-10-21 22:23
Duplicate of #2008

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-10-21 22:23 UTC
Labels: enhancement, E: new optional setting, E: new feature

**Comment by MaxGripe** [comment] 2022-10-21 22:44
> Duplicate of #2008

#2008 is considered duplicate of #1070 but that request is about title filtering only.
I don't understand how my request is a duplicate of that?

**Comment by ExInferi** [comment] 2022-11-09 12:33
This was one of my favourite features in Vanced, the ability to hide shorts in subscription feed. Upcoming videos don't bug me, but this feature isn't used often by the creators I'm subscribed to. I can see why this would be a wanted feature. 

> #2008 is considered duplicate of #1070 but that request is about title filtering only. I don't understand how my request is a duplicate of that?

I suppose your suggested alternatives are a duplicate?

**Comment by Flashwalker** [comment] 2023-03-13 18:21
The feed is flooded with shorts,
We want to skip shorts!

**Comment by Flashwalker** [comment] 2025-05-09 06:19
Shorts are still present in the search results. Please add a filter for search results
