### ISSUE TITLE
Recommended

### ISSUE THREAD

**Issue by NotDiamondZ** [FreeTubeApp/FreeTube#1547] opened 2021-07-26 01:34 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Please describe clear and concise of what the problem is. Ex. I'm always frustrated when [...]
Not a problem, just a request.
**Describe the solution you'd like to see implemented**
Please give a clear and concise description of what you want to happen.
It would be lit if you guys could add a recommended page using YouTube's algorithm to show recommended videos
**Describe alternatives you've considered**
Are there other ways to solve the problem? Please give a clear and concise description of any alternative solutions or features you might have considered.
None
**Screenshots**
Sometimes people have screenshots from mock-ups or other projects. Add them here.
Nope
**Additional context**
Add any other context about the feature request here.
PLEASE ADD IT I BEG YOU @PrestonN @freetubeapp

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-26 14:27
> FreeTube is an open source desktop YouTube player built with privacy in mind. Use YouTube without advertisements and prevent Google from tracking you with their cookies and JavaScript. Available for Windows, Mac & Linux thanks to Electron.

I think that this will be a wont implement, because it uses like u said yt's algorithm. The algorithm that collects ur data. This is the opposite of having privacy in mind.

**Comment by GilgusMaximus** [comment] 2021-07-26 19:00
Well we have planned a recommendation system, but it obviously will have very clear limits of what is possible and is a long time in the future.

**Comment by NotDiamondZ** [comment] 2021-07-27 18:54
Ok thanks

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by PrestonN** [comment] 2021-07-28 18:01
I'll consider this as a duplicate of #677. I've already described my plan for this over there. It's something I'd like to do at some point however it is not a priority at this time.

**Closed by PrestonN** 2021-07-28 18:01 UTC
Labels: enhancement
