### ISSUE TITLE
[Feature Request]: Ability to delete really old videos from watch history

### ISSUE THREAD

**Issue by WatchOfTime** [FreeTubeApp/FreeTube#5499] opened 2024-07-30 04:16 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I'm worried about the watch history taking up space, but sometimes I still use it to keep track of long format videos.

### Proposed Solution

I want the ability to delete all videos before a certain watch date from my history. I'm thinking maybe from 3 months ago.

### Alternatives Considered

- Deleting my watch history when it gets too much.
- Not saving watch history & just using a note to save or keep track of where I am in the video.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-30 21:37
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2889

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-30 21:37 UTC
Labels: enhancement, E: new feature
