### ISSUE TITLE
[Feature Request]: View playlists as a grid instead of as a list

### ISSUE THREAD

**Issue by redactedscribe** [FreeTubeApp/FreeTube#4860] opened 2024-04-04 12:50 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The new playlists view is displayed as a list and less is visible on screen at any one time than before (pre v0.20). In v0.20 (with my current window size), I can see 4 video thumbnails in full on my screen in the Favorites playlist, compared to in v0.19 I could see 12 at once since a grid-based view was used.

### Proposed Solution

Allow switching between displaying playlists in list or grid view (and remember the state, not per-playlist, but globally).

### Alternatives Considered

Get used to a list view and scroll more.

### Issue Labels

ease of use improvement, improvement to existing feature, visual improvement

### Additional Information

A grid view makes less sense when wanting to order the playlist items, but for browsing it is arguably better. With the view mode being toggleable, we could switch back to viewing the playlist as a list to order them. In both view modes, we should still be able to order videos via the arrow buttons.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-04 12:54
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4708

See my comment about it

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-04 12:54 UTC
Labels: enhancement, E: improvement existing feature, E: visual improvement, E: ease of use improvement
