### ISSUE TITLE
Integration with SponsorBlock project

### ISSUE THREAD

**Issue by connervieira** [FreeTubeApp/FreeTube#487] opened 2020-06-08 16:59 UTC
The one feature I miss from typical YouTube is the ability to use the SponsorBlock plugin, which uses a crowdsourced database of YouTube sponsorship segments, and automatically skips them.
Here is a link to the project: https://sponsor.ajay.app/

**Comment by PrestonN** [comment] 2020-06-08 17:34
This is a duplicate of #471

**Closed by PrestonN** 2020-06-08 17:34 UTC
Labels: duplicate
