### ISSUE TITLE
[Feature Request]: Better oversight of what channels have been added to which subscription groups

### ISSUE THREAD

**Issue by SentientBeingOnAQuest** [FreeTubeApp/FreeTube#4095] opened 2023-10-03 06:39 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

As it stands you are presented with a giant messy list of all of your subscriptions and you have to scroll through the entire list picking which ones to add to which profile without any ability to see whether channels have been added to other profiles ect. 

This poses various problems such as duplicate occurrences across profiles, channels not being included in any profiles ect. 

The popular addon for Youtube called Pockettube has solved many of these issues by showing you an overview of all subscriptions and which folders they have been added to. 

I would like to see a similar thing implemented in Freetube. 

### Proposed Solution

1 The ability to get an overview of all subscribed channels that shows in which subscription profiles the channels have been included
2 The ability to see which channels have not been included in any subscription profiles

### Alternatives Considered

N/A

### Issue Labels

display more information to user, ease of use improvement, improvement to existing feature

**Comment by absidue** [comment] 2023-10-06 06:50
Sounds like the existing profile edit page already does a lot of that, the only missing thing is seeing what you subscribed to in the all channels profile but not in any of your custom profiles.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-23 23:10
Sounds like @jasonhenriquez PR fixes this

**Comment by jasonhenriquez** [comment] 2023-11-23 23:20
No, but 2) it seems to be a duplicate of #914. 1) seems to already exist through Profile Edit.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-23 23:32
You're right, duplicate of #914

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-23 23:32 UTC
Labels: enhancement, E: improvement existing feature, E: display more information, E: ease of use improvement
