### ISSUE TITLE
[Bug]: FreeTube erroneously thinks I'm subscribed to "Ethereum (US)" channel but I'm not

### ISSUE THREAD

**Issue by torriem** [FreeTubeApp/FreeTube#2118] opened 2022-03-11 22:45 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Click on "Subscriptions."

I see a live stream video from a channel called, "Ethereum (US)" that FreeTube thinks is in my subscriptions list. That channel is not listed on the side in my list of channels, and If I click on the channel link, the button says "Unsubscribe," so FreeTube thinks I am subscribed to it. Yet it's not in my list of channels and when I export my channels, it's not in the export file. 

### Expected Behavior

I expect to see only the videos from channels I'm actually subscribed to.

### Issue Labels

usability issue

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Fedora 35 Linux

### Installation Method (If applicable)

.rpm

### Last Known Working FreeTube Version (If Any)

v0.15.0

### Primary API used

Invidious API

### Additional Information

Perhaps Invidious is injecting this video into my list somehow?  I cannot determine.  Seems to be using https://invidious.esmailelbob.xyz instance at the moment.  Not sure why FreeTube thinks I'm subscribed to that Ethereum (US) channel, though.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by torriem** [comment] 2022-03-12 00:35
I can't see it anymore, so if it is a bug, or an interaction with Invidious, I don't see any way of tracking this down unless the devs know about it.  I will close this bug tomorrow.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-03-12 14:01
I'll close it since u cant reproduce it and i cant reproduce this on my end.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-03-12 14:01 UTC
Labels: bug, B: usability

**Comment by torriem** [comment] 2022-03-12 14:25
Okay this is not a bug, not a problem with FreeTube.  The problem seems to be that some nefarious people stole the channel of a well-known metal worker, Ron Covell. They changed the channel name, which is probably why FreeTube thought I was subscribed, although it no longer thinks that.
