### ISSUE TITLE
[Feature Request]: Visual indicator of current playback speed when using keyboard shotcuts

### ISSUE THREAD

**Issue by ssnor** [FreeTubeApp/FreeTube#6059] opened 2024-11-01 13:17 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When playback speed is changed using keyboard shortcuts "O" and "P" in the player there is no visual indication of the new playback speed.

### Proposed Solution

I think a quick discreet popup that displays the current playback speed on change would be both good feedback and informational for the user.

### Alternatives Considered

Maybe a toast message can be used?

### Issue Labels

display more information to user

**Comment by absidue** [comment] 2024-11-01 15:40
Duplicate of #4658

**Closed** 2024-11-01 15:40 UTC
Labels: enhancement, E: display more information
