### ISSUE TITLE
Gray out forward or backward button

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1420] opened 2021-06-16 13:51 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Would be nice to have some user feedback in the application to know when u reached the first/last page u can go to.

**Describe the solution you'd like to see implemented**
When u first start Freetube u cant go forward or backward because u just started the application. 
Gray out the buttons on start of the application and make them not clickable when grayed out.
Gray out when u cant go forward/backward anymore and make them not clickable when grayed out.
![Capture](https://user-images.githubusercontent.com/73130443/122230534-45285c80-cea9-11eb-9103-bb8a7e200907.PNG)

**Describe alternatives you've considered**
None.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/73130443/122230328-13af9100-cea9-11eb-81c2-f930b0767aa3.PNG)

**Additional context**
None.

**Comment by GilgusMaximus** [comment] 2021-06-17 10:48
Duplicate of #1058

**Closed by GilgusMaximus** 2021-06-17 10:48 UTC
Labels: enhancement
