### ISSUE TITLE
[Bug]: Error: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by cocoonkid** [FreeTubeApp/FreeTube#2181] opened 2022-04-10 11:08 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Problem appeared today out of nowhere. All I did was adding a few videos from subscriptions to playlist.

Start freetube

Error message:
```
A JavaScript error occurred in the main process
```
```
Uncaught Exception:
Error: Cannot create a string longer than 0x1fffffe8 characters
at Object.slice (node:buffer:593:37)
at Buffer.toString (node:buffer:811:14)
at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:63:23)
```

Now it shows my playlist as empty.

My playlist.db file is approaching 700mb. 
699.3MB  to be exact Is that a possible source of the  problem?

I restored a backup from yesterday which just has 300mb.

Somehow an item which I added to my playlist must have caused a write loop to the db until it got corrupted.

I tried opening the 700mb db file and it is not possible.  The 300mb works.

### Expected Behavior

Able to see my playlists.

### Issue Labels

data loss

### FreeTube Version

0.16.0

### Operating System Version

MacOS 12.3.1

### Installation Method (If applicable)

.dmg

### Last Known Working FreeTube Version (If Any)

0.16.0

### Primary API used

Invidious API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-04-10 11:42
duplicate of #2171 

i would recommend posting over there!

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-04-10 11:42 UTC
Labels: bug, B: data loss

**Comment by cocoonkid** [comment] 2022-04-10 12:12
thanks!  weird. I searched for issues though :-)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-04-10 12:22
dont worry about it :D
