### ISSUE TITLE
[Bug]:Not being able to watch age restricted videos

### ISSUE THREAD

**Issue by Brookliner** [FreeTubeApp/FreeTube#2071] opened 2022-02-10 11:20 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Go to a age restricted video.
2. Will not load and get error 410 and {"error":"Missing JSON element \"twoColumnWatchNextResults\"","errorBacktrace":"Missing JSON element \"twoColumnWatchNextResults\" (BrokenTubeException)\n  from /usr/lib/crystal/core/json/any.cr:102:10 in 'extract_video_info:video_id'\n  from /usr/lib/crystal/core/hash.cr:1139:13 in 'get_video:region'\n  from src/invidious/routes/api/v1/videos.cr:11:15 in '->'\n  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call'\n  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'\n  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'\n  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'\n  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'\n  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:158:7 in 'call'\n  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'\n  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'\n  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'\n  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'\n  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'\n  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'\n  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'\n  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'\n"}

### Expected Behavior

The video should load without issues and errors.

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Windows 10 version 21H2

### Installation Method (If applicable)

.exe

### Last Known Working FreeTube Version (If Any)

v0.15.1

### Primary API used

Local API

### Additional Information

![Freetube age restricted videos bug](https://user-images.githubusercontent.com/23708434/153395617-e9afa331-2f9f-491e-a95f-92f470009d52.png)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment] 2022-02-10 14:05
LocalApi hasn't worked for AgeRestricted in a while (the 410). I'm not sure about the [Invidious](https://github.com/iv-org/invidious) error and I think that Invidious should be able to play at least some age restricted videos. Could you share a link to the video that gave you this error?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-02-10 19:03
Duplicate of #1296

**Closed** 2022-02-10 19:04 UTC
Labels: bug, U: duplicate, B: content not loading, B: API issue

**Comment by Brookliner** [comment] 2022-02-10 19:35
https://www.youtube.com/watch?v=QVCW7-0Q8FQ

**Comment by ChunkyProgrammer** [comment] 2022-02-12 17:55
Looks like there's a PR on the invidious repo to fix the issue. https://github.com/iv-org/invidious/pull/2892

**Comment by SamantazFox** [comment] 2022-02-12 19:23
> Looks like there's a PR on the invidious repo to fix the issue. [iv-org/invidious#2892](https://github.com/iv-org/invidious/pull/2892)

The PR only makes the page print a more comprehensive error message.
Age-restricted and private videos can't currently be played (on invidious, and maybe others).
