### ISSUE TITLE
[Bug]: RSS Feed Stops Working If The Profile is Overused

### ISSUE THREAD

**Issue by CTRLexe** [FreeTubeApp/FreeTube#5749] opened 2024-09-25 13:07 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

![image](https://github.com/user-attachments/assets/d09201ee-abd9-41e7-905b-5cd27c14a7a1)
I click refresh feed after it didn't show me all the channels. It instead shows me this.

### Expected Behavior

Shows new videos from creators regardless of profile.

### Issue Labels

content not loading

### FreeTube Version

v0.21.3

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.2

### Additional Information

It doesn't matter which API I use or whether or not I use a VPN. If I had to guess, I'm still being rate limited.
It also seems to affect smaller profiles if I have RSS enabled.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by rauldipeas** [comment] 2024-09-25 13:28
Same situation here.

**Comment by karolyi** [comment] 2024-09-25 13:32
Same.

**Comment by riverpiers** [comment] 2024-09-25 13:42
You cannot see subscriptions when there are more than 124 in the default category of all channels. If you don’t have separate categories, you won’t see any videos currently. “Temporary solution”:
1. Go to the subscriptions tab and create several thematic categories.
2. Add subscriptions according to, for example, the channel’s topic, up to 124 subscriptions in one category.
3. Now you can see subscriptions outside the main aggregate category. (Channels not included in the subscription list will not be fetched).

**Comment by karolyi** [comment] 2024-09-25 13:44
@riverpiers all I can say is that I didn't add any new subs, and it started failing today. I don't think it's related to what you claim.

**Comment by NoSpiner** [comment] 2024-09-25 14:22
> You cannot see subscriptions when there are more than 124 in the default category of all channels. If you don’t have separate categories, you won’t see any videos currently. “Temporary solution”:
> 
>     1. Go to the subscriptions tab and create several thematic categories.
> 
>     2. Add subscriptions according to, for example, the channel’s topic, up to 124 subscriptions in one category.
> 
>     3. Now you can see subscriptions outside the main aggregate category. (Channels not included in the subscription list will not be fetched).

No this won't work. I had similar setup before just for convenience sake and  I have the same issue. Even if profile has only one channel it won't show anything. opening individual profiles still works fine though.

**Comment by riverpiers** [comment] 2024-09-25 14:38
@NoSpiner On the portable version: v0.21.3 Beta/Win 10, the rest still works, including adding subscriptions to a separate category, apart from collective subscriptions. Currently, I don't see it in "All Channels" today, not only because I have 300+ subs.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-25 14:55
This issue only occurs when RSS is enabled by the user or forced by the application because the profile contains >= 125 subscriptions 

For everyone that needs to use FT right now, try the following workaround. 
- Create a profile with < 125 subscriptions and disable RSS under Subscription Settings

**Comment by karolyi** [comment] 2024-09-25 15:34
Problem is, I use the RSS feed exactly because the compiled feed will have youtube's controversial/shadowbanned channels and some videos removed, which isn't what I want.

I don't want any of YT's algorithms interfere with my subbed content. But then again, I'm sizing down my YT reliance and seeking out the important creators on alternative platforms anyway.

**Comment by glanduin** [comment] 2024-09-25 15:37
I think the issue is bigger than just a number of subscription limit. Because even if i just try to log in to

[https://www.youtube.com/feeds/videos.xml](url)

in Chromium or Firefox, i get exact same page as "karolyi" pasted:

![image](https://github.com/user-attachments/assets/73f151c7-3721-405b-ba8a-1a6ae0a76def)

So even if it is just one channel (or no channel), doesn't matter for google. RSS feed is unreachable. I am thinking that this might be an IP block. My ISP is assigning JGNAT ip addresses, so maybe that is causing the issue. Google just thinks certain IP addresses are basically spamming.

**Comment by karolyi** [comment] 2024-09-25 15:42
@glanduin it's basically yt's (google's) next step in erecting their walled gardens.

**Comment by glanduin** [comment] 2024-09-25 15:50
> @glanduin it's basically yt's (google's) next step in erecting their walled gardens.

I just tried with a VPN and i can reach RSS feeds. Without a VPN and with my own IP address, i get the "We are sorry" screen :)

So i am guessing that google has applied an IP block and banned our ip addresses (me and others whose subscription feed is not updating) from using the RSS feed option.

Freetube has a Tor proxy option. I wonder if we can utilize this to get around the block.

**Comment by karolyi** [comment] 2024-09-25 16:14
> Edit: I just reset my router and got a new ip address. My subscriptions were updated. So this ip is good, until i got a bad ip again? Or maybe google will ban this one too? I don't know.

I wouldn't be surprised when in the case of IPv6 addresses, they would just ban /64 subnets, because of SLAAC.

Funny thing is, with this move they don't just make FreeTube unusable, but other RSS readers as well, e.g. Feedly. But like I said, I think it's intentional.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-29 10:45
Closing as RSS should be up again

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-29 10:45 UTC
Labels: bug, B: content not loading
