### ISSUE TITLE
Age restricted videos not played by LocalAPI nor default invidious API

### ISSUE THREAD

**Issue by a-p-jo** [FreeTubeApp/FreeTube#1594] opened 2021-08-18 06:50 UTC
**Behavior of the program**
When an age restricted video is clicked (usually among the search results),  `Local API Error (Click to Copy) : Error: Status code: 410` is displayed and then it says `Falling back to Invidious API` , and lastly `Invidious API Error : undefined`. Clicking to view comments also does not work. Greyed out, empty video player.

**Environment Information (please complete the following information):**
 - OS: macOS
 - OS Version: macOS 11.4 (20F71)
 - FreeTube version: v0.13.2 Beta
 - Installation Method : .dmg from your website
 - Primary API Used: Local API, Invidious API default (invidious.snopyta.org).

**Additional context**
Using https://invidious.kavin.rocks as the invidious API fixes it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-08-18 06:55
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1296

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-08-18 06:55 UTC
Labels: bug
