### ISSUE TITLE
[Feature Request]: Remove video from playlist while playing the playlist

### ISSUE THREAD

**Issue by andriuhatm** [FreeTubeApp/FreeTube#5551] opened 2024-08-09 17:22 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

After watching a video (especially from a "Watch Later") playlist, I want to remove it from the list, but there is no easy way. I need to go back and find the video, or click on playlists, select watch later, find the video and remove it. Then start playing another video, and repeat the process.

Hope it makes sense. Sorry if there's already a request I've missed.

<img width="1217" alt="image" src="https://github.com/user-attachments/assets/85ed18a7-5f6e-45fe-b255-9ff514160cb2">

### Proposed Solution

Add a remove from playlist button next to Add to Favourites.

### Alternatives Considered

Add an option to the context menu of the video.
<img width="457" alt="image" src="https://github.com/user-attachments/assets/1a512aa1-39f9-419c-90e1-2557c041bc77">

### Issue Labels

ease of use improvement

**Comment by andriuhatm** [comment] 2024-08-09 17:38
I have found a workaround - to use "Enable quick bookmark with this playlist". But it's only going to work with one playlist.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-08-15 20:55
I consider this a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/547

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-08-15 20:55 UTC
Labels: enhancement, E: ease of use improvement
