### ISSUE TITLE
[Feature Request]: Audio only in resolution dropdown 

### ISSUE THREAD

**Issue by cardcraft** [FreeTubeApp/FreeTube#2249] opened 2022-05-18 01:01 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There is a way to set freetube to audio only through the settings. this is slow and inconvenient when just trying to listen to music

### Proposed Solution

Along with all the resolotion options have an Audio option. this could be used to save data and performace. 

### Alternatives Considered

A button next to the resolution options with an audio only toggle

### Issue Labels

ease of use improvement, new optional setting

### Additional Information

![freetube audio only](https://user-images.githubusercontent.com/61369184/168935997-298d0908-6b0c-4805-b3cf-4994f808b556.png)

**Comment by absidue** [comment] 2022-05-18 07:19
This issue can be closed as this feature already exists:
![change_format_button](https://user-images.githubusercontent.com/48293849/168980429-aeedd3c8-5b50-4316-90b3-a173ae6fb72d.jpg)

**Closed** 2022-05-18 07:20 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement

**Comment by Winterhuman** [comment] 2022-05-18 21:17
@absidue The issue isn't about the current audio format button: "There is a way to set freetube to audio only through the settings. this is slow and inconvenient when just trying to listen to music"

They're asking for an audio-only button just left of the video speed button on the video itself for easier access.

**Comment by absidue** [comment] 2022-05-18 21:19
The new button will end up doing the same thing as the format button, I see no good reason to add a second button close to the first one with redundant functionality.

**Comment by Winterhuman** [comment] 2022-05-18 21:22
True, it's technically easier to access since it's one click less (click Video Formats, then Audio Format vs. Click audio-only button), but yeah, redundant functionality might not be great
