### ISSUE TITLE
"Error: Status code: 404"

### ISSUE THREAD

**Issue by avincent98144** [FreeTubeApp/FreeTube#1458] opened 2021-06-26 14:29 UTC
With the latest build, sites subscriptions I daily check are now giving me this error message:

"Error: Status code: 404"

 and I see nothing blocked as no changes were made on my side to block anything free tube related. 

I could not find how to troubleshoot this *anywhere*!

**Comment by Tiltowait2** [comment] 2021-06-26 15:20
It's some highly technical problem I don't understand.  But the "solution" is to go into settings and change something called "Invidious Instance".  Something happened to the default so you have to change it to one of the others.  Even after this I still get videos that won't play.  

I'm just some dude that likes using a Youtube front-end, I can't study the tech behind it nor understand.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-06-26 15:21
Duplicate of #1438

**Closed** 2021-06-26 15:34 UTC
