### ISSUE TITLE
ERR_INVALID_ARG_TYPE error on Mac

### ISSUE THREAD

**Issue by rm-rf-home** [FreeTubeApp/FreeTube#755] opened 2020-10-31 21:12 UTC
**Behavior of the program**
Every time I click on a video in the app, it is loading indefinitely and showing the following error.
It started a few days ago and it's the same behavior in Subscriptions, Trending, History etc. Also the same happens when I paste a YouTube Link directly in the Search bar. I cannot watch any Video, but everything else seems to be working, Subscriptions are loading fine for example.
> TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined

**Expected behavior**
Video should start

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to Subscriptions for example
2. Click on a video
3. See error and red "loading bubble"

**Screenshots**
<img width="1201" alt="Screenshot 2020-10-31 at 22 06 29" src="https://user-images.githubusercontent.com/36776420/97790005-598f4180-1bc5-11eb-9acf-d633fecaad8b.png">

**Desktop:**
 - OS: macOS
 - OS Version: 10.15.7 (19H2)
 - FreeTube version: 0.9.1
 - FreeTube build: 0.9.1

**Comment by PrestonN** [comment] 2020-10-31 21:14
Please look for existing issues before creating new ones.

This is a duplicate of #733

**Closed by PrestonN** 2020-10-31 21:14 UTC
Labels: bug
