### ISSUE TITLE
Right click to slow down Playback Rate

### ISSUE THREAD

**Issue by Salyut9** [FreeTubeApp/FreeTube#1673] opened 2021-09-08 16:21 UTC
**Describe the solution you'd like to see implemented :**

As it is possible to increase the Playback Rate with a left-click on it, it would be nice to be able to reduce it with a right-click for example.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-08 17:06
Hi @Salyut9, this is a duplicate of
https://github.com/FreeTubeApp/FreeTube/issues/1559

If u want u can leave a comment over there.

I'll be closing this issue in order to prevent cluttering the backlog.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-09-08 17:06 UTC
