### ISSUE TITLE
[Feature Request]: Add a "recommended" (home) page

### ISSUE THREAD

**Issue by Tuquilo9** [FreeTubeApp/FreeTube#6024] opened 2024-10-29 21:31 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Re-create a similar experience to Youtube, where the user can easly find a video about a topic which interests him.

### Proposed Solution

My idea would be a page like the "Subscriptions" page and it would be based of recent searches, watched videos' recommendations and suscribed channels.

### Alternatives Considered

I'm my opion nothing.

### Issue Labels

new feature

### Additional Information

I hope my english was good and I provided enough informations!

**Comment by absidue** [comment] 2024-10-29 23:19
Duplicate of #677

**Closed** 2024-10-29 23:19 UTC
Labels: U: duplicate, enhancement, E: new feature
