### ISSUE TITLE
Region for Trending's list is unpopulated

### ISSUE THREAD

**Issue by Winterhuman** [FreeTubeApp/FreeTube#1644] opened 2021-09-05 12:23 UTC
**Behavior of the program**
In settings, the "Region for Trending" setting is completely blank with only the title, question mark, and down arrow visible. Clicking on the down arrow, or the blank space, causes the blue line that appears on selecting a setting to be highlighted. Where the menu for selecting a region is supposed to be is a thin grey line just under the highlighted blue line, the menu is being spawned as it's supposed to be, but, the menu isn't being populated so it appears as a collapsed line.

**Expected behavior**
The menu you get when changing the "Region for Trending" setting should be populated with countries and areas as normal, the blue line shown when a setting is selected for "Region for Trending" also shouldn't be highlighted.

**To Reproduce**
1. Go to 'Settings'.
2. Click on the down arrow, or the blank space, of "Region for Trending".
3. See the blue line under the setting become highlighted in pale blue and a menu spawn in a collapsed state with no items.

**Environment Information**
 - OS: Arch Linux
 - FreeTube version: 0.14.0 Beta
 - Installation Method: FlatHub
 - Primary API Used: Local API

**Comment by peepopoggers** [comment] 2021-09-05 17:22
Can confirm the region is not working.

**Comment by jasonhenriquez** [comment] 2021-09-05 17:25
Correct me if I'm wrong, but I believe this error only occurs when your Locale Preference has never been interacted with. Does the error persist after changing it?

**Comment by peepopoggers** [comment] 2021-09-05 18:27
@jasonhenriquez it works after locale change, however this is not intended design right?

**Comment by jasonhenriquez** [comment] 2021-09-05 18:33
Of course not, this is still a bug, but I just need to know when exactly the bug occurs so that we can best fix it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-27 10:41
Wait a second.... Isnt this a duplicate of #484

**Comment by peepopoggers** [comment] 2021-09-27 12:03
no

**Comment by Smurflicious** [comment] 2022-02-25 20:08
I have/had this bug, or something very similar, but on 0.16.0 Beta, I fixed the Trending Region dropdown by setting the Locale Preference first, as per Jason's comment. Set Trending region to UK, Trending page does not work. Set Trending region to US, Trending page still does not work. Tried restarting FreeTube several times. 

I get this error on the trending page "TypeError: Cannot read properties of undefined (reading 'match')".

No one above mentions if their trending page worked at all or if setting the trending region fixed the trending page. Possibly this bug needs to be escalated if others are getting the same problem??

**Comment by MarmadileManteater** [comment] 2022-10-17 15:20
I believe I have managed to replicate the issue described by OP on 0.17.1 by deleting my `settings.db` file.
![demonstrating-bug-on-0 17 1](https://user-images.githubusercontent.com/106682128/196214306-191b709d-610d-4cf7-b188-8e60f18b201d.gif)

The underlying issue is that the function responsible for fetching the region data (`getRegionData`) is only dispatched inside of the sideEffectsHandler for `currentLocale`. Usually, `grabUserSettings` will dispatch this function as soon as the app is mounted, but `grabUserSettings` currently only triggers the sideEffectHandlers for settings which have a value defined in `settings.db`.

![image](https://user-images.githubusercontent.com/106682128/196215896-493ed904-c0b9-4345-a9fd-41d74e66da56.png)

**Closed** 2022-11-23 12:51 UTC
Labels: bug
