### ISSUE TITLE
[Bug]: After long (hours) pause, the video cannot play anymore until refresh

### ISSUE THREAD

**Issue by truenicoco** [FreeTubeApp/FreeTube#5231] opened 2024-06-06 06:43 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Play any long video
2. Pause before the end
3. Wait several hours, eg, a night's sleep
4. Get back to the video and hit play
5. It plays for a few seconds (what was buffered probably) but then enters a "infinite loading loop"

### Expected Behavior

Resume play should be possible. Since there is no refresh button, the only way to continue watching is to switch to another page and open it back (eg, clicking back, then next).

### Issue Labels

content not loading

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Debian stable, but I have the same behaviour on Mac OS (M1)

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-06 07:07
Duplicate of #4160

**Closed** 2024-06-06 07:07 UTC
Labels: bug, B: content not loading

**Comment by truenicoco** [comment] 2024-06-06 07:08
Oops, sorry, I swear I did search but didn't realize this was a dupe…
