### ISSUE TITLE
Please Add optional setting for Default Caption or an optional setting for Translated subtitle.

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [FreeTubeApp/FreeTube#4760] opened 2024-03-12 06:06 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

First of All Please keep on great work. I have just used the latest FreeTube App on both Microsoft Windows 11 and Mac OS and. I Love it , however there are some options which could be improve. I know that I could have Different Local Preference language (in my Case Persian (Farsi) is my first language. and English is my second language.  I know even with the latest FreeTube beta apps also I could have a auto generated English Captions for Persian and Farsi too, however the current problem is whenever I play new video on FreeTube App I have to set again the captions and it doesn't keep the Caption Setting in order to have in my case Persian Subtitle, and this issue is general with other languages too. This is really critical issue with Latest FreeTube App. Sincerely,
Kindest Regards,
Pooya M

### Proposed Solution

set optional setting for remembering the default captions Language or optional setting for language subtitle.

### Alternatives Considered

set optional setting for remembering the default captions Language or optional setting for language subtitle.

### Issue Labels

display more information to user, ease of use improvement, improvement to existing feature, new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-03-12 06:14
Duplicate of #62

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-03-12 06:14 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: display more information, E: ease of use improvement, E: new feature
