### ISSUE TITLE
[Bug]: videos not loading after opening notebook lid

### ISSUE THREAD

**Issue by kenderipa** [FreeTubeApp/FreeTube#4281] opened 2023-11-04 18:50 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Start a video.
2. Pause the video.
3. Close the notebook lid.
4. Reopen notebook lid.
5. Play the video.

After the buffered chunk of the video is through, the video loads forever. FreeTube needs to be restarted to continue viewing the video.

### Expected Behavior

After reopening the lid video loads and plays normally.

### Issue Labels

content not loading

### FreeTube Version

0.19.1

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

?

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-04 19:28
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4159

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-04 19:28 UTC
Labels: bug, B: content not loading
