### ISSUE TITLE
Refresh Button / Function - Menu Bar Integration

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1958] opened 2021-12-20 22:34 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
The **"Refresh" option is available within the "Subscriptions", etc. needs to be directly integrated into the Menu Bar** instead of falling under each category.
Currently, this **"Refresh" option is just floating over and looks unrefined**, as it **needs a complete integration similar to the "Filter" option in terms of looks and function**.

**Describe the solution you'd like to see implemented**
From my personal experience, **this option needs to be near the "Filter" or the "Profile" option** to have a complete enclosure to the system, to have it available at search and at everywhere need.

**Screenshots**
![FreeTube_PBWrwtLgem](https://user-images.githubusercontent.com/96393348/146840924-574fcdab-d220-4cf1-bb82-f4327a85762e.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-12-21 16:53
This is already going to be implemented in PR https://github.com/FreeTubeApp/FreeTube/pull/1578

Duplicate of #1008

**Closed** 2021-12-21 16:54 UTC
Labels: enhancement
