### ISSUE TITLE
[Feature Request]: Bring back playback speed indicator

### ISSUE THREAD

**Issue by m3thm4th** [FreeTubeApp/FreeTube#6026] opened 2024-10-29 22:05 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

In v0.22.0 playback speed button is just an icon, previously it used to display the current playback speed

### Proposed Solution

Bring back previous behavior

### Alternatives Considered

Add a setting to let users decide which style they prefer

### Issue Labels

display more information to user, ease of use improvement, improvement to existing feature, new optional setting, visual improvement

**Comment by Giger22** [comment] 2024-10-30 13:33
My thread was closed...
https://github.com/FreeTubeApp/FreeTube/issues/5957

**Comment by 12people** [comment] 2024-10-30 14:27
The old one not just showed the speed, but also clicking it would toggle the speed up — which was an extremely useful shortcut for people like me.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-30 22:31
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5957

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-30 22:31 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: visual improvement, E: display more information, E: ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-30 22:38
@m3thm4th issuing a warning to you as you have opened multiple duplicates and false reports. Please respect the rules listed in the issue template.
