### ISSUE TITLE
Exiting PIP when not focused on the video page should force freetube to reopen the video's original page

### ISSUE THREAD

**Issue by rsmyst** [FreeTubeApp/FreeTube#1725] opened 2021-09-20 15:26 UTC
Here's what I usually do. 
Choose a video and being watching. 
Enter PIP mode and go back to homepage on freetube i.e. the page where you can see all the videos from your subscriptions.
Now, I expected freetube to just return to the video's original page when I clicked exit PIP mode. BUT, it always seems to just exit the video rather than going from the homepage to the video's page.
I really do hope this feature gets added soon since it's such a QOL feature for me. 
Thanks for the hard work!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-20 15:34
Hi @rsmyst this is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/624

If u want u can leave a comment over there.

I'll be closing this issue in order to prevent cluttering the backlog.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-09-20 15:34 UTC
Labels: duplicate, enhancement, doesn't follow template
