### ISSUE TITLE
[Bug]: play/pause hotkey not working properly

### ISSUE THREAD

**Issue by rebelcode-xr** [FreeTubeApp/FreeTube#3173] opened 2023-02-08 12:14 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. open a video
2. I click with the mouse on the fullscreen button (important!)
3. press spacebar to pause it
4. instead of pausing the video the space disables the fullscreen
5. if I press k (the other hotkey for play/pause) there's no effect

### Expected Behavior

I expect the video to play/pause pressing space or k on my keyboard.

### Issue Labels

keyboard control not working, usability issue

### FreeTube Version

0.18.0

### Operating System Version

Mac OS Monterey 12.6.3

### Installation Method

.dmg

### Primary API used

Local API

### Additional Information

It seems that clicking on whatever UI button (fullscreen in the example) activates some accessibility function.
In fact if I press TAB a square appears and I can interact with the UI without the mouse, using space to simulate the "click".
<img width="263" alt="image" src="https://user-images.githubusercontent.com/63522951/217523478-f8599c03-bae7-4b55-a6ab-9bfa54f96975.png">

That's why pressing space after click on whatever button doesn't have the expected behaviour.
In order to have space/k to play/pause I need to click on the video, then the hotkey works again.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-02-08 19:57
Can confirm that this is happening in the nightly builds

**Comment by absidue** [comment] 2023-02-08 21:19
duplicate of #766 and #637

**Closed** 2023-02-08 21:20 UTC
Labels: bug, U: duplicate, B: keyboard control, B: usability

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-02-08 21:51
@absidue are u sure these issues are similar? I had the feeling that this wasn't the case in other versions. I did not verify this though

**Comment by absidue** [comment] 2023-02-08 21:56
@efb4f5ff-1298-471a-8973-3d47447115dc the video.js buttons have always kept the focus, until you click or tab away, they made the decision to go the more accessible route.

**Comment by rebelcode-xr** [comment] 2023-02-09 00:45
> duplicate of #766 and #637

I couldn't find those issues, sorry. So I was right that "space" acts also as a "click" when the focus is stolen, but the "k" hotkey should work all the time, but it doesn't! When the focus is on a button the "k" does nothing.
Would help also accessibility to have a key that always play/pause (normally is space).

**Comment by absidue** [comment] 2023-02-09 15:48
The focus isn't stolen, it's standard web browser behaviour that if you click on a link or a button, it receives focus and keeps it until the focus is changed to something else, either by you, the code in the website or by the web browser if the focussed element no longer exists.

So when you click on the fullscreen button you activate it but also focus it.

Yes, quite a few things that act as buttons in FreeTube don't have that behaviour, but that is because they aren't actually buttons and we haven't written any code to replicate the standard behaviour, e.g. the refresh subscriptions button is an image that we've added a click trigger to.

Other players probably have to code to change the focussed element after you've clicked a button in them, video.js doesn't. We'll have to look into why pressing keys other than space and enter, doesn't reach our keyboard event handler, it's possible that video.js is swallowing the event before it reaches our code but I can't say for sure without looking into it.

**Comment by rebelcode-xr** [comment] 2023-02-09 18:45
Thank you for the explanation, hope you can find the issue! 😸

I was looking for an hotkey to reset the focus in order to create a rule in BetterTouchTool and override the current behaviour, but I couldn't find it.
The easiest temporary solution I found is to use "f" or "s" and avoid the UI buttons.
