### ISSUE TITLE
Player - Manual quality change issue

### ISSUE THREAD

**Issue by Jimmymax297** [FreeTubeApp/FreeTube#965] opened 2021-01-21 20:46 UTC
**Behavior of the program**
Manual quality change in the player can result in multiple options selected or none.

**Expected behavior**
Manual quality change should set the quality to the one desired by the User.

**Preconditions**
- User has videos in their Subscriptions tab

**To Reproduce**
1. User opens a video from their Subscriptions tab
2. User changes quality of the video to a different one
3. User changes quality of the video to different ones for some time
4. Observe results shown on the quality list

**Screenshots**
![Odtwarzacz - Manualna zmiana jakości](https://user-images.githubusercontent.com/33980616/105409987-92254100-5c31-11eb-9a88-43ba1e554c50.PNG)
Please also see attached GIF
https://drive.google.com/file/d/1qaG25ovZq-EovyXue9noFoBsNTFTfrA6/view?usp=sharing

**Environment Information (please complete the following information):**
 - OS: [Windows]
 - OS Version: [Windows 10]
 - FreeTube version: [0.11.1]
 - Primary API Used: [Local API]

**Comment by PrestonN** [comment] 2021-01-21 21:04
Duplicate of #595

**Closed by PrestonN** 2021-01-21 21:04 UTC
Labels: bug
