### ISSUE TITLE
[Feature Request]: Setting a custom caching/bufferring goal 

### ISSUE THREAD

**Issue by t3dium** [FreeTubeApp/FreeTube#3144] opened 2023-02-01 22:09 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

in instances where you tend to skip the video a lot, or using an unstable invidious instance where it may be fast at one point, but slow soon after, setting a higher buffering/caching goal would help.

### Proposed Solution

adding an option in settings to allow entering a custom value in seconds for the caching/buffering goal.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-02-02 17:47
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/678

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-02-02 17:47 UTC
Labels: enhancement, E: new feature
