### ISSUE TITLE
[Bug]: Starts up with a grey window

### ISSUE THREAD

**Issue by hollunder** [FreeTubeApp/FreeTube#2167] opened 2022-04-06 12:29 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Launch freetube.

### Expected Behavior

Working application.

### Issue Labels

content not loading

### FreeTube Version

freetube@0.16.0

### Operating System Version

Arch Linux

### Installation Method (If applicable)

other

### Additional Information

Built from AUR https://aur.archlinux.org/packages/freetube-git or https://aur.archlinux.org/packages/freetube.

```$ freetube                   
[17150:0406/142712.219062:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[17150:0406/142712.219112:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[17198:0406/142712.287597:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/unique_ptr.h:659: typename std::add_lvalue_reference<element_type>::type std::unique_ptr<blink::CSSSelector []>::operator[](std::size_t) const [_Tp = blink::CSSSelector [], _Dp = std::default_delete<blink::CSSSelector []>]: Assertion 'get() != pointer()' failed.```

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-04-06 12:58
Duplicate of #2163

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-04-06 12:58 UTC
Labels: bug, B: content not loading
