### ISSUE TITLE
[Feature Request]: Option to limit SponsorBlock to channels you're not subscribed to

### ISSUE THREAD

**Issue by enrrari** [FreeTubeApp/FreeTube#5549] opened 2024-08-09 15:40 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

'Tis not really a problem. I am not a user of SponsorBlock per se. Or rather, I do not auto-skip (I do have it show on the bar). However, the idea seems interesting that one could have SponsorBlock affect only channels one is not subscribed to. For channels one is subscribed to, there is already an interest in the creator and/or their content, but that's not always the case for channels one does not subscribe to. Being able to “get to the point” on a video one stumbled upon somehow, whether through their own search or a shared link somewhere, instead of sitting through intros, outros, breaks, sponsor segments, etc. Akin to skipping the life story before a recipe online (an experience I've only ever heard of, as I seek not recipes online)

### Proposed Solution

The proposed “solution” (feature) would be an option within SponsorBlock settings to enable SponsorBlock only for videos from channels to which one is not subscribed (or, if you will, disable SponsorBlock on subscribed channels). The option would work as described, doing SponsorBlock as usual on general videos but ignoring it on channels you're subscribed to.

I am willing to help, if needed. I know JavaScript (and CSS, and could learn the other languages on the project, if needed). Not sure how easy it is to get contributing to this project (I lack experience contributing to FOSS, though I did work with GitHub professionally for a few months)

PS: I'm not sure whether this constitutes a “new feature” or an “improvement to existing feature”, seeing as SponsorBlock is already a feature, but what I'm describing is not (yet) an option. I'll set it to “improvement”, but I can change if needed

### Alternatives Considered

Given this is not an issue onto itself, I reckon no alternative is needed. Though an alternative to such solution could be simply a user having segments set to show on bar and skip (or, as I sometimes do, speed up) specific segments one does not care to watch

### Issue Labels

improvement to existing feature, new optional setting

**Comment by Aiz0** [comment] 2024-08-22 21:07
I'd like to be able to limit DeArrow titles and thumbnails to certain channels.

**Comment by Cat333Pokemon** [comment] 2024-09-01 20:24
Instead of opening a new feature request, I'm going to comment on this one because my request is similar. **DeArrow** is really useful, but I don't use it because several of my subscriptions lose their consistent titles and thumbnail format.

I'd suggest adding a few toggles for DeArrow to apply to:

- [ ] Subscriptions (toggling this would enable/disable for all profiles)
  - [ ] Profile 1
  - [ ] Profile 2
  - [ ] Profile 3
- [ ] Trending
- [ ] Popular
- [ ] Search results
- [ ] Recommended videos

Always use SponsorBlock/DeArrow on these channels: ________
Never use SponsorBlock/DeArrow on these channels: ________
(For these last two, use the same UI element as the "Hide Videos From Channels" in the *Distraction Free Settings*.)

Likewise, this same set of options could also exist for SponsorBlock.

Perhaps, it could also be possible to add a "DeArrow this video" option to the triple-dots menu for any video.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-06 09:07
basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4991

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-06 09:07 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: new feature
