### ISSUE TITLE
[Bug]: No Title bar in Nightly version on KDE plasma

### ISSUE THREAD

**Issue by zestygrass** [FreeTubeApp/FreeTube#3726] opened 2023-07-04 15:19 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

After upgrading to the latest nightly build from github nightly-3083 to be specific. I noticed the title bar is not there anymore.
Not sure the cause, Otherwise the application works fine.

### Expected Behavior

Title bar should  be present.

### Issue Labels

visual bug

### FreeTube Version

0.18.0-nightly-3083

### Operating System Version

ArchLinux, Kernal V6.4.1 KDE Plasma 5.27.6

### Installation Method

.deb

### Primary API used

Local API

### Additional Information

![Screenshot_20230704_160840](https://github.com/FreeTubeApp/FreeTube/assets/121700814/8c730afc-2531-41d8-9d74-a5c9d5eca4e5)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-07-04 15:20
hi @zestygrass could u try pressing f11

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-07-04 15:21
Also duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3220

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-07-04 15:21 UTC
Labels: bug

**Comment by zestygrass** [comment] 2023-07-04 15:23
@efb4f5ff-1298-471a-8973-3d47447115dc F11 did the trick. Thanks for the tip. 
Sorry for the duplicate issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-07-04 15:34
No worries :) I'm glad that it worked for u!
