### ISSUE TITLE
[Feature Request]: Add labels to seek bar for timestamped sections

### ISSUE THREAD

**Issue by Robert-LC** [FreeTubeApp/FreeTube#5874] opened 2024-10-15 20:48 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When a video has timestamped sections in the description, the seek bar is automatically sliced up to denote those sections. In YouTube, along with a thumbnail of the current frame it also says the name of the section, this is very useful in long videos specially tutorials.

This would help make the timestamped section more useful, as of right now I still have to look at the description, without the labels it makes the sections on the bar much less useful, and saves me from having to open the description.

### Proposed Solution

Read the description, in the same code where you set the thumbnail and sections on the seek bar, add the label from the description onto it.

### Alternatives Considered

N/A

### Issue Labels

display more information to user, ease of use improvement, improvement to existing feature

**Comment by absidue** [comment] 2024-10-16 04:12
Duplicate of #2829

**Closed** 2024-10-16 04:13 UTC
Labels: enhancement, E: improvement existing feature, E: display more information, E: ease of use improvement
