### ISSUE TITLE
[Bug]: electron window not opening in local development

### ISSUE THREAD

**Issue by 80avin** [FreeTubeApp/FreeTube#6296] opened 2024-12-07 09:41 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Do a fresh clone of FreeTube
2. Run `yarn install`
3. Run `yarn run dev`

Notice that the script gets stuck at following status
![image](https://github.com/user-attachments/assets/8c92a717-21e8-42b4-851b-fa2e8bba0807)

It also happens if I build the appimage and run it.

### Expected Behavior

Electron window should popup

### Issue Labels

causes crash, only happens in developer mode

### FreeTube Version

0e8db50ed07d0b721104031c1cfc81721cdbbe38

### Operating System Version

Kubuntu 24.04 ( Linux avinash-Nitro-AN515-45 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux )

### Installation Method

other

### Primary API used

Local API

### Additional Information

I think major issue is that [logging is disabled](https://github.com/FreeTubeApp/FreeTube/blob/59590d77316f4777859c1ab4e60d1ab7268be667/_scripts/dev-runner.js#L67-L71) in local, which prevents me from debugging it.

After I enable logging, I can find that the issue is
https://github.com/electron/electron/issues/42510
![image](https://github.com/user-attachments/assets/21f31a2f-a94d-4b8f-9958-5c91f155cfc1)

which can be worked around by adding `--no-sandbox` flag to the electron.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-07 09:45
duplicate of #5952

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-07 09:45 UTC
Labels: bug, B: crash, B: developer mode

**Comment by absidue** [comment] 2024-12-07 10:06
Passing --no-sandbox to disable Electron's security is definitely not the correct solution, the problem in this case is that Ubuntu is too restrictive by default and requires you to set up AppArmor profiles to run various applications.

**Comment by 80avin** [comment] 2024-12-07 10:10
@absidue Understandable.

Suspecting something similar, I only added it as a comment and the main focus was kept on increasing the visibility.
Otherwise, the errors are quite opaque to new contributors, which can possibly decrease the number of new contributors.
