### ISSUE TITLE
Add the ability to queue up videos from recommended as a de-facto playlist ala the youtube webapp

### ISSUE THREAD

**Issue by elitecoder27** [FreeTubeApp/FreeTube#4314] opened 2023-11-11 03:10 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

on the youtube web frontend you can make a queue out of videos from recomended or via search when in miniplayer mode. you cannot do that on freetube 
![ezgif-3-53ca9fd59c](https://github.com/FreeTubeApp/FreeTube/assets/85319456/58d66787-854a-4388-9bd0-fab5d98b4931)

### Proposed Solution

just add an "add to queue" button

### Alternatives Considered

there are no alternatives for this issue. as there are no necessary ones anyways

### Issue Labels

ease of use improvement, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-11 06:39
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/547

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-11 06:39 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement
