### ISSUE TITLE
No Videoload

### ISSUE THREAD

**Issue by Gittahubble** [FreeTubeApp/FreeTube#1454] opened 2021-06-25 16:35 UTC
There is an API-Error. No Videos load. 

Here is a Screenshot: https://whisp.ly/r/jJHzyCl#Xyi0zcAYqrCx6

**Comment by zvkfhapjg** [comment] 2021-06-25 17:02
I'm having the same issue

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-06-25 17:11
Duplicate of #1438

**Closed** 2021-06-25 17:49 UTC
Labels: bug
