### ISSUE TITLE
Add word wrap for comments

### ISSUE THREAD

**Issue by altwarg** [FreeTubeApp/FreeTube#1240] opened 2021-04-30 06:38 UTC
**Behavior of the program**
Sometimes a comment contains a very long word (e.g. "LOLOLOLOLO..."). These words are out of comments bounds.

**Expected behavior**
All long words in comments must have word wrap.

**To Reproduce**
1. Go to some video with long comment
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/34391398/116657518-39371880-a997-11eb-8378-3cbb017486b3.png)

**Environment Information (please complete the following information):**
 - OS: Windows 10
 - FreeTube version: 0.12.0 beta
 - Installation Method (If applicable): Portable
 - Primary API Used: Local API

**Comment by Svallinn** [comment] 2021-04-30 14:06
Do you mind providing a link to a video in which that kind of comment exists?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-05-01 00:45
Duplicate of #856 
See 11.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-04 22:01
Going to close this one. I'll recommend to u to make an comment in the issue i linked.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-09-04 22:01 UTC
Labels: bug
