### ISSUE TITLE
[Bug]: Quality selector only displays 360p/720p despite Youtube offering a full range of options

### ISSUE THREAD

**Issue by Tiltowait2** [FreeTubeApp/FreeTube#2266] opened 2022-05-25 06:02 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

I have an unstable connection so I use the "downgrade my video so it doesn't stall out" features. Usually it works fine. Lately I've been noticing that more of my videos are stalling out.  I keep my Default Quality setting on "auto".   When this stalling happens, I see that there are only two choices for resolution: 360p and 720p.  I open the video in Youtube.com and the player displays the full range of options from 1080p to 144p.  Previously the 360/720 binary option only existed on livestreams, which is reasonable, but now it seems to be on all videos.  

### Expected Behavior

I expect FreeTube to act as it always has, offering the same range of resolutions as Youtube.com does.

### Issue Labels

feature stopped working, usability issue

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Windows 8.1

### Installation Method (If applicable)

.exe

### Last Known Working FreeTube Version (If Any)

v0.15

### Primary API used

Local API

### Additional Information

The video I was watching when it stuttered and stopped and I got motivated enough to post an issue was https://youtu.be/6Ta_eum5hdU but it appears to be a general issue.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-05-25 16:16
Cant seem to reproduce your issue. Just for clarification while using the Local API u have 720p and 360p formats available on every video u watch?

**Comment by Tiltowait2** [comment] 2022-05-27 11:05
Yes.  Those are the ONLY formats available.  Usually Youtube offers 144p, 240p, 360p, 480p, 720p, 1080p.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-05-27 11:59
Can u provide examples of videos where this is happening?

**Comment by Tiltowait2** [comment] 2022-05-28 12:23
Have you set Player Settings -> Default Quality -> Auto
and Default Video Format -> Legacy Formats

The gear icon (open quality selector menu) only displays 360/720 on every single video.  I literally cannot get it to display 144/240/etc on **any** video.  

Here is the video I was watching when I wrote this post: https://youtu.be/Y0VSE3qfR_A?t=17

**Comment by Tiltowait2** [comment] 2022-05-28 12:27
I think I figured out how to post a screenshot finally
![1](https://user-images.githubusercontent.com/50357641/170825488-4641b8f9-442f-49e4-9b26-22a2278f2a9d.jpg)
![2](https://user-images.githubusercontent.com/50357641/170825490-e060c1ff-7b8c-4a1a-bb99-88b551ca623f.jpg)

[https://i.postimg.cc/qzvckzy9/1.jpg](url)

[https://i.postimg.cc/ZCs804L0/2.jpg]()

**Comment by Tiltowait2** [comment] 2022-05-28 12:28
It appears I clicked a wrong button somewhere and messed up the status of this post. :*

**Comment by alekksander** [comment] 2022-05-28 16:45
switched back to invidious and 1080 is back for me.

**Comment by PrestonN** [comment] 2022-05-28 20:27
Your instance of FreeTube is set to use legacy formats which are capped out at 720p. You must switch to DASH formats if you'd like more options, including lower quality ones.

You can find more information about this here: https://docs.freetubeapp.io/usage/video-formats/

What you described here is working as intended. We already have open issues for the buffering problem so I will go ahead and close this.

**Closed by PrestonN** 2022-05-28 20:27 UTC
Labels: bug, B: usability, B: feature stopped working

**Comment by Konglomneshued** [comment] 2022-12-13 02:10
I'm having this same issue still.  My default video format is DASH.
![image](https://user-images.githubusercontent.com/94726665/207208707-67ab82a1-53ce-45fc-b49a-7dbe80e7f4c1.png)

Video I watch: https://www.youtube.com/watch?v=bHJZGBmmEdA

On FreeTube:
[Screencast from 2022-12-12 20-05-21.webm](https://user-images.githubusercontent.com/94726665/207208737-31bc1046-0fca-4b91-8f42-7e241150013a.webm)

On Youtube:
[Screencast from 2022-12-12 20-06-38.webm](https://user-images.githubusercontent.com/94726665/207208767-8a02b7f7-a955-4f4f-8773-dbfa3d880499.webm)

**Comment by m-delc** [comment] 2023-04-13 17:52
I am having this exact same issue. v0.18.0 Beta

**Comment by Taarsier** [comment] 2025-04-30 19:43
I have the Problem that i only get 360p as option despite having DASH is Default.

![Image](https://github.com/user-attachments/assets/f7a732d2-ac9c-4ba4-92ac-07c5ebf08eee)

v0.23.4 Beta
