### ISSUE TITLE
[Feature Request]: Block users in comments

### ISSUE THREAD

**Issue by defski** [FreeTubeApp/FreeTube#2209] opened 2022-04-19 15:38 UTC
### Guidelines

- [x] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I'd like a way to block user comments that I'd rather not see. A place in settings to enter usernames to block would be nice, or maybe a text filter.

### Proposed Solution

n/a

### Alternatives Considered

n/a

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-04-19 16:32
Duplicate of #95

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-04-19 16:32 UTC
Labels: enhancement, E: new feature
