### ISSUE TITLE
[Bug]: 100% thread usage upon network loss with Ethernet and switch box

### ISSUE THREAD

**Issue by RandomHashTags** [FreeTubeApp/FreeTube#6483] opened 2024-12-30 11:58 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Watch a video
2. Lose network connection (using Ethernet and a switch box)
3. Wait for video to buffer
4. Gets stuck in an infinite loop using 100% of a thread, spiking temps and crippling system

### Losing network connection

I lost network connection intermittently from my provider due to their servers rebooting. However, the setup I have allows me to reproduce the bug with 100% success rate using a switch box. I just unplug the source Ethernet from the switch box and the problem occurs.

Here a few things that don't reproduce the problem:
- Disabling network on the system
- Unplugging the Ethernet cord from the system
- Unplugging the Ethernet cord for the system from the switch box

Worth noting that it never recovers from this state even if network is restored. I have to close the video to stop it.

### Expected Behavior

1. Watch a video
2. Lose network connection
3. Wait idly for network connection to be restored to resume video

Worth noting that it does wait idly if the network is lost some other way than described above.

### Issue Labels

usability issue

### FreeTube Version

v0.22.1 Beta

### Operating System Version

6.12.7-arch1-1 (Arch Linux, x86_64)

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.22.1 Beta

### Additional Information

I did not test with a nightly build.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-30 12:07
Is already fixed by https://github.com/FreeTubeApp/FreeTube/pull/6180

**Comment by absidue** [comment] 2024-12-30 12:07
Already fixed by #6180 on the development branch/nightly builds and this issue is a duplicate of the issues that that pull request closed.

**Closed** 2024-12-30 12:07 UTC
Labels: bug, B: usability, B: Unofficial Download
