### ISSUE TITLE
[Bug]: There was an issue downloading "video"

### ISSUE THREAD

**Issue by linlinxza** [FreeTubeApp/FreeTube#2211] opened 2022-04-20 20:22 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Click download
2. Select format to download
3. Wait
4. There was an issue downloading "video"

### Expected Behavior

Should download the video.

### Issue Labels

API issue

### FreeTube Version

0.16.0 beta

### Operating System Version

Ubuntu 20.04

### Installation Method (If applicable)

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-04-20 21:18
Duplicate of #2110

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-04-20 21:18 UTC
Labels: bug, B: API issue
