### ISSUE TITLE
[Feature Request]: A way to block videos and channels 

### ISSUE THREAD

**Issue by Somethingelseuk** [FreeTubeApp/FreeTube#4189] opened 2023-10-19 06:01 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

We need a way to block videos and channels
maybe a not interested or a never show this video again, with the option to block the channel

### Proposed Solution

A option to block channels

### Alternatives Considered

a not interested in this video option

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-19 07:54
Under the distraction free settings you can there is a setting called Hide Videos From Channels. That will block all videos from a channel.

The mark videos as not interested is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1362

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-10-19 07:54 UTC
Labels: enhancement, E: new feature

**Comment by PMTabs** [comment] 2023-10-22 18:52
It would be a great time-saver if we could add channels to the "Hide Videos From Channels" page with the right-click context menu (i.e. right-click the channel name, then click "Block" or something like that), rather than having to manually copy and paste it into the settings.

**Comment by Alexander-Wilms** [comment] 2023-11-11 21:13
I imported my BlockTube channel list this way:

- Copy channel list to text editor
- Search and replace`\n//.*\n` with empty string
- Replace `\n` with `\",\"`
- Prepend `{"_id":"channelsHidden","value":"[\"`
- Append `]"}`
- Copy the text to ~/.var/app/io.freetubeapp.FreeTube/config/FreeTube/settings.db

Maybe I'll try to add this to FreeTube.
