### ISSUE TITLE
[Feature Request]: Ability to configure data location

### ISSUE THREAD

**Issue by martinlindhe** [FreeTubeApp/FreeTube#6454] opened 2024-12-25 17:00 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I want to sync my freetube settings between a Windows and a macOS computer and in order to do that I would like to override the default data location for my installs to point to my ~/Sync folder.

### Proposed Solution

Ability to configure a override for "data location", the defaults are documented here: https://docs.freetubeapp.io/usage/data-location/

### Alternatives Considered

Symlink but it fails considering the Windows machine.

Some related discussion in #746

### Issue Labels

support for external software

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-25 17:14
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/370

**Comment by martinlindhe** [comment] 2024-12-25 21:42
> Duplicate of #370

If I am reading #370 correctly, (comment #2), then it is about implementing WebDAW in order to sync files?

That is unrelated to my request as I really would prefer just to be able to configure location in order to chose my own sync solution. Your project do not need to include syncing in your roadmap, there is already solutions for that, just help us to use them by allow us to change file locations.

**Comment by absidue** [comment] 2024-12-26 11:40
I would highly recommend using symlinks (yes you can use symlinks on Windows 10+ https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/), alternatively you can pass the Chromium `--user-data-dir=/path/to/different/folder` flag every time you launch FreeTube.

Closing as it is already possible by symlinking the individual databases (the recommended and supported way) or the Chromium flag (should work but we don't test it, so use it at your own risk).

**Closed by absidue** 2024-12-26 11:40 UTC
Labels: U: duplicate, enhancement, E: support external software
