### ISSUE TITLE
[Feature Request]: I would like to have the option to hide shorts

### ISSUE THREAD

**Issue by sint-f** [FreeTubeApp/FreeTube#2440] opened 2022-08-01 19:00 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

i dont watch shorts (1 minut videos).
there is a channel that i like to watch but puts 5 shorts a day.
because of that my subscription page isnt a nice view.

### Proposed Solution

blocking videos that are a minut or below and have a certain resolution.

### Alternatives Considered

a way to block words.
if i can block the word shorts, the problem is not fixed but there are a lot of shorts that has the word shorts or short in it.

### Issue Labels

ease of use improvement, new feature, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-01 22:04
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2008

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-08-01 22:04 UTC
Labels: enhancement, E: visual improvement, E: ease of use improvement, E: new feature

**Comment by Flashwalker** [comment] 2023-03-13 18:24
Shorts must die!
