### ISSUE TITLE
[Feature Request]: Ability to search for videos and load FreeTube via the terminal

### ISSUE THREAD

**Issue by rhysday** [FreeTubeApp/FreeTube#2447] opened 2022-08-03 01:24 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I want to be able to use a terminal command to search and launch FreeTube, so that I can search for videos straight from dmenu without first having to open FreeTube and then searching.

### Proposed Solution

Terminal command to search for a video via FreeTube 

### Alternatives Considered

.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-03 01:37
basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1619

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-08-03 01:37 UTC
Labels: enhancement, E: new feature
