### ISSUE TITLE
Error Calling Youtube API

### ISSUE THREAD

**Issue by smh020** [FreeTubeApp/FreeTube#81] opened 2018-05-03 20:31 UTC
![image](https://user-images.githubusercontent.com/15349123/39601295-5034baca-4ed6-11e8-8931-8be713fc394c.png)
stopped working today.

**Comment by LexHimself** [comment] 2018-05-03 20:45
Seems to work fine here, perhaps a temporary problem with the api key used at that time?

**Comment by aproposnix** [comment] 2018-05-04 19:44
I had the same problem last night. There was definitely a problem.

**Comment by PrestonN** [comment] 2018-05-04 22:58
Nothing seems to be out of the ordinary with the API keys.  I never noticed anything either through my personal usage of the app.  Is this problem still happening?  Were only certain aspects of the app not working or was it everything?  It's possible something could have happened with one of the API keys but it doesn't look like it on my end.

**Comment by aproposnix** [comment] 2018-05-05 16:37
@PrestonN I think it was on the side of Google. It stopped working, I then removed my API key... it didn't work at first but then just starting working. Eventually I added my key again and it worked.

**Comment by PrestonN** [comment] 2018-05-10 22:25
If this isn't a problem anymore then I am going to close this issue.  If you see this pop up again, please make a new issue.  Thanks.

**Closed by PrestonN** 2018-05-10 22:25 UTC

**Comment by damko** [comment] 2018-08-04 05:28
no the problem is still here. It depends on the moment. Sometimes I can't fetch anything. Some other times I get a handful of results but most of the chances today it doesn't work. It looks like a youtube issue.

**Comment by aproposnix** [comment] 2018-08-05 07:48
I've noticed that, for me, I have this problem every morning (CET). I don't think it's Freetube though.
