### ISSUE TITLE
[Feature Request]: Possiblity to update a playslit copied from sombody else (who updates it regularly)

### ISSUE THREAD

**Issue by Janaue** [FreeTubeApp/FreeTube#5646] opened 2024-09-04 13:10 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I copied this playlist https://www.youtube.com/playlist?list=PL6HEDhK_szHTPIHX6XJ2wADFMxiJt-XeG into a personal one and I expected it would get updated when there's a new video from the owner of the channel who updates its own playlist.

### Proposed Solution

So it would be nice to have a button on copied playlists to retrieve manually the latest videos.

### Alternatives Considered

NA

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-04 13:12
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/312

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-04 13:12 UTC
Labels: enhancement, E: improvement existing feature
