### ISSUE TITLE
[Feature Request]: Some YouTube videos have too low sound volume.

### ISSUE THREAD

**Issue by CornFromHell** [FreeTubeApp/FreeTube#5258] opened 2024-06-12 18:41 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There are still videos where the sound volume is turned up to 100, but the sound is still tinny. I would like to see Freetube automatically detect and normalize the volume, or have an additional feature that allows users to manually turn up the volume.

### Proposed Solution

https://github.com/valpackett/soundfixer I think providing something similar to soundfixer would solve the problem.

### Alternatives Considered

If there were shortcuts to manipulate FFmpeg's filters, this would be a simple fix.

F1 af toggle "lavfi=[loudnorm]" ; show-text "loudness normalization"
F2 af toggle "lavfi=[alimiter=10:1:1:5:8000]" ; show-text "Audio limiter enabled"
F3 af toggle "lavfi=[pan=1c|c0=0.5*c0+0.5*c1]" ; show-text "Audio mix set to Mono"
F4 af set "" ; show-text "Reset Audio Filters"

Ctrl+Alt+Right no-osd cycle-values video-rotate  "90" "180" "270" "0"
Ctrl+Alt+Left no-osd cycle-values video-rotate  "270" "180" "90" "0"

] add speed 0.1
[ add speed -0.1

Ctrl+Wheel_Up add volume  5
Ctrl+Wheel_Down add volume -5

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-12 18:57
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1551

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-06-12 18:57 UTC
Labels: enhancement, E: ease of use improvement
