### ISSUE TITLE
Save Playlist

### ISSUE THREAD

**Issue by hyblocker** [FreeTubeApp/FreeTube#1170] opened 2021-04-06 21:43 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
The ability to save playlists seems to be missing. I'd like to save playlists in order to watch them later. If the feature is implemented the means to save a playlist should be better communicated to the end user.

**Describe the solution you'd like to see implemented**
A simple and clear button to save playlists

**Describe alternatives you've considered**
Saving videos is a workaround but playlists tend to get updated, defeating the purpose, and on the other hand, saving a playlist's videos manually is cumbersome

**Screenshots**
N/A

**Additional context**

**Comment by GilgusMaximus** [comment] 2021-04-07 11:00
Duplicate of #312

**Closed by GilgusMaximus** 2021-04-07 11:00 UTC
Labels: enhancement
