### ISSUE TITLE
[Feature Request]: Keyboard shortcuts for navigating FreeTube

### ISSUE THREAD

**Issue by enrrari** [FreeTubeApp/FreeTube#5888] opened 2024-10-17 18:03 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I'd like to propose adding more shortcuts, such that FreeTube is even better to use, and navigating around is made easier, when using the keyboard (read: better navigation via keyboard, less 'tab'ing to get to buttons).

### Proposed Solution

 I have two suggestions: 

* Shortcuts for the "tabs" on the left (subscriptions, playlists, history, etc.). I kinda like the way Microsoft does it with their software, where one can press, say, Ctrl+n, in which 'n' refers to the item order on the list, and it takes them to that "tab." Say I have subscriptions, channel list, playlists, history. Pressing Ctrl+2 would take me to "channel list", regardless of where I am within the app. With such shortcut, one could more easily reach these other parts of the app via keyboard without having to tab around to get to the button.

* Shortcuts to switch between "tabs" in the subscription feed (videos, shorts, live, community). Ctrl+Tab could work great for this. If I am in "videos", for instance, Ctrl+Tab (or your shortcut of preference) could switch to "shorts". Another Ctrl+Tab would take me to "live".

These are but some suggestions. Would be interesting having more ways to navigate FreeTube more easily with the keyboard.

### Alternatives Considered

I don't really have any alternative solutions. Users could just use the mouse, or tab around with their keyboard.

### Issue Labels

ease of use improvement, new keyboard shortcut

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-17 19:18
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2691

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-17 19:18 UTC
Labels: enhancement, E: ease of use improvement, E: keyboard shortcut
