### ISSUE TITLE
[Feature Request]: You Might Like Page

### ISSUE THREAD

**Issue by hutonahill** [FreeTubeApp/FreeTube#4307] opened 2023-11-09 11:41 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I miss YouTube's algorithm. Yea it sucked in some ways, but when I was looking to veg out and had existed my subscription list, it was great.

. 

### Proposed Solution

As a kind of sudo algorithm, you could have a page called You Might Like. This would be very similar to a subscription page. it would look at the last 20 channels, not on your subscription list, where you watched videos, and would show you a selection of those videos

### Alternatives Considered

N/A. this is an alternative. legit algorithms are invasive and kinda against your ideals. If you don't what to do this i am not sure what you would do.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-09 11:51
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/677

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-09 11:51 UTC
Labels: enhancement, E: new feature
