### ISSUE TITLE
[Feature Request]: Play All for Channels

### ISSUE THREAD

**Issue by ParasiteDelta** [FreeTubeApp/FreeTube#4776] opened 2024-03-18 06:23 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

In NewPipe (or Tubular), there exists a button to automatically play the entire channel's content. This is good for everything from background noise to a sleep timer. Having something similar here would also greatly help in the case of people like me, where we generally use YouTube for random background noise or sideline content at best, and don't want to have to drain our phones playing YouTube videos when we have our computers right there. 

### Proposed Solution

Implement a Play All button for the Channel view, perhaps just a button next to the Channel Name, which gathers all of the channel's content and plays it sequentially. Bonus points for making the Play All button respect the Sort By filter, so you could start from the newest video or the oldest.

### Alternatives Considered

Draining my phone's battery to play YouTube via NewPipe, Tubular, or even Grayjay isn't viable or reasonable when I have access to a full-scale computer.

### Issue Labels

ease of use improvement, new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-03-18 07:19
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/629

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-03-18 07:19 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement, E: new feature

**Comment by ParasiteDelta** [comment] 2024-03-20 14:06
A duplicate of a four-year old Issue that was never resolved, yes.

**Comment by absidue** [comment] 2024-03-21 12:07
FreeTube is maintained by a small number of volunteers in their spare time, so we don't have time to get to everything quickly. Also fixing bugs is generally a much higher priority than constantly adding new features, because that means an existing feature is broken, don't forget about all the times we have to make changes to keep up with YouTube's changes.

If you desperately want it, we accept pull requests, otherwise I kindly ask you to be patient and respectful.
