### ISSUE TITLE
[Feature Request]: Different profiles should have their own individual settings.

### ISSUE THREAD

**Issue by Growebis** [FreeTubeApp/FreeTube#3262] opened 2023-03-05 22:18 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Sometimes i use Freetube to listen to songs audio only and would put the song to audio format, the process is somewhat tedious but manageable, but sometimes when i switch songs frequently or are playing a playlist, i don't want it to automatically go back to DASH format when the next song plays. Creating a profile dedicated to simply listening audio only doesn't help as settings are universal across all profiles.

### Proposed Solution

Make it so that every profile has its own settings so that one can setup a profile for different things.
example being an audio only profile or a profile for saving data, (in case the person is using LTE to tether to his laptop).

### Alternatives Considered

#2295

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-03-05 22:34
Duplicate of #1996

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-03-05 22:35 UTC
Labels: enhancement, E: new feature
