### ISSUE TITLE
[Bug]: When typing in search bar "i" the stats of video show up

### ISSUE THREAD

**Issue by sound-infinity** [FreeTubeApp/FreeTube#2207] opened 2022-04-17 04:31 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Go to a video
2. Select the search bar
3. Type "i"

Not a big issue, just wanted to let you guys know of this.

### Expected Behavior

The information panel shouldn't pop up

### Issue Labels

visual bug

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Windows 10

### Installation Method (If applicable)

.exe

### Primary API used

Invidious API

### Additional Information

![image](https://user-images.githubusercontent.com/39848886/163700476-6a119c22-73fc-4655-8069-c9f29a5b7b67.png)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-04-17 06:59
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2062

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-04-17 07:00 UTC
Labels: bug, B: visual
