### ISSUE TITLE
[Bug]: settings.db has setting values added and not replaced

### ISSUE THREAD

**Issue by maplepy** [FreeTubeApp/FreeTube#5523] opened 2024-08-04 00:09 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

`settings.db` does not replace the values but adds the new value to the setting making files extremely long and weird if you tinkered with values a lot

### Expected Behavior

value is replaced

### Issue Labels

feature stopped working, usability issue

### FreeTube Version

v.21.3 beta

### Operating System Version

arch linux

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Additional Information

```
{"_id":"hideLiveStreams","value":false}
{"_id":"hideLiveStreams","value":true}
{"_id":"showDistractionFreeTitles","value":false}
{"_id":"showDistractionFreeTitles","value":true}
{"_id":"showDistractionFreeTitles","value":false}
{"_id":"showDistractionFreeTitles","value":true}
{"_id":"showDistractionFreeTitles","value":false}
{"_id":"showDistractionFreeTitles","value":true}
{"_id":"showDistractionFreeTitles","value":false}
{"_id":"showDistractionFreeTitles","value":true}
{"_id":"showDistractionFreeTitles","value":false}
{"_id":"showDistractionFreeTitles","value":true}
{"_id":"showDistractionFreeTitles","value":false}
{"_id":"showDistractionFreeTitles","value":true}
{"_id":"showDistractionFreeTitles","value":false}
{"_id":"showDistractionFreeTitles","value":true}
{"_id":"showDistractionFreeTitles","value":false}
{"_id":"showDistractionFreeTitles","value":true}
{"_id":"showDistractionFreeTitles","value":false}
{"_id":"showDistractionFreeTitles","value":true}
{"_id":"showDistractionFreeTitles","value":false}
{"_id":"showDistractionFreeTitles","value":true}
{"_id":"showDistractionFreeTitles","value":false}
{"_id":"hideUpcomingPremieres","value":false}
{"_id":"hideChannelSubscriptions","value":true}
{"_id":"hideChannelSubscriptions","value":false}
{"_id":"hideVideoViews","value":true}
{"_id":"hideVideoViews","value":false}
{"_id":"hideChannelSubscriptions","value":true}
{"_id":"hideChannelSubscriptions","value":false}
{"_id":"hideSharingActions","value":true}
{"_id":"hideSharingActions","value":false}
{"_id":"hideChannelCommunity","value":true}
{"_id":"hideChannelCommunity","value":false}
{"_id":"hideFeaturedChannels","value":true}
{"_id":"hideFeaturedChannels","value":false}
{"_id":"hideChannelReleases","value":true}
{"_id":"hideChannelReleases","value":false}
{"_id":"hideChannelPodcasts","value":true}
{"_id":"hideChannelPodcasts","value":false}
{"_id":"hideChannelPlaylists","value":true}
{"_id":"hideChannelPlaylists","value":false}
{"_id":"hideChannelShorts","value":true}
{"_id":"hideChannelShorts","value":false}
{"_id":"hideFeaturedChannels","value":true}
{"_id":"hideFeaturedChannels","value":false}
{"_id":"showFamilyFriendlyOnly","value":true}
{"_id":"showFamilyFriendlyOnly","value":false}
{"_id":"showFamilyFriendlyOnly","value":true}
{"_id":"showFamilyFriendlyOnly","value":false}
{"_id":"useDeArrowThumbnails","value":true}
{"_id":"useDeArrowThumbnails","value":false}
{"_id":"useDeArrowThumbnails","value":true}
{"_id":"useDeArrowThumbnails","value":false}
{"_id":"useDeArrowThumbnails","value":true}
{"_id":"useDeArrowThumbnails","value":false}
{"_id":"useDeArrowThumbnails","value":true}
{"_id":"useDeArrowThumbnails","value":false}
{"_id":"useDeArrowThumbnails","value":true}
{"_id":"useDeArrowThumbnails","value":false}
{"_id":"useDeArrowThumbnails","value":true}
{"_id":"useDeArrowThumbnails","value":false}
{"_id":"useDeArrowThumbnails","value":true}
{"_id":"useDeArrowThumbnails","value":false}
{"_id":"useDeArrowThumbnails","value":true}
{"_id":"useDeArrowThumbnails","value":false}
{"_id":"settingsPassword","value":"loli"}
{"_id":"settingsPassword","value":""}
```

This is a excerpt from my `settings.db`, notice how the value is not being replaced for every setting

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-08-04 07:01
Did you access the db while FT was still running?

**Comment by absidue** [comment] 2024-08-04 07:07
That is not a bug and is working as expected, while the app is running nedb uses an append-only format, so it only writes what has changed to the end of the file. When FreeTube gets closed it asks nedb to compact the databases, which makes it merge together all the changes.

While FreeTube is running you should stay away from the database files, if you modify ANYTHING or start moving the files around while FreeTube is running you are risking corrupting your databases.

If you are saying that is the case after you closed FreeTune, then you didn't give it enough time to clean up, as that starts when you close the last window. Make sure you leave enough time before you start messing with the files.

**Comment by maplepy** [comment] 2024-08-06 16:59
Ooh alright that is interesting! 

Freetube was indeed opened but I was just cleaning my dotfiles a bit and was checking every file or so to see what was needed and what could be removed from those :)

I did not modify any file, just opened those out of curiosity aha

**Closed** 2024-08-06 16:59 UTC
Labels: bug, B: usability, B: feature stopped working, B: Unofficial Download
