### ISSUE TITLE
[Bug]: Age Restricted Videos No Longer Play

### ISSUE THREAD

**Issue by AnonymousHex** [FreeTubeApp/FreeTube#2152] opened 2022-03-26 06:47 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Try to play an age restricted video.
2. Local APi fails with code 410 as usual.
3. Invidious API fails with error: {"error":"This video may be inappropriate for some users."}
4. Video does not play.  Comments will load but not the title, description, upload date, etc.

### Expected Behavior

Video should play.

### Issue Labels

feature stopped working

### FreeTube Version

v0.16.0 build 1520, v0.16.0 release

### Operating System Version

Windows 7 SP1 64 bit

### Installation Method (If applicable)

Portable

### Last Known Working FreeTube Version (If Any)

N/A

### Primary API used

Local API

### Additional Information

This worked as recently as a couple days ago.  

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-03-26 09:10
Duplicate of #1296

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-03-26 09:10 UTC
Labels: bug, B: feature stopped working
