### ISSUE TITLE
Playlist thumbnail mismatch

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1353] opened 2021-05-28 02:44 UTC
**Behavior of the program**
When u go into any playlist, the thumbnail on the left rarely matches the actual thumbnail.

**Expected behavior**
Thumbnail of the playlist must match first video in list.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any playlist
2. See thumbnail mismatch

**Link to video**
None.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/73130443/119922096-a7eb9f80-bf5e-11eb-9b99-0df93554edb7.PNG)

**Environment Information (please complete the following information):**

- OS: [Win 10]
- OS Version: [20h2]
- FreeTube version: [v0.13.0-nightly-859 Beta]
- Installation Method (If applicable): [Portable]
- Primary API Used: [Local API]

**Additional context**
None.

**Comment by Tamnac** [comment] 2021-09-26 07:42
I decided to take up this issue and was unable to reproduce. 

Looking through the code and commit history, it seems the issue was that the thumbnail was picked from a random video instead of the first video. This issue was inadvertently fixed in #1361.

**Comment by jasonhenriquez** [comment] 2021-09-26 13:13
@Tamnac good find! Thank you for doing your due diligence and figuring this one out better than we could.

**Closed by jasonhenriquez** 2021-09-26 13:13 UTC
Labels: bug, good first issue
