### ISSUE TITLE
[Feature Request]: Open YT links in a new window if the app is already open

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#4401] opened 2023-11-28 14:36 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I'm using Libredirect to redirect YT links to the freetube app. But if freetube is already open, it opens the link into the said window, wich is pretty annoying if another video is already loaded. It would be more practical if it would open a new window.

### Proposed Solution

A option in the parameters "open in a new window".

### Alternatives Considered

Not relevant.

### Issue Labels

ease of use improvement, new feature, new optional setting

**Comment by absidue** [comment] 2023-11-28 15:20
duplicate of #1501

**Closed** 2023-11-28 16:02 UTC
Labels: U: duplicate, enhancement, E: new optional setting, E: ease of use improvement, E: new feature
