### ISSUE TITLE
[Bug]: freetube 0.22.0 (amd64.deb) does not start after update

### ISSUE THREAD

**Issue by RevAngel7** [FreeTubeApp/FreeTube#5954] opened 2024-10-27 07:00 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Update the FreeTube app via the file freetube_0.22.0_amd64.deb and gdebi
2. Try to start FreeTube 0.22.0
3. App fails to start

### Expected Behavior

Since gdebi checks for prerequisites before installing the app, it is expected for the app actually work after an update

### Issue Labels

causes crash

### FreeTube Version

freetube_0.22.0_amd64.deb

### Operating System Version

Ubuntu 24.04

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

previous most recent stable release

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by RevAngel7** [comment] 2024-10-27 07:08
For some unknown reasons the AppImage version works on my system.

**Comment by RevAngel7** [comment] 2024-10-27 07:54
Flatpak version is also working, but settings get reset.

**Comment by RevAngel7** [comment] 2024-10-27 07:57
Uninstalled the .deb version, reinstalled, same issue: does not start.

**Comment by absidue** [comment] 2024-10-27 08:30
@RevAngel7 Have you tried starting it from a terminal so you can actually see what is going wrong?

**Comment by SoenkeGraf** [comment] 2024-10-27 08:39
Same here! Terminal says:

[7740:1027/093804.542049:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/FreeTube/chrome-sandbox is owned by root and has mode 4755.

**Comment by Wiilliiamm** [comment] 2024-10-27 08:42
application only launch with command line and arguments "freetube --no-sandbox"

**Comment by SoenkeGraf** [comment] 2024-10-27 08:44
> freetube --no-sandbox
 confirmed from my side
@Wiilliiamm

**Comment by absidue** [comment] 2024-10-27 08:44
@Wiilliiamm @SoenkeGraf Please see #5952 and the solutions there.

**Comment by SoenkeGraf** [comment] 2024-10-27 09:03
@absidue @Wiilliiamm @RevAngel7 

Next to the suggested changes by @CrazzzzyChipmunk ( see #5952 ):
sudo chmod 4755 /opt/FreeTube/chrome-sandbox
I added an additional:
sudo chown root:root /opt/FreeTube/chrome-sandbox

To fully satisfy the requirements of the error message:

[9892:1027/095614.385039:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/FreeTube/chrome-sandbox is owned by root and has mode 4755.

**Comment by actionschnitzel** [comment] 2024-10-27 11:09
The same problem also occurs in the arm64.deb version. The solution mentioned above works.

**Comment by Bobbaganush** [comment] 2024-10-27 11:38
> chmod

Can confirm the chmod fixes the issue for me:
sudo chmod 4755 /opt/FreeTube/chrome-sandbox

**Comment by absidue** [comment] 2024-10-27 11:39
The problem is caused by Ubuntu's AppArmor settings being way too restrictive by default. It sounds like Ubuntu comes with built-in for popular programs like Chromium and Visual Studio Code, but for other apps like FreeTube need to figure out our own solution.

**Comment by absidue** [comment] 2024-10-27 11:50
Closing in favour of #5952

@RevAngel7 If it turns out your problem is something different we can reopen this issue, but for the moment I'm closing it as everyone is commenting on the wrong issue.

**Closed by absidue** 2024-10-27 11:50 UTC
Labels: bug, U: Waiting for Response from Author, B: crash

**Comment by RevAngel7** [comment] 2024-10-28 05:59
`$ freetube
[58088:1028/065529.786246:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/FreeTube/chrome-sandbox is owned by root and has mode 4755.
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)`

**Comment by RevAngel7** [comment] 2024-10-28 06:11
Thank you for all the comments and to @absidue for considering a fix! (Note to myself: keep you mail program open when opening an issue to respond more timely. Sorry about that!)

**Comment by VGerris** [comment] 2024-10-29 00:30
hi, I am not following. Did the changes from 0.21.3 to 0.22 involve ones that are not fixable by setting up apparmour properly ? 0.21.3 worked fine, and 0.22 does not. also apt package, AMD graphics. Will the next version include the fixes ? thank you
