### ISSUE TITLE
[Bug]: JavaScript Error; Object has been destroyed

### ISSUE THREAD

**Issue by 626164** [FreeTubeApp/FreeTube#6169] opened 2024-11-15 20:01 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

This error message appeared when I closed my FreeTube instance. It was acting slow, not loading videos I wanted to watch. 
![image](https://github.com/user-attachments/assets/ca3b37c1-117e-48a6-84c8-c523f094c669)

### Expected Behavior

Expected FreeTube to shutdown smoothly.

### Issue Labels

feature stopped working

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Microsoft Windows 11 Pro v10.0.22631 Build 22631

### Installation Method

.exe

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-11-15 21:33
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4762

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-11-15 21:33 UTC
Labels: bug, B: feature stopped working
