### ISSUE TITLE
FreeTube not reliable. Subscription updates are missing

### ISSUE THREAD

**Issue by felixsanz** [FreeTubeApp/FreeTube#513] opened 2020-08-13 06:37 UTC
Funny... i've opened newpipe and there is a lot of videos that FreeTube never showed up, so i don't even know what i missed.

Plus, sometimes you update FreeTube subscriptions and some videos appear, but you update tomorrow and some old videos appear in between those.

Looks like subscriptions updates are totally broken and not reliable

**Comment by PrestonN** [comment] 2020-08-13 12:53
I imagine it's related to [this](https://github.com/iv-org/invidious/issues/1333) issue on the Invidious side.  There won't be anything I can do with the live release as this issue needs to be fixed on the Invidious side.

Having said that, I'm hard at work with the rewrite and loading channel data still works fine over there.  Subscriptions have not been implemented yet however so it's obviously missing a few things.  This issue will only be fixed when Invidious is fixed or when the rewrite is finished.

**Comment by esotericDisciple** [comment] 2020-08-13 18:47
invidio.us instance has this issue as well

**Comment by felixsanz** [comment] 2020-08-13 21:02
youtube subscriptions are just rss feeds, why not parse them with a library and stop depending on dead projects?

**Comment by PrestonN** [comment] 2020-08-13 21:43
Because the project wasn't being shut down when I originally implemented it.

RSS feeds also don't provide all of the information that users expect so we have to get video information from the channels page.

The rewrite will provide the option to get feed information from RSS feeds though. The current code base is very poorly put together so I'm redoing a lot of the functionality that's in the live release. It'll take some time but the end result will be a much better kept application and I think the wait will be worth it.

Builds of the rewrite are already available to download and can be tested while the development is progressing. If you'd like to fix some of these problems (while also being aware that some functionality is missing) then I welcome you to give the rewrite a try and provide feedback.

**Comment by razzor1984** [comment] 2020-08-17 19:11
Hello @PrestonN,
is 7.3 a build with parts of a rewrite ? Where can i download your latest stuff as described in the last post. I would try to test it ;)

**Comment by PrestonN** [comment] 2020-08-17 20:02
The current v0.7.3 release has absolutely no work done from the rewrite.  The repository where the rewrite has been living up to this point is over [here](https://github.com/FreeTubeApp/FreeTube-Vue).

If you go over to the [Actions](https://github.com/FreeTubeApp/FreeTube-Vue/actions?query=workflow%3ABuild) tab, here you will find automated builds of the rewrite that are available to test out.  Please be aware that many features are missing compared to the live release and anything in the rewrite is subject to change.  Anyone is more than welcome to give the rewrite a try and provide feedback over at the respective repository.

**Comment by lbriais** [comment] 2020-08-24 08:58
I have the same issue as OP
But the point is **I tested my issue with the new Vue.js version and I get exactly the same issue...**

I often watch the [Andertons channel](https://www.youtube.com/c/andertons/videos). They provide new videos almost everyday... For months now Freetube is not able to show any of their videos, be it as subscription or even directly going to the channel page (although the videos themselves are shown as result of a direct search). 

Hearing about the refactor project of Freetube, I tried with the [new flavour of Freetube](https://github.com/FreeTubeApp/FreeTube-Vue) with the **exact same result** !! No video is shown !

Result of a direct search:
![image](https://user-images.githubusercontent.com/3846669/91024498-517cb980-e5f8-11ea-8c06-ac8ba5117310.png)

Going to the channel shows an empty page (hitting "fetching more results" changes nothing) !
![image](https://user-images.githubusercontent.com/3846669/91024583-74a76900-e5f8-11ea-8bce-e53b743e1738.png)

This happens in both Freetube and Freetube-vue...

**Comment by PrestonN** [comment] 2020-08-24 21:01
If you're getting the exact same result, that means you're still using the Invidious API over in the rewrite.  I just tested the local API with the exact channel you mentioned and I'm not experiencing any issues.

Because this issue is because of the Invidious API, I'm closing this here.  If you want to get updates on when this issue will be fixed (It likely isn't going to be fixed anytime soon just an FYI), you can track the progress over [here](https://github.com/iv-org/invidious/issues/1333).

**Closed by PrestonN** 2020-08-24 21:01 UTC

**Comment by lbriais** [comment] 2020-08-25 07:05
Humm... You're saying I'm using the invidious API but that's not what the config says...
![image](https://user-images.githubusercontent.com/3846669/91142838-ceb83500-e6b1-11ea-8173-29ed887427da.png)

The end of the invidio.us instance was actually the reason why I checked the new rewrite of Freetube....

**Comment by alidan** [comment] 2020-08-25 09:56
where do you get this preferred api backend option?

**Comment by lbriais** [comment] 2020-08-25 11:12
This is actually a screen capture using the [new flavour of Freetube](https://github.com/FreeTubeApp/FreeTube-Vue) which is supposed not to use invidious as a backend (which seems to be confirmed by the config flag in the screen capture).

I agree that if there is an issue with this, this is probably a bug to be reported in the relevant project (ie FreeTube-Vue), but before doing so, I just wanted a confirmation from @PrestonN  that I was doing things correctly (maybe a specific branch in that other project works as expected).

**Comment by PrestonN** [comment] 2020-08-25 12:49
@lbriais Can you confirm that you're on the latest iteration of the rewrite?  Judging by your screenshot, you're using a very old version where there wasn't a way to gather channel information using the local API.   This means that your app would use Invidious regardless of your settings.  Please try again with the latest version and let me know if you're still experiencing problems.

**Comment by lbriais** [comment] 2020-08-25 14:00
Indeed I was way behind the head... :stuck_out_tongue_winking_eye: 

Although I have been doing a `git pull`, I didn't notice that the `package.json` which had been modified by a previous `npm install` had been preventing the `git pull` to complete...

I just removed the offending file, git pulled again, npm installed and now everything is fine... I see the new version working :+1: .

Sorry for the useless noise...

**Comment by alidan** [comment] 2020-08-26 09:30
welp, looks like there is no easy way for me to install the new one to use, so ill ask, any idea when a version for that will be made to install? and if that's the version thats getting worked on, may as well move my feature request over there as well.
