### ISSUE TITLE
FreeTube not working with Tor on Windows

### ISSUE THREAD

**Issue by ChillSheep** [FreeTubeApp/FreeTube#314] opened 2019-08-03 17:08 UTC
FreeTube isn't working with the Tor option enabled, I have tor running as administrator.
I tried renaming firefox.exe to Tor.exe and it still won't work, tor in the browser is working fine.

**Comment by PrestonN** [comment] 2019-08-05 13:17
Maybe a duplicate of #293?  Let's wait until the next release comes out and see if that fixes it.  If it doesn't then we can pursue this further.

**Closed** 2020-09-29 20:55 UTC
