### ISSUE TITLE
[Feature Request]: Video Thumbnail caching instead of constant reloading

### ISSUE THREAD

**Issue by fugbixer** [FreeTubeApp/FreeTube#2397] opened 2022-07-12 18:58 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Slow instances due to network or amount of requests load image some times slowly

this was already adressed here https://github.com/FreeTubeApp/FreeTube/issues/1837

but you ignored it and got buried under the other issues. 

### Proposed Solution

video thumbnail caching instead of constant reloading

So load video thumbnails from cache instead of requesting them from the instance again and again

Sometimes thumbnails are changing, maybe load them in the background and compare hashes if the old one is still the current one set, but for me i think we dont have to do it. 

### Alternatives Considered

none

reduce server load for those providing instances to the public by caching the images

### Issue Labels

improvement to existing feature

### Additional Information
Request for bounty welcome (will pay for it)

**Comment by absidue** [comment] 2022-07-17 09:59
Duplicate of #1837

**Closed** 2022-07-17 09:59 UTC
Labels: U: duplicate, enhancement, E: improvement existing feature
