### ISSUE TITLE
[Feature Request]: Responsive UI for grid view - making much better use of screen estate

### ISSUE THREAD

**Issue by Eiion** [FreeTubeApp/FreeTube#5434] opened 2024-07-19 14:06 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

As is the resizing and adding colums of the displayed content is done very leniently.

Example 1:
![image](https://github.com/user-attachments/assets/7e87a1db-5b7a-4ad7-9c4f-3bd1e39cfcc1)
Left and right of the displayed content are about 98 pixels of wasted screenspace - a total of 196. (In the screenshot the window is sized in such a manner that FreeTube has just changed from only 3 columns to 4.)

Eample 2:
![image](https://github.com/user-attachments/assets/978c2fa9-1903-47f7-b90c-9c8ae85d20eb)
This window's size is right before it switches to 5 colums and now there's about 120 pixels on the left and the right, so a total of 240 pixels of wasted screen estate.

These big empty space side bars should not exist. 

### Proposed Solution

The responsive design should be set up in a way that the empty space of wasted screen estate does not exist.
The empty space should be wider than 10 pixels at the most. There's no use is having this empty space in the window. All it does is fill the physical screen without giving the benefit of more visible content.

The solution should not be to simply make the tiles bigger but to add columns much earlier (again, there shouldn't be more than 10 wasted pixels on both sides.
This could be done by more optimized dynamic resizing of the used thumbnails. Also, I (personally) do not have to see three lines of video title below a thumbnail like here on the left and right side of the screenshot:
![image](https://github.com/user-attachments/assets/66beecaa-c1e1-437f-9310-3e75a3f53bf1)
Mouseover could display the full video title while it shouldn't be more than 2 lines of video title or maybe even 1 line plus the second line for the channel/views/upload timestamp.

As is there's just so much screen space wasted that isn't filled with content no matter if on the Subscriptions or the Trending page, where increasing does not get you more tiles/columns but just more unused screen estate in a bigger window.

### Alternatives Considered

And alternative to better dynamic resizing of displayed content or responsive design could be to add setting to the general settings, i.e. options one can choose from after selecting "Grid" in "Video View Type", letting the user select the columns shown on the window.
Something like suggested about three years ago here https://github.com/FreeTubeApp/FreeTube/issues/1960.

### Issue Labels

display more information to user, ease of use improvement, improvement to existing feature, new optional setting, visual improvement

**Comment by absidue** [comment] 2024-07-19 14:14
Duplicate of #5007

**Closed by absidue** 2024-07-19 14:14 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: visual improvement, E: display more information, E: ease of use improvement
