### ISSUE TITLE
[Feature Request]: Hide "Watched" videos from recommended, channels and playlists

### ISSUE THREAD

**Issue by Jeefongithub** [FreeTubeApp/FreeTube#5189] opened 2024-05-29 19:16 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The watched videos feature is good for the homepage but doesn't hide videos in other aspects of the program

### Proposed Solution

Similarly how there is a toggle to hide watched videos from homepage I'd like to suggest a toggle to also hide videos that are in the watched state from recommended or sidebar when in a video, from the channel pages and from playlists. That way only videos that are unscene or unwatched are shown as options. 

### Alternatives Considered

alternatively watched videos could be less prioritized in the list of videos in recommended pushing unwatched videos to the top of the list but I assume the ordering is coming from youtube so that might not be possible

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-29 19:43
basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4497 with an expanded scope. Please put the scope expansion you like to see in the comment section of that issue

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-05-29 19:43 UTC
Labels: enhancement, E: new feature
