### ISSUE TITLE
Doubles in the quality menu 

### ISSUE THREAD

**Issue by rebelcode-xr** [FreeTubeApp/FreeTube#1702] opened 2021-09-14 20:50 UTC
In some videos (like [this](https://youtu.be/1-NxodiGPCU)) this is what I see in the quality menu:

![image](https://user-images.githubusercontent.com/63522951/133330465-46a34fb1-8f23-4701-ade3-29f37e99c906.png)

![image](https://user-images.githubusercontent.com/63522951/133331423-ec1df181-c811-42b6-9b6f-b1ccbc864828.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-14 20:59
Hi/@rebelcode-xr im sorry but this is also a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1344

I get why u didn't it tho. No worries! This issue is still a work in progress. Hopefully this will be fixed soon.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-09-14 20:59 UTC
Labels: bug

**Comment by rebelcode-xr** [comment] 2021-09-14 21:03
Ok, no problem, sorry again! 😅
