### ISSUE TITLE
[Feature Request]: Profile Order Customization

### ISSUE THREAD

**Issue by git-hop22** [FreeTubeApp/FreeTube#4308] opened 2023-11-09 11:50 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The current version lacks a feature to **adjust the order of profiles**, limiting user customization and ease of access. This improvement would significantly enhance the program's usability for users who prefer a personalized profile arrangement. Additionally, it would benefit users with a high profile count, providing them with a more efficient way to manage and access their profiles.

### Proposed Solution

Introduce a feature that allows users to **rearrange the order of individual profiles**. This could be a simple option to modify the sequence, providing users with flexibility in organizing profiles based on their preferences. Additionally, consider options like displaying the two most recently used profiles at the top or sorting profiles by frequency of use or subscription count.

### Alternatives Considered

I have not identified any existing features that address this specific need. However, I'm open to exploring other suggestions or implementations that could achieve a similar outcome.

### Issue Labels

ease of use improvement, new feature, new optional setting, visual improvement

### Additional Information

Thank you for your efforts in developing the software. It's much appreciated!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-09 11:53
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/987

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-09 11:53 UTC
Labels: enhancement, E: new optional setting, E: visual improvement, E: ease of use improvement, E: new feature
