### ISSUE TITLE
[Feature Request]: Option to sort videos in playlist

### ISSUE THREAD

**Issue by hblaise** [FreeTubeApp/FreeTube#5128] opened 2024-05-19 10:46 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Before the new playlist feature became a thing, to me, it was very convenient to just favorite a video and later on check my favorites and see what I put there in the last day or two, and I was able to watch them easily. With the new playlist feature however, I find myself unable to use my favorite playlist, because it has more than 4k videos, but I have no way of changing the order of the videos, I have to scroll to the newest ones which is not feasible every day multiple times. This made me not use playlists at all, and it made using FreeTube a pain. Now, I understand that I could change the way I use FreeTube, but I would still miss the option of sorting the videos in the playlists.

### Proposed Solution

Introduce an option to be able to sort individual playlists or even set it globally to every playlist. Sort by date added, video date, etc.. The most important is to be able to sort videos by the date when it was added to the playlist.

### Alternatives Considered

-

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by absidue** [comment] 2024-05-19 11:50
Duplicate of #4870
It was implemented in #4921 and will be in the next release.

**Closed by absidue** 2024-05-19 11:50 UTC
Labels: enhancement, E: improvement existing feature, E: ease of use improvement
