### ISSUE TITLE
Video quality setting does not work

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [FreeTubeApp/FreeTube#681] opened 2020-10-17 12:56 UTC
**Important note**
Please check other open and closed issues for a similar bug before reporting a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Behavior of the program**
Selecting the default video quality in the settings
**Expected behavior**
The video quality should be the same as in settings for ALL videos 

**To Reproduce**
Please add all steps to reproduce the behavior:
1. go to settings
2. select the video quality (let's say 360p)
3. open any video after this tweak
4. see the quality menu and you would find it's 720p (in my case) on all videos no matter what
**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.

**Desktop (please complete the following information):**
 - OS: Linux Debian
 - OS Version: 10
 - FreeTube version: v0.9.0 Beta

**Additional context**

**Comment by Synkky** [comment] 2020-10-17 13:37
Duplicate of #595

**Closed** 2020-10-17 14:00 UTC
Labels: bug

**Comment by EsmailELBoBDev2** [comment] 2020-10-17 19:10
sorry, i tried to search in the "closed tickets" 

Thanks!
