### ISSUE TITLE
[Feature Request]: Shortcut or faster way to mark subscription video as played

### ISSUE THREAD

**Issue by lewgrant** [FreeTubeApp/FreeTube#5689] opened 2024-09-11 19:35 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Removing videos from the subscription screen is a slow process that requires clicking on a small target then a second click in a context menu that may automatically scroll the screen.

### Proposed Solution

Any faster / easier way to quickly dismiss videos from the subscription page. Perhaps something like Shift + Click or maybe a 'select' mode where you can quickly pick a non-contiguous selection and then choose mark as played for the entire selection?

### Alternatives Considered

None come to mind

### Issue Labels

ease of use improvement, new keyboard shortcut

**Comment by absidue** [comment] 2024-09-11 20:58
Duplicate of #2517

**Closed by absidue** 2024-09-11 20:58 UTC
Labels: enhancement, E: ease of use improvement, E: keyboard shortcut
