### ISSUE TITLE
[Feature Request]: More comprehensive codec selection in settings

### ISSUE THREAD

**Issue by glanduin** [FreeTubeApp/FreeTube#5744] opened 2024-09-24 14:50 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I am on a RPI-5 and a more comprehensive codec selection in settings would make this app so much better. Currently there is only the "legacy codec" option which is h264 and "dash format" option which is probably a combination of vp9 and av1. RPI is a relatively low-powered computer and the latest nightly version of Freetube can play vp9 codec youtube videos quite well without dropping any frames in 1080p in 60fps (which is awesome performance for a RPI). However, it can only do this when the codec is vp9. AV1 codec causes a lot of dropped frames and little pauses here and there. The selection of vp9 or av1 seems like "random" as the playback starts. It can be changed after the playback started but that is cumbersome. The options that we have after the playback starts do not specify which one is vp9 or which one is av1 but presumably, the "hdr" versions are av1 and "non-hdr" ones are vp9 (at least for the examples that i have tried).

### Proposed Solution

An option to be able to either "enforce" vp9 or to disable the use of "av1" codec, in the settings.

### Alternatives Considered

I can not think of any alternatives to that.

### Issue Labels

new feature

**Comment by absidue** [comment] 2024-09-24 16:09
> "dash format" option which is probably a combination of vp9 and av1

DASH are separate audio and video streams, YouTube offers the video ones in h264, vp9 and AV1 (AV1 may be missing if the video was only published "recently").

> options that we have after the playback starts do not specify which one is vp9 or which one is av1

If you right click on the player you can turn on the stats which tell you what streams it is using at that moment.

---

We do tell shaka-player to filter out streams that the browser predicts that it won't be able to play smoothly, which I was really hoping would be enough to avoid having to add messy codec settings, but from what you are saying it sounds like that it isn't working correctly.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-24 16:21
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/504

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-24 16:21 UTC
Labels: enhancement, E: new feature

**Comment by artenax** [comment] 2025-01-13 11:42
AV1 is slow in HD. I would like to block it.
