### ISSUE TITLE
[Bug]: Not all videos retrieved by FT querry.

### ISSUE THREAD

**Issue by ChattyMatty** [FreeTubeApp/FreeTube#3138] opened 2023-01-30 18:12 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

On some of my subscribed channels only a portion of the total number of posted videos are retrieved. Specifically, Matt Christiansen's channel will populate all his solo videos but not his weekly collabs with Blonde. In order to see the unretrieved video I have to go to YouTube, copy the URL (or the full title) and paste that in the search and then presto! it magically finds the video... so FT does have access to the video it just isn't populating them in my subscription list. Briefly looking at some other channels, I see a similar issue with Timcast IRL- his short videos populate no problems, but this longer videos appear to be blocked.

Does FreeTube block search results based on the length of a video all of a sudden? If it were failing to populate a particular creator (like YT's coders were blocking people based on politics with some tag which interferes with Invidious/FT) whatever, the internet is full of blocked people for petty reasons, that's life in the modern world. But clearly _some_ of these creators' content is making it through, just not the longer stuff, or so it would appear to me. Is there a reason longer videos would not populate?

### Expected Behavior

A subscription to a channel should populate ALL that channels recent content, not just some.

### Issue Labels

content not loading

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Win 10 x64

### Installation Method

.zip

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-01-30 20:30
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2852

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-01-30 20:30 UTC
Labels: bug, B: content not loading
