### ISSUE TITLE
update markers

### ISSUE THREAD

**Issue by therealgoodstuff** [FreeTubeApp/FreeTube#369] opened 2019-08-27 09:51 UTC
Hi,

I´d like to see numbers on the channelnames whenever there is new content available. 
When there are new videos available on the channel from the point I was watching
last I want a number count so I can see how many new videos have been put on since.
Same as in minitube wich I am using right now. Also it would be great if I could choose between
list view of the subscriptions or a tiled view.

cheers

**Comment by morfikov** [comment] 2019-08-27 11:11
Duplicate of  #329

**Closed** 2019-08-27 13:21 UTC
