### ISSUE TITLE
Blanck window on middle-mouse-button click on a video

### ISSUE THREAD

**Issue by tzzza** [FreeTubeApp/FreeTube#1792] opened 2021-10-05 11:35 UTC
**Behavior of the program**
On middle-mouse-button click on a video from suggested videos only blanck window appears (see pic). Bug newly introduced with ver. 0.14.0 beta

**Expected behavior**
open (play) selected video

**Screenshots**
![blankbug](https://user-images.githubusercontent.com/91953963/136015891-6b953e4f-0350-48eb-8a07-cecf392e83a1.png)

**Environment Information (please complete the following information):**
 - Windows 10 Enterprise
 - OS Version: Latest
 - FreeTube version: 0.14.0 beta
 - Installation Method (If applicable): Portable
 - Primary API Used: Local API

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-05 12:48
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1636

This is already fixed in the latest nightly build. U can also try out the RC https://github.com/FreeTubeApp/FreeTube/discussions/1773

**Closed** 2021-10-05 12:48 UTC
Labels: bug, duplicate
