### ISSUE TITLE
[Feature Request]: Block/Hide Channels, Users or Specific Videos with 1 Click or RegEx

### ISSUE THREAD

**Issue by MagiDruid** [FreeTubeApp/FreeTube#2514] opened 2022-08-28 20:38 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

[Feature Request]: Block/Hide Channels, Users or Specific Videos with 1 Click or RegEx

### Proposed Solution

This feature request was inspired by the following web extension: Channel Blocker by Time Machine Development. 

Chrome: https://chrome.google.com/webstore/detail/channel-blocker/nfkmalbckemmklibjddenhnofgnfcdfp
Firefox: https://addons.mozilla.org/en-US/firefox/addon/youtube-cleaner/

1. The extension allows users to hide/block: 
- users/channels
- videos by title
- users/channels by name
- comments by comment-content*
- users/channels from regular expressions
3. The extension supports RegEx for maximum customization. 
4. Import/Export of RegEx settings is also supported.

* Option already exists within FreeTube to turn off comments

This feature could improve upon the already excellent Distraction Free settings within FreeTube and allow users even more control over what they see when they search for something and save them time (filtering out undesirable or useless content). 

Thank you for your time and consideration. Kind Regards. 

### Alternatives Considered

These are similar alternatives to the aforementioned extension: uBlacklist (blocks/hides Google & other major search engine results but not results from or on video sharing platforms), CustomBlocker, Filter Anything Anywhere (etc.) Channel Blocker is best suited for filtering search results on video sharing platforms like YouTube (doesn't work on vimeo, tiktok). 

### Issue Labels

ease of use improvement, improvement to existing feature, new feature, new optional setting

### Additional Information

![Blocked comments by comments-content](https://user-images.githubusercontent.com/100071592/187093526-fc23a252-7455-454d-b905-9fe78c671378.jpg)
![Blocked users:channels](https://user-images.githubusercontent.com/100071592/187093534-e675bbfb-7a63-4fea-bb87-1c23cb96f1b4.jpg)
![Blocked users:channels by name](https://user-images.githubusercontent.com/100071592/187093545-302481f3-0ffe-402a-9911-0912049e6c23.jpg)
![Blocked videos by title](https://user-images.githubusercontent.com/100071592/187093548-fc69f276-3813-4440-8d4b-da69c0cf3153.jpg)
![Excluded users:channels from RegEx](https://user-images.githubusercontent.com/100071592/187093552-b4a8c4a0-d73c-4e81-9ea6-3e93e6aabcc1.jpg)

**Comment by absidue** [comment] 2022-08-29 07:10
Duplicate of #95

**Closed by absidue** 2022-08-29 07:10 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: ease of use improvement, E: new feature
