### ISSUE TITLE
[Feature Request]: Sorting options for Playlists

### ISSUE THREAD

**Issue by maxsubs** [FreeTubeApp/FreeTube#4729] opened 2024-02-28 13:05 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

On previous versions when I went to "saved videos" the first videos I saw were the last to be added, now on the favorite playlist I see first the oldest videos, I've been adding videos for a long time and my playlist is like +8000 videos, which makes watching the latest videos impossible for the time it takes to scroll down.

### Proposed Solution

They should be shown imho in the inverse order or letting you order them by different criteria (added time, published time, duration, etc) and remember each desired order for each playlist. Also an option to search through playlist should be added as we had on the previous versions for the saved videos.

### Alternatives Considered

Thanks for this great piece of software!!!

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-03-01 15:08
duplicate of https://github.com/PikachuEXE/FreeTube/issues/54

Issues regarding the upcoming playlist feature will be migrated to here when playlists reached stable release.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-03-01 15:08 UTC
Labels: enhancement, E: ease of use improvement
