### ISSUE TITLE
[Bug]: Time ago error

### ISSUE THREAD

**Issue by milotype** [FreeTubeApp/FreeTube#2548] opened 2022-09-07 18:54 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

![Time error](https://user-images.githubusercontent.com/43657314/188955165-0a62ca5f-e252-4a99-8e3b-1353abe1b52f.png)

### Expected Behavior

The strings should be checked and corrected ...

### Issue Labels

visual bug

### FreeTube Version

v0.17.1 Beta

### Operating System Version

Mac OS 10.11.6

### Installation Method

.dmg

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-09-07 18:59
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2439

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-09-07 18:59 UTC
Labels: bug, B: visual
