### ISSUE TITLE
Playlist list rearranges itself

### ISSUE THREAD

**Issue by squinonescolon** [FreeTubeApp/FreeTube#4925] opened 2024-04-10 20:13 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

If you have already added a video to one of my playlist list, when you add the next one, the last playlist that you added a video to moves to the front of the list.

### Proposed Solution

When this happens I would propose the list of lists stays the same so I can quickly select a new list based on alphabetical order.

### Alternatives Considered

Different types of sorting might be appreciated.

### Issue Labels

ease of use improvement

### Additional Information

Nothing else

**Comment by squinonescolon** [comment] 2024-04-10 20:19
Sorry, didn't see the option to sort on the upper right.

**Comment by squinonescolon** [comment] 2024-04-10 20:20
Ok, the sorting gizmo is not sticky, please make it sticky to avoid more clicks.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-11 03:17
Duplicate of #4870

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-11 03:17 UTC
Labels: enhancement, E: ease of use improvement

**Comment by deepspaceaxolotl** [comment] 2025-04-21 23:29
I don't believe this is a duplicate of that issue, this seems to be about the sorting of playlists in the menu to add a video to an existing playlist. While it is possible to sort the playlists using the option in the upper right corner, it's immediately forgotten when going to add another video. I would also greatly appreciate seeing this fixed!
