### ISSUE TITLE
[Bug]: loading a video site enters a refresh endless looping

### ISSUE THREAD

**Issue by Cyborgscode** [FreeTubeApp/FreeTube#5457] opened 2024-07-24 17:02 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. ABOS -> choose a video
2. when video page is loaded => it repeats loading it in an endless looping.

restarting client did not help
SHIFT+R+CTRL  did not help
R+CTRL  did not help

this morning, appr. 10 hours ago, it worked.

### Expected Behavior

x

### Issue Labels

content not loading

### FreeTube Version

v0.21.1 Beta

### Operating System Version

Fedora 39

### Installation Method

.rpm

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by mokahless** [comment] 2024-07-24 17:08
I'm here searching because I've just started running into this, too. Not on all videos but that could be because it wasn't happening just a bit ago. I left one open for a few minutes to flicker/refresh and when it finally calmed down, it turned into a white X with a "DASH request error."

Based on that, I disabled "Allow DASH AV1 formats." Same issue.

So then i set default to "legacy formats" and set default quality to "720p." Same issue.

Restarted freetube in between. Also trying different videos now - pretty sure it's a universal issue, not just a few videos.

**Comment by OothecaPickle** [comment] 2024-07-24 17:27
#5456

**Comment by 4yman-0** [comment] 2024-07-24 18:31
#5459 #5458 #5456

make sure you searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues.

**Comment by fiendUnpleasant** [comment] 2024-07-24 20:40
I am also having this issue on Fedora. Here is a screen recording of what is happening https://mastodon.social/@fiend_unpleasant/112843366475665505

**Comment by tjhaskel** [comment] 2024-07-24 20:47
I'm also encountering this with version v0.21.1 Beta on Windows 10 x64. 

Turning on "Player Settings" -> "Proxy Videos Through Invidious" seems to work for the time being.

**Comment by mikebronner** [comment] 2024-07-24 20:47
I just tried the latest build, and that does not seem to have this refresh issue. However, the videos still don't seem to load.

https://docs.freetubeapp.io/development/nightly-builds

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-24 21:06
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5456

[Temporary workaround](https://github.com/FreeTubeApp/FreeTube/issues/5456#issuecomment-2248897869)

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-24 21:06 UTC
Labels: bug, B: content not loading
