### ISSUE TITLE
[Feature Request]: Custom Font Option in FreeTube  Dear FreeTube Team

### ISSUE THREAD

**Issue by Erick12890** [FreeTubeApp/FreeTube#5767] opened 2024-09-29 22:13 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I hope this message finds you well. I would like to suggest a feature that could improve the user experience in FreeTube. It would be fantastic to have the option to change the default font to a custom one, allowing users to select and apply their preferred fonts within the program.

The current font feels quite large and lacks visual appeal for my personal taste, so the ability to customize the font would greatly enhance the program’s appearance and offer a more personalized experience.

Thank you for considering this request, and I appreciate all the great work your team has done so far!

### Proposed Solution

To address the need for more font customization within FreeTube, I suggest implementing a feature that allows users to upload and select custom fonts. This would work similarly to how themes are applied, giving users the flexibility to choose fonts that better fit their preferences for size, style, and overall appearance.

This feature could be added under the "Appearance" or "Settings" section of the program, where users can either select from pre-installed fonts or upload their own font files. The option to adjust font size and style would further enhance customization. This change would allow for a more visually appealing and personalized interface without significantly altering the functionality of the program.

### Alternatives Considered

While exploring options to improve the visual appeal of FreeTube, I considered several alternatives. One option could be to reduce the size of the default font or change it to a more modern or visually appealing typeface. Another option could be to provide a selection of preset fonts for users to choose from.

However, these alternatives would still limit the personalization capabilities, as they would not allow users to fully express their preferences. Therefore, the most effective solution is to enable the ability to upload and apply custom fonts, such as .ttf files. This would give users the freedom to select any font they find visually appealing, rather than being restricted to a set of default or preset options.

### Issue Labels

visual improvement

### Additional Information

Allowing users to upload and use custom fonts, such as .ttf files, is a feature seen in various modern applications, including design software and media players. By incorporating this option, FreeTube would not only increase user satisfaction but also enhance its flexibility and appeal for a broader audience.

Additionally, this feature could be implemented in a way that maintains FreeTube’s current performance. By ensuring that the fonts are optimized for both readability and rendering speed, the user experience would remain smooth. Providing guidance on supported font types and sizes would also ensure that users can easily integrate their preferred fonts without technical difficulties.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-29 22:15
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5766

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-29 22:15 UTC
Labels: enhancement, E: visual improvement
