### ISSUE TITLE
I tried using FreeTube but it didn't work for me. Getting "The address wasn't understood" error

### ISSUE THREAD

**Issue by amit-raut** [FreeTubeApp/FreeTube#118] opened 2018-06-14 15:28 UTC
I tried using FreeTube on latest version of firefox on mac and it never leads to the expected results. I just see "The address wasn't understood" error. 

Is there anything I need to do more to use it? 

Detailed Error:

The address wasn’t understood

Firefox doesn’t know how to open this address, because one of the following protocols (freetube) isn’t associated with any program or is not allowed in this context.

    You might need to install other software to open this address.

<img width="1346" alt="error" src="https://user-images.githubusercontent.com/12902959/41422040-13901a40-6fc6-11e8-9c3d-fbe2f4d1ec76.png">

Thank you,
Amit

**Comment by PrestonN** [comment] 2018-06-16 14:31
Hey there.  This is a known issue.  Unfortunately I don't have a Mac that I can test with right now but I'm working on getting a virtual machine setup for this in the future.

The problem is that your computer does not know how to handle the `freetube:` protocol.  This protocol is setup during the installation of FreeTube.  Unfortunately the current Mac release is considered more of a "portable" version instead of an "installed" version.  When i can setup .dmg support and you install FreeTube using that file, this issue should be fixed.

I don't know how useful it would be, but in the mean time I'd take a look at #44 and see if you can get it working using the instructions in that thread.

**Comment by amit-raut** [comment] 2018-06-22 19:41
Thank you @PrestonN for your response. I'll check if there is a way I can make use of `freetube:` protocol on macOS. :)

**Comment by PrestonN** [comment] 2018-06-28 17:24
One other thing that I forgot to mention.  If you're crafty enough to do so, you should be able to build a .dmg on your Mac and see if it works after installing that.  It _should_ work but I haven't tried it so I don't know for sure.  If you're unsure on how to do this then I can give you some instructions.  It shouldn't be too bad to do.  I'd love to know what the results are if you try this. :)

**Comment by drod3763** [comment] 2018-09-12 16:33
I would be up for trying. I think I am having this issue but I don't see that particular error page. It just opens FreeTube but doesn't open any videos.

**Comment by PrestonN** [comment] 2018-09-13 14:11
FreeTube needs to be open prior to clicking on a video in order for it to redirect properly.  I'm hoping to change the behavior of this in the future.

**Comment by drod3763** [comment] 2018-09-13 17:48
Even when its open it still doesn't work. When I say open, I mean it comes into focus on my desktop.

**Comment by aldobelus0** [comment] 2018-11-22 23:31
Same for me. Even when the program is open, the extension doesn't work, it won't open.

**Closed** 2020-09-29 19:41 UTC
Labels: bug
