### ISSUE TITLE
[Bug]: Unexcepted token [1:71], video plays fine in browser

### ISSUE THREAD

**Issue by windowsfan6** [FreeTubeApp/FreeTube#6328] opened 2024-12-09 17:51 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I was going to download a video, since I needed it for a project. However, it didn't load, both with Local and Invidious API's, which it means that it's YT screwing things again. The video is https://youtu.be/rek5_c1BXQI.

All other videos play just fine, and this video plays fine in a browser.

### Expected Behavior

Video should play as usual.

### Issue Labels

accessibility issue, API issue, content not loading, feature stopped working

### FreeTube Version

v0.22.0

### Operating System Version

Windows 10, version 21H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

[bundle-1733766668291.log](https://github.com/user-attachments/files/18065816/bundle-1733766668291.log)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Bennguyen2** [comment] 2024-12-09 18:00
Glad I wasn't the one that I'm having the same issues. This is what the "Unexcepted token [1:71]" error looks like on the screenshot.

![Screenshot_20241209_125842](https://github.com/user-attachments/assets/38a0d2ad-7fa8-4577-b021-ac2b86236458)

**Comment by absidue** [comment] 2024-12-09 18:02
Please don't leave "me too" comments, we are aware of the problem, spamming the thread doesn't help anyone.

**Comment by Ex-Ark** [comment] 2024-12-09 18:04
Showing console logs I can see the following error stack
![image](https://github.com/user-attachments/assets/801d08b7-8954-4398-b0d3-5ed7536e5c0d)

**Comment by rjdg14** [comment] 2024-12-09 18:06
Something I feel I should be mentioned would be that be that the problem doesn't seem to be affecting videos that I've watched in the past few hours, and they all stream fine when I attempt to watch them again, but it seems to be affecting any new video users attempt to stream. This suggests that it may be cookie/token related.

**Comment by absidue** [comment] 2024-12-09 18:07
@windowsfan6  Thank you for providing the logs, according to that the Invidious error is just that the Invidious instance you are using is temporarily unavailable, as for the local API error that is caused by a YouTube deciphering code change. They did a few of those recently the previous ones just failed silently, so you would only notice them when you specifically used the legacy formats but it looks like they've done another change, this time causing an error earlier on in the process.

**Comment by windowsfan6** [comment] 2024-12-09 18:14
It's worth to mention that the "fake age restriction" popup appears even when the errror is just Invidious API error, at least for me. I think it should've been changed to show only when trying to actually play age restricted videos.

**Comment by absidue** [comment] 2024-12-09 18:16
@windowsfan6 Please stay on-topic, as mentioned in your other issue that has nothing to do with age-restrictions.

**Comment by SciverSatoh** [comment] 2024-12-09 19:01
This problem appears to be affecting music videos specifically on my end. I don't know if that's useful or not but I hope it helps.

**Comment by rjdg14** [comment] 2024-12-09 19:16
> This problem appears to be affecting music videos specifically on my end. I don't know if that's useful or not but I hope it helps.

I can confirm that it seems to be impacting most videos that I suspect ContentID has flagged for containing music, yet doesn't appear to be affecting most other videos.

**Comment by DestructionDyme** [comment] 2024-12-09 19:34
I've tested around 100 of my music videos and until now every single video of channels who promote various artists aren't working while around 90 % of the music videos from the channels of the artists work. I don't have a clue why 10 % are affected tho cause not all of the affected ones were remixes of popular songs or had a lot of views.

**Comment by scoop96** [comment] 2024-12-09 21:26
im adding the other message  that the app gave me (just because nobody published it)

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by kuligs2** [comment] 2024-12-09 22:33
In the last hour videos that i have in playlist wont play, just tried nightly build, same error:
[BAD_HTTP_STATUS: 403] YouTube watch session expired. Please reopen this video
Error: Unexpected token (1:71)

before that it was working

Its a music playlist so i listen to them every day..

https://youtu.be/J20JcIFpnx0

It works in browser but not in freetube.. maybe there is a way to reset cookies or cache or something?.. Other new videos in subscriptions works, just the playlist with the music does not.. none of the videos

![image](https://github.com/user-attachments/assets/ba30d983-4426-4dc9-b276-35adae057700)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-09 23:51
UPDATE: [Upstream fix is being tested as we speak](https://github.com/LuanRT/YouTube.js/pull/832)

**Comment by liammcsh2008** [comment] 2024-12-10 02:10
It seems like when it switches to Invidious it works now. Invidious has fixed the bug.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-10 13:43
UPDATE: [Upstream fix has been released and we are currently testing it on our end as we speak](https://github.com/FreeTubeApp/FreeTube/pull/6341)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-10 14:19
UPDATE: We have tested the fix on our end and we will put out a hotfix release ASAP.

**Comment by ArthurKun21** [comment] 2024-12-10 14:38
Tested and working! many thanks

**Comment by rowo2002** [comment] 2024-12-10 16:25
Many thanks! Tested [78f75d3](https://github.com/FreeTubeApp/FreeTube/commit/78f75d3f13d9e086082329f489af9e00cf93f89d) and it worked but every video is played with a resolution of 360p only. Is this expected behavior or only a problem on my side?

**Comment by Bennguyen2** [comment] 2024-12-10 16:31
@rowo2002 I don't have that issue.

**Comment by rowo2002** [comment] 2024-12-10 16:57
@Bennguyen2 Thank you for your quick hint. Don't know how -  don't know why - my default video format was set to legacy :-( after returning to DASH everything is fine again!

**Comment by kuligs2** [comment] 2024-12-10 17:49
https://github.com/FreeTubeApp/FreeTube/actions/runs/12259959051 tested wut this - works fine, thank you bois, world is safe yet again

**Comment by kelua168** [comment] 2024-12-10 18:35
it works for me .. thank you !

**Comment by rjdg14** [comment] 2024-12-10 23:45
When attempting the MacOS ARM64 build of the fix it seems to claim that it is damaged and can't be opened. This may be due to signed software settings in newer versions of MacOS. Is there any terminal command that will make it work (as I think you can use to bypass this)?

**Comment by rjdg14** [comment] 2024-12-11 02:03
The issue does still seem to be occuring on a few videos in the patched Nightly build although a much smaller percentage.

**Comment by ArthurKun21** [comment] 2024-12-11 04:37
78f75d3f13d9e086082329f489af9e00cf93f89d

Agree with @rjdg14 it looks like some music videos is still getting it

```log
renderer.js:2 eB: Unexpected token (1:71)
    at zV.evaluate (app://bundle/renderer.js:2:1561535)
    at Object.eval (app://bundle/renderer.js:2:1673389)
    at _$.decipher (app://bundle/renderer.js:2:1573009)
    at tN.decipher (app://bundle/renderer.js:2:1354987)
    at app://bundle/renderer.js:2:1790091
    at zK (app://bundle/renderer.js:2:1790103)
    at async r.getVideoInformationLocal (app://bundle/renderer.js:2:2243809)
getVideoInformationLocal @ renderer.js:2
await in getVideoInformationLocal
onMountedDependOnLocalStateLoading @ renderer.js:2
mounted @ renderer.js:2
Ht @ renderer.js:2
wi @ renderer.js:2
insert @ renderer.js:2
Ht @ renderer.js:2
i @ renderer.js:2
T @ renderer.js:2
(anonymous) @ renderer.js:2
e._update @ renderer.js:2
n @ renderer.js:2
e.get @ renderer.js:2
e.run @ renderer.js:2
Li @ renderer.js:2
(anonymous) @ renderer.js:2
Xt @ renderer.js:2
Promise.then
Wt @ renderer.js:2
ti @ renderer.js:2
Mi @ renderer.js:2
e.update @ renderer.js:2
e.$forceUpdate @ renderer.js:2
(anonymous) @ renderer.js:2
l @ renderer.js:2
Ht @ renderer.js:2
i @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
qs @ renderer.js:2
(anonymous) @ renderer.js:2
requestAnimationFrame
(anonymous) @ renderer.js:2
requestAnimationFrame
zs @ renderer.js:2
C @ renderer.js:2
Zs @ renderer.js:2
remove @ renderer.js:2
C @ renderer.js:2
_ @ renderer.js:2
(anonymous) @ renderer.js:2
e._update @ renderer.js:2
n @ renderer.js:2
e.get @ renderer.js:2
e.run @ renderer.js:2
Li @ renderer.js:2
(anonymous) @ renderer.js:2
Xt @ renderer.js:2
Promise.then
Wt @ renderer.js:2
ti @ renderer.js:2
Mi @ renderer.js:2
e.update @ renderer.js:2
e.notify @ renderer.js:2
set @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
Hl.updateRoute @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
n @ renderer.js:2
n @ renderer.js:2
Bl @ renderer.js:2
(anonymous) @ renderer.js:2
n @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
g @ renderer.js:2
n @ renderer.js:2
n @ renderer.js:2
n @ renderer.js:2
Bl @ renderer.js:2
Hl.confirmTransition @ renderer.js:2
Hl.transitionTo @ renderer.js:2
t.push @ renderer.js:2
(anonymous) @ renderer.js:2
tc.push @ renderer.js:2
rQ.push @ renderer.js:2
y @ renderer.js:2
Ht @ renderer.js:2
i @ renderer.js:2
a._wrapper @ renderer.js:2
renderer.js:2 WARNING: Too many active WebGL contexts. Oldest context will be lost.
(anonymous) @ renderer.js:2
NC @ renderer.js:2
n.configure @ renderer.js:2
$C @ renderer.js:2
bk @ renderer.js:2
(anonymous) @ renderer.js:2
Ht @ renderer.js:2
wi @ renderer.js:2
insert @ renderer.js:2
T @ renderer.js:2
(anonymous) @ renderer.js:2
e._update @ renderer.js:2
n @ renderer.js:2
e.get @ renderer.js:2
e.run @ renderer.js:2
Li @ renderer.js:2
(anonymous) @ renderer.js:2
Xt @ renderer.js:2
Promise.then
Wt @ renderer.js:2
ti @ renderer.js:2
Mi @ renderer.js:2
e.update @ renderer.js:2
e.notify @ renderer.js:2
set @ renderer.js:2
setAppTitle @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
fc._withCommit @ renderer.js:2
fc.commit @ renderer.js:2
commit @ renderer.js:2
setAppTitle @ renderer.js:2
(anonymous) @ renderer.js:2
fc.dispatch @ renderer.js:2
dispatch @ renderer.js:2
Ic.forEach.i.<computed> @ renderer.js:2
updateTitle @ renderer.js:2
(anonymous) @ renderer.js:2
Promise.then
getVideoInformationInvidious @ renderer.js:2
getVideoInformationLocal @ renderer.js:2
await in getVideoInformationLocal
onMountedDependOnLocalStateLoading @ renderer.js:2
mounted @ renderer.js:2
Ht @ renderer.js:2
wi @ renderer.js:2
insert @ renderer.js:2
Ht @ renderer.js:2
i @ renderer.js:2
T @ renderer.js:2
(anonymous) @ renderer.js:2
e._update @ renderer.js:2
n @ renderer.js:2
e.get @ renderer.js:2
e.run @ renderer.js:2
Li @ renderer.js:2
(anonymous) @ renderer.js:2
Xt @ renderer.js:2
Promise.then
Wt @ renderer.js:2
ti @ renderer.js:2
Mi @ renderer.js:2
e.update @ renderer.js:2
e.$forceUpdate @ renderer.js:2
(anonymous) @ renderer.js:2
l @ renderer.js:2
Ht @ renderer.js:2
i @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
qs @ renderer.js:2
(anonymous) @ renderer.js:2
requestAnimationFrame
(anonymous) @ renderer.js:2
requestAnimationFrame
zs @ renderer.js:2
C @ renderer.js:2
Zs @ renderer.js:2
remove @ renderer.js:2
C @ renderer.js:2
_ @ renderer.js:2
(anonymous) @ renderer.js:2
e._update @ renderer.js:2
n @ renderer.js:2
e.get @ renderer.js:2
e.run @ renderer.js:2
Li @ renderer.js:2
(anonymous) @ renderer.js:2
Xt @ renderer.js:2
Promise.then
Wt @ renderer.js:2
ti @ renderer.js:2
Mi @ renderer.js:2
e.update @ renderer.js:2
e.notify @ renderer.js:2
set @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
Hl.updateRoute @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
n @ renderer.js:2
n @ renderer.js:2
Bl @ renderer.js:2
(anonymous) @ renderer.js:2
n @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
g @ renderer.js:2
n @ renderer.js:2
n @ renderer.js:2
n @ renderer.js:2
Bl @ renderer.js:2
Hl.confirmTransition @ renderer.js:2
Hl.transitionTo @ renderer.js:2
t.push @ renderer.js:2
(anonymous) @ renderer.js:2
tc.push @ renderer.js:2
rQ.push @ renderer.js:2
y @ renderer.js:2
Ht @ renderer.js:2
i @ renderer.js:2
a._wrapper @ renderer.js:2
```

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-11 14:38
@rjdg14 @ArthurKun21 we cant reproduce this yet on our end. Could you maybe provide some urls? Are you using a VPN and if so where was the server located when the error occurred?

**Comment by ArthurKun21** [comment] 2024-12-11 15:43
> Could you maybe provide some urls?

I don't have specific urls, but it was mostly music videos. But I can say that it is not happening too much.

> Are you using a VPN

nope

**Comment by rjdg14** [comment] 2024-12-11 15:44
> > Could you maybe provide some urls?
> 
> I don't have specific urls, but it was mostly music videos. But I can say that it is not happening too much.
> 
> > Are you using a VPN
> 
> nope

In my experience the occasional music video still displays the error and then plays after a couple of tries.

**Comment by TheOracle22** [comment] 2024-12-11 15:50
> @rjdg14 @ArthurKun21 we cant reproduce this yet on our end. Could you maybe provide some urls? Are you using a VPN and if so where was the server located when the error occurred?

Here are some URL's to reproduce:
https://youtu.be/v5ryZdpEHqM

https://youtu.be/_vw--yxcDNM

https://youtu.be/ZQCoh1PJjOk

These work totally fine in the browser, but give the error in this bug description in Freetube.

**Comment by ArthurKun21** [comment] 2024-12-11 15:52
> Here are some URL's to reproduce: https://youtu.be/v5ryZdpEHqM
> 
> https://youtu.be/_vw--yxcDNM
> 
> https://youtu.be/ZQCoh1PJjOk

I tried loading this and only the 3rd one produced the error for me.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-11 17:05
UPDATE: The error mentioned in the recent comments has been reproduced. We have to investigate this further. This will probably result in another upstream change.

**Comment by rjdg14** [comment] 2024-12-11 20:16
The issue now seems to have returned to most previously affected videos despite not occuring on non-music videos.

Is there a reason why the issue seems to only be affecting videos that YouTube detects as containing copyrighted music? I know such videos usually contain a metadata section in their description that other videos lack, and perhaps this could be why, but don't otherwise see how the format of videos containing music is any different from other videos.

It would be interesting to know if the problem is also impacting non-music videos that contain other forms of content flagged by ContentID (eg: TV shows or certain video games).

NewPipe is unaffected by this particular issue so it's definitely fixable.

**Comment by riverpiers** [comment] 2024-12-11 20:37
I encountered the same error today on a channel where I previously watched videos normally. Channel: https://www.youtube.com/@thedorbrothers/videos On v0.22.0-nightly-5100 Beta.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-12 02:06
UPDATE: [second upstream fix is being tested as we speak](https://github.com/LuanRT/YouTube.js/pull/837)

**Comment by Tetriser** [comment] 2024-12-12 05:59
I got the 403 error whenever I try to open videos with "copyrighted music", is this related to this issue?
![image](https://github.com/user-attachments/assets/436c227c-3760-42dd-9661-bec3b2b41e57)

**Comment by ndgsa** [comment] 2024-12-12 13:49
Used: https://github.com/LuanRT/YouTube.js/pull/832
Compiled.
Works.
![Untitled](https://github.com/user-attachments/assets/e545c68c-d21e-48c2-838e-46f46bcd8d01)

P.S Thanks devs!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-12 13:59
UPDATE: [Second upstream fix has been released and we are currently testing it on our end as we speak](https://github.com/FreeTubeApp/FreeTube/pull/6359)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-12 14:10
@Tetriser there is a high chance that this is related. Lets wait for the second fix to be merged so others can verify is this is resolved

**Comment by chasewalsh** [comment] 2024-12-12 17:00
Fixed for me with 0.22.1.  I'm using a locally compiled arm64 version.  Much thanks for the fix so I can enjoy my dj mix videos again.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-12 17:12
UPDATE: We have tested the second fix on our end and if no more reports will come in we will put out a hotfix release ASAP.

**Comment by scoop96** [comment] 2024-12-12 21:17
@efb4f5ff-1298-471a-8973-3d47447115dc  @kuligs2 
This video keeps breaking with the update

https://youtu.be/tS_apmFNEU8?si=cDu5RX0UzMvPYMd3

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-12 21:19
Hi @scoop96 what version are you using?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-13 06:51
UPDATE:

v0.22.1 has been released! You can download the latest version using the following methods:
- [GitHub release page](https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.22.1-beta)
- [Through our website](https://freetubeapp.io/#download)

Thank you for being patient and happy watching 📺!

**Closed** 2024-12-13 06:52 UTC
Labels: bug, B: content not loading, B: accessibility, B: feature stopped working, B: API issue, U: reproduced

**Comment by kLabz** [comment] 2024-12-13 06:59
Thanks! solves most issues I think.

Still broken there: https://youtu.be/XmYM505rHkQ with `freetube-nightly-0.21.2_nightly_4590-1`

**Comment by ArthurKun21** [comment] 2024-12-13 07:01
Nightly is now 5304

https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml

**Comment by cartersocha** [comment] 2024-12-14 08:26
I updated to v22.1 beta and am still receiving this error on some music videos. I built locally on my Mac arm laptop. 

Error specifically occurs on this video: https://youtu.be/a5uQMwRMHcs

**Comment by absidue** [comment] 2024-12-14 08:28
@cartersocha As you said you built it yourself could you please specify exactly which commit you are using?

**Comment by cartersocha** [comment] 2024-12-14 08:35
The yarn install seems to have fixed it. Thanks for the prompt reply! Im on 22.1 beta

**Comment by absidue** [comment] 2024-12-14 08:41
@cartersocha Okay good to know it was caused by not building it correctly and not an actual problem with FreeTube. If you are going to be doing custom builds for yourself please make sure you build it correctly next time and test with one of the official builds, before reporting something as an issue with FreeTube.

**Comment by Astaoth** [comment] 2024-12-21 12:37
Hi,

When using the invidious API, the videos can't be played, with an error similar to https://github.com/FreeTubeApp/FreeTube/issues/6362

- With https://inv.nadeko.net I have : "SyntaxError: Unexpected token 'A', "API disabled" is not valid JSON"
- With https://yewtu.be I have "SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON"
- https://invidious.jing.rocks seems to work : I've been able to load a video, when I don't have a rate limit error (most of the time it's "Error: This content isn't available, try again later.", not a Freetube).
