### ISSUE TITLE
[Feature Request]: Make the huge play button transparent(er) on hover out

### ISSUE THREAD

**Issue by karolyi** [FreeTubeApp/FreeTube#6027] opened 2024-10-29 22:08 UTC
### Problem Description

Hey,

congratulations on implementing a new player! So far, everything works good, I have only one qualm though:

The play button is immensely huge, and it doesn't go transparent (or at least semi-transparent) when I halt the video and hover out. I sometimes pause videos to read text in it, or to look at details or for whatever else reason.

I can't read text when there's a humongous white play button eats up all the available video real estate :)

So as said in the title: please make the huge play button transparent(er) on hover out. This worked with the old player.

### Issue Labels

ease of use improvement

**Comment by absidue** [comment] 2024-10-29 23:26
Duplicate of #5951

**Closed** 2024-10-29 23:26 UTC
Labels: enhancement, E: ease of use improvement
