### ISSUE TITLE
[Bug]: Can't Listen To This Song

### ISSUE THREAD

**Issue by eternalnothing** [FreeTubeApp/FreeTube#2317] opened 2022-06-13 18:09 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

I can't listen to Breaking the Habit by Linkin Park. It is impossible to watch the video on FreeTube. The link to the video is: https://youtu.be/v2H4l9RpkwM

The reason is probably because the video has a warning about the video's content. Warning reads:
_The following content may contain suicide or self-harm topics._

You can click the 'I understand and wish to proceed' button to watch the video.

This is a recent attempt by YouTube to get into people's business so understandably currently causes bugs in FreeTube.

### Expected Behavior

I should be able to watch the video directly without getting the original warning. The warning is a nuisance and a form of tyranny.

### Issue Labels

content not loading

### FreeTube Version

0.16.0

### Operating System Version

Windows 10 Home Single Language 21H1 19043.1706

### Installation Method (If applicable)

.exe

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by gtsop** [comment] 2022-06-16 19:03
Am I wrong to think this is a bug for invidious? The invidious API instances can't seem to play this video themselves.

**Comment by fugbixer** [comment] 2022-06-19 22:28
Yeah @gtsop  but the issue is for example in playlists etc. sometimes it loads sometimes it does not.
Either retry 3 times, than use fallback method (works often) use the invidious feature local=true which proxies the content through the invidious server or if in playlist, skip to next item to avoid endless stuck until user interaction.

often these issues are based on not whitelisted  / blacklisted region (youtube video setting) and requesting ip location

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-10-10 15:34
getting a 410 error on the local api so it seems like this is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1296

also not getting errors on invidious

**Closed as completed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-10-10 15:34 UTC
Labels: bug, U: duplicate, third-party, B: content not loading
