### ISSUE TITLE
[Bug]: YouTube's New Dubs

### ISSUE THREAD

**Issue by StandingPadAnimations** [FreeTubeApp/FreeTube#3388] opened 2023-04-02 22:00 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click on a video with dubs, like the recent Mr. Beast video	
2. Instead of English audio, the Arabic dub is played

### Expected Behavior

At least a way to select between different dubs

### Issue Labels

usability issue

### FreeTube Version

0.18.0-1

### Operating System Version

Linux arch 6.2.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 30 Mar 2023 14:51:14 +0000 x86_64 GNU/Linux

### Installation Method

AUR

### Primary API used

Local API

### Additional Information

Dubs are a feature in YouTube that allow different audio tracks for different languages

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-04-03 05:43
duplicate of #2419

**Closed** 2023-04-03 05:44 UTC
Labels: bug, U: duplicate, B: usability, B: Unofficial Download
