### ISSUE TITLE
[Bug]: Spanish dub playing on some videos

### ISSUE THREAD

**Issue by TheRedOnline** [FreeTubeApp/FreeTube#3694] opened 2023-06-22 19:08 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Not even sure how to start troubleshooting this one...

I started watching [this](https://vid.puffyan.us/watch?v=mWEE2RJj3YI) video.  And a Spanish (I think) translator started playing.  I copied the invidious link and it plays fine from invidious.  Taking that same link back to freetube, once again, has a translator.  I want to make this clear, this is an audio overlay, not text captions.  I am using v0.18.0 Beta but I remember this happening a few times before.  This also happens between my Fedora, Arch and Windows 10 machines.  I have not installed any program that could do this.

### Expected Behavior

Have video play with correct language

### Issue Labels

usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Windows 10, Arch, Fedora

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

unknown

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-06-23 07:53
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2419

This is fixed for the Local API in https://github.com/FreeTubeApp/FreeTube/pull/3563 but not for Invidious because they doesnt support switching audio tracks yet.

Use the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds) to make use of this feature.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-06-23 07:53 UTC
Labels: bug
