### ISSUE TITLE
[Bug]:  Freetube disables full screen on next playback

### ISSUE THREAD

**Issue by Faviously** [FreeTubeApp/FreeTube#5332] opened 2024-06-24 16:23 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Freetube disables full screen on next playback.
When a video finishes playing in full screen, the next one in the list goes out of full screen to the player in small format with the controls.

### Expected Behavior

If a video finishes playing in full screen then the next one should continue in full screen as well.

### Issue Labels

visual bug

### FreeTube Version

v0.21.0 Beta

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-06-24 16:25
duplicate of #2295

**Closed by absidue** 2024-06-24 16:25 UTC
Labels: bug, B: visual
