### ISSUE TITLE
[Bug]: Cannot import playlist; file does not show up in explorer

### ISSUE THREAD

**Issue by stealthswor** [FreeTubeApp/FreeTube#3891] opened 2023-08-17 00:14 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. get file from youtube takeout manager
2. extract .zip
3. go to import playlists
4. file does not appear where it should

### Expected Behavior

The file appears in the explorer program

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Edition	Windows 10 Home Version	22H2 Installed on	‎10/‎19/‎2020 OS build	19045.3324 Experience	Windows Feature Experience Pack 1000.19041.1000.0

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

The import subscription feature worked as intended.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-08-17 05:57
This isnt possible yet.

Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1016

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-08-17 05:57 UTC
Labels: bug
