### ISSUE TITLE
[Bug]: Problem with subscription.csv import

### ISSUE THREAD

**Issue by Lothnar** [FreeTubeApp/FreeTube#4177] opened 2023-10-17 11:26 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When I import subscriptions.csv from
Settings->Data Settings->Import Subscriptions

in one case - with "local API" selected - nothing happened
in second case - with "invidious API" selected - I have errors after

### Expected Behavior

I expect my subscriptions will import and show in Subscriptions menu

### Issue Labels

API issue, feature stopped working

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 10 22H2 - 19045.3570

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

![1](https://github.com/FreeTubeApp/FreeTube/assets/148215256/8f4f4de7-7b9a-4c14-8efb-fa9f9871e4fe)
![2](https://github.com/FreeTubeApp/FreeTube/assets/148215256/b39ba0a8-b4ab-481d-a054-0327b1bf856a)
![3](https://github.com/FreeTubeApp/FreeTube/assets/148215256/dac1bcb2-0cc1-4c45-8058-026fb8cadf70)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-17 12:28
how many subscriptions do you have?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-17 12:31
please follow https://docs.freetubeapp.io/usage/importing-subscriptions/#troubleshooting-issues

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-17 12:37
This is a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3943

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-10-17 12:37 UTC
Labels: bug, U: Waiting for Response from Author, B: feature stopped working, B: API issue
