### ISSUE TITLE
Feature request change the volume with the wheel also in the PiP

### ISSUE THREAD

**Issue by Janaue** [FreeTubeApp/FreeTube#1926] opened 2021-11-30 13:18 UTC
i

I would like the ability to change the volume with the tiny PiP too, so when the mouse wheel is over the video, the volume is changed too

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-12-31 12:48
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1284

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-12-31 12:48 UTC
Labels: enhancement, U: doesn't follow template
