### ISSUE TITLE
Incoherent indication for "premiere soon" videos

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#795] opened 2020-11-16 11:07 UTC
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**
2 videos that have a "premiere soon" at the exact same time doesn't have the same indication.

**Expected behavior**
The same indication for both of the videos.

**To Reproduce**
1) Subscribe to channels using the premiere system.

**Screenshots**
Both of the video here below have their premiere at the exact same time.
![Screenshot_20201116_120240](https://user-images.githubusercontent.com/22192600/99245420-7483c780-27fb-11eb-810c-83816f9bb3a2.png)

**Environment Information (please complete the following information):**
 - OS: Debian
 - OS Version: 10.6
 - FreeTube version: 0.9.2 beta
 - Installation Method (If applicable): deb package
 - Primary API Used: Default is local API, but jumps to iv API if it fails

**Comment by GilgusMaximus** [comment] 2020-11-16 16:03
Closing because duplicate of #754

**Closed** 2020-11-18 16:20 UTC
Labels: bug
