### ISSUE TITLE
[Bug]: Buffer Fails on Extended Resume

### ISSUE THREAD

**Issue by hl2guide** [FreeTubeApp/FreeTube#4136] opened 2023-10-11 22:27 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Play a video
2. Pause it after 10 seconds
3. Leave it open for a few hours (paused)
4. Come back and play it
5. The buffer will only play for a few seconds
6. Endless spinner with no resume, forces refresh

### Expected Behavior

Video plays as normal.

### Issue Labels

content not loading

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 10 Pro

### Installation Method

.zip

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-10-12 07:46
This is definitely a duplicate of an existing issue but I can't find it at the moment, hopefully one of the other contributors can.

This is caused by the streaming URLs expiring after 6 hours. The easiest solution would just be for us to reload the watch page when we detect a player error more than 6 hours after you opened the watch page, but I suspect that would be disliked because you would loose your playback position and all of your player settings (payback rate, selected subtitle track, selected audio track).

I'm sure it's possible to come up with a better solution, that doesn't require reloading the entire watch page, but that might have to wait until we've switched to the new player.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-12 22:17
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1964

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-10-12 22:17 UTC
Labels: bug, B: content not loading
