### ISSUE TITLE
Comments haven't been loading for about a week, and age restricted videos have suddenly stopped loading again

### ISSUE THREAD

**Issue by rjdg14** [FreeTubeApp/FreeTube#1539] opened 2021-07-22 22:55 UTC
For about the past week or so, I've been getting the error "TypeError: Cannot read property 'continuationContents' of undefined" along with "undefined" when attempting to load the comments segment of any video containing comments. This is the same message that you'd normally see on a video without comments or where comments have been disabled. Age restricted videos have also stopped loading yet again, with the error "Error: Status code: 404" alongside "{"error":"Could not extract video info. Instance is likely blocked."}", which is the same error that has occured the two times these became broken in the past.

These are almost certainly down to the ytdl core needing an update, though I feel I should bring them up to try and ensure that they're fixed as soon as the ytdl core gets updated.

**Comment by rjdg14** [comment] 2021-07-22 23:02
I also want to add that if I change the Invidious instance to https://invidious.namazso.eu and try and load an age restricted video, I also receive the following long error:

`{"error":"Could not check out a connection in 2.0 seconds","errorBacktrace":"Could not check out a connection in 2.0 seconds (DB::PoolTimeout)\n  from lib/db/src/db/pool.cr:240:9 in 'wait_for_available'\n  from lib/db/src/db/pool.cr:85:35 in 'checkout'\n  from src/invidious/helpers/utils.cr:35:7 in 'fetch_video'\n  from src/invidious/videos.cr:961:13 in 'get_video'\n  from src/invidious/videos.cr:944:1 in 'get_video:region'\n  from src/invidious.cr:2210:13 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'\n  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:212:5 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:94:12 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:158:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:70:5 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/logger.cr:17:35 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'\n  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'\n  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'\n  from /usr/share/crystal/src/http/server.cr:468:13 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'\n  from /usr/share/crystal/src/fiber.cr:92:34 in '->'\n  from ???\n"}`

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-23 07:26
Duplicate of #1490

@PrestonN

**Comment by GilgusMaximus** [comment] 2021-07-23 17:02
yes, duplicates of both

**Closed by GilgusMaximus** 2021-07-23 17:02 UTC
Labels: bug
