### ISSUE TITLE
Picture in Picture mode for autoplay

### ISSUE THREAD

**Issue by pablodekota** [FreeTubeApp/FreeTube#927] opened 2021-01-12 23:40 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
When autoplay is active, the Picture in Picture mode doesnt automatically get activated on the new video, it just stays on the old one.

**Describe the solution you'd like to see implemented**
I would like the PIP mode to carry over on next videos when autoplay is on, tho i would still like it to stay when i click home, so i can find new videos while still watching the original one

**Describe alternatives you've considered**
I personally dont know how to do this, if i did, i would have made a PR, but as an example when you use firefoxes PIP mode, the next video uses PIP aswell.

**Comment by GilgusMaximus** [comment] 2021-01-14 11:45
The PiP has some problems, or more like intended behavior. E.g. it does not go back to the video once you leave the page. To make it more useful a lot of work has to be done. 

#624

**Comment by pablodekota** [comment] 2021-01-15 21:35
> The PiP has some problems, or more like intended behavior. E.g. it does not go back to the video once you leave the page. To make it more useful a lot of work has to be done.
> 
> #624

@GilgusMaximus 
that is not my concern, that it not going back to a video can be overdone by just going back and minimizing it into the player and it will act as if you continued watching, my only real issue is that it wont go to the next video when autoplay is active

**Comment by GilgusMaximus** [comment] 2021-05-13 17:29
So this sounds like a good plan. But I'd maybe change one thing. Instead of adding the parameter to the URL, it'd be better to add a boolean value lastPlayedAsPip to the state of the app, so the information is stored across the videos for normal autoplay, YouTube playlists and custom playlists in the future. Because there is no format yet for custom playlists, and whether we'll actually store the whole URl or just the videoId, it'd be more future proof to decouple that from the next video.

But otherwise it sounds good

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-06-05 23:17
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2295

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-06-05 23:17 UTC
Labels: enhancement
