### ISSUE TITLE
No videos show in the subscribed channel

### ISSUE THREAD

**Issue by jannymcd** [FreeTubeApp/FreeTube#520] opened 2020-08-24 21:11 UTC
my subscriptions are all on YT but no longer appear on FT.... 
Maybe YT censor but even CNN doesnt have video's
![Image 08-24-20 at 4 54 PM](https://user-images.githubusercontent.com/69284735/91096390-f5338d00-e62b-11ea-90a7-127a0b34cd9b.jpg)

**Comment by jannymcd** [comment] 2020-08-24 21:12
![Image 08-24-20 at 4 54 PM](https://user-images.githubusercontent.com/69284735/91097017-f74a1b80-e62c-11ea-841b-f3681eecc729.jpg)

**Comment by PrestonN** [comment] 2020-08-24 21:12
Duplicate of #513, which is a duplicate of [this](https://github.com/iv-org/invidious/issues/1333) issue on Invidious.  Closing

**Comment by jannymcd** [comment] 2020-08-24 21:13
Im just learning, this was my 1st post, ty so much!

**Closed by PrestonN** 2020-08-24 21:12 UTC

**Comment by PrestonN** [comment] 2020-08-24 21:29
All good.  I still appreciate you for being a part of this community! :)
