### ISSUE TITLE
[Question]: Downloads and Comment Sorting

### ISSUE THREAD

**Issue by Rusenche** [FreeTubeApp/FreeTube#3917] opened 2023-08-21 17:59 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [ ] This issue contains only one bug.

### Describe the bug

See below, I have described it in detail.

### Expected Behavior

See below, I have described it in detail.

### Issue Labels

usability issue

### FreeTube Version

Freetube v.0.19.0 beta x64 portable

### Operating System Version

Windows 10 22H2

### Installation Method

PortableApps

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

Freetube v.0.19.0 beta x64 portable

### Additional Information

Hello

Your application is good.

I downloaded Freetube v.0.19.0 beta x64 portable.

I'm not sure if it's a bug or if I'm writing in the right section.

But to briefly describe my thoughts.

1. No visual ability to monitor download progress. There is simply nowhere to check how far a clip has been downloaded.

2. I find it strange that only video downloads are offered. I played a clip that supports 1080p. I decided to download it in 1080p. Turns out I can't download it in 1080p because the app only offers to download video but no audio. Someone explain to me why anyone would need to download only a video?! The only way to download a video + audio clip is at the lower 720p. This is what your app offers. And yet - someone explain why the app doesn't offer to download a 1080p video clip with video + audio?! The app offers you for 1080p only to download it, but only VIDEO (no audio). This is some madness.

3. There is no setting anywhere in the app that I can set in such a way that comments everywhere, whatever clip I open for viewing, are automatically sorted - "Newest first". Nowhere in the app did I find a setting to sort the comments and set "Newest first".

That's it. I hope you take my thoughts and implement them. These are the most basic things that must be fixed to make the app stand out.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-08-21 18:12
1. Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2110
2. This is intended behavior for now see https://github.com/FreeTubeApp/FreeTube/issues/582#issuecomment-703641821
3. Its best to create Feature request for this instead of in a bug report. Please be as detailed as possible in your feature request

**Comment by absidue** [comment] 2023-08-21 18:14
1. Yes the built-in downloader is very rudimentary right now, if you want to monitor progress I recommend setting the download behaviour setting to "Open in Browser".
2. YouTube provides the audio and video files separately, they get combined by the player while you are watching the video. If you want both audio and video, you need to download both an audio and video file, you need to download both and then use a program like ffmpeg to combine them into a single file. YouTube only provides two combined files (only one on some videos) 720p, default audio track, h264 MP4 and 360p, default audio track, h264 MP4.
3. Please send a screenshot of what the comments section looks like on your machine, because the sort by dropdown is definitely there on my machine.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-08-21 18:25
>     3. Please send a screenshot of what the comments section looks like on your machine, because the sort by dropdown is definitely there on my machine.

@absidue i think they mean that they would like an option in the settings to make sorting by recent comment the default

**Comment by Rusenche** [comment] 2023-08-21 18:31
You did not understood me.

Sorting is everywhere.

I want globally, with a setting from the application settings, to set it once according to the criteria I specified and for it to be this way everywhere, and not to manually change the way the comments are arranged on each clip.

As for ffmpeg.exe - the way you wrote it, it won't work. So some kind of GUI is required. Whoever runs ffmpeg.exe - it will open and in less than 1 second it will close.

As for 2, what you wrote - in practice, the download method is absolutely inconvenient.

As for the comment from @efb4f5ff-1298-471a-8973-3d47447115dc - needless to say it's a duplicate and from a thread that's 3 years old and has no development.

**Closed** 2023-08-21 18:34 UTC
Labels: question

**Comment by absidue** [comment] 2023-08-21 18:38
ffmpeg works if you use it correctly, it's a commandline tool, so double clicking on it will not have the desired effect.

There are various feature requests open to enhance the in-app downloader, please search the issue tracker next time, opening duplicate issues achieves nothing but to annoy us devs.

**Comment by Rusenche** [comment] 2023-08-21 18:47
> ffmpeg works if you use it correctly, it's a commandline tool, so double clicking on it will not have the desired effect.

I will allow myself to take an attitude only on this.

And that's for something as simple as downloading a video and wondering how to merge it with the audio... via commands in ffmpeg.exe. How do you imagine the average internet user learning commands to use in ffmpeg.exe?! I don't think this is the right approach.

/I see you are giving each other a thumbs up. I don't even understand what this accomplishes./

Gentlemen, you need to understand that different people have opinions, and you can't approach it in a way that you get annoyed if someone brings up a feature for discussion, and then treat it edifyingly.

I'm ending the discussion.
