### ISSUE TITLE
[Bug]: Portable app doesn't save subscriptions or other data

### ISSUE THREAD

**Issue by Gevaarlijk** [FreeTubeApp/FreeTube#3490] opened 2023-05-05 15:10 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Portable app doesn't save subscriptions or other data.

When transferred to another device subscriptions are gone. It seems they are saved locally but not in the FreeTube folder.

### Expected Behavior

I expect it to be portable.

### Issue Labels

content not loading

### FreeTube Version

?

### Operating System Version

Windows 10

### Installation Method

.zip

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-05-05 15:27
I consider this a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/746

**Closed** 2023-05-05 15:27 UTC
Labels: bug, B: content not loading
