### ISSUE TITLE
[Feature Request]: yt-dlp as a backend in addition to freetube api and invidious

### ISSUE THREAD

**Issue by Destroyinator69420** [FreeTubeApp/FreeTube#3667] opened 2023-06-14 20:47 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Youtube is harassing the developers of invidious and it is not as reliable as it used to be. The freetube local api also has reliability problems in my opinion.

### Proposed Solution

The lack of progress in invidious and the fact that youtube is harassing the invidious devs is highly problematic for the future of freetube. We need alternatives if youtube wins this battle. The natural candidate is yt-dlp, which can be included in the installer for freetube as a python zipapp. This means that the python interpreter built into the system will run the yt-dlp program cross platform. On Windows, users will need to install python from python.org, but many linux distributions provide python by default or make it easy to install via the package manager with "sudo dnf install python3" or "sudo apt-get install python3". yt-dlp is actively maintained and will work nicely with freetube as an alternative to invidious and the less reliable in my experience freetube backend.

### Alternatives Considered

Freetube could also use newpipe-extractor, which will require java instead of python. Newpipe-extractor works with java versions 8 and up. Same situation as yt-dlp except that freetube will require java to be installed instead of python.

### Issue Labels

new optional setting

### Additional Information

yt-dlp can be found at https://github.com/yt-dlp/yt-dlp and newpipe extractor can be found at https://github.com/TeamNewPipe/NewPipeExtractor. Both are licensed under the GPL-v3.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-06-14 21:38
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3291

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-06-14 21:38 UTC
Labels: enhancement, E: new optional setting
