### ISSUE TITLE
[Feature Request]: distinguish the "bookmark" function from the "watch later" function

### ISSUE THREAD

**Issue by goldanorak** [FreeTubeApp/FreeTube#4302] opened 2023-11-08 12:35 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

As it stands, the playlist function is more geared towards a "watch later" function, given that when videos are viewed they are displayed fainter and with the words "viewed".

### Proposed Solution

Would it be possible to add a "library" function, more suited to storing videos that have already been viewed but that we'd like to return to later? (and, as I proposed in another request, that each "profile" have a separate "library list"?)
Thanks

### Alternatives Considered

N/A

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-08 14:01
Multiple playlists are coming https://github.com/FreeTubeApp/FreeTube/pull/4234

But not for multiple profiles that is something that needs to addressed separately 

Duplicate of #1996

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-08 14:01 UTC
Labels: enhancement, E: improvement existing feature
