### ISSUE TITLE
[Feature Request]: Enable multiple invidious instances and automatically detect which work and which are the fastest ones

### ISSUE THREAD

**Issue by TheodorSmall** [FreeTubeApp/FreeTube#5547] opened 2024-08-09 09:04 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

This issue refers to the usage and usability of the invidious API, both as the primary and secondary API.

When encountering problems with loading / playing a video, it is often necessary to reload the video using an other invidious instance, and to repeat that process multiple times.

### Proposed Solution

- Making it possible to select multiple (or all) invidious instances at the same time
- If a video doesn't load at all, or won't load any further because of a fatal error, automatically switch to another working instance
- If a video does load, but is too slow to play smoothly, either another instance could be used, or two or more at the same time, fetching different parts of the video each (if something like that is even possible, of course)
- Download speed for each instance selected by the user can be cached, to use the fastest one(s) available

### Alternatives Considered

- Switch to PiP while changing the settings
- Adding a button on the player page to switch through invidious instances manually

### Issue Labels

ease of use improvement, improvement to existing feature, new optional setting

### Additional Information

- This is related to #5512, since the process of switching repeatedly through instances manually is more complicated because of this.
- I'm using "Proxy videos", so that's probably the reason so few instances work for me at the moment, however these change a few times per day

**Comment by Gorrrg** [comment] 2024-08-09 13:40
I wonder what the people who run all those Invidious instances think about features like this. I can imagine that they are already feeling the impact whenever YT is changing/blocking something. More might closing off access without an account.

**Comment by jsbrn** [comment] 2024-08-11 15:19
What about a "randomize instance" button in between the "clear" and "set as default" options? It could pull from wherever it sources the instance list on startup. That way we can save the user several clicks without dramatically changing our relationship to these providers.

Even better, an option under the video could choose a new random instance then refresh the page.

**Comment by TheodorSmall** [comment] 2024-08-11 22:57
Choosing a randomized instance is already implemented in case 1. no default instance is set and 2. no current instance is set. A "randomize instance" button in the settings would of course be better than selecting and deleting the current instance every time, though this is no solution, just making the workaround easier.
Also, at least with my configuration (proxy videos through invidious, don't fallback to non-preferred API, using Invidious), randomly hoping for instances that might work will usually result in repeating that process at least 5 times, with sometimes only 2 - 3 working instances, though you cannot really remember those because they're changing all the time.
Assuming there is one instance that works in the first place (meaning you can watch a video without waiting for it to load every 5 - 10 seconds), surely it would be a better approach to cycle through the list instead of randomly choosing an instance, so that the time needed is at least constant?
Combining that with refreshing the page is also an issue since that will cause the selected profile to switch to the default profile (not sure though if that's intentional), and I'm not sure if there's a "player only" refresh option internally available.
So much for the workaround in case there is at least one working instance at a time, however that's not always the case. 

Also, I'm not sure why instance admins wouldn't want us to implement some kind of "client side load balancing" (I hope I understood you correctly @Gorrrg and that's what you were referring to). The other feature (I know, that's two in one, but they're also pretty much linked together) I proposed was to use multiple instances at once, for the very same reason, to reduce the amount of traffic per instance or whatever the bottleneck might be. Isn't that exactly what they want: every client connects to the fastest instance(s), so that none is overrun (unnecessarily) with too much traffic to deal with? Or do you think there's some secret hope that all the other instances are used more often and the own bandwidth isn't at its absolute maximum all the time?
I really see no problem with that, but why not just ask them where possible?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-06 11:01
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1791 and https://github.com/FreeTubeApp/FreeTube/issues/3048

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-06 11:01 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: ease of use improvement
