### ISSUE TITLE
2 qualities visually selected when trying to switch video quality - quality does not change

### ISSUE THREAD

**Issue by snakyjake1** [FreeTubeApp/FreeTube#791] opened 2020-11-15 18:02 UTC
**Behavior of the program**
When changing the Player quality, the Player's video quality bar does two things:
1)  Multiple quality highlights are displayed.
2)  I'm not sure the quality I selected is actually what FreeTube is playing.
3)  Doesn't seem like I can change/upgrade the quality after selecting a different quality.
4)  Seems like the only quality I can now get is the lowest quality.

**Expected behavior**
I should get the quality I selected.  
I should be able to switch quality while playing video.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Change Player quality while playing video.
2. Change quality again while playing video.

**Screenshots**
![FT1](https://user-images.githubusercontent.com/8312560/99192723-4c00bc80-276c-11eb-8239-2fbc49fdb685.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: 7
 - FreeTube version: 0.9.2
 - Installation Method (If applicable): Portable
 - Primary API Used: Local API

**Comment by GilgusMaximus** [comment] 2020-11-16 15:57
Hi. So this was mentioned in the Matrix chat as well. It is very likely that VideoJS and the vhs plugin do things under the hood to keep the video running instead of having it buffer.

Reading up on this in the VideoJS doc and looking into possible flags in the VideoJS settings could be worth a shot here. However it will take some time until this can be fixed.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2020-12-08 15:26
Isnt this a duplicate of #595 ?

**Comment by GilgusMaximus** [comment] 2020-12-09 15:28
Partially yes. But partially not, because additionally here the UI is mentioned to not work properly. In #595 it is only about not being able to play properly. I might change the title a bit to make it more clear

**Comment by Svallinn** [comment] 2021-05-20 15:06
This particular bug should be fixed. Let us know otherwise.
**NOTE**: This bug is considered to be **separate** from #595

**Closed by Svallinn** 2021-05-20 15:06 UTC
Labels: bug
