### ISSUE TITLE
[Feature Request]: Hide/sort channel videos based on viewed or not

### ISSUE THREAD

**Issue by jojo2357** [FreeTubeApp/FreeTube#5500] opened 2024-07-30 05:15 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When viewing a channel page, I would like to see only videos that I have not seen. Another place I would like this is on the subscription feed.

### Proposed Solution

Add a local toggle to show/hide watched/unwatched videos,

### Alternatives Considered

Make a global setting; however this has the obvious drawback of being cumbersome to toggle off.

### Issue Labels

ease of use improvement, new feature

### Additional Information

Example of videos I would like to hide:

![image](https://github.com/user-attachments/assets/07260c8d-1cec-4b78-ad66-260a7cad30e1)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-30 21:42
> Another place I would like this is on the subscription feed.

Go to: Settings -> Subscription Settings -> Enable `Hide Videos on Watch`

> When viewing a channel page, I would like to see only videos that I have not seen.

duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4497

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-30 21:42 UTC
Labels: enhancement, E: ease of use improvement, E: new feature

**Comment by jojo2357** [comment] 2024-07-31 04:52
> Go to: Settings -> Subscription Settings -> Enable Hide Videos on Watch

This is a rather cumbersome solution, would prefer a simpler check similar to what was asked for in 4497. 

Sorry for partial duplicate, not sure how i missed it
