### ISSUE TITLE
[Feature Request]: Down button should scroll the screen down like on Youtube.com

### ISSUE THREAD

**Issue by Tiltowait2** [FreeTubeApp/FreeTube#2618] opened 2022-09-25 14:43 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

When I am on Youtube.com, I can scroll down the screen by using the down button.  This has become second nature, muscle memory.  It also adjusts the volume, but only if the player has focus.  Otherwise the screen scrolls down.  This is very useful when reading comments, as is often done.

### Proposed Solution

Make the down button able to scroll the screen down in the same way as Youtube.com.

### Alternatives Considered

None.

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-09-30 13:32
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1966

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-10-26 09:12
My apologies i incorrectly marked this as a duplicate

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-02-17 16:56
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/931

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-02-17 16:56 UTC
Labels: enhancement, good first issue, E: ease of use improvement
