### ISSUE TITLE
[Feature Request]: Automatically go fullscreen when opening videos

### ISSUE THREAD

**Issue by 0Raik** [FreeTubeApp/FreeTube#5849] opened 2024-10-09 22:56 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Using my phone to send **YouTube** links with **KDE Connect**/**GSConnect** and Junction to open **YouTube** links with **Freetube** but user has to use mouse to make the video playback go fullscreen. 
It would be the best open source alternative to 'Watch on TV' with the official YouTube TV app which is not available but in Google approved hardware.

This way the user could browse **YouTube**/**NewPipe** with their phones and share the link using **KDE Connect**. **Junction** opens any browser or in this case **Freetube** and opens the link but the extra steps using the mouse makes it not ideal for a media center. 

### Proposed Solution

Just a checkbox in **Freetube** to enable fullscreen playback.

### Alternatives Considered

The only alternative I see would be to use **Freetube** to launch yet another player that starts in fullscreen. Haven't tried as it would only be ideal in a pure media center and not a PC.

### Issue Labels

new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-10 08:52
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5427

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-10 08:52 UTC
Labels: enhancement, E: new optional setting, E: new feature
