### ISSUE TITLE
[Bug]: TLS Certificate for https://freetubeapp.io/ is expired

### ISSUE THREAD

**Issue by knrdl** [FreeTubeApp/FreeTube#2254] opened 2022-05-21 10:39 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

TLS Certificate for https://freetubeapp.io/ is expired

### Expected Behavior

TLS Certificate for https://freetubeapp.io/ is not expired

### Issue Labels

feature stopped working

### FreeTube Version

website

### Operating System Version

any

### Nightly Build

- [x] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-05-21 10:41
duplicate of https://github.com/FreeTubeApp/FreeTubeApp.io/issues/16

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-05-21 10:41 UTC
Labels: bug, B: feature stopped working
