### ISSUE TITLE
Add full HD to playback

### ISSUE THREAD

**Issue by tiotrom** [FreeTubeApp/FreeTube#219] opened 2019-02-12 00:05 UTC
Hi. Is there a reason why 1080p is not an option for video playback? Thanks for this great application!

**Comment by avion540** [comment] 2019-02-13 04:18
See #60

**Comment by tiotrom** [comment] 2019-02-13 04:35
Thanks

**Comment by PrestonN** [comment] 2019-02-19 15:31
As was mentioned, this is a duplicate of #60. I will go ahead and close this.

**Closed by PrestonN** 2019-02-19 15:31 UTC
