### ISSUE TITLE
[Bug]: Sometimes, when FreeTube is started, almost all the videos of one YouTuber is loaded first

### ISSUE THREAD

**Issue by Sandyran** [FreeTubeApp/FreeTube#3609] opened 2023-05-29 17:46 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads)
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug
1. Open FreeTube.
2. Show error.

![bilde](https://github.com/FreeTubeApp/FreeTube/assets/31732894/75fab80a-ca40-45a3-a801-38c034b5f48d)
![bilde](https://github.com/FreeTubeApp/FreeTube/assets/31732894/69775954-f7ff-41de-a79e-c02167633693)
![bilde](https://github.com/FreeTubeApp/FreeTube/assets/31732894/c57c6966-2618-40cf-b0d1-6aaf9fa7c7ff)
![bilde](https://github.com/FreeTubeApp/FreeTube/assets/31732894/3dd26c68-715d-4e0d-95a9-13bf78614712)
![bilde](https://github.com/FreeTubeApp/FreeTube/assets/31732894/719c6fc1-603d-495e-a0ad-355bee1fe240)
![bilde](https://github.com/FreeTubeApp/FreeTube/assets/31732894/9ce4dd9b-83d7-4e9c-88bf-924f360541fc)

### Expected Behavior
I was expecting FreeTube to show most of the recent videos, from the YouTubers I am subscribed to.

### Issue Labels

content not loading

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux Mint 21.1 Cinnamon

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.17.0 Beta

### Additional Information

This doesn't happen all the time, but it can happen every 3rd or 4th time I open FreeTube, so it can be fairly regular.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-05-29 19:49
duplicate of #3587

**Closed** 2023-05-29 19:49 UTC
Labels: bug, B: content not loading
