### ISSUE TITLE
[Bug]: search filter type: playlist or direct playlist url don't work

### ISSUE THREAD

**Issue by pravi** [FreeTubeApp/FreeTube#6265] opened 2024-12-03 10:21 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click on search icon on top bar
2. search for things - eg, hindi hits 2000
3. now click on filter -> type -> playlists

Or visit url www.youtube.com/playlist?list=PLs0evDzPiKwAyJDAbmMOg44iuNLPaI4nn (which shows play list on browser)

### Expected Behavior

it should show playlist only results (as works from browser - but newpipe also fails this filter).

or at least direct link to playlist should open.

This is useful when you want to play an already created / shared playlist.

### Issue Labels

API issue

### FreeTube Version

v0.22.0 beta

### Operating System Version

FuriOS (Debian GNU/Linux) testing/trixie) - default on Furiphone FLX1

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by pravi** [comment] 2024-12-03 10:35
On newpipe there is additional Youtube music search playlist option which works.

**Comment by pravi** [comment] 2024-12-03 11:14
On NewPipe 0.27.2 to 0.27.4 update, this seems fixed (playlist search not under Youtube Music also works).

**Comment by absidue** [comment] 2024-12-03 14:08
Duplicate of #6183

**Closed** 2024-12-03 14:08 UTC
Labels: bug, U: duplicate, B: API issue
