### ISSUE TITLE
[Bug]: FreeTube v 0.15.1 Beta Crash on Windows 7

### ISSUE THREAD

**Issue by VideoVoyeur** [FreeTubeApp/FreeTube#1999] opened 2022-01-10 01:34 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Go to FreeTube.exe and run program.
2. Click on any video available.
3. Video runs for 3-4 seconds before program crashes.
4. Window error message pops up. "FreeTube stopped working. A Problem cause the program to stop working correctly. Windows will close the program and notify you if a solution is available."
5. Sound continues to run an additional 2-3 seconds after the crash.

### Expected Behavior

The video is expected to run until completion.

### Issue Labels

causes crash

### FreeTube Version

v 0.15.1 Beta

### Operating System Version

Windows 7

### Installation Method (If applicable)

.zip

### Primary API used

Invidious API

### Additional Information

1. downloaded: freetube-0.15.1-win-64x-portable.zip
2. extracted and created a shortcut
3. shortcut installed onto Desktop.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-10 06:07
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1886

**Closed** 2022-01-10 06:07 UTC
Labels: bug, U: duplicate, B: crash
