### ISSUE TITLE
[Feature Request]: Hide individual videos from Subscription feed (NOT watched)

### ISSUE THREAD

**Issue by luke-bravenboer** [FreeTubeApp/FreeTube#5261] opened 2024-06-13 02:10 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Youtube's website has the ability to 'hide' individual videos from the subscriptions page, which helps me curate my feed (eg. I use it frequently for channels that produce multiple streams of content but I'm only interested in one of them, such as Critical Role).

I know there is an option to hide **watched** videos from the subs feed, but that's not suitable for my use case - I often watch very long videos that I stop and resume later, so I do not want things disappearing from the subs feed as soon as they're marked as 'watched'

### Proposed Solution

A 'hide video' button in the drop-down menu for videos on the subscriptions feed

### Alternatives Considered

- The setting to hide watched videos does not suit my needs - I would still like to be able to see videos that are partially watched
- Using the 'mark as watched' button to grey them out is a reasonable workaround, but a true hide button would just be a nice-to-have (and improve feature parity with Youtube)

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-13 09:15
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1362

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-06-13 09:15 UTC
Labels: enhancement, E: improvement existing feature
