### ISSUE TITLE
[Feature Request]: Change video order in a playlist

### ISSUE THREAD

**Issue by NewNiklas** [FreeTubeApp/FreeTube#5099] opened 2024-05-11 23:17 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I use the watch later playlist very often and usually organize my videos there according to length. However, this can be quite annoying if I add a video to a 100-video-long playlist that is added at the end of the playlist and I want to move it to the very beginning or to the middle, for example.

### Proposed Solution

To solve this problem, it would be good if I could simply hold down the video and move it to where I want it. In addition, an option in the context menu to move it to the first position in the playlist and to the last position in the playlist would be useful.

### Alternatives Considered

Alternatively, you could also add that you double-click on the number and enter a number and then press enter to move the video to the position you entered.

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-05-12 13:34
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4872

**Closed** 2024-05-12 13:35 UTC
Labels: U: duplicate, enhancement, E: ease of use improvement
