### ISSUE TITLE
Please allow more granular user definable playback speeds

### ISSUE THREAD

**Issue by MANICX100** [FreeTubeApp/FreeTube#996] opened 2021-01-30 10:46 UTC
At the moment you can select 0.25x - 3x as a playback speed. Using a extension in chrome such as 

https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?hl=en

you can go in increments of 0.1 to any speed. I sometimes use 4x or 0.8x for example.

**Describe the solution you'd like to see implemented**
Less hard limits on playback speed.

**Describe alternatives you've considered**
Using video speed controller

**Screenshots**
![Freetube](https://user-images.githubusercontent.com/5303241/106354257-42f1a700-62e8-11eb-8735-83eac9bacce5.png)
![Video speed controller](https://user-images.githubusercontent.com/5303241/106354264-5735a400-62e8-11eb-864e-eca90324994a.png)

**Comment by GilgusMaximus** [comment] 2021-03-18 11:46
Closing as this is a duplicate of #616

**Closed by GilgusMaximus** 2021-03-18 11:46 UTC
Labels: enhancement
