### ISSUE TITLE
Search Syntax Error

### ISSUE THREAD

**Issue by AmandaONeilll** [FreeTubeApp/FreeTube#807] opened 2020-11-25 07:40 UTC
**Behavior of the program**
Trying to search for any kind of thing/word/ect results in:
"SyntaxError: Unexpected end of JSON input" or end up empty

**Expected behavior**
show search results

**Screenshots**
![Screenshot from 2020-11-25 08-35-20](https://user-images.githubusercontent.com/65868299/100196645-73d4ea80-2ef9-11eb-9b80-3c914692fdd3.png)

**Environment Information (please complete the following information):**
 - OS: EndeavourOS
 - OS Version: rolling release but technically upwards from: 2020.09.20
 - FreeTube version: v0.9.2-nightly-311 Beta
 - Installation Method (If applicable): portable
 - Primary API Used: Local APi but more often than not falls back to invidious API

**Additional context**
i tried previous version as well this seems to be a consistent problem, perhaps some youtube update?

**Comment by andradei** [comment] 2020-11-25 18:48
For me the issue comes and goes. Same version.

OS: Windows 10

**Comment by arrowgent** [comment] 2020-11-25 20:57
https://invidious.site

its not a freetube issue, its the invidious api which is down

nothing can be searched.

**Comment by PrestonN** [comment] 2020-11-25 21:04
This is a duplicate of #662.

**Closed by PrestonN** 2020-11-25 21:04 UTC
Labels: bug

**Comment by carverh** [comment] 2020-11-25 21:10
Not a duplicate of #662, all invidious instances including mine lost the ability to search at the same time.

**Comment by PrestonN** [comment] 2020-11-25 21:33
Search not working for "either API" includes Invidious, hence this is a duplicate.

**Comment by arrowgent** [comment] 2020-11-25 21:43
irreguardless if its a duplicate, its not a freetube bug.

the 3rd party tool invidious is not working.  nothing freetube can fix aside from offering yet another api for search results.

**Comment by Prazgreen1** [comment] 2025-08-01 06:16
invidious works now but issue appears to persist.
