### ISSUE TITLE
[Bug]: TypeError: e.language.split is not a function

### ISSUE THREAD

**Issue by Insulinocytus** [FreeTubeApp/FreeTube#6388] opened 2024-12-16 02:25 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Upon setting Freetube's language to Chinese, I encounter a "TypeError: e.language.split is not a function" error while playing videos, resulting in the application becoming unresponsive.

### Expected Behavior

Nothing more.

### Issue Labels

causes crash

### FreeTube Version

v0.22.1 Beta

### Operating System Version

Windows 11 Pro 23H2

### Installation Method

Scoop (Unofficial)

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.3 Beta

### Additional Information

The error is highly reproducible. Every time I set Freetube's language to Chinese and play a video, the error almost always appears. (Though there have been rare instances where it worked.)

Here is the log.
```
renderer.js:2 TypeError: e.language.split is not a function
    at renderer.js:2:2113343
    at Array.sort (<anonymous>)
    at renderer.js:2:2113310
    at setup (renderer.js:2:2113728)
    at Vt (renderer.js:2:834447)
    at renderer.js:2:849717
    at nn (renderer.js:2:849927)
    at e._init (renderer.js:2:853630)
    at new r (renderer.js:2:858692)
    at renderer.js:2:841865
Ht @ renderer.js:2
jt @ renderer.js:2
$t @ renderer.js:2
Vt @ renderer.js:2
(anonymous) @ renderer.js:2
nn @ renderer.js:2
e._init @ renderer.js:2
r @ renderer.js:2
(anonymous) @ renderer.js:2
init @ renderer.js:2
(anonymous) @ renderer.js:2
h @ renderer.js:2
(anonymous) @ renderer.js:2
x @ renderer.js:2
(anonymous) @ renderer.js:2
x @ renderer.js:2
(anonymous) @ renderer.js:2
x @ renderer.js:2
(anonymous) @ renderer.js:2
e._update @ renderer.js:2
n @ renderer.js:2
e.get @ renderer.js:2
e.run @ renderer.js:2
Ei @ renderer.js:2
(anonymous) @ renderer.js:2
Kt @ renderer.js:2
Promise.then
zt @ renderer.js:2
Zt @ renderer.js:2
Ai @ renderer.js:2
e.update @ renderer.js:2
e.notify @ renderer.js:2
set @ renderer.js:2
en.set @ renderer.js:2
getVideoInformationLocal @ renderer.js:2
await in getVideoInformationLocal
onMountedDependOnLocalStateLoading @ renderer.js:2
mounted @ renderer.js:2
Vt @ renderer.js:2
vi @ renderer.js:2
insert @ renderer.js:2
Vt @ renderer.js:2
i @ renderer.js:2
T @ renderer.js:2
(anonymous) @ renderer.js:2
e._update @ renderer.js:2
n @ renderer.js:2
e.get @ renderer.js:2
e.run @ renderer.js:2
Ei @ renderer.js:2
(anonymous) @ renderer.js:2
Kt @ renderer.js:2
Promise.then
zt @ renderer.js:2
Zt @ renderer.js:2
Ai @ renderer.js:2
e.update @ renderer.js:2
e.$forceUpdate @ renderer.js:2
(anonymous) @ renderer.js:2
l @ renderer.js:2
Vt @ renderer.js:2
i @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
c @ renderer.js:2
(anonymous) @ renderer.js:2
setTimeout
Gs @ renderer.js:2
(anonymous) @ renderer.js:2
requestAnimationFrame
(anonymous) @ renderer.js:2
requestAnimationFrame
js @ renderer.js:2
k @ renderer.js:2
Qs @ renderer.js:2
remove @ renderer.js:2
k @ renderer.js:2
_ @ renderer.js:2
(anonymous) @ renderer.js:2
e._update @ renderer.js:2
n @ renderer.js:2
e.get @ renderer.js:2
e.run @ renderer.js:2
Ei @ renderer.js:2
(anonymous) @ renderer.js:2
Kt @ renderer.js:2
Promise.then
zt @ renderer.js:2
Zt @ renderer.js:2
Ai @ renderer.js:2
e.update @ renderer.js:2
e.notify @ renderer.js:2
set @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
$l.updateRoute @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
n @ renderer.js:2
n @ renderer.js:2
Nl @ renderer.js:2
(anonymous) @ renderer.js:2
n @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
g @ renderer.js:2
n @ renderer.js:2
n @ renderer.js:2
n @ renderer.js:2
Nl @ renderer.js:2
$l.confirmTransition @ renderer.js:2
$l.transitionTo @ renderer.js:2
t.push @ renderer.js:2
(anonymous) @ renderer.js:2
Jl.push @ renderer.js:2
$Q.push @ renderer.js:2
y @ renderer.js:2
Vt @ renderer.js:2
i @ renderer.js:2
a._wrapper @ renderer.js:2
```

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-12-16 07:47
Duplicate of #5969

**Closed** 2024-12-16 07:47 UTC
Labels: bug, B: crash, B: Unofficial Download
