### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by mastercoldcoder** [FreeTubeApp/FreeTube#680] opened 2020-10-17 12:04 UTC
I don't use the invidious api, just the local api because invidious is dead, or is close to becoming so. The problem is the following:
When I click on search to make a search and when I validate, the following error message is displayed and I have nothing in the results.
The following error message appears :
SyntaxError: Unexpected token < in JSON at position 0

**Comment by PrestonN** [comment] 2020-10-17 14:05
Duplicate of #662

You can enable fallback to use Invidious only for search while we wait for a fix. It should still be working.

**Closed by PrestonN** 2020-10-17 14:05 UTC
Labels: bug
