### ISSUE TITLE
The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

### ISSUE THREAD

**Issue by i300220** [FreeTubeApp/FreeTube#885] opened 2020-12-19 01:30 UTC
Hi,

I get this error almost daily on different videos: The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

Happened twice today.  Usually happens soon after I skip some time in the video with the right arrow.

<a href="https://ibb.co/bW6Ks4k"><img src="https://i.ibb.co/bW6Ks4k/Clipboard01.jpg" alt="Clipboard01" border="0"></a>

It happened with version 0.9.3 and happens again with version 0.10.  The videos work perfectly fine in any browser I use.

OS is Win 7 sp1 64

**Comment by PrestonN** [comment] 2020-12-19 02:24
Please don't clear out the template. I can't properly help you when it isn't filled out.

I need information such as which videos are causing the errors? Which API are you using? What happens if you swap to the opposite API? If you're using the local API, can Invidious get the video? Have you tried using legacy formats? Legacy formats can be enabled while on a video page or can be changed to be the default in settings.

Another reason this could happen is if you've been away for a while and you try to come back and continue watching a video. YouTube links are only valid for a certain amount of time and can become invalid if you've been on the page for too long.

Does any error (outside of the one your seeing) show up in the console? You can open up the console by using `Ctrl + Shift + I` on your keyboard.

This error can be a very large variety of issues and it's difficult to pin down the exact reason it's causing this problem.

**Comment by GilgusMaximus** [comment] 2020-12-19 11:54
I want to chip in as well and add that watching in resolutions larger than 1080p leads to this problem more frequently than normal (although I did not experience it for some while now).

**Comment by i300220** [comment] 2020-12-19 11:57
Oh! My mistake.  I thought I read to clear the template before submitting.  Kind of things that happens after a day reading stuff in a second language.

Here's one video that caused problem: file:///E:/Program%20Files/Freetube/resources/app.asar/dist/index.html#/watch/hi9lxIE2Kfw
Sorry if it's local, that is what the 'copy link' gives.  Quite unexpected.

I use local API, with fallback enabled.  In version 0.9.2 it usually gave a cryptic error message each time I loaded a video even though the video eventually played after fallback to the other API so I indeed tried to switch to the other API but it was giving more errors messages so I've reset everything back to default and never touched those settings since.  Now using V 0.10 with default settings.

I do not have any idea what legacy format could be.  All I know is that in my browsers, I have an extension to disable VP8, VP9, AV1 and 60fps youtube videos.  If I could achieve same results with Freetube, I'd be very happy.

Can't get Ctrl-Shift-I to work.  Radeon software takes a screenshot when I press it.  F12 expected here.  And F5 to reload the video would be very appreciated when if crashes because otherwise I have to return on the internet to get the youtube link again.

If I can help more please let me know.  Ant thanks for this wonderful program.  If I could never have to go to youtube.com again that would be awesome.

While I'm here I have a feature request.  Right click on a video link in Freetube to open a new Freetube instance to play the video.  The reason is when I press the back button in Freetube, I get back to the listings of videos and if mine was in the 6th page, I have to press "search more results" 5 times to get back where I was and select another video.

I set resolution to 720p max. (Added this line after reading GilgusMaximus comment, thanks GilgusMaximus!)

**Comment by Leza89** [comment] 2020-12-20 10:14
I'd like to chip in as well, getting the same error after playing certain videos for <2 min

System: Windows 7 x64 SP1 Build 7601 

Video1 :  https://youtu.be/D5xX6nRWDko
Video2 : https://youtu.be/XRVA5PMSKKE

* Local API or Invidious API doesn't make a difference
* Force Local Backend for Legacy Formats doesn't make a difference

Pressing "Change Video Formats" within the video player window and choosing "USE LEGACY FORMATS" resolves the issue

**Comment by GilgusMaximus** [comment] 2020-12-30 10:41
@Leza89 here the problem sometimes is that we do not get any information from yt-dl-core because YouTube usually provides an already compiled DASH file, which our module is unable to download for some reason. So the Legacy format is the only option for these videos at the moment

**Comment by i300220** [comment] 2021-01-22 00:08
Hi,

Just to confirm that using legacy format seems to solve this issue.  It never happened again in one month.

**Comment by twisteros** [comment] 2022-04-18 10:06
I experience that issue as well. I've got a couple of videos I watch on daily basis and they usually work fine. However if I leave a running FreeTune instance,  put my laptop into sleep and then wake it up the video gets the error message. I've got "DASH Formats" set as default.

![image](https://user-images.githubusercontent.com/18228956/163792991-ff209d11-804e-4d86-9b93-79d24e62afc0.png)

**Comment by Leza89** [comment] 2022-04-26 11:02
I do still get this error (non-reproducably, sadly) sometimes as well; It is so rare though that I wouldn't give it priority.

**Comment by absidue** [comment] 2022-04-27 07:06
As you have said that changing to legacy formats works and the DASH formats don't, I am assuming that Windows 7 is too old to support the modern DASH formats. If that is indeed the case then the "fix" would have to be to prevent you from selecting the DASH formats on legacy operating systems like Windows 7.

**Comment by Leza89** [comment] 2022-04-28 09:19
> I am assuming that Windows 7 is too old to support the modern DASH formats.

In that case there should be playback issues with youtube videos regardless, but this problem does not occur within a regular browser.
Plus I have also noticed it on Ubuntu 20.04, albeit less frequent.

**Comment by absidue** [comment] 2022-04-28 09:34
I suspect that YouTube in your browser is clever enough to only show formats that can be played on your machine. Keep in mind that YouTube doesn't let you choose between legacy and DASH formats so you are less likely to notice when it's using legacy formats. I don't have access to a machine running Windows 7 so I can't confirm my suspicions.

**Comment by Leza89** [comment] 2022-04-28 11:36
I'm not sure how I'd check for the format within youtube, but this video:
https://www.youtube.com/watch?v=XNTNS8hlWZ8
for example works as intended with all options from 144s over 720s and 1440s up to 2160s

I'd also figure that if there was a problem with the format, it should be consistent, not sporadic.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-02-05 22:00
Hi @i300220, @twisteros and @Leza89 

Can you try a nightly build and check if u can still reproduce the bug? 
https://docs.freetubeapp.io/development/nightly-builds

**Comment by Leza89** [comment] 2023-02-05 22:34
> Can you try a nightly build and check if u can still reproduce the bug? https://docs.freetubeapp.io/development/nightly-builds

The issue has become so rare that it will be hard to reproduce.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-02-06 07:35
How rare is rare? Like once a week/month/3months? When was the last time u saw it

**Comment by Leza89** [comment] 2023-02-06 12:43
> How rare is rare? Like once a week/month/3months? When was the last time u saw it

Honestly, I can't remember.. between once a month and once a quarter, maybe..
When I get it, it doesn't play the video to begin with though.. I'll look out for it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-01-02 18:15
Going to close this issue as it seems to be a very rare issue. I also got this error but it was because of user error

1. I was playing a video
2. Switched user account
3. Switched back to the user account that was playing a vid in FT
4. Got the error

Looks like that was expected because switching the user account suspends activity in the account

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-01-02 18:15 UTC
Labels: bug
