### ISSUE TITLE
Setting to Enable Ads

### ISSUE THREAD

**Issue by TheShadowOfHassen** [FreeTubeApp/FreeTube#5002] opened 2024-04-23 01:29 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I like using FreeTube. I like being able to have all my favorite creators all in one place, and the YouTube algorithm can't try to make me watch something else. However, I feel horrible skipping ads that the creators rely on for revenue.

### Proposed Solution

Can we please have a setting that just loads the ads?

### Alternatives Considered

I could just open the links with my browser, but that's a lot more clunky than just using one client.

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-23 07:15
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/319

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-23 07:15 UTC
Labels: enhancement, E: new optional setting
