### ISSUE TITLE
[Feature Request]: Add a "custom color" option for theme colors

### ISSUE THREAD

**Issue by trzyglow** [FreeTubeApp/FreeTube#5715] opened 2024-09-17 21:17 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The theme color settings only have preset colors, limited to color scheme sets which get proposed in the repo.

### Proposed Solution

Adding a "custom color" option (like in the profile settings) for the theme colors [base, main & secondary] would add a lot of freedom in the field of customization to the user.

### Alternatives Considered

An optional "custom color" hex-value field.

### Issue Labels

improvement to existing feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-17 21:30
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3145

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-17 21:30 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting
