### ISSUE TITLE
[Feature Request]: keep relative timestamps ("Minutes ago") in Subscriptions up-to-date

### ISSUE THREAD

**Issue by aleksejrs** [FreeTubeApp/FreeTube#3736] opened 2023-07-08 10:59 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The Subscriptions page shows relative times like "3 minutes ago", and those times are not updated when I leave the page/profile and come back, so I don't know if the videos are still recent, or if I need to refresh.

### Proposed Solution

Show the times relative to now, not to when the page was last updated.

### Alternatives Considered

Show absolute times.
Show the last refresh time.

### Issue Labels

ease of use improvement, improvement to existing feature

### Additional Information

v0.18.0-nightly-3087 Beta

**Comment by absidue** [comment] 2023-07-08 11:08
YouTube only gives us the relative timestamps (unless you enable the setting to use the RSS feeds, but then you loose out on video durations and live status information), so can only display the information we get from them, just translated to the display language you have chosen in FreeTube.
To keep them accurate we would either need to refresh the subscriptions every time you visit the page, which is not only wasteful but would also likely get you ratelimited by YouTube, or do some inaccurate calculations (why inaccurate? because `5 hours ago` could be anywhere between exactly 5 hours ago or 5 hours 59 minutes and 59 seconds ago, so instead of displaying an outdated timestamp, we would end up displaying misinformation if we did calculations).

**Comment by aleksejrs** [comment] 2023-07-08 11:11
Then show the last refresh time (or whatever related is available)?

**Comment by absidue** [comment] 2023-07-08 11:13
already requested in: https://github.com/FreeTubeApp/FreeTube/issues/1010

As that makes this a duplicate of the issue linked above, I'll close this as a duplicate unless you have anything else?

**Comment by absidue** [comment] 2023-07-08 11:19
duplicate of #1010

**Closed by absidue** 2023-07-08 11:19 UTC
Labels: enhancement

**Comment by absidue** [comment] 2024-03-10 13:58
Reopened this, as I ended up implementing it in the linked pull request. The next time this issue is closed, it will be because that pull request got merged :).
