### ISSUE TITLE
feature request: customizable key bindings

### ISSUE THREAD

**Issue by ExpandingMan** [FreeTubeApp/FreeTube#797] opened 2020-11-17 02:43 UTC
It would be really great to have customizable key bindings, particularly if the enough could be made available so that keyboard-only could be used if so desired.  Anyway, thanks for all the hard work!

**Comment by PrestonN** [comment] 2020-11-17 03:23
Duplicate of #251

**Closed by PrestonN** 2020-11-17 03:23 UTC
Labels: enhancement
