### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by libertesedamatrix** [FreeTubeApp/FreeTube#457] opened 2020-02-27 10:26 UTC
Man, you can add the possibility to [create/manage tabs] to organize channels list, like this:

adventure tab:
channel1
channel2
channel3
channel4

Tech tab:
channel1
channel2
channel3
channel4

**Comment by PrestonN** [comment] 2020-02-29 19:07
If you're asking for the ability to organize your subscriptions, you can check out the profile functionality by clicking on the bubble in the top right corner of the app.

If you're asking about traditional "browser" tabs, then this is a duplicate of #333

**Closed by PrestonN** 2020-02-29 19:07 UTC
