### ISSUE TITLE
TypeError: Cannot read property 'continuationContents' of undefined

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#1493] opened 2021-07-02 18:26 UTC
**Behavior of the program**
Tried to show the comments, but§ instead, i have this error
`TypeError: Cannot read property 'continuationContents' of undefined`

**Expected behavior**
Comments showing

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any video
2. Click on 'see comments'

**Environment Information (please complete the following information):**
 - OS: debian stable
 - FreeTube version: v0.13.2 Bêta
 - Installation Method (If applicable): deb
 - Primary API Used: local, fallback to iv API if it fails

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-02 19:50
Duplicate of #1490

**Comment by Svallinn** [comment] 2021-07-03 19:16
Duplicate of #1490

**Closed by Svallinn** 2021-07-03 19:16 UTC
Labels: bug
