### ISSUE TITLE
[Feature Request]: Make Arabic letters bigger.

### ISSUE THREAD

**Issue by Growebis** [FreeTubeApp/FreeTube#3181] opened 2023-02-11 01:34 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The current problem with Arabic text in FreeTube is that in the description and up next, the Arabic text is small to read, with the only exception being the title.
![image](https://user-images.githubusercontent.com/113867283/218229349-5ced6bf7-6b55-454f-a848-8789ce83fb4e.png)

Whats worse is that the comments are almost unreadable unless i get close to the screen.
![image](https://user-images.githubusercontent.com/113867283/218229396-4f9b7103-9b18-481f-9180-dc1f60f8caea.png)

### Proposed Solution

Make the Arabic text larger and more readable.

### Alternatives Considered

An alternative would be to add an option somewhere in Theme Settings to change the font size specifically for Arabic letters.

### Issue Labels

new optional setting, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-02-11 11:39
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2489

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-02-11 11:39 UTC
Labels: enhancement, E: new optional setting, E: visual improvement
