### ISSUE TITLE
[Bug]: language of audio is different than what expected [Multiple language audio tracks?]

### ISSUE THREAD

**Issue by zh54tg234f** [FreeTubeApp/FreeTube#2866] opened 2022-11-14 18:03 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

0. use a foreign vpn / prefered api is local for me (with fallback enabled) 
-> i dont know if its important so i mention it 
1. Watch the linked below MrBeast Video or any similar channel with translated audio (as it seems) 
https://youtu.be/kX3nB4PpJko
2.1 with freetube for the 2 latest videos i get an audio track in a different language than English
1.2 open the link over an invidious instance: https://invidious.weblibre.org/watch?v=kX3nB4PpJko

2, realize the video on invidious is English as expected and over freetube its some other language

for this video ( his 3th latest) : https://youtu.be/gHzuabZUd6c
this issue does not happen, its on english over freetube
but this second latest video: https://youtu.be/iogcY_4xGjo
is on hindi english or what ever => so i guess its some experimental youtube feature
that freetube is falling for 

### Expected Behavior

give me default audio track like invidious is doing it (english)

### Issue Labels

accessibility issue, content not loading, inconsistent behavior, usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux

### Installation Method

AUR

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.17

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-11-14 18:33
Just to clarify, what do u mean with a foreign VPN? A VPN company that is not from the US or connect to a non US country?

**Comment by zh54tg234f** [comment] 2022-11-15 13:15
mainly it can't be caused by the vpn, i checked my vpn location is swiss and i got something hindu (i guess)

**Comment by ChunkyProgrammer** [comment] 2022-11-16 04:24
just gonna leave this here as a potential option: https://www.npmjs.com/package/videojs-plugin-audio-switch

**Comment by Smurflicious** [comment] 2022-11-19 23:20
I have this bug as well. Embarrassingly I only see this problem with MrBeast videos. The audio is in Russian or something.

I expect this is only happening with videos where the creator goes to the effort of creating multiple languages/audio tracks when uploading etc. And FreeTube is taking the first one it gets returned maybe? Which would explain why it is working for most videos, they only have one audio track available.

**Comment by zh54tg234f** [comment] 2022-11-20 20:08
> Only started after I updated to v0.18.0 Beta.

since its just for the 2 latest videos, i think its something experimental / new from youtube 
and freetube will be buggy for previous versions as well. (another reason to orientate more on the invidious project

invidious: https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_1439,w_2560,x_0,y_0/dpr_1.5/c_limit,w_1044/fl_lossy,q_auto/v1492121692/articles/2015/11/11/south-park-tackles-police-brutality-presents-a-world-without-racist-trigger-happy-cops/151111-wilstein-south-park-tease_vcuijq

freetube: https://static.fjcdn.com/gifs/Meanwhile+in+canada+found+this+and+it+made+me+think_76041f_4958185.gif

**Comment by Smurflicious** [comment] 2022-11-20 20:22
> i think its something experimental / new from youtube

Good points, I agree.

**Comment by absidue** [comment] 2022-11-23 12:54
Duplicate of #2419

**Closed by absidue** 2022-11-23 12:54 UTC
Labels: bug, B: content not loading, B: accessibility, B: usability, B: inconsistent behavior, B: Unofficial Download

**Comment by ssnor** [comment] 2023-02-05 16:19
I didn't see it mentioned, so for anyone with this issue a workaround is to switch to legacy formats for the video.

I got this issue on this video: https://youtu.be/BGD-oSwJv3E
Got Spanish language with a Swedish IP.
I'm on openSUSE Rawhide and FreeTube v0.18.0-nightly-2591.
