### ISSUE TITLE
See only subscribed channels not belonging to any profile

### ISSUE THREAD

**Issue by m3thm4th** [FreeTubeApp/FreeTube#5018] opened 2024-04-25 19:05 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Some channels are subscribed with the "All channels" generic profile, thus not belonging to any specific profile. There should be a way to only show these channel to be able to sort them by adding them to specific profiles.

### Proposed Solution

.

### Alternatives Considered

.

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-25 20:10
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/914

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-25 20:10 UTC
Labels: enhancement, E: new optional setting
