### ISSUE TITLE
[Bug]: No search results when filter-searching for playlists

### ISSUE THREAD

**Issue by BloodRaven0** [FreeTubeApp/FreeTube#6204] opened 2024-11-21 09:33 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Click on the search filters button next to the search bar
2. Click "Type" > "Playlists", then Close.
3. Search for anything
4. "There are no results for this search"

### Expected Behavior

Playlist results should be displayed.

### Issue Labels

API issue, feature stopped working, usability issue

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Windows 10 21H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-11-21 10:15
Duplicate of #6183

**Closed** 2024-11-21 10:15 UTC
Labels: bug, B: usability, B: feature stopped working, B: API issue
