### ISSUE TITLE
[Feature Request]: Change Home Page

### ISSUE THREAD

**Issue by ActualBest** [FreeTubeApp/FreeTube#2377] opened 2022-07-04 02:08 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

When I open the app, I don't want to see my subscriptions, I want to see my Favorites.

### Proposed Solution

A dropdown in settings where you can select which page the app opens to

### Alternatives Considered

None that I can think of

### Issue Labels

ease of use improvement, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-29 10:01
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/183

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-08-29 10:01 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement
