### ISSUE TITLE
[Feature Request]: Volume management

### ISSUE THREAD

**Issue by 4164696f73** [FreeTubeApp/FreeTube#4059] opened 2023-09-19 13:40 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Make it more advanced etc. Improvements similar to what [Enhancer for Youtube](https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle) offers.

### Proposed Solution

1. Option to reset volume to default after switching to another video.
2. Separate volume adjustment for mouse and arrow keys. For example, I want to set "up arrow" to increase volume by 5%, but mouse wheel (scroll) to increase it by 1% (same for decreasing volume).
3. Temporarily remember the volume settings of last video (not permanently, closing Freetube would forget that).

### Alternatives Considered

---

### Issue Labels

improvement to existing feature, new feature, new optional setting

### Additional Information

Legends say I only remembered like half or less of what I wanted to suggest...

**Comment by absidue** [comment] 2023-09-19 16:12
Number 3 is how FreeTube behaves today, the volume is remembered across videos in the same window.

**Comment by toby63** [comment] 2023-10-06 22:07
@4164696f73 For always using Option 1 I wrote the following patch:

```
--- ft-video-player.js	2023-05-01 21:31:18.502416525 +0200
+++ new/ft-video-player.js	2023-05-08 23:11:29.156292693 +0200
@@ -753,7 +753,8 @@
         sessionStorage.setItem('muted', muted)
       } else {
         // If volume isn't muted by dragging the slider, muted and volume values are carried over to next video.
-        const volume = this.player.volume()
+        // const volume = this.player.volume()
+        const volume = parseFloat(sessionStorage.getItem('defaultVolume'))
         const muted = this.player.muted()
         sessionStorage.setItem('volume', volume)
         sessionStorage.setItem('muted', muted)
```

**Comment by Wehrmachtserdbeere** [comment] 2023-10-23 12:23
> Number 3 is how FreeTube behaves today, the volume is remembered across videos in the same window.

It doesn't. Every time I have to reload the app (which is very often), it resets the volume to full.

**Comment by absidue** [comment] 2023-10-23 12:28
Not sure why you are surprised about something resetting when you reload, that clears all temporary data including the saved volume. We have never recommended reloading FreeTube, why exactly are you doing it?
I have never in two years of using and working on FreeTube had to reload.

**Comment by Wehrmachtserdbeere** [comment] 2023-10-23 12:38
Because every time I lose connection, the client grinds the currently playing video to a halt. So it's just easier to press "CTRL + R" than to copy the title, put it into the search bar, and going back to the same video, or to click on share, copy the URL, then paste that into the search bar. 3 User Interactions vs 1 User Interaction.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-10-23 12:44
This discussion belongs in https://github.com/FreeTubeApp/FreeTube/issues/2295

Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2295

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-10-23 12:44 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: new feature
