### ISSUE TITLE
[Bug]: Local API no longer working since two days

### ISSUE THREAD

**Issue by BarbzYHOOL** [FreeTubeApp/FreeTube#3773] opened 2023-07-13 22:07 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Any video, even in 480p keeps loading every 2 seconds, it's unwatchable. Happening since two days ago

so i went to settings and changed Local Api to Invidious and now it works but it's still a bug and invidious has many issues too (seeems like no utf-8 on video comments for example)

### Expected Behavior

No stuttering

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

v0.18

### Operating System Version

Linux Mint 20

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.18

### Additional Information

PS: when is the new release going to happen??????????

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by VorpalQ** [comment] 2023-07-13 22:20
I am also having this issue, no matter the bitrate of the video it constantly stutters.

Flatpak Freetube, Fedora 38.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-07-14 07:59
This is already fixed, use a nightly build of u want the fix.

Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/3457

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-07-14 07:59 UTC
Labels: bug

**Comment by BarbzYHOOL** [comment] 2023-07-14 20:34
how do i run the nightly build, i don't want to compile stuff and spend time in the terminal

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-07-14 21:13
See https://docs.freetubeapp.io/development/nightly-builds

**Comment by BarbzYHOOL** [comment] 2023-07-15 22:28
ok interesting
