### ISSUE TITLE
[Bug]: Comments will not load

### ISSUE THREAD

**Issue by antglove** [FreeTubeApp/FreeTube#5236] opened 2024-06-07 13:12 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Go to any video and select a random comment with replies, now click on "Show More Replies" and it will not load more comments

### Expected Behavior

Load more Comments

### Issue Labels

visual bug

### FreeTube Version

v0.20.0 Beta

### Operating System Version

Windows 11

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-07 13:18
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4928

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-06-07 13:18 UTC
Labels: bug, B: visual

**Comment by antglove** [comment] 2024-06-07 13:20
sorry i searched but i have not found it before. thanks for the reply!
