### ISSUE TITLE
[Bug]: Hide shorts

### ISSUE THREAD

**Issue by eshsdhsd** [FreeTubeApp/FreeTube#3976] opened 2023-08-30 08:32 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

There is No option to hide shorts. 

### Expected Behavior

I expected a option to hide shorts especially I waited 1 year for this GODDAMN UPDATE.

### Issue Labels

accessibility issue, usability issue

### FreeTube Version

v0.19.0 Beta

### Operating System Version

windows

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

I waited a year for this only not to come,also I have No way to contact the freetube staff.
Matrix server seems to be down.
Preston dosent respond by emails anymore.
I really cant reach anyone and this is the only way I could somehow
I made a request about year ago only just closed instantly

This looks very unprofessional and bad. I want to enjoy freetube but there is just 1 issue and it can be fixed easily and quickly otherwise I would recommend free tube and love it with joy

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2023-08-30 08:47
Hi

Firstly being rude helps no one, we are volunteers working on FreeTube in our free time.

Secondly you used the incorrect issue template, this is a feature request, yet you picked the bug report template.
Thirdly no way to contact the team is incorrect, considering both this GitHub repository and the FreeTube General Matrix room have not only been available the entire time but also active.

As for the actual feature request in this issue, there are options to hide the shorts tabs on the subscriptions and channel pages, for other places in FreeTube, YouTube doesn't give us any information to say what is a short and what isn't, so we can't hide them from other places at the moment.

**Comment by eshsdhsd** [comment] 2023-09-02 10:11
Im sorry for a bit of rudeness.  I wanted only a general option to block shorts like how you could block live streams or at least in the search bar as it's flooded with it. I though it was a thing being worked on so I took it as a bug.

Sorry for that

**Comment by absidue** [comment] 2023-09-03 11:24
The only place we don't currently hide shorts but have enough information to do so (at least with the local API), are playlists that contain only shorts, as YouTube uses a different layout for those. But if we hid them there, you would just be looking at an empty playlist, which seems a bit pointless.

As for other locations we unfortunately don't have enough information from YouTube to conclusively say that something is a short. The old method that people were suggesting of checking for the #shorts hashtag, would miss loads of shorts, as lots of creators no longer include that hashtag in their shorts. Checking the duration of the video and filtering out anything shorter than 60 seconds would be too aggressive, as there are lots of videos that aren't shorts, that are less than a minute long.

Unless YouTube starts clearly labelling shorts everywhere, we can't filter out shorts from anywhere else than we currently provide options for.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-09-06 15:43
tbh there are many issues regarding this and just creating another for it doesnt make us work faster on it

basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1070

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-09-06 15:43 UTC
Labels: bug, U: Waiting for Response from Author, B: accessibility, B: usability

**Comment by asagdotzler** [comment] 2024-10-23 08:53
I wonder if it wouldn't be enough to make the radio button in the filter list into a checkbox so that I could check all but the shortest duration and in so doing escape shorts with some false positives I could live with. Alternatively, let me save filters on searches so I can quickly search for something with each of the individual radio buttons for the not-"less than 4 minutes" time durations you already provide but make difficult to utilize.

**Comment by asagdotzler** [comment] 2024-10-23 09:37
then perhaps some aggregation/collation so you make it pretty for me but behind the scenes you do multiple api calls for the not-less-than-4-minutes options and then sort and display them to me as a single list.
