### ISSUE TITLE
Freetube app 0.15.1 Windows 8.1 crashes after opening any video[Bug]: 

### ISSUE THREAD

**Issue by deeznutser** [FreeTubeApp/FreeTube#2018] opened 2022-01-22 13:59 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

When I open the app(latest version 0.15.1) and going to a some video - a window "program crashed" appears". I tried  to use 0.15.0 version and didn't have any problems

### Expected Behavior

I expected to watch a video without crashes

### Issue Labels

feature stopped working

### FreeTube Version

0.15.1

### Operating System Version

Windows 8.1 Professional

### Installation Method (If applicable)

.exe

### Last Known Working FreeTube Version (If Any)

0.15.0

### Primary API used

Local API

### Additional Information

With Invidious API a crash exists too

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-22 15:01
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1886

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-01-22 15:01 UTC
Labels: bug, B: feature stopped working
