### ISSUE TITLE
[Feature Request]: Add Ability to Blur Thumbnails or completely remove them as a toggelable checkbox

### ISSUE THREAD

**Issue by fislysandi** [FreeTubeApp/FreeTube#3657] opened 2023-06-12 09:38 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

hi i would like to have this feature implemented in free tube Distraction Free Settings.

this feature would save people a lot of time not getting click baited into watching garbage content because of a good thumbnail,

also another feature completely Hide Them Would be nice if it was implemented.

### Proposed Solution

if it was to be implemented,
- it would look like this:
![FreeTube_AnxWqlNCkI](https://github.com/FreeTubeApp/FreeTube/assets/45166203/ad20787b-6d35-4011-8787-0b63006fd4c0)

and for the Thumbnailless View, 
- it would look Something Like This.:
![FreeTube Thumbnailless Preview](https://github.com/FreeTubeApp/FreeTube/assets/45166203/e3fff126-3569-43d6-9e1c-1174c61407db)

### Alternatives Considered

i already told what it would look like.
i don't think any alternatives would be necessary since you are just blurring the thumbnails or removing them thats it.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-06-12 09:42
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2814

Please list your suggestions over there.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-06-12 09:42 UTC
Labels: enhancement, E: new feature
