### ISSUE TITLE
[Bug]: scrolling problem

### ISSUE THREAD

**Issue by linuxgirl22** [FreeTubeApp/FreeTube#2436] opened 2022-08-01 06:37 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Thank you for this new release. :-) Noticeably running a lot faster! 
Have an issue with scrolling; scrolls but stops at video title ... when continue, only right column moves, and clicking on 'comments' isn't possible until reach the bottom of the right column. When click on 'comments', comments open at the bottom, and need to scroll up to start reading. 
Just opened console, and the scrolling issue isn't there while console is open. A video width error shows; I have the text zoomed up, to help with comments size, so videos are larger too, showing 2 per line. (Have channel names showing text beside, too.) 

 

### Expected Behavior

Had been using one of the nightlies, I think from about 3-4 weeks ago, and no issue at all with scrolling as expected, by placing mouse anywhere, and can get directly to comments. 

### Issue Labels

feature stopped working

### FreeTube Version

17.0

### Operating System Version

MX Linux 21, 5.10.0-13-amd64 

### Installation Method

.AppImage

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

FreeTube-0.16.0-nightly-1645.AppImage

### Additional Information

Dragging screenshot in isn't working, but the error part about width:

Uncaught TypeError: Cannot read properties of null (reading 'videoWidth'
at o.checkAspectRatio 
... includes various refs to renderer.js:2

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by linuxgirl22** [comment] 2022-10-08 07:20
Hi :-) Wondering what to do about this bot thing marking thread as stale and pending closed; not keen to keep commenting to keep an active bug thread alive, if that's what the dumb thing is saying ... yes, not keen on all these bots etc, lol, and also prefer not to be on github. I've done a comment on this occasion, but all I can add regarding feedback is that still on Freetube 0.16.0 as scrolling is great in that but not working in 0.17.0. 
If another bot reminder to comment or close comes up, will just stick with Freetube 0.16.0 and thanks that it's possible to use that.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-10-08 07:54
Dont worry ill remove the label when the issue is valid no need to comment. If i dont and its the 6th day or something like that feel free to comment

**Comment by linuxgirl22** [comment] 2022-10-08 17:01
Thanks @efb4f5ff-1298-471a-8973-3d47447115dc. Can see 'stale' label removed, but can also see bug removed from 'To assign' ... no plans to fix broken accessibility features? or it's going into another queue? Really don't like the bot stuff etc, but didn't expect bug report possibly closed when said that, lol. Did report for anyone else needing to use larger text setting also, so fingers crossed it's not being closed, or closed because new features block it being fixed.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-10-08 17:23
> Thanks @efb4f5ff-1298-471a-8973-3d47447115dc. Can see 'stale' label removed, but can also see bug removed from 'To assign' ... no plans to fix broken accessibility features? 

This is definitly a bug of the workflow. I have created a bug report on their repo.

> Really don't like the bot stuff etc, but didn't expect bug report possibly closed when said that, lol. Did report for anyone else needing to use larger text setting also, so fingers crossed it's not being closed, or closed because new features block it being fixed.

I can assure u that nothing will be closed or blocked automatically by bots. I understand why u dont like the automation stuff but it is necessary for us now that we keep growing. With the stale workflow we can evaluate if an bug report/feature request is really valid when its going stale. This will help us to get a healthy backlog and not get a enormous backlog like some other repos have.

**Comment by linuxgirl22** [comment] 2022-10-09 00:43
Thanks for assurances regarding bugs not being auto-closed/blocked; appreciate it.  

The 'stale' auto-labelling unfortunately caused more work and confusion, in auto-threatening removal, forcing posting on github, and also in removing the bug from the project board ... and I'd thought it was a human, Preston, had done that removal, which wasn't great. It should be clear whether a human or a bot is doing something. 

Am more put off from reporting even a show-stopping bug now, due to automation, but you've been very responsive and helpful about it, which I really appreciate. In closing, thanks for reporting to 'stale', and hopefully the scrolling bug can be re-added and work out okay.

**Comment by linuxgirl22** [comment] 2022-10-10 13:28
Just got an email update from #2704 ... thanks for continued efforts about fixing issues; much appreciate.

**Comment by absidue** [comment] 2022-10-10 13:41
> It should be clear whether a human or a bot is doing something.

Unfortunately due to GitHub limitations some actions have to be done by actual user accounts, as the default github bot account doesn't have enough permissions, so they need to be automated with an actual user account as well.

https://github.com/alex-page/github-project-automation-plus#personal-access-token
> You will need a personal access token to send events from your issues and pull requests.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-11-03 21:43
@linuxgirl22 is it maybe possible for u to make a screen recording of the old and the new behavior?

**Comment by linuxgirl22** [comment] 2022-11-04 09:21
Hi and thanks for message. I've done two little recordings, one of 0.16 (working) and one of 0.18 (scrolling issue). 

https://user-images.githubusercontent.com/35760727/199937406-e1e6aec5-079d-4091-b877-4cde0bbdf2a9.mp4

Having a problem getting the second video down from 11.5 mb to under 10, but back soon.

**Comment by ramsaimanjunadh** [comment] 2022-11-04 11:28
Hi can i check the details by the given  links.

**Comment by linuxgirl22** [comment] 2022-11-04 12:47
Hi, sorry but I'm not sure what you're asking ... I was able to get the video downsized; using a locked down browser that doesn't play the videos, but downloading one of them (the one in your attached text) resulted in it playing fine.

**Comment by linuxgirl22** [comment] 2022-12-03 10:28
Hello, I've got the email yet again saying "This issue is stale because it has been open 28 days with no activity. Remove stale label or comment or this will be closed in 7 days."

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-09 15:10
> Hi, sorry but I'm not sure what you're asking ... I was able to get the video downsized; using a locked down browser that doesn't play the videos, and was showing them as 'corrupt', but downloading one of them to check (the one in your attached text) resulted in it playing fine. Both should be okay and viewable in less locked down browsers or through download.

Hi @linuxgirl22 sorry that there hasnt been allot of traction on this. I wanted to look at the screen recordings again but it shows as corrupt. Is there a way for you to re-upload them

**Comment by linuxgirl22** [comment] 2024-12-09 16:52
Hello and thank you very much for your message. 2.3-year-old thread ... shows should never give up hope, lol. On checking just now, the comments scroll really well. Also just found the 'hide recommended videos' option, so catching the videos instead of text when scrolling is solved too! Thanks for Freetube and how well it works.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-09 17:15
Great to hear. I will close this one. Dont hesitate to comment if something breaks :)

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-09 17:15 UTC
Labels: bug, B: feature stopped working

**Comment by linuxgirl22** [comment] 2024-12-09 21:52
Much appreciate. Thanks :-)
