### ISSUE TITLE
[Bug]: Default quality=auto, but 1080p always appears

### ISSUE THREAD

**Issue by Tiltowait2** [FreeTubeApp/FreeTube#2059] opened 2022-02-08 10:01 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Go to Player Settings -> Default Quality
2. Set to "auto".  
3. Open the player to any video.
4. The "select quality" box in the player simply shows "1080p" no matter what quality is playing. There is an "auto" setting in there but it never appears. The "1080p" is there even if the video does not support playback at 1080p.

### Expected Behavior

The Youtube.com player will always tell you what quality you are at if you click the gear icon. It will say "Auto 480p" or whatever.  

### Issue Labels

usability issue

### FreeTube Version

v0.16.0 Beta

### Operating System Version

Windows 8.1

### Installation Method (If applicable)

.exe

### Last Known Working FreeTube Version (If Any)

v0.16.0 Beta

### Primary API used

Local API

### Additional Information

I have a dodgy connection and I'm not able to keep up 720p like most users.  I'm happy with 480p if I can get it.  So my connection constantly shifts the quality but I'm not sure what I'm getting. 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-02-08 22:32
At this moment in time there is not logic behind the Auto Quality.

I'll mark this as a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/595

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-02-08 22:32 UTC
Labels: bug, B: usability
