### ISSUE TITLE
[Bug]: Search is not working

### ISSUE THREAD

**Issue by exefile2** [FreeTubeApp/FreeTube#6219] opened 2024-11-23 15:40 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Searching something on freetube showing nothing.

1. go to freetube
2. search something
3. search data not available 

### Expected Behavior

videos should load 

### Issue Labels

content not loading

### FreeTube Version

0.22.0 beta

### Operating System Version

windows 10 pro

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

![image](https://github.com/user-attachments/assets/f14c9bc4-3aca-4e18-ab41-629c7ba888e3)
![image](https://github.com/user-attachments/assets/21311d72-2dcd-4d0a-ac39-034ec2997a83)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by artkapl** [comment] 2024-12-05 19:33
For me this issue only happens when I search for playlists (Search filter > Type > Playlists). I use v0.22.0 beta.

Newpipe also had this problem and fixed it in https://github.com/TeamNewPipe/NewPipeExtractor/pull/1240. Maybe this helps?

**Comment by trobertson** [comment] 2024-12-18 08:29
I'm on 0.22.1, and I have the same experience at @artkapl. My search works fine for videos but there are never any playlist results, even when specifically searching for playlists.

**Comment by nemya9066** [comment] 2024-12-20 13:59
I also encountered this issue some search keyword show nothing on freetube but work fine in youtube.

**Comment by lflo5727** [comment] 2024-12-23 22:13
On v0.22.1 Beta on Linux and seeing this issue specifically with searching for playlists. Been an issue for awhile for me.

**Comment by lflo5727** [comment] 2024-12-23 23:15
Well, nevermind. I cloned the repo and built and its already fixed on the `development` branch, so I assume it's just not in any releases yet.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-24 21:46
hi please try the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds) and check if this is still an issue for you.

**Comment by nemya9066** [comment] 2024-12-25 12:41
> Well, nevermind. I cloned the repo and built and its already fixed on the `development` branch, so I assume it's just not in any releases yet.

can confirm that the issue is fixed in the latest nighlty build

**Comment by lflo5727** [comment] 2024-12-25 15:41
@efb4f5ff-1298-471a-8973-3d47447115dc  @nemya9066 
Yes, the bug is fixed in the latest nightly build.

**Closed** 2024-12-25 16:07 UTC
Labels: bug, U: Waiting for Response from Author, B: content not loading
