### ISSUE TITLE
[Feature Request]: Sort playlist by duration

### ISSUE THREAD

**Issue by adiosocelote** [FreeTubeApp/FreeTube#5336] opened 2024-06-24 22:06 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently, you can sort only by a-Z, Z-a, channel name etc. Would be nice to also have by duration, so longest-to-shortest, shortest-to-longest, maybe even expand that to "by duration and channel name" etc.

### Proposed Solution

Add sorting by video duration, first video: 17:31, second video: 18:12, third video 33:59 and so on, or backwards, 1st 33:59, 2nd 18:12, 3rd 17:31.

### Alternatives Considered

The only alternative is to sort them by hand. At least that is the only thing that comes to my mind.

### Issue Labels

improvement to existing feature

### Additional Information

I just like having some playlists start from shortest to longest, because then I can know if I can watch the next one or not before I leave. Also, I find it more convenient than having a-Z or by channel name sorting - to me those make no sense (though that is just subjective). Wouldn't hate it if it never happened, but would really appreciate having it.

**Comment by kommunarr** [comment] 2024-06-24 22:21
Duplicate of #5268

**Closed by kommunarr** 2024-06-24 22:21 UTC
Labels: enhancement, E: improvement existing feature
