### ISSUE TITLE
[Bug]: A channel with errors list is appearing every time I refresh my RSS subscriptions feed.

### ISSUE THREAD

**Issue by vF360** [FreeTubeApp/FreeTube#4615] opened 2024-01-29 15:30 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

The title says it all. Here is what it looks like: https://i.imgur.com/FD7Fpbv.png

### Expected Behavior

I expect videos from every subscribed channel to appear on my feed; when I open a channel from the error list, I am still able to see the latest videos.

### Issue Labels

content not loading

### FreeTube Version

v0.19.1 Beta

### Operating System Version

Windows 10 LTSC 1809

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by JamarleyHub** [comment] 2024-01-29 15:35
Same here. I don't get the channels showing up in my sub-feed, instead it tells me that about half of my subscribed channels have supposed errors with them. I am able to access their channel pages just fine though. I don't know if it's invidious acting up or if that is FreeTube that actually messes this up.
I'll be happy to provide logs if requested.

**Comment by vF360** [comment] 2024-01-29 15:43
> Same here. I don't get the channels showing up in my sub-feed, instead it tells me that about half of my subscribed channels have supposed errors with them. I am able to access their channel pages just fine though. I don't know if it's invidious acting up or if that is FreeTube that actually messes this up. I'll be happy to provide logs if requested.

I'm pretty sure it is an invidious problem, but you could double-check by making a web account with them to see if the same thing occurs after you subbed to a load of random channels.

**Comment by JamarleyHub** [comment] 2024-01-29 16:04
Weird addition: I noticed the number of channels that error is currently... growing??? I now get channels that error which previously didn't.

**Comment by freeklucas** [comment] 2024-01-29 16:04
Same here, I solved it by disabling "Fetch Feeds from RSS" as a temporary workaround.

**Comment by BobbyMcJefferson** [comment] 2024-01-29 16:05
Same problem here. As of today, I no longer see my subscriptions feed. Just a long list of channels with errors.

**Comment by xyhbhtt** [comment] 2024-01-29 16:05
Odd update: I've had the same problem just growing until all my channels had errors. Some are, however coming back without errors?

**Comment by JamarleyHub** [comment] 2024-01-29 16:08
I assume this is related to #4614 then?

**Comment by autogris** [comment] 2024-01-29 16:32
As of today I'm also experiencing a blank list of videos with just the list of subscriptions bellow. I didn't add any new subscription for a long time, and they are bellow 100 in number. I also have always used with the setting "Fetch Subscription RSS" disabled. Tried with the latest nightly build, error still occurring. Both Local API and Invidious API have the same results.

**Comment by senolfndk** [comment] 2024-01-29 16:42
😒
https://github.com/FreeTubeApp/FreeTube/assets/52818836/fb258676-d7be-48e4-8380-82fe07a38670

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-01-29 16:43
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4614

Check https://github.com/FreeTubeApp/FreeTube/issues/4614#issuecomment-1914871618 for workaround

**Comment by senolfndk** [comment] 2024-01-29 16:43
https://github.com/FreeTubeApp/FreeTube/assets/52818836/0ce97189-db5e-4bf0-ac55-fead0e403714

😒

**Comment by xyhbhtt** [comment] 2024-01-29 16:43
> Odd update: I've had the same problem just growing until all my channels had errors. Some are, however, coming back without errors?

And my subscription list on 100% error again

**Closed** 2024-01-29 16:43 UTC
Labels: bug, B: content not loading

**Comment by senolfndk** [comment] 2024-01-29 16:53
> > Tuhaf güncellemesi: Aynı sorundaki tüm kesintilerde oluşan hatalara kadar devam ettirildi. Ancak bazı hatalar geri döner mi?
> 
> Ve bunların listesi yine %100 hata veriyor
same problem 😒

**Comment by vF360** [comment] 2024-01-29 16:56
> Duplicate of #4614
> 
> Check [#4614 (comment)](https://github.com/FreeTubeApp/FreeTube/issues/4614#issuecomment-1914871618) for workaround

I don't want to reduce my channel list, though. It makes more sense to split up my subscriptions within multiple FreeTube instances, but then I would need a way to remove duplicate videos in my playlist; is something like that possible to achieve?
