### ISSUE TITLE
[Feature Request]: Smaller Play/Pause button

### ISSUE THREAD

**Issue by konomikitten** [FreeTubeApp/FreeTube#6030] opened 2024-10-30 01:16 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The new player for FreeTube is amazing and works much better than the old one however I feel like one aspect has been a bit of a downgrade. The button for play/pause is now much larger than it used to be and actually obscures the video quite a bit when moving the mouse around.

![FreeTube New Video Player Large Controls](https://github.com/user-attachments/assets/4a451331-8e22-4f6a-8729-cfedbc2eff5d)

### Proposed Solution

Change the size of the play/pause button to be smaller and more in line with the older size.

### Alternatives Considered

An alternative to shrinking the size of the button would be to have an option disabling it.

### Issue Labels

visual improvement

**Comment by ChunkyProgrammer** [comment] 2024-10-30 01:20
You can disable disable `Display Play Button In Video Player` under `Player Settings`.

It will be disabled by default in the next release (it will also likely be more transparent and be smaller if you do enable the big play button)

This is also a duplicate of #5951

**Closed by ChunkyProgrammer** 2024-10-30 01:20 UTC
Labels: enhancement, E: visual improvement

**Comment by konomikitten** [comment] 2024-10-30 01:22
> This is also a duplicate of #5951

Thanks, sorry for the noise I did search for a similar issue but didn't happen to find that one.
