### ISSUE TITLE
[Feature Request]: Piped support

### ISSUE THREAD

**Issue by MichealGun777** [FreeTubeApp/FreeTube#2757] opened 2022-10-22 00:39 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Well i have been wanting to watch videos with piped but sadly theres no client for desktop, i was wondering if you could add piped support to FreeTube to make it better i guess.

### Proposed Solution

Not sure.

### Alternatives Considered

no?

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-10-22 05:03
Duplicate of #2615

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-10-22 05:03 UTC
Labels: enhancement, E: new feature
