### ISSUE TITLE
[Bug]: 4320P Content begins to stutter and drop frames in playback 

### ISSUE THREAD

**Issue by GreasedSparrow** [FreeTubeApp/FreeTube#5436] opened 2024-07-21 08:46 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Loading a high-quality video in 4320p, [such as this one](https://youtu.be/GnFpKtDkgdA), playback in both Local-API and Invidious begins smoothly without issue but after a short-period of playback it begins to stop playback for a couple to several seconds at a time before resuming, and then repeating without fixing itself. This is true for both SDR and HDR.

### Expected Behavior

The video plays smoothly in accordance with sufficient bandwidth and hardware, similar to playback on YouTube in a Chromium browser.

### Issue Labels

content not loading, feature stopped working

### FreeTube Version

0.21.0

### Operating System Version

Windows 10 LTSC 1909

### Installation Method

.exe

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

N/A

### Additional Information

Stats for nerds show that first-hitch results in one dropped frame, and the second as twenty or so (from cursory observation). This process repeats.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-21 09:08
duplicate of https://github.com/FreeTubeApp/FreeTube/discussions/5166

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-21 09:08 UTC
Labels: bug, B: content not loading, B: feature stopped working
