### ISSUE TITLE
[Bug]: Unresponsive upon internet disconnection

### ISSUE THREAD

**Issue by the-rocinante** [FreeTubeApp/FreeTube#6111] opened 2024-11-06 19:17 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Watch a video.
Disconnect internet before playback is finished.
Reconnect internet.
Watch endless loading image.
Click anything ... nothing happens.
Close app.
Open app.
Click History.
Click the video to resume playback.
It starts at the beginning of the video instead of the time index where it left off.

### Expected Behavior

The expected behaviour is that it should either detect that the internet has been restored and resume playback at the same time index, or as with previous versions allow to resume playback from the same time index by navigating back and forward, or by going to History and clicking the video to resume.

### Issue Labels

causes crash, content not loading, data loss, inconsistent behavior, usability issue

### FreeTube Version

v0.22.0_amd64

### Operating System Version

Linux Mint 21.3

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.3_amd64

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-11-06 19:53
Duplicate of #6028

**Closed** 2024-11-06 19:53 UTC
Labels: bug, B: content not loading, B: usability, B: crash, B: inconsistent behavior, B: data loss
