### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON (when wanting to use a working Invidious instance)

### ISSUE THREAD

**Issue by linlinxza** [FreeTubeApp/FreeTube#5720] opened 2024-09-20 01:05 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Add any Invidious instance.
2. Try playing a video

### Expected Behavior

Should just play video.

### Issue Labels

API issue, feature stopped working

### FreeTube Version

v0.21.3 Beta

### Operating System Version

KDE Neon (Ubuntu 22.04)

### Installation Method

Flathub

### Primary API used

Invidious API

### Additional Information

Presents this error:

SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-09-22 14:01
Duplicate of #5534

IV instances are down because YT changed something again

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-09-22 14:01 UTC
Labels: bug, B: feature stopped working, B: API issue

**Comment by linlinxza** [comment] 2024-09-22 18:28
> Duplicate of #5534
> 
> IV instances are down because YT changed something again
> 
> Use the Local API

Thankfully, with all the nonsense Google is doing, I really don't care all that much for YouTube. Thank goodness there is Odysee and Peertube.
