### ISSUE TITLE
Feature request: Auto Load Comments

### ISSUE THREAD

**Issue by bbsixzz** [FreeTubeApp/FreeTube#1517] opened 2021-07-13 14:52 UTC
Hello,

would you please consider adding a setting to auto load comments so one doesn't have to click "Click to View Comments" on each video? Would it also be possible to load all comments at once instead of having to click "Load More Comments" similar to https://github.com/mattwright324/youtube-comment-suite?

YouTube makes loading and searching all comments a chore; loading and searching all comments would make for a very powerful learning tool when watching long technical videos with thousands of comments.

Cheers

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-07-13 17:42
Please do not write multiple issues into one issue. Otherwise your issues will be closed if they contain > 1 not already open issues / discussions.

Also use the template, its there for a reason. If u do this its highly possible ur issue gets closed.

The search feature u mentioned is a duplicate of #1401

So the only thing that is relevant here is to auto load the comments.

**Comment by GilgusMaximus** [comment] 2021-07-23 16:44
We will not be able to load all comments. This may instant rate-limit you on videos with a lot of comments.
Auto loading comments was already thought about, but we did not add it yet

**Closed** 2022-10-16 17:01 UTC
Labels: enhancement, U: doesn't follow template
