### ISSUE TITLE
[Feature Request]: Playlist of channel

### ISSUE THREAD

**Issue by UltraBlackLinux** [FreeTubeApp/FreeTube#2454] opened 2022-08-05 11:44 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I'm into music (Like many other people), and I like to have a playlist of music which I can then shuffle and loop. If a channel doesn't have a playlist, it's basically impossible to just leave their music running.

### Proposed Solution

Add a button that opens a playlist containing all videos of a channel

### Alternatives Considered

none really. Everything else is just a chore.

### Issue Labels

ease of use improvement, new feature

### Additional Information

[This](https://www.reddit.com/r/LifeProTips/comments/247c2u/lpt_youtube_how_to_play_all_videos_from_a_channel/) was once possible, but when I tried it just now, it doesn't seem to work anymore, or I just pasted it wrong, idk

EDIT: Oh! Comments are useful! Adding `?view=57` to the videos tab url brings back this feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-10 22:05
basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/629

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-08-10 22:05 UTC
Labels: enhancement, E: ease of use improvement, E: new feature
