### ISSUE TITLE
[UI] minimized subscription list fails to load until "minimize" button pressed

### ISSUE THREAD

**Issue by arrowgent** [FreeTubeApp/FreeTube#1883] opened 2021-11-10 16:13 UTC
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- yes
- Make sure you are on the latest release of FreeTube before submitting an issue.
- yes 0.15.0

**Behavior of the program**
Please write a clear and concise description of what the bug is.
closing then opening freetube
the subscriber avatars on the left do not load
clicking "minimize" to expand then again to minimize restores the avatars and loaded information

**Expected behavior**
Please describe clear and concise what you expected to happen.
as before with 0.13.0 & 0.14.0 minimized subscriber list should load when first opening freetube

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to '...' close freetube & open it again
2. Click on '....' click top left 3 bars

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.
red box to highlight area with issue -- the subscribers
![img](https://i.imgur.com/cr60bIO.png)
red box to click the "minimize" button to expand
![img](https://i.imgur.com/AAFETxi.png)
red box to show minimized subscriber avatars are fixed
![img](https://i.imgur.com/DRwt7eO.png)

**Environment Information (please complete the following information):**
 - OS: [e.g. Windows, Mac, Ubuntu, Fedora, Arch, etc.]
linux Ubuntu 18.04 LTS
 - OS Version: [e.g. Windows 10, Ubuntu 20.04]
 - FreeTube version: [e.g. 0.9.0, Nightly build?]
0.15.0 beta
 - Installation Method (If applicable): [e.g. Portable, .exe, .deb, .AppImage, FlatHub]
.deb
 - Primary API Used: [Local API, Invidious API]
Invidious API,  same issue occurs on Local API

**Additional context**
autoloading minimized subscriber avatars worked in previous versions without issue
if this is *by design* that is ok,  possibly lowers loading overhead, but adds 2 clicks to a usable UI

does not appear to be a theme issue,  same occurs in other themes.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-02-09 19:13
Duplicate of #1642

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-02-09 19:13 UTC
Labels: bug
