### ISSUE TITLE
[Feature Request]: Context menu entries should also be translatable

### ISSUE THREAD

**Issue by MarkusGaugg** [FreeTubeApp/FreeTube#6333] opened 2024-12-09 20:09 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently, the context menu entries can't be translated into another language.

![Ashampoo_Snap_Montag, 9  Dezember 2024_21h6m30s](https://github.com/user-attachments/assets/f7cc97e9-f855-478a-a2ce-e83016fe6c06)

### Proposed Solution

To keep a consistent look and feel, the context menu entries should be made translatable too.

### Alternatives Considered

None

### Issue Labels

improvement to existing feature, visual improvement

**Comment by absidue** [comment] 2024-12-09 21:02
Duplicate of #5254

Yes, I am aware that that one says main menu and this one says context menu, but they are handled by the same mechanisms, so they have the same challenges (outside of the translation system that the rest of the app uses) and will have to be dealt with in the same way.

**Closed** 2024-12-09 21:02 UTC
Labels: enhancement, E: improvement existing feature, E: visual improvement
