### ISSUE TITLE
Context Menu (More Options) Customization

### ISSUE THREAD

**Issue by hl2guide** [FreeTubeApp/FreeTube#1920] opened 2021-11-26 15:45 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Please allow for the customization of the Context Menu (More Options) on the Subscriptions page.

**Describe the solution you'd like to see implemented**
Settings for toggling (boolean) for the showing of specific items so that it can be cleaner.

Also the option to show the context menu when right-clicking the thumbnail image.

**Describe alternatives you've considered**
N/A

**Comment by GLLM** [comment] 2021-11-26 17:06
Very good idea, the list is way too long for my use :)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-06-12 10:09
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1920

please put your suggestions over there.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-06-12 10:09 UTC
Labels: enhancement
