### ISSUE TITLE
[Feature Request]: Command-line Option for '--new-window' or '-n'

### ISSUE THREAD

**Issue by ChristianSilvermoon** [FreeTubeApp/FreeTube#6237] opened 2024-11-27 19:24 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

FreeTube is a app. It's such a app that on my system, I have it set to open *all* youtube links. My default browser is a personally written Shell Script that catches and passes certain URLs to certain programs, such as YouTube links in FreeTube.

But I'd really prefer if it doesn't open the new link in the same window, taking me away from wherever I was at the time, as sometimes I like to have multiple videos up in different windows as a sort of queue for what I intend to watch that viewing session after browsing subscriptions.

### Proposed Solution

Add a `--new-window`/`-n` option to FreeTube so that it may be invoked with

```bash
freetube --new-window "$URL"
```

in order to achieve the desired outcome, opening the passed URL in additional window rather than an existing one.

This would greatly enable me to enjoy FreeTube even more than I already do.

### Alternatives Considered

- Change the default behaviour to open a new window every time.
- - However, this may not be desirable for all users.
- Add a setting in the UI to open external links in a new window instead of an existing one.

### Issue Labels

ease of use improvement, new feature, new optional setting

### Additional Information

Visual Mockup of a possible CLI help message
![image](https://github.com/user-attachments/assets/cb74a80a-d708-4527-a1b9-579f915688a7)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-06 22:11
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4446

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-12-06 22:11 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement, E: new feature
