### ISSUE TITLE
[Feature Request]: Start playing in full window mode by default

### ISSUE THREAD

**Issue by Venomtek** [FreeTubeApp/FreeTube#5407] opened 2024-07-14 19:40 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There is no settings toggle for full window mode to be default watching mode instead of having to toggle it on every time.

### Proposed Solution

Have a settings toggle for full window mode to be default watching mode instead of having to toggle it on every time.

### Alternatives Considered

None.

### Issue Labels

ease of use improvement, improvement to existing feature, new optional setting, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-18 12:25
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1047

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-18 12:25 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: visual improvement, E: ease of use improvement
