### ISSUE TITLE
Dont expand filter window when going to another page

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1341] opened 2021-05-25 22:28 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
If u click on the filter icon, the filter window comes down. If the filter window is down and u click on lets say on the settings page, the filter window will still be expanded. In my opinion this behavior is annoying.

**Describe the solution you'd like to see implemented**
Don't keep the expanded the filter window when u navigate to another page. 
If #1337 is already implemented and u want to work on this, u need to fix the described logic in this issue for the solution in #1337. 

**Describe alternatives you've considered**
None.

**Screenshots**
None.

**Additional context**
None.

**Comment by GilgusMaximus** [comment] 2021-05-26 16:19
Closing as it basically is a duplicate of the discussion of #1337

**Closed by GilgusMaximus** 2021-05-26 16:19 UTC
Labels: enhancement

**Comment by GilgusMaximus** [comment] 2021-05-27 17:32
Yes and no. It is not a real duplicate like saying twice 'Do this and that'. This issue tho really depends on what we settle in #1337. So there is currently no need to have someone fix this if we change it completely anyways. I would add this as important to look at if we stay the current way. But not with the ongoing discussion.
