### ISSUE TITLE
"Watch Later" feature

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#358] opened 2019-08-21 19:00 UTC
There was the #221 issue in which a user asked about the "Watch Later"  feature. I open a new issue because of a better title and because the problem #221 was solved anyway, and I think it should be closed, and the discussion about the "Watch Later" topic should be moved here.

> I would consider "Favorites" and "Watch later" as the same thing. Is there a good enough reason as to why these should be 2 separate options?

`favorites` are the vids which you watched already, and for some reason you want to keep them (for future reference or to watch them again in the future). `watch later` are the vids you think they are interesting enough to be watched. Of course you can keep them as well after you watch them, but from my experience, less than 5% of the not yet seen vids can make it to the favorites. So mixing the two lists of videos isn't really a good thing.

**Comment by PrestonN** [comment] 2019-08-23 17:32
This is a duplicate of #248

**Closed by PrestonN** 2019-08-23 17:32 UTC
