### ISSUE TITLE
Local API Error when loading any kind of video

### ISSUE THREAD

**Issue by bernd972** [FreeTubeApp/FreeTube#748] opened 2020-10-30 21:07 UTC
Freetube works normal so far. but when I go to a video's site, the loading animation is shown and also immediately 
an "Local API error:TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined"
is displayed. sometimes the error message is another one which I cant reproduce right now.

aside from that , in only lie 20% of the cases is the video ever getting loaded.
in like 80% of the cases, the above mentioned error message is displayed and the loading animation jsut stays there, the video and the page never getting actually loaded.
at least after like 20 seconds of staring at that animation, I'm annoyed and dont wait any longer, going elsewhere.

so yeah, most videos simply dnt ever load and always have this, or a similar, error message.

doesnt matter from when or where you go to a videos page, above mentioned behavior happens with literally every video.

it's like a 1 in 20 miracle if you click on a video lin and the video, still with error message as usual, loads almost instant.

but for the msot part, it's the never-loading scenario from above.

Which is really annoying if freetube has subscriptions and all but you almost cant watch a single video on it cause they never get loaded :-(

**Comment by PrestonN** [comment] 2020-10-30 21:09
Duplicate of #733

**Closed by PrestonN** 2020-10-30 21:09 UTC
Labels: bug
