### ISSUE TITLE
[Feature Request]: can you provide the ability to store all profiles separately, so we can choose and load a specific profile at start

### ISSUE THREAD

**Issue by sevakmaheshr** [FreeTubeApp/FreeTube#3586] opened 2023-05-25 08:23 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

i currently have more than 500 subscriptions in my freetube app. there seem to be multiple problems in this case:
1. at startup, the app shows an error message saying (something like this) "falling back to rss because of too many subscriptions" (i understand that the limit is 125 subscriptions
2. the "all" profile is always there and there is NO way to delete it, afaik
3. i have already created multiple profiles (e.g., tech, travel, food, auto, news, documentaries, etc), each with anywhere upto a max of 50-60 subcriptions, mostly in the 15-20 per profile
4. with these many subscriptions, the app takes a long time to load

### Proposed Solution

my proposed solution is to have a screen similar to what chrome has when you configure multiple profiles in chrome.

when you have multiple profiles in chrome, chrome gives you a screen on which you can choose a particular profile.

i am suggesting that freetube have a similar interface. here's how i see the whole scheme working:
- i start freetube
- i get to see the "choose your profile" page
- let's say i choose "tech"
- freetube should now load only the videos from my tech profile's subscription
- hopefully there will be less than 125 channels in a profile, ensuring that the app would load up faster, and not have to show any error messages about falling back to rss
- NOTE: there should be NO "all" profile in the app

### Alternatives Considered

none! any suggestions are welcome.

### Issue Labels

ease of use improvement, improvement to existing feature, new feature, new optional setting, visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-05-25 15:16
This is basically a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1996 with an added screen to choose what profile u want to be in. Like a login screen to choose one of the users u want. The all channels profile wont be removed because some users dont use profiles at all and like everything on one place.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-05-25 15:16 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: visual improvement, E: ease of use improvement, E: new feature
