### ISSUE TITLE
Implement Sponsorblock

### ISSUE THREAD

**Issue by Hx2-code** [FreeTubeApp/FreeTube#1078] opened 2021-03-02 14:48 UTC
**Additional context**
Implement [Sponsorblock](https://chrome.google.com/webstore/detail/sponsorblock-for-youtube/mnjggcdmjocbbbhaepdhchncahnbgone?hl=en) in freetube. It will save a lot of time while watching videos.

**Comment by PrestonN** [comment] 2021-03-02 14:56
Duplicate of #798

**Closed by PrestonN** 2021-03-02 14:56 UTC
Labels: enhancement
