### ISSUE TITLE
Enhancement to freetube static content and video delivery from youtube

### ISSUE THREAD

**Issue by temporallyaccount** [FreeTubeApp/FreeTube#531] opened 2020-09-14 18:06 UTC
From https://github.com/FreeTubeApp/FreeTube-Vue/issues/51

>Even after proxied through invidious then i see connectivity for below domains. Isn't it possible to prevent use these domains and relay on invidious?
`youtube-ui.l.google.com`, `i.ytimg.com`, `photos-ugc.l.googleusercontent.com`

>Another thing when i go to invidious website and watch videos through web browsers then i only see connectivity below domains.
`invidio.us`, `r3.sn-random-jhcl.googlevideo.com`, `r3.sn-random.googlevideo.com`, `redirector.gvt1.com`

> @PrestonN  This is something I wanted to look more into at the time, however with the future of Invidious being uncertain, I will be holding off on looking more into this.
You're welcome to create a new issue in the main repo about this when we are passed the initial release as I won't be focusing on this any time soon.

Youtube videos deliver through `googlevideo.com` then only the higher bandwidth domain that required direct access but if possible to combine with free cdn service better. Lol.

**Comment by peepopoggers** [comment] 2021-09-16 22:15
Important issue.
Duplicate of mine #1625 because this got buried

**Comment by JacksonBarker** [comment] 2022-10-09 20:48
I am unsure why this issue was marked as low priority, as far as I can tell based on my incredibly limited understanding of YouTube's CDN structure, ytimg.com and googleusercontent.com are for thumbnails? I have to assume that these thumbnails are fetched from the subscription feed because I'd imagine that the recommendations are delivered by Invidious.

For a player that pitches itself as "built with privacy in mind" leaking your subscriptions to Google seems to entirely negate the privacy benefits that come from using feeds opposed to just signing in with a Google account. But, if I've entirely missed the mark on this issue please let me know, as my knowledge is fairly limited in this field.

**Comment by ChunkyProgrammer** [comment] 2023-01-24 22:44
YouTube thumbnails should be replaced with invidious thumbnails and there's a setting to proxy videos through invidious so I believe this can be closed

**Closed by ChunkyProgrammer** 2023-01-24 22:44 UTC
Labels: Rewrite: featurerequest
