### ISSUE TITLE
Choose home page

### ISSUE THREAD

**Issue by patxikuku** [FreeTubeApp/FreeTube#1138] opened 2021-03-24 06:39 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
When FreeTube starts, the home page is always the page Subscriptions. I would like to be able to set Playlists as the home page.

**Describe the solution you'd like to see implemented**
A solution could be to be able to choose the home page in the settings : one among the pages in the menu of the left column for example.

**Comment by GilgusMaximus** [comment] 2021-03-24 11:43
Closing because this is a duplicate of #183

**Closed by GilgusMaximus** 2021-03-24 11:43 UTC
Labels: enhancement
