### ISSUE TITLE
[Feature Request]: setting to remember playback rate between videos

### ISSUE THREAD

**Issue by ikizey** [FreeTubeApp/FreeTube#6448] opened 2024-12-24 09:41 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

My preferred playback rate is 3.0. But sometimes I want to listen to a playlist of music. And I prefer to listen to the music with playback rate of 1.0. But on every new song in a playlist, playback rate will be reset to 3.0. Current solution is to go to settings, change default playback rate to 1, go to playlist, listen, then don't forget to get back to settings and change rate back to 3.0. 

### Proposed Solution

Add a setting that will remember playback rate, when I change it on a video.

### Alternatives Considered

The alternative is to make this behavior by default.

### Issue Labels

ease of use improvement

### Additional Information

Idea is from "Video Speed controller" plugin for Chrome/Firefox

**Comment by absidue** [comment] 2024-12-24 10:04
Duplicate of #2295

**Closed** 2024-12-24 10:04 UTC
Labels: enhancement, E: ease of use improvement
