### ISSUE TITLE
[Feature Request]: How do I turn off 50p/60p?

### ISSUE THREAD

**Issue by artenax** [FreeTubeApp/FreeTube#5750] opened 2024-09-26 19:30 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

720p50 and 720p60 are slow for me. How can I switch to 720p25 or 720p30?
I know these streams exist, but are not offered by default. In the browser, the enhanced-h264ify extension can bring them back, for example.

**Comment by absidue** [comment] 2024-09-26 19:47
Please read this thread: https://github.com/FreeTubeApp/FreeTube/discussions/5713

Closing as a duplicate of https://github.com/FreeTubeApp/FreeTube/discussions/5713

**Closed** 2024-09-26 19:47 UTC
Labels: enhancement, E: new optional setting

**Comment by artenax** [comment] 2024-09-27 01:29
Well, I'll have to pass the link to the mpv player with parameters:
```
~/.config/mpv/mpv.conf
volume=75
ytdl-format=bestvideo[height<=720]+bestaudio[acodec=opus]/best
vo=gpu
```
mpv plays much better. Although, it's not as comfortable.

By the way, I'm using Xubuntu 22.04. I tried the newer openSUSE Tumbleweed and there 60p video in Firefox plays smoothly. Maybe there are some useful command line flags for Freetube, since it's on Electron?

**Comment by artenax** [comment] 2024-09-27 03:00
If I use yt-dlp+mpv a lot, YouTube asks for proof that you're not a bot.
