### ISSUE TITLE
[Feature Request]: Manual choice for location Country

### ISSUE THREAD

**Issue by Scheisser** [FreeTubeApp/FreeTube#2519] opened 2022-08-31 06:44 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Please, emergency needed to have possibility set location Region (Country) in Settings manually for avoid regional blocking without using proxies or system-wide VPN

### Proposed Solution

Menu point "Regon" like as original YouTube

### Alternatives Considered

--

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-31 14:11
We wont implement such a feature. You have to setup a VPN, proxy or tor connection yourself to avoid this.

**Comment by ChunkyProgrammer** [comment] 2022-08-31 14:35
> We wont implement such a feature. You have to setup a VPN, proxy or tor connection yourself to avoid this.

I believe they're talking about the "Region" feature in YouTube
<img width="235" alt="image" src="https://user-images.githubusercontent.com/78101139/187704867-14afc24f-c7b9-4190-81c6-4b0831f28f89.png">

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-31 14:37
Oh thats my bad. Should we reopen this?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-08-31 14:58
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/484 https://github.com/FreeTubeApp/FreeTube/issues/1133

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-08-31 14:58 UTC
Labels: enhancement, E: new optional setting
