### ISSUE TITLE
Search Filters - Reset 

### ISSUE THREAD

**Issue by geekdiop** [FreeTubeApp/FreeTube#1894] opened 2021-11-14 21:01 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I use to filter results when I am searching something on Freetube, but the problem is when you wanna search again without filtering; you have to reset all options (that you've chosen) to the default  manually-(Most Relevant, Any time, All Types, All duration). 

**Describe the solution you'd like to see implemented**
I was thinking that If you can add a button to reset these options automatically.

**Describe alternatives you've considered**
 N/A

**Screenshots**
 N/A

**Additional context**
 N/A

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-11-15 15:20
Duplicate of #1693

**Closed** 2021-11-15 15:20 UTC
Labels: U: duplicate, enhancement
