### ISSUE TITLE
[Bug]: Being able to open an external hyperlink in FreeTube window

### ISSUE THREAD

**Issue by 7echLife** [FreeTubeApp/FreeTube#1998] opened 2022-01-09 18:53 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Go to any video that has a hyperlink that isn't YouTube. Middle click the hyperlink that is not YouTube. A new window will open with the external hyperlink opening to an external webpage on the FreeTube window.

### Expected Behavior

I expected FreeTube to open the external hyperlink in the default browser.

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.15.1 Beta

### Operating System Version

Windows 10 IoT LTSC 2021 21H2

### Installation Method (If applicable)

.exe

### Primary API used

Invidious API

### Additional Information

![image](https://user-images.githubusercontent.com/54084841/148696393-e3eff8bb-7ebb-462c-8fb1-a0689df9992e.png)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-09 18:54
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1809

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-01-09 18:54 UTC
Labels: bug, B: inconsistent behavior
