### ISSUE TITLE
[Feature Request]: Automatic Background Feed Updates

### ISSUE THREAD

**Issue by yosefario-dev** [FreeTubeApp/FreeTube#5884] opened 2024-10-17 09:33 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently, FreeTube updates the feed automatically only when a new Subscriptions window is opened. This can be inconvenient for users who frequently open multiple windows or tabs. When returning to an already open window, the feed does not refresh, which can lead to missed updates and a disjointed viewing experience. This limitation can be particularly frustrating for users who want to stay current with their subscriptions without having to manually refresh each window.

### Proposed Solution

I propose implementing automatic background feed updates for existing subscription windows. This feature would ensure that the feed refreshes periodically or when the user returns to an already open window, allowing users to see the latest content without needing to manually refresh. Additionally, this functionality could lay the groundwork for future features, such as notifications for new videos, enhancing the overall user experience.

### Alternatives Considered

...

### Issue Labels

ease of use improvement, improvement to existing feature, new optional setting

**Comment by kommunarr** [comment] 2024-10-17 13:46
Duplicate of #5140

**Closed by kommunarr** 2024-10-17 13:46 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: ease of use improvement
