### ISSUE TITLE
[Feature Request]: Integrating SponsorBlock marking and report feature

### ISSUE THREAD

**Issue by xyhbhtt** [FreeTubeApp/FreeTube#5694] opened 2024-09-12 17:32 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

SponsorBlock is integrated into Freetube, but it's only the skipping marked sponsor feature lacking the ability to mark and upload sponsor and other segments.

A screenshot of the added panel to submit a sponsor segment on a youtube video:
![image](https://github.com/user-attachments/assets/0a253701-3aae-4c47-9aa1-c7377b735455)

### Proposed Solution

Adding the option to mark and report sponsors and other sections in a playing video to create feature parity with the browser plugin of SponsorBlock.

### Alternatives Considered

no Alternatives.

### Issue Labels

improvement to existing feature

**Comment by absidue** [comment] 2024-09-12 17:58
Duplicate of #2170

Please read the comment here: https://github.com/FreeTubeApp/FreeTube/issues/2170#issuecomment-1093549872

**Closed** 2024-09-12 18:01 UTC
Labels: U: duplicate, enhancement, E: improvement existing feature
