### ISSUE TITLE
Display only latest video per subscription

### ISSUE THREAD

**Issue by stpnwf** [FreeTubeApp/FreeTube#1428] opened 2021-06-18 13:49 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I subscribe to some channels that post many videos, and some that post only occasionally, that ends up "burying" a lot of videos, and I often have to scroll to see what some subscriptions have posted.
I also want to spend less time mindlessly browsing YT.

**Describe the solution you'd like to see implemented**
I would like an option to display only the latest (or latest unwatched) video per subscription in the Subscriptions window.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-05 11:02
Duplicate of #546

**Closed** 2022-01-05 11:03 UTC
Labels: U: duplicate, enhancement
