### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shmantiko** [FreeTubeApp/FreeTube#3139] opened 2023-01-30 20:32 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [x] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I Opened the Latest Hacksmith Video. https://youtu.be/PrGaaxhLs6M
There was Spanish Dubbed audio and no way to disable it.

Youtube has a feature now for dubbed audio and it apperently automaticaly uses spanish in this cas.

### Expected Behavior

The Feature to have a selector in the app or the default being English or the Original Languge

### Issue Labels

usability issue

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux Jojo-Main 5.15.85-1-MANJARO #1 SMP PREEMPT Wed Dec 21 21:15:06 UTC 2022 x86_64 GNU/Linux

### Installation Method

AUR

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-01-30 20:33
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2419

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-01-30 20:33 UTC
Labels: bug, B: usability, B: Unofficial Download
