### ISSUE TITLE
[Feature Request]: Allow higher video resolutions

### ISSUE THREAD

**Issue by CodingMadness** [FreeTubeApp/FreeTube#5318] opened 2024-06-24 03:28 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently the maximum allowed video resolution is 1080p

### Proposed Solution

Allow using higher resolutions IF the video of course allows it aswell, like if the video creator allows higher resolutions like 1440p or 2160p and so on, currently it will always only use 1080p at max, even tho the video allows for more.

### Alternatives Considered

none.

### Issue Labels

new feature

### Additional Information

![grafik](https://github.com/FreeTubeApp/FreeTube/assets/28008874/10d14e99-88c2-4e23-830b-027c36efffcb)

**Comment by absidue** [comment] 2024-06-24 05:26
Duplicate of #2013

**Closed** 2024-06-24 05:26 UTC
Labels: enhancement, E: new feature
