### ISSUE TITLE
[Feature Request]: Cast to Chromecast similar to website/apps

### ISSUE THREAD

**Issue by ohhsodead** [FreeTubeApp/FreeTube#2881] opened 2022-11-21 02:44 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

So that 1) doesn't have to cast entire screen/page from PC to Chromecast and 2) would be an awesome feature to use, as I am lazy..

### Proposed Solution

A very similar feature to the original website/app buttons that shows the list of Chromecasts to send/connect the video

### Alternatives Considered

Maybe a plugin or an extension built-in that allows for doing this..

### Issue Labels

new feature

### Additional Information

I think there might be open source libraries that can provide the functionality for this. You can make use of DLNA to do the same thing, I believe..

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-11-21 06:40
Closing because this is a duplicate of #437 and can also be found in #539

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-11-21 06:40 UTC
Labels: enhancement, E: new feature
