### ISSUE TITLE
[Bug]: Please have installer and other files signed by publisher on Windows

### ISSUE THREAD

**Issue by GHM3434** [FreeTubeApp/FreeTube#4864] opened 2024-04-04 16:03 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

WDAC (Windows Defender Application Control) blocks installs and updates because the .exe install file is not signed by a publisher. Also when updating, it will be blocked because old-uninstaller.exe at C:\Users\username\Local\Temp\XXX.tmp\ is also not signed by a publisher.

Is it possible to have these files signed by publisher?

### Expected Behavior

Have WDAC enabled and have freetube install and update normally

### Issue Labels

accessibility issue

### FreeTube Version

0.20.0

### Operating System Version

Windows 11 23H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

Explicit rules must be added to WDAC to allow freetube to install and update without being blocked.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-04 17:46
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1363

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-04 17:46 UTC
Labels: bug, B: accessibility
