### ISSUE TITLE
[Feature Request]: user defined Font

### ISSUE THREAD

**Issue by Golddouble** [FreeTubeApp/FreeTube#3063] opened 2023-01-14 10:14 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I use the flatpack version of FreeTube v0.18.0 Beta.

My system: MX Linux 19.4 (Debian 10 based)
My system is antialiasing free and I use system-wide Arial, because this font works good without antialiasing.

1)
Problem:
It looks like FreeTube does not use Arial:
![k20230113-134502](https://user-images.githubusercontent.com/13977359/212466441-05bc2f86-2c76-4a6b-a7a4-bac15c05b206.png)

Why do I think so?
Because this is a font, that is not suitable for a antialiasing free system. This font may be good for a system that has antialiasing. But without antialiasing it looks bad as you can see in the picture.
(To see exactly what I see on my screen, please click on each of the picture, so that it will be opened in a separate tab with 100% scaling)

2)
Further:
In firefox, I have denied the use of page-specific fonts, so Firefox is only allowed to use the user defined font (Arial).
But Freetube shows me the font from the homepage I guess. Here you can see the difference between Freetube and Firefox:
![k20230114-110412](https://user-images.githubusercontent.com/13977359/212466731-63295e0f-1c7b-465b-86aa-8a89ae680e05.png)
(To see exactly what I see on my screen, please click on each of the picture, so that it will be opened in a separate tab with 100% scaling)
 
![k20230114-110458](https://user-images.githubusercontent.com/13977359/212466733-045179bd-9465-40b9-9a7c-814c12195820.png)
(To see exactly what I see on my screen, please click on each of the picture, so that it will be opened in a separate tab with 100% scaling)

### Proposed Solution

So here is the feature request:
Please allow in the freetube settings to choose my own font
-for FreeTube App
-for the youtube site
This way I would be able to choose for each of them "Arial".

### Alternatives Considered

?

### Issue Labels

visual improvement

**Comment by absidue** [comment] 2023-01-14 10:32
> for the youtube site

FreeTube gets the information from YouTube or Invidious but we have our own user interface, we don't display any part of the actual YouTube site inside FreeTube.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-01-14 10:48
Duplicate of #39

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-01-14 10:48 UTC
Labels: enhancement, E: visual improvement
