### ISSUE TITLE
[Bug]: Video Not Playing And Showing Error

### ISSUE THREAD

**Issue by exefile2** [FreeTubeApp/FreeTube#5515] opened 2024-08-02 15:05 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

while playing any video, its showing an error message.
![Screenshot (244)](https://github.com/user-attachments/assets/f2e77862-af92-48ce-9159-094c215f0851)

### Expected Behavior

the video should play...

### Issue Labels

API issue

### FreeTube Version

v0.21.2 Beta

### Operating System Version

Windows 10 pro

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.19

### Additional Information

![Screenshot (245)](https://github.com/user-attachments/assets/f93f024f-1a64-4925-9b1c-a21e98604b47)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-08-02 15:07
Duplicate of #5502

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-08-02 15:07 UTC
Labels: bug, B: API issue
