### ISSUE TITLE
Almost every video is intermittently buffering - Please review buffering and playback issues

### ISSUE THREAD

**Issue by Leza89** [FreeTubeApp/FreeTube#1868] opened 2021-11-03 05:18 UTC
**Behavior of the program**
Freetube regularly intermittently buffers: 4/5 times videos just keep buffering, while the same video (with share link copied from FreeTube) plays absolutely fine in the browser (even 1 qualitity level above FreeTube settings) on the same machine.

**Expected behavior**
Videos play as they do in a regular browser on youtube directly.

**To Reproduce**

Use FreeTube for a bit and the issue will show up; It is not consistently reproducable.

**Link to video**
This shows up irregularly – no particular video

**Environment Information (please complete the following information):**

OS: 2x Windows 7 SP1 and 1x Ubuntu 20.04
FreeTube version: v0.15.0 (2x Windows 7) and 0.13.2 (1x Ubuntu 20.04)
Primary API Used: Local API

This issue exists since Version 0.13 and has gotten worse until the current release 0.15

**Comment by toby63** [comment] 2021-11-03 16:01
Listen mate, this is simply disrespectful.

This is free software and most programmers work in their free time.

Additionally this kind of software will always have errors, because it tries to read out information from a website.

So be a bit more respectful and patient, as the programmers (also in the projects related to this one) will try to improve the software as much as they can and want.

**Comment by Leza89** [comment] 2021-11-03 18:48
> Listen mate, this is simply disrespectful.

You are absolutetly correct; I was in a really bad mood yesterday and Freetube was the final straw". This does not warrant ranting on open software, of course.
I am really grateful for Freetube and I am so sorry for my behaviour.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-11-03 19:03
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1856

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-11-03 19:03 UTC
Labels: U: doesn't follow template

**Comment by EVEarchitect** [comment] 2022-06-26 03:05
This seems to be an intentional measure taken by Freetube for whatever reason, invidious and all other other sources do not have this problem directly, only when played in Freetube.

**Comment by junglized** [comment] 2023-10-30 18:47
I can't see how original post was disrespectful? Intermitent buffering is the issue with 0.19.1 beta, FYI.

**Comment by jasonhenriquez** [comment] 2023-10-30 23:13
I'm presuming they were referring to the first iteration of the post before they edited it a few times, which didn't follow the template, provide replication info, or provide environment info. @junglized [There was an issue with YouTube as a whole yesterday](https://nitter.net/TeamYouTube/status/1718687545154761150); are you still seeing this today?
