### ISSUE TITLE
[Bug]: App Freezes 

### ISSUE THREAD

**Issue by exefile2** [FreeTubeApp/FreeTube#5404] opened 2024-07-13 17:34 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

While changing video quality to 720p, the app freezes, while the other videos play smoothly. This video is taking much time to load.
![Screenshot (234)](https://github.com/user-attachments/assets/2d82a5cf-1ab3-408e-a347-27660cfbcf2a)

### Expected Behavior

the video should play but the app freezes

### Issue Labels

causes crash

### FreeTube Version

v0.21.1 Beta

### Operating System Version

Windows 10 pro

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.19

### Nightly Build

- [x] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-15 15:04
This is normal for such a big video

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-15 15:04
also duplicate of https://github.com/FreeTubeApp/FreeTube/issues/845

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-15 15:04 UTC
Labels: bug, B: crash

**Comment by exefile2** [comment] 2024-07-19 04:46
> This is normal for such a big video

But other clients can handle these long videos but freetube can't. Should be fixed soon.
