### ISSUE TITLE
[Feature Request]: Auto update

### ISSUE THREAD

**Issue by mouarfff** [FreeTubeApp/FreeTube#2074] opened 2022-02-11 08:36 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

hello !
I have a lot of very good free software but most of them (and yours) dson't have any auto update system.
But when i do update, i take a lot of tiume to go to the site, download, install etc etc ... and more you make update (it's good), more we need to do that, and sometimes, i don't use it because that ...

### Proposed Solution

An auto update system, who donload the last version and install it ..
And u can use Chocolatey package manager ?

### Alternatives Considered

There are not alternative to this sort of functionality

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-02-11 13:38
Duplicate of #841

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-02-11 13:38 UTC
Labels: enhancement, E: new feature
