### ISSUE TITLE
[Feature Request]: Click to View/Close Recommended Videos (Up Next)

### ISSUE THREAD

**Issue by lothar-cell** [FreeTubeApp/FreeTube#4916] opened 2024-04-09 14:23 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The option to hide recommended videos (like comments) would be a great distraction-free feature, which is already implemented both by Piped and Improved YouTube plugin. Please take a look at the following screenshots:

<img width="1440" alt="Screenshot 2024-04-09 at 16 14 37" src="https://github.com/FreeTubeApp/FreeTube/assets/2356354/33e481e6-7629-4619-89b1-51673ea3b6a3">

<img width="1440" alt="319459888-dbafd7f0-4ab2-4917-9456-f5e367d1a628" src="https://github.com/FreeTubeApp/FreeTube/assets/2356354/c82df287-caa8-4501-aeac-bd9defe7881d">

### Proposed Solution

An option in the Distraction Free Settings menu, to hide recommended videos, just like with comments. Because you gotta love the choice on the spot, whether you want to be bombarded with content or not. I'm even somewhat surprised, that it is missing from Distraction Free Settings.

### Alternatives Considered

Piped.video
ImprovedTube: https://github.com/ImprovedTube/ImprovedTube

### Issue Labels

improvement to existing feature, new feature, new optional setting, visual improvement

**Comment by absidue** [comment] 2024-04-09 17:02
Any time you are required to manually do something to show information in FreeTube, it means that FreeTube would have to make extra request to fetch the information, hence why the comments are "hidden" by default (can't show something that isn't there) but the recommended videos are visible (unless you've hidden them in the distraction free settings).

So to answer your suprise at it not existing yet, it's because nobody has wanted or asked for it until now.

A setting like that would however pose questions to how the play next video functionality is supposed to work. Would you expect it to keep working when you haven't expanded that section yet or would you expect it to only trigger when the section is open?

**Comment by lothar-cell** [comment] 2024-04-09 17:09
I don't mind either, but I would assume hidden is not the same as being switched off when it comes to coding.

**Comment by absidue** [comment] 2024-04-09 17:13
It's not about hidden vs switched off in coding, it's how you want it to behave and as you have requested the feature, you have to decide how it should influence the rest of the app.

The least confusing for the user would likely be to only play the next video automatically if the recommended section is currently expanded when the video ends. That way it wouldn't be playing something unknown. If the section is collapsed it would behave the same as if you had hidden the recommended videos entirely or the video didn't have any recommended videos.

**Comment by lothar-cell** [comment] 2024-04-09 17:22
I think the user can switch off autoplay, if they find it confusing.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-09 18:45
Duplicate of https://github.com/FreeTubeApp/FreeTube/discussions/4850

> which is already implemented both by Piped and Improved YouTube plugin

This doesn't make sense for FT, our UI elements and the way they are structured is differently than those listed above. Implementing this would only confuse user.

We dont have the objective to merge all the same features like other platforms/extensions into FT. We are structured different and that's just the way it is.

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-09 18:45 UTC
Labels: enhancement, E: improvement existing feature, E: new optional setting, E: new feature

**Comment by lothar-cell** [comment] 2024-04-09 19:44
It is not about being like other platforms, it is an essential distraction free feature. Perhaps the team can decide instead of [efb4f5ff-1298-471a-8973-3d47447115dc](https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc) acting arbitrarily and rather shortsightedly in the matter?

Also it is not a duplicate, because this is a Feature Request, the other one is a discussion.

**Comment by lothar-cell** [comment] 2024-04-09 19:50
@PikachuEXE @ChunkyProgrammer @GilgusMaximus @PrestonN  what is your opinion about the matter? I honestly think it would enhance usability and sad that one person shuts it down before the team could take a look.

**Comment by absidue** [comment] 2024-04-09 19:54
@lothar-cell Do not unnecessarily mass-ping people. You were given a good reason for the issue to be closed, please don't annoy everyone else just because you can't accept a no, for a feature that is very similar to the existing setting to hide the recommended videos.
