### ISSUE TITLE
Subscribe button on playlist page

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1335] opened 2021-05-25 20:16 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
At this moment u are unable to subscribe to a channel from the playlist page. In YouTube users are able to do this.

**Describe the solution you'd like to see implemented**
Add subscribe button next to the channel icon. See screen for an example.

**Describe alternatives you've considered**
None.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/73130443/119562599-0ade0a80-bd96-11eb-945e-0dc78aed1f34.PNG)

**Additional context**
None.

**Comment by PrestonN** [comment] 2021-05-25 20:25
Gonna mark this as a duplicate of #312

**Closed by PrestonN** 2021-05-25 20:25 UTC
Labels: enhancement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-05-25 20:31
My apologies for creating this duplicate.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-06-24 14:23
@PrestonN is it the same tho? Because this is just about subscribing to the creators channel of the playlist. #312 is about only saving the playlist.
