### ISSUE TITLE
[Bug]: Incorrect Video Player Controls Formatting

### ISSUE THREAD

**Issue by Temmie19** [FreeTubeApp/FreeTube#6003] opened 2024-10-29 00:01 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When viewing a video the controls only takes up part of the allotted space, as well as a giant pause menu button shows up when hovering over the video

### Expected Behavior

The player menu takes up the correct amount of space and the pause menu is either non visible while the video is playing or is much smaller

### Issue Labels

visual bug

### FreeTube Version

V23 Beta

### Operating System Version

Manjaro Latest Build

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v22.03 Beta

### Additional Information

![image](https://github.com/user-attachments/assets/2b859312-081f-4125-a6ad-9925a5ff3ed6)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-10-29 08:58
Duplicate of #5951 and other issues. Please check for open and closed issues in the future.

**Closed** 2024-10-29 08:59 UTC
Labels: bug, B: visual

**Comment by Temmie19** [comment] 2024-10-29 13:55
@absidue I would argue it's not a duplicate of #5951 because that only handles the large pause button size. My ticket also mentions the incorrect sizing of the control bar which is not addressed in the other ticket.

![image](https://github.com/user-attachments/assets/d96bd450-208c-432e-a967-5e26cb876451)
Both on the left and right edges and underneath

**Comment by absidue** [comment] 2024-10-29 13:59
It is not incorrectly sized, the appearance of things changing in an update is not a bug. A bug is something that is broken, wanting the old player back is a feature request. Also it is already covered elsewhere, hence the "and other issues" part of my message. Having duplicate issues open helps nobody and makes it a lot harder to track issues.
