### ISSUE TITLE
[Feature Request]: Keep same video speed when watching a playlist

### ISSUE THREAD

**Issue by Anonsignup37456** [FreeTubeApp/FreeTube#4457] opened 2023-12-14 15:20 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When watching videos in a playlist at (example) 1.5x speed and the video ends and plays the next video. The next videos speed is back to 1x.

### Proposed Solution

It would be nice if all the videos in the playlist played at the speed as the one before it was playing. (This especially helps with short videos in a long playlist)

### Alternatives Considered

Maybe playlists could have a speed setting that overrides video speed if it cant be coded for each one since each video is a new link. 

### Issue Labels

ease of use improvement, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-12-14 15:53
Duplicate of #2295

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-12-14 15:53 UTC
Labels: enhancement, E: new optional setting, E: ease of use improvement
