### ISSUE TITLE
Legacy formats are not available for this video

### ISSUE THREAD

**Issue by onlineapps-cloud** [FreeTubeApp/FreeTube#6329] opened 2024-12-09 19:28 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

hi, when i want to play this [video](https://youtu.be/OiPVgAhRE6E) i get this error:
![image](https://github.com/user-attachments/assets/40c0769d-05a3-4216-8faf-6b44dee87b00)

### Expected Behavior

expect to play this video

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Linux

### Installation Method

.AppImage

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-12-09 19:35
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/6328

**Closed** 2024-12-09 19:36 UTC
Labels: bug, B: content not loading, B: API issue
