### ISSUE TITLE
Version 0.15.1 crashes when I try to play a video.

### ISSUE THREAD

**Issue by Tiltowait2** [FreeTubeApp/FreeTube#1922] opened 2021-11-28 07:33 UTC
**Behavior of the program**
Version 0.15.1 crashes when I try to play a video.

**Expected behavior**
The video should play until the end.

**To Reproduce**
Installation options: only for me, same directory as previous 0.15 version,

It will fetch my subscriptions, then when I click on a video, the video starts playing and I get the Windows box that says "FreeTube has stopped working" and "check online for a solution and close the program." The video continues playing in the background for 5-10 seconds, then stops.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	FreeTube.exe
  Application Version:	0.15.1.0
  Application Timestamp:	6189679d
  Fault Module Name:	FreeTube.exe
  Fault Module Version:	0.15.1.0
  Fault Module Timestamp:	6189679d
  Exception Code:	c0000005
  Exception Offset:	00000000004e0903
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	1033
  Additional Information 1:	51f9
  Additional Information 2:	51f99e86895ae751c0b5630fa6f601e5
  Additional Information 3:	033c
  Additional Information 4:	033c55beed45668f0c189028e0ad20fd

**Link to video**
All videos

**Screenshots**
N/A

**Environment Information (please complete the following information):**
 - OS: Windows 
 - OS Version: 8.1
 - FreeTube version: 0.15.1
 - Installation Method (If applicable): freetube-0.15.1-setup-x64.exe
 - Primary API Used: Local API

**Additional context**
I reinstall freetube-0.15.0-setup-x64.exe in the same directory and it works fine.

**Comment by rhinoduck** [comment] 2021-12-02 21:49
Most likely a duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1886.

Contrary to what the current title of the other GitHub issue reads, the issue does not seem to be limited to Windows 7; I get the crashes with 0.15.1 on Windows 8.1 too.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-02-06 21:04
closed in #1895

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-02-06 21:04 UTC
Labels: bug
