### ISSUE TITLE
Add the ability to add unviewed videos to the Queue or Tabs

### ISSUE THREAD

**Issue by Ygarr** [FreeTubeApp/FreeTube#1057] opened 2021-02-24 09:01 UTC
**Important note**
Please check other open and closed issues for a similar feature request before proposing a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Is your feature request related to a usage problem (not a bug)? Please describe.**
Please describe clear and concise of what the problem is. Ex. I'm always frustrated when 
there are several videos of candidates for viewing in notifications but no way to transfer them from browser

**Describe the solution you'd like to see implemented**
Tabs or Queue or "See later" videos

**Comment by GilgusMaximus** [comment] 2021-02-24 18:59
So these two are both already requested and planned. Therefore  I am going to close the issue as duplicate of #96 #333 #413 #519

**Closed by GilgusMaximus** 2021-02-24 18:59 UTC
Labels: enhancement
