### ISSUE TITLE
[Bug]: no comments

### ISSUE THREAD

**Issue by Unt1t13d** [FreeTubeApp/FreeTube#5899] opened 2024-10-20 10:07 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

In the FreeTube client, when I click on a video, sometimes it won't show the comments, instead it wrote "There are no comments available for this video", I have checked the video on YouTube, it does show the comments as intended.
![bug in freetube](https://github.com/user-attachments/assets/155b98b2-367f-43cb-ad24-ab83b0bfb2bf)
![bug in freetube (part 2)](https://github.com/user-attachments/assets/5173a45e-c93a-4949-b9f4-eac746f07468)
I also tried refreshing the page and although it does work, but it still happens to other videos too.
![image](https://github.com/user-attachments/assets/8d9e68c8-ac17-4359-80a2-ea2d31f86252)
Image under this text is another video that has this issue, even though it has comments on
![image](https://github.com/user-attachments/assets/1af4aa01-4b08-4e90-a4ae-22f3f91d7dbf)
image below this text is the original video on YouTube, and as you can see, it has comments on too
![image](https://github.com/user-attachments/assets/ad400c97-4aad-4d06-b34d-9af10bece4cf)
Also from my perspective, this bug seems to happen commonly in watched videos, but I don't remember seeing it happen in unwatched videos tho.

### Expected Behavior

I expected the client to have the video comments shown just like how it was supposed to show in YouTube, instead of showing "There are no comments available for this video".

### Issue Labels

content not loading

### FreeTube Version

v.0.21.3 Beta

### Operating System Version

Windows 11 Pro 23H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-20 10:25
Duplicate of #5880

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-20 10:25 UTC
Labels: bug, B: content not loading
