### ISSUE TITLE
Issues with subscriptions [bug report]

### ISSUE THREAD

**Issue by Laucha** [FreeTubeApp/FreeTube#70] opened 2018-04-04 07:34 UTC
Hi,

I am trying FreeTube since a week about now on Ubuntu. It is nice application which works well if we use it a simple player (searching and watching video, most popular list, history).
But, if we add few subscriptions, FreeTube (2.0 beta) blocks when we open it. The red point doesn't stop to loading with the subscription list in background but we can do anything: impossible to access in menu, impossible to launch any videos, impossible to search any things.
To fix it, the only way it's to stop the app and empty the file "subscriptions.db" on the folder "/.config/FreeTube/". When re-started with out any subscriptions, FreeTube works well back.

So, I can't say if it's a specific problem with Ubuntu. Perhaps!
I installed it via the .deb file available here.

**Comment by PrestonN** [comment] 2018-04-05 03:36
I believe this is a duplicate of #65.  The issue is because I forgot to remove the loading animation when the user loads a low amount of videos.  This should be fixed by subscribing to more channels.

I plan on releasing a patch this weekend that should fix the issue.  When it comes out please let me know if it gets fixed.  I'll keep this issue open in the mean time.

**Comment by Laucha** [comment] 2018-04-05 06:26
Hi,

Thank, it exactly this problem.

**Comment by Laucha** [comment] 2018-04-09 07:35
Hi,

Thank for the update.
I tested right now the 2.1 version with my subscription list, it was working like a charm.

Great application.

**Comment by Laucha** [comment] 2018-04-09 07:36
So, I close the thread.

**Closed** 2018-04-10 06:42 UTC
Labels: bug, duplicate
