### ISSUE TITLE
[Bug]: All subscribed channels show no videos

### ISSUE THREAD

**Issue by feather42** [FreeTubeApp/FreeTube#4619] opened 2024-01-29 19:29 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Start Freetube, the app refreshes the list of videos for all my subscriptions (I have 768) and comes back with a screen showing all my subscriptions under a title of channels with errors and the message "Your subscribed channels currently does not have any videos."
I get the same if I switch to another profile that has less channels on it.

I have tried this on windows 11 & Linux mint both have freetube V0.19.1beta
I was using Freetube ok this morning this just happened from lunchtime (GMT) today.

### Expected Behavior

I expected after loading the channels to refresh and a list of videos to be shown, this was working fine on Linux & Windows until lunchtime (GMT) today.

### Issue Labels

content not loading

### FreeTube Version

v0.19.1Beta

### Operating System Version

Windows 11 & Linux Mint

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.1Beta

### Additional Information

![2024-01-29 19_26_58-Subscriptions - FreeTube](https://github.com/FreeTubeApp/FreeTube/assets/127102751/f5ab867e-f2ce-4604-a173-5c91de635ec7)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by profucius** [comment] 2024-01-29 19:31
Same issue here

**Comment by rm-rf-home** [comment] 2024-01-29 19:31
same

**Comment by BluPhant** [comment] 2024-01-29 19:36
Same here, just happened.

**Comment by SirXaphoon** [comment] 2024-01-29 19:37
Same exact issue

**Comment by Woodhousemelena** [comment] 2024-01-29 19:42
I confirm this bug as described

**Comment by gelatinbomb** [comment] 2024-01-29 19:44
Same issue here

**Comment by absidue** [comment] 2024-01-29 19:46
duplicate of #4614

**Closed** 2024-01-29 19:46 UTC
Labels: bug, B: content not loading

**Comment by jibedoubleve** [comment] 2024-01-29 19:48
Not sure it'll help but here's what I found in the console
![image](https://github.com/FreeTubeApp/FreeTube/assets/2678545/056f2b44-2dfc-44e5-91d4-4fd6b3fc9170)

And when I copy paste the URL from console to browser, as expected an error 404

![image](https://github.com/FreeTubeApp/FreeTube/assets/2678545/24103d91-9c9b-4a8a-8843-1d0f84929061)
