### ISSUE TITLE
Problem with the latest windows update

### ISSUE THREAD

**Issue by ogromanas** [FreeTubeApp/FreeTube#1754] opened 2021-09-26 01:55 UTC
Hi
With the latest windows 10 insider update. Freetube stopped working. Although the program starts, there is no way to access the settings, no videos, ... the application remains "white", with all buttons available, but inaccessible. 

I have deleted the files contained in \AppData\Roaming\FreeTube in case it could be a problem with the saved configuration. It did not work.

Tested versions:
Release v0.14.0 Beta
0.14.0-nightly-1226 (portable too)

Is there any way to make a log?

Windows 10 pro 21H2 19044.1263
Screenshots: 
[https://ibb.co/YTJjYGQ](https://ibb.co/YTJjYGQ)
[https://ibb.co/YTJjYGQ](https://ibb.co/Qv6TyBR)
[https://ibb.co/YTJjYGQ](https://ibb.co/NVQXGLW)

Update: KB5005611 Windows 10 Insider RP 21H1 19043.1263 and 21H2 19044.1263
Changelog update: [https://www.tenforums.com/windows-10-news/185523-kb5005611-windows-10-insider-rp-21h1-19043-1263-21h2-19044-1263-a.html](https://www.tenforums.com/windows-10-news/185523-kb5005611-windows-10-insider-rp-21h1-19043-1263-21h2-19044-1263-a.html)

Thank you for your work and your spectacular application.

**Comment by ChunkyProgrammer** [comment] 2021-09-27 21:59
Hi, you can view the console by doing "Ctrl + Shift + i". It would be appreciated if you could do that and take a screenshot of any red errors that you see. Thanks :)

**Comment by ogromanas** [comment] 2021-09-28 14:37
No problem. Console log. 

[https://ibb.co/GpyrZfJ](https://ibb.co/GpyrZfJ)
[https://ibb.co/9cjk9jv](https://ibb.co/9cjk9jv)
[https://ibb.co/9cjk9jv](https://ibb.co/9cjk9jv)

PS: weird! When I activated the console, the buttons and settings options became accessible and functional.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-09-28 14:42
Hi @ogromanas quick tip u can just drag and drop ur screens into ur comment :)

**Comment by ogromanas** [comment] 2021-09-28 15:03
Thank you efb4f5ff-1298-471a-8973-3d47447115dc c!!!
If it comes written below, that's what I get for not reading :-D. Sorry, now I know ;-). Thanks again!

**Comment by ogromanas** [comment] 2021-09-28 15:24
Update: I have deleted again AppData\Roaming\FreeTube. I installed version 0.14.0-nightly-1229. When I started the application it worked the first time. I downloaded the subscriptions again and imported them again. 
I opened and closed the application several times. And now it seems to work normally. 
There has been no windows 10 update since I opened the issue 3 days ago.
Everything worked normally again when I opened the console the first time. Is there any other directory where there might be some settings that might be useful to figure out the bug?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-01 09:47
i'll mark this as duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1689 but wont close this yet. Possible solution is https://github.com/FreeTubeApp/FreeTube/issues/1768#issuecomment-931957408

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-03 13:35
Hi @ogromanas can u test out the RC release this should fix it https://github.com/FreeTubeApp/FreeTube/discussions/1773

**Comment by ogromanas** [comment] 2021-10-04 11:28
I will try it. Thank you!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-10-04 14:40
@ogromanas Feel free to close this issue if it fixed ur problem

**Closed** 2021-11-03 18:58 UTC
Labels: bug, U: duplicate
