### ISSUE TITLE
[Feature Request]: Adjust video player control bar.

### ISSUE THREAD

**Issue by Penguin-Guru** [FreeTubeApp/FreeTube#6165] opened 2024-11-14 16:29 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Since switching to the new video player, the player's menu bar (at the bottom of the video frame) has moved farther up into the video frame and there is a shadow effect that darkens the video both below and above that menu bar. I personally find this placement irritating for two reasons. The first is simply because it is not where I expect a video player bar to be. The second is because I often pause videos I'm watching to read text. The placement of the menu bar and the size of the shadow effect often block details I want to see. The menu bar is also a bit distracting when I'm doing something in another window, because most players hide it and the many bright buttons make the dark area of the window feel a bit cluttered.

### Proposed Solution

I'm not confident in my visual sense but I would start by keeping the buttons, seek bar, and relative placements of such the same and simply moving those items down as far as possible within the video frame. I would also reduce the shadow effect so it ends maybe five pixels above the seek bar's new placement and then adjust its other attributes as necessary so it looks good with that size.

I would also make the whole control bar fade away after six seconds or so if the cursor is outside of the video frame or if the video is in full screen mode.

### Alternatives Considered

Currently, the only way I know to view that part of a video frame while the video is paused is to save a screenshot and examine it in an image viewer. This is really inconvenient.

### Issue Labels

visual improvement

**Comment by absidue** [comment] 2024-11-14 22:00
Please check for existing issues both open and closed before opening issues, this is a duplicate of multiple other ones.

**Closed by absidue** 2024-11-14 22:00 UTC
Labels: enhancement, E: visual improvement

**Comment by Penguin-Guru** [comment] 2024-11-14 22:46
In that case, I'm sorry. I did look. These concepts are difficult to search for. I've tried terms like "bar", "menu", "control", "player", and "buttons". I just searched through all those again and I still don't see the duplicates, but I'll take your word for it.
