### ISSUE TITLE
[Bug]: A JavaScript error occurred in the main process Uncaught Exception: TypeError: Object has been destroyed

### ISSUE THREAD

**Issue by fuengfah** [FreeTubeApp/FreeTube#6338] opened 2024-12-10 03:16 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Double click to open application
2. Error Message shown "Error
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Object has been destroyed
at App.<anonymous>
(C:(Users)Fuengfah)AppDatal Local(Programs(FreeTubelresources)app.asar)(dist(ma..:99551)
at App.emit (node:events:518:28)"
[app.asar.zip](https://github.com/user-attachments/files/18071005/app.asar.zip)

### Expected Behavior

This happens just right after double click to open application

### Issue Labels

causes crash

### FreeTube Version

0.22.0-nightly-5265

### Operating System Version

Windows 10 22H2 19045.4412

### Installation Method

.zip

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

-

### Additional Information

-

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-12-10 05:22
Duplicate of #4762

**Closed** 2024-12-10 05:22 UTC
Labels: bug, B: crash
