### ISSUE TITLE
[Bug]: Fullscreening turns video to white on Arch using Hyprland.

### ISSUE THREAD

**Issue by MillionsToOne** [FreeTubeApp/FreeTube#6015] opened 2024-10-29 15:24 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Install Arch or any Arch based recent distro with Hyprland.
2. Play a video.
3. Profit.

### Expected Behavior

You should be able to play videos in fullscreen without image going white.

### Issue Labels

feature stopped working, usability issue, visual bug

### FreeTube Version

5a4cd98

### Operating System Version

Linux arch 6.11.5-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Tue, 22 Oct 2024 18:31:33 +0000 x86_64 GNU/Linux

### Installation Method

.pacman

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

v0.21.3

### Additional Information

![swappy-20241029-171655](https://github.com/user-attachments/assets/7a8b20ed-2050-40d4-8f92-a53c57c50d45)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-10-29 15:54
Duplicate of #5979

**Closed** 2024-10-29 15:54 UTC
Labels: bug, U: duplicate, B: visual, B: usability, B: feature stopped working
