### ISSUE TITLE
[Feature Request]: Play Button Keeps a lot of Space on the Screen

### ISSUE THREAD

**Issue by Tahinli** [FreeTubeApp/FreeTube#5993] opened 2024-10-28 16:26 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hi,

Thanks for new player, it works great. 
For user experience the big bold play button keeps a lot of space in the screen. Because of this it's hard to watch couple seconds of the video when you stop and start again even when you move mouse unintentionally. It stays too much and it's unnecessarily big.

### Proposed Solution

You can consider to remove main play button since there is another button on the bottom left corner, but still keep the functionality of clicking video to stop and play again. I mean don't force user to click bottom left corner to start and stop video but still give visually feedback via the bottom left button.

Thanks a lot.

### Alternatives Considered

I don't know

### Issue Labels

visual improvement

**Comment by Tahinli** [comment] 2024-10-28 16:39
Oh sorry, I saw there is a option to disable this main play button. My mistake.
I think it can be opt out default, since new users may feel uncomfortable and may not think about there must be setting for it to disable.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-10-28 16:49
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/5993

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-10-28 16:49 UTC
Labels: enhancement, E: visual improvement

**Comment by thingsiplay** [comment] 2024-10-28 17:58
> duplicate of #5993

This reference points to this issue itself.

**Comment by tuxayo** [comment] 2024-10-29 05:26
Does this issue still make sense for the question of having a smaller button and have it fade away faster?
For the best default experience for most people.
