### ISSUE TITLE
[Bug]: Librem 5 Freetube Video Thumbnails Blue

### ISSUE THREAD

**Issue by CaptainMorgan12** [FreeTubeApp/FreeTube#5420] opened 2024-07-15 14:55 UTC
![Freetube](https://github.com/user-attachments/assets/107b12a2-4d38-4ec8-9374-28d07178170a)
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. view list of subscriptions
2. observe the video thumbnails are blue tinted
3. videos play normally and once the video is selected from the subscription list the blue tint goes away

### Expected Behavior

Do not show blue tinting.

### Issue Labels

accessibility issue, visual bug

### FreeTube Version

0.21.1

### Operating System Version

postnarketos edge, linux, arm64, Vivante GC7000 gpu, mesa 24.1.2-r1, wayland

### Installation Method

Flathub

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

Unknown

### Additional Information

It works on my Desktop with am64 Ubuntu 23.10, amdgpu graphics

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-15 14:59
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4890

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-07-15 14:59 UTC
Labels: bug, B: visual, B: accessibility

**Comment by CaptainMorgan12** [comment] 2024-07-15 16:00
The visual artifact appears a slightly different issue then #4890 which shows as more of a flickering when playing a video, my videos play fine.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-07-18 14:40
This seems more an issue with your phone than with FT it self. I would suggest updating the drivers, check color profiles
