### ISSUE TITLE
[Bug]: v0.21.3 Beta: The Shorts on the channel tab doesn't want to show video content, it has "This channel does not have currently have shorts" message instead 

### ISSUE THREAD

**Issue by Bennguyen2** [FreeTubeApp/FreeTube#5729] opened 2024-09-22 19:20 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When going to channel's Shorts tab section, the video content isn't there. Instead, it has "This channel does not have currently have shorts" as shown in the video below. Clicking "Fetch more results" doesn't work either. This effects every channel that has the Shorts tab. Switching to Invidious API and back to Local API doesn't do anything.

https://github.com/user-attachments/assets/822c51d3-d668-45ab-bb49-40b3c95ad0b3

### Expected Behavior

Clicking channel's Shorts tab should show the video content (like the one below but this is from the browser. This is how the Shorts content should show up on FreeTube) unless the channel does not have one.

![Screenshot from 2024-09-22 14-55-27](https://github.com/user-attachments/assets/16d338e9-2de0-45aa-b6d4-f1336ad466aa)

### Issue Labels

content not loading

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Linux Mint 22

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-09-22 19:48
Duplicate of #5685

**Closed** 2024-09-22 19:48 UTC
Labels: bug, B: content not loading
