### ISSUE TITLE
[Bug]: The window size is getting bigger and bigger for each launch

### ISSUE THREAD

**Issue by shawhu** [FreeTubeApp/FreeTube#6029] opened 2024-10-30 00:25 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I have a 2 monitors setup with windows 10.
Both 4k but the left one is on 175% scale. The right one is on 150%.

Now. with this setting, you can see the issue by starting the FreeTube and close it and start it again. The size of the window will be larger and larger for each time you open it.

when I set both my monitors to have the same scale value the issue goes away. for example, if I set both my monitors to 150% then it's working.

### Expected Behavior

the size of the window shouldn't be getting bigger and bigger

### Issue Labels

usability issue

### FreeTube Version

v0.21.3 Beta

### Operating System Version

Windows 10 Pro, version: 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Tech-How** [comment] 2024-11-01 12:29
Oddly, this never happens for me on Windows, but happens exactly as you described on my Linux computer, which is running Kubuntu with the Flatpak installation method. Definitely seems like an issue with the program. I haven't tested the latest beta on Windows yet, did this just start happening on Windows or has it been happening for a while?

**Comment by shawhu** [comment] 2024-11-01 12:42
> Oddly, this never happens for me on Windows, but happens exactly as you described on my Linux computer, which is running Kubuntu with the Flatpak installation method. Definitely seems like an issue with the program. I haven't tested the latest beta on Windows yet, did this just start happening on Windows or has it been happening for a while?

it's been a while, I've tried the previous stable version and the current stable version...both have the same problem.
it's definitely something to do with multiple monitors and with different scales.

for example, it works on my main monitor, but not on my secondary one. the problem only shows up on my 2nd monitor (with a different scale than my main monitor)...

and, btw, another app has the same issue, postman, which is based on electron too.......

**Comment by Tech-How** [comment] 2024-11-01 13:05
Actually yeah, that does remind me I do have scaling enabled on Kubuntu but not on Windows. That's likely the culprit.

**Comment by tangomike99** [comment] 2024-11-21 14:54
This issue is a duplicate of the following:
https://github.com/FreeTubeApp/FreeTube/issues/5346

**Comment by absidue** [comment] 2024-12-01 12:45
Duplicate of #5346

**Closed by absidue** 2024-12-01 12:45 UTC
Labels: bug, B: usability
