### ISSUE TITLE
[Feature Request]: Font Size too small

### ISSUE THREAD

**Issue by ACR-Jeff** [FreeTubeApp/FreeTube#5351] opened 2024-06-30 19:27 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Font size in video comments is too small, Even with reading glasses it can be tough to read, With reading glasses it's a bit better but having to put my face close up to the monitor is a little ridiculous.

### Proposed Solution

An option to adjust the font size in video comments

### Alternatives Considered

An option to adjust the font size in video comments

### Issue Labels

new feature, visual improvement

**Comment by kommunarr** [comment] 2024-06-30 19:52
In case this helps, you can increase the UI scale in Theme Settings or use <kbd>Ctrl</kbd>+<kbd>+</kbd>. We're currently using the same font size for comments as YT (14px), so not saying an increase isn't on the table, but it would have to be evaluated with regards to its effect on the comments section UX design.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-06-30 19:55
duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4665

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-06-30 19:55 UTC
Labels: enhancement, E: visual improvement, E: new feature

**Comment by ACR-Jeff** [comment] 2024-06-30 20:11
> In case this helps, you can increase the UI scale in Theme Settings or use Ctrl++. We're currently using the same font size for comments as YT (14px), so not saying an increase isn't on the table, but it would have to be evaluated with regards to its effect on the comments section UX design.

That was the first steps I made for adjustments, Yet doing so adjusts all of the UI making everything other then just the text extra large or larger than needed, It would be great to have an option to adjust the smaller text, Thank you
