### ISSUE TITLE
[Feature Request]: Make the pause start image replaceable, smaller, or transparent

### ISSUE THREAD

**Issue by JackSparrow006** [FreeTubeApp/FreeTube#6349] opened 2024-12-11 04:54 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When watching on Freetube as wanting to see details, I usually pause the video. but then there is a huge circular paused button showing up that block 20% of the screen.

### Proposed Solution

Having the ability to remove, replace, make smaller, or make transparent in the setting menu.

### Alternatives Considered

Having it default to not there and adding a option to add it is also great :)

### Issue Labels

ease of use improvement, improvement to existing feature, visual improvement

**Comment by ArthurKun21** [comment] 2024-12-11 06:54
You could try beta and see that it is much smaller now

link to the builds -> https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml

select the latest one with green and then select your package with your OS

![image](https://github.com/user-attachments/assets/eed9e32a-dd09-4054-81f0-586714376c94)

or turn off the play button `Display Play Button In Video Player`

![image](https://github.com/user-attachments/assets/8036f8de-de1d-48e9-91b8-46461758995e)

**Comment by absidue** [comment] 2024-12-11 07:14
Closing as a duplicate of many other issues and because the provided comment tells you everything you need to know, please check both open and closed issues next time before opening an issue.

**Closed** 2024-12-11 07:14 UTC
Labels: enhancement, E: improvement existing feature, E: visual improvement, E: ease of use improvement

**Comment by JackSparrow006** [comment] 2024-12-11 17:03
Thank you, I was being dumb, this helps me a ton, thanks man :)
