### ISSUE TITLE
[Bug]: Picture in Picture is not in the foreground

### ISSUE THREAD

**Issue by kgorol** [FreeTubeApp/FreeTube#2024] opened 2022-01-24 06:16 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

1. Open video
2. Toggle PiP
3. PiP opens, but video can be obscured by other windows.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/34159482/150731238-6c7800c9-2bdb-4213-95ad-601fb37879c6.png">

### Expected Behavior

Video should be all the time in the foreground.

### Issue Labels

usability issue

### FreeTube Version

v0.15.1

### Operating System Version

Manjaro KDE

### Installation Method (If applicable)

other

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-24 07:49
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1142

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-01-24 07:49 UTC
Labels: bug, B: usability
