### ISSUE TITLE
[Bug]: Video freezes when continuing after very long pauze

### ISSUE THREAD

**Issue by Gevaarlijk** [FreeTubeApp/FreeTube#4330] opened 2023-11-13 10:40 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When I play a video, pause and then after a long time (not sure exactly what the cutoff is but it is hours) continue to play it it will then play out whatever was loaded in the buffer already and then freeze. The only thing I can do is restart the video. This is kind of annoying as I often pause for long times. Is there a reason for this behavior? 

### Expected Behavior

To have the video continue where I paused and finish playing even if I paused it for 2 days either by default or by having a setting to allows for long pausing like this.  

### Issue Labels

content not loading

### FreeTube Version

All versions

### Operating System Version

Windows 11

### Installation Method

Portable

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-13 10:44
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4160

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-11-13 10:44 UTC
Labels: bug, B: content not loading

**Comment by Gevaarlijk** [comment] 2023-11-13 10:49
To be sure; it looks similar and #4160 and my bug report may very well have the same cause but I'm not talking about a video playing for 6 hours. I have never done that. I will play 15 minutes of 30 minute video and then continue the next day.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-11-13 11:03
Root cause is still the same

the streaming URLs expiring after 6 hours.
