### ISSUE TITLE
Following a specific playlist on a channel

### ISSUE THREAD

**Issue by sugguy** [FreeTubeApp/FreeTube#1167] opened 2021-04-05 17:54 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Some big channels have a good content on a specific playlist only. so when you subscribe to that channel your subscription feed gets flooded with all the other videos that do not interest you.

**Describe the solution you'd like to see implemented**
I would like to be able to follow what is added to a specific playlist on a Youtube channel and see it on the the regular subscriptions feed. 

**Describe alternatives you've considered**

**Screenshots**

**Additional context**

**Comment by GilgusMaximus** [comment] 2021-04-06 18:31
Closes because it is a duplicate of #312

**Closed by GilgusMaximus** 2021-04-06 18:31 UTC
Labels: enhancement
