### ISSUE TITLE
"Fetch more results" always gets the same results again

### ISSUE THREAD

**Issue by DasJott** [FreeTubeApp/FreeTube#813] opened 2020-11-27 09:02 UTC
**Behavior of the program**
If you search for something, you get a bunch of results. There's a button at the bottom that says: "Fetch more results". By pressing this, it loads the same results again and adds them to them to the view.

**Expected behavior**
I would expect more (different) results being fetched and added. Not a duplicate first page.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Search for something
2. Click on "Fetch more results" at the bottom.
3. See that the same results are added (again).

**Environment Information (please complete the following information):**
 - OS: Manjaro Linux
 - FreeTube version: v0.9.2 Beta
 - AUR package
 - Primary API Used: Invidious API (Local doesn't work)

**Comment by PrestonN** [comment] 2020-11-28 16:46
This is a duplicate of #662.  It's an issue with Invidious at the moment, which I am unable to fix on my end.

**Closed by PrestonN** 2020-11-28 16:46 UTC
Labels: bug
