### ISSUE TITLE
[Bug]: Website Certificate Expired

### ISSUE THREAD

**Issue by cachandlerdev** [FreeTubeApp/FreeTube#2245] opened 2022-05-16 21:46 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

When visiting the [freetubeapp.io/](https://freetubeapp.io/) website, the browser gives a warning that the certificate is no longer valid.

### Expected Behavior

The website's certificate would be valid.

### Issue Labels

API issue

### FreeTube Version

(This is a website bug, so the version doesn't matter)

### Operating System Version

(This is a website bug, so the OS doesn't matter)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-05-16 22:05
duplicate of https://github.com/FreeTubeApp/FreeTubeApp.io/issues/16

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-05-16 22:05 UTC
Labels: bug, B: API issue
