### ISSUE TITLE
[Feature Request]: Pin a playlist to the sidebar

### ISSUE THREAD

**Issue by redactedscribe** [FreeTubeApp/FreeTube#4861] opened 2024-04-04 12:58 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

With playlists now being a thing in v0.20, to view our "Saved Videos", we must first click the playlists sidebar button, and then open the Favorites playlist. This is an additional click each time I just want to see my "watch it later" videos (which is what saving a video used to mean to me) compared to v0.19.

### Proposed Solution

If we could pin playlists to the sidebar, it would effectively bring back being able to click the the "Saved Videos" button to immediately reveal the list. The benefit of being able to pin playlists is that any playlists could also be pinned if you want immediate access to any others other than Favorites.

### Alternatives Considered

Get used to clicking the sidebar, locating and selecting the Favorites playlists out of the others which could exist, to view the videos I wish to watch later.

### Issue Labels

ease of use improvement, new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2024-04-04 13:04
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/4594

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2024-04-04 13:05 UTC
Labels: enhancement, E: ease of use improvement, E: new feature
