### ISSUE TITLE
Right clicking at the bottom of the player adds a scrollbar to the player

### ISSUE THREAD

**Issue by NomadVibes88** [FreeTubeApp/FreeTube#6409] opened 2024-12-18 10:19 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open any video.
2. Right-click at the bottom of the player
3. A scrollbar will appear on the right side of the player

### Expected Behavior

The scrollbar shouldn't appear

### Issue Labels

inconsistent behavior, visual bug

### FreeTube Version

v0.22.1 Beta

### Operating System Version

Windows 11 x64

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

![2024-12-18 16_14_02-Viewer sent me a game  I fainted  - FreeTube](https://github.com/user-attachments/assets/50451b7e-02e1-4f20-adcf-9865e5108f25)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment] 2024-12-18 10:51
Duplicate of #6006

**Closed** 2024-12-18 10:51 UTC
Labels: bug, B: visual, B: inconsistent behavior
