### ISSUE TITLE
[Feature Request]: Channel blocklist

### ISSUE THREAD

**Issue by GreaterJoe** [FreeTubeApp/FreeTube#2304] opened 2022-06-09 21:30 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Youtube and Freetube both have several ways of suggesting videos chosen by some manner of relevancy algorithm to the user. A user might not find videos by a particular channel at all relevant to their interest, especially when SEO can break any automated curation method.

### Proposed Solution

Allow users the ability to block channels of their choosing, preferably from the triple-dot menu of a channel's suggested video. Blocked channels would not have videos suggested to the user in any way. This would clear up space for material more relevant to the user. It'd also allow superior curation of videos over Youtube's, as the site will allow you to click a few buttons to say "I do not like this channel" and will then recommend it anyway 5 minutes later.

### Alternatives Considered

A blocklist of terms might also work, especially if that list is cross-referenced with a video's channel name.

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-06-09 21:56
Duplicate of #1070, #2087

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-06-09 21:56 UTC
Labels: enhancement, E: visual improvement
