### ISSUE TITLE
[Feature Request] Optional Sponsorblock integration

### ISSUE THREAD

**Issue by MuffinLover42** [FreeTubeApp/FreeTube#913] opened 2021-01-05 09:21 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
One of the features I miss most from YouTube (though not from Youtube directly) is the [SponsorBlock extension](https://github.com/ajayyy/SponsorBlock), that blocks Sponsors and silent music parts via crowdsourcing.

**Describe the solution you'd like to see implemented**
SponsorBlocks's database is public, so what I'd recommend is to make it so that it skips the parts in a video that are sponsors according to the database. This could be an option that's toggleable in the settings.

**Describe alternatives you've considered**
The other way I see is doing this indirectly by making it possible to install extensions.

**Screenshots**
None.

**Additional context**
None.

**Comment by GilgusMaximus** [comment] 2021-01-08 08:26
Closing this because it is a duplicate of #798

**Closed by GilgusMaximus** 2021-01-08 08:26 UTC
Labels: enhancement
