### ISSUE TITLE
[Bug]: Title is weirdly spaced

### ISSUE THREAD

**Issue by maplepy** [FreeTubeApp/FreeTube#3277] opened 2023-03-09 20:41 UTC
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open a video
2. Notice a weird title

### Expected Behavior

Title is properly formatted without extreme spacing between each word

### Issue Labels

feature stopped working

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux 6.2.2-arch1-1

### Installation Method

AUR

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

2 versions ago I think was working fine, not sure

### Additional Information

![image](https://user-images.githubusercontent.com/28269333/224151990-8c4b4ae4-37a3-46e9-8b79-fbd9288c7d52.png)

See the weird title 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-03-10 08:33
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2782

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2023-03-10 08:33 UTC
Labels: bug, B: feature stopped working, B: Unofficial Download

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-03-14 19:23
It's ok we understand :)
