### ISSUE TITLE
subscription containers

### ISSUE THREAD

**Issue by EmlynM** [FreeTubeApp/FreeTube#159] opened 2018-09-15 11:05 UTC
This would work how different accounts on YouTube works, you have a folder and you can add subscriptions into the folder and see all the videos from the channels in the folder.

**Comment by PrestonN** [comment] 2018-09-17 15:00
Hey there!  This is a duplicate of #86 so I will close this to try and keep the open issues clean.  It's on the list though :)

**Closed by PrestonN** 2018-09-17 15:00 UTC
