### ISSUE TITLE
[Feature Request]: Add capability for users to upload custom profile icons.

### ISSUE THREAD

**Issue by haydenheroux** [FreeTubeApp/FreeTube#2014] opened 2022-01-16 19:38 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The current profile icon system involves black text set on a colored background. However, there are few background colors which match well with the black text, and it is difficult to differentiate some profiles from others when they have the same background colors. While the placement of the profile icon is congruent to placement on YouTube, the readability of FreeTube's profile icons are remarkably worse.  

### Proposed Solution

The ability to upload an image of any size, crop the selected image to a square section, and use the cropped image within the profile icon area would increase the readability of each profile, as well as adding personalization to each. 

### Alternatives Considered

Although the ability to upload full images would be preferable, increasing the customizability of the profile menu can be accomplished in other ways. For example, the ability to change to colors of the letter in the profile image would increase the readability for certain color combinations. The ability to select any background colors may also prove beneficial, since most of the current colors may not create the most appealing combinations. 

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by haydenheroux** [comment] 2022-01-16 19:40
My potential solution of using a custom background color had already been implented, however it would be beneficial to make this option more prominent, as I did not notice the option in the profile creation menu.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-16 20:07
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/1979

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-01-16 20:07 UTC
Labels: enhancement, E: improvement existing feature, E: ease of use improvement
