### ISSUE TITLE
Since 0.14.0 Beta, Media control button no longer works

### ISSUE THREAD

**Issue by merspieler** [FreeTubeApp/FreeTube#1664] opened 2021-09-07 09:26 UTC
**Behavior of the program**
While a video is playing, the media control buttons on the keyboard are no longer able to pause/play the video

**Expected behavior**
The video can be paused/played with the media control buttons on the keyboard

**To Reproduce**
1. Open any video
2. Use the media control pause/play button to pause the running video

**Environment Information (please complete the following information):**
 - OS: Debian
 - OS Version: Bookworm (Testing)
 - FreeTube version: 0.14.0 beta
 - Installation Method (If applicable): .deb
 - Primary API Used: Local API

**Additional context**
Before the update to 0.14.0 beta it worked.

**Comment by cihlarma** [comment] 2021-09-16 10:51
I can confirm this happens on my end too. Release 0.14.0 doesn't seem to expose an MPRIS interface like previous versions did (downgraded to 0.13.2 on the same system to check), there aren't any media controls in the notification centre in GNOME or Phosh.

**Comment by jasonhenriquez** [comment] 2021-09-19 05:14
Hello, [can you try using this nightly build](https://github.com/FreeTubeApp/FreeTube/actions/runs/1215943137) and share whether the issue still persists?

**Comment by merspieler** [comment] 2021-09-19 08:35
Works here, thanks

**Comment by cihlarma** [comment] 2021-09-19 12:45
Likewise, cheers!

**Comment by cihlarma** [comment] 2021-10-20 12:54
Could this issue be re-opened? I'm using 0.15.0 and the issue is present here too (despite it being fixed in the nightly build linked by @jasonhenriquez earlier).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-11-10 16:16
Fixed in https://github.com/FreeTubeApp/FreeTube/pull/1764

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2021-11-10 16:16 UTC
Labels: bug
