### ISSUE TITLE
[Feature Request]: Open videos in different tabs within a single Freetube window

### ISSUE THREAD

**Issue by collector-ynh** [FreeTubeApp/FreeTube#3177] opened 2023-02-09 18:47 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The opening of videos in several windows is problematic! Browsers have abandoned this mode of operation for a very long time. Managing several Freetube windows for each video becomes quickly cumbersome!

### Proposed Solution

Allow the possibility of opening videos in different tabs within a single Freetube window, so that we can switch from one tab to another to access the videos.

### Alternatives Considered

For now, I bookmark the videos and open them one by one because of the lack of a FreeTube tab manager!

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-02-09 19:22
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/333

**Closed** 2023-02-09 19:22 UTC
Labels: enhancement, E: new feature
