### ISSUE TITLE
video playback

### ISSUE THREAD

**Issue by senolfndk** [FreeTubeApp/FreeTube#1449] opened 2021-06-25 09:53 UTC
**README: Before You Submit Your Issue**
- Please check other open and closed issues for a similar bug before reporting a new one.
- Make sure you are on the latest release of FreeTube before submitting an issue.
- Remove this notice before posting.

**Behavior of the program**
Please write a clear and concise description of what the bug is.

**Expected behavior**
Please describe clear and concise what you expected to happen.

**To Reproduce**
Please add all steps to reproduce the behavior:

**Link to video**
If you refer to a problem which occurs within a specific video, or a range of videos, please link at least one here.

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.

**Environment Information (please complete the following information):**
 - OS: [e.g. Windows, Mac, Ubuntu, Fedora, Arch, etc.]
 - OS Version: [e.g. Windows 10, Ubuntu 20.04]
 - FreeTube version: [e.g. 0.9.0, Nightly build?]
 - Installation Method (If applicable): [e.g. Portable, .exe, .deb, .AppImage, FlatHub]
 - Primary API Used: [Local API, Invidious API]

**Additional context**
![SharedScreenshot](https://user-images.githubusercontent.com/52818836/123406997-28300f80-d5b4-11eb-8962-2f741fa01ab4.jpg)

**Comment by senolfndk** [comment] 2021-06-25 10:00
https://user-images.githubusercontent.com/52818836/123408124-5530f200-d5b5-11eb-92ea-e48e2c3941de.mp4

:(

**Comment by senolfndk** [comment] 2021-06-25 10:03
https://user-images.githubusercontent.com/52818836/123408397-a3de8c00-d5b5-11eb-811e-5f3c41af5951.mp4

☹

**Comment by StoppingBuck** [comment] 2021-06-25 10:26
This is a duplicate of #1438

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-06-27 02:09
Hotfix update is available to download:

https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.13.2-beta

https://freetubeapp.io/#download

This should resolve this issue.

**Comment by senolfndk** [comment] 2021-06-28 07:03
ok

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: ***@***.***>
Gönderilme: 27 Haziran 2021 Pazar 05:09
Kime: ***@***.***>
Bilgi: şenol ***@***.***>; ***@***.***>
Konu: Re: [FreeTubeApp/FreeTube] video playback (#1449)


Hotfix update is available to download:

https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.13.2-beta

https://freetubeapp.io/#download

This should resolve this issue.

**Closed** 2021-07-05 10:10 UTC
Labels: bug
