### ISSUE TITLE
[Feature Request]: Ability to hide videos from the entire app

### ISSUE THREAD

**Issue by elesto** [FreeTubeApp/FreeTube#2022] opened 2022-01-24 01:04 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

If we add a way to hide videos from the entire app (and I mean entire app, subscriptions, trending, most popular) We will be able to implement many specific hiding features such as:

1. Hiding channels by name (most important for me)
2. Hiding shorts
3. Hiding videos by title regex

### Proposed Solution

?

### Alternatives Considered

?

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-01-24 07:45
Duplicate of #1070, https://github.com/FreeTubeApp/FreeTube/issues/1577

**Closed by efb4f5ff-1298-471a-8973-3d47447115dc** 2022-01-24 07:45 UTC
Labels: enhancement, E: visual improvement
