### ISSUE TITLE
[Feature Request] portable Data Location for portable(.zip) version of FreeTube

### ISSUE THREAD

**Issue by ag10yen** [FreeTubeApp/FreeTube#1866] opened 2021-11-02 23:07 UTC
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I am using the portable version of FreeTube.
I want to be able to have the Data Location be in a folder within the same directory as the program instead of %APPDATA%\FreeTube (on Windows). This would make it easier to back up Subscriptions/etc. to move to another computer or when reinstalling Windows(especially for us guys that avoid saving anything to the system partition itself).

**Describe the solution you'd like to see implemented**
A simple option to optionally save all user data to a folder within the program directory instead of %APPDATA%\FreeTube

**Describe alternatives you've considered**
n/a

**Screenshots**
n/a

**Additional context**
I use portable applications whenever possible, for, among other reasons, specifically to avoid having data I need saved to anything chained into the Windows User Account system. If my system drive ever fries itself, I like to have most of my data saved to an additional hard drive(which is where I "install" all of my portable applications). Some portable applications(including FreeTube), save user data to \%APPDATA%\ instead of a directory within the program directory itself, and I think this is bad.

**Comment by ChunkyProgrammer** [comment] 2021-11-03 04:34
Duplicate of #746

**Closed by ChunkyProgrammer** 2021-11-03 04:34 UTC
Labels: U: duplicate, enhancement
